'use strict';
const measures=require('./analysis-model-measures'),{fail,hash}=measures;
function scope(core,ctx,actor){core.scope(ctx,actor);core.resolver.assertCapability(ctx,actor,'analysis:reports');core.resolver.assertCapability(ctx,actor,'analysis:events');}
function positive(value){return /^[1-9][0-9]*$/.test(String(value))&&Number.isSafeInteger(Number(value));}
function compute(core,platform,ctx,actor,id,revision){scope(core,ctx,actor);const row=core.get(ctx,actor,'analytic_models',id);if(!positive(revision)||row.revision!==Number(revision))fail('analysis_model_revision_conflict','Kies de actuele modelrevisie',409);if(row.status==='ARCHIVED'||row.deleted_at)fail('analysis_model_archived','Dit model is gearchiveerd',409);if(row.model_version!==1)fail('analysis_model_version_unsupported','Deze modelversie is niet beschikbaar',409);const def=measures.definition(row.model_definition),observedTo=new Date(Math.min(Date.parse(def.to),Date.now())).toISOString();if(Date.parse(def.from)>=Date.parse(observedTo))fail('analysis_model_period_unobserved','De gekozen periode is nog niet waargenomen');const fields=[...new Set([...def.group_by,...(def.measure.kind==='COUNT'?[]:def.measure.kind==='SUM_CENTS'?[def.measure.field,'currency']:[def.measure.field])])],facts=[];
 const projection=platform.scanEventsForProjection(ctx,actor,{event_names:def.event_names,from:def.from,to:observedTo,filters:def.filters,fields},event=>facts.push(event)),result=measures.measure(def,facts);result.excluded_invalid_records+=projection.invalid_visible_timestamp_count;if(result.excluded_invalid_records)result.value=null;const reference={id:row.id,revision:row.revision,title:row.title,model_version:row.model_version,definition_fingerprint:hash(def)},queryFingerprint=hash({ctx,actor_id:actor.id,reference,source_fingerprint:result.source_fingerprint,invalid:result.excluded_invalid_records});return {result,facts,reference,queryFingerprint,observedTo};}
function page(input,allowed){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!allowed.includes(k))||input.offset!==undefined&&(!Number.isSafeInteger(Number(input.offset))||Number(input.offset)<0)||input.limit!==undefined&&(!positive(input.limit)||Number(input.limit)>100))fail('analysis_model_query_invalid','Kies een geldige modelpagina');return {offset:Number(input.offset||0),limit:Number(input.limit||50)};}
function query(core,platform,ctx,actor,id,input){const {offset,limit}=page(input,['expected_revision','offset','limit']),{result,reference,queryFingerprint,observedTo}=compute(core,platform,ctx,actor,id,input.expected_revision),{supporting_records,...summary}=result;return {...summary,items:result.items.slice(offset,offset+limit),offset,limit,next_offset:offset+limit<result.items.length?offset+limit:null,definition_reference:reference,query_fingerprint:queryFingerprint,observed_to:observedTo,period_complete:observedTo===result.definition.to,supporting_records:supporting_records.slice(0,100),supporting_record_count:supporting_records.length,supporting_records_truncated:supporting_records.length>100,source_records_modified:false,saved_result:false};}
function drilldown(core,platform,ctx,actor,id,input){const {offset,limit}=page(input,['expected_revision','query_fingerprint','group_id','offset','limit']);if(typeof input.query_fingerprint!=='string'||!/^[a-f0-9]{64}$/.test(input.query_fingerprint)||typeof input.group_id!=='string'||!/^[a-f0-9]{64}$/.test(input.group_id))fail('analysis_model_drilldown_invalid','Kies een exacte berekende groep en bronvingerafdruk');const {result,facts,reference,queryFingerprint}=compute(core,platform,ctx,actor,id,input.expected_revision);if(queryFingerprint!==input.query_fingerprint)fail('analysis_model_sources_changed','De toegankelijke brongegevens zijn gewijzigd; bereken het model opnieuw',409);const group=result.items.find(g=>g.id===input.group_id);if(!group)fail('analysis_model_group_missing','Deze groep hoort niet bij het actuele modelresultaat',404);const evidence=result.supporting_records.filter(e=>e.group_id===group.id),lookup=new Map(facts.map(f=>[f.event_id,f]));return {items:evidence.slice(offset,offset+limit).map(e=>({...e,projected_fields:lookup.get(e.event_id)})),total:evidence.length,offset,limit,next_offset:offset+limit<evidence.length?offset+limit:null,group,definition_reference:reference,query_fingerprint:queryFingerprint,current_query_revalidated:true,source_records_modified:false,saved_result:false};}
module.exports={scope,query,drilldown,compute};
