'use strict';
const crypto=require('node:crypto');
const fail=(code,message,statusCode=422)=>{throw Object.assign(Error(message),{code,statusCode});};
// Supported RFC 5322 dot-atom Message-IDs. Obsolete syntax remains unavailable;
// identifiers are case-sensitive and are never treated as verified identities.
function validId(value){if(typeof value!=='string'||value.length>254||!/^<[^<>\s]+@[^<>\s]+>$/.test(value))return false;const text=value.slice(1,-1),at=text.indexOf('@');if(at!==text.lastIndexOf('@'))return false;const atom=/^[A-Za-z0-9!#$%&'*+\-/=?^_`{|}~]+(?:\.[A-Za-z0-9!#$%&'*+\-/=?^_`{|}~]+)*$/;return atom.test(text.slice(0,at))&&(atom.test(text.slice(at+1))||/^\[[\x21-\x5a\x5e-\x7e]+\]$/.test(text.slice(at+1)));}
function headerState(row){const refs=row.references??[],reply=row.in_reply_to??[];if(row.thread_headers_available===false||row.internet_message_id!=null&&!validId(row.internet_message_id)||!Array.isArray(refs)||!Array.isArray(reply)||refs.length>100||reply.length>100||[...refs,...reply].some(value=>!validId(value)))return {available:false,message_id:null,references:[],in_reply_to:[]};return {available:true,message_id:row.internet_message_id||null,references:refs,in_reply_to:reply};}
function replyHeaders(source){const state=headerState(source);if(!state.available)return {available:false,reason:'SOURCE_THREAD_HEADERS_UNAVAILABLE',in_reply_to:[],references:[]};const refs=[...(state.references.length?state.references:state.in_reply_to.length===1?state.in_reply_to:[]),...(state.message_id?[state.message_id]:[])];if(refs.length>100)return {available:false,reason:'REFERENCE_CHAIN_LIMIT',in_reply_to:[],references:[]};return {available:true,reason:null,in_reply_to:state.message_id?[state.message_id]:[],references:refs};}
function sendContext(core,ctx,actor,draft,account){if(!draft.source_message_ref)return null;const ref=draft.source_message_ref,source=core.get(ctx,actor,'messages',ref.id);if(source.deleted_at||source.revision!==ref.revision||require('./communication-replies').sourceHash(source,ref.hash_version||1)!==ref.hash)fail('send_reply_source_changed','Het oorspronkelijke bericht is gewijzigd; bereid het antwoord opnieuw voor',409);if(ref.mode==='REPLY_ALL'&&(!account||account.from!==ref.reply_from))fail('send_reply_identity_changed','De afzender voor allen beantwoorden is gewijzigd; bereid het antwoord opnieuw voor',409);const headers=['REPLY','REPLY_ALL'].includes(ref.mode)?replyHeaders(source):{available:true,reason:null,in_reply_to:[],references:[]};return {source_id:ref.id,source_revision:ref.revision,source_hash:ref.hash,mode:ref.mode,headers,linkage:'RETAINED_SOURCE_REFERENCE',provider_thread_verified:false};}
function query(core,ctx,actor,id,input={}){
 core.scope(ctx,actor);core.resolver.assertCapability(ctx,actor,'communication:threads');core.resolver.assertCapability(ctx,actor,'communication:inbox');const source=core.get(ctx,actor,'messages',id);if(source.deleted_at||source.status==='ARCHIVED')fail('record_not_found','Bericht niet gevonden',404);
 if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(key=>!['limit','offset'].includes(key)))fail('thread_query_invalid','Ongeldige gespreksfilter');const limit=Number(input.limit??25),offset=Number(input.offset??0);if(!Number.isSafeInteger(limit)||limit<1||limit>100||!Number.isSafeInteger(offset)||offset<0||offset>25000)fail('thread_query_invalid','Kies een geldige gesprekspagina');
 const retained=core.bucket(ctx,'messages');if(retained.length>25000)fail('thread_capacity','De bewaarde gespreksindex is te groot',507);
 const rows=retained.filter(row=>!row.deleted_at&&row.status!=='ARCHIVED'&&row.provider_currently_draft!==true&&core.visible(row,actor)),byId=new Map(rows.map(row=>[row.id,row])),headers=new Map(rows.map(row=>[row.id,headerState(row)])),owners=new Map(),adjacent=new Map(rows.map(row=>[row.id,new Set()]));let links=0;
 for(const row of rows){const state=headers.get(row.id);if(state.available&&state.message_id){const ids=owners.get(state.message_id)||[];ids.push(row.id);owners.set(state.message_id,ids);}}
 for(const row of rows){const state=headers.get(row.id);if(!state.available||state.message_id&&owners.get(state.message_id)?.length!==1)continue;for(const ref of new Set([...state.references,...state.in_reply_to])){const candidates=owners.get(ref);if(candidates?.length!==1||candidates[0]===row.id)continue;if(++links>100000)fail('thread_capacity','Er zijn te veel verbanden voor deze gespreksindex',507);adjacent.get(row.id).add(candidates[0]);adjacent.get(candidates[0]).add(row.id);}}
 const seen=new Set([id]),queue=[id];for(let n=0;n<queue.length;n++)for(const next of adjacent.get(queue[n])||[])if(!seen.has(next)){seen.add(next);queue.push(next);}
 const connected=queue.map(key=>byId.get(key)).filter(Boolean).sort((a,b)=>String(a.sent_at||a.received_at||a.authored_at||'').localeCompare(String(b.sent_at||b.received_at||b.authored_at||''))||a.id.localeCompare(b.id));let participantComplete=true,participantLimited=false;const addresses=new Set();for(const row of connected){for(const values of [[row.from],row.to,row.cc===undefined?[]:row.cc]){if(!Array.isArray(values)||values.some(value=>!require('./communication-send-reviews').address(value))){participantComplete=false;continue;}for(const value of values){if(addresses.size<2000||addresses.has(value))addresses.add(value);else{participantComplete=false;participantLimited=true;}}}}
 const unavailable=connected.some(row=>!headers.get(row.id).available),ambiguous=connected.some(row=>{const state=headers.get(row.id);return [state.message_id,...state.references,...state.in_reply_to].some(value=>value&&owners.get(value)?.length>1);});
 return {source_id:id,items:connected.slice(offset,offset+limit).map(row=>({id:row.id,revision:row.revision,title:typeof row.title==='string'?row.title:null,from:row.from??null,to:row.to??null,cc:row.cc??null,direction:row.direction??null,sent_at:row.sent_at??null,received_at:row.received_at??null,authored_at:row.authored_at??null,content_available:row.content_available!==false&&typeof row.content==='string'})),total_retained_visible:connected.length,limit,offset,next_offset:offset+limit<connected.length?offset+limit:null,participants:[...addresses].sort(),participants_complete:participantComplete,participants_window_limited:participantLimited,participant_identity_verified:false,linkage:'UNVERIFIED_MESSAGE_HEADERS',ambiguous_identifiers:ambiguous,headers_available:!unavailable,external_thread_total:null,external_thread_complete:false,snapshot_sha256:crypto.createHash('sha256').update(JSON.stringify(connected.map(row=>({id:row.id,revision:row.revision,headers:headers.get(row.id)})))).digest('hex'),observed_at:new Date().toISOString()};
}
module.exports={validId,headerState,replyHeaders,sendContext,query};
