'use strict';
// Extensible object records use the existing CRM permission vocabulary and
// encrypted adapter without modifying the frozen CRM engine.
const crypto=require('node:crypto'),{FoundlyCrmCore,normalizeContext,principalShape,sanitizeInput}=require('./crm-core'),{scopedMutation}=require('./scoped-mutation');
const SCOPES={definitions:'crm:object_definitions',records:'crm:object_records',history:'crm:object_history',audit:'crm:object_audit'};
const TYPES=['TEXT','NUMBER','BOOLEAN','DATE','SELECT','MULTI_SELECT','MONEY','RELATION'];
const RELATIONS=['contacts','companies','people','leads','opportunities','deals','tasks','appointments'];
const {ENTITY_CAPABILITIES}=require('./module-access-contracts');
const fail=(code,message,statusCode=422)=>{throw Object.assign(Error(message),{code,statusCode});};
const clone=v=>JSON.parse(JSON.stringify(v)),hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const keys=(v,allowed)=>object(v)&&Object.keys(v).every(k=>allowed.includes(k));
const idOK=v=>typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,99}$/.test(v);
const text=(v,max)=>typeof v==='string'&&v.trim()&&v.length<=max;
const privileged=p=>p.permissions.has('*')||p.permissions.has('crm:manage');
const readable=(row,p)=>FoundlyCrmCore.prototype.canReadRecord(row,p);
const writable=(row,p)=>FoundlyCrmCore.prototype.canWriteRecord(row,p);
function definition(input){
 if(!keys(input,['key','name','version','fields','team_id','record_entity'])||!text(input.name,160)||typeof input.key!=='string'||!/^[a-z][a-z0-9_]{1,49}$/.test(input.key)||!Number.isSafeInteger(input.version)||input.version<1||input.version>100000||!Array.isArray(input.fields)||!input.fields.length||input.fields.length>30||input.team_id!==undefined&&input.team_id!==null&&!idOK(input.team_id))fail('crm_object_schema_invalid','Kies een naam, sleutel, positieve versie en 1–30 eigen velden');
 if(input.record_entity!==undefined&&!RELATIONS.includes(input.record_entity))fail('crm_object_schema_invalid','Kies een ondersteunde CRM-collectie voor deze eigen velden');
 const seen=new Set();for(const f of input.fields){
  if(!keys(f,['key','label','type','required','restricted','options','target_entity'])||typeof f.key!=='string'||!/^[a-z][a-z0-9_]{0,49}$/.test(f.key)||['id','constructor','prototype','__proto__','tenant_id','dealer_id','owner_id','revision'].includes(f.key)||seen.has(f.key)||/^(?:password|secret|token|authorization|cookie|api_key|private_key|credential)s?$/i.test(f.key)||!text(f.label,100)||!TYPES.includes(f.type)||typeof f.required!=='boolean'||f.restricted!==undefined&&typeof f.restricted!=='boolean')fail('crm_object_field_invalid','Controleer unieke veldnamen, typen en verplichte velden');seen.add(f.key);
  if(['SELECT','MULTI_SELECT'].includes(f.type)){if(!Array.isArray(f.options)||!f.options.length||f.options.length>30||f.options.some(v=>!text(v,80))||new Set(f.options).size!==f.options.length)fail('crm_object_field_invalid','Kies maximaal dertig unieke keuzewaarden');}else if(Object.hasOwn(f,'options'))fail('crm_object_field_invalid','Alleen keuzevelden hebben keuzewaarden');
  if(f.type==='RELATION'){if(!RELATIONS.includes(f.target_entity))fail('crm_object_field_invalid','Kies een ondersteund CRM-relatiedoel');}else if(Object.hasOwn(f,'target_entity'))fail('crm_object_field_invalid','Alleen relatievelden hebben een relatiedoel');
 }
 const clean=sanitizeInput(input);if(JSON.stringify(clean)!==JSON.stringify(input))fail('crm_object_schema_invalid','Gebruik expliciete geldige veldwaarden zonder stille normalisatie');return clone(input);
}
class CrmObjects{
 constructor(adapter,resolver){this.adapter=adapter;this.resolver=resolver;}
 scope(context,actor,operation='read',manage=false){
  const ctx=normalizeContext(context);this.resolver.assertModule(ctx,actor,'crm',operation);if(operation!=='export')this.resolver.assertCapability(ctx,actor,'crm:relationships',operation);
  const roles=[...(actor.roles||[])];if(roles.some(r=>['FOUNDER','SUPER_ADMIN'].includes(String(r).toUpperCase())))roles.push('ADMIN');const principal=principalShape({...actor,roles});FoundlyCrmCore.prototype.assertRead(principal);
  if(manage&&!privileged(principal))fail('crm_object_manage_forbidden','Alleen CRM-beheer kan objectdefinities of toegang beheren',403);
  if(operation==='write'&&!privileged(principal)&&!principal.permissions.has('crm:write_all')&&!principal.permissions.has('crm:write_assigned'))fail('crm_object_write_forbidden','CRM-schrijftoegang ontbreekt',403);
  if(operation==='export'&&!principal.permissions.has('*')&&!principal.permissions.has('crm:export'))fail('crm_object_export_forbidden','CRM-exportrecht ontbreekt',403);
  return {ctx,principal};
 }
 rows(ctx,kind){return this.adapter.bucket(ctx,SCOPES[kind]);}
 getDefinition(ctx,p,id){const row=this.rows(ctx,'definitions').find(r=>r.id===id&&readable(r,p));if(!row)fail('crm_object_missing','Objectdefinitie niet gevonden',404);return row;}
 getRecord(ctx,p,id,{includeDeleted=false}={}){const row=this.rows(ctx,'records').find(r=>r.id===id&&(includeDeleted||!r.deleted_at)&&readable(r,p));if(!row)fail('crm_object_record_missing','Objectrecord niet gevonden',404);const def=this.getDefinition(ctx,p,row.object_id);this.nativeRecord(ctx,p,def,row);return row;}
 nativeRecord(ctx,actor,def,row,operation='read'){
  if(!def.record_entity)return null;if(!idOK(row.native_record_id))fail('crm_object_parent_required','Kies het bestaande CRM-record voor deze eigen velden');
  this.resolver.assertCapability(ctx,actor,ENTITY_CAPABILITIES.crm[def.record_entity],operation);const parent=this.adapter.readRelated(ctx,actor,def.record_entity,row.native_record_id);
  if(operation==='write'&&!writable(parent,actor.permissions instanceof Set?actor:principalShape(actor)))fail('crm_object_parent_forbidden','Geen schrijfbevoegdheid voor het gekoppelde CRM-record',403);return parent;
 }
 parentVisible(ctx,actor,def,row){try{this.nativeRecord(ctx,actor,def,row);return true;}catch(e){if([403,404].includes(e.statusCode))return false;throw e;}}
 audit(ctx,p,action,kind,id,revision,reason=null){this.rows(ctx,'audit').push({id:crypto.randomUUID(),action,kind,record_id:id,revision,actor_id:p.id,reason,at:new Date().toISOString()});}
 mutate(ctx,fn){if(this.rows(ctx,'history').length>=100000||this.rows(ctx,'audit').length>=100000)fail('crm_object_history_capacity','De objecthistorie heeft de bewaarlimiet bereikt',507);return scopedMutation(this.adapter,ctx,Object.values(SCOPES),fn);}
 listDefinitions(context,actor){const {ctx,principal:p}=this.scope(context,actor);return {items:clone(this.rows(ctx,'definitions').filter(r=>readable(r,p))),can_manage:privileged(p),can_write:privileged(p)||p.permissions.has('crm:write_all')||p.permissions.has('crm:write_assigned'),types:TYPES,relation_entities:RELATIONS,scope:'CURRENT_CRM_ACCESS',immutable_schema_versions:true};}
 saveDefinition(context,actor,id,input){
  const {ctx,principal:p}=this.scope(context,actor,'write',true);if(!idOK(id)||!keys(input,['definition','expected_revision'])||input.expected_revision!==0)fail('crm_object_schema_invalid','Nieuwe definities vereisen een eigen kenmerk en revisie nul');const value=definition(input.definition),fingerprint=hash(value),rows=this.rows(ctx,'definitions'),prior=rows.find(r=>r.id===id);
  if(prior){if(!readable(prior,p))fail('crm_object_missing','Objectdefinitie niet gevonden',404);if(prior.definition_fingerprint===fingerprint&&prior.created_by===p.id)return {record:clone(prior),deduplicated:true};fail('crm_object_immutable','Bewaar gewijzigde velden als een nieuwe objectversie',409);}
  if(rows.some(r=>r.key===value.key&&r.version===value.version))fail('crm_object_version_conflict','Deze objectversie bestaat al',409);if(rows.length>=250)fail('crm_object_capacity','Maximaal 250 bewaarde objectversies',507);
  return this.mutate(ctx,()=>{const now=new Date().toISOString(),row={...value,id,owner_id:p.id,tenant_id:ctx.tenant_id,dealer_id:ctx.dealer_id,revision:1,definition_fingerprint:fingerprint,created_by:p.id,created_at:now,updated_at:now};rows.push(row);this.audit(ctx,p,'CREATE','definition',id,1);return {record:clone(row)};});
 }
 values(ctx,actor,p,def,input,previous={}){
  if(!object(input)||JSON.stringify(input).length>64000||Object.keys(input).some(k=>!def.fields.some(f=>f.key===k)))fail('crm_object_values_invalid','Onbekende of te grote veldinvoer');const result={...clone(previous)};
  for(const f of def.fields){const supplied=Object.hasOwn(input,f.key);if(supplied&&f.restricted&&!privileged(p))fail('crm_object_field_forbidden','Dit veld is alleen toegankelijk voor CRM-beheer',403);if(!supplied)continue;const v=input[f.key];if(v===null){if(f.required)fail('crm_object_required','Een verplicht veld mag niet leeg zijn');result[f.key]=null;continue;}
   let valid=false;switch(f.type){case'TEXT':valid=typeof v==='string'&&v.length<=2000&&(!f.required||Boolean(v.trim()));break;case'NUMBER':valid=typeof v==='number'&&Number.isFinite(v);break;case'BOOLEAN':valid=typeof v==='boolean';break;case'DATE':valid=typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;break;case'SELECT':valid=typeof v==='string'&&f.options.includes(v);break;case'MULTI_SELECT':valid=Array.isArray(v)&&v.length<=30&&new Set(v).size===v.length&&v.every(x=>f.options.includes(x));break;case'MONEY':valid=keys(v,['amount_cents','currency'])&&Number.isSafeInteger(v.amount_cents)&&typeof v.currency==='string'&&/^[A-Z]{3}$/.test(v.currency);break;case'RELATION':valid=idOK(v);if(valid)this.adapter.readRelated(ctx,actor,f.target_entity,v);break;}
   if(!valid)fail('crm_object_value_type','Controleer het type en de waarde van '+f.label);result[f.key]=clone(v);
  }
  for(const f of def.fields)if(f.required&&(result[f.key]===undefined||result[f.key]===null||result[f.key]===''||Array.isArray(result[f.key])&&!result[f.key].length))fail('crm_object_required','Vul het verplichte veld '+f.label+' in');
  // Reject secret-bearing or structurally altered values using the frozen sanitizer.
  if(JSON.stringify(sanitizeInput(result))!==JSON.stringify(result))fail('crm_object_values_invalid','Veldinvoer kan niet ongewijzigd worden bewaard');return result;
 }
 project(ctx,actor,p,def,row){this.nativeRecord(ctx,actor,def,row);let parentWritable=true;try{this.nativeRecord(ctx,actor,def,row,'write');}catch(e){if(![403,404].includes(e.statusCode))throw e;parentWritable=false;}const record=clone(row),unavailable=[];delete record.last_request_hash;delete record.request_revision;delete record.archive_request_hash;for(const f of def.fields){if(f.restricted&&!privileged(p)){delete record.values[f.key];unavailable.push(f.key);continue;}if(f.type==='RELATION'&&record.values[f.key])try{this.adapter.readRelated(ctx,actor,f.target_entity,record.values[f.key]);}catch(e){if(![403,404].includes(e.statusCode))throw e;delete record.values[f.key];unavailable.push(f.key);}}return {...record,unavailable_fields:unavailable,can_write:!row.deleted_at&&writable(row,p)&&parentWritable,can_restore:Boolean(row.deleted_at)&&writable(row,p)&&parentWritable};}
 listRecords(context,actor,objectId,query={}){const {ctx,principal:p}=this.scope(context,actor),def=this.getDefinition(ctx,p,objectId),limit=Number(query.limit??50),offset=Number(query.offset??0),q=String(query.q||'').trim().toLowerCase();if(!keys(query,['limit','offset','q','archived','native_record_id'])||query.archived!==undefined&&!['true','false'].includes(query.archived)||!Number.isInteger(limit)||limit<1||limit>100||!Number.isInteger(offset)||offset<0||offset>25000||q.length>200||query.native_record_id!==undefined&&!idOK(query.native_record_id))fail('crm_object_query_invalid','Kies een geldige zoekterm en pagina');if(query.native_record_id){if(!def.record_entity)fail('crm_object_parent_invalid','Dit objecttype is niet aan CRM-records gekoppeld');this.nativeRecord(ctx,actor,def,{native_record_id:query.native_record_id});}const fields=def.fields.filter(f=>f.type!=='RELATION'&&(!f.restricted||privileged(p))),rows=this.rows(ctx,'records').filter(r=>r.object_id===objectId&&(query.archived==='true'?Boolean(r.deleted_at):!r.deleted_at)&&readable(r,p)&&(!query.native_record_id||r.native_record_id===query.native_record_id)&&this.parentVisible(ctx,actor,def,r)&&(!q||fields.some(f=>typeof r.values[f.key]==='string'&&r.values[f.key].toLowerCase().includes(q))));return {items:rows.slice(offset,offset+limit).map(r=>this.project(ctx,actor,p,def,r)),total:rows.length,next_offset:offset+limit<rows.length?offset+limit:null,definition:clone(def),scope:'CURRENT_CRM_ACCESS',search_scope:'VISIBLE_TEXT_VALUES_EXCLUDING_RELATION_IDS'};}

 saveRecord(context,actor,id,input){
  const {ctx,principal:p}=this.scope(context,actor,'write');if(!idOK(id)||!keys(input,['object_id','schema_revision','expected_revision','values','native_record_id'])||!idOK(input.object_id)||!Number.isInteger(input.expected_revision)||input.expected_revision<0)fail('crm_object_record_invalid','Kies een object, schema- en recordrevisie');const def=this.getDefinition(ctx,p,input.object_id);if(def.revision!==input.schema_revision)fail('crm_object_schema_changed','De objecttoegang is gewijzigd; laad het actuele schema',409);
  const rows=this.rows(ctx,'records'),prior=rows.find(r=>r.id===id);if(prior&&(prior.deleted_at||!readable(prior,p)||!writable(prior,p)||prior.object_id!==def.id))fail('crm_object_record_missing','Objectrecord niet toegankelijk',404);
  if(def.record_entity){this.nativeRecord(ctx,actor,def,input,'write');if(prior&&prior.native_record_id!==input.native_record_id)fail('crm_object_parent_immutable','Eigen velden kunnen niet naar een ander CRM-record worden verplaatst',409);if(rows.some(r=>r.id!==id&&r.object_id===def.id&&r.native_record_id===input.native_record_id))fail('crm_object_parent_duplicate','Deze veldversie is al aan het CRM-record gekoppeld; laad het bestaande record',409);}else if(input.native_record_id!==undefined)fail('crm_object_parent_invalid','Dit objecttype is niet aan CRM-records gekoppeld');const requestHash=hash({actor_id:p.id,input}),value=this.values(ctx,actor,p,def,input.values,prior?.values);if(prior?.last_request_hash===requestHash&&prior.request_revision===input.expected_revision)return {record:this.project(ctx,actor,p,def,prior),deduplicated:true};if(input.expected_revision!==(prior?.revision||0))fail('crm_object_record_conflict','Het record is elders gewijzigd; je invoer is niet overschreven',409);if(!prior&&rows.length>=25000)fail('crm_object_capacity','Objectrecordlimiet bereikt',507);
  return this.mutate(ctx,()=>{const now=new Date().toISOString(),row={id,object_id:def.id,...(def.record_entity?{native_record_id:input.native_record_id}:{}),values:value,owner_id:prior?.owner_id||p.id,team_id:prior?.team_id||null,tenant_id:ctx.tenant_id,dealer_id:ctx.dealer_id,revision:(prior?.revision||0)+1,created_by:prior?.created_by||p.id,created_at:prior?.created_at||now,updated_at:now,updated_by:p.id,last_request_hash:requestHash,request_revision:input.expected_revision};if(prior)rows[rows.indexOf(prior)]=row;else rows.push(row);this.rows(ctx,'history').push(clone(row));this.audit(ctx,p,prior?'UPDATE':'CREATE','record',id,row.revision);return {record:this.project(ctx,actor,p,def,row)};});
 }
 history(context,actor,id,query={}){const {ctx,principal:p}=this.scope(context,actor),row=this.getRecord(ctx,p,id,{includeDeleted:true}),def=this.getDefinition(ctx,p,row.object_id),offset=Number(query.offset??0),limit=Number(query.limit??50);if(!keys(query,['limit','offset'])||!Number.isInteger(offset)||offset<0||offset>100000||!Number.isInteger(limit)||limit<1||limit>100)fail('crm_object_query_invalid','Kies een geldige historiepagina');const rows=this.rows(ctx,'history').filter(r=>r.id===id).reverse();return {items:rows.slice(offset,offset+limit).map(r=>({...this.project(ctx,actor,p,def,r),can_write:false,can_restore:false})),total:rows.length,next_offset:offset+limit<rows.length?offset+limit:null,current_revision:row.revision,current_access_rechecked:true};}

 setAccess(context,actor,kind,id,input){const {ctx,principal:p}=this.scope(context,actor,'write',true);if(!['definitions','records'].includes(kind)||!keys(input,['team_id','expected_revision','confirm','reason'])||input.confirm!==true||!text(input.reason,500)||input.team_id!==null&&!idOK(input.team_id))fail('crm_object_access_invalid','Bevestig een expliciete teamkeuze met reden');const row=kind==='definitions'?this.getDefinition(ctx,p,id):this.getRecord(ctx,p,id);if(kind==='records')this.nativeRecord(ctx,actor,this.getDefinition(ctx,p,row.object_id),row,'write');if(row.revision!==input.expected_revision)fail('crm_object_record_conflict','De toegang is inmiddels gewijzigd',409);return this.mutate(ctx,()=>{row.team_id=input.team_id;row.revision++;row.updated_at=new Date().toISOString();if(kind==='records'){delete row.last_request_hash;delete row.request_revision;this.rows(ctx,'history').push(clone(row));}this.audit(ctx,p,'ACCESS',kind==='definitions'?'definition':'record',id,row.revision,input.reason.trim());return {id,team_id:row.team_id,revision:row.revision};});}
 count(context,actor){let scoped;try{scoped=this.scope(context,actor);}catch(e){if(e.statusCode===403)return null;throw e;}const {ctx,principal:p}=scoped,definitions=new Map(this.rows(ctx,'definitions').filter(r=>readable(r,p)).map(r=>[r.id,r]));return this.rows(ctx,'records').filter(r=>!r.deleted_at&&readable(r,p)&&definitions.has(r.object_id)&&this.parentVisible(ctx,actor,definitions.get(r.object_id),r)).length;}
 related(context,actor,entity,id){const {ctx,principal:p}=this.scope(context,actor);if(!RELATIONS.includes(entity))return {items:[],total:0};this.adapter.readRelated(ctx,actor,entity,id);const definitions=new Map(this.rows(ctx,'definitions').filter(d=>readable(d,p)).map(d=>[d.id,d])),rows=this.rows(ctx,'records').filter(r=>!r.deleted_at&&readable(r,p)&&definitions.has(r.object_id)&&this.parentVisible(ctx,actor,definitions.get(r.object_id),r)&&(definitions.get(r.object_id).record_entity===entity&&r.native_record_id===id||definitions.get(r.object_id).fields.some(f=>f.type==='RELATION'&&f.target_entity===entity&&(!f.restricted||privileged(p))&&r.values[f.key]===id)));return {items:rows.slice(0,50).map(r=>({object_name:definitions.get(r.object_id).name,object_version:definitions.get(r.object_id).version,record:this.project(ctx,actor,p,definitions.get(r.object_id),r)})),total:rows.length,limit:50,current_source_access:true};}
 archive(context,actor,id,input,restore=false){const {ctx,principal:p}=this.scope(context,actor,'write');if(!keys(input,['expected_revision','confirm','reason'])||input.confirm!==true||!text(input.reason,500))fail('crm_object_archive_invalid','Bevestig deze archiefwijziging met een reden');const row=this.getRecord(ctx,p,id,{includeDeleted:true});this.nativeRecord(ctx,actor,this.getDefinition(ctx,p,row.object_id),row,'write');if(!writable(row,p))fail('crm_object_write_forbidden','Geen schrijfbevoegdheid voor dit record',403);const requestHash=hash({actor_id:p.id,input,restore});if(row.archive_request_hash===requestHash)return {id,revision:row.revision,archived:Boolean(row.deleted_at),deduplicated:true};if(row.revision!==input.expected_revision||Boolean(row.deleted_at)!==restore)fail('crm_object_record_conflict','De archiefstatus of revisie is gewijzigd',409);return this.mutate(ctx,()=>{row.deleted_at=restore?null:new Date().toISOString();row.updated_at=new Date().toISOString();row.revision++;row.archive_request_hash=requestHash;this.rows(ctx,'history').push(clone(row));this.audit(ctx,p,restore?'RESTORE':'ARCHIVE','record',id,row.revision,input.reason.trim());return {id,revision:row.revision,archived:Boolean(row.deleted_at)};});}
 export(context,actor){const {ctx,principal:p}=this.scope(context,actor,'export'),definitions=this.rows(ctx,'definitions').filter(r=>readable(r,p)),byDefinition=new Map(definitions.map(d=>[d.id,d])),records=this.rows(ctx,'records').filter(r=>readable(r,p)&&byDefinition.has(r.object_id)&&this.parentVisible(ctx,actor,byDefinition.get(r.object_id),r)).map(r=>this.project(ctx,actor,p,byDefinition.get(r.object_id),r)),recordIds=new Set(records.map(r=>r.id)),history=this.rows(ctx,'history').filter(r=>recordIds.has(r.id)).map(r=>({...this.project(ctx,actor,p,byDefinition.get(r.object_id),r),can_write:false,can_restore:false})),audit=this.rows(ctx,'audit').filter(r=>r.kind==='definition'?byDefinition.has(r.record_id):r.kind==='record'?recordIds.has(r.record_id):r.actor_id===p.id);return this.mutate(ctx,()=>{this.audit(ctx,p,'EXPORT','objects',null,null);return {module_id:'crm',objects:clone(definitions),records,history,audit:clone(audit),scope:'CURRENT_CRM_ACCESS',source_references_rechecked:true,audited:true};});}

}
module.exports={CrmObjects,SCOPES,TYPES,definition};
function createCrmObjectApi({objects,context,principal,readBody,sendJson}){return async(req,res,url)=>{
 if(!/^\/api\/crm\/objects(?:\/|$)/.test(url.pathname))return false;
 try{
  const ctx=context(req),actor=principal();
  if(url.pathname==='/api/crm/objects'&&req.method==='GET')return sendJson(res,200,objects.listDefinitions(ctx,actor));
  if(url.pathname==='/api/crm/objects/export'&&req.method==='GET')return sendJson(res,200,objects.export(ctx,actor));
  let m=url.pathname.match(/^\/api\/crm\/objects\/([A-Za-z0-9_.:-]{1,100})$/);if(m&&req.method==='PUT')return sendJson(res,200,objects.saveDefinition(ctx,actor,m[1],await readBody(req)));
  m=url.pathname.match(/^\/api\/crm\/objects\/([A-Za-z0-9_.:-]{1,100})\/records$/);if(m&&req.method==='GET')return sendJson(res,200,objects.listRecords(ctx,actor,m[1],Object.fromEntries(url.searchParams)));
  m=url.pathname.match(/^\/api\/crm\/objects\/([A-Za-z0-9_.:-]{1,100})\/records\/([A-Za-z0-9_.:-]{1,100})$/);if(m&&req.method==='PUT'){const input=await readBody(req);if(input.object_id!==undefined&&input.object_id!==m[1])fail('crm_object_record_invalid','Het gekozen object wijkt af van de route');return sendJson(res,200,objects.saveRecord(ctx,actor,m[2],{...input,object_id:m[1]}));}
  m=url.pathname.match(/^\/api\/crm\/objects\/records\/([A-Za-z0-9_.:-]{1,100})(\/restore)?$/);if(m&&(req.method==='DELETE'&&!m[2]||req.method==='POST'&&m[2]))return sendJson(res,200,objects.archive(ctx,actor,m[1],await readBody(req),Boolean(m[2])));
  m=url.pathname.match(/^\/api\/crm\/objects\/records\/([A-Za-z0-9_.:-]{1,100})\/history$/);if(m&&req.method==='GET')return sendJson(res,200,objects.history(ctx,actor,m[1],Object.fromEntries(url.searchParams)));
  m=url.pathname.match(/^\/api\/crm\/objects\/(records\/)?([A-Za-z0-9_.:-]{1,100})\/access$/);if(m&&req.method==='PATCH')return sendJson(res,200,objects.setAccess(ctx,actor,m[1]?'records':'definitions',m[2],await readBody(req)));
  return sendJson(res,404,{code:'crm_object_route_missing',error:'Objectroute niet gevonden'});
 }catch(e){return sendJson(res,e.statusCode||500,{code:e.code||'crm_object_failed',error:e.statusCode?e.message:'Objectactie is niet gelukt'});}
};}
module.exports.createCrmObjectApi=createCrmObjectApi;
