'use strict';

const crypto=require('crypto');

const ENTITY_DEFINITIONS=Object.freeze({
  tenants:{required:['name'],adminOnly:true},
  users:{required:['name'],adminOnly:true},
  teams:{required:['name'],adminOnly:true},
  roles:{required:['name'],adminOnly:true},
  people:{required:['name']},
  contacts:{required:['name']},
  companies:{required:['name']},
  leads:{required:['name']},
  opportunities:{required:['title']},
  deals:{required:['title']},
  pipelines:{required:['name'],manageOnly:true},
  stages:{required:['name','pipeline_id'],manageOnly:true},
  activities:{required:['type']},
  tasks:{required:['title']},
  appointments:{required:['title']},
  notes:{required:['content']},
  calls:{required:['direction']},
  emails:{required:['direction']},
  messages:{required:['channel','direction']},
  products:{required:['name']},
  vehicles:{required:[]},
  inventory_relations:{required:['inventory_id']},
  quotes:{required:['number']},
  orders:{required:['number']},
  documents:{required:['name']},
  campaigns:{required:['name']},
  sources:{required:['name']},
  attributions:{required:['source_id']},
  workflows:{required:['name'],manageOnly:true},
  automations:{required:['name','trigger','actions'],manageOnly:true},
  automation_executions:{required:['automation_id','event_id'],readOnly:true},
  custom_fields:{required:['name','entity','field_type'],manageOnly:true},
  tags:{required:['name']},
  segments:{required:['name']},
  consents:{required:['subject_id','purpose','status']},
  dashboard_views:{required:['name','widgets']},
  webhook_subscriptions:{required:['name','event_types'],adminOnly:true},
  audit_events:{required:['action','entity'],readOnly:true}
});

const DASHBOARD_WIDGET_TYPES=new Set(['KPI','LINE','BAR','FUNNEL','PIPELINE','TABLE','LEADERBOARD','FORECAST','ACTIVITY_FEED']);
const AUTOMATION_TRIGGERS=new Set(['new_lead','stage_change','no_contact','appointment','quote','deal_won','deal_lost','product_interest','campaign_source','score_threshold','webhook']);
const AUTOMATION_ACTIONS=new Set(['task','notify','assign','message','email','follow_up','field_update','stage_change','webhook','zero_task']);
const SENSITIVE_FIELD=/^(?:password|secret|token|authorization|cookie|api[_-]?key|private[_-]?key|credential)s?$/i;
const SAFE_FIELD=/^[a-z][a-z0-9_]{0,63}$/;
const MAX_COLLECTION_SIZE=25000;
const ENTITY_SINGULAR=Object.freeze({companies:'company',activities:'activity',inventory_relations:'inventory_relation',opportunities:'opportunity',consents:'consent',people:'person'});
const MARKETING_ENTITIES=new Set(['campaigns','sources','attributions','segments','campaign','source','attribution','segment']);
const ANALYTICS_FILTERS=new Set(['owner_id','team_id','pipeline_id','stage_id','source_id','campaign_id','status']);

const ROLE_PERMISSIONS=Object.freeze({
  ADMIN:['*'],
  MANAGER:['crm:read_all','crm:write_all','crm:manage','crm:analytics','crm:export','crm:automate','crm:dashboard'],
  SALES:['crm:read_assigned','crm:write_assigned','crm:analytics','crm:dashboard'],
  MARKETING:['crm:read_all','crm:write_marketing','crm:analytics','crm:dashboard'],
  VIEWER:['crm:read_assigned','crm:analytics','crm:dashboard']
});

const PRESET_WIDGETS=Object.freeze({
  EXECUTIVE:[['pipeline_value','KPI'],['won_value','KPI'],['forecast','FORECAST'],['conversion','KPI'],['pipeline','PIPELINE'],['source_performance','BAR']],
  SALES:[['leads','KPI'],['qualified_leads','KPI'],['pipeline_value','KPI'],['appointments','KPI'],['pipeline','PIPELINE'],['priority_leads','TABLE'],['activity','ACTIVITY_FEED']],
  MARKETING:[['leads','KPI'],['conversion','KPI'],['source_performance','BAR'],['campaign_attribution','TABLE'],['lead_trend','LINE']],
  OPERATIONS:[['open_tasks','KPI'],['follow_up_rate','KPI'],['response_time','KPI'],['appointments','KPI'],['activity','ACTIVITY_FEED']],
  CRM_MANAGER:[['pipeline_value','KPI'],['win_rate','KPI'],['sales_cycle','KPI'],['stalled_deals','TABLE'],['owner_performance','LEADERBOARD'],['pipeline','FUNNEL']],
  PERSONAL:[['my_leads','KPI'],['my_tasks','KPI'],['my_pipeline','KPI'],['priority_leads','TABLE'],['activity','ACTIVITY_FEED']]
});

function crmError(status,code,message,details){const error=new Error(message);error.statusCode=status;error.code=code;if(details!==undefined)error.details=details;return error}
function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
function finite(value,fallback=0){const number=Number(value);return Number.isFinite(number)?number:fallback}
function iso(value){if(!value)return null;const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString()}
function safeId(value){const id=String(value||'').trim();return /^[A-Za-z0-9][A-Za-z0-9_.:-]{0,199}$/.test(id)?id:null}
function normalizeContext(context={}){const tenant_id=safeId(context.tenant_id),dealer_id=safeId(context.dealer_id||'default');if(!tenant_id||!dealer_id)throw crmError(400,'crm_context_invalid','Geldige tenant- en businesscontext is verplicht');return {tenant_id,dealer_id}}
function permissionsFor(principal={}){const explicit=Array.isArray(principal.permissions)?principal.permissions:[],roles=Array.isArray(principal.roles)?principal.roles:[principal.role||'VIEWER'];return new Set([...explicit,...roles.flatMap(role=>ROLE_PERMISSIONS[String(role).toUpperCase()]||[])])}
function principalShape(principal={}){return {id:safeId(principal.id)||'anonymous',roles:(Array.isArray(principal.roles)?principal.roles:[principal.role||'VIEWER']).map(x=>String(x).toUpperCase()).slice(0,8),team_ids:(Array.isArray(principal.team_ids)?principal.team_ids:[]).map(safeId).filter(Boolean).slice(0,50),permissions:permissionsFor(principal)}}
function hasPermission(principal,permission){return principal.permissions.has('*')||principal.permissions.has(permission)}
function requirePermission(principal,permission){if(!hasPermission(principal,permission))throw crmError(403,'crm_forbidden','Deze CRM-actie is niet toegestaan voor de actieve rol')}
function randomId(){return crypto.randomUUID?crypto.randomUUID():crypto.randomBytes(16).toString('hex')}
function sha(value){return crypto.createHash('sha256').update(String(value)).digest('hex')}
function deepClone(value){return value===undefined?undefined:JSON.parse(JSON.stringify(value))}
function safeString(value,max=4000){return String(value??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g,' ').trim().slice(0,max)}
function sanitizeValue(value,key='',depth=0){
  if(depth>6)throw crmError(400,'crm_payload_too_deep','CRM-payload is te diep genest');
  if(SENSITIVE_FIELD.test(key)&&value!==null&&value!==undefined&&String(value)!=='')throw crmError(400,'crm_secret_rejected','Secrets en credentials horen niet in CRM-records');
  if(value===null||value===undefined||typeof value==='boolean')return value??null;
  if(typeof value==='number')return Number.isFinite(value)?value:null;
  if(typeof value==='string')return safeString(value,12000);
  if(Array.isArray(value))return value.slice(0,200).map(item=>sanitizeValue(item,key,depth+1));
  if(typeof value==='object'){
    const out={};
    for(const [rawKey,item] of Object.entries(value).slice(0,200)){
      const cleanKey=String(rawKey).trim();
      if(!SAFE_FIELD.test(cleanKey)||['__proto__','constructor','prototype'].includes(cleanKey))continue;
      out[cleanKey]=sanitizeValue(item,cleanKey,depth+1);
    }
    return out;
  }
  return null;
}
function sanitizeInput(value){return sanitizeValue(value&&typeof value==='object'&&!Array.isArray(value)?value:{})}
function sortRows(rows,field='updated_at',direction='desc'){const dir=String(direction).toLowerCase()==='asc'?1:-1;return rows.sort((a,b)=>{const av=a[field]??'',bv=b[field]??'';if(av===bv)return String(a.id).localeCompare(String(b.id))*dir;return (av>bv?1:-1)*dir})}
function dateInRange(value,from,to){const at=Date.parse(value||0);if(!Number.isFinite(at))return !from&&!to;if(from&&at<Date.parse(from))return false;if(to&&at>Date.parse(to))return false;return true}
function average(values){const rows=values.filter(Number.isFinite);return rows.length?rows.reduce((sum,value)=>sum+value,0)/rows.length:null}
function metric(value,unit,sourceCount){return {value:value===null?null:(Number.isFinite(value)?Number(value.toFixed(2)):value),unit,available:sourceCount>0,source_count:sourceCount}}
function analyticsFilters(input={}){const clean=sanitizeInput(input),out={};for(const [field,value] of Object.entries(clean))if(ANALYTICS_FILTERS.has(field)&&value!==null&&value!==undefined&&value!==''){const normalized=safeString(value,200);if(normalized)out[field]=normalized}return out}
function matchesAnalyticsFilters(row,filters={}){return Object.entries(filters).every(([field,value])=>{if(field==='source_id')return String(row.source_id||row.source||'')===value;if(field==='status')return String(row.status||'').toLowerCase()===value.toLowerCase();return String(row[field]??'')===value})}
function dayKey(value){const at=Date.parse(value||'');return Number.isFinite(at)?new Date(at).toISOString().slice(0,10):null}
function comparisonRange(from,to){const start=Date.parse(from||''),end=Date.parse(to||'');if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)return null;const duration=Math.max(86400000,end-start+1),previousTo=start-1,previousFrom=previousTo-duration+1;return {from:new Date(previousFrom).toISOString(),to:new Date(previousTo).toISOString()}}

function presetDashboard(name='SALES',ownerId='current-user'){
  const requested=String(name||'SALES').toUpperCase().replace(/\s+/g,'_'),preset=PRESET_WIDGETS[requested]?requested:'SALES',rows=PRESET_WIDGETS[preset];
  let x=0,y=0,rowHeight=0;
  const widgets=rows.map(([metricId,type])=>{const w=['TABLE','PIPELINE','ACTIVITY_FEED'].includes(type)?8:4,h=type==='KPI'?2:4;if(x+w>12){x=0;y+=rowHeight||3;rowHeight=0}const widget={id:`${preset.toLowerCase()}-${metricId}`,metric:metricId,type,x,y,w,h,filters:{}};x+=w;rowHeight=Math.max(rowHeight,h);if(x>=12){x=0;y+=rowHeight;rowHeight=0}return widget});
  return {id:`preset-${preset.toLowerCase().replace(/_/g,'-')}`,name:preset.replace(/_/g,' '),preset,owner_id:ownerId,share_mode:'PRIVATE',filters:{date_range:'LAST_30_DAYS'},widgets,persisted:false};
}

class FoundlyCrmCore{
  constructor(adapter={}){
    if(typeof adapter.bucket!=='function')throw new TypeError('CRM adapter.bucket is required');
    this.adapter={persist:()=>{},emit:()=>{},enqueue:()=>null,now:()=>new Date(),id:randomId,...adapter};
  }

  context(context,principal){return {ctx:normalizeContext(context),principal:principalShape(principal)}}
  collection(ctx,entity){if(!ENTITY_DEFINITIONS[entity])throw crmError(404,'crm_entity_unknown','Onbekende CRM-collectie');return this.adapter.bucket(ctx,`crm:${entity}`)}
  commit(){this.adapter.persist()}
  assertEntity(entity){const value=String(entity||'').toLowerCase();if(!ENTITY_DEFINITIONS[value])throw crmError(404,'crm_entity_unknown','Onbekende CRM-collectie');return value}
  canReadRecord(record,principal){return hasPermission(principal,'crm:read_all')||record.owner_id===principal.id||!record.owner_id||principal.team_ids.includes(record.team_id)}
  canWriteRecord(record,principal){return hasPermission(principal,'crm:write_all')||hasPermission(principal,'crm:manage')||hasPermission(principal,'crm:write_marketing')&&MARKETING_ENTITIES.has(record.entity_type)||hasPermission(principal,'crm:write_assigned')&&(record.owner_id===principal.id||!record.owner_id||principal.team_ids.includes(record.team_id))}
  assertRead(principal){if(!hasPermission(principal,'crm:read_all')&&!hasPermission(principal,'crm:read_assigned'))throw crmError(403,'crm_forbidden','CRM-leestoegang ontbreekt')}
  assertCreate(entity,principal){const def=ENTITY_DEFINITIONS[entity];if(def.readOnly)throw crmError(405,'crm_entity_read_only','Deze CRM-collectie wordt uitsluitend door het systeem geschreven');if(def.adminOnly||def.manageOnly)requirePermission(principal,'crm:manage');else if(!(hasPermission(principal,'crm:write_all')||hasPermission(principal,'crm:write_assigned')||hasPermission(principal,'crm:write_marketing')&&MARKETING_ENTITIES.has(entity)))throw crmError(403,'crm_forbidden','CRM-schrijftoegang ontbreekt')}
  validate(entity,input,{partial=false}={}){
    const data=sanitizeInput(input),def=ENTITY_DEFINITIONS[entity];
    for(const protectedField of ['id','tenant_id','dealer_id','created_at','created_by','updated_at','updated_by','revision','deleted_at'])delete data[protectedField];
    if(!partial)for(const field of def.required)if(data[field]===undefined||data[field]===null||data[field]===''||(Array.isArray(data[field])&&!data[field].length))throw crmError(400,'crm_validation_failed',`${field} is verplicht`,{field});
    for(const field of ['owner_id','team_id','contact_id','person_id','company_id','lead_id','opportunity_id','deal_id','pipeline_id','stage_id','campaign_id','source_id','product_id','vehicle_id','subject_id'])if(data[field]!==undefined&&data[field]!==null&&!safeId(data[field]))throw crmError(400,'crm_validation_failed',`${field} heeft een ongeldig formaat`,{field});
    if(data.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))throw crmError(400,'crm_validation_failed','email heeft een ongeldig formaat',{field:'email'});
    if(data.probability!==undefined)data.probability=clamp(finite(data.probability),0,100);
    for(const field of ['value','margin','amount','forecast_value'])if(data[field]!==undefined)data[field]=Math.max(0,finite(data[field]));
    for(const field of ['expected_close_at','due_at','scheduled_at','closed_at','won_at','lost_at','last_contacted_at','next_action_at','consented_at','revoked_at'])if(data[field]!==undefined&&data[field]!==null){const normalized=iso(data[field]);if(!normalized)throw crmError(400,'crm_validation_failed',`${field} moet een geldige datum zijn`,{field});data[field]=normalized}
    if(entity==='automations')this.validateAutomation(data,partial);
    if(entity==='dashboard_views')this.validateDashboard(data,partial);
    if(entity==='custom_fields'&&data.field_type&&!['TEXT','NUMBER','DATE','BOOLEAN','SELECT','MULTI_SELECT','MONEY','USER','RELATION'].includes(String(data.field_type).toUpperCase()))throw crmError(400,'crm_validation_failed','Niet-ondersteund custom-fieldtype');
    return data;
  }
  validateAutomation(data,partial){if(data.trigger!==undefined){const type=String(data.trigger?.type||data.trigger).toLowerCase();if(!AUTOMATION_TRIGGERS.has(type))throw crmError(400,'crm_automation_invalid','Niet-ondersteunde automationtrigger');data.trigger={...(typeof data.trigger==='object'?data.trigger:{}),type}}if(data.actions!==undefined){if(!Array.isArray(data.actions)||!data.actions.length||data.actions.length>20)throw crmError(400,'crm_automation_invalid','Een automation heeft 1–20 acties nodig');data.actions=data.actions.map(action=>{const type=String(action?.type||'').toLowerCase();if(!AUTOMATION_ACTIONS.has(type))throw crmError(400,'crm_automation_invalid',`Niet-ondersteunde automationactie: ${type}`);return {...sanitizeInput(action),type}})}if(!partial&&(!data.trigger||!data.actions))throw crmError(400,'crm_automation_invalid','Trigger en acties zijn verplicht')}
  validateDashboard(data,partial){if(data.share_mode!==undefined&&!['PRIVATE','TEAM'].includes(String(data.share_mode).toUpperCase()))throw crmError(400,'crm_dashboard_invalid','Dashboard kan PRIVATE of TEAM gedeeld worden');if(data.share_mode)data.share_mode=String(data.share_mode).toUpperCase();if(data.widgets!==undefined){if(!Array.isArray(data.widgets)||data.widgets.length>24)throw crmError(400,'crm_dashboard_invalid','Een dashboard ondersteunt maximaal 24 widgets');data.widgets=data.widgets.map((widget,index)=>{const type=String(widget.type||'KPI').toUpperCase();if(!DASHBOARD_WIDGET_TYPES.has(type))throw crmError(400,'crm_dashboard_invalid',`Niet-ondersteund widgettype: ${type}`);const w=clamp(Math.round(finite(widget.w,4)),1,12),h=clamp(Math.round(finite(widget.h,3)),1,12),x=clamp(Math.round(finite(widget.x)),0,12-w);return {id:safeId(widget.id)||`widget-${index+1}`,type,metric:safeString(widget.metric||'',64),x,y:clamp(Math.round(finite(widget.y)),0,200),w,h,filters:sanitizeInput(widget.filters||{})}})}if(!partial&&!data.widgets)throw crmError(400,'crm_dashboard_invalid','Dashboardwidgets zijn verplicht')}
  audit(ctx,principal,action,entity,recordId,changes={},meta={}){
    const row={id:this.adapter.id(),tenant_id:ctx.tenant_id,dealer_id:ctx.dealer_id,entity_type:'audit_event',action,entity,record_id:recordId||null,actor_id:principal.id,actor_roles:principal.roles,changes:sanitizeInput(changes),meta:sanitizeInput(meta),created_at:this.adapter.now().toISOString()};
    const bucket=this.collection(ctx,'audit_events');bucket.unshift(row);if(bucket.length>10000)bucket.splice(10000);return row;
  }
  emit(ctx,type,message,meta){this.adapter.emit(ctx,{type:`crm.${type}`,message:safeString(message,240),meta:sanitizeInput(meta||{})})}
  runIdempotent(ctx,principal,key,signature,operation){
    if(!key)return operation();const normalized=safeString(key,200);if(!/^[A-Za-z0-9_.:-]{8,200}$/.test(normalized))throw crmError(400,'crm_idempotency_invalid','Ongeldige Idempotency-Key');
    const digest=sha(`${principal.id}:${normalized}`),bucket=this.adapter.bucket(ctx,'crm:idempotency'),existing=bucket.find(row=>row.digest===digest);
    if(existing){if(existing.signature!==signature)throw crmError(409,'crm_idempotency_conflict','Idempotency-Key is al voor een andere mutatie gebruikt');return {...deepClone(existing.result),idempotent_replay:true}}
    const result=operation();bucket.push({digest,signature,result:deepClone(result),created_at:this.adapter.now().toISOString()});if(bucket.length>2000)bucket.splice(0,bucket.length-2000);this.commit();return result;
  }
  create(context,principalInput,entityInput,input,options={}){
    const {ctx,principal}=this.context(context,principalInput),entity=this.assertEntity(entityInput);this.assertCreate(entity,principal);const data=this.validate(entity,input),signature=sha(JSON.stringify({entity,data}));
    return this.runIdempotent(ctx,principal,options.idempotencyKey,signature,()=>{const now=this.adapter.now().toISOString(),row={...data,id:this.adapter.id(),tenant_id:ctx.tenant_id,dealer_id:ctx.dealer_id,entity_type:ENTITY_SINGULAR[entity]||entity.replace(/s$/,''),owner_id:data.owner_id||(['contacts','leads','opportunities','deals','tasks','appointments'].includes(entity)?principal.id:data.owner_id),created_at:now,created_by:principal.id,updated_at:now,updated_by:principal.id,revision:1};const bucket=this.collection(ctx,entity);bucket.push(row);if(bucket.length>MAX_COLLECTION_SIZE)throw crmError(507,'crm_capacity_reached','CRM-collectielimiet bereikt');this.audit(ctx,principal,'CREATE',entity,row.id,{fields:Object.keys(data)});this.emit(ctx,'record.created',`${entity} record aangemaakt`,{entity,record_id:row.id});this.commit();return deepClone(row)})
  }
  list(context,principalInput,entityInput,query={}){
    const {ctx,principal}=this.context(context,principalInput),entity=this.assertEntity(entityInput);this.assertRead(principal);const limit=clamp(Math.round(finite(query.limit,50)),1,200),offset=clamp(Math.round(finite(query.cursor,0)),0,1000000),q=safeString(query.q||'',200).toLowerCase(),filters=sanitizeInput(query.filters||{});let rows=this.collection(ctx,entity).filter(row=>!row.deleted_at&&this.canReadRecord(row,principal));
    if(q)rows=rows.filter(row=>[row.name,row.title,row.email,row.phone,row.company_name,row.status,row.number,...(Array.isArray(row.tags)?row.tags:[])].some(value=>String(value||'').toLowerCase().includes(q)));
    for(const [field,value] of Object.entries(filters))if(SAFE_FIELD.test(field)&&value!==''&&value!==undefined&&value!==null)rows=rows.filter(row=>Array.isArray(row[field])?row[field].map(String).includes(String(value)):String(row[field]??'')===String(value));
    const total=rows.length;sortRows(rows,String(query.sort||'updated_at'),query.order);const items=rows.slice(offset,offset+limit).map(deepClone);return {items,total,limit,next_cursor:offset+limit<total?String(offset+limit):null};
  }
  get(context,principalInput,entityInput,idInput,{includeDeleted=false}={}){const {ctx,principal}=this.context(context,principalInput),entity=this.assertEntity(entityInput);this.assertRead(principal);const record=this.collection(ctx,entity).find(row=>row.id===idInput&&(includeDeleted||!row.deleted_at));if(!record||!this.canReadRecord(record,principal))throw crmError(404,'crm_record_not_found','CRM-record niet gevonden');return deepClone(record)}
  update(context,principalInput,entityInput,idInput,input,options={}){
    const {ctx,principal}=this.context(context,principalInput),entity=this.assertEntity(entityInput),data=this.validate(entity,input,{partial:true}),signature=sha(JSON.stringify({entity,idInput,data,revision:options.expectedRevision||null}));
    return this.runIdempotent(ctx,principal,options.idempotencyKey,signature,()=>{const bucket=this.collection(ctx,entity),index=bucket.findIndex(row=>row.id===idInput&&!row.deleted_at),record=bucket[index];if(!record||!this.canWriteRecord(record,principal))throw crmError(record?403:404,record?'crm_forbidden':'crm_record_not_found',record?'Deze CRM-mutatie is niet toegestaan':'CRM-record niet gevonden');if(ENTITY_DEFINITIONS[entity].readOnly)throw crmError(405,'crm_entity_read_only','Deze CRM-collectie is alleen-lezen');if(options.expectedRevision!==undefined&&Number(options.expectedRevision)!==Number(record.revision))throw crmError(409,'crm_revision_conflict','CRM-record is ondertussen gewijzigd',{current_revision:record.revision});const changed={};for(const [field,value] of Object.entries(data))if(JSON.stringify(record[field])!==JSON.stringify(value))changed[field]={from:record[field]??null,to:value};const next={...record,...data,tenant_id:ctx.tenant_id,dealer_id:ctx.dealer_id,id:record.id,created_at:record.created_at,created_by:record.created_by,updated_at:this.adapter.now().toISOString(),updated_by:principal.id,revision:Number(record.revision||0)+1};bucket[index]=next;this.audit(ctx,principal,'UPDATE',entity,next.id,changed);this.emit(ctx,'record.updated',`${entity} record bijgewerkt`,{entity,record_id:next.id,fields:Object.keys(changed)});this.commit();return deepClone(next)})
  }
  remove(context,principalInput,entityInput,idInput,options={}){const {ctx,principal}=this.context(context,principalInput),entity=this.assertEntity(entityInput);if(ENTITY_DEFINITIONS[entity].readOnly)throw crmError(405,'crm_entity_read_only','Deze CRM-collectie is alleen-lezen');const signature=sha(`${entity}:${idInput}:delete`);return this.runIdempotent(ctx,principal,options.idempotencyKey,signature,()=>{const bucket=this.collection(ctx,entity),index=bucket.findIndex(row=>row.id===idInput&&!row.deleted_at),record=bucket[index];if(!record||!this.canWriteRecord(record,principal))throw crmError(record?403:404,record?'crm_forbidden':'crm_record_not_found',record?'Deze CRM-mutatie is niet toegestaan':'CRM-record niet gevonden');const now=this.adapter.now().toISOString();bucket[index]={...record,deleted_at:now,deleted_by:principal.id,updated_at:now,updated_by:principal.id,revision:Number(record.revision||0)+1};this.audit(ctx,principal,'DELETE',entity,idInput,{});this.emit(ctx,'record.deleted',`${entity} record gearchiveerd`,{entity,record_id:idInput});this.commit();return {ok:true,id:idInput,deleted_at:now}})}
  moveDeal(context,principalInput,dealId,stageId,options={}){const {ctx}=this.context(context,principalInput),stage=this.get(context,principalInput,'stages',stageId),deal=this.get(context,principalInput,'deals',dealId);if(stage.pipeline_id!==deal.pipeline_id)throw crmError(409,'crm_stage_pipeline_mismatch','Fase hoort niet bij de pipeline van deze deal');const next=this.update(context,principalInput,'deals',dealId,{stage_id:stage.id,probability:stage.probability??deal.probability,status:stage.status||deal.status,stage_history:[...(deal.stage_history||[]).slice(-49),{stage_id:stage.id,at:this.adapter.now().toISOString()}]},{...options,expectedRevision:options.expectedRevision??deal.revision});this.evaluateAutomations(ctx,principalShape(principalInput),{id:options.eventId||this.adapter.id(),type:'stage_change',entity:'deals',record_id:dealId,before:{stage_id:deal.stage_id},after:{stage_id:stage.id}});return next}
  pipelineBoard(context,principalInput,pipelineId){const pipeline=this.get(context,principalInput,'pipelines',pipelineId),stages=this.list(context,principalInput,'stages',{limit:200,filters:{pipeline_id:pipelineId},sort:'position',order:'asc'}).items,deals=this.list(context,principalInput,'deals',{limit:200,filters:{pipeline_id:pipelineId},sort:'updated_at',order:'desc'}).items;return {pipeline,stages:stages.map(stage=>({...stage,deals:deals.filter(deal=>deal.stage_id===stage.id),value:deals.filter(deal=>deal.stage_id===stage.id).reduce((sum,deal)=>sum+finite(deal.value),0)})),unassigned:deals.filter(deal=>!stages.some(stage=>stage.id===deal.stage_id)),observed_at:this.adapter.now().toISOString()}}
  customer360(context,principalInput,idInput){
    const {ctx,principal}=this.context(context,principalInput);this.assertRead(principal);const subject=['contacts','people','leads'].flatMap(entity=>this.collection(ctx,entity).filter(row=>!row.deleted_at&&row.id===idInput&&this.canReadRecord(row,principal)).map(row=>({entity,row})))[0];if(!subject)throw crmError(404,'crm_customer_not_found','Contact of lead niet gevonden');const row=subject.row,related=entity=>this.collection(ctx,entity).filter(item=>!item.deleted_at&&this.canReadRecord(item,principal)&&(item.contact_id===row.id||item.person_id===row.id||item.lead_id===row.id||row.company_id&&item.company_id===row.company_id)).map(deepClone),timeline=['activities','tasks','appointments','notes','calls','emails','messages','consents'].flatMap(entity=>related(entity).map(item=>({...item,timeline_type:entity}))).sort((a,b)=>Date.parse(b.occurred_at||b.scheduled_at||b.consented_at||b.revoked_at||b.created_at||0)-Date.parse(a.occurred_at||a.scheduled_at||a.consented_at||a.revoked_at||a.created_at||0)),history=this.collection(ctx,'audit_events').filter(item=>item.record_id===row.id&&this.canReadRecord(item,principal)).sort((a,b)=>Date.parse(b.created_at||0)-Date.parse(a.created_at||0)).slice(0,300).map(deepClone);const companies=row.company_id?this.collection(ctx,'companies').filter(item=>item.id===row.company_id&&!item.deleted_at).map(deepClone):[];return {subject_type:subject.entity,subject:deepClone(row),companies,opportunities:related('opportunities'),deals:related('deals'),communications:{calls:related('calls'),emails:related('emails'),messages:related('messages')},tasks:related('tasks'),appointments:related('appointments'),notes:related('notes'),documents:related('documents'),products:[...related('products'),...related('vehicles')],campaigns:related('attributions'),consents:related('consents'),timeline:timeline.slice(0,300),history,observed_at:this.adapter.now().toISOString(),source:'foundly_crm_persisted_records'}
  }
  inventoryCustomerMatches(context,principalInput,inventoryIdInput,{limit=20}={}){
    const {ctx,principal}=this.context(context,principalInput);this.assertRead(principal);const inventoryId=safeId(inventoryIdInput);if(!inventoryId)throw crmError(400,'crm_inventory_invalid','Geldig product- of voertuig-id is verplicht');const inventory=['vehicles','products'].flatMap(entity=>this.collection(ctx,entity).filter(row=>!row.deleted_at&&row.id===inventoryId&&this.canReadRecord(row,principal)).map(row=>({entity,row})))[0];if(!inventory)throw crmError(404,'crm_inventory_not_found','Product of voertuig niet gevonden');const relations=this.collection(ctx,'inventory_relations').filter(row=>!row.deleted_at&&row.inventory_id===inventoryId&&this.canReadRecord(row,principal)),subjects=['contacts','people','leads'].flatMap(entity=>this.collection(ctx,entity).filter(row=>!row.deleted_at&&this.canReadRecord(row,principal)).map(row=>({entity,row}))),byId=new Map(subjects.map(item=>[item.row.id,item])),matches=[];
    for(const relation of relations){const subjectId=relation.contact_id||relation.person_id||relation.lead_id||relation.subject_id,subject=byId.get(subjectId);if(!subject)continue;const score=clamp(finite(relation.match_score??relation.score),0,100),reasons=(Array.isArray(relation.reasons)?relation.reasons:[relation.reason||relation.relationship||relation.type]).map(value=>safeString(value,240)).filter(Boolean).slice(0,12),candidate={customer_type:subject.entity,customer:deepClone(subject.row),relation:deepClone(relation),match_score:score,reasons,inference:'explicit_persisted_inventory_relation'};const existing=matches.findIndex(item=>item.customer.id===subject.row.id);if(existing<0)matches.push(candidate);else if(score>matches[existing].match_score)matches[existing]=candidate}
    matches.sort((a,b)=>b.match_score-a.match_score||String(a.customer.name||a.customer.id).localeCompare(String(b.customer.name||b.customer.id)));return {inventory_type:inventory.entity,inventory:deepClone(inventory.row),items:matches.slice(0,clamp(Number(limit)||20,1,100)),total:matches.length,observed_at:this.adapter.now().toISOString(),source:'foundly_crm_persisted_records',rule:'explicit_inventory_relations_only',no_fake_data:true}
  }
  priorityLeads(context,principalInput,{limit=20,filters={}}={}){const now=this.adapter.now().getTime(),normalizedFilters=analyticsFilters(filters),leads=this.list(context,principalInput,'leads',{limit:200,sort:'updated_at',order:'desc'}).items.filter(row=>matchesAnalyticsFilters(row,normalizedFilters)),dealFilters={...normalizedFilters};delete dealFilters.status;const deals=this.list(context,principalInput,'deals',{limit:200}).items.filter(row=>matchesAnalyticsFilters(row,dealFilters));const items=leads.map(lead=>{const linked=deals.filter(deal=>deal.lead_id===lead.id),daysSinceContact=lead.last_contacted_at?Math.max(0,(now-Date.parse(lead.last_contacted_at))/864e5):null,daysOld=Math.max(0,(now-Date.parse(lead.created_at))/864e5),value=linked.reduce((sum,deal)=>sum+finite(deal.value),0),reasons=[];let score=clamp(finite(lead.score,35),0,100);if(/qualified|hot|warm/i.test(String(lead.status)))score+=18,reasons.push('gekwalificeerde status');if(value>0)score+=Math.min(18,Math.log10(value+1)*4),reasons.push('gekoppelde pipelinewaarde');if(lead.next_action_at&&Date.parse(lead.next_action_at)<=now+864e5)score+=12,reasons.push('volgende actie is nu relevant');if(daysSinceContact===null||daysSinceContact>3)score+=10,reasons.push('contactmoment ontbreekt of is ouder');if(daysOld<7)score+=6,reasons.push('recente lead');if(String(lead.consent_status||'').toUpperCase()==='REVOKED')score-=35,reasons.push('toestemming ingetrokken');return {lead,priority_score:Number(clamp(score,0,100).toFixed(1)),reasons,linked_deal_value:Number(value.toFixed(2)),inference:'deterministic_from_persisted_crm_fields'}}).sort((a,b)=>b.priority_score-a.priority_score);return {items:items.slice(0,clamp(Number(limit)||20,1,100)),total:items.length,filters:normalizedFilters,observed_at:this.adapter.now().toISOString(),source:'foundly_crm_persisted_records',empty:items.length===0}}
  analytics(context,principalInput,options={}){
    const {ctx,principal}=this.context(context,principalInput);requirePermission(principal,'crm:analytics');const from=iso(options.from),to=iso(options.to),filters=analyticsFilters(options.filters),rows=entity=>this.collection(ctx,entity).filter(row=>!row.deleted_at&&this.canReadRecord(row,principal)&&dateInRange(row.created_at,from,to)&&matchesAnalyticsFilters(row,filters));const leads=rows('leads'),deals=rows('deals'),tasks=rows('tasks'),appointments=rows('appointments'),activities=rows('activities'),attributions=rows('attributions'),campaigns=rows('campaigns'),won=deals.filter(deal=>/won|gewonnen/i.test(String(deal.status))),lost=deals.filter(deal=>/lost|verloren/i.test(String(deal.status))),open=deals.filter(deal=>!won.includes(deal)&&!lost.includes(deal)),qualified=leads.filter(lead=>/qualified|gekwalificeerd|hot/i.test(String(lead.status))||lead.qualified_at),leadIds=new Set(deals.map(deal=>deal.lead_id).filter(Boolean)),value=list=>list.reduce((sum,row)=>sum+finite(row.value||row.amount),0),margin=list=>list.reduce((sum,row)=>sum+finite(row.margin),0),salesCycles=won.map(deal=>{const start=Date.parse(deal.created_at),end=Date.parse(deal.closed_at||deal.won_at);return Number.isFinite(start)&&Number.isFinite(end)?(end-start)/864e5:NaN}),responseTimes=leads.map(lead=>{const first=activities.filter(activity=>activity.lead_id===lead.id).sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at))[0];return first?(Date.parse(first.created_at)-Date.parse(lead.created_at))/36e5:NaN}),completedTasks=tasks.filter(task=>/done|completed|afgerond/i.test(String(task.status))),noShows=appointments.filter(item=>/no.?show|niet verschenen/i.test(String(item.status))),forecast=open.reduce((sum,deal)=>sum+finite(deal.value)*clamp(finite(deal.probability),0,100)/100,0),bySource={},leadById=new Map(leads.map(lead=>[lead.id,lead]));for(const lead of leads){const source=String(lead.source_id||lead.source||'onbekend');bySource[source]??={leads:0,deals:0,value:0};bySource[source].leads++}for(const deal of deals){const sourceLead=leadById.get(deal.lead_id),source=String(deal.source_id||deal.source||sourceLead?.source_id||sourceLead?.source||'onbekend');bySource[source]??={leads:0,deals:0,value:0};bySource[source].deals++;bySource[source].value+=finite(deal.value)}const byOwner={};for(const deal of deals){const owner=String(deal.owner_id||'niet_toegewezen');byOwner[owner]??={deals:0,won:0,value:0};byOwner[owner].deals++;byOwner[owner].value+=finite(deal.value);if(won.includes(deal))byOwner[owner].won++}
    const myLeads=leads.filter(row=>row.owner_id===principal.id),myTasks=tasks.filter(row=>row.owner_id===principal.id),myOpenDeals=open.filter(row=>row.owner_id===principal.id),metrics={leads:metric(leads.length,'count',leads.length),qualified_leads:metric(qualified.length,'count',leads.length),pipeline_value:metric(value(open),'currency',open.length),won_value:metric(value(won),'currency',won.length),lost_value:metric(value(lost),'currency',lost.length),conversion:metric(leads.length?leadIds.size/leads.length*100:null,'percent',leads.length),win_rate:metric(won.length+lost.length?won.length/(won.length+lost.length)*100:null,'percent',won.length+lost.length),average_deal_value:metric(deals.length?value(deals)/deals.length:null,'currency',deals.length),margin:metric(margin(deals),'currency',deals.filter(deal=>Number.isFinite(Number(deal.margin))).length),sales_cycle:metric(average(salesCycles),'days',salesCycles.filter(Number.isFinite).length),response_time:metric(average(responseTimes),'hours',responseTimes.filter(Number.isFinite).length),follow_up_rate:metric(tasks.length?completedTasks.length/tasks.length*100:null,'percent',tasks.length),appointments:metric(appointments.length,'count',appointments.length),no_show_rate:metric(appointments.length?noShows.length/appointments.length*100:null,'percent',appointments.length),forecast:metric(forecast,'currency',open.length),open_tasks:metric(tasks.filter(task=>!/done|completed|afgerond|cancel/i.test(String(task.status))).length,'count',tasks.length),my_leads:metric(myLeads.length,'count',myLeads.length),my_tasks:metric(myTasks.filter(task=>!/done|completed|afgerond|cancel/i.test(String(task.status))).length,'count',myTasks.length),my_pipeline:metric(value(myOpenDeals),'currency',myOpenDeals.length)};
    const stages=this.collection(ctx,'stages').filter(row=>!row.deleted_at&&this.canReadRecord(row,principal)&&(!filters.pipeline_id||row.pipeline_id===filters.pipeline_id)&&(!filters.stage_id||row.id===filters.stage_id)).sort((a,b)=>finite(a.position)-finite(b.position));
    const pipeline_stages=stages.map(stage=>{const stageDeals=deals.filter(deal=>deal.stage_id===stage.id);return {id:stage.id,name:stage.name,pipeline_id:stage.pipeline_id,position:finite(stage.position),deals:stageDeals.length,value:Number(value(stageDeals).toFixed(2)),probability:finite(stage.probability)}});
    const trendByDay={};for(const lead of leads){const day=dayKey(lead.created_at);if(day){trendByDay[day]??={date:day,leads:0,deals:0,won_value:0};trendByDay[day].leads++}}for(const deal of deals){const day=dayKey(deal.created_at);if(day){trendByDay[day]??={date:day,leads:0,deals:0,won_value:0};trendByDay[day].deals++;if(won.includes(deal))trendByDay[day].won_value+=finite(deal.value)}}
    const stalledCutoff=this.adapter.now().getTime()-7*864e5,stalled_deals=open.filter(deal=>Date.parse(deal.next_action_at||deal.updated_at||deal.created_at)<stalledCutoff||deal.next_action_at&&Date.parse(deal.next_action_at)<this.adapter.now().getTime()).map(deal=>({id:deal.id,title:deal.title,value:finite(deal.value),owner_id:deal.owner_id||null,stage_id:deal.stage_id||null,next_action_at:deal.next_action_at||null,updated_at:deal.updated_at})).slice(0,50);
    const activity_feed=[...activities].sort((a,b)=>Date.parse(b.occurred_at||b.created_at||0)-Date.parse(a.occurred_at||a.created_at||0)).slice(0,30).map(row=>({id:row.id,type:row.type||row.entity_type||'activity',summary:row.summary||row.title||null,status:row.status||null,owner_id:row.owner_id||null,at:row.occurred_at||row.created_at}));
    return {ok:true,observed_at:this.adapter.now().toISOString(),range:{from,to},filters,metrics,pipeline_stages,trends:{lead_trend:Object.values(trendByDay).sort((a,b)=>a.date.localeCompare(b.date))},stalled_deals,activity_feed,source_performance:Object.entries(bySource).map(([source_id,data])=>({source_id,...data,value:Number(data.value.toFixed(2))})).sort((a,b)=>b.value-a.value),owner_performance:Object.entries(byOwner).map(([owner_id,data])=>({owner_id,...data,value:Number(data.value.toFixed(2)),win_rate:data.deals?Number((data.won/data.deals*100).toFixed(2)):null})).sort((a,b)=>b.value-a.value),campaigns:campaigns.map(campaign=>({id:campaign.id,name:campaign.name,attributions:attributions.filter(row=>row.campaign_id===campaign.id).length})),counts:{activities:activities.length,tasks:tasks.length,appointments:appointments.length},source:'foundly_crm_persisted_records',no_fake_data:true}
  }
  analyticsWithComparison(context,principalInput,options={}){const current=this.analytics(context,principalInput,options);if(!options.compare)return current;const previousRange=comparisonRange(current.range.from,current.range.to);if(!previousRange)return {...current,comparison:{available:false,reason:'Een geldige vanaf- en tot-datum is nodig voor periodevergelijking'}};const previous=this.analytics(context,principalInput,{...options,...previousRange,compare:false}),metrics={};for(const [name,item] of Object.entries(current.metrics)){const prior=previous.metrics[name],available=Boolean(item?.available||prior?.available),currentValue=Number(item?.value),previousValue=Number(prior?.value),absolute=Number.isFinite(currentValue)&&Number.isFinite(previousValue)?currentValue-previousValue:null,percent=absolute!==null&&previousValue!==0?absolute/Math.abs(previousValue)*100:null;metrics[name]={available,current:item?.value??null,previous:prior?.value??null,unit:item?.unit||prior?.unit||null,absolute_delta:absolute===null?null:Number(absolute.toFixed(2)),percent_delta:percent===null?null:Number(percent.toFixed(2))}}return {...current,comparison:{available:true,range:previousRange,metrics,source:'foundly_crm_persisted_records'}}}
  activityVersion(context,principalInput){const {ctx,principal}=this.context(context,principalInput);requirePermission(principal,'crm:dashboard');const rows=this.collection(ctx,'audit_events').filter(row=>!row.deleted_at&&this.canReadRecord(row,principal)),latest=rows.slice().sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at)||String(b.id).localeCompare(String(a.id)))[0];return {change_token:sha(`${rows.length}:${latest?.created_at||''}:${latest?.id||''}`).slice(0,24),last_change_at:latest?.created_at||null,changes:rows.length}}
  dashboard(context,principalInput,{id,preset='SALES',forcePreset=false}={}){const {ctx,principal}=this.context(context,principalInput);requirePermission(principal,'crm:dashboard');if(id){const row=this.collection(ctx,'dashboard_views').find(item=>item.id===id&&!item.deleted_at&&(item.owner_id===principal.id||item.share_mode==='TEAM'&&item.team_id&&principal.team_ids.includes(item.team_id)||hasPermission(principal,'crm:read_all')));if(!row)throw crmError(404,'crm_dashboard_not_found','Dashboardweergave niet gevonden');return deepClone(row)}if(forcePreset)return presetDashboard(preset,principal.id);const saved=this.collection(ctx,'dashboard_views').find(item=>!item.deleted_at&&item.owner_id===principal.id&&item.is_default);return saved?deepClone(saved):presetDashboard(preset,principal.id)}
  saveDashboard(context,principalInput,input,options={}){const {ctx,principal}=this.context(context,principalInput);requirePermission(principal,'crm:dashboard');const desired={...input,owner_id:principal.id,persisted:true};if(String(desired.share_mode||'PRIVATE').toUpperCase()==='TEAM'){const teamId=safeId(desired.team_id);if(!teamId)throw crmError(400,'crm_dashboard_invalid','Een team-id is verplicht om een dashboard met een team te delen');if(!hasPermission(principal,'crm:manage')&&!principal.team_ids.includes(teamId))throw crmError(403,'crm_forbidden','Dashboard kan alleen met een eigen team worden gedeeld');desired.team_id=teamId}else delete desired.team_id;if(desired.is_default)for(const row of this.collection(ctx,'dashboard_views'))if(!row.deleted_at&&row.owner_id===principal.id&&row.id!==input.id&&row.is_default){row.is_default=false;row.updated_at=this.adapter.now().toISOString();row.updated_by=principal.id;row.revision=Number(row.revision||0)+1;this.audit(ctx,principal,'UPDATE','dashboard_views',row.id,{is_default:{from:true,to:false}})}if(input.id){const current=this.get(context,principalInput,'dashboard_views',input.id);if(current.owner_id!==principal.id&&!hasPermission(principal,'crm:manage'))throw crmError(403,'crm_forbidden','Alleen de eigenaar kan dit dashboard wijzigen');return this.update(context,principalInput,'dashboard_views',input.id,desired,options)}return this.create(context,principalInput,'dashboard_views',desired,options)}
  evaluateAutomations(ctxInput,principalInput,eventInput){
    const ctx=normalizeContext(ctxInput),principal=principalShape(principalInput),event=sanitizeInput(eventInput);requirePermission(principal,'crm:automate');if(!safeId(event.id)||!AUTOMATION_TRIGGERS.has(String(event.type||'').toLowerCase()))throw crmError(400,'crm_event_invalid','Automationevent is ongeldig');const eventType=String(event.type).toLowerCase(),executions=this.collection(ctx,'automation_executions');if(executions.some(row=>row.event_id===event.id))return {event_id:event.id,replayed:true,executions:executions.filter(row=>row.event_id===event.id).map(deepClone)};const definitions=this.collection(ctx,'automations').filter(row=>!row.deleted_at&&row.enabled!==false&&String(row.trigger?.type||row.trigger).toLowerCase()===eventType),results=[];
    for(const automation of definitions.slice(0,25)){
      const conditions=automation.trigger?.conditions||{},matches=Object.entries(conditions).every(([field,value])=>String(event.after?.[field]??event.record?.[field]??'')===String(value));if(!matches)continue;const actionResults=[];
      for(const action of automation.actions.slice(0,20)){
        const type=String(action.type).toLowerCase();
        if(type==='task'||type==='follow_up'||type==='zero_task'){const task={id:this.adapter.id(),tenant_id:ctx.tenant_id,dealer_id:ctx.dealer_id,entity_type:'task',title:safeString(action.title||`Automation: ${automation.name}`,240),status:'OPEN',owner_id:safeId(action.owner_id)||safeId(event.after?.owner_id)||safeId(event.record?.owner_id)||principal.id,source:'crm_automation',automation_id:automation.id,related_entity:event.entity||null,related_id:event.record_id||null,created_at:this.adapter.now().toISOString(),created_by:'crm-automation',updated_at:this.adapter.now().toISOString(),updated_by:'crm-automation',revision:1};this.collection(ctx,'tasks').push(task);actionResults.push({type,status:'EXECUTED_INTERNAL',record_id:task.id,external_write:false})}
        else if(['message','email','webhook'].includes(type))actionResults.push({type,status:'AWAITING_EXPLICIT_AUTHORIZATION',external_write:false,connector_required:true});
        else if(type==='notify')actionResults.push({type,status:'RECORDED_INTERNAL',external_write:false,message:safeString(action.message||automation.name,240)});
        else actionResults.push({type,status:'PLANNED_REQUIRES_VERIFIED_TARGET',external_write:false});
      }
      const execution={id:this.adapter.id(),tenant_id:ctx.tenant_id,dealer_id:ctx.dealer_id,entity_type:'automation_execution',automation_id:automation.id,event_id:event.id,event_type:eventType,status:actionResults.every(row=>!row.status.startsWith('AWAITING'))?'COMPLETED':'PARTIAL',actions:actionResults,created_at:this.adapter.now().toISOString()};executions.push(execution);results.push(deepClone(execution));this.audit(ctx,principal,'AUTOMATION_EXECUTE','automations',automation.id,{event_id:event.id,action_count:actionResults.length});
    }
    this.emit(ctx,'automation.evaluated','CRM-automationevent verwerkt',{event_id:event.id,event_type:eventType,executions:results.length});this.commit();return {event_id:event.id,replayed:false,executions:results}
  }
  provisionProfile(context,principalInput,input={},options={}){
    const {ctx,principal}=this.context(context,principalInput);requirePermission(principal,'crm:manage');const profile=sanitizeInput(input),name=safeString(profile.business_name||profile.name,160),country=safeString(profile.country||profile.market,80),industry=safeString(profile.industry,80),segment=safeString(profile.segment,80);if(!name||!country||!industry||!segment)throw crmError(400,'crm_profile_invalid','business_name, country, industry en segment zijn verplicht');
    const list=(value,fallback=[],maximum=40)=>Array.isArray(value)?value.map(item=>safeString(item,64)).filter(Boolean).slice(0,maximum):fallback,preset=String(profile.dashboard_preset||'SALES').toUpperCase().replace(/\s+/g,'_'),presetName=PRESET_WIDGETS[preset]?preset:'SALES',kpis=[...new Set((PRESET_WIDGETS[presetName]||[]).map(([metricId])=>metricId))],normalized={business_name:name,country,industry,segment,capabilities:list(profile.capabilities,['crm','contacts','pipelines','activities','analytics','automations']),engines:list(profile.engines,['crm','analytics','automation']),regions:list(profile.regions,[country]),crm_config:{locale:safeString(profile.crm_config?.locale||profile.locale||'nl-NL',32),currency:safeString(profile.crm_config?.currency||profile.currency||'EUR',8),timezone:safeString(profile.crm_config?.timezone||profile.timezone||'Europe/Amsterdam',64),industry,segment},pipelines:[{name:'Sales',purpose:'general_sales'}],kpis:list(profile.kpis,kpis),connectors:list(profile.connectors,[]),zero_tools:['crm_priority_leads','crm_pipeline_summary','crm_customer_360','crm_inventory_customer_matches'],workflows:list(profile.workflows,[]),permissions:{roles:Object.keys(ROLE_PERMISSIONS)},dashboard_preset:presetName,schema_version:1};const signature=sha(JSON.stringify(normalized)),idempotencyKey=options.idempotencyKey||`provision:${sha(`${ctx.tenant_id}:${ctx.dealer_id}:${signature}`).slice(0,32)}`;
    return this.runIdempotent(ctx,principal,idempotencyKey,signature,()=>{const tenant=this.create(ctx,principal,'tenants',{name,business_profile:normalized},{idempotencyKey:`${idempotencyKey}:tenant`}),pipeline=this.create(ctx,principal,'pipelines',{name:'Sales',purpose:'general_sales',country,industry,segment,is_default:true},{idempotencyKey:`${idempotencyKey}:pipeline`}),stageSpecs=[['Nieuw',10,'OPEN'],['Gekwalificeerd',30,'OPEN'],['Voorstel',60,'OPEN'],['Onderhandeling',80,'OPEN'],['Gewonnen',100,'WON'],['Verloren',0,'LOST']],stages=stageSpecs.map(([stageName,probability,status],index)=>this.create(ctx,principal,'stages',{name:stageName,pipeline_id:pipeline.id,position:index+1,probability,status},{idempotencyKey:`${idempotencyKey}:stage:${index+1}`})),dashboard=this.saveDashboard(ctx,principal,{...presetDashboard(normalized.dashboard_preset,principal.id),id:undefined,name:`${name} Sales`,is_default:true,business_profile:normalized},{idempotencyKey:`${idempotencyKey}:dashboard`});this.audit(ctx,principal,'PROVISION','tenants',tenant.id,{profile:normalized,pipeline_id:pipeline.id,dashboard_id:dashboard.id});this.emit(ctx,'profile.provisioned','CRM-bedrijfsprofiel ingericht',{tenant_record_id:tenant.id,pipeline_id:pipeline.id,dashboard_id:dashboard.id});this.commit();return {ok:true,profile:normalized,tenant_record:tenant,pipeline,stages,dashboard,created_business_records:0,no_demo_data:true,one_codebase:true}})
  }
  schema(){return {version:1,entities:Object.fromEntries(Object.entries(ENTITY_DEFINITIONS).map(([name,definition])=>[name,{...definition}])),dashboard_widget_types:[...DASHBOARD_WIDGET_TYPES],dashboard_filters:[...ANALYTICS_FILTERS],automation_triggers:[...AUTOMATION_TRIGGERS],automation_actions:[...AUTOMATION_ACTIONS],roles:Object.keys(ROLE_PERMISSIONS),presets:Object.keys(PRESET_WIDGETS),contracts:{tenant_isolation:'adapter_partitioned_trusted_context',deletion:'soft_delete_audited',concurrency:'optimistic_revision',idempotency:'Idempotency-Key',external_writes:'never_without_explicit_authorization_and_connector',analytics:'persisted_records_only',period_comparison:'equal_previous_period',live_updates:'audited_change_token_polling',inventory_customer_matches:'explicit_persisted_relations_only'}}}
  export(context,principalInput,entityInput){const {ctx,principal}=this.context(context,principalInput);requirePermission(principal,'crm:export');const entity=this.assertEntity(entityInput),records=this.collection(ctx,entity).filter(row=>!row.deleted_at&&this.canReadRecord(row,principal)).map(row=>sanitizeInput(row));return {entity,exported_at:this.adapter.now().toISOString(),tenant_id:ctx.tenant_id,records,count:records.length,no_secrets:true}}
}

module.exports={FoundlyCrmCore,ENTITY_DEFINITIONS,ROLE_PERMISSIONS,DASHBOARD_WIDGET_TYPES,AUTOMATION_TRIGGERS,AUTOMATION_ACTIONS,PRESET_WIDGETS,presetDashboard,crmError,sanitizeInput,normalizeContext,principalShape};
