'use strict';

const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const state={schema:null,summary:null,analytics:null,dashboard:null,pipelines:[],board:null,entity:'leads',records:[],editing:false,changeToken:null,polling:false,lastDashboardRefresh:0};
const ENTITY_LABELS={leads:'Leads',contacts:'Contacten',companies:'Bedrijven',deals:'Deals',opportunities:'Opportunities',tasks:'Taken',appointments:'Afspraken',activities:'Activiteiten',notes:'Notities',calls:'Calls',emails:'E-mails',messages:'Berichten',segments:'Segmenten',products:'Producten',vehicles:'Voertuigen',quotes:'Offertes',orders:'Orders',campaigns:'Campagnes'};
const PRIMARY_FIELD={deals:'title',opportunities:'title',tasks:'title',appointments:'title',activities:'type',notes:'content',quotes:'number',orders:'number'};

async function api(path,options={}){
  const response=await fetch(path,{...options,headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})}}),text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text||`HTTP ${response.status}`}}
  if(!response.ok)throw Object.assign(new Error(data.error||data.code||`HTTP ${response.status}`),{status:response.status,code:data.code,data});return data;
}
function toast(message,error=false){const node=$('#toast');node.textContent=String(message);node.className=error?'show error':'show';clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.className='',3800)}
function formatDate(value){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeStyle:'short'}).format(date)}
function formatMetric(metric){if(!metric?.available)return {value:'Geen data',unit:'',available:false};if(metric.unit==='currency')return {value:new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(metric.value||0),unit:'',available:true};if(metric.unit==='percent')return {value:new Intl.NumberFormat('nl-NL',{maximumFractionDigits:1}).format(metric.value||0),unit:'%',available:true};return {value:new Intl.NumberFormat('nl-NL',{maximumFractionDigits:1}).format(metric.value||0),unit:metric.unit==='count'?'':metric.unit,available:true}}
function titleize(value){return String(value||'').replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase())}
function localDate(value){const date=new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function gridClass(widget){return `x-${Math.max(1,Math.min(12,Number(widget.x||0)+1))} w-${Math.max(1,Math.min(12,Number(widget.w||4)))} h-${Math.max(2,Math.min(12,Number(widget.h||3)))}`}
function packWidgets(widgets=[]){let x=0,y=0,rowHeight=0;for(const widget of widgets){widget.w=Math.max(1,Math.min(12,Number(widget.w||4)));widget.h=Math.max(2,Math.min(12,Number(widget.h||3)));if(x+widget.w>12){x=0;y+=rowHeight||3;rowHeight=0}widget.x=x;widget.y=y;x+=widget.w;rowHeight=Math.max(rowHeight,widget.h);if(x>=12){x=0;y+=rowHeight;rowHeight=0}}return widgets}
function deltaBody(metricName){const item=state.analytics?.comparison?.metrics?.[metricName];if(!item?.available||item.absolute_delta===null)return '';const sign=item.absolute_delta>0?'+':'';const percent=item.percent_delta===null?'':` · ${sign}${new Intl.NumberFormat('nl-NL',{maximumFractionDigits:1}).format(item.percent_delta)}%`;return `<p class="comparison ${item.absolute_delta<0?'down':'up'}">${sign}${escapeHtml(new Intl.NumberFormat('nl-NL',{maximumFractionDigits:1}).format(item.absolute_delta))}${escapeHtml(percent)} t.o.v. vorige periode</p>`}

function setView(name,entity,section){
  $$('.view').forEach(view=>view.classList.toggle('active',view.id===`view-${name}`));
  const navButtons=$$('#crmNav button'),matching=navButtons.filter(button=>button.dataset.view===name&&(!entity||button.dataset.entity===entity)),active=section?matching.find(button=>button.dataset.section===section):matching[0];
  navButtons.forEach(button=>button.classList.toggle('active',button===active));
  if(entity){state.entity=entity;$('#recordEntity').value=entity}$('#viewTitle').textContent=section?titleize(section):name==='records'?(ENTITY_LABELS[state.entity]||titleize(state.entity)):titleize(name);
  if(name==='dashboard')loadDashboard().catch(showError);if(name==='pipeline')loadPipelines().catch(showError);if(name==='records')loadRecords().catch(showError);if(name==='automation')loadAutomations().catch(showError);if(name==='settings')loadSchema().catch(showError);
}
function showError(error){toast(error.message||error,true)}

async function loadStatus(){const status=await api('/api/crm/status'),node=$('#crmConnection');node.textContent=`LIVE · ${status.records} RECORDS`;node.classList.add('online');if(state.changeToken===null)state.changeToken=status.change_token||null;return status}
async function pollLiveStatus(){if(state.polling)return;state.polling=true;try{const previous=state.changeToken,status=await loadStatus();if(status.change_token&&previous&&status.change_token!==previous){state.changeToken=status.change_token;const active=$('.view.active')?.id;if(active==='view-dashboard'&&!state.editing)await refreshDashboardData();else if(active==='view-records')await loadRecords();else if(active==='view-pipeline')await loadPipelines();else if(active==='view-automation')await loadAutomations()}else if(status.change_token)state.changeToken=status.change_token}catch{$('#crmConnection').classList.remove('online')}finally{state.polling=false}}
async function loadSchema(){if(!state.schema)state.schema=await api('/api/crm/schema');$('#schemaSummary').innerHTML=`<article><h3>${Object.keys(state.schema.entities||{}).length} domeincollecties</h3><p>Tenantisolatie, RBAC, audit, revisions en idempotency.</p></article><article><h3>${(state.schema.dashboard_widget_types||[]).length} widgettypen</h3><p>${(state.schema.dashboard_widget_types||[]).map(escapeHtml).join(' · ')}</p></article><article><h3>Externe writes beschermd</h3><p>${escapeHtml(state.schema.contracts?.external_writes||'Alleen na autorisatie')}</p></article>`;return state.schema}
function dashboardQuery(){const query=new URLSearchParams();if($('#dateFrom').value)query.set('from',new Date(`${$('#dateFrom').value}T00:00:00`).toISOString());if($('#dateTo').value)query.set('to',new Date(`${$('#dateTo').value}T23:59:59.999`).toISOString());if($('#comparePeriod').checked)query.set('compare','true');for(const [field,node] of [['status',$('#dashboardStatusFilter')],['owner_id',$('#dashboardOwnerFilter')],['source_id',$('#dashboardSourceFilter')]])if(node.value.trim())query.set(`filter.${field}`,node.value.trim());return query}
function dashboardSettings(){return {from:$('#dateFrom').value?new Date(`${$('#dateFrom').value}T00:00:00`).toISOString():null,to:$('#dateTo').value?new Date(`${$('#dateTo').value}T23:59:59.999`).toISOString():null,compare:$('#comparePeriod').checked,status:$('#dashboardStatusFilter').value.trim()||null,owner_id:$('#dashboardOwnerFilter').value.trim()||null,source_id:$('#dashboardSourceFilter').value.trim()||null}}
async function loadSummary(){state.summary=await api(`/api/crm/summary?${dashboardQuery()}`);state.analytics=state.summary.analytics;state.lastDashboardRefresh=Date.now();return state.summary}
function syncDashboardControls({filters=true}={}){const dashboard=state.dashboard||{},settings=dashboard.filters||{};$('#dashboardShare').value=dashboard.share_mode||'PRIVATE';$('#dashboardTeam').value=dashboard.team_id||'';$('#dashboardTeamWrap').classList.toggle('hidden',$('#dashboardShare').value!=='TEAM');if(filters&&dashboard.persisted!==false){if(settings.from)$('#dateFrom').value=localDate(settings.from);if(settings.to)$('#dateTo').value=localDate(settings.to);$('#comparePeriod').checked=Boolean(settings.compare);$('#dashboardStatusFilter').value=settings.status||'';$('#dashboardOwnerFilter').value=settings.owner_id||'';$('#dashboardSourceFilter').value=settings.source_id||''}}
async function loadDashboard({forcePreset=false}={}){
  $('#dashboardNotice').classList.remove('ready');$('#dashboardNotice').textContent='Werkelijke CRM-data laden…';
  const preset=$('#dashboardPreset').value.replace(' ','_'),query=new URLSearchParams({preset});if(forcePreset)query.set('force_preset','true');const dashboard=await api(`/api/crm/dashboard?${query}`);state.dashboard=dashboard.dashboard;syncDashboardControls({filters:!forcePreset});const summary=await loadSummary();renderDashboard();$('#dashboardNotice').classList.add('ready');return summary;
}
async function refreshDashboardData(){if(!state.dashboard)return loadDashboard();$('#dashboardNotice').classList.remove('ready');$('#dashboardNotice').textContent='Werkelijke CRM-data vernieuwen…';const summary=await loadSummary();renderDashboard();$('#dashboardNotice').classList.add('ready');$('#dashboardFreshness').textContent=`Laatst gecontroleerd ${new Intl.DateTimeFormat('nl-NL',{timeStyle:'medium'}).format(new Date(state.lastDashboardRefresh))} · alleen vastgelegde CRM-data`;return summary}
function widgetBody(widget){
  const metric=state.analytics?.metrics?.[widget.metric];if(metric){const formatted=formatMetric(metric);return formatted.available?`<div class="metric">${escapeHtml(formatted.value)}<span class="unit">${escapeHtml(formatted.unit)}</span></div>${deltaBody(widget.metric)}<p class="unavailable">${Number(metric.source_count||0)} bronrecords</p>`:`<p class="unavailable">Geen echte brondata voor deze metric.</p>`}
  if(widget.metric==='priority_leads'){const rows=state.summary?.priority_leads?.items||[];return rows.length?`<table><tbody>${rows.slice(0,5).map(item=>`<tr><td>${escapeHtml(item.lead.name)}</td><td>${escapeHtml(item.priority_score)}</td></tr>`).join('')}</tbody></table>`:'<p class="unavailable">Geen echte leads beschikbaar.</p>'}
  if(widget.metric==='source_performance'){const rows=state.analytics?.source_performance||[],maximum=Math.max(...rows.map(item=>item.value||item.leads),1);return rows.length?`<div class="spark">${rows.slice(0,12).map(row=>`<i title="${escapeHtml(row.source_id)} · ${escapeHtml(row.value)}" class="bar-${Math.max(1,Math.min(20,Math.round((row.value||row.leads)/maximum*20)))}"></i>`).join('')}</div><div class="legend">${rows.slice(0,4).map(row=>`<span>${escapeHtml(row.source_id)}</span>`).join('')}</div>`:'<p class="unavailable">Geen bronattributie beschikbaar.</p>'}
  if(widget.metric==='owner_performance'){const rows=state.analytics?.owner_performance||[];return rows.length?`<ol class="leaderboard">${rows.slice(0,6).map(row=>`<li><span>${escapeHtml(row.owner_id)}</span><strong>${escapeHtml(row.deals)} deals · ${escapeHtml(new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(row.value||0))}</strong></li>`).join('')}</ol>`:'<p class="unavailable">Geen verkopersdata beschikbaar.</p>'}
  if(widget.metric==='pipeline'){const rows=state.analytics?.pipeline_stages||[];return rows.length?`<div class="funnel">${rows.map(row=>`<div><span>${escapeHtml(row.name)}</span><strong>${escapeHtml(row.deals)} · ${escapeHtml(new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(row.value||0))}</strong></div>`).join('')}</div>`:'<p class="unavailable">Geen pipelinegegevens beschikbaar.</p>'}
  if(widget.metric==='lead_trend'){const rows=state.analytics?.trends?.lead_trend||[],maximum=Math.max(...rows.map(row=>row.leads),1);return rows.length?`<div class="spark trend">${rows.slice(-20).map(row=>`<i title="${escapeHtml(row.date)} · ${escapeHtml(row.leads)} leads" class="bar-${Math.max(1,Math.min(20,Math.round(row.leads/maximum*20)))}"></i>`).join('')}</div>`:'<p class="unavailable">Geen leadtrend beschikbaar.</p>'}
  if(widget.metric==='campaign_attribution'){const rows=state.analytics?.campaigns||[];return rows.length?`<table><tbody>${rows.slice(0,8).map(row=>`<tr><td>${escapeHtml(row.name)}</td><td>${escapeHtml(row.attributions)}</td></tr>`).join('')}</tbody></table>`:'<p class="unavailable">Geen campagne-attributie beschikbaar.</p>'}
  if(widget.metric==='stalled_deals'){const rows=state.analytics?.stalled_deals||[];return rows.length?`<table><tbody>${rows.slice(0,8).map(row=>`<tr><td>${escapeHtml(row.title)}</td><td>${escapeHtml(formatDate(row.next_action_at||row.updated_at))}</td></tr>`).join('')}</tbody></table>`:'<p class="unavailable">Geen vastgelopen deals volgens het deterministische contract.</p>'}
  if(widget.metric==='activity'){const rows=state.analytics?.activity_feed||[];return rows.length?`<div class="activity-feed">${rows.slice(0,8).map(row=>`<p><strong>${escapeHtml(titleize(row.type))}</strong><span>${escapeHtml(row.summary||row.status||'Vastgelegde activiteit')} · ${escapeHtml(formatDate(row.at))}</span></p>`).join('')}</div>`:'<p class="unavailable">Nog geen activiteiten vastgelegd.</p>'}
  return '<p class="unavailable">Deze widget heeft nog geen beschikbare brondata.</p>';
}
function renderDashboard(){
  const grid=$('#widgetGrid');grid.classList.toggle('editing',state.editing);grid.innerHTML=(state.dashboard?.widgets||[]).map((widget,index)=>`<article class="widget ${widget.type==='KPI'?'':'chart'} ${gridClass(widget)}" draggable="${state.editing}" data-widget="${escapeHtml(widget.id)}"><div class="widget-tools"><button data-size="down" title="Kleiner">−</button><button data-size="up" title="Groter">+</button><button data-remove title="Verwijderen">×</button></div><h3>${escapeHtml(titleize(widget.metric||widget.type))}</h3>${widgetBody(widget)}<small class="unavailable">${escapeHtml(widget.type)} · positie ${index+1}</small></article>`).join('')||'<div class="empty">Dit dashboard heeft nog geen widgets. Kies + WIDGET.</div>';
  bindWidgetEditing();
}
function bindWidgetEditing(){
  $$('.widget').forEach(card=>{card.ondragstart=event=>{event.dataTransfer.setData('text/plain',card.dataset.widget)};card.ondragover=event=>event.preventDefault();card.ondrop=event=>{event.preventDefault();const from=event.dataTransfer.getData('text/plain'),to=card.dataset.widget;if(from===to)return;const widgets=state.dashboard.widgets,a=widgets.findIndex(item=>item.id===from),b=widgets.findIndex(item=>item.id===to);if(a<0||b<0)return;const [moved]=widgets.splice(a,1);widgets.splice(b,0,moved);packWidgets(widgets);renderDashboard()};card.onclick=event=>{const widget=state.dashboard.widgets.find(item=>item.id===card.dataset.widget);if(!widget)return;if(event.target.closest('[data-remove]')){state.dashboard.widgets=state.dashboard.widgets.filter(item=>item.id!==widget.id);packWidgets(state.dashboard.widgets);renderDashboard()}if(event.target.closest('[data-size="up"]')){widget.w=Math.min(12,(widget.w||4)+2);widget.h=Math.min(12,(widget.h||3)+1);packWidgets(state.dashboard.widgets);renderDashboard()}if(event.target.closest('[data-size="down"]')){widget.w=Math.max(2,(widget.w||4)-2);widget.h=Math.max(2,(widget.h||3)-1);packWidgets(state.dashboard.widgets);renderDashboard()}}});
}
async function saveDashboard(){const payload={...state.dashboard,name:state.dashboard.name||'Mijn CRM Dashboard',widgets:state.dashboard.widgets||[],filters:dashboardSettings(),share_mode:$('#dashboardShare').value,team_id:$('#dashboardShare').value==='TEAM'?$('#dashboardTeam').value.trim():undefined,is_default:true};if(payload.persisted===false||String(payload.id||'').startsWith('preset-'))delete payload.id;delete payload.persisted;const response=await api('/api/crm/dashboard',{method:payload.id?'PATCH':'POST',headers:{'idempotency-key':`dashboard-${crypto.randomUUID()}`,...(payload.revision?{'if-match':`"${payload.revision}"`}:{})},body:JSON.stringify(payload)});state.dashboard=response.dashboard;state.editing=false;syncDashboardControls();renderDashboard();await loadStatus();toast('Dashboardweergave opgeslagen')}

async function loadPipelines(){const response=await api('/api/crm/pipelines?limit=200&sort=updated_at&order=desc');state.pipelines=response.items||[];const select=$('#pipelineSelect');select.innerHTML=state.pipelines.map(row=>`<option value="${escapeHtml(row.id)}">${escapeHtml(row.name)}</option>`).join('');if(!state.pipelines.length){$('#pipelineBoard').innerHTML='<div class="empty">Nog geen pipeline geconfigureerd. Maak een pipeline of gebruik het bedrijfsprofiel.</div>';return}await loadPipelineBoard(select.value)}
async function loadPipelineBoard(id){if(!id)return;state.board=(await api(`/api/crm/pipelines/${encodeURIComponent(id)}/board`)).board;$('#pipelineBoard').innerHTML=state.board.stages.map(stage=>`<section class="stage" data-stage="${escapeHtml(stage.id)}"><div class="stage-head"><h3>${escapeHtml(stage.name)}</h3><span>${stage.deals.length} · ${escapeHtml(new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(stage.value||0))}</span></div><div class="stage-drop">${stage.deals.map(deal=>`<article class="deal-card" draggable="true" data-deal="${escapeHtml(deal.id)}" data-revision="${escapeHtml(deal.revision)}"><h4>${escapeHtml(deal.title)}</h4><div class="deal-meta"><span>${escapeHtml(deal.probability??0)}%</span><span>${escapeHtml(new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(deal.value||0))}</span></div></article>`).join('')}</div></section>`).join('')||'<div class="empty">Deze pipeline heeft nog geen fasen.</div>';bindPipelineDrag()}
function bindPipelineDrag(){$$('.deal-card').forEach(card=>card.ondragstart=event=>event.dataTransfer.setData('application/json',JSON.stringify({id:card.dataset.deal,revision:card.dataset.revision})));$$('.stage').forEach(stage=>{stage.ondragover=event=>{event.preventDefault();stage.classList.add('drag-over')};stage.ondragleave=()=>stage.classList.remove('drag-over');stage.ondrop=async event=>{event.preventDefault();stage.classList.remove('drag-over');try{const deal=JSON.parse(event.dataTransfer.getData('application/json'));await api(`/api/crm/deals/${encodeURIComponent(deal.id)}/stage`,{method:'PATCH',headers:{'if-match':`"${deal.revision}"`,'idempotency-key':`stage-${crypto.randomUUID()}`,'x-foundly-event-id':crypto.randomUUID()},body:JSON.stringify({stage_id:stage.dataset.stage})});await loadPipelineBoard(state.board.pipeline.id);toast('Deal verplaatst en geverifieerd')}catch(error){showError(error)}}})}
function openPipelineDialog(){const form=$('#pipelineForm');form.reset();form.elements.stages.value='Nieuw, Gekwalificeerd, Voorstel, Onderhandeling, Gewonnen, Verloren';$('#pipelineDialog').showModal();requestAnimationFrame(()=>form.elements.name.focus())}
async function createPipeline(event){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form).entries()),name=String(data.name||'').trim(),stageNames=String(data.stages||'').split(',').map(value=>value.trim()).filter(Boolean).slice(0,20);if(!name||!stageNames.length)return;const response=await api('/api/crm/pipelines',{method:'POST',headers:{'idempotency-key':`pipeline-${crypto.randomUUID()}`},body:JSON.stringify({name})}),pipeline=response.record;for(let index=0;index<stageNames.length;index++)await api('/api/crm/stages',{method:'POST',headers:{'idempotency-key':`pipeline-stage-${crypto.randomUUID()}`},body:JSON.stringify({name:stageNames[index],pipeline_id:pipeline.id,position:index+1,probability:Math.round(index/Math.max(1,stageNames.length-1)*100),status:/gewonnen/i.test(stageNames[index])?'WON':(/verloren/i.test(stageNames[index])?'LOST':'OPEN')})});$('#pipelineDialog').close();form.reset();await loadPipelines();$('#pipelineSelect').value=pipeline.id;await loadPipelineBoard(pipeline.id);toast('Pipeline en fasen aangemaakt')}

async function loadRecords(){const entity=$('#recordEntity').value||state.entity;state.entity=entity;const query=new URLSearchParams({limit:'100',sort:'updated_at',order:'desc'}),search=$('#recordSearch').value.trim();if(search)query.set('q',search);const response=await api(`/api/crm/${encodeURIComponent(entity)}?${query}`);state.records=response.items||[];const rows=$('#recordRows'),empty=$('#recordEmpty');rows.innerHTML=state.records.map(record=>`<tr><td><strong>${escapeHtml(record.name||record.title||record.number||record.type||record.channel||'Naamloos record')}</strong><br><small>${escapeHtml(record.email||record.phone||record.id)}</small></td><td>${escapeHtml(record.status||'—')}</td><td>${escapeHtml(record.owner_id||'—')}</td><td>${escapeHtml(formatDate(record.updated_at))}</td><td class="row-actions">${['contacts','leads','people'].includes(entity)?`<button data-360="${escapeHtml(record.id)}" class="ghost">360</button>`:''}<button data-edit="${escapeHtml(record.id)}" class="ghost">BEWERK</button><button data-archive="${escapeHtml(record.id)}" class="ghost danger">ARCHIVEER</button></td></tr>`).join('');empty.classList.toggle('hidden',state.records.length>0);empty.textContent=`Geen echte ${ENTITY_LABELS[entity]||entity} beschikbaar.`;$$('[data-360]').forEach(button=>button.onclick=()=>openCustomer(button.dataset['360']));$$('[data-edit]').forEach(button=>button.onclick=()=>openRecordDialog(state.records.find(record=>record.id===button.dataset.edit)));$$('[data-archive]').forEach(button=>button.onclick=()=>archiveRecord(button.dataset.archive).catch(showError))}
async function openCustomer(id){const data=(await api(`/api/crm/customers/${encodeURIComponent(id)}/360`)).customer,s=data.subject;$('#customer360').innerHTML=`<section><h3>Identiteit</h3><p><strong>${escapeHtml(s.name)}</strong><br>${escapeHtml(s.email||'')} ${escapeHtml(s.phone||'')}</p></section><section><h3>Lifecycle</h3><p>Status: ${escapeHtml(s.status||'—')} · Score: ${escapeHtml(s.score??'—')}</p></section><section><h3>Relaties</h3><p>${data.deals.length} deals · ${data.tasks.length} taken · ${data.appointments.length} afspraken · ${data.documents.length} documenten</p></section><section><h3>Tijdlijn</h3>${data.timeline.length?data.timeline.slice(0,30).map(row=>`<article><strong>${escapeHtml(titleize(row.timeline_type))}</strong> · ${escapeHtml(formatDate(row.occurred_at||row.scheduled_at||row.created_at))}<p>${escapeHtml(row.summary||row.title||row.content||row.status||'')}</p></article>`).join(''):'<p>Geen vastgelegde tijdlijnitems.</p>'}</section><section><h3>Wijzigingshistorie</h3>${data.history?.length?data.history.slice(0,20).map(row=>`<article><strong>${escapeHtml(row.action)}</strong> · ${escapeHtml(formatDate(row.created_at))}<p>${escapeHtml(titleize(row.entity))}</p></article>`).join(''):'<p>Geen toegankelijke wijzigingshistorie.</p>'}</section><section><h3>Toestemming</h3><p>${data.consents.length?data.consents.map(row=>`${escapeHtml(row.purpose)}: ${escapeHtml(row.status)}`).join('<br>'):'Geen toestemmingsrecord beschikbaar.'}</p></section>`;$('#customerDialog').showModal()}
function openRecordDialog(record=null){const form=$('#recordForm'),field=PRIMARY_FIELD[state.entity]||'name',input=form.elements.name;form.reset();input.dataset.field=field;$('#dialogTitle').textContent=`${record?'Bewerk':'Nieuw'} · ${ENTITY_LABELS[state.entity]||titleize(state.entity)}`;input.placeholder=field==='title'?'Titel':titleize(field);form.elements.id.value=record?.id||'';form.elements.revision.value=record?.revision||'';if(record){input.value=record[field]||record.name||'';for(const name of ['status','email','phone','value','probability','owner_id','team_id','source_id','channel','direction','note'])if(form.elements[name])form.elements[name].value=record[name]??'';if(record.next_action_at)form.elements.next_action_at.value=new Date(record.next_action_at).toISOString().slice(0,16)}$('#recordDialog').showModal()}
async function saveRecord(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries()),id=data.id,revision=data.revision,primary=data.name,field=$('#recordForm [name="name"]').dataset.field||'name';delete data.id;delete data.revision;delete data.name;data[field]=primary;for(const key of Object.keys(data))if(data[key]==='')delete data[key];for(const key of ['value','probability'])if(data[key]!==undefined)data[key]=Number(data[key]);if(data.next_action_at)data.next_action_at=new Date(data.next_action_at).toISOString();await api(`/api/crm/${encodeURIComponent(state.entity)}${id?`/${encodeURIComponent(id)}`:''}`,{method:id?'PATCH':'POST',headers:{'idempotency-key':`record-${crypto.randomUUID()}`,...(revision?{'if-match':`"${revision}"`}:{})},body:JSON.stringify(data)});$('#recordDialog').close();await Promise.all([loadRecords(),loadStatus()]);toast(`CRM-record ${id?'bijgewerkt':'opgeslagen'}`)}
async function archiveRecord(id){const record=state.records.find(item=>item.id===id);if(!record||!confirm(`Archiveer ${record.name||record.title||record.number||'dit record'}?`))return;await api(`/api/crm/${encodeURIComponent(state.entity)}/${encodeURIComponent(id)}`,{method:'DELETE',headers:{'idempotency-key':`archive-${crypto.randomUUID()}`,'if-match':`"${record.revision}"`}});await Promise.all([loadRecords(),loadStatus()]);toast('CRM-record gearchiveerd')}
async function loadAutomations(){const response=await api('/api/crm/automations?limit=100&sort=updated_at&order=desc'),rows=response.items||[];$('#automationList').innerHTML=rows.length?rows.map(row=>`<article><h3>${escapeHtml(row.name)}</h3><p>${escapeHtml(row.trigger?.type||row.trigger)} → ${escapeHtml((row.actions||[]).map(action=>action.type).join(', '))} · ${row.enabled===false?'UIT':'ACTIEF'}</p></article>`).join(''):'<div class="empty">Nog geen automationdefinities.</div>'}
async function saveAutomation(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());await api('/api/crm/automations',{method:'POST',headers:{'idempotency-key':`automation-${crypto.randomUUID()}`},body:JSON.stringify({name:data.name,enabled:true,trigger:{type:data.trigger},actions:[{type:data.action,title:`${data.name} · opvolging`}]})});event.currentTarget.reset();await loadAutomations();toast('Automation veilig opgeslagen')}
async function provision(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());const result=await api('/api/crm/provision',{method:'POST',headers:{'idempotency-key':`provision-${crypto.randomUUID()}`},body:JSON.stringify(data)});toast(`${result.profile.business_name}: configuratie ingericht, zonder demodata`);await loadStatus()}

function runUiCommands(commands=[]){for(const command of commands){if(command.type==='OPEN_ENGINE'&&['analysis','finance'].includes(command.target)){location.href=`/${command.target}`;return}if(command.type==='OPEN_ENGINE'&&command.target==='crm')setView('dashboard');if(command.type==='FOCUS_NODE'&&command.target==='crm')setView('dashboard');if(command.type==='SHOW_TASK')setView('records','tasks')}}
async function runZero(event){event.preventDefault();const input=$('#zeroInput'),message=input.value.trim();if(!message)return;$('#zeroOutput').textContent='ZERO analyseert de CRM-context…';input.value='';try{const result=await api('/api/zero/turn',{method:'POST',body:JSON.stringify({message,conversation_id:sessionStorage.foundlyCrmConversation||(sessionStorage.foundlyCrmConversation=crypto.randomUUID()),turn_id:crypto.randomUUID(),client_context:{surface:'crm',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}})});$('#zeroOutput').textContent=result.display_text||result.answer;runUiCommands(result.ui_commands);if(result.modules?.includes('crm'))await Promise.allSettled([loadStatus(),loadDashboard()])}catch(error){$('#zeroOutput').textContent=error.message;showError(error)}}
function filterCommandPalette(){const query=$('#commandSearch').value.trim().toLocaleLowerCase('nl-NL');$$('#commandList button').forEach(button=>button.hidden=Boolean(query&&!button.textContent.toLocaleLowerCase('nl-NL').includes(query)))}
function openCommandPalette(){const dialog=$('#commandDialog');if(!dialog.open)dialog.showModal();$('#commandSearch').value='';filterCommandPalette();requestAnimationFrame(()=>$('#commandSearch').focus())}
function closeCommandPalette(){const dialog=$('#commandDialog');if(dialog.open)dialog.close()}

function bind(){
  $$('#crmNav button').forEach(button=>button.onclick=()=>setView(button.dataset.view,button.dataset.entity,button.dataset.section));$('#recordEntity').onchange=()=>{state.entity=$('#recordEntity').value;$('#viewTitle').textContent=ENTITY_LABELS[state.entity]||titleize(state.entity);loadRecords().catch(showError)};$('#recordSearch').oninput=()=>{clearTimeout(bind.searchTimer);bind.searchTimer=setTimeout(()=>loadRecords().catch(showError),220)};$('#refreshRecords').onclick=()=>loadRecords().catch(showError);$('#createRecord').onclick=()=>openRecordDialog();$('#newRecord').onclick=()=>{const active=$('.view.active')?.id;if(active==='view-pipeline')openPipelineDialog();else{if(active!=='view-records')setView('records','leads');openRecordDialog()}};$('#recordForm').onsubmit=event=>saveRecord(event).catch(showError);
  $('#refreshDashboard').onclick=()=>refreshDashboardData().catch(showError);$('#dashboardPreset').onchange=()=>loadDashboard({forcePreset:true}).catch(showError);for(const node of [$('#dateFrom'),$('#dateTo'),$('#comparePeriod'),$('#dashboardStatusFilter'),$('#dashboardOwnerFilter'),$('#dashboardSourceFilter')])node.onchange=()=>refreshDashboardData().catch(showError);$('#dashboardShare').onchange=()=>$('#dashboardTeamWrap').classList.toggle('hidden',$('#dashboardShare').value!=='TEAM');$('#editDashboard').onclick=()=>{state.editing=!state.editing;renderDashboard()};$('#saveDashboard').onclick=()=>saveDashboard().catch(showError);$('#addWidget').onclick=()=>$('#widgetDialog').showModal();$('#widgetForm').onsubmit=event=>{event.preventDefault();const input=Object.fromEntries(new FormData(event.currentTarget).entries());state.dashboard.widgets.push({id:`widget-${crypto.randomUUID()}`,type:input.type,metric:input.metric,x:0,y:0,w:input.type==='KPI'?4:8,h:input.type==='KPI'?2:4,filters:{}});packWidgets(state.dashboard.widgets);state.editing=true;$('#widgetDialog').close();event.currentTarget.reset();renderDashboard()};
  $('#pipelineSelect').onchange=()=>loadPipelineBoard($('#pipelineSelect').value).catch(showError);$('#refreshPipeline').onclick=()=>loadPipelines().catch(showError);$('#createPipeline').onclick=openPipelineDialog;$('#pipelineForm').onsubmit=event=>createPipeline(event).catch(showError);$('#automationForm').onsubmit=event=>saveAutomation(event).catch(showError);$('#provisionForm').onsubmit=event=>provision(event).catch(showError);$('#zeroForm').onsubmit=runZero;$('#commandButton').onclick=openCommandPalette;$('#commandSearch').oninput=filterCommandPalette;$$('#commandList [data-command-view]').forEach(button=>button.onclick=()=>{closeCommandPalette();setView(button.dataset.commandView,button.dataset.commandEntity)});$('#commandList [data-command-zero]').onclick=()=>{closeCommandPalette();$('#zeroInput').focus()};document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();openCommandPalette()}if(event.key==='/'&&!/input|textarea|select/i.test(document.activeElement?.tagName)){event.preventDefault();$('#zeroInput').focus()}});
}

async function init(){const today=new Date(),from=new Date(today);from.setDate(from.getDate()-29);$('#dateFrom').value=localDate(from);$('#dateTo').value=localDate(today);bind();try{await Promise.all([loadStatus(),loadSchema(),loadDashboard()]);$('#dashboardFreshness').textContent=`Laatst gecontroleerd ${new Intl.DateTimeFormat('nl-NL',{timeStyle:'medium'}).format(new Date())} · alleen vastgelegde CRM-data`;setInterval(pollLiveStatus,5000)}catch(error){showError(error);$('#crmConnection').textContent='NIET BESCHIKBAAR'}}
init();
