'use strict';
const crypto=require('node:crypto'),hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const OPERATIONS=Object.freeze(Object.fromEntries(['SCENARIO','PREVIEW_CLOSE','CLOSE'].map(operation=>[operation,{tool:'finance_'+operation.toLowerCase(),mode:operation==='CLOSE'?'write':'read',permission:operation==='CLOSE'?'write':'read',capabilities:operation==='SCENARIO'?['finance:reports']:['finance:ledger','finance:invoices','finance:payments']}])));
function tools(){return Object.entries(OPERATIONS).map(([operation,op])=>({tool_id:op.tool,name:'Finance '+operation,engine:'finance',description:'Expliciete actuele kasplanning of interne periodecontrole via native Finance-beleid.',parameter_schema:{type:'object',properties:{operation:{type:'string',enum:[operation]},input:{type:'object'}},required:['operation','input'],additionalProperties:false},required_permissions:['finance:read',...(operation==='CLOSE'?['finance:close']:[])],mode:op.mode,risk_level:operation==='CLOSE'?'HIGH_RISK':'READ_ONLY',provider:'foundly_finance',timeout_ms:3000,retry:{max_attempts:1},confirmation:operation==='CLOSE'?'explicit_native_policy':'never',handler:'finance_native',verification:'current_native_sources_and_receipts',audit:'source_free_reference'}));}
function execute(finance,resolver,ctx,actor,action,meta){
 const fail=(code,message,statusCode=422)=>{throw Object.assign(Error(message),{code,statusCode});},op=action&&Object.hasOwn(OPERATIONS,action.operation)&&OPERATIONS[action.operation];
 if(!op||Object.keys(action).some(k=>!['operation','input'].includes(k))||!action.input||typeof action.input!=='object'||Array.isArray(action.input)||JSON.stringify(action).length>128000)fail('finance_zero_invalid','Kies een expliciete Finance-actie');
 resolver.assertTool(ctx,actor,op.tool);const request_hash=hash({message:meta.message,action});if(meta.prior&&(meta.prior.request_hash!==request_hash||meta.prior.operation!==action.operation))fail('finance_zero_turn_conflict','Deze turn hoort bij andere Finance-invoer',409);
 let data;
 if(action.operation==='SCENARIO')data=finance.forecastScenario(ctx,actor,action.input);
 else {const {period_id,...input}=action.input;if(typeof period_id!=='string'||!/^[-A-Za-z0-9_.:]{1,200}$/.test(period_id))fail('finance_zero_period_invalid','Kies expliciet een periode');if(action.operation==='PREVIEW_CLOSE'){if(Object.keys(input).length)fail('finance_zero_invalid','Gebruik alleen de gekozen periode');data=finance.previewPeriodClose(ctx,actor,period_id);}else data=finance.closePeriod(ctx,actor,period_id,input.reason,input);}
 return {ok:true,status:'completed',modules:['finance'],answer:action.operation==='CLOSE'?'De interne periodeafsluiting is geverifieerd.':'De actuele Finance-bron is berekend. Financiële acties vereisen een afzonderlijke bevestiging.',finance_data:data,finance_action_reference:{operation:action.operation,tool_id:op.tool,request_hash},actions:[],syncs:[],web:{used:false,sources:[],error:null},voice_mode:'ANALYSIS',plan:{goal:'Gekozen Finance-actie',steps:['current_native_authority','current_native_source'],tools:[op.tool]},verification:{native_policy:true,financial_posting_performed:false,provider_acceptance:'UNVERIFIED',source_result_retained:false},ui_commands:[]};
}
function retain(result){const {finance_data,...safe}=result,answer='Finance-actie verwerkt. Vraag de actuele bron opnieuw op.';return {...safe,answer,display_text:answer,spoken_text:answer,verification:{native_policy:true,current_source_recalculation_required:true,source_result_retained:false,financial_posting_performed:false}};}
module.exports={OPERATIONS,tools,execute,retain};
