'use strict';
const crypto=require('node:crypto'),hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const invoiceOperations=Object.fromEntries(Object.entries(require('./finance-invoice-actions').CONTRACTS).flatMap(([command,spec])=>['PREVIEW','EXECUTE','RECOVER'].map(phase=>[command+'_'+phase,{tool:'finance_'+command.toLowerCase()+'_'+phase.toLowerCase(),mode:phase==='PREVIEW'?'read':'write',permission:phase==='PREVIEW'?'read':'write',capabilities:spec.capabilities,core_permission:phase==='PREVIEW'?'finance:read':spec.permission,...(spec.commerce?{capability_operations:Object.fromEntries(spec.capabilities.map(cap=>[cap,spec.capability_modes?.[cap]||(phase==='PREVIEW'?'read':'write')]))}:{}),command,phase}])));
const OPERATIONS=Object.freeze({...Object.fromEntries(['SCENARIO','PREVIEW_CLOSE','CLOSE'].map(operation=>[operation,{tool:'finance_'+operation.toLowerCase(),mode:operation==='CLOSE'?'write':'read',permission:operation==='CLOSE'?'write':'read',capabilities:operation==='SCENARIO'?['finance:reports']:['finance:ledger','finance:invoices','finance:payments']}])),...invoiceOperations});
function tools(){return Object.entries(OPERATIONS).map(([operation,op])=>({tool_id:op.tool,name:'Finance '+operation,engine:'finance',description:op.command?(op.command==='CREDIT_NOTE_CREATE'?'Maak een volledige creditnota op basis van de gekozen geboekte verkoopfactuur. PREVIEW vereist invoice_id, invoice_number, invoice_date, supply_date en due_date. Dit creëert alleen een concept; boeken, verrekenen en terugbetalen zijn afzonderlijke handelingen. EXECUTE en RECOVER gebruiken de exacte input, request_id, expected_source_hash, confirm:true en reason.':op.command==='COMMERCE_INVOICE_CREATE'?'Factureer een native Sales-order voor de gekozen CRM-klant. PREVIEW gebruikt order_id, contact_id, legal_entity_id, invoice_number en expliciete invoice_date, supply_date, due_date. EXECUTE en RECOVER gebruiken de exacte input, request_id, expected_source_hash, confirm:true en reason. Bedragen en klantgegevens komen uit de actuele native bronnen.':'Bereid de gekozen factuur- of interne betalingsactie voor; voer uitsluitend de exact bevestigde bronhash en aanvraag-ID uit of herstel die aanvraag. Een interne betalingsboeking voert geen bankoverschrijving uit.'):'Expliciete actuele kasplanning of interne periodecontrole via native Finance-beleid.',parameter_schema:{type:'object',properties:{operation:{type:'string',enum:[operation]},input:{type:'object'}},required:['operation','input'],additionalProperties:false},required_permissions:[...new Set(['finance:read',...(op.core_permission?[op.core_permission]:operation==='CLOSE'?['finance:close']:[])])],mode:op.mode,risk_level:op.mode==='write'?'HIGH_RISK':'READ_ONLY',provider:'foundly_finance',timeout_ms:3000,retry:{max_attempts:1},confirmation:op.mode==='write'?'explicit_native_policy':'never',handler:'finance_native',verification:'current_native_sources_and_receipts',audit:'source_free_reference'}));}
function execute(finance,resolver,ctx,actor,action,meta){
 const fail=(code,message,statusCode=422)=>{throw Object.assign(Error(message),{code,statusCode});},op=action&&Object.hasOwn(OPERATIONS,action.operation)&&OPERATIONS[action.operation];
 if(!op||Object.keys(action).some(k=>!['operation','input'].includes(k))||!action.input||typeof action.input!=='object'||Array.isArray(action.input)||JSON.stringify(action).length>128000)fail('finance_zero_invalid','Kies een expliciete Finance-actie');
 resolver.assertTool(ctx,actor,op.tool);const request_hash=hash({message:meta.message,action});if(meta.prior&&(meta.prior.request_hash!==request_hash||meta.prior.operation!==action.operation))fail('finance_zero_turn_conflict','Deze turn hoort bij andere Finance-invoer',409);
 let data;
 if(op.command){
   const payload=op.phase==='PREVIEW'?{operation:op.command,input:action.input}:{...action.input,operation:op.command};
   if(op.phase!=='PREVIEW'&&Object.hasOwn(action.input,'operation'))fail('finance_zero_invalid','Kies één expliciete financiële actie');
   data=finance[op.phase==='PREVIEW'?'previewInvoiceAction':op.phase==='EXECUTE'?'executeInvoiceAction':'recoverInvoiceAction'](ctx,actor,payload);
   const performed=op.phase==='EXECUTE'&&data.state==='COMMITTED'&&!data.deduplicated;
   const answer=op.phase==='PREVIEW'?(data.ready?'De actuele financiële voorbereiding is beschikbaar. Bevestig de getoonde invoer afzonderlijk.':'De financiële voorbereiding bevat blokkades; controleer de actuele bron.'):data.state==='NOT_APPLIED'?'De aanvraag is definitief afgesloten zonder uitvoering.':'De bevestigde financiële registratie en de huidige factuur zijn afzonderlijk gecontroleerd. Er is geen externe bankbetaling uitgevoerd.';
   return {ok:true,status:'completed',modules:['finance'],answer,finance_data:data,finance_action_reference:{operation:action.operation,tool_id:op.tool,request_hash},actions:op.phase==='EXECUTE'&&data.state==='COMMITTED'?[{type:op.command,tool_id:op.tool,status:data.deduplicated?'ORIGINAL_RESULT_VERIFIED':'RECORDED',deduplicated:data.deduplicated,performed_now:performed,external_payment_performed:false}]:[],syncs:[],web:{used:false,sources:[],error:null},voice_mode:performed?'SUCCESS':'ANALYSIS',plan:{goal:'Gekozen financiële registratie',steps:['current_native_authority','source_bound_confirmation','durable_native_receipt'],tools:[op.tool]},verification:{native_policy:true,financial_posting_performed:performed&&data.financial_posting_performed,original_financial_posting_performed:data.financial_posting_performed||false,external_payment_performed:false,bank_settlement_verified:false,source_result_retained:false},ui_commands:[]};
 }
 if(action.operation==='SCENARIO')data=finance.forecastScenario(ctx,actor,action.input);
 else {const {period_id,...input}=action.input;if(typeof period_id!=='string'||!/^[-A-Za-z0-9_.:]{1,200}$/.test(period_id))fail('finance_zero_period_invalid','Kies expliciet een periode');if(action.operation==='PREVIEW_CLOSE'){if(Object.keys(input).length)fail('finance_zero_invalid','Gebruik alleen de gekozen periode');data=finance.previewPeriodClose(ctx,actor,period_id);}else data=finance.closePeriod(ctx,actor,period_id,input.reason,input);}
 return {ok:true,status:'completed',modules:['finance'],answer:action.operation==='CLOSE'?'De interne periodeafsluiting is geverifieerd.':'De actuele Finance-bron is berekend. Financiële acties vereisen een afzonderlijke bevestiging.',finance_data:data,finance_action_reference:{operation:action.operation,tool_id:op.tool,request_hash},actions:[],syncs:[],web:{used:false,sources:[],error:null},voice_mode:'ANALYSIS',plan:{goal:'Gekozen Finance-actie',steps:['current_native_authority','current_native_source'],tools:[op.tool]},verification:{native_policy:true,financial_posting_performed:false,provider_acceptance:'UNVERIFIED',source_result_retained:false},ui_commands:[]};
}
function retain(result){const {finance_data,...safe}=result,answer='Finance-actie verwerkt. Vraag de actuele bron opnieuw op.';return {...safe,answer,display_text:answer,spoken_text:answer,actions:[],verification:{native_policy:true,current_source_recalculation_required:true,source_result_retained:false,financial_posting_performed:false}};}
module.exports={OPERATIONS,tools,execute,retain};
