(function(root,factory){'use strict';const value=factory(typeof module==='object'&&module.exports?require('./foundly-static-copy'):root.FoundlyStaticCopy||{});if(typeof module==='object'&&module.exports)module.exports=value;else root.FoundlyLocales=value;})(typeof globalThis!=='undefined'?globalThis:this,function(staticRows){
  'use strict';
  const locales=Object.freeze(['nl-NL','en-GB','de-DE','fr-FR','es-ES','da-DK','nb-NO','sv-SE']);
  const names=Object.freeze(['Nederlands','English (UK)','Deutsch','Français','Español','Dansk','Norsk bokmål','Svenska']);
  // Explicit catalog entries only. Business records and provider text are never
  // translated by DOM inspection or substituted by a language fallback.
  const rows={
    'common.language':['Interfacetaal','Interface language','Sprache der Oberfläche','Langue de l’interface','Idioma de la interfaz','Grænsefladesprog','Grensesnittspråk','Gränssnittsspråk'],
    'common.close':['Sluiten','Close','Schließen','Fermer','Cerrar','Luk','Lukk','Stäng'],
    'common.save':['Opslaan','Save','Speichern','Enregistrer','Guardar','Gem','Lagre','Spara'],
    'common.cancel':['Annuleren','Cancel','Abbrechen','Annuler','Cancelar','Annuller','Avbryt','Avbryt'],
    'common.loading':['Laden…','Loading…','Wird geladen…','Chargement…','Cargando…','Indlæser…','Laster…','Läser in…'],
    'common.wait':['Even geduld…','Please wait…','Bitte warten…','Veuillez patienter…','Espera un momento…','Vent venligst…','Vennligst vent…','Vänta…'],
    'common.unknown':['Onbekend','Unknown','Unbekannt','Inconnu','Desconocido','Ukendt','Ukjent','Okänt'],
    'common.no_data':['Geen data','No data','Keine Daten','Aucune donnée','Sin datos','Ingen data','Ingen data','Inga data'],
    'common.request_failed':['De aanvraag kon niet worden voltooid. Probeer het opnieuw.','The request could not be completed. Please try again.','Die Anfrage konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.','La demande n’a pas pu aboutir. Veuillez réessayer.','No se ha podido completar la solicitud. Inténtalo de nuevo.','Anmodningen kunne ikke gennemføres. Prøv igen.','Forespørselen kunne ikke fullføres. Prøv igjen.','Begäran kunde inte slutföras. Försök igen.'],
    'common.required':['Vul dit veld in.','Complete this field.','Bitte füllen Sie dieses Feld aus.','Veuillez renseigner ce champ.','Completa este campo.','Udfyld dette felt.','Fyll ut dette feltet.','Fyll i det här fältet.'],
    'common.access_denied':['Je hebt geen toegang tot dit onderdeel.','You do not have access to this area.','Sie haben keinen Zugriff auf diesen Bereich.','Vous n’avez pas accès à cette section.','No tienes acceso a esta sección.','Du har ikke adgang til dette område.','Du har ikke tilgang til dette området.','Du har inte åtkomst till det här området.'],
    'common.rate_limited':['Te veel verzoeken. Probeer het later opnieuw.','Too many requests. Please try again later.','Zu viele Anfragen. Bitte versuchen Sie es später erneut.','Trop de demandes. Veuillez réessayer plus tard.','Demasiadas solicitudes. Inténtalo más tarde.','For mange anmodninger. Prøv igen senere.','For mange forespørsler. Prøv igjen senere.','För många förfrågningar. Försök igen senare.'],
    'common.offline':['Geen verbinding. Controleer je netwerk en probeer het opnieuw.','No connection. Check your network and try again.','Keine Verbindung. Prüfen Sie Ihr Netzwerk und versuchen Sie es erneut.','Aucune connexion. Vérifiez votre réseau et réessayez.','Sin conexión. Comprueba la red e inténtalo de nuevo.','Ingen forbindelse. Kontrollér dit netværk, og prøv igen.','Ingen tilkobling. Kontroller nettverket og prøv igjen.','Ingen anslutning. Kontrollera nätverket och försök igen.'],
    'identity.sign_in':['Aanmelden','Sign in','Anmelden','Se connecter','Iniciar sesión','Log ind','Logg inn','Logga in'],
    'identity.title':['Aanmelden · Foundly OS','Sign in · Foundly OS','Anmelden · Foundly OS','Connexion · Foundly OS','Inicio de sesión · Foundly OS','Log ind · Foundly OS','Logg inn · Foundly OS','Logga in · Foundly OS'],
    'identity.description':['Gebruik je persoonlijke Foundly-account.','Use your personal Foundly account.','Verwenden Sie Ihr persönliches Foundly-Konto.','Utilisez votre compte Foundly personnel.','Usa tu cuenta personal de Foundly.','Brug din personlige Foundly-konto.','Bruk din personlige Foundly-konto.','Använd ditt personliga Foundly-konto.'],
    'identity.username':['Gebruikersnaam','Username','Benutzername','Nom d’utilisateur','Nombre de usuario','Brugernavn','Brukernavn','Användarnamn'],
    'identity.password':['Wachtwoord','Password','Passwort','Mot de passe','Contraseña','Adgangskode','Passord','Lösenord'],
    'identity.help':['Nog geen account? Vraag je bevoegde Foundly-beheerder om een uitnodiging.','Need an account? Ask your authorised Foundly administrator for an invitation.','Sie benötigen ein Konto? Bitten Sie Ihren zuständigen Foundly-Administrator um eine Einladung.','Besoin d’un compte ? Demandez une invitation à votre administrateur Foundly habilité.','¿Necesitas una cuenta? Pide una invitación al administrador autorizado de Foundly.','Mangler du en konto? Bed din autoriserede Foundly-administrator om en invitation.','Trenger du en konto? Be din autoriserte Foundly-administrator om en invitasjon.','Behöver du ett konto? Be din behöriga Foundly-administratör om en inbjudan.'],
    'identity.admin':['Beheerderstoegang','Administrator access','Administratorzugang','Accès administrateur','Acceso de administrador','Administratoradgang','Administratortilgang','Administratörsåtkomst'],
    'identity.activate_title':['Persoonlijk account activeren','Activate your personal account','Persönliches Konto aktivieren','Activer votre compte personnel','Activar tu cuenta personal','Aktivér din personlige konto','Aktiver din personlige konto','Aktivera ditt personliga konto'],
    'identity.activate':['Account activeren','Activate account','Konto aktivieren','Activer le compte','Activar cuenta','Aktivér konto','Aktiver konto','Aktivera konto'],
    'identity.invitation_help':['Kies een eigen wachtwoord van 15–128 tekens. De uitnodiging kan één keer worden gebruikt.','Choose your own password of 15–128 characters. The invitation can only be used once.','Wählen Sie ein eigenes Passwort mit 15–128 Zeichen. Die Einladung kann nur einmal verwendet werden.','Choisissez un mot de passe personnel de 15 à 128 caractères. L’invitation est à usage unique.','Elige una contraseña de entre 15 y 128 caracteres. La invitación solo se puede usar una vez.','Vælg din egen adgangskode på 15–128 tegn. Invitationen kan kun bruges én gang.','Velg ditt eget passord på 15–128 tegn. Invitasjonen kan bare brukes én gang.','Välj ett eget lösenord med 15–128 tecken. Inbjudan kan bara användas en gång.'],
    'identity.credentials_invalid':['Ongeldige aanmeldgegevens.','Invalid sign-in details.','Ungültige Anmeldedaten.','Identifiants de connexion incorrects.','Datos de inicio de sesión incorrectos.','Ugyldige loginoplysninger.','Ugyldig påloggingsinformasjon.','Ogiltiga inloggningsuppgifter.'],
    'identity.invitation_invalid':['Deze uitnodiging is ongeldig of verlopen. Vraag een nieuwe uitnodiging aan.','This invitation is invalid or has expired. Request a new invitation.','Diese Einladung ist ungültig oder abgelaufen. Fordern Sie eine neue Einladung an.','Cette invitation est invalide ou a expiré. Demandez-en une nouvelle.','Esta invitación no es válida o ha caducado. Solicita una nueva.','Denne invitation er ugyldig eller udløbet. Bed om en ny invitation.','Denne invitasjonen er ugyldig eller utløpt. Be om en ny invitasjon.','Den här inbjudan är ogiltig eller har gått ut. Be om en ny inbjudan.'],
    'identity.password_invalid':['Kies een wachtwoord van 15–128 tekens.','Choose a password of 15–128 characters.','Wählen Sie ein Passwort mit 15–128 Zeichen.','Choisissez un mot de passe de 15 à 128 caractères.','Elige una contraseña de entre 15 y 128 caracteres.','Vælg en adgangskode på 15–128 tegn.','Velg et passord på 15–128 tegn.','Välj ett lösenord med 15–128 tecken.'],
    'identity.auth_required':['Meld je aan om verder te gaan.','Sign in to continue.','Melden Sie sich an, um fortzufahren.','Connectez-vous pour continuer.','Inicia sesión para continuar.','Log ind for at fortsætte.','Logg inn for å fortsette.','Logga in för att fortsätta.'],
    'nav.open':['Open globale Foundly-navigatie','Open Foundly navigation','Foundly-Navigation öffnen','Ouvrir la navigation Foundly','Abrir la navegación de Foundly','Åbn Foundly-navigation','Åpne Foundly-navigasjon','Öppna Foundly-navigering'],
    'nav.heading':['GLOBALE NAVIGATIE','GLOBAL NAVIGATION','GLOBALE NAVIGATION','NAVIGATION GLOBALE','NAVEGACIÓN GLOBAL','GLOBAL NAVIGATION','GLOBAL NAVIGASJON','GLOBAL NAVIGERING'],
    'nav.workspaces':['Foundly-werkruimten','Foundly workspaces','Foundly-Arbeitsbereiche','Espaces de travail Foundly','Espacios de trabajo de Foundly','Foundly-arbejdsområder','Foundly-arbeidsområder','Foundly-arbetsytor'],
    'nav.search':['Zoek werkruimte','Search workspaces','Arbeitsbereiche suchen','Rechercher un espace de travail','Buscar espacios de trabajo','Søg i arbejdsområder','Søk i arbeidsområder','Sök arbetsytor'],
    'nav.search_hint':['CRM, Financiën, Koppelingen…','CRM, Finance, Connectors…','CRM, Finanzen, Anbindungen…','CRM, Finances, Connecteurs…','CRM, Finanzas, Conectores…','CRM, Økonomi, Integrationer…','CRM, Økonomi, Integrasjoner…','CRM, Ekonomi, Integrationer…'],
    'nav.empty':['Geen toegankelijke werkruimte gevonden.','No accessible workspace found.','Kein zugänglicher Arbeitsbereich gefunden.','Aucun espace de travail accessible trouvé.','No se ha encontrado ningún espacio de trabajo accesible.','Ingen tilgængelige arbejdsområder fundet.','Fant ingen tilgjengelige arbeidsområder.','Ingen tillgänglig arbetsyta hittades.'],
    'nav.unavailable':['Navigatie kon niet worden geladen.','Navigation could not be loaded.','Die Navigation konnte nicht geladen werden.','La navigation n’a pas pu être chargée.','No se ha podido cargar la navegación.','Navigationen kunne ikke indlæses.','Navigasjonen kunne ikke lastes.','Navigeringen kunde inte läsas in.'],
    'module.core':['Commandocentrum','Command centre','Kommandozentrale','Centre de commande','Centro de control','Kommandocentral','Kommandosentral','Kommandocentral'],
    'module.crm':['CRM','CRM','CRM','CRM','CRM','CRM','CRM','CRM'],
    'module.sales':['Verkoop','Sales','Vertrieb','Ventes','Ventas','Salg','Salg','Försäljning'],
    'module.procurement':['Inkoop','Procurement','Einkauf','Achats','Compras','Indkøb','Innkjøp','Inköp'],
    'module.analysis':['Analyse','Analysis','Analyse','Analyse','Análisis','Analyse','Analyse','Analys'],
    'module.finance':['Financiën','Finance','Finanzen','Finances','Finanzas','Økonomi','Økonomi','Ekonomi'],
    'module.calendar':['Agenda','Calendar','Kalender','Calendrier','Calendario','Kalender','Kalender','Kalender'],
    'module.communication':['Communicatie','Communication','Kommunikation','Communication','Comunicación','Kommunikation','Kommunikasjon','Kommunikation'],
    'module.marketing':['Marketing','Marketing','Marketing','Marketing','Marketing','Marketing','Markedsføring','Marknadsföring'],
    'module.automation':['Automatisering','Automation','Automatisierung','Automatisation','Automatización','Automatisering','Automatisering','Automatisering'],
    'module.data':['Gegevens','Data','Daten','Données','Datos','Data','Data','Data'],
    'module.knowledge':['Kennis','Knowledge','Wissen','Connaissances','Conocimiento','Viden','Kunnskap','Kunskap'],
    'module.learning':['Leren','Learning','Lernen','Apprentissage','Aprendizaje','Læring','Læring','Lärande'],
    'module.connectors':['Koppelingen','Connectors','Anbindungen','Connecteurs','Conectores','Integrationer','Integrasjoner','Integrationer'],
    'module.settings':['Instellingen','Settings','Einstellungen','Paramètres','Configuración','Indstillinger','Innstillinger','Inställningar'],
    'module.automotive':['Automotive','Automotive','Automobilhandel','Automobile','Automoción','Bilhandel','Bilhandel','Bilhandel'],
    'nav.eyebrow.business':['FOUNDLY BEDRIJFSVOERING','FOUNDLY BUSINESS OPERATIONS','FOUNDLY GESCHÄFTSBETRIEB','OPÉRATIONS MÉTIER FOUNDLY','OPERACIONES EMPRESARIALES FOUNDLY','FOUNDLY VIRKSOMHEDSDRIFT','FOUNDLY VIRKSOMHETSDRIFT','FOUNDLY AFFÄRSVERKSAMHET'],
    'nav.eyebrow.home':['FOUNDLY CORE','FOUNDLY CORE','FOUNDLY CORE','FOUNDLY CORE','FOUNDLY CORE','FOUNDLY CORE','FOUNDLY CORE','FOUNDLY CORE'],
    'nav.eyebrow.automotive':['AUTOMOTIVE FUNCTIEPAKKET','AUTOMOTIVE CAPABILITY PACK','AUTOMOBIL-FUNKTIONSPAKET','PACK DE FONCTIONNALITÉS AUTOMOBILE','PAQUETE DE FUNCIONES DE AUTOMOCIÓN','FUNKTIONSPAKKE TIL BILHANDEL','FUNKSJONSPAKKE FOR BILHANDEL','FUNKTIONSPAKET FÖR BILHANDEL'],
    'nav.eyebrow.crm':['KLANTINZICHT','CUSTOMER INTELLIGENCE','KUNDENANALYSE','CONNAISSANCE CLIENT','INTELIGENCIA DE CLIENTES','KUNDEINDSIGT','KUNDEINNSIKT','KUNDINSIKT'],
    'nav.eyebrow.analysis':['BEDRIJFSINZICHT UIT CANONIEKE DATA','CANONICAL BUSINESS INTELLIGENCE','GESCHÄFTSANALYSE AUS KANONISCHEN DATEN','ANALYSE MÉTIER DES DONNÉES CANONIQUES','ANÁLISIS EMPRESARIAL DE DATOS CANÓNICOS','FORRETNINGSINDSIGT FRA KANONISKE DATA','FORRETNINGSINNSIKT FRA KANONISKE DATA','AFFÄRSINSIKT FRÅN KANONISKA DATA'],
    'nav.eyebrow.finance':['GEBOEKTE ONWIJZIGBARE JOURNAALPOSTEN','POSTED IMMUTABLE JOURNALS','GEBUCHTE UNVERÄNDERLICHE JOURNALPOSTEN','ÉCRITURES COMPTABILISÉES IMMUABLES','ASIENTOS CONTABILIZADOS INMUTABLES','BOGFØRTE UFORANDERLIGE POSTER','BOKFØRTE UFORANDERLIGE POSTER','BOKFÖRDA OFÖRÄNDERLIGA POSTER'],
    'nav.eyebrow.data':['CANONIEKE GEGEVENSLAAG','CANONICAL DATA FABRIC','KANONISCHE DATENEBENE','COUCHE DE DONNÉES CANONIQUES','CAPA DE DATOS CANÓNICOS','KANONISK DATALAG','KANONISK DATALAG','KANONISKT DATALAGER'],
    'nav.eyebrow.knowledge':['BEWIJSNETWERK','EVIDENCE GRAPH','NACHWEISGRAPH','GRAPHE DE PREUVES','GRAFO DE EVIDENCIAS','EVIDENSGRAF','EVIDENSGRAF','EVIDENSGRAF'],
    'nav.eyebrow.learning':['RESULTAATKALIBRATIE','OUTCOME CALIBRATION','ERGEBNISKALIBRIERUNG','CALIBRAGE DES RÉSULTATS','CALIBRACIÓN DE RESULTADOS','RESULTATKALIBRERING','RESULTATKALIBRERING','RESULTATKALIBRERING'],
    'nav.eyebrow.automation':['CONTROLEERBARE UITVOERING','AUDITED EXECUTION','PROTOKOLLIERTE AUSFÜHRUNG','EXÉCUTION AUDITÉE','EJECUCIÓN AUDITADA','REVIDERBAR UDFØRELSE','REVIDERBAR UTFØRELSE','GRANSKNINGSBAR KÖRNING'],
    'nav.eyebrow.connectors':['INTEGRATIEBEHEER','INTEGRATION CONTROL PLANE','INTEGRATIONSSTEUERUNG','PILOTAGE DES INTÉGRATIONS','CONTROL DE INTEGRACIONES','INTEGRATIONSSTYRING','INTEGRASJONSSTYRING','INTEGRATIONSSTYRNING'],
    'nav.eyebrow.communication':['OMNICHANNEL BEDRIJFSVOERING','OMNICHANNEL OPERATIONS','OMNICHANNEL-BETRIEB','OPÉRATIONS OMNICANALES','OPERACIONES OMNICANAL','OMNIKANALDRIFT','OMNIKANALDRIFT','OMNIKANALVERKSAMHET'],
    'nav.eyebrow.marketing':['INZICHT IN KLANTWERVING','ACQUISITION INTELLIGENCE','KUNDENGEWINNUNGSANALYSE','ANALYSE DE L’ACQUISITION CLIENT','ANÁLISIS DE CAPTACIÓN','INDSIGT I KUNDETILGANG','INNSIKT I KUNDEVERVING','INSIKT I KUNDANSKAFFNING'],
    'nav.eyebrow.settings':['ORGANISATIEBEHEER','TENANT CONTROL','MANDANTENVERWALTUNG','GESTION DE L’ORGANISATION','GESTIÓN DE LA ORGANIZACIÓN','ORGANISATIONSSTYRING','ORGANISASJONSSTYRING','ORGANISATIONSSTYRNING'],
    'zero.language':['Gesprekstaal van ZERO','ZERO conversation language','Gesprächssprache von ZERO','Langue de conversation de ZERO','Idioma de conversación de ZERO','ZERO-samtalesprog','Samtalespråk for ZERO','Samtalsspråk för ZERO'],
    'zero.greeting_morning':['Goedemorgen, {name}. Waarmee kan ik helpen?','Good morning, {name}. How can I help?','Guten Morgen, {name}. Wie kann ich helfen?','Bonjour, {name}. Comment puis-je vous aider ?','Buenos días, {name}. ¿En qué puedo ayudarte?','Godmorgen, {name}. Hvad kan jeg hjælpe med?','God morgen, {name}. Hva kan jeg hjelpe med?','God morgon, {name}. Vad kan jag hjälpa till med?'],
    'zero.greeting_afternoon':['Goedemiddag, {name}. Waarmee kan ik helpen?','Good afternoon, {name}. How can I help?','Guten Tag, {name}. Wie kann ich helfen?','Bonjour, {name}. Comment puis-je vous aider ?','Buenas tardes, {name}. ¿En qué puedo ayudarte?','God eftermiddag, {name}. Hvad kan jeg hjælpe med?','God ettermiddag, {name}. Hva kan jeg hjelpe med?','God eftermiddag, {name}. Vad kan jag hjälpa till med?'],
    'zero.greeting_evening':['Goedenavond, {name}. Waarmee kan ik helpen?','Good evening, {name}. How can I help?','Guten Abend, {name}. Wie kann ich helfen?','Bonsoir, {name}. Comment puis-je vous aider ?','Buenas noches, {name}. ¿En qué puedo ayudarte?','Godaften, {name}. Hvad kan jeg hjælpe med?','God kveld, {name}. Hva kan jeg hjelpe med?','God kväll, {name}. Vad kan jag hjälpa till med?'],
    'zero.provider_unavailable':['De analyseprovider is niet beschikbaar. Er is geen zakelijke actie uitgevoerd.','The analysis provider is unavailable. No business action was performed.','Der Analysedienst ist nicht verfügbar. Es wurde keine Geschäftsaktion ausgeführt.','Le service d’analyse est indisponible. Aucune action métier n’a été effectuée.','El proveedor de análisis no está disponible. No se ha realizado ninguna acción empresarial.','Analysetjenesten er ikke tilgængelig. Der blev ikke udført nogen forretningshandling.','Analysetjenesten er utilgjengelig. Ingen forretningshandling ble utført.','Analystjänsten är inte tillgänglig. Ingen affärsåtgärd utfördes.'],
    'zero.time':['Het is {time} op {date} in tijdzone {zone}.','It is {time} on {date} in the {zone} time zone.','Es ist {time} am {date} in der Zeitzone {zone}.','Il est {time} le {date} dans le fuseau horaire {zone}.','Son las {time} del {date} en la zona horaria {zone}.','Klokken er {time} den {date} i tidszonen {zone}.','Klokken er {time} den {date} i tidssonen {zone}.','Klockan är {time} den {date} i tidszonen {zone}.'],
    'zero.date':['Het is {date} in tijdzone {zone}.','It is {date} in the {zone} time zone.','Heute ist {date} in der Zeitzone {zone}.','Nous sommes le {date} dans le fuseau horaire {zone}.','Es {date} en la zona horaria {zone}.','Det er {date} i tidszonen {zone}.','Det er {date} i tidssonen {zone}.','Det är {date} i tidszonen {zone}.']
  };
  const staticLookup={};
  for(const [source,translations]of Object.entries(staticRows)){
    let hash=2166136261;for(let i=0;i<source.length;i++)hash=Math.imul(hash^source.charCodeAt(i),16777619);
    const key='static.'+(hash>>>0).toString(16).padStart(8,'0');if(Object.hasOwn(rows,key))throw Error('static_translation_key_collision');
    if(translations.length!==locales.length||translations.some(value=>typeof value!=='string'||!value))throw Error('static_translation_incomplete');
    staticLookup[source]=key;rows[key]=translations;
  }
  const recordCounts=[['{count} record','{count} records'],['{count} record','{count} records'],['{count} Datensatz','{count} Datensätze'],['{count} enregistrement','{count} enregistrements'],['{count} registro','{count} registros'],['{count} post','{count} poster'],['{count} oppføring','{count} oppføringer'],['{count} post','{count} poster']];
  const messages=Object.fromEntries(locales.map((locale,i)=>[locale,Object.freeze({...Object.fromEntries(Object.entries(rows).map(([key,values])=>[key,values[i]])),'common.record_count':Object.freeze({one:recordCounts[i][0],other:recordCounts[i][1]})})]));
  return Object.freeze({locales,names,messages:Object.freeze(messages),staticLookup:Object.freeze(staticLookup)});
});
