'use strict';
const crypto=require('node:crypto'),{timestamp}=require('./calendar-time');
const NAMES=['marketing_spend','campaign_snapshot','ad_impression','ad_click','lead_created','conversion','deal_won','purchase_completed','invoice_paid'];
const FIELDS=['lead_id','source','event_name','campaign_id','provider','currency','value_cents','revenue_cents','attributed_revenue_cents','spend_cents','impressions','clicks','metric_semantics','metric_period_from','metric_period_to','financial_outcome_id','financial_outcome_namespace','financial_outcome_complete'];
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex'),fail=(code,message,statusCode=422)=>{throw Object.assign(Error(message),{code,statusCode});};
const integer=v=>Number.isSafeInteger(v)&&v>=0,currency=v=>typeof v==='string'&&/^[A-Z]{3}$/.test(v),priority={deal_won:1,purchase_completed:2,invoice_paid:3};
function selection(input){
 if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['from','to','campaign_ids','sources','providers'].includes(k)))fail('marketing_metrics_query_invalid','Kies een expliciete periode en bronfilters');
 const from=timestamp(input.from),to=timestamp(input.to);if(to<=from||to-from>366*86400000)fail('marketing_metrics_period_invalid','Kies maximaal 366 dagen');
 const query={from:new Date(from).toISOString(),to:new Date(to).toISOString()},filters={};
 for(const [key,field]of [['campaign_ids','campaign_id'],['sources','source'],['providers','provider']])if(input[key]!==undefined){if(!Array.isArray(input[key])||!input[key].length||input[key].length>20||input[key].some(v=>typeof v!=='string'||!v||v.length>200)||new Set(input[key]).size!==input[key].length)fail('marketing_metrics_filter_invalid','Kies volledige expliciete bronfilters');query[key]=[...input[key]].sort();filters[field]=query[key];}
 return {query,filters};
}
function calculate(events,query,invalidTimestampCount=0){
 const groups=new Map(),outcomes=new Map(),support=[],unresolved=[],metricSources=new Map();
 const group=cur=>{if(!groups.has(cur))groups.set(cur,{currency:cur,spend:0n,revenue:0n,impressions:0n,clicks:0n,seen:new Set(),invalid:new Set(),outcomes:0});return groups.get(cur);};
 const seen=new Set();for(const event of events){
  const eventKey=JSON.stringify([event.source,event.event_id]);if(!event.event_id||!event.source||seen.has(eventKey)){unresolved.push({event_id:event.event_id,source:event.source,reason:'DUPLICATE_OR_MISSING_SOURCE_ID'});continue;}seen.add(eventKey);
  if(priority[event.event_name]){
   const value=event.attributed_revenue_cents??event.revenue_cents??event.value_cents;
   if(!currency(event.currency)||!integer(value)||typeof event.financial_outcome_id!=='string'||!event.financial_outcome_id||typeof event.financial_outcome_namespace!=='string'||!event.financial_outcome_namespace||event.financial_outcome_complete!==true){unresolved.push({event_id:event.event_id,source:event.source,reason:'EXACT_COMPLETE_FINANCIAL_OUTCOME_UNAVAILABLE'});continue;}
   const key=JSON.stringify([event.financial_outcome_namespace,event.financial_outcome_id]);if(!outcomes.has(key))outcomes.set(key,[]);outcomes.get(key).push({...event,selected_value_cents:value});continue;
  }
  if(event.event_name==='lead_created')support.push({event_id:event.event_id,source:event.source,decision:'RECORDED_DISTINCT_LEAD_SOURCE'});
  if(!['marketing_spend','campaign_snapshot'].includes(event.event_name))continue;
  if(!currency(event.currency)){unresolved.push({event_id:event.event_id,source:event.source,reason:'CURRENCY_UNAVAILABLE'});continue;}
  const g=group(event.currency),exactPeriod=event.metric_semantics==='PERIOD_TOTAL'&&event.metric_period_from===query.from&&event.metric_period_to===query.to;
  if(event.metric_semantics!=='DELTA'&&!exactPeriod){for(const field of ['spend','impressions','clicks'])g.invalid.add(field);support.push({event_id:event.event_id,source:event.source,decision:'METRIC_WINDOW_OR_SEMANTICS_UNVERIFIED',currency:event.currency});continue;}
  const scope=JSON.stringify([event.source,event.provider,event.campaign_id,event.currency]),prior=metricSources.get(scope);if(prior&&(prior!=='DELTA'||event.metric_semantics!=='DELTA'))for(const f of ['spend','impressions','clicks'])g.invalid.add(f);metricSources.set(scope,event.metric_semantics);
  for(const [field,key]of [['spend','spend_cents'],['impressions','impressions'],['clicks','clicks']]){if(event[key]===null||event[key]===undefined)continue;if(!integer(event[key]))g.invalid.add(field);else{g[field]+=BigInt(event[key]);g.seen.add(field);}}
  support.push({event_id:event.event_id,source:event.source,decision:'RECORDED_METRIC_INPUT',currency:event.currency,metric_semantics:event.metric_semantics});
 }
 for(const candidates of outcomes.values()){
  const currencies=new Set(candidates.map(e=>e.currency)),highest=Math.max(...candidates.map(e=>priority[e.event_name])),terminal=candidates.filter(e=>priority[e.event_name]===highest);
  if(currencies.size!==1||new Set(terminal.map(e=>e.selected_value_cents)).size!==1){for(const event of candidates)unresolved.push({event_id:event.event_id,source:event.source,reason:'CONFLICTING_FINANCIAL_OUTCOME'});continue;}
  terminal.sort((a,b)=>JSON.stringify([a.source,a.event_id]).localeCompare(JSON.stringify([b.source,b.event_id])));const selected=terminal[0],g=group(selected.currency);g.revenue+=BigInt(selected.selected_value_cents);g.seen.add('revenue');g.outcomes++;
  for(const event of candidates)support.push({event_id:event.event_id,source:event.source,currency:event.currency,decision:event===selected?'SELECTED_TERMINAL_OUTCOME':priority[event.event_name]<highest?'SUPERSEDED_FINANCIAL_STAGE':'DUPLICATE_TERMINAL_OBSERVATION',selected_event_id:selected.event_id,financial_outcome_namespace:event.financial_outcome_namespace,financial_outcome_id:event.financial_outcome_id});
 }
 const number=v=>v<=BigInt(Number.MAX_SAFE_INTEGER)?Number(v):null;
 const rows=[...groups.values()].sort((a,b)=>a.currency.localeCompare(b.currency)).map(g=>{const value=f=>g.seen.has(f)&&!g.invalid.has(f)&&!invalidTimestampCount&&!unresolved.length?number(g[f]):null,spend=value('spend'),revenue=unresolved.length?null:value('revenue'),impressions=value('impressions'),clicks=value('clicks');return {currency:g.currency,spend_cents:spend,revenue_cents:revenue,impressions,clicks,roas:spend>0&&revenue!==null?revenue/spend:null,ctr:impressions>0&&clicks!==null?clicks/impressions*100:null,cpc_cents:clicks>0&&spend!==null?Math.round(spend/clicks):null,reconciled_outcomes:g.outcomes,source_completeness:'UNVERIFIED'};});
 const leadEvents=events.filter(e=>e.event_name==='lead_created'),leadCount=leadEvents.length&&leadEvents.every(e=>typeof e.lead_id==='string'&&e.lead_id)&&!invalidTimestampCount&&!unresolved.length?new Set(leadEvents.map(e=>JSON.stringify([e.source,e.lead_id]))).size:null,conversionCount=rows.reduce((sum,g)=>sum+g.reconciled_outcomes,0);
 return {leads_count:leadCount,conversions_count:conversionCount&&!invalidTimestampCount&&!unresolved.length?conversionCount:null,currency_groups:rows,support,unresolved,invalid_visible_timestamp_count:invalidTimestampCount,financial_reconciliation_complete:unresolved.length===0&&invalidTimestampCount===0,provider_verified:false,scope:'CURRENT_AUTHORIZED_RECORDED_EVENTS',attribution_model:'RECORDED_EXPLICIT_OUTCOME_LINKS',cross_currency_total:null,source_records_modified:false};
}
function compute(core,platform,ctx,actor,input){core.scope(ctx,actor);core.resolver.assertCapability(ctx,actor,'marketing:attribution','read');const {query,filters}=selection(input),events=[],observedTo=new Date(Math.min(Date.parse(query.to),Date.now())).toISOString();if(Date.parse(query.from)>=Date.parse(observedTo))fail('marketing_metrics_period_unobserved','De gekozen periode is nog niet waargenomen');const projection=platform.scanEventsForProjection(ctx,actor,{event_names:NAMES,fields:FIELDS,from:query.from,to:observedTo,filters},event=>events.push(event));events.sort((a,b)=>JSON.stringify([a.source,a.event_id]).localeCompare(JSON.stringify([b.source,b.event_id])));const result=calculate(events,query,projection.invalid_visible_timestamp_count),fingerprint=hash({ctx,actor_id:actor.id,query,events,invalid:projection.invalid_visible_timestamp_count});return {result,events,query,fingerprint,observedTo};}
function query(core,platform,ctx,actor,input){const data=compute(core,platform,ctx,actor,input),{support,unresolved,...result}=data.result;return {...result,query:data.query,query_fingerprint:data.fingerprint,observed_to:data.observedTo,period_complete:data.observedTo===data.query.to,supporting_record_count:support.length,unresolved_record_count:unresolved.length,events_evaluated:data.events.length,source_preview:data.events.slice(0,100),source_preview_truncated:data.events.length>100};}
function drilldown(core,platform,ctx,actor,input){if(!input||Object.keys(input).some(k=>!['query','query_fingerprint','offset','limit'].includes(k))||typeof input.query_fingerprint!=='string'||!/^[a-f0-9]{64}$/.test(input.query_fingerprint))fail('marketing_metrics_drilldown_invalid','Kies een actuele berekening');const offset=input.offset??0,limit=input.limit??50;if(!Number.isSafeInteger(offset)||offset<0||!Number.isSafeInteger(limit)||limit<1||limit>100)fail('marketing_metrics_page_invalid','Kies een geldige bronpagina');const data=compute(core,platform,ctx,actor,input.query);if(data.fingerprint!==input.query_fingerprint)fail('marketing_metrics_source_changed','De bron is gewijzigd; bereken de periode opnieuw',409);const evidence=[...data.result.support,...data.result.unresolved.map(r=>({...r,decision:r.reason}))],events=new Map(data.events.map(e=>[JSON.stringify([e.source,e.event_id]),e]));return {items:evidence.slice(offset,offset+limit).map(e=>({...e,projected_fields:events.get(JSON.stringify([e.source,e.event_id]))||null})),total:evidence.length,offset,limit,next_offset:offset+limit<evidence.length?offset+limit:null,query_fingerprint:data.fingerprint,current_source_revalidated:true,source_records_modified:false};}
module.exports={NAMES,FIELDS,selection,calculate,query,drilldown};
