'use strict';
const crypto=require('node:crypto'),hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const AUDIENCE=['MEMBERS','MEMBER_SAVE','SELECTION','AUDIENCE_FILTERS'],JOURNEY=['JOURNEY_DEFINE','ACTIVATION_PREVIEW','ACTIVATE','JOURNEY_READ','JOURNEY_TASK_COMPLETE','JOURNEY_ADVANCE','JOURNEY_PAUSE','JOURNEY_RESUME','JOURNEY_CANCEL'];
const OPERATIONS=Object.freeze(Object.fromEntries(['HISTORY','VERSION','RESTORE','METRICS','SOURCES',...AUDIENCE,...JOURNEY].map(operation=>{const write=['VERSION','RESTORE','MEMBER_SAVE','AUDIENCE_FILTERS','JOURNEY_DEFINE','ACTIVATE','JOURNEY_TASK_COMPLETE','JOURNEY_ADVANCE','JOURNEY_PAUSE','JOURNEY_RESUME','JOURNEY_CANCEL'].includes(operation);return [operation,{tool:'marketing_'+operation.toLowerCase(),mode:write?'write':'read',permission:write||operation==='ACTIVATION_PREVIEW'?'write':'read',capabilities:AUDIENCE.includes(operation)?['marketing:audiences']:JOURNEY.includes(operation)?['marketing:campaigns','marketing:audiences']:['marketing:'+(['METRICS','SOURCES'].includes(operation)?'attribution':'campaigns')]}];})));

function tools(){return Object.entries(OPERATIONS).map(([operation,op])=>({tool_id:op.tool,name:'Marketing '+operation,engine:'marketing',description:'Actuele creatieve revisies of periodeberekening via native Marketing-beleid.',parameter_schema:{type:'object',properties:{operation:{type:'string',enum:[operation]},input:{type:'object'}},required:['operation','input'],additionalProperties:false},required_permissions:['marketing:'+op.permission],mode:op.mode,risk_level:op.mode==='write'?'MEDIUM_RISK':'READ_ONLY',provider:'foundly_marketing',timeout_ms:3000,retry:{max_attempts:1},confirmation:op.mode==='write'?'explicit_native_policy':'never',handler:'marketing_native',verification:'current_native_sources_and_receipts',audit:'source_free_reference'}));}
function execute(core,platform,ctx,actor,action,meta,communication=null){
 const fail=(code,message,statusCode=422)=>{throw Object.assign(Error(message),{code,statusCode});},op=action&&Object.hasOwn(OPERATIONS,action.operation)&&OPERATIONS[action.operation];
 if(!op||Object.keys(action).some(k=>!['operation','input'].includes(k))||!action.input||typeof action.input!=='object'||Array.isArray(action.input)||JSON.stringify(action).length>128000)fail('marketing_zero_invalid','Kies een expliciete Marketing-actie');core.resolver.assertTool(ctx,actor,op.tool);const request_hash=hash({message:meta.message,action});if(meta.prior&&(meta.prior.request_hash!==request_hash||meta.prior.operation!==action.operation))fail('marketing_zero_turn_conflict','Deze turn hoort bij andere Marketing-invoer',409);
 let data;const options={idempotency_key:hash(['MARKETING_ZERO',actor.id,meta.conversation_id,meta.turn_id])};
 if(AUDIENCE.includes(action.operation)){const {audience_id,...input}=action.input,service=require('./marketing-audiences');if(action.operation==='SELECTION'&&Object.keys(input).length)fail('marketing_zero_invalid','Kies één doelgroep');data=action.operation==='AUDIENCE_FILTERS'?service.filters(core,ctx,actor,audience_id,input,options):action.operation==='MEMBER_SAVE'?service.upsert(core,ctx,actor,audience_id,input,options):action.operation==='MEMBERS'?service.list(core,ctx,actor,audience_id,input):service.selection(core,ctx,actor,audience_id);}
 else if(JOURNEY.includes(action.operation)){const service=require('./marketing-journeys'),execution=require('./marketing-journey-execution');if(action.operation==='JOURNEY_DEFINE'){const {definition_id,...input}=action.input;data=service.define(core,ctx,actor,definition_id,input);}else if(action.operation==='ACTIVATION_PREVIEW')data=service.preview(core,communication,ctx,actor,action.input);else if(action.operation==='ACTIVATE')data=service.activate(core,communication,ctx,actor,action.input,options);else {const {run_id,...input}=action.input;if(action.operation==='JOURNEY_READ'){if(Object.keys(input).length)fail('marketing_zero_invalid','Kies één uitvoering');data=execution.read(core,communication,ctx,actor,run_id);}else if(action.operation==='JOURNEY_TASK_COMPLETE')data=execution.completeTask(core,communication,ctx,actor,run_id,input,options);else if(action.operation==='JOURNEY_ADVANCE')data=execution.advance(core,communication,ctx,actor,run_id,input,options);else data=execution.control(core,communication,ctx,actor,run_id,action.operation.slice(8),input,options);}}
 else {const history=require('./marketing-creative-history');if(action.operation==='METRICS'||action.operation==='SOURCES')data=require('./marketing-metrics')[action.operation==='METRICS'?'query':'drilldown'](core,platform,ctx,actor,action.input);
 else {const {creative_id,revision_id,...input}=action.input;if(typeof creative_id!=='string'||!/^[-A-Za-z0-9_.:]{1,200}$/.test(creative_id))fail('marketing_zero_creative_invalid','Kies expliciet een creatie');if(action.operation==='HISTORY'){if(revision_id!==undefined)fail('marketing_zero_invalid','Kies alleen de creatie en geschiedenispagina');data=history.history(core,ctx,actor,creative_id,input);}else {if(action.operation==='VERSION'&&revision_id!==undefined||action.operation==='RESTORE'&&(typeof revision_id!=='string'||!revision_id))fail('marketing_zero_revision_invalid','Kies expliciet een passende bewaarde revisie');data=history.save(core,ctx,actor,creative_id,input,{idempotency_key:hash(['MARKETING_ZERO',actor.id,meta.conversation_id,meta.turn_id])},revision_id||null);}}
 }
 return {ok:true,status:'completed',modules:['marketing'],answer:op.mode==='write'?'De interne Marketing-actie is geverifieerd. Er is niets gepubliceerd of verstuurd.':'De actuele Marketing-bron is gecontroleerd.',marketing_data:data,marketing_action_reference:{operation:action.operation,tool_id:op.tool,request_hash},actions:[],syncs:[],web:{used:false,sources:[],error:null},voice_mode:'ANALYSIS',plan:{goal:'Gekozen Marketing-actie',steps:['current_native_authority','current_native_source'],tools:[op.tool]},verification:{native_policy:true,publication_executed:false,provider_acceptance:'UNVERIFIED',source_result_retained:false},ui_commands:[]};
}
function retain(result){const {marketing_data,...safe}=result,answer='Marketing-actie verwerkt. Vraag de actuele bron opnieuw op.';return {...safe,answer,display_text:answer,spoken_text:answer,verification:{native_policy:true,current_source_recalculation_required:true,source_result_retained:false,publication_executed:false}};}
module.exports={OPERATIONS,tools,execute,retain};
