'use strict';

(function exposeNeuralRuntime(root){
  const TAU=Math.PI*2;
  const CAMERA_Z=3;
  const FOV_DEGREES=45;
  const ENERGY_CYCLE_SECONDS=3.15;
  const ROTATION_SECONDS=6.3;
  const AUTONOMOUS_ROTATION_SECONDS=28;
  const CORE_ORIGIN=[.09,-.05,0];
  const STATE_VISUALS={
    STANDBY:{level:.16,tempo:.82,bloom:.62,packets:.55},ACTIVATING:{level:.82,tempo:1.32,bloom:1.22,packets:1.34},
    LISTENING:{level:.46,tempo:.90,bloom:.76,packets:.62},THINKING:{level:.72,tempo:1.14,bloom:1.02,packets:1.02},
    SEARCHING:{level:.86,tempo:1.38,bloom:1.16,packets:1.42},PLANNING:{level:.76,tempo:1.06,bloom:.98,packets:.92},
    WAITING_TOOL:{level:.58,tempo:.72,bloom:.78,packets:.62},EXECUTING:{level:1,tempo:1.46,bloom:1.30,packets:1.62},
    WAITING_CONFIRMATION:{level:.48,tempo:.58,bloom:.86,packets:.44},VERIFYING:{level:.74,tempo:1.02,bloom:1.01,packets:.94},
    SPEAKING:{level:.88,tempo:1,bloom:1.16,packets:1.04},SUCCESS:{level:.70,tempo:.88,bloom:1.10,packets:.78},
    WARNING:{level:.58,tempo:.78,bloom:.92,packets:.66},ERROR:{level:.50,tempo:.38,bloom:.72,packets:.30},
    RECOVERING:{level:.62,tempo:.90,bloom:.90,packets:.72},MUTED:{level:.035,tempo:.55,bloom:.32,packets:.30}
  };
  const STATE_LEVEL=Object.fromEntries(Object.entries(STATE_VISUALS).map(([state,profile])=>[state,profile.level]));
  const QUALITY=[
    {name:'LOW',scale:.50,dpr:1,particles:1100,filaments:210,packets:40,raySteps:40,bloomScale:.46,blurPasses:1},
    {name:'BALANCED',scale:.66,dpr:1,particles:2200,filaments:300,packets:60,raySteps:50,bloomScale:.60,blurPasses:1},
    {name:'HIGH',scale:.80,dpr:1.05,particles:3600,filaments:380,packets:80,raySteps:60,bloomScale:.73,blurPasses:1},
    {name:'ULTRA',scale:.93,dpr:1.15,particles:6200,filaments:420,packets:96,raySteps:70,bloomScale:.84,blurPasses:1}
  ];
  // Measured, deliberately asymmetric presentation volumes. These are not orbit anchors.
  const REGIONS=[
    {id:'inkoop',label:'INKOOP',color:'#ff7147',center:[-.58,.70,-.18],spread:[.40,.23,.28]},
    {id:'verkoop',label:'VERKOOP',color:'#00d9ff',center:[-.98,.08,.18],spread:[.48,.30,.30]},
    {id:'data',label:'DATA',color:'#ef45c0',center:[.62,-.10,.14],spread:[.42,.34,.30]},
    {id:'crm',label:'CRM',color:'#18e5a0',center:[.46,-.72,-.10],spread:[.39,.24,.28]},
    {id:'agenda',label:'AGENDA',color:'#ffd17a',center:[.91,.34,.30],spread:[.34,.25,.25]},
    {id:'voorraad',label:'VOORRAAD',color:'#428dff',center:[-.47,-.73,.16],spread:[.43,.26,.32]},
    {id:'social',label:'SOCIAL MEDIA',color:'#ff315b',center:[-.92,.48,-.26],spread:[.39,.28,.25]},
    {id:'google',label:'GOOGLE',color:'#245cff',center:[.19,.80,.04],spread:[.42,.22,.28]},
    {id:'automatisering',label:'AUTOMATISERING',color:'#ff9d3d',center:[-1.27,-.24,.39],spread:[.36,.30,.28]},
    {id:'communicatie',label:'COMMUNICATIE',color:'#18e5a0',center:[1.00,-.42,-.20],spread:[.39,.30,.25]},
    {id:'rapportages',label:'RAPPORTAGES',color:'#ffd17a',center:[.70,.65,.43],spread:[.38,.23,.26]},
    {id:'integraties',label:'INTEGRATIES',color:'#8a3dff',center:[1.24,-.05,.20],spread:[.38,.38,.32]}
  ];
  const MODULES=REGIONS.map(({id,color})=>[id,color]);
  const MODULE_INDEX=Object.fromEntries(MODULES.flatMap(([id],index)=>[[id,index],[id==='social'?'social_media':id==='google'?'google_ads':id,index]]));
  const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,Number(value)||0));
  const color=(hex)=>{const value=parseInt(hex.slice(1),16);return[((value>>16)&255)/255,((value>>8)&255)/255,(value&255)/255]};
  const mix=(a,b,t)=>a+(b-a)*t;
  const length3=(v)=>Math.hypot(v[0],v[1],v[2]);
  const add3=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
  const sub3=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
  const mul3=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];
  const dot3=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
  const cross3=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
  const normalize3=(v)=>{const length=Math.max(.00001,length3(v));return[v[0]/length,v[1]/length,v[2]/length]};
  function normalizeRegions(input=REGIONS){
    if(!Array.isArray(input)||!input.length)return REGIONS.map(region=>({...region,center:[...region.center],spread:[...region.spread]}));
    const seen=new Set(),rows=[];
    for(const candidate of input.slice(0,32)){
      const id=String(candidate?.id||'').trim().toLowerCase().replace(/[^a-z0-9_-]/g,'_').slice(0,48);
      if(!id||seen.has(id))continue;seen.add(id);
      const fallback=REGIONS[rows.length%REGIONS.length],center=Array.isArray(candidate.center)?candidate.center:fallback.center,spread=Array.isArray(candidate.spread)?candidate.spread:fallback.spread;
      rows.push({id,label:String(candidate.label||candidate.name||id).trim().slice(0,48).toUpperCase(),color:/^#[0-9a-f]{6}$/i.test(String(candidate.color||''))?String(candidate.color):fallback.color,center:[clamp(center[0],-2.08,2.08),clamp(center[1],-1.22,1.22),clamp(center[2],-1.05,1.05)],spread:[clamp(spread[0],.08,.72),clamp(spread[1],.08,.58),clamp(spread[2],.08,.52)]});
    }
    return rows.length?rows:normalizeRegions(REGIONS);
  }
  function moduleIndexFor(regions){return Object.fromEntries(regions.flatMap(({id},index)=>[[id,index],[id==='social'?'social_media':id==='google'?'google_ads':id,index]]))}
  function randomFactory(seed=0x51f0a11){let value=seed>>>0;return()=>{value=(value*1664525+1013904223)>>>0;return value/4294967296}}
  function cubic(a,b,c,d,t){const u=1-t;return u*u*u*a+3*u*u*t*b+3*u*t*t*c+t*t*t*d}
  function cubicPoint(path,t){return[0,1,2].map(axis=>cubic(path.p0[axis],path.p1[axis],path.p2[axis],path.p3[axis],t))}
  function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0])}
  function mat4Multiply(a,b){const out=new Float32Array(16);for(let column=0;column<4;column++)for(let row=0;row<4;row++){let sum=0;for(let index=0;index<4;index++)sum+=a[index*4+row]*b[column*4+index];out[column*4+row]=sum}return out}
  function translationMatrix(x=0,y=0,z=0){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,x,y,z,1])}
  function rotationX(angle=0){const c=Math.cos(angle),s=Math.sin(angle);return new Float32Array([1,0,0,0,0,c,s,0,0,-s,c,0,0,0,0,1])}
  function rotationY(angle=0){const c=Math.cos(angle),s=Math.sin(angle);return new Float32Array([c,0,-s,0,0,1,0,0,s,0,c,0,0,0,0,1])}
  function rotationZ(angle=0){const c=Math.cos(angle),s=Math.sin(angle);return new Float32Array([c,s,0,0,-s,c,0,0,0,0,1,0,0,0,0,1])}
  function organismModelMatrix(orientation={}){const yaw=Number(orientation.yaw)||0,pitch=Number(orientation.pitch)||0,roll=Number(orientation.roll)||0,rotation=mat4Multiply(rotationZ(roll),mat4Multiply(rotationY(yaw),rotationX(pitch)));return mat4Multiply(translationMatrix(...CORE_ORIGIN),mat4Multiply(rotation,translationMatrix(-CORE_ORIGIN[0],-CORE_ORIGIN[1],-CORE_ORIGIN[2])))}
  function inverseRigidMatrix(matrix){const out=new Float32Array(16);out[0]=matrix[0];out[1]=matrix[4];out[2]=matrix[8];out[4]=matrix[1];out[5]=matrix[5];out[6]=matrix[9];out[8]=matrix[2];out[9]=matrix[6];out[10]=matrix[10];out[15]=1;const t=[matrix[12],matrix[13],matrix[14]];out[12]=-(out[0]*t[0]+out[4]*t[1]+out[8]*t[2]);out[13]=-(out[1]*t[0]+out[5]*t[1]+out[9]*t[2]);out[14]=-(out[2]*t[0]+out[6]*t[1]+out[10]*t[2]);return out}
  function transformPoint(matrix,point){const x=point[0],y=point[1],z=point[2],w=matrix[3]*x+matrix[7]*y+matrix[11]*z+matrix[15]||1;return[(matrix[0]*x+matrix[4]*y+matrix[8]*z+matrix[12])/w,(matrix[1]*x+matrix[5]*y+matrix[9]*z+matrix[13])/w,(matrix[2]*x+matrix[6]*y+matrix[10]*z+matrix[14])/w]}
  function lookAt(eye,target=[0,0,0],up=[0,1,0]){const z=normalize3(sub3(eye,target)),x=normalize3(cross3(up,z)),y=cross3(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot3(x,eye),-dot3(y,eye),-dot3(z,eye),1])}
  function cameraAt(time=0,motion=1,rig={}){const target=rig.target||[0,0,0],distance=clamp(rig.distance===undefined?CAMERA_Z:rig.distance,2.15,4.6);return[target[0]+.012*Math.sin(time*.17)*motion,target[1]+.008*Math.cos(time*.13)*motion,target[2]+distance+.018*Math.sin(time*.11)*motion]}
  function cameraBasis(camera,target=[0,0,0]){const forward=normalize3(sub3(target,camera)),right=normalize3(cross3(forward,[0,1,0])),up=normalize3(cross3(right,forward));return{forward,right,up}}
  function autonomousOrientationAt(seconds=0,motion=1){const time=Math.max(0,Number(seconds)||0),base=time/AUTONOMOUS_ROTATION_SECONDS*TAU,variation=.17*Math.sin(time*.23)+.065*Math.sin(time*.071);return{yaw:(base+variation)*motion,pitch:(.105*Math.sin(time*.19)+.038*Math.sin(time*.071))*motion,roll:(.026*Math.sin(time*.113)+.012*Math.cos(time*.047))*motion}}
  class NeuralRotationController{
    constructor(){this.autoYaw=0;this.user={yaw:0,pitch:0,roll:0};this.velocity={yaw:0,pitch:0,roll:0};this.dragging=false;this.autoBlend=1;this.resumeDelay=0;this.lastTime=null}
    begin(time=0){this.dragging=true;this.autoBlend=0;this.resumeDelay=Math.max(0,Number(time)||0)+.42;this.velocity.yaw=0;this.velocity.pitch=0}
    drag(dx=0,dy=0,dt=.016){const seconds=Math.max(.008,Math.min(.08,Number(dt)||.016)),scale=.0056;this.user.yaw+=Number(dx||0)*scale;this.user.pitch=clamp(this.user.pitch+Number(dy||0)*scale,-1.42,1.42);this.velocity.yaw=clamp(Number(dx||0)*scale/seconds,-2.8,2.8);this.velocity.pitch=clamp(Number(dy||0)*scale/seconds,-2.2,2.2)}
    end(time=0){this.dragging=false;this.resumeDelay=Math.max(0,Number(time)||0)+.42}
    step(time=0,dt=.016,motion=1){const seconds=Math.max(0,Math.min(.1,Number(dt)||0)),now=Math.max(0,Number(time)||0),speed=(TAU/AUTONOMOUS_ROTATION_SECONDS)*(1+.18*Math.sin(now*.23)+.08*Math.sin(now*.071));if(!this.dragging&&now>=this.resumeDelay)this.autoBlend+= (1-this.autoBlend)*(1-Math.exp(-seconds*2.5));if(this.dragging)this.autoBlend=0;this.autoYaw+=speed*seconds*this.autoBlend*motion;if(!this.dragging){this.user.yaw+=this.velocity.yaw*seconds;this.user.pitch=clamp(this.user.pitch+this.velocity.pitch*seconds,-1.42,1.42);const inertia=Math.exp(-seconds*4.2);this.velocity.yaw*=inertia;this.velocity.pitch*=inertia}this.lastTime=now;return this.orientation(now,motion)}
    orientation(time=0,motion=1){return{yaw:this.autoYaw+this.user.yaw,pitch:this.user.pitch+(.105*Math.sin(time*.19)+.038*Math.sin(time*.071))*motion,roll:this.user.roll+(.026*Math.sin(time*.113)+.012*Math.cos(time*.047))*motion}}
    reset(){this.autoYaw=0;this.user={yaw:0,pitch:0,roll:0};this.velocity={yaw:0,pitch:0,roll:0};this.dragging=false;this.autoBlend=1;this.resumeDelay=0}
  }
  function motionPhaseAt(seconds=0){const time=Math.max(0,Number(seconds)||0),cyclePhase=(time%ENERGY_CYCLE_SECONDS)/ENERGY_CYCLE_SECONDS,rotationPhase=(time%ROTATION_SECONDS)/ROTATION_SECONDS;return{cyclePhase,rotationPhase,energy:Math.pow(Math.abs(Math.cos(rotationPhase*TAU)),3.2)}}
  function referenceMotionAt(seconds=0,phase=.37,tier=1){const time=Math.max(0,Number(seconds)||0),motion=motionPhaseAt(time),clock=time*(.82+tier*.08),localWave=Math.sin(.61*(5.2+tier*1.7)+clock*(.74+tier*.08)+phase*TAU);return{...motion,core_deformation:.018*Math.sin(time/ENERGY_CYCLE_SECONDS*TAU)+.007*Math.sin(time*.73),sheet_normal:[Math.sin(motion.rotationPhase*TAU),.085*Math.sin(motion.rotationPhase*Math.PI),Math.cos(motion.rotationPhase*TAU)],sheet_width:mix(.014,.17,motion.energy),filament_offset:[Math.sin(clock*.66+phase*TAU+3.294),Math.cos(clock*.57+phase*TAU*1.3+2.745),Math.sin(clock*.45-phase*TAU+4.087)].map((value,index)=>value*(.017+.006*tier)+(index===0?localWave*.006:0)),particle_drift:[Math.sin(time*.31+phase*29),Math.cos(time*.25+phase*17),Math.sin(time*.21+phase*37)].map(value=>value*.014),packet_progress:(phase+time*.24)%1}}
  function nextQualityIndex(current,fps,samples=120){let next=clamp(Math.trunc(current),0,QUALITY.length-1);if(Number(fps)<44&&next>0&&Number(samples)>=36)next--;else if(Number(fps)>58&&next<QUALITY.length-1&&Number(samples)>=150)next++;return next}
  function viewProjection(aspect,camera=[0,0,CAMERA_Z],target=[0,0,0]){return mat4Multiply(perspective(FOV_DEGREES*Math.PI/180,aspect,.1,12),lookAt(camera,target))}
  function compile(gl,type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const reason=gl.getShaderInfoLog(shader)||'shader compile failed';gl.deleteShader(shader);throw new Error(reason)}return shader}
  function makeProgram(gl,vertex,fragment){const program=gl.createProgram(),vs=compile(gl,gl.VERTEX_SHADER,vertex),fs=compile(gl,gl.FRAGMENT_SHADER,fragment);gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){const reason=gl.getProgramInfoLog(program)||'shader link failed';gl.deleteProgram(program);throw new Error(reason)}return program}
  function bindAttribute(gl,program,name,size,data,{usage=gl.STATIC_DRAW,divisor=0}={}){const location=gl.getAttribLocation(program,name),buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,usage);if(location>=0){gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,size,gl.FLOAT,false,0,0);if(divisor)gl.vertexAttribDivisor(location,divisor)}return buffer}

  const FULLSCREEN_VERTEX=`#version 300 es
precision highp float;
out vec2 v_uv;
void main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));v_uv=p;gl_Position=vec4(p*2.0-1.0,0.0,1.0);}`;

  const CORE_FRAGMENT=`#version 300 es
precision highp float;
in vec2 v_uv;out vec4 outColor;
uniform vec2 u_resolution;uniform float u_time;uniform float u_state;uniform float u_audio;uniform vec3 u_audio_bands;uniform float u_state_bloom;uniform float u_route_energy;uniform float u_ray_steps;uniform vec3 u_camera;uniform vec3 u_camera_right;uniform vec3 u_camera_up;uniform vec3 u_camera_forward;uniform mat4 u_view_proj;uniform mat4 u_inverse_model;
const float TAU=6.28318530718;
float hash31(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}
float noise3(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash31(i),hash31(i+vec3(1,0,0)),f.x),mix(hash31(i+vec3(0,1,0)),hash31(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash31(i+vec3(0,0,1)),hash31(i+vec3(1,0,1)),f.x),mix(hash31(i+vec3(0,1,1)),hash31(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm(vec3 p){float value=0.,weight=.52;for(int i=0;i<3;i++){value+=noise3(p)*weight;p=p*2.03+vec3(7.1,11.7,5.2);weight*=.48;}return value;}
float smin(float a,float b,float k){float h=clamp(.5+.5*(b-a)/k,0.,1.);return mix(b,a,h)-k*h*(1.-h);}
float ellipsoid(vec3 p,vec3 r){float k0=length(p/r),k1=length(p/(r*r));return k0*(k0-1.)/max(k1,.0001);}
mat2 rot(float angle){float c=cos(angle),s=sin(angle);return mat2(c,-s,s,c);}
vec3 organismPoint(vec3 world){return (u_inverse_model*vec4(world,1.)).xyz;}
float coreSdf(vec3 world){float cyclePhase=u_time/3.15*TAU,breath=1.+.020*sin(cyclePhase)+.008*sin(u_time*.73);vec3 p=(organismPoint(world)-vec3(.09,-.05,0.))/breath;p.xz=rot(.092*sin(u_time*.37)+.034*sin(u_time*.83))*p.xz;p.xy=rot(.054*sin(u_time*.51))*p.xy;float shift=.026*sin(u_time*.67);float d=ellipsoid(p-vec3(-.19+shift,.055,-.030),vec3(.335,.365,.335));d=smin(d,ellipsoid(p-vec3(.185,-.035,.045),vec3(.35,.345,.325)),.082);d=smin(d,ellipsoid(p-vec3(-.125,.305,.055),vec3(.265,.245,.275)),.058);d=smin(d,ellipsoid(p-vec3(.145,-.315,-.035),vec3(.285,.245,.285)),.055);d=smin(d,ellipsoid(p-vec3(.292,.205,-.080),vec3(.225,.225,.255)),.047);d=smin(d,ellipsoid(p-vec3(-.295,-.205,.085),vec3(.225,.235,.255)),.045);d=smin(d,ellipsoid(p-vec3(.015,.025,-.245),vec3(.285,.300,.205)),.056);float turbulence=fbm(p*4.15+vec3(u_time*.055,-u_time*.041,u_time*.032));float scallops=sin(atan(p.y,p.x)*6.+u_time*.31)*exp(-abs(length(p.xy)-.39)*8.5);float fissure=.048*exp(-p.x*p.x*145.)*exp(-(p.z-.12)*(p.z-.12)*9.)*(1.-smoothstep(.36,.67,abs(p.y)));float sideNotches=.014*sin(atan(p.y,p.x)*6.5+noise3(p*4.)*2.2);return d-(turbulence-.5)*.058-scallops*.017+fissure+sideNotches;}
vec3 normalAt(vec3 p){float e=.0026;vec3 a=vec3(1,-1,-1),b=vec3(-1,-1,1),c=vec3(-1,1,-1),d=vec3(1,1,1);return normalize(a*coreSdf(p+a*e)+b*coreSdf(p+b*e)+c*coreSdf(p+c*e)+d*coreSdf(p+d*e));}
vec2 sphereBounds(vec3 ro,vec3 rd,vec3 center,float radius){vec3 oc=ro-center;float b=dot(oc,rd),h=b*b-dot(oc,oc)+radius*radius;if(h<0.)return vec2(-1.);h=sqrt(h);return vec2(-b-h,-b+h);}
void main(){vec2 ndc=v_uv*2.-1.;float aspect=u_resolution.x/max(1.,u_resolution.y),tanHalf=tan(radians(45.)*.5);vec3 ro=u_camera,rd=normalize(u_camera_right*(ndc.x*aspect*tanHalf)+u_camera_up*(ndc.y*tanHalf)+u_camera_forward);vec3 origin=vec3(.09,-.05,0.);vec2 bounds=sphereBounds(ro,rd,origin,.74);float travel=max(bounds.x,0.),minDistance=9.,volume=0.;bool hit=false;vec3 p=ro;
  if(bounds.x>=0.)for(int step=0;step<84;step++){if(float(step)>=u_ray_steps||travel>bounds.y)break;p=ro+rd*travel;float distance=coreSdf(p);minDistance=min(minDistance,abs(distance));volume+=exp(-abs(distance)*24.)*.011;if(distance<.0018){hit=true;break;}travel+=max(.0042,distance*.72);}
  vec3 background=vec3(.0007,.0025,.0105);float star=step(.9982,hash31(vec3(floor(gl_FragCoord.xy*.46),0.)))*(.20+.65*hash31(vec3(gl_FragCoord.xy,7.)));float mist=noise3(vec3(ndc*1.7,u_time*.014));background+=vec3(.0015,.009,.028)*(mist*.12+exp(-dot(ndc,ndc)*.9)*.12)+star*vec3(.10,.24,.44);
  if(!hit){float halo=bounds.x >= 0.0 ? exp(-minDistance*10.)*(.018+.055*abs(cos(u_time/6.3*TAU))) : 0.;outColor=vec4(background+vec3(.008,.16,.38)*halo+vec3(.018,.22,.46)*volume,1.);gl_FragDepth=.999999;return;}
  vec3 n=normalAt(p),q=organismPoint(p)-origin;float facing=max(dot(n,-rd),0.),fresnel=pow(1.-facing,2.05),phase=u_time/6.3*TAU,cycle=pow(abs(cos(phase)),3.2);vec3 sheetNormal=normalize(vec3(sin(phase),.085*sin(phase*.5),cos(phase)));float sheetWidth=mix(.012,.168,smoothstep(0.,1.,cycle)),sheetOffset=.25*cycle;float sheetDistance=abs(dot(q,sheetNormal)-sheetOffset);float sheet=exp(-pow(sheetDistance/max(sheetWidth,.008),2.));float texture=fbm(q*5.2+vec3(u_time*.066,-u_time*.047,u_time*.038));float vein=pow(clamp(1.-abs(fbm(q*9.2-vec3(u_time*.045,0.,u_time*.03))-.5)*2.,0.,1.),4.4);float cavity=clamp(.4+.6*fbm(q*12.+vec3(0.,u_time*.08,-u_time*.05)),0.,1.);float voiceEnergy=clamp(u_audio*.62+dot(u_audio_bands,vec3(.18,.46,.20)),0.,1.);vec3 deep=vec3(.0012,.010,.050),blue=vec3(.016,.135,.70),cyan=vec3(.012,.82,1.42),white=vec3(1.12,1.80,2.08);float diffuse=.11+.89*max(dot(n,normalize(vec3(-.36,.52,.77))),0.);vec3 surface=deep*(.96+texture*.88)+blue*(diffuse*.12+fresnel*(.19+.18*cycle));surface+=cyan*(vein*(.075+.11*voiceEnergy)+sheet*(.10+1.14*cycle+.24*voiceEnergy)+cavity*.025);surface+=white*sheet*sheet*(.018+1.04*cycle+.30*voiceEnergy);surface+=cyan*volume*.20;surface*=.75+.25*u_state+.12*voiceEnergy+.09*u_state_bloom+.16*u_route_energy;surface=surface/(vec3(1.)+surface*.105);outColor=vec4(surface,1.);vec4 clip=u_view_proj*vec4(p,1.);gl_FragDepth=clamp(clip.z/clip.w*.5+.5,0.,.99999);}`;

  const RIBBON_VERTEX=`#version 300 es
precision highp float;
in vec2 a_corner;in vec3 i_p0;in vec3 i_p1;in vec3 i_p2;in vec3 i_p3;in vec3 i_color;in vec4 i_style;in vec4 i_hierarchy;
uniform mat4 u_view_proj;uniform mat4 u_model;uniform vec2 u_resolution;uniform float u_time;uniform float u_state;uniform float u_motion;uniform float u_tempo;uniform float u_route_index;uniform float u_route_energy;
out vec3 v_color;out float v_alpha;out float v_side;out float v_glow;out float v_emission;out float v_foreground;out float v_tier;out float v_bright;out float v_center_guard;out float v_depth_light;
vec3 bezier(float t){float u=1.-t;return u*u*u*i_p0+3.*u*u*t*i_p1+3.*u*t*t*i_p2+t*t*t*i_p3;}
vec3 derivative(float t){float u=1.-t;return 3.*u*u*(i_p1-i_p0)+6.*u*t*(i_p2-i_p1)+3.*t*t*(i_p3-i_p2);}
vec3 flex(vec3 p,float t){float envelope=sin(t*3.14159265),phase=i_style.w*6.2831853,tier=i_hierarchy.x;float amount=(.017+.006*tier+.006*i_hierarchy.z)*u_motion*envelope,clock=u_time*u_tempo;float localWave=sin(t*(5.2+tier*1.7)+clock*(.74+tier*.08)+phase);return p+vec3(sin(clock*.66+phase+t*5.4),cos(clock*.57+phase*1.3+t*4.5),sin(clock*.45-phase+t*6.7))*amount+vec3(localWave,-localWave*.42,localWave*.58)*amount*.38;}
void main(){float t=a_corner.x,side=a_corner.y;vec3 local=flex(bezier(t),t),localAhead=local+normalize(derivative(t))*.018;vec3 p=(u_model*vec4(local,1.)).xyz,aheadWorld=(u_model*vec4(localAhead,1.)).xyz;vec4 clip=u_view_proj*vec4(p,1.),ahead=u_view_proj*vec4(aheadWorld,1.);vec2 tangent=normalize(ahead.xy/ahead.w-clip.xy/clip.w),perpendicular=vec2(-tangent.y,tangent.x);float taper=.20+.80*pow(sin(t*3.14159265),.28),depthScale=3./max(1.15,3.-p.z),width=i_style.x*taper*depthScale;clip.xy+=perpendicular*side*width*2./u_resolution*clip.w;gl_Position=clip;float selected=1.-step(.35,abs(i_style.z-u_route_index)),breath=.91+.12*sin(u_time*(1.28+i_hierarchy.x*.13)+i_style.w*6.2831853+t*2.7);v_color=i_color;v_alpha=i_style.y*(.92+.38*u_state+selected*u_route_energy*1.62);v_side=side;v_glow=selected*u_route_energy;v_emission=i_hierarchy.y*breath;v_foreground=smoothstep(.04,.66,p.z);v_tier=i_hierarchy.x;v_bright=i_hierarchy.w;v_center_guard=smoothstep(.17,.48,length(local-vec3(.09,-.05,0.)));v_depth_light=.68+.44*smoothstep(-.70,.64,p.z);}`;
  const RIBBON_FRAGMENT=`#version 300 es
precision highp float;
in vec3 v_color;in float v_alpha;in float v_side;in float v_glow;in float v_emission;in float v_foreground;in float v_tier;in float v_bright;in float v_center_guard;in float v_depth_light;out vec4 outColor;
void main(){float edge=1.-smoothstep(.18,1.,abs(v_side)),hot=1.-smoothstep(0.,.38,abs(v_side));float alpha=edge*v_alpha;vec3 white=vec3(.88,1.30,1.52),c=mix(v_color,white,hot*(.34+.20*v_bright+.32*v_glow));float centerAttenuation=mix(.55,1.,v_center_guard),energy=v_emission*v_depth_light*centerAttenuation*(1.+v_foreground*.24+hot*(.15+.18*v_bright));outColor=vec4(c*alpha*energy,alpha);}`;

  const PARTICLE_VERTEX=`#version 300 es
precision highp float;
in vec3 a_position;in vec3 a_color;in vec4 a_meta;
uniform mat4 u_view_proj;uniform mat4 u_model;uniform vec2 u_resolution;uniform float u_time;uniform float u_state;uniform float u_audio;uniform float u_motion;uniform float u_tempo;uniform float u_route_index;uniform float u_route_energy;
out vec3 v_color;out float v_alpha;out float v_hot;
void main(){float size=a_meta.x,module=a_meta.y,encodedPhase=a_meta.z,layer=a_meta.w,knot=step(1.,encodedPhase),phase=fract(encodedPhase);vec3 local=a_position;float clock=u_time*u_tempo,drift=(.009+.012*clamp(layer+.8,0.,1.8))*u_motion;local+=vec3(sin(clock*.31+phase*29.),cos(clock*.25+phase*17.),sin(clock*.21+phase*37.))*drift;vec3 p=(u_model*vec4(local,1.)).xyz;gl_Position=u_view_proj*vec4(p,1.);float selected=1.-step(.35,abs(module-u_route_index)),twinkle=.42+.58*pow(.5+.5*sin(clock*(1.25+phase*.8)+phase*31.),4.),depthScale=3./max(1.15,3.-p.z);gl_PointSize=clamp(size*depthScale*(u_resolution.y/1080.)*(.92+u_state*.30+u_audio*.16+selected*u_route_energy*.65+knot*.24),1.,15.);v_color=a_color;v_alpha=twinkle*(.27+.25*u_state+u_audio*.07+selected*u_route_energy*.80+knot*.28);v_hot=max(selected*u_route_energy,knot*.42);}`;
  const PARTICLE_FRAGMENT=`#version 300 es
precision highp float;
in vec3 v_color;in float v_alpha;in float v_hot;out vec4 outColor;
void main(){vec2 q=gl_PointCoord-.5;float r=length(q);if(r>.5)discard;float head=1.-smoothstep(.02,.46,r),hot=1.-smoothstep(0.,.22,r);float alpha=head*v_alpha;outColor=vec4(mix(v_color,vec3(1.4,1.7,1.8),hot*(.45+v_hot*.4))*alpha,alpha);}`;

  const PACKET_VERTEX=`#version 300 es
precision highp float;
in vec3 a_p0;in vec3 a_p1;in vec3 a_p2;in vec3 a_p3;in vec3 a_color;in vec4 a_meta;in float a_trail;
uniform mat4 u_view_proj;uniform mat4 u_model;uniform vec2 u_resolution;uniform float u_time;uniform float u_state;uniform float u_motion;uniform float u_packet_speed;uniform float u_route_index;uniform float u_route_energy;
out vec3 v_color;out float v_alpha;
vec3 bezier(float t){float u=1.-t;return u*u*u*a_p0+3.*u*u*t*a_p1+3.*u*t*t*a_p2+t*t*t*a_p3;}
void main(){float clock=u_time*u_packet_speed,t=fract(a_meta.x+clock*a_meta.y-a_trail*.021);vec3 local=bezier(t);float envelope=sin(t*3.14159265),phase=a_meta.x*37.;local+=vec3(sin(clock*.69+phase),cos(clock*.57+phase*1.3),sin(clock*.43-phase))*.009*u_motion*envelope;vec3 p=(u_model*vec4(local,1.)).xyz;gl_Position=u_view_proj*vec4(p,1.);float selected=1.-step(.35,abs(a_meta.w-u_route_index)),fade=exp(-a_trail*.36),head=1.-step(.5,a_trail);gl_PointSize=clamp(a_meta.z*fade*(u_resolution.y/1080.)*(1.12+selected*u_route_energy+head*.28),1.2,21.);v_color=mix(a_color,vec3(1.55,2.05,2.18),.62);v_alpha=fade*(.48+.35*u_state+selected*u_route_energy*1.05);}`;
  const PACKET_FRAGMENT=`#version 300 es
precision highp float;
in vec3 v_color;in float v_alpha;out vec4 outColor;
void main(){float r=length(gl_PointCoord-.5);if(r>.5)discard;float glow=exp(-r*r*15.);float hot=exp(-r*r*70.);float alpha=(glow*.7+hot*.65)*v_alpha;outColor=vec4((v_color*glow+vec3(1.8)*hot)*v_alpha,alpha);}`;

  const EXTRACT_FRAGMENT=`#version 300 es
precision highp float;
in vec2 v_uv;out vec4 outColor;uniform sampler2D u_source;uniform float u_threshold;
void main(){vec3 c=texture(u_source,v_uv).rgb;float peak=max(c.r,max(c.g,c.b));float contribution=smoothstep(u_threshold,u_threshold+.7,peak);outColor=vec4(c*contribution,1.);}`;
  const BLUR_FRAGMENT=`#version 300 es
precision highp float;
in vec2 v_uv;out vec4 outColor;uniform sampler2D u_source;uniform vec2 u_direction;
void main(){vec3 c=texture(u_source,v_uv).rgb*.227027;c+=texture(u_source,v_uv+u_direction*1.384615).rgb*.316216;c+=texture(u_source,v_uv-u_direction*1.384615).rgb*.316216;c+=texture(u_source,v_uv+u_direction*3.230769).rgb*.070270;c+=texture(u_source,v_uv-u_direction*3.230769).rgb*.070270;outColor=vec4(c,1.);}`;
  const COMPOSITE_FRAGMENT=`#version 300 es
precision highp float;
in vec2 v_uv;out vec4 outColor;uniform sampler2D u_scene;uniform sampler2D u_bloom0;uniform sampler2D u_bloom1;uniform sampler2D u_bloom2;uniform float u_cycle;uniform float u_state_bloom;uniform float u_audio;
void main(){vec3 scene=texture(u_scene,v_uv).rgb;vec3 bloom=texture(u_bloom0,v_uv).rgb*.68+texture(u_bloom1,v_uv).rgb*.46+texture(u_bloom2,v_uv).rgb*.30;float bloomStrength=(.54+.52*u_cycle)*u_state_bloom+u_audio*.09;vec3 hdr=scene+bloom*bloomStrength;float exposure=.80+.26*u_cycle+.04*u_state_bloom+.045*u_audio;vec3 mapped=vec3(1.)-exp(-hdr*exposure);mapped=pow(max(mapped,0.),vec3(1./2.2));vec2 p=v_uv-.5;float vignette=1.-smoothstep(.28,.79,dot(p,p));mapped*=.72+.28*vignette;mapped+=sin(v_uv.y*1600.)*.0012;outColor=vec4(mapped,1.);}`;

  function boundedPoint(point){return[clamp(point[0],-2.08,2.08),clamp(point[1],-1.22,1.22),clamp(point[2],-1.05,1.05)]}
  function regionDirection(region){return normalize3([region.center[0]-CORE_ORIGIN[0],region.center[1]-CORE_ORIGIN[1],region.center[2]])}
  function perpendicular(direction,random){return normalize3([-direction[1],direction[0],(random()-.5)*.72])}
  function primaryPath(region,module,random,index){const direction=regionDirection(region),perp=perpendicular(direction,random),side=index%2?1:-1,p0=add3(CORE_ORIGIN,mul3(direction,.31+random()*.08)),p3=boundedPoint(add3(region.center,[perp[0]*side*mix(.06,.18,random()),perp[1]*side*mix(.06,.18,random()),(random()-.5)*.18]));return{p0,p1:boundedPoint(add3(p0,add3(mul3(direction,.30),mul3(perp,side*mix(.13,.27,random()))))),p2:boundedPoint(add3(p3,add3(mul3(direction,-.24),mul3(perp,-side*mix(.10,.24,random()))))),p3,color:color(region.color),module,width:mix(2.35,4.15,random()),opacity:mix(.48,.72,random()),phase:random(),tier:0,emission:mix(1.65,2.75,random()),foreground:(p0[2]+p3[2])*.5>.08?1:0,bright:random()<.42?1:0,parent:-1,lengthClass:'medium',kind:'primary'} }
  function childPath(region,module,random,parent,tier,index){const p0=cubicPoint(parent,mix(tier===1?.34:.48,.93,random())),base=normalize3([p0[0]-CORE_ORIGIN[0],p0[1]-CORE_ORIGIN[1],p0[2]*.65]),perp=perpendicular(base,random),angle=(random()-.5)*(tier===1?1.45:2.15),outward=normalize3([base[0]*Math.cos(angle)-base[1]*Math.sin(angle),base[0]*Math.sin(angle)+base[1]*Math.cos(angle),(random()-.5)*(tier===1?.56:.78)]),length=tier===1?mix(.18,.58,Math.pow(random(),1.18)):mix(.065,.31,Math.pow(random(),1.35)),foregroundRoll=random(),zBias=foregroundRoll>.74?mix(.16,.42,random()):foregroundRoll<.18?-mix(.12,.36,random()):(random()-.5)*.12,p3=boundedPoint([p0[0]+outward[0]*length,p0[1]+outward[1]*length,p0[2]+outward[2]*length+zBias]),bend=mul3(perp,(random()-.5)*length*(tier===1?.72:.95)),bright=(index%11===0||foregroundRoll>.91)?1:0;return{p0,p1:boundedPoint(add3(p0,add3(mul3(outward,length*.36),bend))),p2:boundedPoint(add3(p3,add3(mul3(outward,-length*.27),mul3(bend,-.56)))),p3,color:color(region.color),module,width:tier===1?mix(1.35,2.65,random()):mix(.78,1.62,random()),opacity:tier===1?mix(.32,.56,random()):mix(.22,.43,random()),phase:random(),tier,emission:tier===1?mix(1.22,2.12,random()):mix(.92,1.68,random()),foreground:(p0[2]+p3[2])*.5>.08?1:0,bright,parent:parent.id,lengthClass:tier===1?(length<.34?'short':'medium'):'short',kind:tier===1?'secondary':'tertiary'} }
  function transitionPath(region,module,random,index){const foreground=index%3!==0,angle=random()*TAU,radius=mix(.38,.56,random()),a=[Math.cos(angle),Math.sin(angle)*1.08],opposite=angle+Math.PI+mix(-.72,.72,random()),z=foreground?mix(.34,.68,random()):-mix(.30,.62,random()),p0=boundedPoint([CORE_ORIGIN[0]+a[0]*radius,CORE_ORIGIN[1]+a[1]*radius,z]),p3=boundedPoint([CORE_ORIGIN[0]+Math.cos(opposite)*mix(.34,.58,random()),CORE_ORIGIN[1]+Math.sin(opposite)*mix(.36,.61,random()),z+(random()-.5)*.18]),arc=mix(.20,.43,random()),p1=boundedPoint([CORE_ORIGIN[0]+a[0]*arc,CORE_ORIGIN[1]+a[1]*arc,z+(foreground?.13:-.08)]),p2=boundedPoint([CORE_ORIGIN[0]+Math.cos(opposite)*arc,CORE_ORIGIN[1]+Math.sin(opposite)*arc,z+(foreground?.09:-.10)]);return{p0,p1,p2,p3,color:color(region.color),module,width:mix(1.85,3.65,random()),opacity:mix(.39,.64,random()),phase:random(),tier:0,emission:mix(1.62,2.55,random())+(index%4===0?.65:0),foreground:foreground?1:0,bright:index%4===0?1:0,parent:-1,lengthClass:'medium',kind:'transition'} }
  function longPath(region,module,random,parent,index){const p0=cubicPoint(parent,mix(.45,.9,random())),direction=regionDirection(region),angle=(random()-.5)*1.1,outward=normalize3([direction[0]*Math.cos(angle)-direction[1]*Math.sin(angle),direction[0]*Math.sin(angle)+direction[1]*Math.cos(angle),(random()-.5)*.46]),extreme=index<6,length=extreme?mix(1.65,2.25,random()):mix(.82,1.48,random()),p3=boundedPoint(add3(p0,mul3(outward,length))),perp=perpendicular(outward,random),bend=mul3(perp,(random()-.5)*length*.72);return{p0,p1:boundedPoint(add3(p0,add3(mul3(outward,length*.32),bend))),p2:boundedPoint(add3(p3,add3(mul3(outward,-length*.28),mul3(bend,-.58)))),p3,color:color(region.color),module,width:mix(1.45,3.10,random()),opacity:mix(.34,.59,random()),phase:random(),tier:1,emission:mix(1.35,2.40,random()),foreground:(p0[2]+p3[2])*.5>.08?1:0,bright:index%4===0?1:0,parent:parent.id,lengthClass:extreme?'extreme':'long',kind:extreme?'extreme':'long'} }

  function createGeometry(inputRegions=REGIONS){
    const regions=normalizeRegions(inputRegions),random=randomFactory(),maxFilaments=QUALITY.at(-1).filaments,groups=regions.map(()=>({primary:[],secondary:[],tertiary:[]})),primary=[],transition=[],long=[],secondary=[],tertiary=[];let nextId=0;
    const counts={primary:Math.max(regions.length*3,Math.round(maxFilaments*.12)),transition:Math.round(maxFilaments*.08),long:Math.round(maxFilaments*.06),secondary:Math.round(maxFilaments*.31)};counts.tertiary=maxFilaments-counts.primary-counts.transition-counts.long-counts.secondary;
    for(let index=0;index<counts.primary;index++){const module=index%regions.length,path=primaryPath(regions[module],module,random,index);path.id=nextId++;primary.push(path);groups[module].primary.push(path)}
    for(let index=0;index<counts.transition;index++){const module=(index*5+3)%regions.length,path=transitionPath(regions[module],module,random,index);path.id=nextId++;transition.push(path)}
    for(let index=0;index<counts.long;index++){const module=(index*7+1)%regions.length,parents=groups[module].primary,parent=parents[index%parents.length],path=longPath(regions[module],module,random,parent,index);path.id=nextId++;long.push(path)}
    for(let index=0;index<counts.secondary;index++){const module=(index*5+2)%regions.length,parents=groups[module].primary,parent=parents[Math.floor(random()*parents.length)],path=childPath(regions[module],module,random,parent,1,index);path.id=nextId++;secondary.push(path);groups[module].secondary.push(path)}
    for(let index=0;index<counts.tertiary;index++){const module=(index*7+4)%regions.length,parents=groups[module].secondary.length?groups[module].secondary:groups[module].primary,parent=parents[Math.floor(random()*parents.length)],path=childPath(regions[module],module,random,parent,2,index);path.id=nextId++;tertiary.push(path);groups[module].tertiary.push(path)}
    const categories=[primary,transition,long,secondary,tertiary],categoryIndex=categories.map(()=>0),paths=[];while(paths.length<maxFilaments){let selected=-1,progress=Infinity;for(let index=0;index<categories.length;index++){if(categoryIndex[index]>=categories[index].length)continue;const candidate=categoryIndex[index]/Math.max(1,categories[index].length);if(candidate<progress){selected=index;progress=candidate}}if(selected<0)break;paths.push(categories[selected][categoryIndex[selected]++])}const corners=[],segments=14;for(let segment=0;segment<segments;segment++){const a=segment/segments,b=(segment+1)/segments;corners.push(a,-1,a,1,b,-1,b,-1,a,1,b,1)}
    const filamentPositions=[],p1=[],p2=[],p3=[],filamentColors=[],styles=[],hierarchy=[];for(const path of paths){filamentPositions.push(...path.p0);p1.push(...path.p1);p2.push(...path.p2);p3.push(...path.p3);filamentColors.push(...path.color);styles.push(path.width,path.opacity,path.module,path.phase);hierarchy.push(path.tier,path.emission,path.foreground,path.bright)}
    const particles=[];for(const path of paths){const endpoint=path.p3,midpoint=cubicPoint(path,.58),knotColor=path.bright||path.foreground?color('#8cecff'):path.color;particles.push({p:endpoint,c:knotColor,meta:[mix(3.4,6.4,random()),path.module,1+random(),endpoint[2]]});if(path.tier===0||path.kind==='long'||path.kind==='extreme')particles.push({p:midpoint,c:knotColor,meta:[mix(2.8,5.2,random()),path.module,1+random(),midpoint[2]]})}
    const knotCount=particles.length,maxParticles=QUALITY.at(-1).particles;while(particles.length<maxParticles){const module=Math.floor(random()*regions.length),region=regions[module],roll=random();let p,c,layer,size;if(roll<.24){const theta=random()*TAU,z=random()*2-1,xy=Math.sqrt(Math.max(0,1-z*z)),radius=mix(.50,.96,Math.pow(random(),.76));p=[CORE_ORIGIN[0]+Math.cos(theta)*xy*radius,CORE_ORIGIN[1]+Math.sin(theta)*xy*radius*1.08,z*radius];c=color(random()<.68?'#245cff':'#00d9ff');layer=z;size=mix(1.25,3.8,random())}else if(roll<.91){const theta=random()*TAU,z=random()*2-1,xy=Math.sqrt(Math.max(0,1-z*z)),spread=region.spread,radius=Math.pow(random(),1.55);p=[region.center[0]+Math.cos(theta)*xy*spread[0]*radius,region.center[1]+Math.sin(theta)*xy*spread[1]*radius,region.center[2]+z*spread[2]*radius];c=color(region.color);layer=p[2];size=mix(1.05,3.8,random())}else{p=[mix(-2.1,2.1,random()),mix(-1.22,1.22,random()),mix(-1.15,.92,random())];c=color(random()<.72?'#245cff':'#00d9ff');layer=p[2];size=mix(.8,2.1,random())}particles.push({p,c,meta:[size,module,random(),layer]})}
    const ambient=particles.splice(knotCount);for(let index=ambient.length-1;index>0;index--){const other=Math.floor(random()*(index+1)),value=ambient[index];ambient[index]=ambient[other];ambient[other]=value}particles.push(...ambient);const particlePositions=[],particleColors=[],particleMeta=[];for(const particle of particles){particlePositions.push(...particle.p);particleColors.push(...particle.c);particleMeta.push(...particle.meta)}
    const packetPaths=[...paths].sort((a,b)=>(b.bright*4+b.foreground*2+(b.tier===0?1:0))-(a.bright*4+a.foreground*2+(a.tier===0?1:0))||a.id-b.id).slice(0,QUALITY.at(-1).packets),packetP0=[],packetP1=[],packetP2=[],packetP3=[],packetColors=[],packetMeta=[],packetTrail=[],packetTrailCount=8;
    for(const path of packetPaths)for(let trail=0;trail<packetTrailCount;trail++){packetP0.push(...path.p0);packetP1.push(...path.p1);packetP2.push(...path.p2);packetP3.push(...path.p3);packetColors.push(...path.color);packetMeta.push(random(),mix(.11,.36,random()),mix(7.0,13.0,random()),path.module);packetTrail.push(trail)}
    return{regions,paths,segments,ribbonVertexCount:segments*6,packetTrailCount,knotCount,counts,filamentPositions:new Float32Array(filamentPositions),filamentP1:new Float32Array(p1),filamentP2:new Float32Array(p2),filamentP3:new Float32Array(p3),filamentColors:new Float32Array(filamentColors),filamentStyles:new Float32Array(styles),filamentHierarchy:new Float32Array(hierarchy),ribbonCorners:new Float32Array(corners),particlePositions:new Float32Array(particlePositions),particleColors:new Float32Array(particleColors),particleMeta:new Float32Array(particleMeta),packetP0:new Float32Array(packetP0),packetP1:new Float32Array(packetP1),packetP2:new Float32Array(packetP2),packetP3:new Float32Array(packetP3),packetColors:new Float32Array(packetColors),packetMeta:new Float32Array(packetMeta),packetTrail:new Float32Array(packetTrail)};
  }

  class FoundlyNeuralRuntime{
    constructor(canvas,{onQuality,onMetrics,regions}={}){this.canvas=canvas;this.onQuality=onQuality||(()=>{});this.onMetrics=onMetrics||(()=>{});this.regions=normalizeRegions(regions);this.modules=this.regions.map(({id,color})=>[id,color]);this.moduleIndex=moduleIndexFor(this.regions);this.state='STANDBY';this.stateVisual=STATE_VISUALS.STANDBY;this.stateLevel=this.stateVisual.level;this.audio={level:0,output:0,voice:0,low:0,mid:0,high:0,speaking:false};this.routeIndex=-99;this.routeEnergy=0;this.focusIndex=-1;this.qualityIndex=2;this.autoQuality=true;this.frames=[];this.slowWindows=0;this.fastWindows=0;this.lastFrame=0;this.lastGovernor=0;this.lastMetrics=0;this.lastLabelPosition=0;this.visible=!document.hidden;this.available=false;this.reducedMotion=Boolean(root.matchMedia?.('(prefers-reduced-motion: reduce)').matches);this.clockStart=performance.now();this.fixedTime=null;this.rotationController=new NeuralRotationController();this.orientation={yaw:0,pitch:0,roll:0};this.model=organismModelMatrix(this.orientation);this.inverseModel=inverseRigidMatrix(this.model);this.cameraRig={target:[0,0,0],desiredTarget:[0,0,0],distance:CAMERA_Z,desiredDistance:CAMERA_Z};this.camera=cameraAt(0,1,this.cameraRig);this.cameraVectors=cameraBasis(this.camera,this.cameraRig.target);this.pointer={id:null,x:0,y:0,at:0};this.interactionDisposers=[];this.runtimeDisposers=[];try{const params=new URLSearchParams(location.search),local=['localhost','127.0.0.1','::1'].includes(location.hostname);if(local&&params.has('visualTime'))this.fixedTime=Math.max(0,Number(params.get('visualTime'))||0)}catch{}this.init()}
    init(){try{const gl=this.canvas?.getContext?.('webgl2',{alpha:false,antialias:false,depth:true,powerPreference:'high-performance',premultipliedAlpha:false,preserveDrawingBuffer:false});if(!gl){this.canvas?.classList.add('hidden');this.onQuality({available:false,name:'FALLBACK'});return}this.gl=gl;if(!gl.getExtension('EXT_color_buffer_float'))throw new Error('RGBA16F framebuffer support ontbreekt');if(!gl.getExtension('EXT_float_blend'))throw new Error('RGBA16F blending support ontbreekt');this.floatLinear=Boolean(gl.getExtension('OES_texture_float_linear'));this.coreProgram=makeProgram(gl,FULLSCREEN_VERTEX,CORE_FRAGMENT);this.ribbonProgram=makeProgram(gl,RIBBON_VERTEX,RIBBON_FRAGMENT);this.particleProgram=makeProgram(gl,PARTICLE_VERTEX,PARTICLE_FRAGMENT);this.packetProgram=makeProgram(gl,PACKET_VERTEX,PACKET_FRAGMENT);this.extractProgram=makeProgram(gl,FULLSCREEN_VERTEX,EXTRACT_FRAGMENT);this.blurProgram=makeProgram(gl,FULLSCREEN_VERTEX,BLUR_FRAGMENT);this.compositeProgram=makeProgram(gl,FULLSCREEN_VERTEX,COMPOSITE_FRAGMENT);this.fullscreenVao=gl.createVertexArray();this.geometry=createGeometry(this.regions);this.setupGeometry();this.coreUniforms=this.uniforms(this.coreProgram,['u_resolution','u_time','u_state','u_audio','u_audio_bands','u_state_bloom','u_route_energy','u_ray_steps','u_camera','u_camera_right','u_camera_up','u_camera_forward','u_view_proj','u_inverse_model']);this.ribbonUniforms=this.uniforms(this.ribbonProgram,['u_view_proj','u_model','u_resolution','u_time','u_state','u_motion','u_tempo','u_route_index','u_route_energy']);this.particleUniforms=this.uniforms(this.particleProgram,['u_view_proj','u_model','u_resolution','u_time','u_state','u_audio','u_motion','u_tempo','u_route_index','u_route_energy']);this.packetUniforms=this.uniforms(this.packetProgram,['u_view_proj','u_model','u_resolution','u_time','u_state','u_motion','u_packet_speed','u_route_index','u_route_energy']);this.extractUniforms=this.uniforms(this.extractProgram,['u_source','u_threshold']);this.blurUniforms=this.uniforms(this.blurProgram,['u_source','u_direction']);this.compositeUniforms=this.uniforms(this.compositeProgram,['u_scene','u_bloom0','u_bloom1','u_bloom2','u_cycle','u_state_bloom','u_audio']);this.available=true;this.resize();this.installLabels();this.installInteraction();this.installLifecycle();this.reportQuality();this.scheduleFrame()}catch(error){this.failRenderer(error,'renderer_initialization_failed')}}
    failRenderer(error,code='renderer_runtime_failed'){console.error('[NEURAL RENDERER]',String(error?.message||error).slice(0,240));this.available=false;this.canvas?.classList.add('hidden');this.onQuality({available:false,name:'FALLBACK',error:code})}
    scheduleFrame(){requestAnimationFrame(time=>{try{this.draw(time)}catch(error){this.failRenderer(error)}})}
    uniforms(program,names){return Object.fromEntries(names.map(name=>[name,this.gl.getUniformLocation(program,name)]))}
    deleteGeometryResources(){if(!this.gl)return;for(const buffer of [...(this.ribbonBuffers||[]),...(this.particleBuffers||[]),...(this.packetBuffers||[])])this.gl.deleteBuffer(buffer);for(const vao of [this.ribbonVao,this.particleVao,this.packetVao])if(vao)this.gl.deleteVertexArray(vao);this.ribbonBuffers=[];this.particleBuffers=[];this.packetBuffers=[]}
    setupGeometry(){const gl=this.gl,g=this.geometry;this.ribbonVao=gl.createVertexArray();gl.bindVertexArray(this.ribbonVao);this.ribbonBuffers=[bindAttribute(gl,this.ribbonProgram,'a_corner',2,g.ribbonCorners),bindAttribute(gl,this.ribbonProgram,'i_p0',3,g.filamentPositions,{divisor:1}),bindAttribute(gl,this.ribbonProgram,'i_p1',3,g.filamentP1,{divisor:1}),bindAttribute(gl,this.ribbonProgram,'i_p2',3,g.filamentP2,{divisor:1}),bindAttribute(gl,this.ribbonProgram,'i_p3',3,g.filamentP3,{divisor:1}),bindAttribute(gl,this.ribbonProgram,'i_color',3,g.filamentColors,{divisor:1}),bindAttribute(gl,this.ribbonProgram,'i_style',4,g.filamentStyles,{divisor:1}),bindAttribute(gl,this.ribbonProgram,'i_hierarchy',4,g.filamentHierarchy,{divisor:1})];this.particleVao=gl.createVertexArray();gl.bindVertexArray(this.particleVao);this.particleBuffers=[bindAttribute(gl,this.particleProgram,'a_position',3,g.particlePositions),bindAttribute(gl,this.particleProgram,'a_color',3,g.particleColors),bindAttribute(gl,this.particleProgram,'a_meta',4,g.particleMeta)];this.packetVao=gl.createVertexArray();gl.bindVertexArray(this.packetVao);this.packetBuffers=[bindAttribute(gl,this.packetProgram,'a_p0',3,g.packetP0),bindAttribute(gl,this.packetProgram,'a_p1',3,g.packetP1),bindAttribute(gl,this.packetProgram,'a_p2',3,g.packetP2),bindAttribute(gl,this.packetProgram,'a_p3',3,g.packetP3),bindAttribute(gl,this.packetProgram,'a_color',3,g.packetColors),bindAttribute(gl,this.packetProgram,'a_meta',4,g.packetMeta),bindAttribute(gl,this.packetProgram,'a_trail',1,g.packetTrail)];gl.bindVertexArray(null)}
    createTarget(width,height,depth=false){const gl=this.gl,texture=gl.createTexture(),filter=this.floatLinear?gl.LINEAR:gl.NEAREST;gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,filter);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,filter);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA16F,width,height,0,gl.RGBA,gl.HALF_FLOAT,null);const framebuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);let depthBuffer=null;if(depth){depthBuffer=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,depthBuffer);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT24,width,height);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,depthBuffer)}if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error('RGBA16F framebuffer incompleet');return{width,height,texture,framebuffer,depthBuffer}}
    deleteTargets(){const gl=this.gl;for(const target of [this.scene,...(this.bloom||[]).flatMap(level=>[level.a,level.b])].filter(Boolean)){gl.deleteTexture(target.texture);gl.deleteFramebuffer(target.framebuffer);if(target.depthBuffer)gl.deleteRenderbuffer(target.depthBuffer)}}
    runtimeSeconds(now=performance.now()){return this.fixedTime===null?(now-this.clockStart)/1000:this.fixedTime}
    installInteraction(){if(!this.canvas?.addEventListener)return;this.canvas.style.touchAction='none';this.canvas.style.cursor='grab';const on=(type,handler,options)=>{this.canvas.addEventListener(type,handler,options);this.interactionDisposers.push(()=>this.canvas.removeEventListener?.(type,handler,options))},down=event=>{if(event.button!==undefined&&event.button!==0)return;const now=performance.now(),time=this.runtimeSeconds(now);this.pointer={id:event.pointerId,x:event.clientX,y:event.clientY,at:now};this.rotationController.begin(time);this.canvas.setPointerCapture?.(event.pointerId);this.canvas.style.cursor='grabbing';event.preventDefault?.()},move=event=>{if(this.pointer.id===null||event.pointerId!==this.pointer.id)return;const now=performance.now(),dt=(now-this.pointer.at)/1000;this.rotationController.drag(event.clientX-this.pointer.x,event.clientY-this.pointer.y,dt);this.pointer.x=event.clientX;this.pointer.y=event.clientY;this.pointer.at=now;event.preventDefault?.()},end=event=>{if(this.pointer.id===null||event.pointerId!==this.pointer.id)return;this.rotationController.end(this.runtimeSeconds());this.canvas.releasePointerCapture?.(event.pointerId);this.pointer.id=null;this.canvas.style.cursor='grab';event.preventDefault?.()},wheel=event=>{this.zoom(event.deltaY>0?.18:-.18);event.preventDefault?.()};on('pointerdown',down);on('pointermove',move);on('pointerup',end);on('pointercancel',end);on('wheel',wheel,{passive:false})}
    installLifecycle(){const listen=(target,type,handler,options)=>{target?.addEventListener?.(type,handler,options);this.runtimeDisposers.push(()=>target?.removeEventListener?.(type,handler,options))},resize=()=>this.resize(),contextLost=event=>{event.preventDefault();this.available=false;this.onQuality({available:false,name:'CONTEXT_LOST'})},visibility=()=>{this.visible=!document.hidden;if(this.visible){this.lastFrame=performance.now();this.scheduleFrame()}},motionQuery=root.matchMedia?.('(prefers-reduced-motion: reduce)'),motionChange=event=>{this.reducedMotion=event.matches};listen(root,'resize',resize,{passive:true});listen(this.canvas,'webglcontextlost',contextLost);listen(document,'visibilitychange',visibility);listen(motionQuery,'change',motionChange)}
    resize(){if(!this.available)return;const profile=QUALITY[this.qualityIndex],dpr=Math.min(devicePixelRatio||1,profile.dpr);this.canvas.width=Math.max(2,Math.floor(innerWidth*dpr*profile.scale));this.canvas.height=Math.max(2,Math.floor(innerHeight*dpr*profile.scale));this.canvas.style.width=innerWidth+'px';this.canvas.style.height=innerHeight+'px';this.camera=cameraAt(0,this.reducedMotion?.35:1,this.cameraRig);this.cameraVectors=cameraBasis(this.camera,this.cameraRig.target);this.viewProj=viewProjection(this.canvas.width/this.canvas.height,this.camera,this.cameraRig.target);this.deleteTargets();this.scene=this.createTarget(this.canvas.width,this.canvas.height,true);this.bloom=[.42,.20,.095].map(scale=>{const adaptiveScale=scale*profile.bloomScale,width=Math.max(2,Math.floor(this.canvas.width*adaptiveScale)),height=Math.max(2,Math.floor(this.canvas.height*adaptiveScale));return{a:this.createTarget(width,height),b:this.createTarget(width,height)}});this.positionLabels()}
    installLabels(){let container=document.getElementById('neuralLabels');if(!container){container=document.createElement('div');container.id='neuralLabels';container.className='neuralLabels';container.setAttribute('aria-label','Foundly engines');document.body.appendChild(container)}container.replaceChildren();this.labels=this.regions.map((region,index)=>{const button=document.createElement('button'),marker=document.createElement('i'),label=document.createElement('span');button.type='button';button.className='neuralRegionLabel';button.dataset.open=region.id;button.style.setProperty('--region',region.color);label.textContent=region.label;button.append(marker,label);button.addEventListener('click',()=>[...document.querySelectorAll('#legend [data-open]')].find(row=>row.dataset.open===region.id)?.click());container.appendChild(button);return{button,index}});this.positionLabels()}
    project(position){const world=transformPoint(this.model||organismModelMatrix(),position),m=this.viewProj,x=world[0],y=world[1],z=world[2],w=m[3]*x+m[7]*y+m[11]*z+m[15],cx=m[0]*x+m[4]*y+m[8]*z+m[12],cy=m[1]*x+m[5]*y+m[9]*z+m[13],cz=m[2]*x+m[6]*y+m[10]*z+m[14];return[(cx/w*.5+.5)*innerWidth,(1-(cy/w*.5+.5))*innerHeight,cz/w,w>0]}
    positionLabels(){if(!this.labels||!this.viewProj)return;for(const {button,index} of this.labels){const [x,y,depth,visible]=this.project(this.regions[index].center);button.style.left=`${x}px`;button.style.top=`${y}px`;button.style.opacity=visible&&depth<1&&x>-80&&x<innerWidth+80&&y>-40&&y<innerHeight+40?(depth>.94?'.42':'.76'):'0'}}
    setState(state){this.state=state in STATE_VISUALS?state:'STANDBY';this.stateVisual=STATE_VISUALS[this.state];this.stateLevel=this.stateVisual.level}
    setAudio(values={}){for(const key of ['level','output','voice','low','mid','high'])if(values[key]!==undefined)this.audio[key]=clamp(values[key]);if(values.speaking!==undefined)this.audio.speaking=Boolean(values.speaking)}
    route(moduleId,energy=1){const index=this.moduleIndex[String(moduleId||'').toLowerCase()];if(index===undefined)return false;this.routeIndex=index;this.routeEnergy=Math.max(this.routeEnergy,clamp(energy,.2,1));return true}
    event(event={}){const hay=`${event.type||''} ${event.module||''} ${event.message||''}`.toLowerCase();for(const [id] of this.modules)if(hay.includes(id.replace('_',' '))){this.route(id,.78);return true}return false}
    focus(moduleId){const index=this.moduleIndex[String(moduleId||'').toLowerCase()];this.focusIndex=index===undefined?-1:index;for(const row of this.labels||[])row.button.classList.toggle('active',row.index===this.focusIndex);if(index===undefined)return false;this.cameraRig.desiredDistance=2.62;this.route(moduleId,.55);return true}
    focusCore(){this.focusIndex=-1;this.cameraRig.desiredTarget=[0,0,0];this.cameraRig.desiredDistance=CAMERA_Z;for(const row of this.labels||[])row.button.classList.remove('active');return true}
    zoom(delta=0){this.cameraRig.desiredDistance=clamp(this.cameraRig.desiredDistance+Number(delta||0),2.15,4.6);return this.cameraRig.desiredDistance}
    rotateView({yaw=0,pitch=0,roll=0,degrees=false}={}){const factor=degrees?Math.PI/180:1;this.rotationController.user.yaw+=Number(yaw||0)*factor;this.rotationController.user.pitch=clamp(this.rotationController.user.pitch+Number(pitch||0)*factor,-1.42,1.42);this.rotationController.user.roll+=Number(roll||0)*factor;return this.getCameraState()}
    cameraCommand(command={}){const value=typeof command==='string'?{type:command}:command,type=String(value.type||'').toUpperCase();if(type==='FOCUS_REGION'||type==='FOCUS_NODE')return this.focus(value.target||value.module);if(type==='FOCUS_CORE'||type==='CENTER_GRAPH'||type==='RESET_CAMERA'){this.rotationController.reset();return this.focusCore()}if(type==='SHOW_BACK'){this.rotateView({yaw:Math.PI});return true}if(type==='ZOOM_IN'){this.zoom(-Math.abs(Number(value.amount)||.25));return true}if(type==='ZOOM_OUT'){this.zoom(Math.abs(Number(value.amount)||.25));return true}if(type==='ROTATE_VIEW'||type==='ORBIT_CAMERA'){this.rotateView(value);return true}return false}
    getCameraState(){return{orientation:{...this.orientation},target:[...this.cameraRig.target],distance:this.cameraRig.distance,desired_distance:this.cameraRig.desiredDistance,manual_active:this.rotationController.dragging,autonomous_blend:this.rotationController.autoBlend,focus:this.focusIndex>=0?this.regions[this.focusIndex]?.id:'core'}}
    setRegions(regions){const next=normalizeRegions(regions);if(!next.length)return false;this.regions=next;this.modules=next.map(({id,color})=>[id,color]);this.moduleIndex=moduleIndexFor(next);this.focusIndex=-1;this.routeIndex=-99;this.routeEnergy=0;if(this.available){this.deleteGeometryResources();this.geometry=createGeometry(next);this.setupGeometry();this.installLabels()}return true}
    setQuality(name){const index=QUALITY.findIndex(row=>row.name===String(name).toUpperCase());if(index<0)return false;this.autoQuality=false;this.qualityIndex=index;this.resize();this.frames=[];this.slowWindows=0;this.fastWindows=0;this.reportQuality();return true}
    setAutoQuality(){this.autoQuality=true;this.frames=[];this.slowWindows=0;this.fastWindows=0;this.reportQuality()}
    setReferenceTime(seconds=null){this.fixedTime=Number.isFinite(Number(seconds))?Math.max(0,Number(seconds)):null;return this.fixedTime}
    getRegions(){return this.regions.map(region=>({...region,center:[...region.center],spread:[...region.spread]}))}
    reportQuality(extra={}){const profile=QUALITY[this.qualityIndex];this.onQuality({available:this.available,name:this.available?profile.name:'FALLBACK',auto:this.autoQuality,particles:profile.particles,filaments:profile.filaments,packets:profile.packets,ray_steps:profile.raySteps,hdr:'RGBA16F',hdr_filter:this.floatLinear?'LINEAR':'NEAREST',bloom_levels:3,bloom_scale:profile.bloomScale,...extra})}
    metrics(time=0){const profile=QUALITY[this.qualityIndex],average=this.frames.length?this.frames.reduce((sum,value)=>sum+value,0)/this.frames.length:16.67;return{available:this.available,quality:profile.name,auto:this.autoQuality,fps:Math.round(1000/average),particles:profile.particles,filaments:profile.filaments,packets:profile.packets,ray_steps:profile.raySteps,state:this.state,route_active:this.routeEnergy>.05,reduced_motion:this.reducedMotion,hdr:'RGBA16F',bloom_levels:3,bloom_scale:profile.bloomScale,energy_cycle_seconds:ENERGY_CYCLE_SECONDS,rotation_seconds:ROTATION_SECONDS,autonomous_rotation_seconds:AUTONOMOUS_ROTATION_SECONDS,autonomous_rotation:true,manual_rotation:true,manual_active:this.rotationController.dragging,autonomous_blend:this.rotationController.autoBlend,orientation:{...this.orientation},cycle_phase:(time%ENERGY_CYCLE_SECONDS)/ENERGY_CYCLE_SECONDS}}
    govern(now){if(!this.autoQuality||this.fixedTime!==null||now-this.lastGovernor<2400||this.frames.length<36)return;this.lastGovernor=now;const stats=this.metrics();this.slowWindows=stats.fps<44?this.slowWindows+1:0;this.fastWindows=stats.fps>58?this.fastWindows+1:0;const mayDowngrade=this.slowWindows>=1,mayUpgrade=this.fastWindows>=3,next=mayDowngrade?nextQualityIndex(this.qualityIndex,stats.fps,this.frames.length):(mayUpgrade?nextQualityIndex(this.qualityIndex,stats.fps,Math.max(150,this.frames.length)):this.qualityIndex);if(next!==this.qualityIndex){this.qualityIndex=next;this.resize();this.frames=[];this.slowWindows=0;this.fastWindows=0;this.reportQuality({fps:stats.fps})}}
    common(program,uniforms,time,{audio=false,motion=false}={}){const gl=this.gl,actualAudio=Math.max(this.audio.level,this.audio.output*.35,this.audio.voice);gl.useProgram(program);if(uniforms.u_view_proj!=null)gl.uniformMatrix4fv(uniforms.u_view_proj,false,this.viewProj);if(uniforms.u_model!=null)gl.uniformMatrix4fv(uniforms.u_model,false,this.model);if(uniforms.u_inverse_model!=null)gl.uniformMatrix4fv(uniforms.u_inverse_model,false,this.inverseModel);if(uniforms.u_resolution!=null)gl.uniform2f(uniforms.u_resolution,this.canvas.width,this.canvas.height);if(uniforms.u_time!=null)gl.uniform1f(uniforms.u_time,time);if(uniforms.u_state!=null)gl.uniform1f(uniforms.u_state,this.stateLevel);if(uniforms.u_state_bloom!=null)gl.uniform1f(uniforms.u_state_bloom,this.stateVisual.bloom);if(uniforms.u_audio!=null&&audio)gl.uniform1f(uniforms.u_audio,actualAudio);if(uniforms.u_audio_bands!=null)gl.uniform3f(uniforms.u_audio_bands,this.audio.low,this.audio.mid,this.audio.high);if(uniforms.u_motion!=null&&motion)gl.uniform1f(uniforms.u_motion,this.reducedMotion?.35:1);if(uniforms.u_tempo!=null)gl.uniform1f(uniforms.u_tempo,this.stateVisual.tempo);if(uniforms.u_packet_speed!=null)gl.uniform1f(uniforms.u_packet_speed,this.stateVisual.packets);if(uniforms.u_ray_steps!=null)gl.uniform1f(uniforms.u_ray_steps,QUALITY[this.qualityIndex].raySteps);if(uniforms.u_camera!=null)gl.uniform3f(uniforms.u_camera,...this.camera);if(uniforms.u_camera_right!=null)gl.uniform3f(uniforms.u_camera_right,...this.cameraVectors.right);if(uniforms.u_camera_up!=null)gl.uniform3f(uniforms.u_camera_up,...this.cameraVectors.up);if(uniforms.u_camera_forward!=null)gl.uniform3f(uniforms.u_camera_forward,...this.cameraVectors.forward);if(uniforms.u_route_index!=null)gl.uniform1f(uniforms.u_route_index,this.routeIndex);if(uniforms.u_route_energy!=null)gl.uniform1f(uniforms.u_route_energy,this.routeEnergy)}
    fullscreen(program,target,width,height){const gl=this.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,target?.framebuffer||null);gl.viewport(0,0,width,height);gl.useProgram(program);gl.bindVertexArray(this.fullscreenVao);gl.drawArrays(gl.TRIANGLES,0,3)}
    draw(now){if(!this.available||!this.visible)return;const dt=this.lastFrame?Math.min(100,now-this.lastFrame):16.67;this.lastFrame=now;if(dt>0&&dt<100)this.frames.push(dt);if(this.frames.length>180)this.frames.shift();this.govern(now);this.routeEnergy*=Math.pow(.988,dt/16.67);if(this.routeEnergy<.002){this.routeEnergy=0;this.routeIndex=-99}const time=this.runtimeSeconds(now),profile=QUALITY[this.qualityIndex],gl=this.gl,motion=this.reducedMotion?.35:1;this.orientation=this.fixedTime===null?this.rotationController.step(time,dt/1000,motion):autonomousOrientationAt(time,motion);this.model=organismModelMatrix(this.orientation);this.inverseModel=inverseRigidMatrix(this.model);this.cameraRig.desiredTarget=this.focusIndex>=0?transformPoint(this.model,this.regions[this.focusIndex].center):this.cameraRig.desiredTarget;const cameraLerp=1-Math.exp(-dt/1000*3.8);for(let axis=0;axis<3;axis++)this.cameraRig.target[axis]+= (this.cameraRig.desiredTarget[axis]-this.cameraRig.target[axis])*cameraLerp;this.cameraRig.distance+= (this.cameraRig.desiredDistance-this.cameraRig.distance)*cameraLerp;this.camera=cameraAt(time,motion,this.cameraRig);this.cameraVectors=cameraBasis(this.camera,this.cameraRig.target);this.viewProj=viewProjection(this.canvas.width/this.canvas.height,this.camera,this.cameraRig.target);if(now-this.lastLabelPosition>120){this.lastLabelPosition=now;this.positionLabels()}
      gl.bindFramebuffer(gl.FRAMEBUFFER,this.scene.framebuffer);gl.viewport(0,0,this.scene.width,this.scene.height);gl.depthMask(true);gl.clearColor(0,0,0,1);gl.clearDepth(1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.disable(gl.BLEND);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.ALWAYS);this.common(this.coreProgram,this.coreUniforms,time,{audio:true});gl.bindVertexArray(this.fullscreenVao);gl.drawArrays(gl.TRIANGLES,0,3);
      gl.depthFunc(gl.LESS);gl.depthMask(false);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE);this.common(this.ribbonProgram,this.ribbonUniforms,time,{motion:true});gl.bindVertexArray(this.ribbonVao);gl.drawArraysInstanced(gl.TRIANGLES,0,this.geometry.ribbonVertexCount,profile.filaments);this.common(this.particleProgram,this.particleUniforms,time,{audio:true,motion:true});gl.bindVertexArray(this.particleVao);gl.drawArrays(gl.POINTS,0,profile.particles);this.common(this.packetProgram,this.packetUniforms,time,{motion:true});gl.bindVertexArray(this.packetVao);gl.drawArrays(gl.POINTS,0,profile.packets*this.geometry.packetTrailCount);
      gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);for(const level of this.bloom){gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.scene.texture);gl.useProgram(this.extractProgram);gl.uniform1i(this.extractUniforms.u_source,0);gl.uniform1f(this.extractUniforms.u_threshold,.49-.05*this.stateVisual.bloom);this.fullscreen(this.extractProgram,level.a,level.a.width,level.a.height);for(let pass=0;pass<profile.blurPasses;pass++){gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,level.a.texture);gl.useProgram(this.blurProgram);gl.uniform1i(this.blurUniforms.u_source,0);gl.uniform2f(this.blurUniforms.u_direction,1/level.a.width,0);this.fullscreen(this.blurProgram,level.b,level.b.width,level.b.height);gl.bindTexture(gl.TEXTURE_2D,level.b.texture);gl.useProgram(this.blurProgram);gl.uniform1i(this.blurUniforms.u_source,0);gl.uniform2f(this.blurUniforms.u_direction,0,1/level.b.height);this.fullscreen(this.blurProgram,level.a,level.a.width,level.a.height)}}
      gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.useProgram(this.compositeProgram);for(const [unit,texture,name] of [[0,this.scene.texture,'u_scene'],[1,this.bloom[0].a.texture,'u_bloom0'],[2,this.bloom[1].a.texture,'u_bloom1'],[3,this.bloom[2].a.texture,'u_bloom2']]){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(this.compositeUniforms[name],unit)}const cycle=motionPhaseAt(time).energy,actualAudio=Math.max(this.audio.level,this.audio.output*.35,this.audio.voice);gl.uniform1f(this.compositeUniforms.u_cycle,cycle);gl.uniform1f(this.compositeUniforms.u_state_bloom,this.stateVisual.bloom);gl.uniform1f(this.compositeUniforms.u_audio,actualAudio);gl.bindVertexArray(this.fullscreenVao);gl.drawArrays(gl.TRIANGLES,0,3);gl.bindVertexArray(null);
      if(now-this.lastMetrics>1000){this.lastMetrics=now;const metrics=this.metrics(time);this.onMetrics(metrics);this.reportQuality({fps:metrics.fps})}this.scheduleFrame()}
    destroy(){this.available=false;for(const dispose of [...this.interactionDisposers.splice(0),...this.runtimeDisposers.splice(0)])try{dispose()}catch{}if(!this.gl)return;this.deleteTargets();this.deleteGeometryResources();for(const program of [this.coreProgram,this.ribbonProgram,this.particleProgram,this.packetProgram,this.extractProgram,this.blurProgram,this.compositeProgram])if(program)this.gl.deleteProgram(program);document.getElementById('neuralLabels')?.remove()}
  }
  root.FoundlyNeuralRuntime=FoundlyNeuralRuntime;
  if(typeof module!=='undefined'&&module.exports)module.exports={FoundlyNeuralRuntime,NeuralRotationController,STATE_LEVEL,STATE_VISUALS,QUALITY,MODULE_INDEX,REGIONS,ENERGY_CYCLE_SECONDS,ROTATION_SECONDS,AUTONOMOUS_ROTATION_SECONDS,FOV_DEGREES,createGeometry,normalizeRegions,cameraAt,cameraBasis,viewProjection,lookAt,mat4Multiply,translationMatrix,rotationX,rotationY,rotationZ,organismModelMatrix,inverseRigidMatrix,transformPoint,autonomousOrientationAt,motionPhaseAt,referenceMotionAt,nextQualityIndex};
})(typeof globalThis!=='undefined'?globalThis:this);
