'use strict';

(function exposeNeuralRuntime(root){
  const STATE_LEVEL={STANDBY:.12,ACTIVATING:.85,LISTENING:.38,THINKING:.68,SEARCHING:.82,PLANNING:.72,WAITING_TOOL:.55,EXECUTING:1,WAITING_CONFIRMATION:.45,VERIFYING:.7,SPEAKING:.78,SUCCESS:.72,WARNING:.52,ERROR:.4,RECOVERING:.56,MUTED:.04};
  const QUALITY=[{name:'LOW',scale:.5},{name:'BALANCED',scale:.68},{name:'HIGH',scale:.82},{name:'ULTRA',scale:1}];
  const MODULE_INDEX={inkoop:0,verkoop:1,data:2,crm:3,agenda:4,voorraad:5,social:6,social_media:6,google:7,google_ads:7,automatisering:8,communicatie:9,rapportages:10,integraties:11};
  class FoundlyNeuralRuntime{
    constructor(canvas,{onQuality}={}){this.canvas=canvas;this.onQuality=onQuality||(()=>{});this.state='STANDBY';this.stateLevel=STATE_LEVEL.STANDBY;this.audio={level:0,low:0,mid:0,high:0};this.routeAngle=0;this.routeEnergy=0;this.qualityIndex=3;this.autoQuality=true;this.frames=[];this.lastFrame=0;this.lastGovernor=0;this.visible=!document.hidden;this.available=false;this.startTime=performance.now();this.init()}
    init(){const gl=this.canvas?.getContext?.('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance',premultipliedAlpha:false});if(!gl){this.canvas?.classList.add('hidden');this.onQuality({available:false,name:'FALLBACK'});return}this.gl=gl;const vertex=`#version 300 es\nprecision highp float;\nout vec2 uv;\nvoid main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);uv=p;gl_Position=vec4(p*2.0-1.0,0.0,1.0);}`;const fragment=`#version 300 es
precision highp float;
out vec4 outColor;in vec2 uv;
uniform vec2 u_resolution;uniform float u_time;uniform float u_state;uniform float u_audio;uniform vec3 u_bands;uniform float u_route;uniform float u_route_energy;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1)),f.x),f.y);}
float lineField(vec2 p,float t){float v=0.0;for(int i=0;i<18;i++){float fi=float(i);float a=fi*.349+t*(.018+mod(fi,3.)*.006);vec2 d=vec2(cos(a),sin(a));float along=dot(p,d),across=abs(dot(p,vec2(-d.y,d.x))-.055*sin(along*6.+t+fi));float gate=1.-smoothstep(.1,1.55,abs(along));v+=(1.-smoothstep(0.,.013,across))*gate*(.24+.76*hash(vec2(fi,4.)));}return v;}
void main(){vec2 p=(uv-.5)*2.;p.x*=u_resolution.x/max(1.,u_resolution.y);float t=u_time;float r=length(p),angle=atan(p.y,p.x);float n=noise(p*3.2+t*.035)+.5*noise(p*7.-t*.022);float core=exp(-r*r*(5.8-u_state*1.8));float shell=exp(-pow(abs(r-(.28+.028*sin(t*1.5))),2.)*180.);float filaments=lineField(p*(1.05+.08*sin(t*.13)),t)*(1.-smoothstep(.12,1.5,r));float nodes=0.;for(int i=0;i<28;i++){float fi=float(i),a=fi*.897+t*(.01+mod(fi,5.)*.004),rr=.32+hash(vec2(fi,9.))*1.1;vec2 q=vec2(cos(a),sin(a))*rr;q+=.035*vec2(sin(t*.6+fi),cos(t*.43+fi*1.7));nodes+=exp(-dot(p-q,p-q)*(900.+hash(vec2(fi))*900.));}float route=exp(-pow(abs(sin(angle-u_route)),2.)*180.)*(1.-smoothstep(.15,1.45,r))*u_route_energy;vec3 cyan=vec3(.12,.72,1.),blue=vec3(.06,.18,.62),violet=vec3(.62,.16,.92),gold=vec3(1.,.48,.08);vec3 color=vec3(.001,.004,.012);color+=blue*(.035+n*.028);color+=cyan*(core*(.42+u_state*.9+u_audio*1.5)+shell*(.12+u_audio*.5));color+=mix(violet,cyan,fract(angle*1.9))*filaments*(.045+u_state*.075);color+=mix(cyan,gold,step(.45,sin(angle*3.+1.)))*nodes*(.18+u_state*.42);color+=gold*route*.58;color+=cyan*pow(max(0.,1.-r),7.)*u_bands.y*.8;float scan=.012*sin((uv.y*u_resolution.y)*.55);color+=scan*vec3(.1,.5,.7);color*=1.-smoothstep(.72,1.45,r);outColor=vec4(pow(color,vec3(.78)),1.);}`;
      const compile=(type,source)=>{const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(shader)||'shader compile failed');return shader};try{const program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vertex));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program)||'shader link failed');this.program=program;this.uniforms=Object.fromEntries(['u_resolution','u_time','u_state','u_audio','u_bands','u_route','u_route_energy'].map(name=>[name,gl.getUniformLocation(program,name)]));this.available=true;this.resize();addEventListener('resize',()=>this.resize(),{passive:true});document.addEventListener('visibilitychange',()=>{this.visible=!document.hidden;if(this.visible){this.lastFrame=performance.now();this.draw(this.lastFrame)}});this.onQuality({available:true,name:QUALITY[this.qualityIndex].name});this.draw(performance.now())}catch(error){console.error('[NEURAL RENDERER]',error.message);this.canvas.classList.add('hidden');this.onQuality({available:false,name:'FALLBACK'})}}
    resize(){if(!this.available)return;const scale=QUALITY[this.qualityIndex].scale,dpr=Math.min(devicePixelRatio||1,this.qualityIndex>=2?1.65:1.15);this.canvas.width=Math.max(1,Math.floor(innerWidth*dpr*scale));this.canvas.height=Math.max(1,Math.floor(innerHeight*dpr*scale));this.canvas.style.width=innerWidth+'px';this.canvas.style.height=innerHeight+'px';this.gl.viewport(0,0,this.canvas.width,this.canvas.height)}
    setState(state){this.state=state in STATE_LEVEL?state:'STANDBY';this.stateLevel=STATE_LEVEL[this.state]}
    setAudio(values={}){this.audio={...this.audio,...values}}
    route(moduleId,energy=1){const index=MODULE_INDEX[moduleId];if(index===undefined)return;this.routeAngle=(index/12)*Math.PI*2+.15;this.routeEnergy=Math.max(this.routeEnergy,Math.max(.2,Math.min(1,energy)))}
    event(event={}){const hay=`${event.type||''} ${event.message||''}`.toLowerCase();for(const id of Object.keys(MODULE_INDEX))if(hay.includes(id.replace('_',' '))){this.route(id,.8);break}}
    setQuality(name){const index=QUALITY.findIndex(row=>row.name===String(name).toUpperCase());if(index>=0){this.autoQuality=false;this.qualityIndex=index;this.resize();this.onQuality({available:true,name:QUALITY[index].name,auto:false})}}
    setAutoQuality(){this.autoQuality=true;this.frames=[];this.onQuality({available:this.available,name:this.available?QUALITY[this.qualityIndex].name:'FALLBACK',auto:true})}
    govern(now,fps){if(!this.autoQuality||now-this.lastGovernor<5000)return;this.lastGovernor=now;let next=this.qualityIndex;if(fps<43&&next>0)next--;else if(fps>58&&next<3&&this.frames.length>=100)next++;if(next!==this.qualityIndex){this.qualityIndex=next;this.resize();this.frames=[];this.onQuality({available:true,name:QUALITY[next].name,auto:true,fps:Math.round(fps)})}}
    draw(now){if(!this.available||!this.visible)return;const dt=this.lastFrame?now-this.lastFrame:16.7;this.lastFrame=now;if(dt<100)this.frames.push(dt);if(this.frames.length>180)this.frames.shift();const fps=this.frames.length?1000/(this.frames.reduce((a,b)=>a+b,0)/this.frames.length):60;this.govern(now,fps);this.routeEnergy*=Math.pow(.992,dt/16.7);const gl=this.gl;gl.useProgram(this.program);gl.uniform2f(this.uniforms.u_resolution,this.canvas.width,this.canvas.height);gl.uniform1f(this.uniforms.u_time,(now-this.startTime)/1000);gl.uniform1f(this.uniforms.u_state,this.stateLevel);gl.uniform1f(this.uniforms.u_audio,this.audio.level||0);gl.uniform3f(this.uniforms.u_bands,this.audio.low||0,this.audio.mid||0,this.audio.high||0);gl.uniform1f(this.uniforms.u_route,this.routeAngle);gl.uniform1f(this.uniforms.u_route_energy,this.routeEnergy);gl.drawArrays(gl.TRIANGLES,0,3);requestAnimationFrame(t=>this.draw(t))}
  }
  root.FoundlyNeuralRuntime=FoundlyNeuralRuntime;
})(typeof globalThis!=='undefined'?globalThis:this);
