'use strict';
const crypto=require('node:crypto'),hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const OPERATIONS=Object.freeze(Object.fromEntries(['ECONOMICS','SNAPSHOT','OUTCOMES','OBSERVE','ALLOCATION','PREPARE'].map(operation=>{const write=['SNAPSHOT','OBSERVE','PREPARE'].includes(operation);return [operation,{tool:'procurement_'+operation.toLowerCase(),mode:write?'write':'read',permission:write?'write':'read',capabilities:['procurement:'+(['ALLOCATION','PREPARE'].includes(operation)?'approvals':'opportunities')]}];})));
function tools(){return Object.entries(OPERATIONS).map(([operation,op])=>({tool_id:op.tool,name:'Procurement '+operation,engine:'procurement',description:'Expliciete inkoopactie via actuele native bron- en goedkeuringsregels.',parameter_schema:{type:'object',properties:{operation:{type:'string',enum:[operation]},input:{type:'object'}},required:['operation','input'],additionalProperties:false},required_permissions:['procurement:'+op.permission],mode:op.mode,risk_level:op.mode==='write'?'MEDIUM_RISK':'READ_ONLY',provider:'foundly_procurement',timeout_ms:3000,retry:{max_attempts:1},confirmation:op.mode==='write'?'explicit_native_policy':'never',handler:'procurement_native',verification:'current_native_sources_and_receipts',audit:'source_free_reference'}));}
function execute(core,ctx,actor,action,meta){
 const fail=(code,message,statusCode=422)=>{throw Object.assign(Error(message),{code,statusCode});},op=action&&Object.hasOwn(OPERATIONS,action.operation)&&OPERATIONS[action.operation];
 if(!op||Object.keys(action).some(k=>!['operation','input'].includes(k))||!action.input||typeof action.input!=='object'||Array.isArray(action.input)||JSON.stringify(action).length>128000)fail('procurement_zero_invalid','Kies een expliciete Procurement-actie');
 core.resolver.assertTool(ctx,actor,op.tool);const request_hash=hash({message:meta.message,action});if(meta.prior&&(meta.prior.request_hash!==request_hash||meta.prior.operation!==action.operation))fail('procurement_zero_turn_conflict','Deze turn hoort bij andere Procurement-invoer',409);
 const options={idempotency_key:hash(['PROCUREMENT_ZERO',actor.id,meta.conversation_id,meta.turn_id])};let data;
 if(action.operation==='OBSERVE')data=require('./procurement-outcomes').record(core,ctx,actor,action.input,options);
 else if(action.operation==='OUTCOMES'){if(Object.keys(action.input).some(k=>k!=='supplier_id')||typeof action.input.supplier_id!=='string')fail('procurement_zero_invalid','Kies één leverancier');data=require('./procurement-outcomes').supplier(core,ctx,actor,action.input.supplier_id);}
 else {const {rfq_id,...input}=action.input;if(typeof rfq_id!=='string'||!/^[-A-Za-z0-9_.:]{1,200}$/.test(rfq_id))fail('procurement_zero_invalid','Kies een actuele aanvraag');
  if(action.operation==='ECONOMICS')data=require('./procurement-economics').compare(core,ctx,actor,rfq_id,input);
  if(action.operation==='SNAPSHOT')data=require('./procurement-economics').snapshot(core,ctx,actor,rfq_id,input,options);
  if(action.operation==='ALLOCATION'){if(Object.keys(input).some(k=>!['allocations','allocation_mode'].includes(k))||!['FULL','INCREMENTAL'].includes(input.allocation_mode))fail('procurement_zero_invalid','Kies de omvang van de toewijzing');data=input.allocation_mode==='INCREMENTAL'?require('./procurement-incremental-allocations').preview(core,ctx,actor,rfq_id,input.allocations):require('./procurement-reviews').previewAllocation(core,ctx,actor,rfq_id,input.allocations);}
  if(action.operation==='PREPARE')data=require('./procurement-reviews').prepareAward(core,ctx,actor,rfq_id,input,options);
 }
 return {ok:true,status:'completed',modules:['procurement'],answer:op.mode==='write'?'De interne Procurement-actie is vastgelegd.':'De actuele Procurement-bron is gecontroleerd.',procurement_data:data,procurement_action_reference:{operation:action.operation,tool_id:op.tool,request_hash},actions:[],syncs:[],web:{used:false,sources:[],error:null},voice_mode:'ANALYSIS',plan:{goal:'Gekozen Procurement-actie',steps:['current_native_authority','current_native_source'],tools:[op.tool]},verification:{native_policy:true,external_commitment:false,provider_acceptance:'UNVERIFIED',source_result_retained:false},ui_commands:[]};
}
function retain(result){const {procurement_data,...safe}=result,answer='Procurement-actie verwerkt. Vraag de actuele bron opnieuw op.';return {...safe,answer,display_text:answer,spoken_text:answer,verification:{native_policy:true,current_source_recalculation_required:true,source_result_retained:false,external_commitment:false}};}
module.exports={OPERATIONS,tools,execute,retain};
