'use strict';
// Cohort controller tests with declared native response shapes. Core computation,
// current permissions and exact definition retry are separately tested natively.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {browserFixture,Element}=require('../zero-evaluation/dom-fixture'),{locales}=require('../foundly-i18n');
class View extends Element{
 constructor(tag='div'){super(tag);Object.defineProperty(this,'dataset',{value:{}});}
 querySelector(tag){return this.all().find(n=>n.tag===tag)||null;}
 append(...nodes){super.append(...nodes);if(this.tag==='select'&&this.children.length===nodes.length&&nodes.length)this.value=nodes[0].value;}
 replaceChildren(...nodes){for(const child of this.children)for(const node of child.all())node.isConnected=false;super.replaceChildren(...nodes);if(this.tag==='select'&&!nodes.length)this.value='';}
}
function fixture(){
 const f=browserFixture('en-GB'),calls=[];for(const id of ['cohortForm','cohortOutput','cohortNotice','cohortDefinitionHistory','cohortDefinitionsForm','cohortSavedDefinition','cohortDefinitionsNotice','cohortSaveDefinitionForm','cohortDefinitionsPrevious','cohortDefinitionsNext','cohortDefinitionsRefresh'])f.nodes[id]=new View(id.endsWith('Form')?'form':id==='cohortSavedDefinition'?'select':'div');
 const definition={from:'2026-01-01T00:00:00Z',to:'2026-02-01T00:00:00Z',acquisition_event:'private_acquisition',return_event:'private_return',identity_field:'customer_id',interval_days:7,periods:3},record={id:'cohort_literal',revision:1234,title:'Literal <script> definition',cohort_definition:definition};
 const addForm=(id,values)=>{const form=f.nodes[id],fieldset=new View('fieldset'),button=new View('button'),inputs={};form.append(fieldset);for(const [name,value]of Object.entries(values)){const input=new View('input');input.name=name;input.value=String(value);inputs[name]=input;fieldset.append(input);}fieldset.append(button);form.elements={namedItem:name=>inputs[name]};form.reportValidity=()=>true;return inputs;};
 const fields=addForm('cohortForm',{...definition,from:definition.from.slice(0,-1),to:definition.to.slice(0,-1)}),saveFields=addForm('cohortSaveDefinitionForm',{title:''});addForm('cohortDefinitionsForm',{});f.nodes.cohortDefinitionsForm.querySelector('fieldset').append(f.nodes.cohortSavedDefinition);
 f.context.document.createElement=tag=>new View(tag);f.context.document.getElementById=id=>f.nodes[id];let next=0;Object.assign(f.context,{crypto:{randomUUID:()=> 'cohort-key-'+(++next)},URLSearchParams,FormData:class{constructor(form){this.entries=form.all().filter(n=>n.name).map(n=>[n.name,String(n.value)]);}get(name){return this.entries.find(row=>row[0]===name)?.[1]??null;}[Symbol.iterator](){return this.entries[Symbol.iterator]();}},FoundlyAnalysisDefinitionHistory:{create(){const view=new View('section');view.textContent='Literal private history';return view;}}});
 const data={available:true,sample_size:1234,data_quality:{excluded_visible_records:0},items:[{from:definition.from,members:1234,cells:[{age:0,from:definition.from,to:definition.to,complete:true,retention_percent:0,observed_returning_members:0},{age:1,from:definition.from,to:definition.to,complete:false,retention_percent:null,observed_returning_members:12}]}],sources:['Literal source <img>'],freshness:'2026-09-24T12:34:00Z',supporting_records:[{event_id:'literal-private-event',event_name:'Literal event <img>',source:'Literal provider',occurred_at:'2026-01-02T00:00:00Z',provider_verified:false}],supporting_record_count:1234};
 let deny=false,lose=false,hold=null,holdRoute='',holdRemaining=0,started=()=>{};
 const request=async(route,options)=>{calls.push({route,options});if(deny)throw Object.assign(Error('RAW_PRIVATE_ERROR'),{status:403});if(hold&&route.startsWith(holdRoute)&&holdRemaining-->0){started();await hold;}if(options?.method==='POST'){if(lose){lose=false;throw Error('Lost response after write')}return {record};}if(route.includes('/query?')||route.startsWith('/api/analysis/cohorts?'))return data;if(route.includes('?offset='))return {items:[record],total:1,next_offset:null};return {record};};
 vm.runInContext(fs.readFileSync(require.resolve('../analysis-cohorts-client.js'),'utf8'),f.context);const view=f.context.FoundlyCohortUI.mount(f.context.document,request);
 return {...f,view,fields,saveFields,record,data,calls,i:f.context.FoundlyI18n,deny:()=>deny=true,lose:()=>lose=true,hold(route){holdRoute=route;holdRemaining=1;let release;hold=new Promise(resolve=>release=resolve);release.started=new Promise(resolve=>started=resolve);return release;},async start(){await view.setEnabled(true,true);await Promise.resolve();},async loadDefinition(){f.nodes.cohortSavedDefinition.value=record.id;await f.nodes.cohortDefinitionsForm.fire('submit');},key(name){return Object.values(f.nodes).flatMap(n=>n.all()).find(n=>n.getAttribute('data-i18n')==='analysis.cohorts.'+name);}};
}
test('revoking cohort access clears source-populated definition fields as well as results and history',async()=>{
 const f=fixture();await f.start();await f.loadDefinition();assert.equal(f.fields.acquisition_event.value,'private_acquisition');f.view.setEnabled(false);assert.equal(f.fields.acquisition_event.value,'');assert.equal(f.fields.return_event.value,'');assert.equal(f.nodes.cohortDefinitionHistory.children.length,0);assert.equal(f.view.selectedDefinition(),null);
});
test('cohort tables and tooltips follow all locales while source identities, query values and selected revision stay unchanged',async()=>{
 const f=fixture();await f.start();await f.loadDefinition();f.data.items[0].cells[0].retention_percent=12.5;const original=JSON.stringify(f.data);await f.nodes.cohortForm.fire('submit');const query=f.calls.at(-1);assert.equal(query.route,'/api/analysis/cohort_definitions/cohort_literal/query?expected_revision=1234');const table=f.nodes.cohortOutput.children[0],row=table.children[2].children[0],n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.cohortOutput.children[0],table);assert.equal(row.children[1].textContent,f.i.number(1234));assert.equal(row.children[2].textContent,f.i.number(0.125,{style:'percent',maximumFractionDigits:1}));assert.equal(row.children[3].textContent,f.i.t('analysis.cohorts.incomplete'));assert.equal(row.children[2].getAttribute('title'),f.i.t('analysis.cohorts.cell_evidence',{members:f.i.number(0),from:f.i.date(f.record.cohort_definition.from,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}),to:f.i.date(f.record.cohort_definition.to,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'})}));assert.ok(f.key('source_record').textContent.includes('Literal event <img>'));assert.ok(f.key('source_record').textContent.includes('literal-private-event'));assert.ok(f.key('source_record').textContent.includes(f.i.t('analysis.cohorts.unverified')));assert.equal(f.fields.acquisition_event.value,'private_acquisition');assert.equal(f.fields.from.value,'2026-01-01T00:00:00');assert.equal(f.nodes.cohortSavedDefinition.value,'cohort_literal');assert.equal(f.calls.length,n);assert.equal(JSON.stringify(f.data),original);assert.deepEqual(JSON.parse(JSON.stringify(f.view.selectedDefinition())),{id:'cohort_literal',revision:1234});assert.equal(f.i.missingKeys().length,0);}
});
test('cohort saving freezes the actual request while busy, retains authored inputs and retries the same native key after a lost response across locales',async()=>{
 const f=fixture();await f.start();f.fields.acquisition_event.value='Authored event <img>';f.saveFields.title.value='Authored cohort <script>';f.lose();const release=f.hold('/api/analysis/cohort_definitions'),pending=f.nodes.cohortSaveDefinitionForm.fire('submit');await release.started;const n=f.calls.length;await f.nodes.cohortSaveDefinitionForm.fire('submit');assert.equal(f.calls.length,n);
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,n);assert.equal(f.fields.acquisition_event.value,'Authored event <img>');assert.equal(f.saveFields.title.value,'Authored cohort <script>');assert.equal(f.nodes.cohortSaveDefinitionForm.querySelector('button').disabled,true);}
 release();await pending;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.cohortNotice.textContent,f.i.t('analysis.cohorts.save_failed',{reason:f.i.t('common.request_failed')}));}await f.nodes.cohortSaveDefinitionForm.fire('submit');const writes=f.calls.filter(c=>c.options?.method==='POST');assert.equal(writes.length,2);assert.deepEqual(writes[0],writes[1]);const body=JSON.parse(writes[0].options.body);assert.equal(body.title,'Authored cohort <script>');assert.equal(body.cohort_definition.acquisition_event,'Authored event <img>');assert.equal(body.cohort_definition.from,'2026-01-01T00:00:00Z');assert.ok(!f.calls.some(c=>c.route.includes('/query?')||c.route.startsWith('/api/analysis/cohorts?')),'Saving never computes a result');assert.equal(f.i.missingKeys().length,0);
});
test('denied definition refresh removes loaded titles, source fields and history; late cohort replies cannot restore them',async()=>{
 const f=fixture();await f.start();await f.loadDefinition();const release=f.hold('/api/analysis/cohort_definitions/cohort_literal/query'),pending=f.nodes.cohortForm.fire('submit');await release.started;f.deny();await f.nodes.cohortDefinitionsRefresh.fire('click');release();await pending;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.cohortOutput.children.length,0);assert.equal(f.nodes.cohortDefinitionHistory.children.length,0);assert.equal(f.fields.acquisition_event.value,'');assert.equal(f.nodes.cohortSavedDefinition.children.length,0);assert.equal(f.view.selectedDefinition(),null);assert.equal(f.nodes.cohortNotice.textContent,f.i.t('analysis.cohorts.access_required'));assert.equal(f.nodes.cohortDefinitionsNotice.textContent,f.i.t('analysis.cohorts.definitions_failed',{reason:f.i.t('common.access_denied')}));assert.ok(!f.nodes.cohortNotice.textContent.includes('Literal'));assert.equal(f.i.missingKeys().length,0);}
});
test('unknown counts, malformed percentages and non-boolean provider verification do not become zero, a final percentage or verified evidence',async()=>{
 const f=fixture();await f.start();f.data.sample_size=null;f.data.items[0].members=0;f.data.items[0].cells[0].retention_percent=false;f.data.items[0].cells[1].retention_percent=50;f.data.supporting_records[0].provider_verified='true';f.data.supporting_record_count=undefined;await f.nodes.cohortForm.fire('submit');const row=f.nodes.cohortOutput.children[0].children[2].children[0];
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.cohortNotice.textContent,f.i.t('analysis.cohorts.observations',{members:f.i.t('common.unknown'),excluded:f.i.number(0)}));assert.equal(row.children[1].textContent,f.i.number(0));assert.equal(row.children[2].textContent,f.i.t('common.unknown'));assert.equal(row.children[3].textContent,f.i.t('analysis.cohorts.incomplete'));assert.ok(f.key('references').textContent.includes(f.i.t('common.unknown')));assert.ok(f.key('source_record').textContent.includes(f.i.t('analysis.cohorts.unverified')));assert.equal(f.i.missingKeys().length,0);}
});
test('editing a pending cohort query permits a new query; the old completion cannot enable its button or show stale results',async()=>{
 const f=fixture();await f.start();const firstRelease=f.hold('/api/analysis/cohorts?'),first=f.nodes.cohortForm.fire('submit');await firstRelease.started;f.fields.acquisition_event.value='new_source';await f.nodes.cohortForm.fire('input');const secondRelease=f.hold('/api/analysis/cohorts?'),second=f.nodes.cohortForm.fire('submit');await secondRelease.started;firstRelease();await first;assert.equal(f.nodes.cohortForm.querySelector('button').disabled,true);assert.equal(f.nodes.cohortOutput.children.length,0);secondRelease();await second;assert.equal(f.nodes.cohortForm.querySelector('button').disabled,false);assert.ok(f.nodes.cohortOutput.children.length>0);assert.equal(f.calls.at(-1).route.includes('acquisition_event=new_source'),true);
});
