'use strict';
// Tests the actual presentation controller with declared response fixtures.
// Native approval/execution/permission/persistence contracts remain covered by
// analysis-actions-client-test.js in both native and ZERO modes.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {browserFixture}=require('../zero-evaluation/dom-fixture'),{locales}=require('../foundly-i18n');
function fixture(){
  const f=browserFixture('en-GB'),calls=[];let nextKey=0;f.context.crypto={randomUUID:()=> 'action-key-'+(++nextKey)};
  const record={id:'proposal_1',title:'Voorstel goedkeuren <literal title>',status:'APPROVAL_REQUIRED',revision:1234,source_snapshot:{name:'Broncontrole: <literal source>'},target:{kind:'CREATE_ANALYSIS_REPORT',title:'Kies de beoordelaar',content:'Literal <img> report'},owner_id:'owner_literal',reviewer_id:'reviewer_literal',reason:'Literal reason',reviews:[{decision:'APPROVE',actor_id:'reviewer_literal',at:'2026-09-24T12:34:00Z',reason:'Literal review reason'}]};
  const list={items:[record],total:1234,next_offset:null},detail={record,source_status:'CURRENT',can_review:true,can_execute:false,can_cancel:false,current_outcome:null};
  let deny=false,lose=false,held=null;
  const request=async(route,options)=>{calls.push({route,options});if(deny)throw Object.assign(Error('RAW_PRIVATE_ERROR'),{status:403});if(route==='/api/sales/sequences')return {can_create:true,total:1,limit:250,items:[{id:'sequence_literal',title:'Sales-reeks <literal>',version:1234,steps:[{kind:'PREPARE_MAIL_DRAFT',title:'Literal draft step'}]}]};if(route==='/api/sales/opportunities?limit=250')return {total:1,limit:250,items:[{id:'opportunity_literal',title:'Verkoopkans <literal>',revision:2345}]};if(route.includes('reviewers?q='))return {items:[{id:'reviewer_literal',display_name:'Beoordelaar zoeken <literal reviewer>'}],limited:false};if(route.endsWith('/preview'))return {source_count:1234,reviewer_id:'reviewer_literal',preview_fingerprint:'literal_fingerprint',group:{literal:'Kies de beoordelaar'},target:record.target};if(options?.method==='POST'){if(lose){lose=false;throw Error('Lost response after write')}return {record};}if(route.includes('?limit='))return list;if(held)await held;return detail;};
  vm.runInContext(fs.readFileSync(require.resolve('../analysis-actions-client.js'),'utf8'),f.context);
  const box=f.nodes.actions=f.context.FoundlyAnalysisActions.create({document:f.context.document,request});
  const key=(name,tag)=>box.all().find(node=>node.getAttribute('data-i18n')==='analysis.actions.'+name&&(!tag||node.tag===tag));
  const field=name=>key(name,'label').children[0];
  return {...f,box,record,list,detail,calls,key,field,i:f.context.FoundlyI18n,deny:()=>deny=true,lose:()=>lose=true,holdDetail(){let release;held=new Promise(resolve=>release=resolve);return release;}};
}
test('Analysis action details and confirmation change all locales in place while literal evidence and exact native approval requests remain unchanged',async()=>{
  const f=fixture();await f.box.setEnabled(true,true);await f.key('view','button').fire('click');await f.key('approve','button').fire('click');const reason=f.field('reason'),confirm=f.field('confirm_action'),form=f.key('submit','button').parentNode;reason.value='Exact <literal> approval reason';confirm.checked=true;await form.fire('input');const original=JSON.stringify(f.record),before=f.calls.length;
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.field('reason'),reason);assert.equal(f.field('confirm_action'),confirm);assert.equal(reason.value,'Exact <literal> approval reason');assert.equal(confirm.checked,true);assert.equal(f.key('submit','button').textContent,f.i.t('analysis.actions.submit'));assert.equal(f.calls.length,before);assert.equal(JSON.stringify(f.record),original);assert.equal(f.i.missingKeys().length,0);}
  f.lose();await form.fire('submit');assert.equal(f.box.children[0].textContent,f.i.t('common.request_failed'));const first=f.calls.at(-1);
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.box.children[0].textContent,f.i.t('common.request_failed'));assert.equal(f.field('reason').value,'Exact <literal> approval reason');assert.equal(confirm.checked,true);}
  await form.fire('submit');const writes=f.calls.filter(call=>call.options?.method==='POST');assert.equal(writes.length,2);assert.deepEqual(writes[0],writes[1]);assert.equal(first.route,'/api/analysis/action_proposals/proposal_1/approve');assert.deepEqual(JSON.parse(first.options.body),{expected_revision:1234,decision:'APPROVE',confirm:true,reason:'Exact <literal> approval reason'});
  const heading=f.box.all().find(node=>node.tag==='h3'),source=f.box.all().find(node=>node.tag==='pre');
  for(const locale of locales){f.i.setLocale(locale);assert.equal(heading.textContent,f.record.title);assert.equal(source.textContent,JSON.stringify(f.record.source_snapshot,null,2));assert.ok(f.box.textContent.includes(f.i.t('analysis.actions.state.current')));assert.ok(f.box.textContent.includes(f.i.number(1234)));assert.ok(!f.box.textContent.includes('RAW_PRIVATE_ERROR'));}
});
test('Analysis proposal editing, reviewer selection, validation and preview preserve authored values across locale changes without extra writes',async()=>{
  const f=fixture();await f.box.setEnabled(true,true);await f.box.propose({model_id:'model_literal',model_revision:2,query_fingerprint:'q_literal',group_id:'group_literal'});f.field('report_title').value='Rapporttitel <literal title>';f.field('report_body').value='Literal body <script>';f.field('reviewer_query').value='reviewer';await f.field('reviewer_query').fire('input');await f.key('reviewers_search','button').fire('click');f.field('reviewer').value='reviewer_literal';await f.field('reviewer').fire('change');
  const title=f.field('report_title'),body=f.field('report_body'),picker=f.field('reviewer'),before=f.calls.length;
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.field('report_title'),title);assert.equal(title.value,'Rapporttitel <literal title>');assert.equal(body.value,'Literal body <script>');assert.equal(picker.value,'reviewer_literal');assert.equal(picker.children[1].textContent,'Beoordelaar zoeken <literal reviewer>');assert.equal(f.field('kind').value,'CREATE_ANALYSIS_REPORT');assert.equal(f.calls.length,before);assert.equal(f.i.missingKeys().length,0);}
  await f.key('preview','button').fire('click');const preview=f.calls.at(-1);assert.equal(preview.route,'/api/analysis/action_proposals/preview');assert.deepEqual(JSON.parse(preview.options.body).target,{kind:'CREATE_ANALYSIS_REPORT',title:'Rapporttitel <literal title>',content:'Literal body <script>'});
  await f.key('save','button').fire('click');const count=f.calls.length;assert.equal(f.box.children[0].textContent,f.i.t('analysis.actions.confirm_reason'));
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.box.children[0].textContent,f.i.t('analysis.actions.confirm_reason'));assert.equal(f.calls.length,count);assert.equal(f.field('report_title'),title);assert.ok(f.key('preview_source').textContent.includes(f.i.number(1234)));assert.ok(f.key('preview_source').textContent.includes('reviewer_literal'));}
  f.field('reason').value='Exact proposal reason';f.field('confirm_proposal').checked=true;await f.key('save','button').fire('click');const saved=f.calls.find(call=>call.route==='/api/analysis/action_proposals'&&call.options?.method==='POST');assert.ok(saved);assert.equal(JSON.parse(saved.options.body).preview_fingerprint,'literal_fingerprint');assert.equal(JSON.parse(saved.options.body).target.content,'Literal body <script>');
});
test('a denied proposal-list refresh removes previously viewed private source details as well as the list',async()=>{
  const f=fixture();await f.box.setEnabled(true,true);await f.key('view','button').fire('click');assert.ok(f.box.textContent.includes('literal source'));f.deny();await f.box.refresh();
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.box.children[0].textContent,f.i.t('common.access_denied'));assert.equal(f.box.children[1].children.length,0);assert.equal(f.box.children[2].children.length,0);assert.equal(f.box.children[3].children.length,0);assert.ok(!f.box.textContent.includes('literal source'));assert.ok(!f.box.textContent.includes('RAW_PRIVATE_ERROR'));}
});
test('Sales sequence choices, authored mail and native enum values survive all interface locales without triggering execution',async()=>{
  const f=fixture();await f.box.setEnabled(true,true);await f.box.propose({model_id:'model_literal',model_revision:2,query_fingerprint:'q_literal',group_id:'group_literal'});f.field('kind').value='START_SALES_SEQUENCE';await f.field('kind').fire('change');f.field('sales_sequence').value='sequence_literal';await f.field('sales_sequence').fire('change');f.field('opportunity').value='opportunity_literal';f.field('execution').value='AUTOMATIC_INTERNAL';f.field('starts').value='2026-10-01T09:00:00+02:00';f.field('mail_title').value='Literal subject';f.field('mail_body').value='Literal <img> draft';f.field('to').value='one@example.test, two@example.test';f.field('cc').value='copy@example.test';f.field('reviewer_query').value='reviewer';await f.key('reviewers_search','button').fire('click');f.field('reviewer').value='reviewer_literal';await f.field('reviewer').fire('change');const calls=f.calls.length,select=f.field('sales_sequence');
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.field('sales_sequence'),select);assert.equal(select.value,'sequence_literal');assert.equal(select.children[1].textContent,f.i.t('analysis.actions.version',{title:'Sales-reeks <literal>',value:f.i.number(1234)}));assert.equal(f.field('opportunity').value,'opportunity_literal');assert.equal(f.field('execution').value,'AUTOMATIC_INTERNAL');assert.equal(f.field('starts').value,'2026-10-01T09:00:00+02:00');assert.equal(f.field('mail_body').value,'Literal <img> draft');assert.equal(f.calls.length,calls);assert.equal(f.i.missingKeys().length,0);}
  await f.key('preview','button').fire('click');assert.deepEqual(JSON.parse(f.calls.at(-1).options.body).target,{kind:'START_SALES_SEQUENCE',definition_id:'sequence_literal',input:{opportunity_id:'opportunity_literal',expected_opportunity_revision:2345,starts_at:'2026-10-01T09:00:00+02:00',execution_mode:'AUTOMATIC_INTERNAL',mail_drafts:{0:{title:'Literal subject',content:'Literal <img> draft',to:['one@example.test','two@example.test'],cc:['copy@example.test']}}}});assert.equal(f.calls.filter(call=>call.options?.method==='POST').length,1,'Only the explicitly requested preview is sent');
});
test('late detail reads cannot restore source content after a newer denied list refresh',async()=>{
  const f=fixture();await f.box.setEnabled(true,true);const release=f.holdDetail(),pending=f.key('view','button').fire('click');f.deny();await f.box.refresh();release();await pending;assert.equal(f.box.children[2].children.length,0);assert.equal(f.box.children[0].textContent,f.i.t('common.access_denied'));assert.ok(!f.box.textContent.includes('literal source'));
});
