'use strict';
// Runs production presentation controllers against declared response fixtures.
// Native persistence, permissions, revision conflicts and rollback remain
// exercised by analysis-models-client-test and definition-history-client-test.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {browserFixture,Element}=require('../zero-evaluation/dom-fixture'),{locales}=require('../foundly-i18n');
class View extends Element{
 constructor(tag){super(tag);Object.defineProperty(this,'dataset',{value:{}});}
 append(...nodes){super.append(...nodes);if(this.tag==='select'&&nodes.length&&this.children.length===nodes.length)this.value=nodes[0].value;}
 replaceChildren(...nodes){for(const child of this.children)for(const node of child.all())node.isConnected=false;super.replaceChildren(...nodes);}
}
function base(){const f=browserFixture('en-GB');f.context.document.createElement=tag=>new View(tag);let next=0;f.context.crypto={randomUUID:()=> 'definition-key-'+(++next)};for(const file of ['analysis-definition-history-client.js','analysis-models-client.js'])vm.runInContext(fs.readFileSync(require.resolve('../'+file),'utf8'),f.context);const key=(box,name,tag)=>box.all().find(node=>node.getAttribute('data-i18n')===name&&(!tag||node.tag===tag));return {...f,i:f.context.FoundlyI18n,key,field:(box,name)=>key(box,name,'label').children[0]};}
function fixture(){
 const f=base(),calls=[],proposals=[];
 const record={id:'model_literal',title:'Modelnaam <literal>',revision:1234,model_definition:{event_names:['purchase_literal'],measure:{kind:'SUM_CENTS',field:'value_cents'},group_by:['source'],filters:{},from:'2026-01-01T00:00:00Z',to:'2026-02-01T00:00:00Z'}};
 const history={coverage:'NATIVE_RECORDED_REVISIONS',next_offset:null,items:[{id:'revision_literal',definition_revision:1234,snapshot:{title:'Definitienaam <literal>',model_definition:record.model_definition},observed_at:'2026-09-24T12:34:00Z',classification:'NATIVE_DEFINITION_REVISION'}]};
 const data={definition_reference:{title:record.title,revision:record.revision},observed_records:1234,groups_total:2,missing_values:1,excluded_invalid_records:0,period_complete:true,unit:'MINOR_CURRENCY_UNITS',query_fingerprint:'literal_fingerprint',next_offset:null,items:[{id:'group_literal',values:{source:'Onbekende groepwaarde <literal source>',campaign_id:null},currency:'EUR',value:-123456,observed_valid_value:-123456,records:1234},{id:'missing_literal',values:{},currency:'USD',value:null,observed_valid_value:0,records:1}]};
 let deny=false,lose=false,held=null;
 const request=async(route,options)=>{calls.push({route,options});if(deny)throw Object.assign(Error('RAW_PRIVATE_ERROR'),{status:403});if(options?.method==='POST'){if(route.endsWith('/drilldown'))return {total:1234,next_offset:null,items:[{projected_fields:{event_id:'Literal <script> source record'}}]};if(lose){lose=false;throw Error('Lost response after write')}return {record};}if(route.includes('/revisions?'))return history;if(route.includes('/query?')){if(held)await held;return data;}if(route.includes('?limit='))return {items:[record,{...record,id:'model_second',title:'Second literal model'}],next_offset:null};return {record};};
 const box=f.nodes.models=f.context.FoundlyAnalysisModels.create({document:f.context.document,request,onPropose:selection=>proposals.push(selection)});
 const key=(name,tag)=>f.key(box,'analysis.models.'+name,tag),field=name=>f.field(box,'analysis.models.'+name);
 return {...f,box,record,history,data,calls,proposals,key,field,deny:()=>deny=true,lose:()=>lose=true,hold(){let release;held=new Promise(resolve=>release=resolve);return release;},async select(id=record.id){field('saved').value=id;await field('saved').fire('change');await box.children[4].firstChild?.ready;}};
}
test('Analysis model form keeps canonical values, authored input, confirmation and exact retry in all locales',async()=>{
 const f=fixture();await f.box.setEnabled(true,true,true);await f.key('new','button').fire('click');const title=f.field('name'),events=f.field('event_names'),kind=f.field('measure'),measure=f.field('measure_field'),confirm=f.field('confirm'),form=f.key('save','button').parentNode;title.value='Literal <img> authored model';events.value='purchase_literal\nrefund_literal';kind.value='SUM_CENTS';await kind.fire('change');measure.value='value_cents';f.field('from').value='2026-01-01T00:00:00+02:00';f.field('to').value='2026-02-01T00:00:00+02:00';await form.fire('input');await form.fire('submit');const n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.box.children[1].textContent,f.i.t('analysis.models.confirm_required'));assert.equal(f.field('name'),title);assert.equal(title.value,'Literal <img> authored model');assert.equal(events.value,'purchase_literal\nrefund_literal');assert.equal(kind.value,'SUM_CENTS');assert.equal(measure.value,'value_cents');assert.equal(confirm.checked,undefined);assert.equal(f.key('save','button').textContent,f.i.t('analysis.models.save'));assert.equal(f.calls.length,n);assert.equal(f.i.missingKeys().length,0);}
 confirm.checked=true;f.lose();await form.fire('submit');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.box.children[1].textContent,f.i.t('common.request_failed'));assert.equal(confirm.checked,true);assert.equal(title.value,'Literal <img> authored model');}await form.fire('submit');const writes=f.calls.filter(c=>c.options?.method==='POST');assert.equal(writes.length,2);assert.deepEqual(writes[0],writes[1]);const payload=JSON.parse(writes[0].options.body);assert.deepEqual(payload.model_definition.measure,{kind:'SUM_CENTS',field:'value_cents'});assert.equal(payload.title,'Literal <img> authored model');assert.equal(payload.model_definition.from,'2026-01-01T00:00:00+02:00');assert.ok(!f.calls.some(c=>c.route.includes('/query?')),'Saving does not calculate a model');
});
test('model results, uncertainty, units and source drilldown localize in place without changing source values or triggering requests',async()=>{
 const f=fixture();await f.box.setEnabled(true,true,true);await f.select();await f.key('calculate','button').fire('click');const card=f.box.children[3].children.find(n=>n.tag==='article');await card.all().find(n=>n.getAttribute('data-i18n')==='analysis.models.sources').fire('click');const source=card.all().find(n=>n.tag==='pre'),before=JSON.stringify(f.data),n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,n);assert.equal(JSON.stringify(f.data),before);assert.equal(source.textContent,JSON.stringify({event_id:'Literal <script> source record'},null,2));assert.equal(f.key('result','p').textContent,f.i.t('analysis.models.result',{currency:'EUR ',value:f.i.number(-123456),unit:f.i.t('analysis.models.unit.minor_currency_units')}));assert.ok(f.key('group_title','h4').textContent.includes('Onbekende groepwaarde <literal source>'));assert.ok(f.key('group_title','h4').textContent.includes(f.i.t('analysis.models.unknown_group')));assert.ok(f.box.children[3].textContent.includes(f.i.t('analysis.models.partial',{value:f.i.number(0)})));assert.ok(f.key('source_total').textContent.includes(f.i.number(1234)));assert.equal(f.i.missingKeys().length,0);}
 await f.key('propose','button').fire('click');assert.deepEqual(JSON.parse(JSON.stringify(f.proposals)),[{model_id:'model_literal',model_revision:1234,query_fingerprint:'literal_fingerprint',group_id:'group_literal'}]);assert.equal(f.calls.length,n);
});
test('denied refresh clears model output and snapshots; a late query cannot restore them',async()=>{
 const f=fixture();await f.box.setEnabled(true,true,true);await f.select();await f.key('calculate','button').fire('click');assert.ok(f.box.textContent.includes('literal source'));const release=f.hold(),pending=f.key('calculate','button').fire('click');await Promise.resolve();f.deny();await f.box.refresh();release();await pending;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.box.children[1].textContent,f.i.t('common.access_denied'));for(const index of [0,2,3,4])assert.equal(f.box.children[index].children.length,0);assert.ok(!f.box.textContent.includes('literal source'));assert.ok(!f.box.textContent.includes('RAW_PRIVATE_ERROR'));}
});
test('changing model selection away and back invalidates an already pending calculation',async()=>{
 const f=fixture();await f.box.setEnabled(true,true,true);await f.select();const release=f.hold(),pending=f.key('calculate','button').fire('click');await Promise.resolve();await f.select('model_second');await f.select();release();await pending;assert.equal(f.box.children[3].children.length,0,'A previous calculation must not reappear after navigating to another model');
});
test('unknown or malformed observations stay distinct from observed zero in every model locale',async()=>{
 const f=fixture();Object.assign(f.data,{observed_records:null,groups_total:0,missing_values:NaN,excluded_invalid_records:-1,period_complete:'true'});Object.assign(f.data.items[0],{value:false,records:undefined});await f.box.setEnabled(true,true,true);await f.select();await f.key('calculate','button').fire('click');
 for(const locale of locales){f.i.setLocale(locale);const unknown=f.i.t('common.unknown');assert.equal(f.key('observations').textContent,f.i.t('analysis.models.observations',{records:unknown,groups:f.i.number(0),missing:unknown,invalid:unknown}));assert.ok(f.key('result').textContent.includes(unknown));assert.equal(f.key('records').textContent,f.i.t('analysis.models.records',{value:unknown}));assert.equal(f.key('period_unknown').textContent,f.i.t('analysis.models.period_unknown'));assert.equal(f.i.missingKeys().length,0);}
});
test('definition revision editor and explicit restore preserve snapshot, reason and native idempotent requests in all locales',async()=>{
 const f=base(),calls=[],record={id:'cohort_literal',title:'Definitienaam <literal current>',revision:1234,cohort_definition:{from:'2026-01-01T00:00:00Z',to:'2026-02-01T00:00:00Z',acquisition_event:'join_literal',return_event:'return_literal',identity_field:'customer_id',interval_days:7,periods:3}},snapshot=JSON.parse(JSON.stringify(record));let lose=false;
 const request=async(route,options)=>{calls.push({route,options});if(options){if(lose){lose=false;throw Error('Lost response after write')}return {record};}return route.includes('/revisions?')?{coverage:'FROM_FIRST_RETAINED_BASELINE',next_offset:null,items:[{id:'revision_literal',definition_revision:1234,snapshot,observed_at:'2026-09-24T12:34:00Z',classification:'RETAINED_BASELINE_OBSERVED_AT_UPGRADE'}]}:{record};};
 const box=f.nodes.history=f.context.FoundlyAnalysisDefinitionHistory.create({document:f.context.document,request,id:record.id,canWrite:()=>true}),key=(name,tag)=>f.key(box,'analysis.history.'+name,tag),field=name=>f.field(box,'analysis.history.'+name);await box.ready;await key('prepare','button').fire('click');field('name').value='Literal <img> revised title';field('periods').value='5';field('reason').value='Literal explicit reason';field('confirm').checked=true;const name=field('name'),form=key('save','button').parentNode;await form.fire('input');const n=calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(field('name'),name);assert.equal(name.value,'Literal <img> revised title');assert.equal(field('periods').value,'5');assert.equal(field('confirm').checked,true);assert.equal(field('identity').value,'customer_id');assert.equal(calls.length,n);assert.ok(key('current').textContent.includes(f.i.number(1234)));assert.ok(key('observed').textContent.includes(f.i.date('2026-09-24T12:34:00Z',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'})));assert.ok(key('observed').textContent.includes('(UTC)'));assert.equal(box.all().find(n=>n.tag==='pre').textContent,JSON.stringify(snapshot,null,2));assert.equal(f.i.missingKeys().length,0);}
 lose=true;await form.fire('submit');f.i.setLocale('de-DE');await form.fire('submit');assert.deepEqual(calls.filter(c=>c.options)[0],calls.filter(c=>c.options)[1]);assert.equal(JSON.parse(calls.find(c=>c.options).options.body).definition.cohort_definition.periods,5);
 await key('restore','button').fire('click');field('reason').value='Restore literal reason';field('confirm').checked=true;const restore=key('save','button').parentNode;for(const locale of locales){f.i.setLocale(locale);assert.equal(field('reason').value,'Restore literal reason');assert.equal(field('confirm').checked,true);assert.equal(restore.all().find(n=>n.tag==='pre').textContent,JSON.stringify(snapshot,null,2));}await restore.fire('submit');const write=calls.filter(c=>c.options).at(-1);assert.equal(write.route,'/api/analysis/cohort_definitions/cohort_literal/revisions/revision_literal/restore');assert.deepEqual(JSON.parse(write.options.body),{expected_revision:1234,confirm:true,reason:'Restore literal reason'});
});
