'use strict';
// Controller evidence only. No rendered browser, native speaker or provider claim.
const test=require('node:test'),assert=require('node:assert/strict');
const {locales}=require('../foundly-i18n'),{fixture}=require('../zero-evaluation/analysis-page-fixture');
test('a denied Analysis page refresh removes all previously visible source records and observations',async()=>{
 const f=fixture();await f.context.load();assert.ok(f.nodes.analysisEvents.textContent.includes('literal-private-event'));assert.ok(f.nodes.analysisHistory.textContent.includes('literal-private-event'));f.deny();await f.context.load();
 for(const id of ['analysisEvents','analysisHistory','analysisKpis','analysisFunnel','analysisSources','analysisAutomationContent'])assert.equal(f.nodes[id].textContent,'',id+' must not retain denied source observations');assert.ok(f.streams.every(stream=>stream.closed));
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.analysisNotice.textContent,f.i.t('analysis.page.load_failed',{reason:f.i.t('common.access_denied')}));assert.ok(!Object.values(f.nodes).some(node=>node.textContent.includes('literal-private-event')));assert.equal(f.i.missingKeys().length,0);}
});
test('Analysis page locale changes preserve source text, active filters, event identities and native counts without reads or stream reconnects',async()=>{
 const f=fixture();await f.context.load();f.nodes.analysisCampaign.value='Literal <img> campaign';f.nodes.analysisFrom.value='2026-01-01';f.nodes.analysisTo.value='2026-02-01';f.nodes.analysisZeroInput.value='Literal pending question';const counts={calls:f.calls.length,streams:f.streams.length},before=JSON.stringify(f.dashboard),event=f.nodes.analysisEvents.children[0],meter=f.nodes.analysisFunnel.children[0].children[1];
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,counts.calls);assert.equal(f.streams.length,counts.streams);assert.equal(JSON.stringify(f.dashboard),before);assert.equal(f.nodes.analysisCampaign.value,'Literal <img> campaign');assert.equal(f.nodes.analysisZeroInput.value,'Literal pending question');assert.equal(f.nodes.analysisEvents.children[0],event);assert.equal(event.children[0].textContent,'Literal event <script>');assert.equal(event.children[1].getAttribute('datetime'),'2026-09-24T12:34:00Z');assert.ok(event.children[1].textContent.endsWith(' UTC'));assert.equal(meter.value,0);assert.equal(meter.max,1234);assert.equal(meter.textContent,f.i.number(0));assert.equal(f.nodes.analysisFunnel.children[1].children[0].textContent,'Literal custom stage');assert.equal(f.key('minor_units').textContent,f.i.t('analysis.page.minor_units',{value:f.i.number(123456)}));assert.ok(!f.key('minor_units').textContent.includes('€'));assert.equal(f.key('kpi.conversion_rate').textContent,f.i.t('analysis.page.kpi.conversion_rate'));assert.equal(f.i.missingKeys().length,0);}
 const q=f.context.query();assert.equal(q.get('campaign_id'),'Literal <img> campaign');assert.equal(q.get('from'),'2026-01-01T00:00:00.000Z');assert.equal(q.get('to'),'2026-02-01T23:59:59.999Z');
});
test('Analysis rejects truthy verification and malformed metrics, preserving observed zero and unknown observations',async()=>{
 const f=fixture();f.dashboard.kpis.conversion_rate.available='true';f.dashboard.kpis.pipeline_value.value=false;f.dashboard.realtime.events=null;f.dashboard.funnel.stages[0].count=null;f.dashboard.realtime.freshness.freshness_seconds=false;delete f.automation.workflow_count;f.automation.run_count=0;f.platform.persistence.durable='true';f.platform.providers.google.connected='true';f.connectors.items[0].probe_ok='true';await f.context.load();
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.analysisKpis.children[0].children[1].textContent,f.i.t('common.no_data'));assert.equal(f.nodes.analysisKpis.children[4].children[1].textContent,f.i.t('common.no_data'));assert.equal(f.nodes.analysisFunnel.children[0].children[1].tag,'span');assert.equal(f.nodes.analysisFunnel.children[0].children.at(-1).textContent,f.i.t('common.unknown'));assert.equal(f.nodes.analysisAutomationContent.children[0].children[1].textContent,f.i.t('common.unknown'));assert.equal(f.nodes.analysisAutomationContent.children[1].children[1].textContent,f.i.number(0));assert.ok(f.nodes.analysisNotice.textContent.includes(f.i.t('analysis.page.durability_unverified')));assert.ok(!f.nodes.analysisSources.all().some(n=>n.className==='source-state connected'));assert.equal(f.i.missingKeys().length,0);}
});
test('optional Analysis source failures clear only their observations and retain other current authorized results',async()=>{
 const f=fixture();await f.context.load();f.errors.set('/api/automation/status',503);await f.context.load();const n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.analysisNotice.textContent,f.i.t('analysis.page.partial'));assert.equal(f.nodes.analysisAutomationContent.textContent,f.i.t('analysis.page.component_error',{reason:f.i.t('common.request_failed')}));assert.ok(f.nodes.analysisEvents.textContent.includes('literal-private-event'));assert.ok(!f.nodes.analysisAutomationContent.textContent.includes('Literal adapter'));assert.ok(!f.nodes.analysisNotice.textContent.includes('RAW_PRIVATE_ERROR'));assert.equal(f.calls.length,n);assert.equal(f.i.missingKeys().length,0);}
});
test('a late previous page read and closed event stream cannot restore denied data or schedule another refresh',async()=>{
 const f=fixture();await f.context.load();const stream=f.streams.at(-1),release=f.hold('/api/analysis/dashboard'),pending=f.context.load();await release.started;f.deny();await f.context.load();release();await pending;stream.handlers['ready']();stream.handlers['platform.event']();assert.equal(f.nodes.analysisEvents.textContent,'');assert.equal(f.scheduled,undefined);assert.equal(f.nodes.analysisConnection.textContent,f.i.t('analysis.page.error_status'));
});
test('ZERO pending feedback localizes without replaying requests; answers and current draft input stay literal',async()=>{
 const f=fixture();await f.context.load();const release=f.hold('/api/zero/turn');f.nodes.analysisZeroInput.value='Exact literal question';const pending=f.context.askZero({preventDefault(){}});f.nodes.analysisZeroInput.value='Next literal question';const n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.analysisZeroOutput.textContent,f.i.t('analysis.page.zero_pending'));assert.equal(f.nodes.analysisZeroInput.value,'Next literal question');assert.equal(f.calls.length,n);}
 await f.context.askZero({preventDefault(){}});assert.equal(f.calls.length,n);release();await pending;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.analysisZeroOutput.textContent,'Literal <img> ZERO answer');}const body=JSON.parse(f.calls.find(c=>c.route==='/api/zero/turn').options.body);assert.equal(body.message,'Exact literal question');assert.deepEqual(body.client_context.cohort_definition,{id:'cohort_literal',revision:3});
});
test('late ZERO answers and export downloads cannot return after a denied page refresh',async()=>{
 for(const route of ['/api/zero/turn','/api/platform/exports']){const f=fixture();await f.context.load();const release=f.hold(route);f.nodes.analysisZeroInput.value='Question before denial';const pending=route.endsWith('/turn')?f.context.askZero({preventDefault(){}}):f.context.exportEvents();const n=f.calls.length;if(route.endsWith('/exports'))await f.context.exportEvents();assert.equal(f.calls.length,n);f.deny();await f.context.load();release();await pending;assert.equal(f.nodes.analysisZeroOutput.textContent,'');assert.equal(f.downloads.length,0);assert.equal(f.nodes.exportEvents.disabled,true);assert.equal(f.nodes.analysisNotice.textContent,f.i.t('analysis.page.load_failed',{reason:f.i.t('common.access_denied')}));}
});
test('event export preserves the native request and CSV bytes while result counts follow each locale',async()=>{
 const f=fixture();await f.context.load();await f.context.exportEvents();assert.deepEqual(Array.from(f.downloads[0].parts),['Literal CSV bytes']);const call=f.calls.find(c=>c.route==='/api/platform/exports');assert.equal(call.options.method,'POST');assert.deepEqual(JSON.parse(call.options.body),{scope:'events',format:'CSV'});const n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.analysisNotice.textContent,f.i.t('analysis.page.exported',{value:f.i.number(1234)}));assert.equal(f.calls.length,n);assert.equal(f.i.missingKeys().length,0);}
});
test('a current denied dashboard component clears previous ZERO content and disables event-dependent controls without hiding authorized provider status',async()=>{
 const f=fixture();await f.context.load();f.nodes.analysisZeroInput.value='Question';await f.context.askZero({preventDefault(){}});assert.ok(f.nodes.analysisZeroOutput.textContent.includes('Literal'));const route=f.calls.find(c=>c.route.startsWith('/api/analysis/dashboard')).route;f.errors.set(route,403);await f.context.load();assert.equal(f.nodes.analysisZeroOutput.textContent,'');assert.equal(f.nodes.exportEvents.disabled,true);assert.ok(!f.nodes.analysisEvents.textContent.includes('literal-private-event'));assert.ok(f.nodes.analysisSources.textContent.includes('Google'));assert.ok(f.streams.every(stream=>stream.closed));assert.equal(f.views.at(-1)[0],false);
 const n=f.calls.length;await f.context.exportEvents();assert.equal(f.calls.length,n);for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.analysisNotice.textContent,f.i.t('analysis.page.partial'));assert.equal(f.i.missingKeys().length,0);}
});
test('missing source collections do not appear as observed empty history, events or funnel data',async()=>{
 const f=fixture();delete f.dashboard.historical.rollups;delete f.dashboard.realtime.latest;delete f.dashboard.funnel.stages;await f.context.load();
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.rollupCount.textContent,f.i.t('analysis.page.buckets',{value:f.i.t('common.unknown')}));assert.equal(f.nodes.analysisHistoryEmpty.textContent,f.i.t('analysis.page.source_unavailable'));assert.equal(f.nodes.analysisEvents.textContent,f.i.t('analysis.page.source_unavailable'));assert.equal(f.nodes.analysisFunnel.textContent,f.i.t('analysis.page.source_unavailable'));}
});
