'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {locales}=require('../foundly-i18n'),{fixture:baseFixture,ViewElement,extract}=require('../zero-evaluation/zero-presentation-fixture');
function fixture(locale='en-GB'){
  const f=baseFixture(locale),effects=[],timers=[];
  const inputs=['preferredAddress','microphoneEnabled','wakeEnabled','clapEnabled','voiceEnabled','musicEnabled','sfxEnabled','clapSensitivity','masterVolume','voiceVolume','ambienceVolume','sfxVolume','audioMuted'],selects=['zeroLanguage','zeroVoiceGender','zeroVoiceMode','visualQualitySelect'];
  f.nodes.settingsPanel=new ViewElement();f.nodes.saveSettings=new ViewElement('button');f.nodes.toast=new ViewElement();
  for(const id of inputs.concat(selects)){f.nodes[id]=new ViewElement(selects.includes(id)?'select':'input');f.nodes.settingsPanel.append(f.nodes[id]);}
  f.nodes.settingsPanel.append(f.nodes.saveSettings);
  for(const id of ['audioContextStatus','audioOutputStatus','musicStatus','duckingStatus','voiceOutputStatus','micPermissionStatus','masterValue','voiceValue','musicValue','sfxValue','micPrivacy','voiceTransport'])f.nodes[id]=new ViewElement('b');
  Object.assign(f.zero.preferences,{preferred_address:'Big Boss',voice_gender:'MALE',microphone_enabled:true,wake_enabled:true,clap_enabled:true,voice_enabled:true,music_enabled:true,sfx_enabled:true,clap_sensitivity:.62,master_volume:.72,voice_volume:.92,ambience_volume:.28,sfx_volume:.35,muted:false,visual_quality:'AUTO'});
  f.zero.audioScene.setSettings=value=>effects.push({type:'settings',value});f.zero.audioScene.setZeroSpeaking=value=>effects.push({type:'speaking',value});f.context.neuralRuntime.setAutoQuality=()=>effects.push({type:'auto_quality'});f.context.neuralRuntime.setQuality=value=>effects.push({type:'quality',value});
  for(const name of ['stopWakeListener','startWakeListener','startClapDetector','stopClapDetector','initWakeListener','closeRealtime','realtimeSend'])f.context[name]=(...args)=>effects.push({type:name,args});
  f.context.connectRealtime=async()=>effects.push({type:'connectRealtime'});f.context.speechSynthesis={cancel:()=>effects.push({type:'cancel_speech'})};f.context.clearTimeout=()=>{};f.context.setTimeout=(callback,ms)=>{timers.push({callback,ms});return timers.length;};
  vm.runInContext(['audioSettings','audioPercent','renderAudioDiagnostics','refreshMicrophoneDiagnostic','renderPreferenceValues','renderPreferences','preferencePayload','applyPreferences','savePreferences','microphoneToggle','applyLiveControl','ensureStandbyMic','releaseStandbyMic','toast'].map(extract).join('\n'),f.context);
  f.context.renderPreferences();f.i.bind(f.nodes.saveSettings,'static.ebe1c42b');return {...f,effects,timers};
}
const snapshot={audio_context_state:'running',output_unlocked:true,music_enabled:true,music_playing:true,music_gain:.284,voice_enabled:true,voice_active:true,ducking_active:true};
test('observed audio diagnostics and percentages retranslate without changing native controls, querying devices or applying preferences',()=>{
  const f=fixture(),original=JSON.stringify(snapshot),before=JSON.stringify(f.context.preferencePayload());f.context.renderAudioDiagnostics(snapshot);const music=f.nodes.musicStatus.firstChild;
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.audioContextStatus.textContent,f.i.t('audio.running'));assert.equal(f.nodes.audioOutputStatus.textContent,f.i.t('audio.unlocked'));assert.equal(f.nodes.musicStatus.textContent,f.i.t('audio.playing',{level:new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:0}).format(.284)}));assert.equal(f.nodes.musicStatus.firstChild,music);assert.equal(f.nodes.voiceOutputStatus.textContent,f.i.t('audio.speaking'));assert.equal(f.nodes.duckingStatus.textContent,f.i.t('audio.active'));assert.equal(f.nodes.masterValue.textContent,new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:0}).format(.72));assert.equal(JSON.stringify(f.context.preferencePayload()),before);assert.equal(f.zero.preferences.language,'da-DK');assert.equal(f.effects.length,0);assert.equal(f.requests.length,0);assert.equal(f.i.missingKeys().length,0);}
  assert.equal(JSON.stringify(snapshot),original);
  for(const state of ['uninitialized','running','suspended','closed','interrupted']){f.context.renderAudioDiagnostics({...snapshot,audio_context_state:state});for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.audioContextStatus.textContent,f.i.t('audio.'+state));}}
  f.context.renderAudioDiagnostics({...snapshot,audio_context_state:'constructor',output_unlocked:false,music_enabled:true,music_playing:false,voice_active:false,ducking_active:false});f.i.setLocale('de-DE');assert.equal(f.nodes.audioContextStatus.textContent,'constructor');assert.equal(f.nodes.musicStatus.textContent,f.i.t('audio.ready'));assert.equal(f.nodes.audioOutputStatus.textContent,f.i.t('audio.blocked'));assert.equal(f.nodes.voiceOutputStatus.textContent,f.i.t('audio.ready'));assert.equal(f.nodes.duckingStatus.textContent,f.i.t('audio.inactive'));
});
test('unknown audio readings are never shown as zero, disabled or blocked; observed zero and disabled states remain distinct',()=>{
  const f=fixture();f.context.renderAudioDiagnostics({});f.context.renderPreferenceValues({master_volume:0,voice_volume:null,ambience_volume:'0.28',sfx_volume:Infinity});
  for(const locale of locales){f.i.setLocale(locale);for(const id of ['audioContextStatus','audioOutputStatus','musicStatus','duckingStatus','voiceOutputStatus','voiceValue','musicValue','sfxValue'])assert.equal(f.nodes[id].textContent,f.i.t('common.unknown'),id);assert.equal(f.nodes.masterValue.textContent,new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:0}).format(0));}
  f.context.renderAudioDiagnostics({...snapshot,music_gain:null});assert.equal(f.nodes.musicStatus.textContent,f.i.t('audio.playing',{level:f.i.t('common.unknown')}));
  f.context.renderAudioDiagnostics({...snapshot,music_gain:0});assert.equal(f.nodes.musicStatus.textContent,f.i.t('audio.playing',{level:new Intl.NumberFormat(f.i.locale,{style:'percent',maximumFractionDigits:0}).format(0)}));
  f.context.renderAudioDiagnostics({...snapshot,music_enabled:false,music_playing:false,voice_enabled:false});f.i.setLocale('fr-FR');assert.equal(f.nodes.musicStatus.textContent,f.i.t('audio.off'));assert.equal(f.nodes.voiceOutputStatus.textContent,f.i.t('audio.off'));
});
test('microphone permission observations reject late reads and follow revocation without a new query, mic request or locale side effect',async()=>{
  const f=fixture(),pending=[];let queries=0;f.context.navigator.permissions={query:async options=>{assert.deepEqual(JSON.parse(JSON.stringify(options)),{name:'microphone'});queries++;return new Promise(resolve=>pending.push(resolve));}};
  const first=f.context.refreshMicrophoneDiagnostic(),second=f.context.refreshMicrophoneDiagnostic(),old=new ViewElement(),permission=new ViewElement();old.state='granted';permission.state='denied';pending[1](permission);await second;pending[0](old);await first;
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.micPermissionStatus.textContent,f.i.t('audio.denied'));assert.equal(queries,2);assert.equal(f.effects.length,0);assert.equal(old.handlers.change?.length||0,0);assert.equal(permission.handlers.change.length,1);}
  permission.state='granted';await permission.fire('change');assert.equal(f.nodes.micPermissionStatus.textContent,f.i.t('audio.granted'));permission.state='denied';await permission.fire('change');assert.equal(f.nodes.micPermissionStatus.textContent,f.i.t('audio.denied'));assert.equal(queries,2);
  const third=f.context.refreshMicrophoneDiagnostic();assert.equal(permission.handlers.change.length,0);const next=new ViewElement();next.state='prompt';pending[2](next);await third;assert.equal(f.nodes.micPermissionStatus.textContent,f.i.t('audio.permission_prompt'));
  const fourth=f.context.refreshMicrophoneDiagnostic(),replacement=f.nodes.micPermissionStatus=new ViewElement();replacement.textContent='New panel';pending[3](old);await fourth;assert.equal(replacement.textContent,'New panel');assert.equal(old.handlers.change?.length||0,0);
});
test('microphone acquisition and release retain native privacy behavior while owned labels stay live',async()=>{
  const f=fixture(),permission=new ViewElement();permission.state='granted';let queries=0,media=0,stops=0;const stream={active:true,getTracks:()=>[{stop(){stops++;stream.active=false;}}]};f.context.navigator.permissions={query:async()=>{queries++;return permission;}};f.context.navigator.mediaDevices={getUserMedia:async options=>{media++;assert.deepEqual(JSON.parse(JSON.stringify(options)),{audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});return stream;}};
  assert.equal(await f.context.ensureStandbyMic(),stream);assert.equal(await f.context.ensureStandbyMic(),stream);
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.micPrivacy.textContent,f.i.t('static.892ae331'));assert.equal(f.nodes.micPermissionStatus.textContent,f.i.t('audio.granted'));assert.equal(media,1);assert.equal(queries,1);assert.equal(stops,0);assert.equal(f.zero.ambientStream,stream);}
  f.context.releaseStandbyMic();await new Promise(setImmediate);assert.equal(stops,1);assert.equal(f.zero.ambientStream,null);f.i.setLocale('fr-FR');assert.equal(f.nodes.micPrivacy.textContent,f.i.t('static.cfa2497d'));assert.equal(f.nodes.micPermissionStatus.textContent,f.i.t('audio.granted'));assert.equal(media,1);
  f.context.navigator.permissions=null;await f.context.refreshMicrophoneDiagnostic();assert.equal(f.nodes.micPermissionStatus.textContent,f.i.t('common.unknown'));f.zero.ambientStream={active:true};await f.context.refreshMicrophoneDiagnostic();assert.equal(f.nodes.micPermissionStatus.textContent,f.i.t('audio.active'));
});
test('live audio controls retain unsaved voice/profile choices until the native save and reconnect exactly once',async()=>{
  const f=fixture();f.nodes.zeroLanguage.value='en-GB';f.nodes.zeroVoiceGender.value='FEMALE';f.nodes.zeroVoiceMode.value='BRIEFING';f.nodes.preferredAddress.value='Literal unsaved name';f.nodes.masterVolume.value='.37';f.context.applyLiveControl();
  assert.equal(f.zero.preferences.language,'da-DK');assert.equal(f.zero.preferences.voice_gender,'MALE');assert.equal(f.zero.preferences.voice_mode,'CONVERSATION');assert.equal(f.zero.preferences.preferred_address,'Big Boss');assert.equal(f.zero.preferences.master_volume,.37);
  f.zero.enabled=false;f.nodes.microphoneEnabled.checked=false;await f.context.microphoneToggle();assert.equal(f.zero.preferences.microphone_enabled,false);assert.equal(f.zero.preferences.language,'da-DK');assert.equal(f.nodes.zeroLanguage.value,'en-GB');assert.equal(f.zero.preferences.preferred_address,'Big Boss');f.nodes.microphoneEnabled.checked=true;await f.context.microphoneToggle();f.zero.enabled=true;f.zero.conversationActive=true;
  f.nodes.clapSensitivity.disabled=true;const desired=JSON.parse(JSON.stringify(f.context.preferencePayload())),fields=[...f.nodes.settingsPanel.querySelectorAll('input,select')];let release;f.context.fetch=async(path,options)=>{f.requests.push({path,options});return new Promise(resolve=>release=()=>resolve({ok:true,json:async()=>({preferences:{...f.zero.preferences,...desired}})}));};
  const pending=f.context.savePreferences();await f.context.savePreferences();assert.equal(f.requests.length,1);assert.equal(f.nodes.saveSettings.disabled,true);assert.ok(fields.every(node=>node.disabled));
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.saveSettings.textContent,f.i.t('audio.saving'));assert.equal(f.nodes.zeroLanguage.value,'en-GB');assert.equal(f.zero.preferences.language,'da-DK');assert.equal(f.nodes.preferredAddress.value,'Literal unsaved name');assert.equal(f.requests.length,1);}
  release();await pending;const sent=f.requests[0];assert.equal(sent.path,'/api/zero/preferences');assert.equal(sent.options.method,'PUT');assert.deepEqual(JSON.parse(sent.options.body),desired);assert.equal(Object.hasOwn(desired,'ui_locale'),false);assert.equal(f.zero.preferences.language,'en-GB');assert.equal(f.zero.preferences.voice_gender,'FEMALE');assert.equal(f.zero.preferences.voice_mode,'BRIEFING');assert.equal(f.i.locale,'sv-SE');assert.equal(f.nodes.saveSettings.disabled,false);assert.equal(f.nodes.clapSensitivity.disabled,true);assert.equal(f.nodes.masterVolume.disabled,false);assert.equal(f.nodes.settingsPanel.classList.contains('hidden'),true);assert.equal(f.effects.filter(e=>e.type==='closeRealtime').length,1);assert.equal(f.effects.filter(e=>e.type==='connectRealtime').length,1);assert.equal(f.effects.filter(e=>e.type==='cancel_speech').length,1);assert.equal(f.timers.length,1);
  const count=f.effects.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.toast.textContent,f.i.t('static.403a1b21'));assert.equal(f.nodes.saveSettings.textContent,f.i.t('static.ebe1c42b'));assert.equal(f.effects.length,count);assert.equal(f.requests.length,1);assert.equal(f.timers.length,1);}
});
test('denied or unconfirmed preference writes retain drafts, localize errors and never reconnect, retry or expose raw backend copy',async()=>{
  for(const failure of [403,429,500,'lost','invalid']){
    const f=fixture();f.nodes.preferredAddress.value='Literal draft';f.nodes.zeroLanguage.value='es-ES';f.context.fetch=async(path,options)=>{f.requests.push({path,options});if(failure==='lost')throw Error('RAW_PRIVATE_ERROR');return {ok:failure==='invalid',status:failure,json:async()=>({error:'RAW_PRIVATE_ERROR'})};};await f.context.savePreferences();
    for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.listenText.textContent,f.i.t(failure===403?'common.access_denied':failure===429?'common.rate_limited':'audio.save_unconfirmed'));assert.equal(f.nodes.preferredAddress.value,'Literal draft');assert.equal(f.nodes.zeroLanguage.value,'es-ES');assert.equal(f.zero.preferences.language,'da-DK');assert.equal(f.nodes.saveSettings.disabled,false);assert.equal(f.nodes.settingsPanel.classList.contains('hidden'),false);assert.equal(f.requests.length,1);assert.equal(f.effects.length,0);assert.equal(f.nodes.toast.textContent,'');assert.ok(!f.nodes.listenText.textContent.includes('RAW_PRIVATE_ERROR'));assert.equal(f.i.missingKeys().length,0);}
  }
});
test('a confirmed settings write and failed audio reconnect stay distinct without a second save or false success notice',async()=>{
  const f=fixture();f.zero.conversationActive=true;f.nodes.zeroLanguage.value='fr-FR';const desired=JSON.parse(JSON.stringify(f.context.preferencePayload()));f.context.fetch=async(path,options)=>{f.requests.push({path,options});return {ok:true,json:async()=>({preferences:{...f.zero.preferences,...desired}})};};let attempts=0;f.context.connectRealtime=async()=>{attempts++;throw Error('RAW_RECONNECT_ERROR');};await f.context.savePreferences();
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.listenText.textContent,f.i.t('audio.saved_activation_incomplete'));assert.equal(f.zero.preferences.language,'fr-FR');assert.equal(f.nodes.zeroLanguage.value,'fr-FR');assert.equal(f.nodes.settingsPanel.classList.contains('hidden'),false);assert.equal(f.nodes.toast.textContent,'');assert.equal(f.nodes.saveSettings.disabled,false);assert.equal(f.requests.length,1);assert.equal(attempts,1);}
});
test('the live transcription prefix follows interface locale while the captured utterance and native voice turn stay literal',()=>{
  const f=fixture(),{VoiceTurns}=require('../zero-voice-turns');f.zero.voiceTurns=new VoiceTurns();vm.runInContext(['realtimeFunctionCalls','handleRealtimeEvent'].map(extract).join('\n'),f.context);
  const literal='Gehoord: <img src=x> maak een taak — København';f.zero.voiceTurns.start('native-item');f.context.handleRealtimeEvent({type:'conversation.item.input_audio_transcription.completed',item_id:'native-item',transcript:literal});const stamp=f.zero.lastTranscript.at;
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.listenText.textContent,f.i.t('static.b319c7b5',{p0:literal}));assert.equal(f.zero.lastTranscript.text,literal);assert.equal(f.zero.lastTranscript.at,stamp);assert.equal(f.zero.preferences.language,'da-DK');assert.equal(f.requests.length,0);assert.equal(f.effects.length,0);assert.equal(f.events.length,0);assert.equal(f.nodes.listenText.children.length,0);}
});
