'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('../zero-evaluation/automotive-page-fixture');
const {locales}=require('../foundly-i18n');
const candidate=()=>({canonical_listing_id:'id',vehicle:{make:'BMW',model:'i4 <img>',build_year:2024,mileage_km:0,images:['source_ref']},commercial:{gross_price_eur:12345},identity:{provider:'Literal provider',provider_listing_id:'Literal ID',source_url:'https://provider.example.test/listing'},seller:{name:'Literal seller',city:'Literal city',country:'NL'},listing:{freshness:{classification:'CACHED'}},provenance:{provider_verified:true,transformation_version:'Literal version',raw_source_reference:'Literal reference'}});
const owned=(host,key)=>host.all().find(n=>n.getAttribute('data-i18n')==='automotive.detail.'+key);
test('Automotive detail does not display an unavailable numeric Buy Score',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();Object.assign(f.analysis,{candidate:{canonical_listing_id:'id',vehicle:{make:'BMW'},identity:{},commercial:{},seller:{}},buy_score:{available:false,score:94}});await f.context.showVehicle('id');assert.equal(f.nodes.detailScore.querySelector('strong').textContent,f.i.t('common.unknown'));
});
test('Automotive source evidence does not turn a string false into verified provider evidence',async()=>{
 const f=fixture();await f.context.loadStatus();const content=f.context.sourceContent({candidate:{provenance:{provider_verified:'false'}}});const value=typeof content==='string'?content:content.textContent;assert.ok(!value.includes('JA'));assert.ok(value.includes(f.i.t('common.unknown')));
});
test('all six Automotive detail tabs and header update in eight locales without source reads or mutations',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();Object.assign(f.analysis,{candidate:candidate(),observed_at:'2026-09-24T13:14:00Z',buy_score:{available:true,score:0,components:[{name:'Acquisition Advantage',score:0,confidence:'HIGH',weight:25},{name:'Literal <img> custom component',score:80,confidence:'LOW',weight:10}]},comparables:{comparable_count:1234,confidence:'HIGH',price_distribution_eur:{median:30000,p25:20000,p75:40000},listings:[{provider:'Literal listing provider',price_eur:12345,mileage_km:0,build_year:2024,similarity_score:100,freshness:{classification:'CACHED'},source_url:'https://source.example.test/listing'}]},market_signals:{listing_scarcity:{value:'LOW'},price_position:{value:-12.34},actual_sales_demand:{type:'UNKNOWN'}},economics:{status:'needs_input',all_in_acquisition_eur:0,expected_retail_range:{expected_eur:null,type:'UNKNOWN'},expected_gross_margin_range:{expected_eur:-1234,low_eur:-2500,high_eur:0},bpm:{estimated_payable_bpm_eur:0,rule_version:'Literal BPM rule'},breakdown:[{component:'transport_eur',value_eur:0,type:'FACT'},{component:'Literal <img> component',value_eur:null,type:'UNKNOWN'}],missing_fields:['co2_g_km','transport_eur','Literal missing field']},risks:[{code:'VIN_UNKNOWN',severity:'MEDIUM'},{code:'Literal <img> risk',severity:'HIGH'}]});await f.context.showVehicle('id');const n=f.calls.length,source=JSON.stringify(f.analysis);
 for(const tab of ['why','market','economics','comparables','risks','source']){await f.tabs[tab].fire('click');assert.equal(f.tabs[tab].getAttribute('aria-selected'),'true');const root=f.nodes.detailContent.children[0];for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.detailContent.children[0],root);assert.equal(f.calls.length,n);assert.equal(JSON.stringify(f.analysis),source);assert.equal(f.nodes.detailTitle.textContent,'BMW i4 <img>');assert.equal(f.nodes.detailTitle.children.length,0);assert.equal(f.nodes.detailScore.querySelector('strong').textContent,f.i.number(0));assert.equal(f.nodes.sourceLink.href,'https://provider.example.test/listing');assert.ok(f.nodes.detailSubtitle.textContent.includes(new Intl.NumberFormat(locale,{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(12345)));
   if(tab==='why'){assert.ok(root.textContent.includes(f.i.t('automotive.detail.component.acquisition_advantage')));assert.ok(root.textContent.includes('Literal <img> custom component'));}
   if(tab==='market'){assert.equal(owned(root,'price_position').parentNode.children[1].textContent,new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:2}).format(-0.1234));assert.ok(root.textContent.includes(f.i.t('automotive.detail.sales_warning',{type:f.i.t('automotive.status.state.unknown')})));}
   if(tab==='economics'){assert.equal(owned(root,'margin').parentNode.children[1].textContent,new Intl.NumberFormat(locale,{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(-1234));assert.ok(root.textContent.includes('Literal BPM rule'));assert.ok(root.textContent.includes(f.i.t('automotive.detail.field.co2')));assert.ok(root.textContent.includes('Literal missing field'));}
   if(tab==='comparables'){const link=root.all().find(n=>n.tag==='a');assert.equal(link.href,'https://source.example.test/listing');assert.equal(link.rel,'noopener noreferrer');assert.ok(root.textContent.includes('Literal listing provider'));}
   if(tab==='risks'){assert.ok(root.textContent.includes(f.i.t('automotive.detail.risk.vin_unknown')));assert.ok(root.textContent.includes('Literal <img> risk'));assert.equal(root.all().filter(n=>n.tag==='img').length,0);}
   if(tab==='source'){assert.ok(root.textContent.includes('Literal provider'));assert.ok(root.textContent.includes('Literal ID'));assert.ok(root.textContent.includes('Literal reference'));assert.equal(owned(root,'verified').parentNode.children[1].textContent,f.i.t('automotive.detail.yes'));assert.equal(owned(root,'observed').parentNode.children[1].textContent,f.i.t('automotive.detail.utc',{time:f.i.date(f.analysis.observed_at,{dateStyle:'short',timeStyle:'medium',timeZone:'UTC'})}));}
   assert.equal(f.i.missingKeys().length,0);
  }}
});
test('missing detail lists and nonnumeric values stay unknown while literal native zero and false keep their meaning',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();Object.assign(f.analysis,{candidate:candidate(),buy_score:{available:true,score:'90'},comparables:{comparable_count:null,price_distribution_eur:{median:false}},market_signals:{price_position:{value:'0'}},economics:{all_in_acquisition_eur:null}});await f.context.showVehicle('id');assert.equal(f.nodes.detailScore.querySelector('strong').textContent,f.i.t('common.unknown'));await f.tabs.market.fire('click');assert.equal(owned(f.nodes.detailContent,'nl_comparables').parentNode.children[1].textContent,f.i.t('common.unknown'));assert.equal(owned(f.nodes.detailContent,'median_price').parentNode.children[1].textContent,f.i.t('common.unknown'));assert.equal(owned(f.nodes.detailContent,'price_position').parentNode.children[1].textContent,f.i.t('common.unknown'));await f.tabs.risks.fire('click');assert.ok(owned(f.nodes.detailContent,'risks_unknown'));await f.tabs.comparables.fire('click');assert.ok(owned(f.nodes.detailContent,'comparables_unknown'));
 for(const value of [undefined,null,'false','true',false,true]){const view=f.context.sourceContent({candidate:{provenance:{provider_verified:value}}});f.nodes.detailContent.replaceChildren(view);for(const locale of locales){f.i.setLocale(locale);assert.equal(owned(view,'verified').parentNode.children[1].textContent,value===true?f.i.t('automotive.detail.yes'):value===false?f.i.t('automotive.detail.no'):f.i.t('common.unknown'));}}
});
test('unsafe source URLs and markup-like evidence are inert in actual detail renderers',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();for(const url of ['javascript:alert(1)','data:text/html,x','https://user:password@provider.example.test/listing']){const value=candidate();value.identity.source_url=url;value.identity.provider='<img src=x onerror=alert(1)>';Object.assign(f.analysis,{candidate:value,buy_score:{available:true,score:0,components:[]},comparables:{listings:[{provider:'<script>alert(1)</script>',source_url:url}]}});f.clearAnalyses();await f.context.showVehicle('id');assert.equal(f.nodes.sourceLink.hidden,true);assert.equal(f.nodes.sourceLink.getAttribute('href'),null);await f.tabs.source.fire('click');assert.ok(f.nodes.detailContent.textContent.includes('<img src=x onerror=alert(1)>'));assert.equal(f.nodes.detailContent.all().filter(n=>['a','img','script'].includes(n.tag)).length,0);await f.tabs.comparables.fire('click');assert.ok(f.nodes.detailContent.textContent.includes('<script>alert(1)</script>'));assert.equal(f.nodes.detailContent.all().filter(n=>['a','img','script'].includes(n.tag)).length,0);}
});
test('a newer detail selection wins over an older pending read and denied detail clears all source observations',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();const a={candidate:candidate(),buy_score:{available:false}},b={candidate:{...candidate(),vehicle:{make:'Literal B'}},buy_score:{available:false}};f.respond('/api/automotive/vehicles/a/analysis',{payload:{analysis:a}});f.respond('/api/automotive/vehicles/b/analysis',{payload:{analysis:b}});const release=f.hold('/api/automotive/vehicles/a/'),pending=f.context.showVehicle('a');await release.started;await f.context.showVehicle('b');release();await pending;assert.equal(f.nodes.detailTitle.textContent,'Literal B');f.deny();await f.context.showVehicle('not_cached');assert.equal(f.nodes.detailTitle.textContent,'');assert.equal(f.nodes.vehicleDetail.hidden,true);assert.equal(f.nodes.automotiveOverviewGrid.textContent,'');assert.equal(f.nodes.searchButton.disabled,true);assert.ok(!f.nodes.toastRegion.textContent.includes('RAW_PRIVATE_ERROR'));
});
