'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/automation-page-fixture'),{locales}=require('../foundly-i18n');
test('actual workflow catalogue headings and registered trigger/action readouts follow all eight locales while literal source text and native IDs remain unchanged',async()=>{
 for(const section of ['TRIGGERS','ACTIONS','DEPENDENCIES','WORKFLOWS']){const f=fixture();await f.render(section);const before=f.calls.length,card=f.find('article'),name=f.find('h3');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.find('article'),card);assert.equal(name.textContent,f.workflow.name);assert.ok(card.textContent.includes(f.i.t('workflow.list.version_state',{version:f.i.number(1234),state:f.i.t('workflow.list.active')})));if(['TRIGGERS','WORKFLOWS'].includes(section))assert.ok(card.textContent.includes(f.i.t('workflow.trigger.custom_event')));if(['ACTIONS','WORKFLOWS'].includes(section)){assert.ok(card.textContent.includes(f.i.t('workflow.action.create_task')));assert.ok(card.textContent.includes('Literal <script> action'));}assert.equal(f.i.missingKeys().length,0);}assert.equal(f.calls.length,before);assert.equal(f.content.querySelector('img'),null);assert.equal(f.content.querySelector('script'),null);}
});
test('run filters, count, step status and pagination localize in place without changing selectors, input or issuing requests',async()=>{
 const f=fixture();await f.render('RUNS',{q:'Literal <img> search',status:'ERROR'});const search=f.find('input'),status=f.find('select'),calls=f.calls.length;search.value='Current unsent literal query';for(const locale of locales){f.i.setLocale(locale);assert.equal(f.find('input'),search);assert.equal(f.find('select'),status);assert.equal(search.value,'Current unsent literal query');assert.equal(status.value,'ERROR');assert.ok(f.content.textContent.includes(f.i.t('workflow.list.run_count',{count:f.i.number(1234),from:f.i.number(1)})));assert.ok(f.content.textContent.includes(f.i.t('workflow.status.failed')));assert.ok(f.find('button',f.i.t('workflow.list.next')));assert.equal(f.i.missingKeys().length,0);}assert.equal(f.calls.length,calls);assert.ok(!f.content.textContent.includes('RAW_PRIVATE_STEP_DIAGNOSIS'));
});
test('late workflow success from a retired workspace cannot overwrite current content or dispatch follow-up reads',async()=>{
 const f=fixture();f.data.can_manage=true;const release=f.hold('/api/automation/workflows'),pending=f.render('WORKFLOWS');await release.started;f.retire();f.content.textContent='Current other workspace';release();await pending;assert.equal(f.content.textContent,'Current other workspace');assert.equal(f.calls.length,1);
});
test('a stale rejected list request cannot replace a newer same-section result or a different active section',async()=>{
 for(const next of ['TRIGGERS','ACTIONS']){const f=fixture(),release=f.hold('/api/automation/workflows',true),pending=f.render('TRIGGERS');await release.started;await f.render(next);const shown=f.content.textContent;release();await pending;assert.equal(f.content.textContent,shown);assert.ok(!f.content.textContent.includes('RAW_PRIVATE_LATE_FAILURE'));}
});
test('retired run-page loading cannot fetch composition or replace a detached view',async()=>{
 const f=fixture(),release=f.hold('/api/automation/runs'),pending=f.render('RUNS');await release.started;f.content.isConnected=false;f.content.textContent='Detached preserved view';release();await pending;assert.equal(f.content.textContent,'Detached preserved view');assert.equal(f.calls.length,1);
});
test('a late private-draft response cannot construct an editor or overwrite the current workspace',async()=>{
 const f=fixture();f.data.can_manage=true;const release=f.hold('/api/automation/drafts'),pending=f.render('WORKFLOWS');await release.started;f.retire();f.content.textContent='Current unrelated workspace';release();await pending;assert.equal(f.content.textContent,'Current unrelated workspace');assert.equal(f.calls.length,2);assert.equal(f.storage.size,0);
});
test('missing or malformed workflow and run evidence is not rendered as a trustworthy empty or zero result',async()=>{
 for(const [route,value,section]of [['/api/automation/workflows',{},'TRIGGERS'],['/api/automation/workflows',{workflows:null,workflow_count:0},'ACTIONS'],['/api/automation/runs',{items:[],total:null,offset:0},'RUNS'],['/api/automation/runs',{items:[],total:0,offset:-1},'RUNS']]){const f=fixture();f.responses.set(route,value);await f.render(section);assert.ok(f.content.textContent.includes(f.i.t('workflow.list.invalid')));assert.ok(!f.content.textContent.includes(f.i.t('workflow.list.empty')));assert.equal(f.calls.filter(c=>c.options.method&&c.options.method!=='GET').length,0);}
});
test('current access denial and genuine empty results have distinct owned feedback that follows the current locale',async()=>{
 const denied=fixture();denied.errors.set('/api/automation/workflows',403);await denied.render('TRIGGERS');const empty=fixture();empty.data.workflows=[];empty.data.workflow_count=0;await empty.render('TRIGGERS');for(const locale of locales){denied.i.setLocale(locale);empty.i.setLocale(locale);assert.ok(denied.nodes.workspaceNotice.textContent.includes(denied.i.t('common.access_denied')));assert.ok(!denied.content.textContent.includes('RAW_PRIVATE_HTTP_DIAGNOSIS'));assert.ok(empty.content.textContent.includes(empty.i.t('workflow.list.empty')));assert.equal(empty.calls.length,1);}
});
test('retired filter and pagination controls cannot initiate fresh reads or replace the active workspace',async()=>{
 const f=fixture();await f.render('RUNS');const form=f.find('form'),next=f.content.all().filter(n=>n.tag==='button').find(n=>n.textContent==='Volgende'||n.textContent===f.i.t('workflow.list.next')),before=f.calls.length;assert.ok(next);f.retire();await form.fire('submit');await next.fire('click');assert.equal(f.calls.length,before);
});
test('a stale access-denied response cannot retire a newer authorized workflow view',async()=>{
 const f=fixture();f.errors.set('/api/automation/workflows',403);const release=f.hold('/api/automation/workflows'),pending=f.render('TRIGGERS');await release.started;f.errors.clear();await f.render('ACTIONS');const shown=f.content.textContent,workspace=f.ui.state.workspace;release();await pending;assert.equal(f.content.textContent,shown);assert.equal(f.ui.state.workspace,workspace);assert.notEqual(f.nodes.workspaceNotice.className,'workspace-notice error');
});
test('empty pagination, missing activation and invalid wake time remain distinct from an empty catalogue, paused workflow or measured time',async()=>{
 const f=fixture();f.page.items=[];f.page.offset=1250;f.page.next_offset=null;await f.render('RUNS');assert.ok(f.content.textContent.includes(f.i.t('workflow.list.empty_page')));assert.ok(!f.content.textContent.includes(f.i.t('workflow.list.empty')));const g=fixture();delete g.workflow.effective_enabled;await g.render();assert.ok(g.content.textContent.includes(g.i.t('common.unknown')));assert.ok(!g.content.textContent.includes(g.i.t('workflow.list.paused')));const h=fixture();h.run.status='WAITING_TIME';h.run.next_wakeup_at=false;await h.render('RUNS');assert.ok(h.content.textContent.includes(h.i.t('workflow.list.wake',{time:h.i.t('common.unknown')})));h.run.next_wakeup_at='2026-09-25T10:20:00+02:00';await h.render('RUNS');const count=h.calls.length;for(const locale of locales){h.i.setLocale(locale);assert.ok(h.content.textContent.includes(h.i.t('workflow.list.wake',{time:h.i.date(h.run.next_wakeup_at,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'})})));}assert.equal(h.calls.length,count);
});
test('retired shared resume, recovery, approval, activation and manual controls cannot dispatch native operations',async()=>{
 for(const kind of ['resume','recovery','approval','activation','manual','zero']){const f=fixture();f.page.can_manage=f.data.can_manage=true;let button,form,section='RUNS';if(kind==='resume'){f.run.can_recover=true;f.run.status='WAITING_TIME';f.run.next_wakeup_at='2026-09-25T00:00:00Z';}if(kind==='recovery')f.run.can_recover=true;if(kind==='approval'){f.run.status='AWAITING_APPROVAL';section='APPROVALS';}if(['activation','manual','zero'].includes(kind))section='WORKFLOWS';await f.render(section);const labels={resume:'Hervatten zodra wachttijd verstreken is',recovery:'Controleer opgeslagen resultaat',approval:'Exacte run goedkeuren',activation:'Alleen deze versie activeren',manual:'Workflow uitvoeren',zero:'Uitvoering met ZERO voorbereiden'};button=kind==='recovery'?f.content.all().find(n=>n.getAttribute?.('data-result-action')==='prepare'):kind==='resume'?f.content.all().find(n=>n.getAttribute?.('data-resume-action')==='prepare'):kind==='activation'?f.content.all().find(n=>n.getAttribute?.('data-activation-action')==='activate'):kind==='approval'?f.content.all().find(n=>n.getAttribute?.('data-approval-action')==='prepare'):['zero','manual'].includes(kind)?f.content.all().find(n=>n.getAttribute?.('data-workflow-run-mode')===(kind==='zero'?'zero':'native'))?.all().find(n=>n.getAttribute?.('data-workflow-run-action')==='prepare'):f.find('button',labels[kind]);assert.ok(button,kind+' control');form=button.closest('form');const before=f.calls.length;f.retire();if(['activation'].includes(kind))await form.fire('submit',{submitter:button});else await button.fire('click');assert.equal(f.calls.length,before,kind+' retired request');}
});
test('a pending resume review cannot duplicate its request or refresh a newer view when the old reply arrives',async()=>{
 const f=fixture();f.page.can_manage=true;f.run.can_recover=true;f.run.status='WAITING_TIME';f.run.next_wakeup_at='2026-09-25T00:00:00Z';await f.render('RUNS');const button=f.content.all().find(n=>n.getAttribute?.('data-resume-action')==='prepare'),release=f.hold('/api/automation/runs/'+f.run.run_id+'/resume-preview'),pending=button.fire('click');await release.started;const count=f.calls.length;await button.fire('click');assert.equal(f.calls.length,count);await f.render('ACTIONS');const shown=f.content.textContent,after=f.calls.length;release();await pending;assert.equal(f.calls.length,after);assert.equal(f.content.textContent,shown);
});
test('a late ZERO run preview cannot alter a retired view, restore its controls or adopt conversation state',async()=>{
 const f=fixture();f.data.can_manage=true;await f.render('WORKFLOWS');const button=f.content.all().find(n=>n.getAttribute?.('data-workflow-run-mode')==='zero').all().find(n=>n.getAttribute?.('data-workflow-run-action')==='prepare'),box=button.closest('fieldset'),release=f.hold('/api/zero/turn'),pending=button.fire('click');await release.started;assert.equal(button.disabled,true);const before=box.textContent,conversation=f.ui.state.conversationId;f.retire();release();await pending;assert.equal(box.textContent,before);assert.equal(button.disabled,true);assert.equal(f.ui.state.conversationId,conversation);
});
