'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('../zero-evaluation/automotive-page-fixture'),{locales}=require('../foundly-i18n');
test('configured Automotive credentials without a successful search do not claim marketplace readiness',async()=>{
 const f=fixture();await f.context.loadStatus();assert.notEqual(f.nodes.railStatusLight.className,'status-light ok');assert.notEqual(f.nodes.railStatusText.textContent,'Market ready');
});
test('a denied Automotive status reload removes previously observed private dealer and inventory data',async()=>{
 const f=fixture();await f.context.loadStatus();assert.equal(f.nodes.partnerName.textContent,'Literal private dealer');f.deny();await f.context.loadStatus();assert.notEqual(f.nodes.partnerName.textContent,'Literal private dealer');assert.equal(f.nodes.automotiveOverviewGrid.textContent,'');
});
test('Automotive status, counts and UTC observations update in all locales without source requests or changing authored queries and provider identity',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();f.nodes.automotiveQuery.value='Literal authored BMW query';f.nodes.zeroQuery.value='Literal question';const n=f.calls.length,grid=f.nodes.automotiveOverviewGrid,card=f.nodes.providerGrid.children[0],original=JSON.stringify(f.overview);
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,n);assert.equal(f.nodes.automotiveOverviewGrid,grid);assert.equal(f.nodes.providerGrid.children[0],card);assert.equal(card.children[0].children[0].textContent,'Literal <img> provider');assert.equal(card.children[0].children[0].children.length,0);assert.equal(f.nodes.partnerName.textContent,'Literal private dealer');assert.equal(f.nodes.automotiveQuery.value,'Literal authored BMW query');assert.equal(f.nodes.zeroQuery.value,'Literal question');assert.equal(f.nodes.inventoryOperationState.textContent,f.i.t('automotive.status.inventory_records',{records:f.i.number(1234),risk:f.i.number(0)}));assert.equal(f.nodes.automotiveObserved.textContent,f.i.t('automotive.status.observed',{time:f.i.date(f.overview.observed_at,{dateStyle:'short',timeStyle:'medium',timeZone:'UTC'})}));assert.equal(f.nodes.railStatusText.textContent,f.i.t('automotive.status.configured_status'));assert.equal(JSON.stringify(f.overview),original);assert.equal(f.i.missingKeys().length,0);}
});
test('registry connection evidence, public references and observed native searches remain distinct from configuration and unknown records',async()=>{
 const f=fixture();Object.assign(f.overview.provider_health[0],{connection_state:'CONNECTED',probe_state:'PASS',sync_state:'PASS',records:1234});f.overview.provider_health.push({connector_id:'rdw',provider:'rdw',name:'RDW',connection_state:'CONNECTED',authentication_state:'AUTHENTICATED_PUBLIC',probe_state:'PASS',sync_state:'NOT_RUN',records:0});Object.assign(f.status.providers[1],{probe:'PASS',real_search:'PASS',last_attempt_at:'2026-09-24T12:34:00Z'});await f.context.loadStatus();
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.railStatusText.textContent,f.i.t('automotive.status.search_status'));assert.equal(f.nodes.automotiveOverviewGrid.children[0].children[1].textContent,f.i.t('automotive.status.coverage',{connected:f.i.number(2),total:f.i.number(2)}));assert.ok(f.nodes.providerGrid.textContent.includes(f.i.t('automotive.status.verified_records',{value:f.i.number(1234)})));assert.ok(f.nodes.providerGrid.textContent.includes(f.i.t('automotive.status.verified_records',{value:f.i.number(0)})));assert.equal(f.i.missingKeys().length,0);}
 f.overview.provider_health[0].probe_state='FAIL';await f.context.loadStatus();assert.equal(f.nodes.automotiveOverviewGrid.children[0].children[1].textContent,f.i.t('automotive.status.coverage',{connected:f.i.number(1),total:f.i.number(2)}));
});
test('missing collections, null scores, truthy booleans and duplicate provider observations do not invent zeros or connection proof',async()=>{
 const f=fixture();delete f.overview.recent_searches;f.overview.top_buy_scores=[{score:null},{score:false},{score:'80'}];f.overview.inventory_risk.available='true';f.overview.provider_health.push({...f.overview.provider_health[0],connection_state:'CONNECTED',probe_state:'PASS',sync_state:'PASS'});f.status.providers[1].authenticated='true';await f.context.loadStatus();
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.automotiveOverviewGrid.children[0].children[1].textContent,f.i.t('automotive.status.coverage',{connected:f.i.t('common.unknown'),total:f.i.t('common.unknown')}));assert.equal(f.nodes.automotiveOverviewGrid.children[2].children[1].textContent,f.i.t('common.unknown'));assert.equal(f.nodes.automotiveOverviewGrid.children[3].children[1].textContent,f.i.t('common.unknown'));assert.equal(f.nodes.automotiveOverviewGrid.children[5].children[1].textContent,f.i.t('common.unknown'));assert.ok(f.nodes.providerGrid.textContent.includes(f.i.t('automotive.status.conflict')));assert.notEqual(f.nodes.railStatusLight.className,'status-light ok');assert.equal(f.i.missingKeys().length,0);}
});
test('an older status reply cannot restore a private dealer after a newer denied status read',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();const release=f.hold('/api/automotive/status'),pending=f.context.loadStatus();await release.started;f.deny();await f.context.loadStatus();release();await pending;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.partnerName.textContent,f.i.t('automotive.status.dealer_unknown'));assert.equal(f.nodes.automotiveOverviewGrid.children.length,0);assert.ok(!f.nodes.providerGrid.textContent.includes('RAW_PRIVATE_ERROR'));assert.ok(f.nodes.providerGrid.textContent.includes(f.i.t('common.access_denied')));assert.equal(f.i.missingKeys().length,0);}
});
test('pending opportunity, search and ZERO replies cannot repaint views after current Automotive access is denied',async()=>{
 for(const route of ['/api/automotive/opportunities/today','/api/automotive/search','/api/zero/turn']){const f=fixture();await f.context.loadStatus();await f.context.loadToday();const release=f.hold(route),pending=route.endsWith('/today')?f.context.loadToday():route.endsWith('/search')?f.context.runSearch('Literal query'):f.context.askZero('Literal question');await release.started;f.deny();await f.context.loadStatus();release();await pending;assert.equal(f.nodes.todayList.textContent,'');assert.equal(f.nodes.vehicleGrid.textContent,'');assert.equal(f.nodes.zeroAnswer.textContent,'');assert.equal(f.nodes.searchButton.disabled,true);assert.equal(f.nodes.zeroQuery.disabled,true);assert.equal(f.nodes.zeroForm.querySelector('button').disabled,true);}
});
test('authorized Automotive search, enrichment and detail keep the native routes and values; closing a detail invalidates its pending read',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();const candidate={canonical_listing_id:'listing_literal',vehicle:{make:'BMW',model:'i4',variant:'Literal <img>',build_year:2024,mileage_km:1234,fuel:'ELECTRIC',images:[]},commercial:{gross_price_eur:12345},identity:{provider:'mobile_de',provider_listing_id:'native_listing',source_url:'https://provider.example.test/listing'},listing:{freshness:{classification:'FRESH'}},seller:{city:'Literal city',country:'NL'},provenance:{provider_verified:false}};f.search.results=[candidate];Object.assign(f.analysis,{candidate,buy_score:{available:true,score:78,components:[]}});await f.context.runSearch('Exact BMW query');assert.equal(JSON.parse(f.calls.find(c=>c.route==='/api/automotive/search').options.body).query,'Exact BMW query');assert.ok(f.calls.some(c=>c.route==='/api/automotive/vehicles/listing_literal/analysis'));await f.context.showVehicle('listing_literal');assert.equal(f.nodes.detailTitle.textContent,'BMW i4 Literal <img>');assert.equal(f.nodes.detailScore.querySelector('strong').textContent,'78');assert.equal(f.nodes.sourceLink.href,'https://provider.example.test/listing');assert.equal(f.nodes.vehicleDetail.hidden,false);
 f.clearAnalyses();const release=f.hold('/api/automotive/vehicles/'),pending=f.context.showVehicle('listing_literal');await release.started;await f.nodes.closeDetail.fire('click');release();await pending;assert.equal(f.nodes.vehicleDetail.hidden,true);assert.equal(f.nodes.searchButton.disabled,false);
});
