'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('../zero-evaluation/automotive-page-fixture');
const {locales}=require('../foundly-i18n');
const candidate=()=>({canonical_listing_id:'literal_listing',vehicle:{make:'BMW',model:'i4',variant:'Literal <img>',build_year:2024,mileage_km:0,fuel:'ELECTRIC',images:['native_reference']},commercial:{gross_price_eur:12345},identity:{provider:'literal_provider',source_url:'https://provider.example.test/listing'},seller:{city:'Literal city',country:'NL'},listing:{freshness:{classification:'CACHED'}},provenance:{provider_verified:false}});
const find=(host,key)=>host.all().find(n=>n.getAttribute('data-i18n')==='automotive.search.'+key);
test('denied Automotive search clears earlier source criteria and detail evidence',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();f.search.criteria={make:'Private source make'};await f.context.runSearch('first');f.nodes.detailTitle.textContent='Private vehicle';f.nodes.vehicleDetail.hidden=false;f.deny();await f.context.runSearch('second');assert.equal(f.nodes.criteriaPanel.textContent,'');assert.equal(f.nodes.detailTitle.textContent,'');assert.equal(f.nodes.vehicleDetail.hidden,true);assert.equal(f.nodes.searchButton.disabled,true);
});
test('missing Automotive results are not presented as an observed zero count',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();delete f.search.results;await f.context.runSearch('query');assert.equal(f.nodes.resultCount.textContent,f.i.t('common.unknown'));
});
test('Automotive results and criteria localize in place without altering source identity, authored inputs, native payloads or known zero',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();const row=candidate();f.search.results=[row];f.search.criteria={make:'BMW',model:'i4 <img>',year_min:2020,mileage_max_km:1234,purchase_price_max_eur:25000,fuel:'ELECTRIC',transmission:'AUTOMATIC',drivetrain:'AWD',options:['Literal option'],country:'NL',custom:'Literal custom field'};f.search.provider_executions=[{provider:'literal_provider',state:'LIVE',success:'true',called:true}];Object.assign(f.analysis,{candidate:row,buy_score:{available:false,score:90}});f.nodes.automotiveQuery.value='Authored BMW query';await f.context.runSearch('Authored BMW query');const card=f.nodes.vehicleGrid.children[0],n=f.calls.length,source=JSON.stringify(f.search);
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,n);assert.equal(f.nodes.vehicleGrid.children[0],card);assert.equal(f.nodes.automotiveQuery.value,'Authored BMW query');assert.equal(card.querySelector('h3').textContent,'BMW i4 Literal <img>');assert.equal(card.querySelector('h3').children.length,0);assert.ok(card.textContent.includes(f.i.t('automotive.search.enum.electric')));assert.ok(card.textContent.includes(new Intl.NumberFormat(locale,{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(12345)));assert.equal(find(card,'mileage').parentNode.children[1].textContent,new Intl.NumberFormat(locale).format(0));assert.equal(find(card,'year').parentNode.children[1].textContent,'2024');assert.equal(card.all().find(n=>n.className==='mini-score').textContent,f.i.t('common.unknown'));assert.equal(find(f.nodes.criteriaPanel,'field.make').parentNode.children[1].textContent,'BMW');assert.equal(find(f.nodes.criteriaPanel,'field.model').parentNode.children[1].textContent,'i4 <img>');assert.ok(f.nodes.criteriaPanel.textContent.includes('Literal custom field'));assert.ok(f.nodes.criteriaPanel.textContent.includes(f.i.t('automotive.status.state.unknown')));assert.equal(JSON.stringify(f.search),source);assert.equal(f.i.missingKeys().length,0);}
 assert.deepEqual(JSON.parse(f.calls.find(c=>c.route==='/api/automotive/search').options.body),{query:'Authored BMW query'});await find(card,'open').fire('click');assert.equal(f.nodes.detailTitle.textContent,'BMW i4 Literal <img>');
});
test('pending search keeps localized progress and blocks duplicate provider queries',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();const release=f.hold('/api/automotive/search'),pending=f.context.runSearch('Exact pending query');await release.started;const n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.searchButton.querySelector('span').textContent,f.i.t('automotive.search.searching'));assert.equal(f.nodes.vehicleGrid.all().find(n=>n.className==='loading-ring').getAttribute('aria-label'),f.i.t('automotive.search.search_loading'));await f.context.runSearch('Unwanted duplicate');assert.equal(f.calls.length,n);assert.equal(f.nodes.searchButton.disabled,true);}
 release();await pending;assert.equal(f.nodes.searchButton.disabled,false);assert.equal(f.nodes.resultCount.textContent,f.i.number(0));assert.equal(f.i.missingKeys().length,0);
});
test('ranked opportunities keep source identity, native zero scores and locale bindings without additional reads',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();const row=candidate();f.today.opportunities=[{candidate:row,rank:1,buy_score:{available:true,score:0,components:[]}}];f.today.warning='Native fallback profile warning';f.today.personalisation='UNCONFIGURED';await f.context.loadToday();const button=f.nodes.todayList.children[0],n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.todayList.children[0],button);assert.ok(button.textContent.includes('BMW i4 Literal <img>'));assert.ok(button.textContent.includes('literal_provider'));assert.equal(button.children[2].textContent,f.i.number(0));assert.equal(f.nodes.todayList.children[1].textContent,f.i.t('automotive.search.no_profile'));assert.equal(f.calls.length,n);assert.equal(f.i.missingKeys().length,0);}
 await button.fire('click');assert.equal(f.nodes.detailTitle.textContent,'BMW i4 Literal <img>');assert.equal(f.nodes.vehicleDetail.hidden,false);
});
test('denied enrichment clears all prior observations and rejects a late opportunity read',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();f.search.results=[candidate()];f.respond('/api/automotive/vehicles/literal_listing/analysis',{status:403,payload:{error:'RAW_PRIVATE_ERROR'}});const release=f.hold('/api/automotive/opportunities/today'),pending=f.context.loadToday();await release.started;await f.context.runSearch('query');release();await pending;assert.equal(f.nodes.vehicleGrid.textContent,'');assert.equal(f.nodes.criteriaPanel.textContent,'');assert.equal(f.nodes.todayList.textContent,'');assert.equal(f.nodes.automotiveOverviewGrid.textContent,'');assert.equal(f.nodes.searchButton.disabled,true);assert.notEqual(f.nodes.partnerName.textContent,'Literal private dealer');
});
test('ZERO progress localizes while its answer remains literal and a later failed turn replaces it with safe localized feedback',async()=>{
 const f=fixture();await f.context.loadStatus();await f.context.loadToday();f.respond('/api/zero/turn',{payload:{display_text:'Literal <img> Analyseer markt'}});const release=f.hold('/api/zero/turn'),pending=f.context.askZero('Exact authored question');await release.started;const n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.zeroAnswer.textContent,f.i.t('automotive.search.zero_loading'));await f.context.askZero('Duplicate');assert.equal(f.calls.length,n);}
 release();await pending;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.zeroAnswer.textContent,'Literal <img> Analyseer markt');assert.equal(f.nodes.zeroAnswer.children.length,0);}
 f.respond('/api/zero/turn',{status:403,payload:{error:'RAW_PRIVATE_ERROR'}});await f.context.askZero('next');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.zeroAnswer.textContent,f.i.t('automotive.search.zero_error',{reason:f.i.t('common.access_denied')}));assert.equal(f.i.missingKeys().length,0);}assert.equal(f.nodes.searchButton.disabled,false);
});
