'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/calendar-creation-recovery-fixture'),{calendarOperations}=require('../calendar-operations');
function setup(){const f=fixture(),ops=calendarOperations(f.core),query={from:'2026-10-02T08:00:00Z',to:'2026-10-02T09:00:00Z',duration_minutes:60},availability=f.core.save(f.ctx,f.actor,'availability',{title:'Literal available window',calendar_id:f.calendar.id,start_at:query.from,end_at:query.to,timezone:'Europe/Amsterdam'}).record;return {...f,ops,query,availability};}
test('Scheduling slots retain the literal native calendar name and revision for the reviewed choice',()=>{const f=setup(),slot=f.ops.slots(f.ctx,f.actor,f.query).items[0];assert.equal(slot.calendar_name,f.calendar.name);assert.equal(slot.calendar_revision,f.calendar.revision);const updated=f.core.save(f.ctx,f.actor,'calendars',{name:'Literal PRIVATE renamed calendar'},{id:f.calendar.id,expected_revision:f.calendar.revision}).record;assert.throws(()=>f.ops.book(f.ctx,f.actor,{...slot,title:'Reviewed old calendar',confirm:true},{idempotency_key:'reviewed-old-calendar'}),{code:'availability_changed'});const fresh=f.ops.slots(f.ctx,f.actor,f.query).items[0];assert.equal(fresh.calendar_name,updated.name);assert.equal(fresh.calendar_revision,updated.revision);assert.equal(f.core.list(f.ctx,f.actor,'events').total,0);});
test('Scheduling rejects changed or incomplete reviewed calendar metadata while preserving legacy booking input',()=>{for(const change of [s=>s.calendar_name='Different reviewed calendar',s=>s.calendar_revision++,s=>delete s.calendar_name,s=>delete s.calendar_revision]){const f=setup(),slot=f.ops.slots(f.ctx,f.actor,f.query).items[0];change(slot);assert.throws(()=>f.ops.book(f.ctx,f.actor,{...slot,title:'PRIVATE mismatched review',confirm:true},{idempotency_key:'mismatched-calendar-review'}),{code:'availability_changed'});assert.equal(f.core.list(f.ctx,f.actor,'events').total,0);}const f=setup(),legacy=f.ops.slots(f.ctx,f.actor,f.query).items[0];delete legacy.calendar_name;delete legacy.calendar_revision;assert.equal(f.ops.book(f.ctx,f.actor,{...legacy,title:'Compatible legacy input',confirm:true},{idempotency_key:'legacy-calendar-review'}).record.calendar_id,f.calendar.id);});
test('Scheduling excludes deleted calendars and availability from offered slots',()=>{const a=setup();assert.equal(a.ops.slots(a.ctx,a.actor,a.query).items.length,1);a.core.bucket(a.ctx,'calendars')[0].deleted_at='2026-10-01T00:00:00Z';assert.equal(a.ops.slots(a.ctx,a.actor,a.query).items.length,0);const b=setup();b.core.bucket(b.ctx,'availability')[0].deleted_at='2026-10-01T00:00:00Z';assert.equal(b.ops.slots(b.ctx,b.actor,b.query).items.length,0);});
test('Scheduling does not treat a deleted appointment as current busy time',()=>{const f=setup();f.core.save(f.ctx,f.actor,'events',{title:'Deleted original appointment',calendar_id:f.calendar.id,start_at:f.query.from,end_at:f.query.to,timezone:'Europe/Amsterdam'});assert.equal(f.ops.slots(f.ctx,f.actor,f.query).items.length,0);f.core.bucket(f.ctx,'events')[0].deleted_at='2026-10-01T00:00:00Z';assert.equal(f.ops.slots(f.ctx,f.actor,f.query).items.length,1);});
test('Scheduling per-calendar candidate limits expose incomplete totals instead of complete empty or false exact counts',()=>{const f=setup();const row=f.core.bucket(f.ctx,'availability')[0];row.end_at='2026-10-05T08:00:00Z';const result=f.ops.slots(f.ctx,f.actor,{from:row.start_at,to:row.end_at,duration_minutes:5,step_minutes:5});assert.equal(result.items.length,500);assert.equal(result.truncated,true);assert.equal(result.total,null);assert.equal(result.returned_count,500);assert.equal(result.candidate_limit_applied,true);});
test('Scheduling automatic calendar selection exposes the fifty-calendar boundary',()=>{const f=setup();for(let n=0;n<50;n++)f.core.save(f.ctx,f.actor,'calendars',{name:'Authorized calendar '+n,timezone:'Europe/Amsterdam'});const result=f.ops.slots(f.ctx,f.actor,f.query);assert.equal(result.truncated,true);assert.equal(result.total,null);assert.equal(result.calendar_limit_applied,true);assert.equal(result.selected_calendar_count,50);assert.equal(result.available_calendar_count,51);});
test('Scheduling a freed deleted-event slot also passes the native conflict check when booked',()=>{const f=setup();f.core.save(f.ctx,f.actor,'events',{title:'Deleted prior event',calendar_id:f.calendar.id,start_at:f.query.from,end_at:f.query.to,timezone:'Europe/Amsterdam'});f.core.bucket(f.ctx,'events')[0].deleted_at='2026-10-01T00:00:00Z';const slot=f.ops.slots(f.ctx,f.actor,f.query).items[0],result=f.ops.book(f.ctx,f.actor,{...slot,title:'New confirmed appointment',confirm:true},{idempotency_key:'replacement-after-deletion'});assert.equal(result.record.title,'New confirmed appointment');assert.equal(f.core.list(f.ctx,f.actor,'events').total,1);});
test('Scheduling explicitly zero duration or step is rejected rather than silently defaulted',()=>{const f=setup();assert.throws(()=>f.ops.slots(f.ctx,f.actor,{...f.query,duration_minutes:0}),{code:'scheduling_window_invalid'});assert.throws(()=>f.ops.slots(f.ctx,f.actor,{...f.query,step_minutes:0}),{code:'scheduling_window_invalid'});});
test('Scheduling a complete exact five-hundred-slot boundary retains the known total',()=>{const f=setup(),row=f.core.bucket(f.ctx,'availability')[0];row.end_at=new Date(Date.parse(row.start_at)+500*5*60000).toISOString();const result=f.ops.slots(f.ctx,f.actor,{from:row.start_at,to:row.end_at,duration_minutes:5,step_minutes:5});assert.equal(result.items.length,500);assert.equal(result.total,500);assert.equal(result.truncated,false);assert.equal(result.candidate_limit_applied,false);});
test('Scheduling a result-page limit retains a computed exact total when source selection is complete',()=>{const f=setup(),query={from:f.query.from,to:'2026-10-02T18:00:00Z',duration_minutes:5,step_minutes:5};f.core.bucket(f.ctx,'availability')[0].end_at=query.to;for(let n=0;n<4;n++){const cal=f.core.save(f.ctx,f.actor,'calendars',{name:'Complete source '+n,timezone:'Europe/Amsterdam'}).record;f.core.save(f.ctx,f.actor,'availability',{title:'Additional complete availability',calendar_id:cal.id,start_at:query.from,end_at:query.to,timezone:'Europe/Amsterdam'});}const result=f.ops.slots(f.ctx,f.actor,query);assert.equal(result.items.length,500);assert.equal(result.total,600);assert.equal(result.known_slot_count,600);assert.equal(result.result_limit_applied,true);assert.equal(result.candidate_limit_applied,false);assert.equal(result.calendar_limit_applied,false);assert.equal(result.truncated,true);});
