'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{fixture}=require('../zero-evaluation/fixture'),{page}=require('../zero-evaluation/calendar-event-page-fixture');
for(const zero of [false,true])test('actual HTTP Calendar '+(zero?'ZERO':'native')+' page recovers from fresh VM after encrypted restart, validates wired assets and retires revoked content',async()=>{const server=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/calendar-creation-ack-drop')});try{
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['calendar'],expected_revision:0})).status,200);const owner=await server.enroll('calendar.page.owner',['SALES']),cal=await server.request('/api/calendar/calendars','POST',{name:'Literal PRIVATE calendar',timezone:'Europe/Amsterdam'},owner.cookie);assert.equal(cal.status,201);let drop=true;
 const transport=async(route,opts={})=>{const input=opts.body?JSON.parse(opts.body):undefined,create=route.endsWith('/create')||input?.client_context?.calendar_action?.operation==='CREATE',headers={...opts.headers};if(create&&drop){drop=false;headers['x-zero-calendar-drop-reply']='isolated-calendar-fixture';}const response=await server.request(route,opts.method||'GET',input,owner.cookie,headers);return {ok:response.status<400,status:response.status,json:async()=>response.body};};
 const first=await page({transport,calendar:cal.body.record});await first.render();if(zero){first.field('transport').value='ZERO';await first.field('transport').fire('change');}await first.fill();await first.submit();assert.equal(first.writes().length,1);assert.ok([...first.saved].some(([k])=>k.startsWith('foundly.calendar.creation.v1:')));assert.ok(!JSON.stringify([...first.saved]).includes('PRIVATE'));first.box().remove();await server.stop();await server.start();owner.cookie=await server.login(owner);
 const list=await server.request('/api/calendar/events','GET',undefined,owner.cookie);assert.equal(list.body.total,1);const record=list.body.items[0];assert.equal((await server.request('/api/calendar/events/'+record.id,'PUT',{title:'Current PRIVATE newer appointment',expected_revision:1},owner.cookie)).status,200);
 const fresh=await page({transport,calendar:cal.body.record,storage:first.saved});await fresh.render();await fresh.control('recover').fire('click');assert.equal(fresh.writes().length,0);assert.equal(fresh.recoveries().length,1);assert.equal([...fresh.saved].filter(([k])=>k.startsWith('foundly.calendar.creation.v1:')).length,0);const content=()=>fresh.content.all().map(n=>n.textContent).join(' ');assert.ok(content().includes('Literal PRIVATE appointment'));assert.ok(content().includes('Current PRIVATE newer appointment'));
 for(const file of ['calendar-recurrence.js','calendar-time.js','calendar-event-client-state.js','calendar-event-client.js']){const asset=await server.request('/'+file);assert.equal(asset.status,200);assert.equal(asset.body,fs.readFileSync(require.resolve('../'+file),'utf8'));}const html=(await server.request('/calendar')).body;let prior=-1;for(const file of ['calendar-recurrence.js','calendar-time.js','calendar-event-client-state.js','calendar-event-client.js','foundly-workspace.js']){const at=html.indexOf('/'+file);assert.ok(at>prior,file);prior=at;}
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['calendar'],capability_flags:{'calendar:events':false},expected_revision:1})).status,200);await fresh.control('load_current').fire('click');assert.equal(fresh.ui.state.workspace,null);assert.ok(!content().includes('PRIVATE'));for(const locale of fresh.context.FoundlyLocales.locales)fresh.i.setLocale(locale);assert.ok(!content().includes('PRIVATE'));
 }finally{await server.close();}});
