'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture'),{page}=require('../zero-evaluation/calendar-scheduling-page-fixture');
test('actual HTTP scheduling page recovers after a lost booking reply and encrypted restart, preserves fresh input and loads its real production assets',async()=>{
 const server=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/calendar-booking-ack-drop')});try{
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['calendar'],expected_revision:0})).status,200);const owner=await server.enroll('scheduling.page.owner',['SALES']),cal=await server.request('/api/calendar/calendars','POST',{name:'PRIVATE actual calendar',timezone:'Europe/Amsterdam'},owner.cookie);assert.equal(cal.status,201);assert.equal((await server.request('/api/calendar/availability','POST',{title:'PRIVATE available window',calendar_id:cal.body.record.id,start_at:'2026-10-02T08:00:00.000Z',end_at:'2026-10-02T09:00:00.000Z',timezone:'Europe/Amsterdam'},owner.cookie)).status,201);
 let drop=true,books=0,recoveries=0;const transport=async(route,options={})=>{const headers={...options.headers};if(route==='/api/calendar/scheduling/book'){books++;if(drop){drop=false;headers['x-zero-booking-drop-reply']='isolated-booking-fixture';}}if(route==='/api/calendar/scheduling/recover')recoveries++;const r=await server.request(route,options.method||'GET',options.body?JSON.parse(options.body):undefined,owner.cookie,headers);return {ok:r.status<400,status:r.status,json:async()=>r.body};};
 const first=await page({calendar:cal.body.record,transport});await first.render();await first.fill();await first.control('book').fire('click');assert.equal(books,1);assert.ok(first.box().textContent.includes(first.i.t('calendar.scheduling.uncertain')));assert.ok(![...first.saved.values()].join('').includes('PRIVATE'));await server.stop();await server.start();owner.cookie=await server.login(owner);
 const current=await page({calendar:cal.body.record,transport,storage:first.saved});await current.render();current.field('title').value='PRIVATE fresh post-reload input';await current.field('title').fire('input');await current.control('recover').fire('click');assert.equal(books,1);assert.equal(recoveries,1);assert.equal(current.field('title').value,'PRIVATE fresh post-reload input');assert.ok(current.box().textContent.includes('Literal PRIVATE slot appointment'));assert.equal((await server.request('/api/calendar/events','GET',undefined,owner.cookie)).body.total,1);assert.equal(current.saved.size,0);assert.ok(!fs.readFileSync(path.join(server.dir,'foundly-core-state.json'),'utf8').includes('PRIVATE'));
 await current.control('clear').fire('click');assert.equal((await server.request('/api/identity/users/'+owner.member.id,'PUT',{roles:['VIEWER'],expected_revision:owner.member.revision,confirm:true,reason:'Revoke booking capability in isolated page test'})).status,200);owner.cookie=await server.login(owner);await current.control('refresh').fire('click');assert.ok(current.box().textContent.includes(current.i.t('calendar.scheduling.read_only')));
 const html=await server.request('/calendar','GET',undefined,owner.cookie);assert.equal(html.status,200);let previous=-1;for(const name of ['calendar-time.js','calendar-event-client-state.js','calendar-scheduling-client-state.js','calendar-scheduling-client.js','foundly-workspace.js']){const at=html.body.indexOf('src="/'+name+'"');assert.ok(at>previous,'Production page must load '+name+' after its dependencies');previous=at;}for(const name of ['calendar-scheduling-client-state.js','calendar-scheduling-client.js']){const asset=await server.request('/'+name,'GET',undefined,owner.cookie);assert.equal(asset.status,200);assert.equal(asset.body,fs.readFileSync(require.resolve('../'+name),'utf8'));}
 }finally{await server.close();}
});
