'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{fixture,hash}=require('../zero-evaluation/calendar-creation-recovery-fixture'),{calendarOperations}=require('../calendar-operations');
const scope='calendar:booking_operations';
function setup(){const f=fixture(),ops=calendarOperations(f.core);f.core.save(f.ctx,f.actor,'availability',{title:'PRIVATE available window',calendar_id:f.calendar.id,start_at:'2026-10-02T08:00:00.000Z',end_at:'2026-10-02T09:00:00.000Z',timezone:'Europe/Amsterdam'});const slot=ops.slots(f.ctx,f.actor,{from:'2026-10-02T08:00:00.000Z',to:'2026-10-02T09:00:00.000Z',duration_minutes:60}).items[0],input={...slot,title:'PRIVATE selected appointment',confirm:true},key=crypto.randomUUID(),meta={request_id:key,request_fingerprint:hash(input),availability_revision:slot.availability_revision};return {...f,ops,input,key,meta,book:()=>ops.book(f.ctx,f.actor,input,{idempotency_key:key}),recover:(metadata=meta,actor=f.actor,ctx=f.ctx)=>ops.recoverBooking(ctx,actor,{...metadata,confirm:true}),journal:()=>f.adapter.bucket(f.ctx,scope)};}
test('native booking replay retains immutable original proof separately from a later current appointment',()=>{const f=setup(),created=f.book();f.core.save(f.ctx,f.actor,'events',{title:'PRIVATE later appointment'},{id:created.record.id,expected_revision:1});const replay=f.book();assert.ok(replay.created_record,'Replay must retain the original booked event, not attribute current fields to the original click');assert.equal(replay.created_record.title,f.input.title);assert.equal(replay.record.title,'PRIVATE later appointment');assert.equal(replay.created_revision,1);assert.equal(replay.current_revision,2);assert.equal(replay.created_record_snapshot_sha256,hash(replay.created_record));assert.equal(replay.event_created,false);assert.equal(f.records().length,1);});
test('native booking replay refuses results after original calendar ownership is withdrawn',()=>{const f=setup();f.book();f.core.bucket(f.ctx,'calendars')[0].owner_id='another-calendar-owner';assert.throws(f.book,{code:'record_not_found'});});
test('native booking replay refuses a deleted current appointment',()=>{const f=setup();f.book();f.records()[0].deleted_at='2026-10-03T00:00:00.000Z';assert.throws(f.book,{code:'calendar_booking_missing'});});
test('native booking requires bounded opaque request metadata before committing an event',()=>{const f=setup();assert.throws(()=>f.ops.book(f.ctx,f.actor,f.input,{idempotency_key:'x'.repeat(201)}),{code:'booking_idempotency_required'});assert.equal(f.records().length,0);});
test('native booking recovers a retained result after restart and never sends an external invitation',()=>{const f=setup();f.book();f.restart();const value=f.recover();assert.equal(value.state,'APPLIED');assert.equal(value.event_created,false);assert.equal(value.external_invitation,false);assert.equal(value.created_record.title,f.input.title);assert.deepEqual(value.request_context,{...f.ctx,actor_id:f.actor.id});assert.equal(value.created_record_snapshot_sha256,hash(value.created_record));assert.equal(f.records().length,1);});
test('native booking absence closes the original request durably before a delayed booking can arrive',()=>{const f=setup(),absent=f.recover();assert.equal(absent.state,'NOT_APPLIED');assert.equal(absent.record,null);assert.equal(absent.created_record,null);f.restart();assert.equal(f.recover().state,'NOT_APPLIED');assert.throws(f.book,{code:'calendar_booking_request_abandoned'});assert.equal(f.records().length,0);});
test('native booking recovery binds metadata, current actor, current capabilities and immutable snapshot',()=>{const f=setup();f.book();assert.throws(()=>f.recover({...f.meta,request_fingerprint:'a'.repeat(64)}),{code:'calendar_booking_request_conflict'});assert.throws(()=>f.recover(f.meta,f.participant),{code:'calendar_booking_recovery_unverifiable'});const entry=f.journal()[0],original=entry.created_record.title;entry.created_record.title='Unbound private alteration';assert.throws(f.recover,{code:'calendar_booking_recovery_unverifiable'});entry.created_record.title=original;f.resolver.configure(f.ctx,f.admin,{entitlements:['calendar'],capability_flags:{'calendar:availability':false},expected_revision:1});assert.throws(f.recover,{code:'capability_disabled'});});
test('native booking event and absence proof roll back on failed persistence',()=>{const f=setup();f.fail(true);assert.throws(f.book,{code:'EIO'});assert.equal(f.records().length,0);assert.equal(f.journal().length,0);assert.throws(f.recover,{code:'EIO'});assert.equal(f.journal().length,0);f.fail(false);assert.equal(f.book().record.title,f.input.title);assert.equal(f.recover().state,'APPLIED');});
test('legacy booking receipts remain replayable with current access but cannot acquire fabricated immutable recovery proof',()=>{const f=setup();f.core.save(f.ctx,f.actor,'events',{title:f.input.title,calendar_id:f.input.calendar_id,start_at:f.input.start_at,end_at:f.input.end_at,timezone:f.input.timezone,status:'CONFIRMED'},{idempotency_key:'booking:'+f.key,request_fingerprint:hash(f.input)});assert.equal(f.book().deduplicated,true);assert.equal(f.book().booking_status,'LEGACY_OUTCOME_UNVERIFIED');assert.equal(f.book().created_record,null);assert.throws(f.recover,{code:'calendar_booking_recovery_unverifiable'});assert.equal(f.journal().length,0);f.core.bucket(f.ctx,'calendars')[0].owner_id='another-calendar-owner';assert.throws(f.book,{code:'record_not_found'});});
test('native booking recovery refuses a changed current calendar and never leaks operational receipts through shared data',()=>{const f=setup(),created=f.book(),other=f.core.save(f.ctx,f.admin,'calendars',{name:'PRIVATE admin calendar',timezone:'Europe/Amsterdam'}).record;f.core.save(f.ctx,f.admin,'events',{calendar_id:other.id},{id:created.record.id,expected_revision:1});assert.throws(f.recover,{code:'record_not_found'});assert.equal(require('../composition-runtime').scopeVisible(scope,f.resolver,f.ctx,f.actor),false);assert.equal(require('../composition-runtime').scopeVisible(scope,f.resolver,f.ctx,f.admin),false);});
test('native booking receipt capacity fails closed without eviction or a partial event',()=>{const f=setup();f.journal().push(...Array.from({length:100000},()=>({})));assert.throws(f.book,{code:'calendar_booking_capacity'});assert.equal(f.records().length,0);assert.equal(f.journal().length,100000);assert.throws(f.recover,{code:'calendar_booking_capacity'});assert.equal(f.journal().length,100000);});
