'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture'),{page}=require('../zero-evaluation/communication-reply-page-fixture'),{locales}=require('../foundly-locales');
for(const mode of ['native','zero'])test('actual '+mode+' HTTP reply controls retain exact authored content after a destroyed reply and encrypted restart without another draft',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reply-page-source-')),sourceFile=path.join(dir,'retained-source.json'),server=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/communication-reply-ack-drop'),FOUNDLY_MESSAGE_SOURCE_FIXTURE:sourceFile});
 try{
  assert.equal((await server.request('/api/composition','PUT',{entitlements:['communication'],expected_revision:0})).status,200);const owner=await server.enroll('reply.page.owner',['MANAGER']),source={fixture:'RETAINED_MESSAGE_CONTRACT_NOT_LIVE',id:'http_reply_source',revision:1,owner_id:owner.member.id,tenant_id:server.env.FOUNDLY_TENANT_ID,dealer_id:server.env.FOUNDLY_DEALER_ID,owned_entity:'messages',title:'Literal PRIVATE source title <img>',content:'PRIVATE untrusted retained source — never copy',from:'sender@example.test',to:['mailbox@example.test'],cc:[],direction:'INBOUND',internet_message_id:'<source@example.test>',in_reply_to:[],references:[],thread_headers_available:true};fs.writeFileSync(sourceFile,JSON.stringify(source));
  const calls=[];let drop=true;const transport=async(route,opts={})=>{const input=opts.body?JSON.parse(opts.body):undefined,operation=route==='/api/zero/turn'?input.client_context.communication_action.operation:route.endsWith('/drafts')&&opts.method==='POST'?'CREATE_REPLY':'READ',lose=operation==='CREATE_REPLY'&&drop;if(lose)drop=false;calls.push({route,body:opts.body,operation,headers:{...opts.headers}});const r=await server.request(route,opts.method||'GET',input,owner.cookie,{...opts.headers,...(lose?{'x-reply-drop-reply':'isolated-reply-fixture'}:{})});return {ok:r.status<400,status:r.status,json:async()=>r.body};};
  const f=await page({mode,transport}),kind=mode==='native'?'REPLY':'FORWARD';await f.render();await f.fill(kind);const form=f.form();await form.fire('submit');assert.equal(calls.filter(c=>c.operation==='CREATE_REPLY').length,1);const original=structuredClone(calls.find(c=>c.operation==='CREATE_REPLY')),before=calls.length;
  for(const locale of locales){f.i.setLocale(locale);assert.ok(f.form()===form);assert.equal(f.field('content').value,'Literal PRIVATE authored body <script>');assert.equal(f.field('title').value,'Literal PRIVATE authored title <img>');assert.ok(f.detail().textContent.includes(f.i.t('communication.reply.pending')));assert.equal(calls.length,before);}f.field('content').value='PRIVATE changed uncertain draft';await f.field('content').fire('input');assert.equal(f.field('content').value,'Literal PRIVATE authored body <script>');assert.equal(f.detail().canLeave(),false);f.ui.state.conversationId='unrelated-after-uncertainty';
  await server.stop();await server.start();owner.cookie=await server.login(owner);assert.equal((await server.request('/api/communication/drafts','GET',undefined,owner.cookie)).body.total,1);await form.fire('submit');const writes=calls.filter(c=>c.operation==='CREATE_REPLY');assert.equal(writes.length,2);assert.deepEqual(writes[1],original);assert.ok(!f.form());assert.equal(f.detail().canLeave(),true);
  const drafts=await server.request('/api/communication/drafts','GET',undefined,owner.cookie);assert.equal(drafts.body.total,1);const row=drafts.body.items[0];assert.equal(row.title,'Literal PRIVATE authored title <img>');assert.equal(row.content,'Literal PRIVATE authored body <script>');assert.equal(row.delivery_state,'NOT_SENT');assert.equal(row.source_message_ref.id,source.id);assert.equal(row.source_message_ref.mode,kind);assert.deepEqual(row.to,kind==='REPLY'?['sender@example.test']:['forward@example.test']);assert.deepEqual(row.cc||[],kind==='REPLY'?[]:['copy@example.test']);assert.equal((await server.request('/api/communication/messages','GET',undefined,owner.cookie)).body.total,1);assert.ok(!fs.readFileSync(path.join(server.dir,'foundly-core-state.json'),'utf8').includes('PRIVATE'));const after=calls.length;for(const locale of locales){f.i.setLocale(locale);assert.ok(f.detail().textContent.includes(f.i.t('communication.reply.saved_help')));assert.equal(calls.length,after);}assert.equal((await server.request('/foundly-workspace.js','GET',undefined,owner.cookie)).body,fs.readFileSync(require.resolve('../foundly-workspace.js'),'utf8'));
 }finally{await server.close();fs.rmSync(dir,{recursive:true,force:true});}
});
