'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture'),{page}=require('../zero-evaluation/communication-reply-page-fixture'),{locales}=require('../foundly-locales');
for(const mode of ['native','zero'])test('actual '+mode+' HTTP reply controls recover original/current drafts from a new page after destroyed response, source edits and encrypted restart',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reply-recovery-page-')),sourceFile=path.join(dir,'source.json'),server=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/communication-reply-ack-drop'),FOUNDLY_MESSAGE_SOURCE_FIXTURE:sourceFile});
 try{
  assert.equal((await server.request('/api/composition','PUT',{entitlements:['communication'],expected_revision:0})).status,200);const owner=await server.enroll('reply.recovery.page.owner',['MANAGER']),source={fixture:'RETAINED_MESSAGE_CONTRACT_NOT_LIVE',id:'http_reply_recovery_source',revision:1,owner_id:owner.member.id,tenant_id:server.env.FOUNDLY_TENANT_ID,dealer_id:server.env.FOUNDLY_DEALER_ID,owned_entity:'messages',title:'PRIVATE retained source title',content:'PRIVATE untrusted original source',from:'sender@example.test',to:['mailbox@example.test'],cc:[],direction:'INBOUND'},seed=()=>fs.writeFileSync(sourceFile,JSON.stringify(source));seed();
  const calls=[];let drop=true;const transport=async(route,opts={})=>{const input=opts.body?JSON.parse(opts.body):undefined,operation=route==='/api/zero/turn'?input.client_context.communication_action.operation:route.endsWith('/drafts')&&opts.method==='POST'?'CREATE_REPLY':route.endsWith('/reply-requests/recover')?'RECOVER':'READ',lose=operation==='CREATE_REPLY'&&drop;if(lose)drop=false;calls.push({route,body:input,operation,headers:{...opts.headers}});const r=await server.request(route,opts.method||'GET',input,owner.cookie,{...opts.headers,...(lose?{'x-reply-drop-reply':'isolated-reply-fixture'}:{})});return {ok:r.status<400,status:r.status,json:async()=>r.body};};
  const first=await page({mode,transport});await first.render();await first.fill(mode==='native'?'REPLY':'FORWARD');await first.form().fire('submit');const saved=[...first.saved.entries()].filter(([key])=>key.startsWith('foundly.communication.replies.v1:'));assert.equal(saved.length,1);const metadata=JSON.parse(saved[0][1]);assert.equal(metadata.length,1);const meta=metadata[0];assert.deepEqual(Object.keys(meta).sort(),['operation','request_fingerprint','request_id','source_id']);assert.equal(meta.source_id,source.id);assert.ok(!saved[0][1].includes('PRIVATE'));assert.ok(!saved[0][1].includes('example.test'));assert.equal(calls.filter(c=>c.operation==='CREATE_REPLY').length,1);
  await server.stop();await server.start();owner.cookie=await server.login(owner);const list=await server.request('/api/communication/drafts','GET',undefined,owner.cookie);assert.equal(list.body.total,1);const original=list.body.items[0];assert.equal((await server.request('/api/communication/drafts/'+original.id,'PUT',{expected_revision:1,title:'PRIVATE later reply title',content:'PRIVATE later reply body <script>',to:['current@example.test'],cc:[]},owner.cookie)).status,200);Object.assign(source,{revision:2,content:'PRIVATE altered source text',from:'changed@example.test'});seed();await server.stop();await server.start();owner.cookie=await server.login(owner);
  const next=await first.reload();assert.notEqual(next.context,first.context);await next.render();assert.equal(calls.filter(c=>c.operation==='RECOVER').length,0);const before=calls.length;for(const locale of locales){next.i.setLocale(locale);assert.ok(next.recovery().textContent.includes(next.i.t('communication.reply_recovery.operation_message_draft')));assert.equal(calls.length,before);}await next.recoveryAction('recover').fire('click');const recovered=calls.filter(c=>c.operation==='RECOVER');assert.equal(recovered.length,1);assert.deepEqual(recovered[0].body,{...meta,confirm:true});assert.equal(calls.filter(c=>c.operation==='CREATE_REPLY').length,1);assert.equal(next.saved.has(saved[0][0]),false);const after=calls.length;
  for(const locale of locales){next.i.setLocale(locale);const view=next.recovery(),text=view.textContent;assert.ok(text.includes(next.i.t('communication.reply_recovery.original')));assert.ok(text.includes(next.i.t('communication.reply_recovery.current')));assert.ok(text.includes(original.title));assert.ok(text.includes(original.content));assert.ok(text.includes('PRIVATE later reply title'));assert.ok(text.includes('PRIVATE later reply body <script>'));assert.ok(text.includes(original.to[0]));assert.ok(text.includes('current@example.test'));assert.ok(!text.includes('PRIVATE altered source text'));assert.ok(text.includes(next.i.t('communication.reply_recovery.internal_only')));assert.equal(view.all().some(n=>['script','img'].includes(n.tag)),false);assert.deepEqual(Array.from(next.i.missingKeys()),[]);assert.equal(calls.length,after);}
  const drafts=await server.request('/api/communication/drafts','GET',undefined,owner.cookie);assert.equal(drafts.body.total,1);assert.equal(drafts.body.items[0].id,original.id);assert.equal(drafts.body.items[0].revision,2);assert.equal(drafts.body.items[0].delivery_state,'NOT_SENT');assert.equal((await server.request('/api/communication/messages','GET',undefined,owner.cookie)).body.total,1);assert.ok(!fs.readFileSync(path.join(server.dir,'foundly-core-state.json'),'utf8').includes('PRIVATE'));
  const html=await server.request('/communication','GET',undefined,owner.cookie);assert.equal(html.status,200);const state=html.body.indexOf('src="/communication-reply-client-state.js"'),client=html.body.indexOf('src="/communication-reply-recovery-client.js"'),workspace=html.body.indexOf('src="/foundly-workspace.js"');assert.ok(state>=0&&state<client&&client<workspace);for(const file of ['communication-reply-client-state.js','communication-reply-recovery-client.js','communication-template-client-state.js','communication-template-recovery-client.js'])assert.equal((await server.request('/'+file,'GET',undefined,owner.cookie)).body,fs.readFileSync(require.resolve('../'+file),'utf8'));
 }finally{await server.close();fs.rmSync(dir,{recursive:true,force:true});}
});
