'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture'),{page}=require('../zero-evaluation/communication-template-page-fixture'),{locales}=require('../foundly-locales');
for(const mode of ['native','zero'])test('actual '+mode+' HTTP template recovery controls separate original/current drafts on a new page after lost reply, source edits and encrypted restart',async()=>{
 const server=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/communication-template-ack-drop')});
 try{
  assert.equal((await server.request('/api/composition','PUT',{entitlements:['communication'],expected_revision:0})).status,200);
  const owner=await server.enroll('template.recovery.page.owner',['MANAGER']),created=await server.request('/api/communication/templates','POST',{title:'Literal PRIVATE {{name}}',content:'Literal PRIVATE body {{detail}} / {{name}}'},owner.cookie);assert.equal(created.status,201,JSON.stringify(created.body));
  const source=created.body.record,calls=[];let drop=true;
  const transport=async(route,opts={})=>{const input=opts.body?JSON.parse(opts.body):undefined,operation=route==='/api/zero/turn'?input.client_context.communication_action.operation:route.endsWith('/drafts')&&opts.method==='POST'?'CREATE_TEMPLATE_DRAFT':route.endsWith('/template-requests/recover')?'RECOVER':'READ',lose=operation==='CREATE_TEMPLATE_DRAFT'&&drop;if(lose)drop=false;calls.push({route,body:input,operation,headers:{...opts.headers}});const r=await server.request(route,opts.method||'GET',input,owner.cookie,{...opts.headers,...(lose?{'x-template-drop-reply':'isolated-template-fixture'}:{})});return {ok:r.status<400,status:r.status,json:async()=>r.body};};
  const first=await page({mode,transport});await first.render();await first.fill();await first.form().fire('submit');const entries=[...first.saved.entries()].filter(([key])=>key.startsWith('foundly.communication.templates.v1:'));assert.equal(entries.length,1);const metadata=JSON.parse(entries[0][1]);assert.equal(metadata.length,1);const meta=metadata[0];assert.deepEqual(Object.keys(meta).sort(),['operation','request_fingerprint','request_id','source_id']);assert.equal(meta.source_id,source.id);assert.ok(!entries[0][1].includes('PRIVATE'));assert.ok(!entries[0][1].includes('example.test'));assert.equal(calls.filter(c=>c.operation==='CREATE_TEMPLATE_DRAFT').length,1);
  await server.stop();await server.start();owner.cookie=await server.login(owner);
  const list=await server.request('/api/communication/drafts','GET',undefined,owner.cookie);assert.equal(list.body.total,1);const original=list.body.items[0];
  assert.equal((await server.request('/api/communication/drafts/'+original.id,'PUT',{expected_revision:1,title:'PRIVATE edited current title',content:'PRIVATE edited current body <script>',to:['current@example.test'],cc:[]},owner.cookie)).status,200);
  assert.equal((await server.request('/api/communication/templates/'+source.id,'PUT',{expected_revision:1,title:'PRIVATE changed source',content:'PRIVATE unrelated source'},owner.cookie)).status,200);
  await server.stop();await server.start();owner.cookie=await server.login(owner);
  const next=await first.reload();assert.notEqual(next.context,first.context);await next.render();assert.equal(calls.filter(c=>c.operation==='RECOVER').length,0);const before=calls.length;
  for(const locale of locales){next.i.setLocale(locale);assert.ok(next.recovery().textContent.includes(next.i.t('communication.template_recovery.operation_template_draft')));assert.equal(calls.length,before);}
  await next.recoveryAction('recover').fire('click');const recovery=calls.filter(c=>c.operation==='RECOVER');assert.equal(recovery.length,1);assert.deepEqual(recovery[0].body,{...meta,confirm:true});assert.equal(calls.filter(c=>c.operation==='CREATE_TEMPLATE_DRAFT').length,1);assert.equal(next.saved.has(entries[0][0]),false);const after=calls.length;
  for(const locale of locales){next.i.setLocale(locale);const view=next.recovery(),text=view.textContent;assert.ok(text.includes(next.i.t('communication.template_recovery.original')));assert.ok(text.includes(next.i.t('communication.template_recovery.current')));assert.ok(text.includes(original.title));assert.ok(text.includes(original.content));assert.ok(text.includes('PRIVATE edited current title'));assert.ok(text.includes('PRIVATE edited current body <script>'));assert.ok(text.includes('to@example.test'));assert.ok(text.includes('cc@example.test'));assert.ok(text.includes('current@example.test'));assert.ok(!text.includes('PRIVATE unrelated source'));assert.ok(text.includes(next.i.t('communication.template_recovery.internal_only')));assert.equal(view.all().some(n=>['script','img'].includes(n.tag)),false);assert.deepEqual(Array.from(next.i.missingKeys()),[]);assert.equal(calls.length,after);}
  const drafts=await server.request('/api/communication/drafts','GET',undefined,owner.cookie);assert.equal(drafts.body.total,1);assert.equal(drafts.body.items[0].id,original.id);assert.equal(drafts.body.items[0].revision,2);assert.equal(drafts.body.items[0].delivery_state,'NOT_SENT');assert.equal((await server.request('/api/communication/messages','GET',undefined,owner.cookie)).body.total,0);assert.ok(!fs.readFileSync(path.join(server.dir,'foundly-core-state.json'),'utf8').includes('PRIVATE'));
  const html=await server.request('/communication','GET',undefined,owner.cookie);assert.equal(html.status,200);const state=html.body.indexOf('src="/communication-template-client-state.js"'),client=html.body.indexOf('src="/communication-template-recovery-client.js"'),workspace=html.body.indexOf('src="/foundly-workspace.js"');assert.ok(state>=0&&state<client&&client<workspace);for(const file of ['communication-template-client-state.js','communication-template-recovery-client.js'])assert.equal((await server.request('/'+file,'GET',undefined,owner.cookie)).body,fs.readFileSync(require.resolve('../'+file),'utf8'));
 }finally{await server.close();}
});
