'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {create}=require('../zero-evaluation/finance-action-client-fixture'),{fixture}=require('../zero-evaluation/commerce-finance-fixture'),{locales}=require('../foundly-locales');
const root='/api/finance/invoice-actions/';
function setup(native=fixture(),options={}){return create({...options,native:{...native,core:native.finance},commerceCreation:true});}
async function fill(f){await f.box.ready;for(const[key,value]of Object.entries({legal_entity:f.native.entity.id,order:'fixture-order',contact:f.native.contact.id,number:'UI-COMMERCE-001',date:'2026-09-26',supply_date:'2026-09-26',due_date:'2026-10-26'}))await f.set(key,value);}
async function submit(f){await f.button('preview').fire('click');await f.confirm();await f.button('submit').fire('click');}
test('order invoice UI reviews actual CRM and immutable order prices in all eight locales, then creates and links only one draft',async()=>{
 const f=setup();f.native.crm.update(f.native.ctx,f.native.actor,'contacts',f.native.contact.id,{name:'Private CRM <img>',billing_address:'Native address <script>'});f.native.run('PRODUCT_SAVE',{product_id:'fixture-product',sku:'FIXTURE',name:'Changed catalog title',currency:'EUR',unit_price_minor:999,tax_rate_bps:900,expected_revision:1},'later-catalog');
 await fill(f);assert.equal(f.field('supplier_name'),undefined);assert.equal(f.box.all().filter(n=>n.getAttribute('data-finance-line')!==null).length,0);await f.button('preview').fire('click');assert.equal(f.native.rows('invoices').length,0);assert.ok(f.box.textContent.includes('Private CRM <img>'));assert.ok(f.box.textContent.includes('Native address <script>'));assert.ok(f.box.textContent.includes('Locked fixture price'));assert.ok(!f.box.all().some(n=>['img','script'].includes(n.tag)));await f.confirm();const calls=f.calls.length;
 for(const locale of locales){f.context.FoundlyI18n.setLocale(locale);assert.equal(f.calls.length,calls);assert.equal(f.field('order').value,'fixture-order');assert.equal(f.field('contact').value,f.native.contact.id);assert.equal(f.field('confirm').checked,true);assert.ok(f.box.textContent.includes(f.context.FoundlyI18n.currencyCents(367,'EUR')));assert.equal(f.context.FoundlyI18n.missingKeys().length,0);}
 await f.button('submit').fire('click');assert.equal(f.native.rows('invoices').length,1,f.box.textContent);const row=f.native.rows('invoices')[0];assert.equal(row.gross_cents,367);assert.equal(row.status,'DRAFT');assert.equal(row.customer_name,'Private CRM <img>');assert.equal(f.native.order().invoice_id,row.id);assert.equal(f.native.rows('journal_entries').length,0);assert.equal(f.native.rows('payments').length,0);assert.equal(f.box.canLeave(),true);
});
test('the order reference never silently selects a CRM customer; changing a selected source or date invalidates confirmation',async()=>{
 const f=setup();await fill(f);await f.set('contact','');await f.button('preview').fire('click');assert.equal(f.button('submit').disabled,true);assert.equal(f.calls.filter(c=>c.route.endsWith('/preview')).length,0);
 await f.set('contact',f.native.contact.id);await f.button('preview').fire('click');await f.confirm();await f.set('due_date','2026-10-27');assert.equal(f.field('confirm').checked,false);assert.equal(f.button('submit').disabled,true);assert.equal(f.native.rows('invoices').length,0);await submit(f);assert.equal(f.native.rows('invoices').length,1);
});
test('a changed CRM source rejects stale execution and restores a nonexecuted selection for explicit renewed review',async()=>{
 const f=setup();await fill(f);await f.button('preview').fire('click');await f.confirm();f.native.crm.update(f.native.ctx,f.native.actor,'contacts',f.native.contact.id,{billing_address:'Current changed source'});await f.button('submit').fire('click');assert.equal(f.native.rows('invoices').length,0);assert.equal(f.button('recover').disabled,false);await f.button('recover').fire('click');assert.equal(f.field('number').value,'UI-COMMERCE-001');assert.equal(f.field('contact').value,f.native.contact.id);assert.equal(f.field('confirm').checked,false);assert.equal(f.box.canLeave(),false);await submit(f);assert.equal(f.native.rows('invoices').length,1);assert.equal(f.native.rows('invoices')[0].customer_address,'Current changed source');assert.equal(f.box.canLeave(),true);
});
test('lost order-invoice reply recovers original draft and current paid state after persistence restart without another execution',async()=>{
 const f=setup();await fill(f);f.lose(root+'execute');await submit(f);const invoice=f.native.rows('invoices')[0];assert.ok(invoice);assert.equal(f.box.canLeave(),false);f.detach();f.native.restart();f.native.finance.postInvoice(f.native.ctx,f.native.actor,invoice.id);f.native.finance.recordPayment(f.native.ctx,f.native.actor,{invoice_id:invoice.id,amount_cents:367,date:'2026-09-26',reference:'Recorded native fixture receipt'});
 const next=setup(f.native);await next.box.ready;assert.equal(next.box.open,true);await next.button('recover').fire('click');assert.equal(next.native.rows('invoices').length,1);assert.equal(next.native.rows('payments').length,1);assert.equal(next.calls.filter(c=>c.route.endsWith('/execute')).length,0);assert.ok(next.box.textContent.includes(next.context.FoundlyI18n.t('finance.actions.status_draft')));assert.ok(next.box.textContent.includes(next.context.FoundlyI18n.t('finance.actions.status_paid')));assert.equal(next.box.canLeave(),true,next.box.textContent);
});
test('bounded CRM paging and explicit search preserve invoice dates and other selected sources while invalidating review',async()=>{
 const native=fixture();for(let i=0;i<54;i++)native.crm.create(native.ctx,native.actor,'contacts',{name:'Paged customer '+String(i).padStart(2,'0'),billing_address:'Actual fixture address'});const f=setup(native);await fill(f);await f.button('preview').fire('click');await f.confirm();assert.equal(f.field('contact').children.length,51);await f.button('contact_next').fire('click');assert.equal(f.field('contact').children.length,6);assert.equal(f.field('contact').value,'');assert.equal(f.field('number').value,'UI-COMMERCE-001');assert.equal(f.field('order').value,'fixture-order');assert.equal(f.field('confirm').checked,false);
 await f.set('contact_query','Paged customer 53');await f.button('contact_search').fire('click');assert.equal(f.field('contact').children.length,2);const id=f.field('contact').children[1].value;await f.set('contact',id);await submit(f);assert.equal(f.native.rows('invoices')[0].customer_name,'Paged customer 53');assert.ok(f.calls.filter(c=>c.route.startsWith('/api/crm/contacts')).every(c=>c.route.includes('limit=50')));
});
test('cancelled and already linked orders remain visible with explicit blocking and never create a second invoice',async()=>{
 const f=setup();await fill(f);await submit(f);await fill(f);await f.set('number','UI-COMMERCE-002');await f.button('preview').fire('click');assert.equal(f.button('submit').disabled,true);assert.ok(f.box.textContent.includes(f.context.FoundlyI18n.t('finance.actions.block_order_linked')));assert.equal(f.native.rows('invoices').length,1);
 const g=setup();await fill(g);g.native.run('ORDER_CANCEL',{order_id:'fixture-order',expected_revision:1},'cancel-order');await g.button('preview').fire('click');assert.equal(g.button('submit').disabled,true);assert.ok(g.box.textContent.includes(g.context.FoundlyI18n.t('finance.actions.block_order')));assert.equal(g.native.rows('invoices').length,0);
});
test('a retained command remains recoverable when source-list loading fails and saved invoices are never retried after a refresh failure',async()=>{
 const f=setup();await fill(f);f.lose(root+'execute');await submit(f);f.detach();const next=setup(f.native);next.lose('/api/crm/contacts');await next.box.ready;assert.equal(next.box.open,true);assert.equal(next.button('recover').disabled,false);next.lose('/api/sales/commerce/commerce_orders');await next.button('recover').fire('click');assert.equal(next.native.rows('invoices').length,1);assert.equal(next.button('recover').disabled,true);assert.ok(next.box.textContent.includes(next.context.FoundlyI18n.t('finance.actions.saved_refresh_needed')));assert.equal(next.calls.filter(c=>c.route.endsWith('/execute')).length,0);await next.button('clear').fire('click');assert.equal(next.box.canLeave(),true);
});
test('detaching during confirmation retention prevents late execution and retiring unseen requests restores the explicit draft',{timeout:5000},async()=>{
 const f=setup();await fill(f);await f.button('preview').fire('click');await f.confirm();const release=f.hold(root+'confirmations'),running=f.button('submit').fire('click');await release.started;f.detach();release();await running;assert.equal(f.native.rows('invoices').length,0);const next=setup(f.native);await next.box.ready;await next.button('recover').fire('click');assert.equal(next.native.rows('invoices').length,0);assert.equal(next.field('number').value,'UI-COMMERCE-001');assert.equal(next.field('confirm').checked,false);assert.equal(next.box.canLeave(),false);await submit(next);assert.equal(next.native.rows('invoices').length,1);
});
test('native order paging stays bounded and preserves chosen CRM customer while source searches clear stale confirmation',async()=>{
 const native=fixture();native.run('STOCK_RECEIVE',{product_id:'fixture-product',quantity:60,expected_revision:3,expected_product_revision:1,evidence_reference:'Additional native stock fixture'},'more-stock');for(let i=0;i<54;i++)native.run('ORDER_RESERVE',{order_id:'paged-order-'+String(i).padStart(2,'0'),currency:'EUR',customer_reference:'Native original reference '+i,expected_revision:0,lines:[{product_id:'fixture-product',quantity:1,expected_product_revision:1,expected_inventory_revision:i+4}]},'paged-order-'+i);
 const f=setup(native);await fill(f);await f.button('preview').fire('click');await f.confirm();await f.button('order_next').fire('click');assert.equal(f.field('order').children.length,6);assert.equal(f.field('contact').value,native.contact.id);assert.equal(f.field('order').value,'');assert.equal(f.field('confirm').checked,false);await f.set('order_query','paged-order-53');await f.button('order_search').fire('click');assert.equal(f.field('order').children.length,2);await f.set('order','paged-order-53');await submit(f);assert.equal(f.native.rows('invoices').length,1);assert.equal(f.native.rows('invoices')[0].gross_cents,122);assert.equal(f.native.rows('invoices')[0].commerce_source.order_id,'paged-order-53');assert.equal(f.field('order_query').value,'');assert.ok(f.calls.filter(c=>c.route.startsWith('/api/sales/commerce/')).every(c=>c.route.includes('limit=50')));
});
test('a detached source search cannot rehydrate an old view after its delayed native response',{timeout:5000},async()=>{
 const f=setup();await fill(f);await f.set('contact_query','PRIVATE');const release=f.hold('/api/crm/contacts?limit=50&cursor=0&q=PRIVATE'),running=f.button('contact_search').fire('click');await release.started;f.detach();const before=f.box.textContent;release();await running;assert.equal(f.box.textContent,before);assert.equal(f.native.rows('invoices').length,0);
});
