'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{page}=require('../zero-evaluation/communication-source-page-fixture'),{locales}=require('../foundly-locales');
async function ready(options){const f=await page(options),record=await f.import();await f.render();await f.open(record.id);return {...f,record};}
test('retained source download binds realm and message revision before releasing untrusted bytes',async()=>{const f=await ready(),value=f.service.source(f.ctx,f.actor,f.record.id);assert.deepEqual(value.request_context,{...f.ctx,actor_id:f.actor.id});assert.equal(value.source_id,f.record.id);assert.equal(value.source_revision,f.record.revision);await f.download().fire('click');assert.equal(f.created.length,1);assert.deepEqual(f.revoked,[f.created[0].href]);assert.equal(f.links[0].download,'message-'+f.record.id+'.eml');assert.equal(f.links[0].clicked,true);assert.equal(f.links[0].isConnected,false);assert.equal(await f.created[0].blob.text(),Buffer.from(value.content_base64,'base64').toString());assert.equal(f.created[0].blob.type,'application/octet-stream');assert.equal(f.reads(),1);});
test('source controls and verified download notice change through eight locales without altering source text or making another request',async()=>{const f=await ready();await f.download().fire('click');const before=f.mailboxCalls.length,content=f.record.content;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.download().textContent,f.i.t('communication.source.download'));assert.equal(f.sourceStatus().textContent,f.i.t('communication.source.downloaded'));assert.ok(f.row(f.record.id).textContent.includes(content));assert.deepEqual(Array.from(f.i.missingKeys()),[]);assert.equal(f.mailboxCalls.length,before);}assert.equal(f.created.length,1);});
test('source download rejects mismatched realm, source, revision, byte evidence and unsafe payloads before creating a Blob URL',async()=>{const changes=[v=>delete v.request_context,v=>v.request_context.actor_id='other',v=>v.request_context.tenant_id='other',v=>v.request_context.dealer_id='other',v=>v.source_id='other',v=>v.source_revision++,v=>v.sha256='f'.repeat(64),v=>v.content_base64=Buffer.from('bad').toString('base64'),v=>v.content_base64='!!!!'+v.content_base64.slice(4),v=>v.size_bytes++,v=>v.size_bytes=262145,v=>v.media_type='text/html',v=>v.content_kind='TRUSTED_MESSAGE',v=>v.provider_mutated=true,v=>v.ok=false];let change;const f=await ready({alter:(v,op)=>{if(op==='SOURCE')change?.(v);return v;}});for(change of changes){await f.download().fire('click');assert.equal(f.created.length,0);assert.equal(f.download().disabled,false);assert.equal(f.sourceStatus().textContent,f.i.t('communication.source.invalid'));}change=null;await f.download().fire('click');assert.equal(f.created.length,1);});
test('native source evidence rejects corrupted source association, retained bounds and noncanonical base64 without provider access',async()=>{const f=await ready(),record=f.core.bucket(f.ctx,'messages').find(r=>r.id===f.record.id),item=f.core.adapter.bucket(f.ctx,'communication:mailbox_items').find(r=>r.message_id===record.id),saved={...item},provenance={...record.provenance};for(const damage of [()=>record.provenance.source_sha256='f'.repeat(64),()=>item.retained_bytes=262145,()=>item.raw_base64+='\n',()=>item.raw_base64='!!!!'+item.raw_base64.slice(4),()=>record.provenance.source='MANUAL']){damage();assert.throws(()=>f.service.source(f.ctx,f.actor,record.id),{code:'mailbox_source_unavailable'});Object.assign(item,saved);record.provenance={...provenance};}assert.equal(f.service.source(f.ctx,f.actor,record.id).source_id,record.id);assert.equal(f.reads(),1);});
test('a newer retained message version cannot download under the older opened view; reopening binds the current version',async()=>{const f=await ready(),record=f.core.bucket(f.ctx,'messages').find(r=>r.id===f.record.id);record.revision++;await f.download().fire('click');assert.equal(f.created.length,0);assert.equal(f.sourceStatus().textContent,f.i.t('communication.source.invalid'));await f.render();await f.open(record.id);await f.download().fire('click');assert.equal(f.created.length,1);assert.equal(f.reads(),1);});
test('a held download suppresses duplicate requests, updates loading copy and preserves a newly entered mailbox reason',async()=>{const f=await ready();f.mailboxField('reason').value='PRIVATE new reason';await f.mailboxField('reason').fire('input');const release=f.holdMailbox('SOURCE'),pending=f.download().fire('click');await release.started;await f.download().fire('click');assert.equal(f.mailboxCalls.filter(c=>c.operation==='SOURCE').length,1);for(const locale of locales){f.i.setLocale(locale);assert.equal(f.sourceStatus().textContent,f.i.t('communication.source.downloading'));assert.equal(f.mailboxField('reason').value,'PRIVATE new reason');}release();await pending;assert.equal(f.created.length,1);assert.equal(f.mailboxField('reason').value,'PRIVATE new reason');assert.equal(f.download().disabled,false);});
test('late source responses cannot download after a new inbox view retires their source control',async()=>{const f=await ready(),release=f.holdMailbox('SOURCE'),pending=f.download().fire('click');await release.started;await f.render();release();await pending;assert.equal(f.created.length,0);assert.equal(f.revoked.length,0);});
test('current authorization failure retires the private source view and never exposes raw server errors',async()=>{const f=await ready();f.denyMailbox();await f.download().fire('click');assert.equal(f.created.length,0);assert.ok(!f.content.textContent.includes('RAW_PRIVATE'));assert.ok(!f.content.textContent.includes(f.record.content));});
test('a failed anchor click still removes the link and revokes its Blob URL without claiming download success',async()=>{const f=await ready(),create=f.context.document.createElement;f.context.document.createElement=tag=>{const n=create(tag);if(tag==='a')n.click=()=>{throw Error('RAW_PRIVATE_BROWSER');};return n;};await f.download().fire('click');assert.equal(f.created.length,1);assert.deepEqual(f.revoked,[f.created[0].href]);assert.equal(f.links[0].isConnected,false);assert.equal(f.download().disabled,false);assert.equal(f.sourceStatus().textContent,f.i.t('common.request_failed'));});
