'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{create}=require('../zero-evaluation/commerce-controls-fixture'),commerce=require('../sales-commerce'),{locales}=require('../foundly-locales');
const root='/api/sales/commerce/';
async function fields(f,values){for(const[key,value]of Object.entries(values))await f.set(key,value);}
async function product(f){await f.box.ready;await fields(f,{operation:'PRODUCT_SAVE',product_id:'ui-product',sku:'UI-PRODUCT',name:'Literal product <img>',currency:'EUR',unit_price:'1,01',tax_rate:'21',reason:'Explicit private product intent'});}
async function submit(f){await f.button('preview').fire('click');await f.confirm();await f.button('submit').fire('click');}
const read=(f,entity,id)=>commerce.read(f.native.sales,f.native.ctx,f.native.actor,entity,id);
for(const mode of ['native','zero'])test(mode+' Commerce controls execute the real product/stock/order/fulfilment/return/cancellation cycle with exact conserved native quantities',async()=>{
 const f=create();await f.box.ready;await f.set('transport',mode);await product(f);await submit(f);assert.equal(read(f,'commerce_products','ui-product').unit_price_minor,101,f.box.textContent);
 await fields(f,{operation:'STOCK_RECEIVE',product:'ui-product',quantity:'5',evidence_reference:'Actual internal receipt',reason:'Explicit stock receipt'});await submit(f);assert.equal(read(f,'commerce_inventory','ui-product').available,5,f.box.textContent);
 await fields(f,{operation:'ORDER_RESERVE',product:'ui-product',quantity:'3',order_id:'ui-order',customer_reference:'Actual user reference',reason:'Explicit reservation'});await f.button('add_line').fire('click');await f.button('preview').fire('click');assert.ok(f.box.textContent.includes(f.context.FoundlyI18n.currencyCents(367,'EUR')));await f.confirm();await f.button('submit').fire('click');assert.equal(read(f,'commerce_orders','ui-order').totals.gross_minor,367,f.box.textContent);assert.equal(read(f,'commerce_inventory','ui-product').available,2);
 await fields(f,{operation:'ORDER_FULFILL',order:'ui-order',evidence_reference:'User-attested native delivery',reason:'Explicit fulfilment'});await submit(f);assert.equal(read(f,'commerce_orders','ui-order').status,'FULFILLED',f.box.textContent);
 await fields(f,{operation:'ORDER_RETURN',order:'ui-order',evidence_reference:'Actual return source',reason:'Explicit one-unit return'});const qty=f.box.all().find(n=>n.getAttribute('data-commerce-return')==='ui-product'),dest=f.box.all().find(n=>n.getAttribute('data-commerce-disposition')==='ui-product');qty.value='1';await qty.fire('input');dest.value='RESTOCK';await dest.fire('change');await submit(f);assert.equal(read(f,'commerce_orders','ui-order').status,'PARTIALLY_RETURNED',f.box.textContent);assert.equal(read(f,'commerce_inventory','ui-product').available,3);
 await fields(f,{operation:'ORDER_RESERVE',product:'ui-product',quantity:'1',order_id:'ui-order-cancel',customer_reference:'Actual user reference',reason:'Explicit second reservation'});await f.button('add_line').fire('click');await submit(f);await fields(f,{operation:'ORDER_CANCEL',order:'ui-order-cancel',reason:'Explicit cancellation'});await submit(f);assert.equal(read(f,'commerce_orders','ui-order-cancel').status,'CANCELLED',f.box.textContent);assert.equal(read(f,'commerce_inventory','ui-product').available,3);assert.equal(f.native.rows('invoices').length,0);assert.equal(f.box.canLeave(),true);
 if(mode==='zero')assert.equal(f.calls.filter(c=>c.action&&c.action.operation!=='COMMERCE_RECOVER').length,7);
});
test('reviewed variant attributes, exact prices and confirmation survive all eight locales without turning source text into HTML',async()=>{
 const f=create();await product(f);await f.button('add_attribute').fire('click');const attr=key=>f.box.all().find(n=>n.getAttribute('data-commerce-attribute')===key);attr('key').value='Colour <img>';await attr('key').fire('input');attr('value').value='Literal <script>';await attr('value').fire('input');await f.button('preview').fire('click');await f.confirm();const count=f.calls.length;
 for(const locale of locales){f.context.FoundlyI18n.setLocale(locale);assert.equal(f.calls.length,count);assert.equal(f.field('confirm').checked,true);assert.equal(f.field('unit_price').value,'1,01');assert.ok(f.box.textContent.includes('Literal <script>'));assert.ok(!f.box.all().some(n=>['img','script'].includes(n.tag)));assert.equal(f.context.FoundlyI18n.missingKeys().length,0);}
 await f.button('submit').fire('click');assert.equal(read(f,'commerce_products','ui-product').attributes['Colour <img>'],'Literal <script>');
});
test('lost ZERO product result reloads as an owned pending command and recovers without executing twice',async()=>{
 const f=create();await f.box.ready;await f.set('transport','zero');await product(f);f.lose('/api/zero/turn');await submit(f);assert.equal(read(f,'commerce_products','ui-product').revision,1);assert.equal(f.box.canLeave(),false);f.detach();f.native.restart();const next=create({native:f.native});await next.box.ready;assert.equal(next.button('recover').disabled,false);await next.button('recover').fire('click');assert.equal(read(next,'commerce_products','ui-product').revision,1);assert.equal(next.box.canLeave(),true,next.box.textContent);assert.equal(next.calls.filter(c=>c.route.includes('/actions/')).length,0);
});
test('stale stock revisions fail closed, explicit retirement restores intent, and a new review uses the current stock source',async()=>{
 const f=create();await f.box.ready;await fields(f,{operation:'STOCK_RECEIVE',product:'fixture-product',quantity:'2',evidence_reference:'Authored receipt source',reason:'Authored receipt intent'});await f.button('preview').fire('click');await f.confirm();f.native.run('STOCK_RECEIVE',{product_id:'fixture-product',quantity:1,expected_product_revision:1,expected_revision:3,evidence_reference:'Concurrent actual receipt'},'concurrent-stock');await f.button('submit').fire('click');assert.equal(read(f,'commerce_inventory','fixture-product').on_hand,6);assert.equal(f.button('recover').disabled,false);await f.button('recover').fire('click');assert.equal(f.field('operation').value,'STOCK_RECEIVE');assert.equal(f.field('quantity').value,'2');assert.equal(f.field('reason').value,'Authored receipt intent');assert.equal(f.field('confirm').checked,false);assert.equal(f.box.canLeave(),false);await submit(f);assert.equal(read(f,'commerce_inventory','fixture-product').on_hand,8);assert.equal(f.box.canLeave(),true,f.box.textContent);
});
test('detaching while confirmation is retained cannot execute late; the next view can retire and restore the pending product draft',{timeout:5000},async()=>{
 const f=create();await product(f);await f.button('preview').fire('click');await f.confirm();const release=f.hold(root+'confirmations'),running=f.button('submit').fire('click');await release.started;f.detach();release();await running;assert.throws(()=>read(f,'commerce_products','ui-product'),{statusCode:404});const next=create({native:f.native});await next.box.ready;await next.button('recover').fire('click');assert.equal(next.field('name').value,'Literal product <img>');assert.equal(next.field('unit_price').value,'1.01');await submit(next);assert.equal(read(next,'commerce_products','ui-product').revision,1);
});
test('a tampered committed receipt stays pending until the original native proof is recovered, without another execution',async()=>{
 let altered=false;const f=create({response:(route,data)=>{if(!altered&&route===root+'actions/PRODUCT_SAVE'){altered=true;data.result_snapshot.name='Forged result';}return data;}});await product(f);await submit(f);assert.equal(read(f,'commerce_products','ui-product').revision,1);assert.equal(f.box.canLeave(),false);assert.equal(f.calls.filter(c=>c.route===root+'acknowledge').length,0);await f.button('recover').fire('click');assert.equal(f.box.canLeave(),true);assert.equal(f.calls.filter(c=>c.route===root+'actions/PRODUCT_SAVE').length,1);
});
test('an acknowledged save followed by source-read failure remains saved, and revoked access clears private result text',async()=>{
 for(const status of [503,403]){let acknowledged=false;const f=create({response:(route,data)=>{if(route===root+'acknowledge')acknowledged=true;if(acknowledged&&route.includes('commerce_products?'))throw Object.assign(Error('Unavailable source'),{status});return data;}});await product(f);await submit(f);assert.equal(read(f,'commerce_products','ui-product').revision,1);assert.equal(require('../commerce-action-confirmations').list(f.native.sales,f.native.ctx,f.native.actor).total,0);assert.equal(f.box.canLeave(),true);if(status===403)assert.ok(!f.box.textContent.includes('Literal product'));else assert.ok(f.box.textContent.includes(f.context.FoundlyI18n.t('commerce.controls.saved_refresh')));}
});
test('an existing pending result can be recovered when initial source pagination is unavailable',async()=>{
 const f=create();await product(f);f.lose(root+'actions/PRODUCT_SAVE');await submit(f);f.detach();const next=create({native:f.native,response:(route,data)=>{if(route.includes('commerce_products?'))throw Error('Source unavailable');return data;}});await next.box.ready;assert.equal(next.button('recover').disabled,false);await next.button('recover').fire('click');assert.equal(read(next,'commerce_products','ui-product').revision,1);assert.equal(next.box.canLeave(),true);assert.equal(next.calls.filter(c=>c.route.includes('/actions/')).length,0);
});
test('detaching during native source preparation prevents a late review or write',{timeout:5000},async()=>{
 const f=create();await f.box.ready;await fields(f,{operation:'STOCK_RECEIVE',product:'fixture-product',quantity:'1',evidence_reference:'Explicit source',reason:'Explicit reason'});const release=f.hold(root+'commerce_products/fixture-product'),running=f.button('preview').fire('click');await release.started;f.detach();release();await running;assert.equal(f.button('submit').disabled,true);assert.equal(f.calls.filter(c=>c.route===root+'confirmations'&&c.method==='POST').length,0);assert.equal(read(f,'commerce_inventory','fixture-product').on_hand,5);
});
test('read-only resolution falls back before requesting private write-confirmation metadata',async()=>{
 let fallback=0;const f=create({response:(route,data)=>route==='/api/composition'?{resolution:{capabilities:['sales:quotes'],tools:[]}}:data,onReadOnly:()=>fallback++});await f.box.ready;assert.equal(fallback,1);assert.equal(f.calls.length,1);assert.equal(f.box.canLeave(),true);
});
test('product review requires renewed confirmation after edits and rejects unsafe variant keys and fractional stock',async()=>{
 const f=create();await product(f);await f.button('preview').fire('click');await f.confirm();await f.set('unit_price','2,02');assert.equal(f.field('confirm').checked,false);assert.equal(f.button('submit').disabled,true);await f.button('add_attribute').fire('click');for(const [key,value]of [['key','__proto__'],['value','Invalid']]){const n=f.box.all().find(n=>n.getAttribute('data-commerce-attribute')===key);n.value=value;await n.fire('input');}await f.button('preview').fire('click');assert.equal(f.button('submit').disabled,true);await f.button('clear').fire('click');await fields(f,{operation:'STOCK_RECEIVE',product:'fixture-product',quantity:'1,5',evidence_reference:'Explicit source',reason:'Explicit reason'});await f.button('preview').fire('click');assert.equal(f.button('submit').disabled,true);assert.equal(f.calls.filter(c=>c.method==='POST').length,0);
});
