'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('../zero-evaluation/fixture'),{create}=require('../zero-evaluation/finance-action-page-http-fixture');
async function fill(view,entity,customer,order,number){for(const[key,value]of Object.entries({legal_entity:entity.id,order,contact:customer.id,number,date:'2026-09-26',supply_date:'2026-09-26',due_date:'2026-10-26'}))await view.set(key,value);}
async function submit(view){await view.button('preview').fire('click');await view.confirm();await view.button('submit').fire('click');}
for(const industry of ['AUTOMOTIVE','ECOMMERCE'])test(industry+' production order billing page preserves locked order/CRM sources, routes native and ZERO, and recovers linked drafts after restart and later payment',{timeout:60000},async()=>{
 const s=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/finance-http-faults')});
 try{
  assert.equal((await s.request('/api/composition','PUT',{industry_id:industry,entitlements:['finance','crm','sales'],expected_revision:0})).status,200);
  const member=await s.enroll('commerce.ui.'+industry.toLowerCase(),['SALES','ACCOUNTANT']),financeOnly=await s.enroll('commerce.finance.'+industry.toLowerCase(),['ACCOUNTANT']);
  const call=(route,method='GET',body,headers={})=>s.request(route,method,body,member.cookie,headers);
  const customer=(await call('/api/crm/contacts','POST',{name:'PRIVATE_COMMERCE_UI_CUSTOMER <img>',billing_address:'PRIVATE_COMMERCE_UI_ADDRESS'})).body.record;
  const entity=(await call('/api/finance/legal-entities','POST',{name:'[SYNTHETIC DEMO] Order supplier',legal_form:'BV',address:'Native supplier address',vat_id:'DEMO-NOT-REAL',kvk_number:'DEMO-NOT-REAL',currency:'EUR'})).body;
  assert.equal((await call('/api/finance/periods','POST',{legal_entity_id:entity.id,start_date:'2026-01-01',end_date:'2026-12-31'})).status,201);assert.equal((await call('/api/finance/legal-entities/'+entity.id+'/bootstrap-chart','POST',{})).status,201);
  const commerce=(operation,input)=>call('/api/sales/commerce/actions/'+operation,'POST',{...input,confirm:true,reason:'Explicit native integration source'},{'idempotency-key':crypto.randomUUID()});
  assert.equal((await commerce('PRODUCT_SAVE',{product_id:'ui-commerce-product',sku:'UI-COMMERCE',name:'Original order product',unit_price_minor:101,tax_rate_bps:2100,currency:'EUR',expected_revision:0})).status,200);
  assert.equal((await commerce('STOCK_RECEIVE',{product_id:'ui-commerce-product',quantity:6,expected_revision:1,expected_product_revision:1,evidence_reference:'Native stock fixture'})).status,200);
  for(let i=1;i<=2;i++)assert.equal((await commerce('ORDER_RESERVE',{order_id:'ui-order-'+i,currency:'EUR',customer_reference:'Unverified customer reference',expected_revision:0,lines:[{product_id:'ui-commerce-product',quantity:3,expected_product_revision:1,expected_inventory_revision:i+1}]})).status,200);
  assert.equal((await commerce('PRODUCT_SAVE',{product_id:'ui-commerce-product',sku:'UI-COMMERCE',name:'Later catalog product',unit_price_minor:999,tax_rate_bps:900,currency:'EUR',expected_revision:1})).status,200);
  const limited=await create(s,financeOnly);assert.equal(limited.commerce,undefined);assert.ok(limited.creation);assert.equal(limited.calls.filter(c=>c.route.startsWith('/api/crm/contacts')||c.route.startsWith('/api/sales/commerce/')).length,0);
  const html=await call('/finance');assert.equal(html.status,200);assert.ok(html.body.includes('id="financeCommerceCreate"'));
  let page=await create(s,member);assert.ok(page.commerce);await fill(page.commerce,entity,customer,'ui-order-1','UI-ORDER-NATIVE');await submit(page.commerce);
  let rows=(await call('/api/finance/records/invoices?limit=100')).body.items;assert.equal(rows.length,1,page.commerce.box.textContent);assert.equal(rows[0].gross_cents,367);assert.equal(rows[0].customer_address,'PRIVATE_COMMERCE_UI_ADDRESS');assert.equal(rows[0].status,'DRAFT');assert.ok(page.field('document').children.some(row=>row.value===rows[0].id));assert.equal((await call('/api/finance/records/journal_entries')).body.total,0);
  await page.transport('zero');await fill(page.commerce,entity,customer,'ui-order-2','UI-ORDER-ZERO');page.loseNext('/api/zero/turn');await submit(page.commerce);assert.equal(page.commerce.box.canLeave(),false);assert.ok(page.calls.some(c=>c.body?.client_context?.finance_action?.operation==='COMMERCE_INVOICE_CREATE_EXECUTE'));
  rows=(await call('/api/finance/records/invoices?limit=100')).body.items;assert.equal(rows.length,2);const invoice=rows.find(row=>row.invoice_number==='UI-ORDER-ZERO');assert.equal(invoice.gross_cents,367);
  const pending=(await call('/api/finance/invoice-actions/confirmations?operation=COMMERCE_INVOICE_CREATE')).body;assert.equal(pending.total,1);const command=pending.items[0].command;assert.equal((await s.request('/api/finance/invoice-actions/recover','POST',command,financeOnly.cookie)).status,403);
  for(const view of [page.box,page.creation.box,page.commerce.box])view.isConnected=false;await s.stop();await s.start();member.cookie=await s.login(member);
  assert.equal((await call('/api/finance/invoices/'+invoice.id+'/post','POST',{})).status,200);assert.equal((await call('/api/finance/payments','POST',{invoice_id:invoice.id,amount_cents:367,date:'2026-09-26',reference:'Native internal receipt'})).status,201);
  const {operation,...input}=command,zero=await call('/api/zero/turn','POST',{message:command.reason,conversation_id:crypto.randomUUID(),turn_id:crypto.randomUUID(),client_context:{finance_action:{operation:'COMMERCE_INVOICE_CREATE_RECOVER',input}}});assert.equal(zero.status,200,JSON.stringify(zero.body));assert.equal(zero.body.finance_data.original_result.invoice.status,'DRAFT');assert.equal(zero.body.finance_data.current_invoice.status,'PAID');assert.equal(zero.body.finance_data.current_result.commerce_link.order.invoice_id,invoice.id);
  page=await create(s,member);assert.equal(page.commerce.box.open,true);await page.commerce.button('recover').fire('click');assert.equal(page.commerce.box.canLeave(),true,page.commerce.box.textContent);assert.equal(page.calls.filter(c=>c.route==='/api/finance/invoice-actions/execute').length,0);assert.equal((await call('/api/finance/records/invoices')).body.total,2);assert.equal((await call('/api/finance/records/journal_entries')).body.total,2);assert.equal((await call('/api/finance/records/payments')).body.total,1);
  await fill(page.commerce,entity,customer,'ui-order-2','UI-ORDER-DUPLICATE');await page.commerce.button('preview').fire('click');assert.equal(page.commerce.button('submit').disabled,true);assert.ok(page.commerce.box.textContent.includes(page.context.FoundlyI18n.t('finance.actions.block_order_linked')));
  assert.equal((await s.request('/api/composition','PUT',{industry_id:industry,entitlements:['finance','crm','sales'],capability_flags:{'crm:contacts':false},expected_revision:1})).status,200);await page.context.load(true);assert.equal(page.nodes.financeCommerceCreate.textContent,'');assert.equal(page.nodes.financeCommerceCreate.hidden,true);assert.equal((await call('/api/finance/invoice-actions/recover','POST',command)).status,403);
  const stored=fs.readFileSync(path.join(s.dir,'foundly-core-state.json'),'utf8');assert.ok(!stored.includes('PRIVATE_COMMERCE_UI_CUSTOMER'));assert.ok(!stored.includes('PRIVATE_COMMERCE_UI_ADDRESS'));
 }finally{await s.close();}
});
