'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('../zero-evaluation/fixture'),{create}=require('../zero-evaluation/commerce-page-http-fixture'),{create:financePage}=require('../zero-evaluation/finance-action-page-http-fixture'),{act}=require('../zero-evaluation/finance-action-client-fixture');
async function fields(f,values){for(const[key,value]of Object.entries(values))await f.set(key,value);}
async function submit(f){await f.button('preview').fire('click');await f.confirm();await f.button('submit').fire('click');}
for(const industry of ['AUTOMOTIVE','ECOMMERCE'])test(industry+' actual Sales page creates products/stock/orders through native and ZERO, recovers after restart and invoices the resulting order through the Finance page',{timeout:60000},async()=>{
 const s=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/commerce-http-faults')});
 try{
  assert.equal((await s.request('/api/composition','PUT',{industry_id:industry,entitlements:['sales','finance','crm'],expected_revision:0})).status,200);const member=await s.enroll('commerce.page.'+industry.toLowerCase(),['SALES','ACCOUNTANT']);const call=(route,method='GET',body,headers={})=>s.request(route,method,body,member.cookie,headers);
  const html=await call('/sales');assert.equal(html.status,200);assert.ok(html.body.includes('/commerce-actions-client.js'));const asset=await call('/commerce-actions-client.js');assert.equal(asset.status,200);assert.equal(asset.body,fs.readFileSync(require.resolve('../commerce-actions-client'),'utf8'));
  let page=await create(s,member);await fields(page,{operation:'PRODUCT_SAVE',product_id:'page-product',sku:'PAGE-PRODUCT',name:'PRIVATE_PAGE_PRODUCT <img>',currency:'EUR',unit_price:'1,01',tax_rate:'21',reason:'PRIVATE_PAGE_PRODUCT_REASON'});await submit(page);assert.equal((await call('/api/sales/commerce/commerce_products/page-product')).body.record.unit_price_minor,101,page.box.textContent);
  await page.set('transport','zero');await fields(page,{operation:'STOCK_RECEIVE',product:'page-product',quantity:'5',evidence_reference:'Native received stock',reason:'Explicit stock receipt'});await submit(page);assert.equal((await call('/api/sales/commerce/commerce_inventory/page-product')).body.record.available,5,page.box.textContent);
  await fields(page,{operation:'ORDER_RESERVE',product:'page-product',quantity:'3',order_id:'page-order',customer_reference:'PRIVATE_PAGE_CUSTOMER_REFERENCE',reason:'Explicit new order'});await page.button('add_line').fire('click');await page.button('preview').fire('click');await page.confirm();page.loseNext('/api/zero/turn');await page.button('submit').fire('click');assert.equal(page.box.canLeave(),false);assert.equal((await call('/api/sales/commerce/commerce_orders')).body.total,1);const command=(await call('/api/sales/commerce/confirmations')).body.items[0].command;
  page.box.isConnected=false;await s.stop();await s.start();member.cookie=await s.login(member);assert.equal((await call('/api/sales/commerce/actions/ORDER_FULFILL','POST',{order_id:'page-order',expected_revision:1,evidence_reference:'User-attested fulfilment',confirm:true,reason:'Explicit native fulfilment'},{'idempotency-key':crypto.randomUUID()})).status,200);
  page=await create(s,member,'COMMERCE_ORDERS');await page.button('recover').fire('click');assert.equal(page.box.canLeave(),true,page.box.textContent);assert.equal(page.calls.filter(c=>c.route.includes('/actions/')||c.body?.client_context?.sales_action?.operation==='COMMERCE_ORDER_RESERVE').length,0);assert.equal((await call('/api/sales/commerce/commerce_inventory/page-product')).body.record.on_hand,2);assert.equal((await call('/api/sales/commerce/commerce_inventory/page-product')).body.record.reserved,0);
  const customer=(await call('/api/crm/contacts','POST',{name:'PRIVATE_PAGE_CRM_CUSTOMER',billing_address:'PRIVATE_PAGE_BILLING_ADDRESS'})).body.record,entity=(await call('/api/finance/legal-entities','POST',{name:'[SYNTHETIC DEMO] Integrated supplier',legal_form:'BV',address:'Native supplier address',vat_id:'DEMO-NOT-REAL',kvk_number:'DEMO-NOT-REAL',currency:'EUR'})).body;assert.equal((await call('/api/finance/periods','POST',{legal_entity_id:entity.id,start_date:'2026-01-01',end_date:'2026-12-31'})).status,201);assert.equal((await call('/api/finance/legal-entities/'+entity.id+'/bootstrap-chart','POST',{})).status,201);
  const finance=await financePage(s,member);await finance.transport('zero');await fields(finance.commerce,{legal_entity:entity.id,order:'page-order',contact:customer.id,number:'PAGE-ORDER-INVOICE',date:'2026-09-26',supply_date:'2026-09-26',due_date:'2026-10-26'});await submit(finance.commerce);const invoice=(await call('/api/finance/records/invoices')).body.items[0];assert.equal(invoice.gross_cents,367,finance.commerce.box.textContent);await act(finance,'INVOICE_POST',invoice.id);await act(finance,'PAYMENT_RECORD',invoice.id,{amount:'3,67',date:'2026-09-26',reference:'Native internal receipt'});assert.equal((await call('/api/finance/records/invoices')).body.total,1);assert.equal((await call('/api/finance/records/journal_entries')).body.total,2);assert.equal((await call('/api/finance/records/payments')).body.total,1);
  assert.equal((await call('/api/sales/commerce/recover','POST',command)).body.record.invoice_id,invoice.id);
  await fields(page,{operation:'PRODUCT_SAVE',product:'page-product',name:'UNSAVED_PRIVATE_PAGE_CHANGE',reason:'Explicit pending edit'});assert.equal((await s.request('/api/composition','PUT',{industry_id:industry,entitlements:['sales','finance','crm'],capability_flags:{'sales:quotes':false},expected_revision:1})).status,200);await page.button('preview').fire('click');assert.ok(!page.nodes.contextContent.textContent.includes('PRIVATE_PAGE_PRODUCT'));assert.equal((await call('/api/sales/commerce/confirmations')).status,403);
  const stored=fs.readFileSync(path.join(s.dir,'foundly-core-state.json'),'utf8');for(const marker of ['PRIVATE_PAGE_PRODUCT','PRIVATE_PAGE_CUSTOMER_REFERENCE','PRIVATE_PAGE_CRM_CUSTOMER','PRIVATE_PAGE_BILLING_ADDRESS'])assert.ok(!stored.includes(marker));
 }finally{await s.close();}
});
