'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('../zero-evaluation/commerce-finance-fixture'),commerce=require('../sales-commerce'),retention=require('../commerce-action-confirmations');
const action=()=>({operation:'PRODUCT_SAVE',request_id:'commerce-ui-retain-1',confirm:true,input:{confirm:true,reason:'PRIVATE UI authored reason',product_id:'fixture-product',sku:'FIXTURE',name:'PRIVATE authored product update',currency:'EUR',unit_price_minor:202,tax_rate_bps:2100,expected_revision:1}});
const env=()=>{const f=fixture();return{...f,remember:c=>retention.remember(f.sales,f.ctx,f.actor,c),list:q=>retention.list(f.sales,f.ctx,f.actor,q),ack:c=>retention.acknowledge(f.sales,f.ctx,f.actor,c),execute:c=>commerce.execute(f.sales,f.ctx,f.actor,c.operation,c.input,{idempotency_key:c.request_id}),inspect:c=>commerce.inspect(f.sales,f.ctx,f.actor,c),recover:c=>commerce.recover(f.sales,f.ctx,f.actor,c)};};
test('owned confirmation retention is metadata-only, durable and idempotent; reads cannot retire an unseen request',()=>{
 const f=env(),command=action(),stock=JSON.stringify(commerce.list(f.sales,f.ctx,f.actor,'commerce_inventory')),orders=JSON.stringify(commerce.list(f.sales,f.ctx,f.actor,'commerce_orders'));const retained=f.remember(command);assert.equal(retained.status,'PENDING');assert.equal(retained.source_records_modified,false);assert.deepEqual(retained.command,command);assert.equal(f.remember(command).deduplicated,true);assert.equal(f.list().total,1);assert.equal(f.list().items[0].command.input.reason,command.input.reason);const before=f.snapshot(),persisted=f.persisted.length;assert.equal(f.inspect(command).state,'UNKNOWN');assert.equal(f.snapshot(),before);assert.equal(f.persisted.length,persisted);assert.throws(()=>f.ack(command),{code:'commerce_confirmation_unresolved'});assert.equal(f.list().total,1);
 f.restart();assert.deepEqual(f.list().items[0].command,command);assert.equal(JSON.stringify(commerce.list(f.sales,f.ctx,f.actor,'commerce_inventory')),stock);assert.equal(JSON.stringify(commerce.list(f.sales,f.ctx,f.actor,'commerce_orders')),orders);assert.equal(f.rows('invoices').length,0);
});
test('lost execution and later source changes preserve original/current receipt and acknowledgement never repeats a commerce effect',()=>{
 const f=env(),c=action();f.remember(c);const applied=f.execute(c);assert.equal(applied.record.revision,2);f.restart();f.run('PRODUCT_SAVE',{...c.input,expected_revision:2,name:'Current later native product'},'later-native-product');const result=f.recover(c);assert.equal(result.result_snapshot.name,c.input.name);assert.equal(result.record.name,'Current later native product');assert.equal(result.result_is_current,false);const stock=JSON.stringify(commerce.list(f.sales,f.ctx,f.actor,'commerce_inventory'));assert.equal(f.ack(c).state,'APPLIED');assert.equal(f.list().total,0);assert.equal(f.remember(c).status,'ACKNOWLEDGED');assert.equal(f.execute(c).deduplicated,true);assert.equal(JSON.stringify(commerce.list(f.sales,f.ctx,f.actor,'commerce_inventory')),stock);assert.equal(f.list().total,0);
});
test('retiring a never-executed command blocks a delayed execution or late retention after reload',()=>{
 const f=env(),c=action();f.remember(c);assert.equal(f.recover(c).state,'NOT_APPLIED');assert.equal(f.ack(c).state,'NOT_APPLIED');f.restart();assert.equal(f.remember(c).status,'ACKNOWLEDGED');assert.equal(f.list().total,0);assert.throws(()=>f.execute(c),{code:'commerce_request_abandoned'});
 const late={...action(),request_id:'commerce-late-retention'};assert.equal(f.recover(late).state,'NOT_APPLIED');assert.equal(f.remember(late).status,'ACKNOWLEDGED');assert.equal(f.list().total,0);
});
test('retention and acknowledgement persistence failures roll back their metadata and audit without touching native commerce',()=>{
 const f=env(),c=action(),before=f.snapshot();f.fail(true);assert.throws(()=>f.remember(c),/persistence failure/);f.fail(false);assert.equal(f.snapshot(),before);assert.equal(f.list().total,0);f.remember(c);f.execute(c);const after=f.snapshot();f.fail(true);assert.throws(()=>f.ack(c),/persistence failure/);f.fail(false);assert.equal(f.snapshot(),after);assert.equal(f.list().total,1);f.restart();assert.equal(f.list().total,1);assert.equal(f.ack(c).state,'APPLIED');assert.equal(f.list().total,0);
});
test('owner, tenant, current source access and current module rights protect retained command bodies',()=>{
 const f=env(),c=action();f.remember(c);const stranger={id:'another-seller',roles:['SALES']};assert.equal(retention.list(f.sales,f.ctx,stranger).total,0);assert.throws(()=>retention.remember(f.sales,f.ctx,stranger,c),{statusCode:404});assert.throws(()=>retention.list(f.sales,f.ctx,{...f.actor,roles:['VIEWER']}),{statusCode:403});
 for(const other of [{...f.ctx,tenant_id:'other-tenant'},{...f.ctx,dealer_id:'other-dealer'}]){f.resolver.configure(other,f.admin,{industry_id:'GENERAL',entitlements:['sales'],expected_revision:0});assert.equal(retention.list(f.sales,other,f.actor).total,0);assert.throws(()=>retention.remember(f.sales,other,f.actor,c),{statusCode:404});}
 const original=f.sales.bucket(f.ctx,'commerce_products')[0];original.owner_id=stranger.id;assert.throws(()=>f.list(),{statusCode:404});assert.throws(()=>f.remember(c),{statusCode:404});original.owner_id=f.actor.id;
 f.resolver.configure(f.ctx,f.admin,{entitlements:['finance','sales','crm'],capability_flags:{'sales:quotes':false},expected_revision:1});assert.throws(()=>f.list(),{statusCode:403});assert.throws(()=>f.inspect(c),{statusCode:403});
});
test('tampered commands and reused request IDs fail closed; paging is bounded and malformed input never retains metadata',()=>{
 const f=env(),c=action();f.remember(c);assert.throws(()=>f.remember({...c,input:{...c.input,name:'Different'}}),{code:'commerce_request_conflict'});for(const limit of [0,51,-1,'1x'])assert.throws(()=>f.list({limit}),{code:'commerce_confirmation_invalid'});assert.equal(f.list({limit:'1'}).items.length,1);assert.equal(f.list({cursor:'1',limit:'1'}).items.length,0);assert.throws(()=>f.remember({...c,request_id:'short'}),{code:'commerce_confirmation_invalid'});assert.throws(()=>f.remember({...c,confirm:false}),{code:'commerce_confirmation_invalid'});
 f.shared.bucket(f.ctx,retention.SCOPE)[0].command.input.name='Tampered';assert.throws(()=>f.list(),{code:'commerce_confirmation_invalid'});assert.throws(()=>f.ack(c),{code:'commerce_confirmation_invalid'});
});
