'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('../zero-evaluation/fixture');
test('actual Commerce confirmation routes preserve all native/ZERO action types, lost replies and encrypted restart without duplicate stock',{timeout:60000},async()=>{
 const s=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/commerce-http-faults')});
 try{
  assert.equal((await s.request('/api/composition','PUT',{industry_id:'ECOMMERCE',entitlements:['sales'],expected_revision:0})).status,200);
  const member=await s.enroll('commerce.controls.seller',['SALES']),other=await s.enroll('commerce.controls.other',['SALES']),viewer=await s.enroll('commerce.controls.viewer',['VIEWER']);
  const call=(route,method='GET',body,headers={})=>s.request('/api/sales/commerce/'+route,method,body,member.cookie,headers),record=async(entity,id)=>(await call(entity+'/'+id)).body.record;
  const confirmed={confirm:true,reason:'PRIVATE_COMMERCE_UI_REASON'},command=(operation,input)=>({operation,request_id:crypto.randomUUID(),confirm:true,input:{...confirmed,...input}});
  async function execute(c,zero=false,drop=false){const headers={...(drop?{'x-fixture-commerce-drop':'committed-reply'}:{})};return zero?s.request('/api/zero/turn','POST',{message:c.input.reason,conversation_id:crypto.randomUUID(),turn_id:crypto.randomUUID(),client_context:{sales_action:{operation:'COMMERCE_'+c.operation,input:c.input,request_id:c.request_id}}},member.cookie,headers):call('actions/'+c.operation,'POST',c.input,{...headers,'idempotency-key':c.request_id});}
  async function retain(c){const r=await call('confirmations','POST',c);assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.status,'PENDING');assert.equal(r.body.source_records_modified,false);}
  async function ack(c,state='APPLIED'){const r=await call('acknowledge','POST',c);assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.state,state);assert.equal((await call('confirmations')).body.total,0);}
  const product=command('PRODUCT_SAVE',{product_id:'commerce-ui-product',sku:'COMMERCE-UI',name:'PRIVATE_COMMERCE_UI_PRODUCT',currency:'EUR',unit_price_minor:101,tax_rate_bps:2100,expected_revision:0});await retain(product);
  assert.equal((await s.request('/api/sales/commerce/confirmations','GET',undefined,other.cookie)).body.total,0);assert.equal((await s.request('/api/sales/commerce/confirmations','GET',undefined,viewer.cookie)).status,403);assert.equal((await call('inspect','POST',product)).body.state,'UNKNOWN');assert.equal((await call('acknowledge','POST',product)).status,409);
  await assert.rejects(execute(product,true,true));await s.stop();await s.start();member.cookie=await s.login(member);assert.equal((await call('confirmations')).body.items[0].command.request_id,product.request_id);assert.equal((await call('recover','POST',product)).body.result_snapshot.name,product.input.name);await ack(product);assert.equal((await call('confirmations','POST',product)).body.status,'ACKNOWLEDGED');
  const stock=command('STOCK_RECEIVE',{product_id:'commerce-ui-product',quantity:5,expected_revision:1,expected_product_revision:1,evidence_reference:'Native received stock'});await retain(stock);await assert.rejects(execute(stock,false,true));await s.stop();await s.start();member.cookie=await s.login(member);assert.equal((await call('recover','POST',stock)).body.state,'APPLIED');await ack(stock);assert.equal((await record('commerce_inventory','commerce-ui-product')).on_hand,5);
  const reserve=command('ORDER_RESERVE',{order_id:'commerce-ui-order',currency:'EUR',customer_reference:'PRIVATE_COMMERCE_UI_REFERENCE',expected_revision:0,lines:[{product_id:'commerce-ui-product',quantity:3,expected_product_revision:1,expected_inventory_revision:2}]});await retain(reserve);assert.equal((await execute(reserve)).status,200);await ack(reserve);assert.equal((await record('commerce_orders','commerce-ui-order')).totals.gross_minor,367);
  const fulfill=command('ORDER_FULFILL',{order_id:'commerce-ui-order',expected_revision:1,evidence_reference:'Internal user-attested fulfilment'});await retain(fulfill);assert.equal((await execute(fulfill,true)).status,200);await ack(fulfill);
  const returned=command('ORDER_RETURN',{order_id:'commerce-ui-order',expected_revision:2,evidence_reference:'Native return source',lines:[{product_id:'commerce-ui-product',quantity:1,disposition:'RESTOCK'}]});await retain(returned);assert.equal((await execute(returned,true)).status,200);await ack(returned);assert.equal((await record('commerce_inventory','commerce-ui-product')).available,3);
  const second=command('ORDER_RESERVE',{...reserve.input,order_id:'commerce-ui-order-cancel',lines:[{product_id:'commerce-ui-product',quantity:1,expected_product_revision:1,expected_inventory_revision:5}]});await retain(second);assert.equal((await execute(second)).status,200);await ack(second);
  const cancel=command('ORDER_CANCEL',{order_id:'commerce-ui-order-cancel',expected_revision:1});await retain(cancel);assert.equal((await execute(cancel,true)).status,200);await ack(cancel);assert.equal((await record('commerce_inventory','commerce-ui-product')).available,3);
  const never=command('PRODUCT_SAVE',{...product.input,product_id:'never-created',sku:'NEVER',expected_revision:0});await retain(never);assert.equal((await call('recover','POST',never)).body.state,'NOT_APPLIED');await ack(never,'NOT_APPLIED');assert.equal((await execute(never)).status,409);assert.equal((await call('commerce_products')).body.total,1);assert.equal((await call('commerce_movements')).body.total,6);
  const raw=fs.readFileSync(path.join(s.dir,'foundly-core-state.json'),'utf8');for(const marker of ['PRIVATE_COMMERCE_UI_REASON','PRIVATE_COMMERCE_UI_PRODUCT','PRIVATE_COMMERCE_UI_REFERENCE'])assert.ok(!raw.includes(marker));
  assert.equal((await s.request('/api/composition','PUT',{industry_id:'ECOMMERCE',entitlements:['sales'],capability_flags:{'sales:quotes':false},expected_revision:1})).status,200);assert.equal((await call('confirmations')).status,403);assert.equal((await call('inspect','POST',product)).status,403);assert.equal((await call('acknowledge','POST',product)).status,403);
 }finally{await s.close();}
});
