'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/crm-objects-fixture'),{locales}=require('../foundly-i18n');
test('CRM custom-object source rows localize framing and exact negative money while preserving literal source names',async()=>{
 const f=await fixture(),calls=f.calls.length,card=f.box.all().find(n=>n.tag==='article');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,calls);assert.ok(f.box.textContent.includes('Private literal object'));assert.ok(f.box.textContent.includes('Private literal record'));assert.ok(card.textContent.includes(f.i.currencyCents(-123,'USD')));assert.ok(card.textContent.includes(f.i.t('crm.objects.record_heading',{id:f.record.id,revision:f.i.number(1)})));assert.ok(f.box.textContent.includes(f.i.t('crm.objects.count',{count:1})));assert.equal(f.i.missingKeys().length,0);}
});
test('CRM custom-object record and schema controls retain authored values and nodes through all locale changes',async()=>{
 const f=await fixture();await f.button('Record bewerken').fire('click');const title=f.field('Private literal title'),currency=f.field('Private literal amount (valutacode)'),amount=f.field('Private literal amount (bedrag in centen)');title.value='Literal authored <img> title';amount.value='-234';const calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,calls);assert.equal(f.field('Private literal title'),title);assert.equal(title.value,'Literal authored <img> title');assert.equal(amount.value,'-234');assert.equal(currency.value,'USD');assert.ok(f.box.textContent.includes(f.i.t('crm.objects.save_record')));}
 await f.button('Nieuw objecttype').fire('click');const name=f.field('Objectnaam'),code=f.field('Objectcode'),fieldLabel=f.field('Veldlabel'),type=f.field('Veldtype');name.value='Literal object name';code.value='literal_object_code';fieldLabel.value='Literal authored field label';const before=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(name.value,'Literal object name');assert.equal(fieldLabel.value,'Literal authored field label');assert.equal(code.value,'literal_object_code');assert.equal(type.value,'TEXT');assert.ok(f.box.textContent.includes(f.i.t('crm.objects.field_type')));assert.equal(f.calls.length,before);}
});
test('CRM custom-object history localizes revision framing without replaying source requests',async()=>{
 const f=await fixture();await f.button('Historie bekijken').fire('click');const calls=f.calls.length,heading=f.box.all().find(n=>n.tag==='h4');for(const locale of locales){f.i.setLocale(locale);assert.equal(heading.textContent,f.i.t('crm.objects.revision',{revision:f.i.number(1)}));assert.ok(f.box.textContent.includes('Private literal record'));assert.equal(f.calls.length,calls);}
});
test('CRM custom-object access and archive retries preserve explicit confirmation, reason and source revision',async()=>{
 for(const type of ['access','archive']){const f=await fixture();await f.button(type==='access'?'Recordtoegang':'Record archiveren').fire('click');const reason=f.field(type==='access'?'Reden voor toegangsverandering':'Reden voor archiveren of herstellen'),confirm=f.field(type==='access'?'Ik bevestig deze toegangsverandering':'Ik bevestig deze archiefwijziging');reason.value='Original explicit reason';confirm.checked=true;if(type==='access')f.field('Team-ID (leeg maakt privé)').value='literal_team';const form=reason.closest('form');await form.fire('input');f.lose();await form.fire('submit');const calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,calls);assert.equal(confirm.checked,true);assert.ok(f.box.textContent.includes(f.i.t('crm.objects.write_unconfirmed')));}reason.value='Must not replace original';confirm.checked=false;await form.fire('submit');assert.equal(f.writes.length,2);assert.deepEqual(f.writes[1],f.writes[0]);assert.equal(f.core.rows(f.ctx,'records')[0].revision,2);}
});
test('CRM custom-object missing write acknowledgement retains the exact save until confirmed',async()=>{
 const f=await fixture();await f.button('Record bewerken').fire('click');const title=f.field('Private literal title'),form=title.closest('form');title.value='Committed with lost acknowledgement';f.malformed();await form.fire('submit');assert.equal(title.disabled,true);assert.ok(f.box.textContent.includes(f.i.t('crm.objects.write_unconfirmed')));await form.fire('submit');assert.deepEqual(f.writes[1],f.writes[0]);assert.equal(f.core.listRecords(f.ctx,f.actor,f.definition.id).items[0].revision,2);
});
test('CRM custom-object denied-source feedback remains classified and localized',async()=>{
 const f=await fixture();f.deny();await f.box.refresh();const calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.ok(f.box.textContent.includes(f.i.t('crm.objects.forbidden')));assert.ok(!f.box.textContent.includes('PRIVATE RAW'));assert.equal(f.calls.length,calls);}
});
