'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {create,locales}=require('../foundly-i18n'),{FoundlyCrmCore}=require('../crm-core');
function formatter(){const source=fs.readFileSync(require.resolve('../crm-script.js'),'utf8'),start=source.indexOf('function formatMetric('),end=source.indexOf('\nfunction ',start+1),context={FoundlyI18n:create('en-GB'),Intl};assert.ok(start>=0&&end>start);vm.createContext(context);vm.runInContext(source.slice(start,end),context);return context;}
test('CRM metric presentation rejects truthy availability and coerced boolean or string amounts',()=>{
 const f=formatter();for(const metric of [{available:'true',value:50},{available:true,value:false},{available:true,value:true},{available:true,value:'1234'}])assert.equal(f.formatMetric(metric).available,false);
});
test('CRM metric presentation cannot invent EUR when the native metric supplies no currency',()=>{
 const f=formatter(),metric=f.formatMetric({available:true,value:1234.5,unit:'currency'});assert.ok(!metric.value.includes('€'));assert.equal(metric.unit,f.FoundlyI18n.t('crm.dashboard.currency_unknown'));
});
test('native CRM comparison keeps missing ratio values unknown while preserving legitimate count changes from zero',()=>{
 const stores=new Map(),ctx={tenant_id:'comparison_tenant',dealer_id:'comparison_dealer'},actor={id:'actor',roles:['ADMIN']};let id=0;const core=new FoundlyCrmCore({bucket:(context,name)=>{const key=context.tenant_id+':'+context.dealer_id+':'+name;if(!stores.has(key))stores.set(key,[]);return stores.get(key);},persist(){},emit(){},id:()=> 'comparison_'+(++id),now:()=>new Date('2026-09-04T09:00:00Z')});core.create(ctx,actor,'leads',{name:'Literal current-period lead'});
 const result=core.analyticsWithComparison(ctx,actor,{from:'2026-09-01T00:00:00Z',to:'2026-09-05T23:59:59Z',compare:true});assert.equal(result.comparison.metrics.leads.absolute_delta,1);const conversion=result.comparison.metrics.conversion;assert.equal(conversion.current,0);assert.equal(conversion.previous,null);assert.equal(conversion.absolute_delta,null);assert.equal(conversion.percent_delta,null);assert.equal(conversion.available,false);
});
test('CRM metrics retain explicit currency, percentage, elapsed units and genuine zero in all eight locales',()=>{
 const f=formatter();for(const locale of locales){f.FoundlyI18n.setLocale(locale);assert.equal(f.formatMetric({available:true,value:-1234.56,unit:'currency',currency:'USD'}).value,new Intl.NumberFormat(locale,{style:'currency',currency:'USD',maximumFractionDigits:2}).format(-1234.56));assert.equal(f.formatMetric({available:true,value:12.5,unit:'percent'}).value,new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:1}).format(0.125));assert.equal(f.formatMetric({available:true,value:1.5,unit:'hours'}).value,new Intl.NumberFormat(locale,{style:'unit',unit:'hour',unitDisplay:'short',maximumFractionDigits:1}).format(1.5));assert.equal(f.formatMetric({available:true,value:0,unit:'count'}).value,new Intl.NumberFormat(locale).format(0));assert.equal(f.formatMetric({available:true,value:1234.5,unit:'currency'}).unit,f.FoundlyI18n.t('crm.dashboard.currency_unknown'));assert.equal(f.formatMetric({available:true,value:5,unit:'Literal unit'}).unit,'Literal unit');for(const value of [-1,0.5,Number.MAX_SAFE_INTEGER+1])assert.equal(f.formatMetric({available:true,value,unit:'count'}).available,false);assert.equal(f.FoundlyI18n.missingKeys().length,0);}
});
test('native CRM comparisons preserve observed zero ratios and valid differences without dividing by zero',()=>{
 const stores=new Map(),ctx={tenant_id:'observed_comparison_tenant',dealer_id:'comparison_dealer'},actor={id:'actor',roles:['ADMIN']};let id=0,clock='2026-08-29T09:00:00Z';const core=new FoundlyCrmCore({bucket:(context,name)=>{const key=context.tenant_id+':'+context.dealer_id+':'+name;if(!stores.has(key))stores.set(key,[]);return stores.get(key);},persist(){},emit(){},id:()=> 'observed_'+(++id),now:()=>new Date(clock)});
 core.create(ctx,actor,'leads',{name:'Literal previous-period lead'});clock='2026-09-04T09:00:00Z';const lead=core.create(ctx,actor,'leads',{name:'Literal current-period lead'}),range={from:'2026-09-01T00:00:00Z',to:'2026-09-05T23:59:59Z',compare:true};let result=core.analyticsWithComparison(ctx,actor,range);assert.equal(result.comparison.metrics.conversion.available,true);assert.equal(result.comparison.metrics.conversion.absolute_delta,0);assert.equal(result.comparison.metrics.conversion.percent_delta,null);
 core.create(ctx,actor,'deals',{title:'Literal linked deal',lead_id:lead.id,status:'WON',value:100});result=core.analyticsWithComparison(ctx,actor,range);assert.equal(result.comparison.metrics.conversion.current,100);assert.equal(result.comparison.metrics.conversion.previous,0);assert.equal(result.comparison.metrics.conversion.absolute_delta,100);assert.equal(result.comparison.metrics.conversion.percent_delta,null);
});
