'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('../zero-evaluation/crm-dashboard-fixture');
const surfaces=[['records','recordRows',f=>f.context.loadRecords(),'/api/crm/leads?'],['pipeline','pipelineBoard',f=>f.context.loadPipelineBoard('literal_pipeline'),'/api/crm/pipelines/'],['customer','customer360',f=>f.context.openCustomer('literal_record'),'/api/crm/customers/'],['automation','automationList',f=>f.context.loadAutomations(),'/api/crm/automations?']];
for(const [name,id,load,route]of surfaces){
 test('CRM '+name+' source is cleared when current access is denied',async()=>{const f=fixture();await load(f);assert.ok(f.nodes[id].textContent.includes('Literal private'));f.deny();await assert.rejects(f.context.loadStatus());assert.ok(!f.nodes[id].textContent.includes('Literal private'));if(name==='customer')assert.equal(f.nodes.customerDialog.open,false);});
 test('CRM late '+name+' response cannot restore private data after a newer denial',async()=>{const f=fixture();const release=f.hold(route),pending=load(f);await release.started;f.deny();await assert.rejects(f.context.loadStatus());release();await pending;assert.ok(!f.nodes[id].textContent.includes('Literal private'));if(name==='customer')assert.notEqual(f.nodes.customerDialog.open,true);});
}
test('CRM a closed customer dialog stays closed when its pending source reply arrives',async()=>{const f=fixture(),release=f.hold('/api/crm/customers/'),pending=f.context.openCustomer('literal_record');await release.started;f.nodes.customerDialog.close();release();await pending;assert.notEqual(f.nodes.customerDialog.open,true);assert.ok(!f.nodes.customer360.textContent.includes('Literal private'));});
test('CRM late ZERO replies cannot restore private answers or run navigation commands after access denial',async()=>{const f=fixture();let navigated=0;f.context.runUiCommands=()=>navigated++;f.nodes.zeroInput.value='Literal authored question';const release=f.hold('/api/zero/turn'),pending=f.context.runZero({preventDefault(){}});await release.started;f.deny();await assert.rejects(f.context.loadStatus());release();await pending;assert.ok(!f.nodes.zeroOutput.textContent.includes('Literal private'));assert.equal(navigated,0);});
const {locales}=require('../foundly-i18n');
test('CRM older entity and pipeline reads cannot replace a newer selection',async()=>{
 const f=fixture();const release=f.hold('/api/crm/leads?'),pending=f.context.loadRecords();await release.started;f.nodes.recordEntity.value='contacts';f.records.items[0].name='Literal newer contact';await f.context.loadRecords();release();await pending;assert.ok(f.nodes.recordRows.textContent.includes('Literal newer contact'));assert.ok(!f.nodes.recordRows.textContent.includes('Literal private record'));
 f.board.board.pipeline.id='literal_old';const boardRelease=f.hold('/api/crm/pipelines/literal_old/'),boardPending=f.context.loadPipelineBoard('literal_old');await boardRelease.started;f.board.board.pipeline.id='literal_new';f.board.board.stages[0].name='Literal newer stage';await f.context.loadPipelineBoard('literal_new');boardRelease();await boardPending;assert.ok(f.nodes.pipelineBoard.textContent.includes('Literal newer stage'));assert.ok(!f.nodes.pipelineBoard.textContent.includes('Literal private stage'));
});
test('CRM malformed list responses remain unavailable while genuine empty lists remain observed empty data',async()=>{
 const f=fixture();delete f.records.items;delete f.pipelines.items;delete f.automations.items;await f.context.loadRecords();await f.context.loadPipelines();await f.context.loadAutomations();for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.recordEmpty.textContent,f.i.t('common.no_data'));assert.equal(f.nodes.pipelineBoard.textContent,f.i.t('common.no_data'));assert.equal(f.nodes.automationList.textContent,f.i.t('common.no_data'));}f.pipelines.items=[];await f.context.loadPipelines();for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.pipelineBoard.textContent,f.i.t('crm.dashboard.pipelines_empty'));}
});
test('CRM ZERO pending progress localizes without duplicate requests, losing a newer draft or translating the literal answer',async()=>{
 const f=fixture();f.nodes.zeroInput.value='Literal authored question';const release=f.hold('/api/zero/turn'),pending=f.context.runZero({preventDefault(){}});await release.started;const before=f.calls.length;await f.context.runZero({preventDefault(){}});assert.equal(f.calls.length,before);for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.zeroOutput.textContent,f.i.t('crm.dashboard.zero_loading'));assert.equal(f.nodes.zeroInput.value,'Literal authored question');assert.equal(f.calls.length,before);}f.nodes.zeroInput.value='Literal newer draft';release();await pending;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.zeroOutput.textContent,'Literal private ZERO answer');assert.equal(f.nodes.zeroInput.value,'Literal newer draft');}assert.equal(JSON.parse(f.calls[0].options.body).message,'Literal authored question');
});
test('CRM failed ZERO requests keep the authored question and classify raw errors in every locale',async()=>{
 const f=fixture();f.nodes.zeroInput.value='Literal failed question';f.errors.set('/api/zero/turn',500);await f.context.runZero({preventDefault(){}});for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.zeroOutput.textContent,f.i.t('common.request_failed'));assert.equal(f.nodes.toast.textContent,f.i.t('common.request_failed'));assert.equal(f.nodes.zeroInput.value,'Literal failed question');assert.equal(f.i.missingKeys().length,0);}
});
test('CRM record editor keeps its original entity even if the surrounding list changes before save',async()=>{
 const {CrmView}=require('../zero-evaluation/crm-dashboard-fixture'),f=fixture(),form=f.nodes.recordForm;form.elements=Object.fromEntries(['name','id','revision','status','email','phone','value','probability','owner_id','team_id','source_id','channel','direction','note','next_action_at'].map(k=>[k,new CrmView('input')]));f.nodes['recordForm [name="name"]']=form.elements.name;f.context.FormData=class{constructor(form){this.form=form;}entries(){return Object.entries(this.form.elements).map(([k,n])=>[k,n.value]);}};await f.context.loadRecords();f.context.openRecordDialog(f.records.items[0]);f.nodes.recordEntity.value='contacts';await f.context.loadRecords();await f.context.saveRecord({preventDefault(){},currentTarget:form});const write=f.calls.find(c=>c.options?.method==='PATCH');assert.equal(write.route,'/api/crm/leads/literal_record');assert.equal(JSON.parse(write.options.body).name,'Literal private record');
});
test('CRM denial closes record and native-field source editors and clears mounted private content',async()=>{
 const {CrmView}=require('../zero-evaluation/crm-dashboard-fixture'),f=fixture();f.nodes.recordForm.elements={name:new CrmView('input')};f.nodes.recordForm.elements.name.value='Literal private edited name';f.nodes.recordDialog.showModal();f.nodes.nativeFieldsDialog.showModal();f.nodes.nativeFieldsWorkspace.append(new CrmView());f.nodes.nativeFieldsWorkspace.children[0].textContent='Literal private field';f.deny();await assert.rejects(f.context.loadStatus());assert.equal(f.nodes.recordDialog.open,false);assert.equal(f.nodes.nativeFieldsDialog.open,false);assert.equal(f.nodes.recordForm.elements.name.value,'');assert.equal(f.nodes.nativeFieldsWorkspace.textContent,'');
});
test('CRM automation save captures its form before the browser clears event.currentTarget after dispatch',async()=>{
 const f=fixture(),form=f.nodes.automationForm;let target=form,reset=false;form.reset=()=>reset=true;f.context.FormData=class{constructor(form){assert.ok(form);}entries(){return [['name','Literal authored automation'],['trigger','new_lead'],['action','task']];}};const release=f.hold('/api/crm/automations'),pending=f.context.saveAutomation({preventDefault(){},get currentTarget(){return target;}});await release.started;target=null;release();await pending;assert.equal(reset,true);assert.equal(JSON.parse(f.calls.find(c=>c.options?.method==='POST').options.body).name,'Literal authored automation');
});
