'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture:storage}=require('../zero-evaluation/crm-save-fixture');
function fixture(){const f=storage(),received=new Map();let down=true,lose=false,ack=true,clock=Date.parse('2026-09-24T12:00:00Z');f.core.adapter.now=()=>new Date(clock);f.actor.roles=['MANAGER'];const publish=(ctx,event)=>{if(down)throw Object.assign(Error('PRIVATE provider failure'),{code:'event_sink_down'});received.set(event.event_id,JSON.parse(JSON.stringify(event)));if(lose){lose=false;throw Error('lost delivery acknowledgement');}return ack?{event_id:event.event_id}:undefined;};f.core.adapter.publish=publish;f.core.adapter.emit=publish;return {...f,received,up(){down=false;clock+=60000;},advance(){clock+=60000;},lose(){lose=true;},noAck(){ack=false;},queue:()=>f.core.adapter.bucket(f.ctx,'crm:event_outbox'),retry:()=>f.core.retryEvents(f.ctx,f.actor)};}
test('CRM committed record and its event survive a sink outage and exact replay after restart',()=>{
 const f=fixture(),input={name:'Literal CRM source'},options={idempotencyKey:'crm-outbox-create'};try{f.core.create(f.ctx,f.actor,'leads',input,options);}catch{}assert.equal(f.core.list(f.ctx,f.actor,'leads').total,1);f.restart();f.up();const replay=f.core.create(f.ctx,f.actor,'leads',input,options);assert.equal(replay.idempotent_replay,true);assert.equal(f.received.size,1);assert.equal(f.queue().filter(row=>row.status==='PENDING').length,0);f.core.create(f.ctx,f.actor,'leads',input,options);assert.equal(f.received.size,1);
});
test('CRM event snapshot keeps original value, unknown fields, source revision and currency while delivery is delayed',()=>{
 const f=fixture(),deal=f.core.create(f.ctx,f.actor,'deals',{title:'Original deal',value:12.34,currency:'USD'});f.core.update(f.ctx,f.actor,'deals',deal.id,{value:20,currency:'GBP'},{expectedRevision:deal.revision});f.up();f.retry();assert.equal(f.received.size,2);const events=[...f.received.values()].map(row=>row.canonical);assert.equal(events[0].properties.value_cents,1234);assert.equal(events[0].properties.currency,'USD');assert.equal(events[0].properties.weighted_value_cents,null);assert.equal(events[1].properties.value_cents,2000);assert.equal(events[1].properties.currency,'GBP');assert.equal(events[0].properties.revision,1);assert.equal(events[1].properties.revision,2);
});
test('CRM lost sink acknowledgement retries one stable event identity without duplicate mutation',()=>{
 const f=fixture();f.up();f.lose();const row=f.core.create(f.ctx,f.actor,'leads',{name:'Literal lead'},{idempotencyKey:'crm-outbox-lost-ack'});assert.equal(f.received.size,1);assert.equal(f.queue()[0].status,'PENDING');f.restart();f.retry();assert.equal(f.received.size,1);assert.equal(f.queue()[0].status,'DELIVERED');assert.equal(f.core.get(f.ctx,f.actor,'leads',row.id).revision,1);
});
test('CRM outbox acknowledgement failure restores pending status and sink callbacks cannot mutate the durable envelope',()=>{
 const f=fixture();f.up();let writes=0;const persist=f.core.adapter.persist;f.core.adapter.persist=()=>{if(++writes===2)throw Error('ack persistence failed');persist();};f.core.adapter.publish=(ctx,event)=>{f.received.set(event.event_id,event.canonical.properties.revision);event.canonical.properties.revision=999;return {event_id:event.event_id};};f.core.create(f.ctx,f.actor,'leads',{name:'Literal lead'});assert.equal(f.queue()[0].status,'PENDING');assert.equal(f.queue()[0].event.canonical.properties.revision,1);f.core.adapter.persist=persist;f.restart();f.retry();assert.equal(f.queue()[0].status,'DELIVERED');assert.equal(f.received.size,1);
});
test('CRM does not acknowledge missing delivery evidence or expose pending payloads to an unauthorized caller',()=>{
 const f=fixture();f.up();f.noAck();f.core.create(f.ctx,f.actor,'leads',{name:'Literal private lead'});assert.equal(f.queue()[0].status,'PENDING');f.actor.roles=['VIEWER'];assert.throws(()=>f.retry(),e=>e.statusCode===403);assert.ok(!JSON.stringify(f.queue()).includes('PRIVATE provider failure'));
});
test('CRM persistence failure leaves neither mutation nor pending event and pending capacity rejects safely',()=>{
 const f=fixture();f.fail(true);assert.throws(()=>f.core.create(f.ctx,f.actor,'leads',{name:'Never persisted'}),/persistence failure/);assert.equal(f.queue().length,0);assert.equal(f.core.list(f.ctx,f.actor,'leads').total,0);f.fail(false);f.queue().push(...Array.from({length:25000},(_,n)=>({event:{event_id:'pending_'+n},status:'PENDING'})));const before=f.snapshot();assert.throws(()=>f.core.create(f.ctx,f.actor,'leads',{name:'Over capacity'}),e=>e.code==='crm_event_capacity');assert.equal(f.snapshot(),before);
});
test('CRM automatic delivery backs off, stops at five attempts and allows an authorized bounded retry',()=>{
 const f=fixture();f.core.create(f.ctx,f.actor,'leads',{name:'Pending lead'});assert.equal(f.queue()[0].attempts,1);assert.equal(f.core.retryEvents(f.ctx,f.actor,{automatic:true}).attempted,0);
 for(let n=1;n<5;n++){f.advance();assert.equal(f.core.retryEvents(f.ctx,f.actor,{automatic:true}).attempted,1);}f.advance();assert.equal(f.core.retryEvents(f.ctx,f.actor,{automatic:true}).automatic_retries_exhausted,1);assert.equal(f.queue()[0].attempts,5);f.up();assert.equal(f.retry().delivered,1);assert.equal(f.received.size,1);
});
test('CRM retry limits one batch to fifty events and cannot cross its tenant scope',()=>{
 const f=fixture();for(let n=0;n<52;n++)f.core.create(f.ctx,f.actor,'leads',{name:'Pending '+n});const other={...f.ctx,tenant_id:'other_tenant'};f.core.create(other,f.actor,'leads',{name:'Other tenant lead'});f.up();assert.equal(f.retry().attempted,50);assert.equal(f.retry().attempted,2);assert.equal(f.received.size,52);assert.ok([...f.received.values()].every(row=>row.canonical.tenant_id===f.ctx.tenant_id));assert.equal(f.core.adapter.bucket(other,'crm:event_outbox')[0].status,'PENDING');
});
test('CRM background eligibility preserves native manage and read authority',()=>{
 const {canRetryCrmEvents}=require('../crm-core');for(const roles of [['SALES'],['VIEWER'],['MARKETING'],[]])assert.equal(canRetryCrmEvents({roles}),false);assert.equal(canRetryCrmEvents({roles:['MANAGER']}),true);assert.equal(canRetryCrmEvents({roles:[],permissions:['crm:manage']}),false);assert.equal(canRetryCrmEvents({roles:[],permissions:['crm:manage','crm:read_assigned']}),true);
});
