'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture:storage}=require('../zero-evaluation/crm-save-fixture');
function fixture(){const f=storage();f.actor.roles=['MANAGER'];const c=f.core,ctx=f.ctx,a=f.actor,user=c.create(ctx,a,'users',{name:'Literal assignee'}),pipeline=c.create(ctx,a,'pipelines',{name:'Literal pipeline'}),stage=c.create(ctx,a,'stages',{name:'Literal target stage',pipeline_id:pipeline.id,probability:60,status:'OPEN'}),deal=c.create(ctx,a,'deals',{title:'Literal target deal',pipeline_id:pipeline.id,value:10,currency:'USD'});return {...f,user,pipeline,stage,deal,event:{id:'native-effects-event',type:'new_lead',entity:'deals',record_id:deal.id,record:{value:9999,owner_id:'forged-owner'}},define(actions,trigger='new_lead'){return c.create(ctx,a,'automations',{name:'Literal effects definition',trigger:{type:trigger},actions});},run(){return c.evaluateAutomations(ctx,a,this.event);}};}
const action=(type,extra={})=>({type,execution_mode:'AUTOMATIC_INTERNAL',target_entity:'deals',...extra});
test('native CRM verified assignment, field and stage effects commit once using actual source data',()=>{
 const f=fixture();f.define([action('assign',{owner_id:f.user.id}),action('field_update',{field:'value',value:20}),action('stage_change',{stage_id:f.stage.id})]);const writes=f.count(),result=f.run(),row=f.core.get(f.ctx,f.actor,'deals',f.deal.id);assert.equal(result.executions[0].status,'COMPLETED');assert.equal(row.owner_id,f.user.id);assert.equal(row.value,20);assert.equal(row.stage_id,f.stage.id);assert.equal(row.probability,60);assert.equal(row.currency,'USD');assert.equal(row.revision,4);assert.equal(f.count(),writes+1);assert.deepEqual(result.executions[0].actions.map(a=>a.record_entity),['deals','deals','deals']);f.restart();const before=f.snapshot();assert.equal(f.run().replayed,true);assert.equal(f.snapshot(),before);
});
test('native CRM effects reject private or missing targets before any task or audit survives',()=>{
 for(const denied of ['missing','private']){const f=fixture();f.define([{type:'task',title:'Must roll back'},action('field_update',{field:'status',value:'QUALIFIED'})]);f.actor.roles=[];f.actor.permissions=['crm:automate','crm:read_assigned','crm:write_assigned'];if(denied==='missing')f.event.record_id='missing-source';else f.core.collection(f.ctx,'deals')[0].owner_id='private-other';const before=f.snapshot();assert.throws(()=>f.run(),e=>[403,404].includes(e.statusCode));assert.equal(f.snapshot(),before);assert.equal(f.core.list(f.ctx,f.actor,'tasks').total,0);}
});
test('native CRM automation permission alone cannot create tasks or update records',()=>{
 for(const actions of [[{type:'task',title:'Unauthorized task'}],[action('field_update',{field:'status',value:'OPEN'})]]){const f=fixture();f.define(actions);f.actor.roles=[];f.actor.permissions=['crm:automate','crm:read_all'];const before=f.snapshot();assert.throws(()=>f.run(),e=>e.statusCode===403);assert.equal(f.snapshot(),before);}
});
test('native CRM follow-up tasks use an authorized native source and ignore supplied owner claims',()=>{
 const f=fixture();f.define([{type:'task',title:'Literal native follow-up'}]);f.run();const task=f.core.list(f.ctx,f.actor,'tasks').items[0];assert.equal(task.owner_id,f.actor.id);assert.equal(task.related_id,f.deal.id);f.actor.roles=[];f.actor.permissions=['crm:automate','crm:read_assigned','crm:write_assigned'];f.core.collection(f.ctx,'deals')[0].owner_id='private-other';assert.throws(()=>f.run(),e=>e.statusCode===404);const before=f.snapshot();assert.throws(()=>f.core.evaluateAutomations(f.ctx,f.actor,{...f.event,id:'new-private-source-event'}),e=>e.statusCode===404);assert.equal(f.snapshot(),before);
});
test('native CRM internal effects reject cross-pipeline stages and unavailable assignees atomically',()=>{
 for(const effect of ['stage','assignee']){const f=fixture();if(effect==='stage')f.core.collection(f.ctx,'stages')[0].pipeline_id='another-pipeline';else f.core.collection(f.ctx,'users')[0].enabled=false;f.define([action('field_update',{field:'status',value:'QUALIFIED'}),effect==='stage'?action('stage_change',{stage_id:f.stage.id}):action('assign',{owner_id:f.user.id})]);const before=f.snapshot(),notifications=f.events.length;assert.throws(()=>f.run(),e=>[404,409].includes(e.statusCode));assert.equal(f.snapshot(),before);assert.equal(f.events.length,notifications);}
});
test('native CRM automatic field definitions cannot mutate authority, ownership or lifecycle metadata',()=>{
 const f=fixture();for(const field of ['owner_id','team_id','stage_id','pipeline_id','tenant_id','revision','deleted_at','permissions','__proto__']){const before=f.snapshot();assert.throws(()=>f.define([action('field_update',{field,value:'bad'})]),e=>e.statusCode===400);assert.equal(f.snapshot(),before);}
});
test('native CRM effect receipts recheck current target access and failed persistence restores all effects',()=>{
 const f=fixture();f.define([action('field_update',{field:'status',value:'QUALIFIED'})]);const before=f.snapshot();f.fail(true);assert.throws(()=>f.run(),/persistence failure/);assert.equal(f.snapshot(),before);f.fail(false);f.run();f.actor.roles=[];f.actor.permissions=['crm:automate','crm:read_assigned','crm:write_assigned'];f.core.collection(f.ctx,'deals')[0].owner_id='private-other';assert.throws(()=>f.run(),e=>e.statusCode===404);
});
test('native CRM automation stage effects do not recursively cascade and stage API receipt returns final source revision',()=>{
 const f=fixture(),initial=f.core.create(f.ctx,f.actor,'stages',{name:'Literal initial stage',pipeline_id:f.pipeline.id,status:'OPEN',probability:10});f.define([action('stage_change',{stage_id:f.stage.id})],'stage_change');const options={idempotencyKey:'native-effects-stage',expectedRevision:f.deal.revision},result=f.core.moveDeal(f.ctx,f.actor,f.deal.id,initial.id,options),row=f.core.get(f.ctx,f.actor,'deals',f.deal.id);assert.equal(row.stage_id,f.stage.id);assert.equal(row.revision,3);assert.equal(result.revision,row.revision);assert.equal(result.stage_id,row.stage_id);assert.equal(result.requested_stage_id,initial.id);assert.equal(f.core.list(f.ctx,f.actor,'automation_executions').total,1);assert.equal(f.core.moveDeal(f.ctx,f.actor,f.deal.id,initial.id,options).idempotent_replay,true);assert.equal(f.core.get(f.ctx,f.actor,'deals',f.deal.id).revision,3);
});
test('native CRM monetary and probability validation preserves unknown and rejects fabricated numeric values',()=>{
 const f=fixture();const row=f.core.update(f.ctx,f.actor,'deals',f.deal.id,{value:null,probability:null});assert.equal(row.value,null);assert.equal(row.probability,null);for(const value of ['not-a-number','',false,{},-1]){const before=f.snapshot();assert.throws(()=>f.core.update(f.ctx,f.actor,'deals',f.deal.id,{value}),e=>e.statusCode===400);assert.equal(f.snapshot(),before);}assert.throws(()=>f.core.update(f.ctx,f.actor,'deals',f.deal.id,{probability:101}),e=>e.statusCode===400);assert.equal(f.core.update(f.ctx,f.actor,'deals',f.deal.id,{value:'12.34'}).value,12.34);
});
