'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/crm-form-fixture'),{locales}=require('../foundly-i18n');
async function setup(){const f=fixture();f.context.FoundlyCrmAutomationEditor=require('../crm-automation-editor');const form=f.automationForm(),submit=form.querySelector('button'),children=form.children.filter(n=>n!==submit);form.replaceChildren(...children,f.nodes.automationActionFields,submit);const {core,ctx,actor}=f.native,user=core.create(ctx,actor,'users',{name:'Literal private CRM owner'});form.elements.action.value='assign';await f.context.selectAutomationAction();const field=f.nodes.automationActionFields.all().find(n=>n.getAttribute('data-i18n')==='crm.automation.owner').parentNode.children.at(-1);field.value=user.id;return {...f,form,submit,user,field,save:()=>f.context.saveAutomation({preventDefault(){},currentTarget:form})};}
test('CRM production form freezes complete automatic source choices through a lost save reply and locale changes',async()=>{
 const f=await setup();f.lose();await assert.rejects(f.save(),/Lost committed response/);const first=JSON.parse(f.writes[0].options.body);assert.deepEqual(first.actions.map(a=>[a.type,a.execution_mode,a.target_entity,a.owner_id]),[['assign','AUTOMATIC_INTERNAL','leads',f.user.id]]);assert.equal(f.field.disabled,true);const before=f.calls.length;for(const locale of locales)f.i.setLocale(locale);assert.equal(f.calls.length,before);f.field.value='forged_replacement';await f.save();assert.deepEqual(f.writes[1],f.writes[0]);const {core,ctx,actor}=f.native,lead=core.create(ctx,actor,'leads',{name:'Literal action source'}),result=core.evaluateAutomations(ctx,actor,{id:'native-authoring-event',type:'new_lead',entity:'leads',record_id:lead.id});assert.equal(result.executions[0].status,'COMPLETED');assert.equal(core.get(ctx,actor,'leads',lead.id).owner_id,f.user.id);assert.equal(core.list(ctx,actor,'automations').total,1);
});
test('CRM production form disables its actual submit and auxiliary source controls while saving',async()=>{
 const f=await setup(),release=f.hold(),pending=f.save();await release.started;assert.equal(f.submit.disabled,true);assert.equal(f.field.disabled,true);assert.ok(f.nodes.automationActionFields.all().filter(n=>n.tag==='button').every(n=>n.disabled));await f.save();release();await pending;assert.equal(f.writes.length,1);assert.equal(f.submit.disabled,false);
});
test('CRM production form retires private action choices and late committed replies after current access denial',async()=>{
 const f=await setup(),release=f.hold(),pending=f.save();await release.started;f.native.actor.roles=[];await assert.rejects(f.context.loadStatus());assert.ok(!f.nodes.automationActionFields.textContent.includes('Literal private CRM owner'));release();await pending;assert.ok(!f.nodes.automationActionFields.textContent.includes('Literal private CRM owner'));await assert.rejects(f.save());assert.equal(f.writes.length,1);
});
