'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/fixture');
test('native CRM HTTP mutations enforce archive revision and current replay permission through encrypted restart',async()=>{
 const f=await fixture();try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['crm'],expected_revision:0})).status,200);
  const account=await f.enroll('crm-replay-operator',['SALES']);let cookie=account.cookie;const create={name:'Literal private HTTP source'},createHeaders={'idempotency-key':'crm-http-private-create'};let response=await f.request('/api/crm/contacts','POST',create,cookie,createHeaders);assert.equal(response.status,201);const row=response.body.record,route='/api/crm/contacts/'+row.id,update={phone:'Literal private HTTP phone'},updateHeaders={'idempotency-key':'crm-http-private-update','if-match':'"'+row.revision+'"'};
  for(const value of ['invalid','"1", "2"','"1','9007199254740992']){const bad=await f.request(route,'PATCH',{phone:'Literal rejected header'},cookie,{'if-match':value});assert.equal(bad.status,400);assert.equal(bad.body.code,'crm_revision_invalid');}assert.equal((await f.request(route,'GET',undefined,cookie)).body.record.revision,row.revision);
  response=await f.request(route,'PATCH',update,cookie,updateHeaders);assert.equal(response.status,200);const revision=response.body.record.revision;
  response=await f.request(route,'DELETE',undefined,cookie,{'idempotency-key':'crm-http-stale-archive','if-match':'"'+row.revision+'"'});assert.equal(response.status,409);assert.equal(response.body.code,'crm_revision_conflict');assert.equal((await f.request(route,'GET',undefined,cookie)).body.record.revision,revision);
  const archiveRow=(await f.request('/api/crm/contacts','POST',{name:'Literal private archive'},cookie,{'idempotency-key':'crm-http-archive-source'})).body.record,archiveRoute='/api/crm/contacts/'+archiveRow.id,archiveHeaders={'idempotency-key':'crm-http-private-archive','if-match':'"'+archiveRow.revision+'"'};response=await f.request(archiveRoute,'DELETE',undefined,cookie,archiveHeaders);assert.equal(response.status,200);assert.equal((await f.request(archiveRoute,'DELETE',undefined,cookie,archiveHeaders)).body.idempotent_replay,true);
  response=await f.request('/api/identity/users/'+account.member.id,'PUT',{roles:['VIEWER'],expected_revision:account.member.revision,confirm:true,reason:'Isolated native CRM replay revocation acceptance'});assert.equal(response.status,200);cookie=await f.login(account);
  for(const restart of [false,true]){if(restart){await f.stop();await f.start();}for(const [path,method,payload,headers]of [['/api/crm/contacts','POST',create,createHeaders],[route,'PATCH',update,updateHeaders],[archiveRoute,'DELETE',undefined,archiveHeaders]]){response=await f.request(path,method,payload,cookie,headers);assert.ok([403,404].includes(response.status),JSON.stringify(response.body));assert.ok(!JSON.stringify(response.body).includes('Literal private'));}}
 }finally{await f.close();}
});
