'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/crm-form-fixture'),{locales}=require('../foundly-i18n');
for(const kind of ['record','automation']){
 const prepare=f=>kind==='record'?f.recordForm():f.automationForm(),save=(f,form)=>f.context[kind==='record'?'saveRecord':'saveAutomation']({preventDefault(){},currentTarget:form}),entity=kind==='record'?'leads':'automations';
 test('CRM '+kind+' save retries the exact committed request across locales without creating duplicates',async()=>{
  const f=fixture(),form=prepare(f);f.lose();await assert.rejects(save(f,form),/Lost committed response/);assert.ok(form.querySelectorAll('input').every(node=>node.disabled));assert.equal(form.querySelector('button').disabled,false);const before=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,before);}form.elements.name.value='Changed after submission';await save(f,form);assert.deepEqual(f.writes[1],f.writes[0]);assert.equal(f.native.core.list(f.native.ctx,f.native.actor,entity).total,1);assert.equal(f.formReads(),1);
 });
 test('CRM '+kind+' pending save rejects duplicate submission',async()=>{
  const f=fixture(),form=prepare(f),release=f.hold(),pending=save(f,form);await release.started;await save(f,form);release();await pending;assert.equal(f.writes.length,1);assert.equal(f.native.core.list(f.native.ctx,f.native.actor,entity).total,1);
 });
}
test('CRM record PATCH retry retains the original editor, revision and key when the dialog is closed and another record is requested',async()=>{
 const f=fixture(),record=f.native.core.create(f.native.ctx,f.native.actor,'leads',{name:'Literal existing record'}),form=f.recordForm(record);form.elements.name.value='Literal changed record';f.lose();await assert.rejects(f.context.saveRecord({preventDefault(){},currentTarget:form}),/Lost committed response/);f.nodes.recordDialog.close();f.context.openRecordDialog(null,'contacts');assert.equal(f.nodes.recordDialog.open,true);assert.equal(form.elements.id.value,record.id);for(const locale of locales)f.i.setLocale(locale);await f.context.saveRecord({preventDefault(){},currentTarget:form});assert.deepEqual(f.writes[1],f.writes[0]);assert.equal(f.writes[0].options.headers['if-match'],'"'+record.revision+'"');assert.equal(f.native.core.get(f.native.ctx,f.native.actor,'leads',record.id).revision,record.revision+1);assert.equal(f.native.core.list(f.native.ctx,f.native.actor,'contacts').total,0);
});
test('CRM pending form responses cannot restore private source or reset a draft after current access is revoked',async()=>{
 for(const kind of ['record','automation']){const f=fixture(),form=kind==='record'?f.recordForm():f.automationForm(),method=kind==='record'?'saveRecord':'saveAutomation',release=f.hold(),pending=f.context[method]({preventDefault(){},currentTarget:form});await release.started;f.native.actor.roles=[];await assert.rejects(f.context.loadStatus());release();await pending;assert.equal(f.nodes.recordRows.textContent,'');assert.equal(f.nodes.automationList.textContent,'');if(kind==='record'){assert.equal(f.nodes.recordDialog.open,false);assert.equal(form.elements.name.value,'');}else assert.equal(form.elements.name.value,'Literal authored automation');assert.equal(form.querySelector('button').disabled,false);}
});
test('CRM definitive form validation failures unlock correction and use a new request key',async()=>{
 for(const kind of ['record','automation']){const f=fixture(),form=kind==='record'?f.recordForm():f.automationForm(),method=kind==='record'?'saveRecord':'saveAutomation',field=kind==='record'?'email':'trigger';form.elements[field].value='invalid';await assert.rejects(f.context[method]({preventDefault(){},currentTarget:form}));assert.ok(form.querySelectorAll('input').every(node=>!node.disabled));form.elements[field].value=kind==='record'?'literal@example.test':'new_lead';await f.context[method]({preventDefault(){},currentTarget:form});assert.notEqual(f.writes[1].options.headers['idempotency-key'],f.writes[0].options.headers['idempotency-key']);assert.equal(f.native.core.list(f.native.ctx,f.native.actor,kind==='record'?'leads':'automations').total,1);}
});
