'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture:pageFixture}=require('../zero-evaluation/crm-dashboard-fixture'),{fixture:coreFixture}=require('../zero-evaluation/crm-save-fixture'),{locales}=require('../foundly-i18n');
function fixture(){const f=pageFixture(),native=coreFixture();let lose=false,malformed=false,reject=0,statusError=0;f.context.fetch=async(route,options={})=>{f.calls.push({route,options});let data,code=200;try{if(route==='/api/crm/dashboard'&&options.method){if(reject)throw Object.assign(Error('RAW_PRIVATE_REJECTION'),{statusCode:reject,code:'crm_validation_failed'});data={dashboard:native.core.saveDashboard(native.ctx,native.actor,JSON.parse(options.body),{idempotencyKey:options.headers['idempotency-key'],expectedRevision:options.headers['if-match']?Number(options.headers['if-match'].replaceAll('"','')):undefined})};if(lose){lose=false;throw Object.assign(Error('Lost committed response'),{transport:true});}if(malformed){malformed=false;data={ok:true};}}else if(route.startsWith('/api/crm/dashboard?'))data={dashboard:native.core.dashboard(native.ctx,native.actor,{})};else if(route.startsWith('/api/crm/summary?'))data=f.summary;else if(route==='/api/crm/status'){if(statusError)throw Object.assign(Error('RAW_PRIVATE_STATUS_ERROR'),{statusCode:statusError,code:'crm_forbidden'});data={records:0,change_token:'literal_version'};}else data={};}catch(error){if(error.transport)throw error;code=error.statusCode||500;data={code:error.code,error:error.message};}return {ok:code<400,status:code,text:async()=>JSON.stringify(data)};};return {...f,native,lose(){lose=true;},malformed(){malformed=true;},reject(value){reject=value;},statusError(value){statusError=value;},writes:()=>f.calls.filter(c=>c.options.method)};}
test('actual CRM controller retries a lost committed POST or PATCH with the exact body, revision and key across all interface locales',async()=>{
 for(const method of ['POST','PATCH']){const f=fixture();if(method==='PATCH')f.native.save('Literal existing',{is_default:true});await f.context.loadDashboard();f.nodes.dashboardOwnerFilter.value='literal_authored_filter';f.lose();await assert.rejects(f.context.saveDashboard(),/Lost committed response/);assert.equal(f.writes()[0].options.method,method);const first=f.writes()[0],before=f.calls.length,layout=f.currentDashboard();assert.equal(f.nodes.dashboardOwnerFilter.disabled,true);assert.equal(f.nodes.saveDashboard.disabled,false);
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,before);assert.equal(f.nodes.dashboardNotice.textContent,f.i.t('crm.dashboard.retry_error',{reason:f.i.t('common.request_failed')}));assert.deepEqual(f.currentDashboard(),layout);assert.equal(f.nodes.dashboardOwnerFilter.value,'literal_authored_filter');}
  f.nodes.dashboardOwnerFilter.value='Changed programmatically';const prior=f.calls.length;await f.context.loadDashboard({forcePreset:true});assert.equal(f.calls.length,prior+1);assert.equal(f.calls.at(-1).route,'/api/crm/status');await f.context.saveDashboard();assert.deepEqual(f.writes()[1],first);assert.equal(f.native.core.list(f.native.ctx,f.native.actor,'dashboard_views').total,1);assert.equal(f.currentDashboard().filters.owner_id,'literal_authored_filter');assert.equal(f.nodes.dashboardOwnerFilter.disabled,false);assert.equal(f.currentDashboard().persisted,true);
 }
});
test('actual CRM controller treats malformed success as unconfirmed and safely replays the committed result',async()=>{
 const f=fixture();await f.context.loadDashboard();f.malformed();await assert.rejects(f.context.saveDashboard(),/response unavailable/);assert.equal(f.native.core.list(f.native.ctx,f.native.actor,'dashboard_views').total,1);await f.context.saveDashboard();assert.deepEqual(f.writes()[0],f.writes()[1]);assert.equal(f.native.core.list(f.native.ctx,f.native.actor,'dashboard_views').total,1);assert.equal(f.nodes.dashboardNotice.textContent,f.i.t('crm.dashboard.saved'));
});
test('actual CRM controller releases a definitive failed save for correction without reusing its key',async()=>{
 const f=fixture();await f.context.loadDashboard();f.reject(400);await assert.rejects(f.context.saveDashboard());assert.equal(f.nodes.dashboardOwnerFilter.disabled,false);assert.equal(f.native.core.list(f.native.ctx,f.native.actor,'dashboard_views').total,0);f.nodes.dashboardOwnerFilter.value='literal_corrected';f.reject(0);await f.context.saveDashboard();assert.notEqual(f.writes()[0].options.headers['idempotency-key'],f.writes()[1].options.headers['idempotency-key']);assert.equal(f.currentDashboard().filters.owner_id,'literal_corrected');
});
test('actual CRM controller checks current authorization during pending-save refresh and clears the frozen private request on denial',async()=>{
 const f=fixture();await f.context.loadDashboard();f.lose();await assert.rejects(f.context.saveDashboard());f.statusError(403);await assert.rejects(f.context.refreshDashboardData());assert.equal(f.currentDashboard(),null);assert.equal(f.nodes.widgetGrid.textContent,'');assert.equal(f.nodes.saveDashboard.disabled,true);const n=f.writes().length;await f.context.saveDashboard();assert.equal(f.writes().length,n);assert.ok(!f.nodes.dashboardNotice.textContent.includes('RAW_PRIVATE'));
});
test('actual CRM controller separates a confirmed save from a later status failure',async()=>{
 const f=fixture();await f.context.loadDashboard();f.statusError(500);await f.context.saveDashboard();assert.equal(f.currentDashboard().persisted,true);assert.equal(f.nodes.dashboardOwnerFilter.disabled,false);for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.dashboardNotice.textContent,f.i.t('crm.dashboard.saved_status_failed'));}assert.equal(f.writes().length,1);
});
