'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{create}=require('../crm-automation-editor'),{contract}=require('../crm-automation-actions'),{browserFixture}=require('../zero-evaluation/dom-fixture'),{CrmView}=require('../zero-evaluation/crm-dashboard-fixture'),{locales}=require('../foundly-i18n');
function fixture(){const f=browserFixture('en-GB'),i=f.context.FoundlyI18n,calls=[],data={users:{items:[{id:'user_literal',name:'Literal <img> owner'}],next_cursor:null},pipelines:{items:[{id:'pipeline_literal',name:'Literal pipeline'},{id:'pipeline_other',name:'Literal second pipeline'}],next_cursor:null},stages:{items:[{id:'stage_literal',name:'Literal stage',pipeline_id:'pipeline_literal'}],next_cursor:null}};let held=null,path='',release,started;f.context.document.createElement=tag=>new CrmView(tag);const request=async route=>{calls.push(route);const response=JSON.parse(JSON.stringify(data[route.split('/')[3].split('?')[0]]));if(held&&route.includes(path)){const pending=held;held=null;started();await pending;}return response;},root=create({document:f.context.document,i18n:i,request,schema:async()=>({automation_internal_contract:contract})});f.nodes.editor=root;const field=key=>root.all().find(n=>n.getAttribute('data-i18n')==='crm.automation.'+key)?.parentNode.children.at(-1),choose=async(key,value)=>{const node=field(key);node.value=value;await node.fire('change');};return {...f,i,root,calls,data,field,choose,hold(route){path=route;held=new Promise(resolve=>release=resolve);release.started=new Promise(resolve=>started=resolve);return release;}};}
test('CRM action editor preserves typed field values and source choices across eight locales without extra reads',async()=>{
 const f=fixture();await f.root.select('assign');await f.choose('owner','user_literal');const owner=f.field('owner'),calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.root.read('assign').owner_id,'user_literal');assert.equal(f.field('owner'),owner);assert.ok(f.root.textContent.includes('Literal <img> owner'));assert.ok(f.root.textContent.includes(f.i.t('crm.automation.target')));assert.equal(f.calls.length,calls);}
 await f.root.select('field_update');await f.choose('field','value');f.field('value').value='1234.5';const input=f.field('value');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.root.read('field_update').value,1234.5);assert.equal(f.field('value'),input);assert.equal(f.field('value').value,'1234.5');assert.equal(f.calls.length,calls);}
});
test('CRM action editor makes unknown values explicit and rejects blank or invalid numeric input',async()=>{
 const f=fixture();await f.root.select('field_update');await f.choose('field','probability');for(const value of ['','wrong','101','-1']){f.field('value').value=value;assert.throws(()=>f.root.read('field_update'),e=>e.code==='crm_automation_input_invalid');}f.field('value').value='0';assert.equal(f.root.read('field_update').value,0);f.field('clear').checked=true;await f.field('clear').fire('change');assert.equal(f.root.read('field_update').value,null);assert.equal(f.field('value').disabled,true);
});
test('CRM action source pagination preserves selection and never silently treats malformed pages as complete',async()=>{
 const f=fixture();f.data.users.next_cursor=200;await f.root.select('assign');await f.choose('owner','user_literal');const more=f.root.all().find(n=>n.tag==='button');f.data.users={items:[{id:'next_literal',name:'Next owner'}],next_cursor:null};await more.fire('click');assert.ok(f.calls[1].includes('cursor=200'));assert.equal(f.root.read('assign').owner_id,'user_literal');assert.ok(f.root.textContent.includes('Next owner'));f.data.users={items:[]};await f.root.select('assign');assert.throws(()=>f.root.read('assign'));assert.ok(f.root.textContent.includes(f.i.t('crm.automation.load_error')));
});
test('CRM action editor discards late private source replies after action replacement or access clearing',async()=>{
 for(const clear of [false,true]){const f=fixture(),release=f.hold('/users?'),pending=f.root.select('assign');await release.started;if(clear)f.root.clear();else await f.root.select('field_update');release();await pending;assert.ok(!f.root.textContent.includes('Literal <img> owner'));if(clear){assert.equal(f.root.textContent,'');assert.throws(()=>f.root.read('assign'));}else{f.field('value').value='OPEN';assert.equal(f.root.read('field_update').value,'OPEN');}}
});
test('CRM action stage selection binds loaded stages to their selected pipeline and blocks detached old replies',async()=>{
 const f=fixture();await f.root.select('stage_change');const pipeline=f.root.all().find(n=>n.getAttribute('data-i18n')==='crm.dashboard.metric.pipeline').parentNode.children.at(-1);pipeline.value='pipeline_literal';await pipeline.fire('change');const stage=f.root.all().find(n=>n.getAttribute('data-i18n')==='crm.pipeline.stage').parentNode.children.at(-1);stage.value='stage_literal';assert.equal(f.root.read('stage_change').stage_id,'stage_literal');pipeline.value='pipeline_other';const release=f.hold('/stages?'),pending=pipeline.fire('change');await release.started;pipeline.value='pipeline_literal';await pipeline.fire('change');stage.value='stage_literal';release();await pending;assert.equal(f.root.read('stage_change').stage_id,'stage_literal');stage.value='forged_stage';assert.throws(()=>f.root.read('stage_change'));
});
test('CRM action editor locks auxiliary buttons with the original unconfirmed request',async()=>{
 const f=fixture();f.data.users.next_cursor=200;await f.root.select('assign');await f.choose('owner','user_literal');const calls=f.calls.length,more=f.root.all().find(n=>n.tag==='button');f.root.setDisabled(true);assert.equal(more.disabled,true);await more.fire('click');assert.equal(f.calls.length,calls);assert.equal(f.field('owner').disabled,true);f.root.setDisabled(false);assert.equal(f.field('owner').disabled,false);
});
test('CRM action source selection excludes inactive, disabled and archived assignees',async()=>{
 const f=fixture();f.data.users.items.push({id:'inactive_owner',name:'Inactive owner',status:'INACTIVE'},{id:'disabled_owner',name:'Disabled owner',enabled:false},{id:'archived_owner',name:'Archived owner',deleted_at:'2026-09-24T12:00:00Z'});await f.root.select('assign');for(const id of ['inactive_owner','disabled_owner','archived_owner']){f.field('owner').value=id;assert.throws(()=>f.root.read('assign'));}f.field('owner').value='user_literal';assert.equal(f.root.read('assign').owner_id,'user_literal');
});
