'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('../zero-evaluation/crm-dashboard-fixture');
test('denied CRM dashboard load clears earlier private source rows and dashboard state',async()=>{
 const f=fixture();await f.context.loadDashboard();assert.ok(f.nodes.widgetGrid.textContent.includes('Literal private'));f.deny();await assert.rejects(f.context.loadDashboard());assert.ok(!f.nodes.widgetGrid.textContent.includes('Literal private'));assert.equal(f.currentDashboard(),null);
});
test('an older CRM dashboard summary cannot repaint after a newer denied dashboard load',async()=>{
 const f=fixture();await f.context.loadDashboard();const release=f.hold('/api/crm/summary'),pending=f.context.refreshDashboardData();await release.started;f.deny();await assert.rejects(f.context.loadDashboard());release();await pending;assert.ok(!f.nodes.widgetGrid.textContent.includes('Literal private'));assert.equal(f.currentDashboard(),null);
});
const {locales}=require('../foundly-i18n');
const key=(f,name)=>f.nodes.widgetGrid.all().find(n=>n.getAttribute('data-i18n')==='crm.dashboard.'+name);
const card=(f,metric)=>f.nodes.widgetGrid.children.find(n=>n.getAttribute('data-widget')===metric);
const add=(f,metric,type='TABLE')=>f.dashboard.dashboard.widgets.push({id:metric,metric,type,x:0,y:0,w:4,h:3});
test('CRM dashboard labels, typed numbers and literal source text change locale without reads or replacing cards and edited layout',async()=>{
 const f=fixture();f.summary.analytics.comparison.metrics.leads={available:true,absolute_delta:-1234,percent_delta:-50,unit:'count'};await f.context.loadDashboard();await f.context.loadStatus();f.setEditing(true);const metric=f.nodes.widgetGrid.children[0],lead=f.nodes.widgetGrid.children[1],source=JSON.stringify(f.summary),before=f.calls.length;f.nodes.dashboardTeam.value='Literal authored team';f.nodes.dashboardOwnerFilter.value='Literal authored filter';
 for(const locale of locales){f.i.setLocale(locale);assert.equal(metric,f.nodes.widgetGrid.children[0]);assert.equal(lead,f.nodes.widgetGrid.children[1]);assert.equal(metric.children[1].textContent,f.i.t('crm.dashboard.metric.leads'));assert.equal(metric.querySelector('.metric').children[0].textContent,f.i.number(1234));assert.equal(key(f,'source_records').textContent,f.i.t('crm.dashboard.source_records',{count:f.i.number(1234)}));assert.equal(metric.children[0].children[1].getAttribute('title'),f.i.t('crm.dashboard.larger'));assert.ok(lead.textContent.includes('Literal private <img> lead'));assert.equal(lead.querySelector('td').children.length,0);assert.equal(f.nodes.dashboardNotice.textContent,f.i.t('crm.dashboard.loaded'));assert.equal(f.nodes.crmConnection.textContent,f.i.t('crm.dashboard.fetched',{count:f.i.number(1234)}));assert.equal(f.nodes.dashboardTeam.value,'Literal authored team');assert.equal(f.nodes.dashboardOwnerFilter.value,'Literal authored filter');assert.equal(metric.draggable,true);assert.equal(f.calls.length,before);assert.equal(JSON.stringify(f.summary),source);assert.equal(f.i.missingKeys().length,0);}
});
test('CRM chart zeros are zero bars and cannot be replaced by counts or invented euros',async()=>{
 const f=fixture();add(f,'source_performance','BAR');add(f,'owner_performance');add(f,'pipeline');add(f,'lead_trend','LINE');f.summary.analytics.source_performance=[{source_id:'Literal <img> source',value:0,leads:999},{source_id:'Literal other',value:20,leads:1}];f.summary.analytics.owner_performance=[{owner_id:'Literal owner',deals:0,value:null}];f.summary.analytics.pipeline_stages=[{name:'Literal stage',deals:2,value:1234.56,currency:'USD'}];f.summary.analytics.trends.lead_trend=[{date:'2026-09-24',leads:0},{date:'2026-09-25',leads:2}];await f.context.loadDashboard();const before=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);const source=card(f,'source_performance'),trend=card(f,'lead_trend');assert.equal(source.querySelector('i').className,'bar-0');assert.equal(trend.querySelector('i').className,'bar-0');assert.equal(source.querySelector('i').getAttribute('title'),f.i.t('crm.dashboard.source_value',{source:'Literal <img> source',value:f.i.number(0)+' · '+f.i.t('crm.dashboard.currency_unknown')}));assert.ok(!source.textContent.includes('€'));assert.ok(card(f,'owner_performance').textContent.includes(f.i.t('crm.dashboard.deals_value',{count:f.i.number(0),value:f.i.t('common.unknown')})));assert.ok(card(f,'pipeline').textContent.includes(new Intl.NumberFormat(locale,{style:'currency',currency:'USD',maximumFractionDigits:2}).format(1234.56)));assert.equal(f.calls.length,before);assert.equal(f.i.missingKeys().length,0);}
});
test('CRM source charts keep one measurement unit and do not combine missing money with lead counts',async()=>{
 const f=fixture();add(f,'source_performance','BAR');f.summary.analytics.source_performance=[{source_id:'Literal missing',value:null,leads:999},{source_id:'Literal amount',value:20,leads:1}];await f.context.loadDashboard();assert.equal(card(f,'source_performance').querySelector('i'),null);assert.equal(card(f,'source_performance').querySelector('td').parentNode.children[1].textContent,f.i.t('common.unknown'));assert.ok(!card(f,'source_performance').textContent.includes('999'));
 f.summary.analytics.source_performance=[{source_id:'Literal euro',value:20,currency:'EUR'},{source_id:'Literal dollar',value:20,currency:'USD'}];await f.context.refreshDashboardData();assert.equal(card(f,'source_performance').querySelector('i'),null);assert.ok(card(f,'source_performance').textContent.includes('€'));
 f.summary.analytics.source_performance=[{source_id:'Literal lead',leads:0},{source_id:'Literal second',leads:3}];await f.context.refreshDashboardData();assert.equal(card(f,'source_performance').querySelector('i').className,'bar-0');assert.equal(card(f,'source_performance').querySelector('i').getAttribute('title'),f.i.t('crm.dashboard.source_leads',{source:'Literal lead',value:f.i.number(0)}));
});
test('CRM missing lists and source counts remain unknown while observed empty lists retain explicit empty states',async()=>{
 const f=fixture();add(f,'campaign_attribution');delete f.summary.analytics.metrics.leads.source_count;delete f.summary.analytics.campaigns;await f.context.loadDashboard();const before=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(key(f,'source_records').textContent,f.i.t('crm.dashboard.source_records',{count:f.i.t('common.unknown')}));assert.ok(card(f,'campaign_attribution').textContent.includes(f.i.t('common.no_data')));assert.equal(f.calls.length,before);}
 f.summary.analytics.campaigns=[];await f.context.refreshDashboardData();for(const locale of locales){f.i.setLocale(locale);assert.equal(key(f,'campaign_empty').textContent,f.i.t('crm.dashboard.campaign_empty'));}
});
test('CRM malformed counts and unavailable comparison deltas do not become observed numbers',async()=>{
 const f=fixture();add(f,'lead_trend');add(f,'campaign_attribution');f.summary.analytics.trends.lead_trend=[{date:'2026-09-24',leads:'1'}];f.summary.analytics.campaigns=[{name:'Literal campaign',attributions:false}];f.summary.analytics.comparison.metrics.leads={available:'true',absolute_delta:100,percent_delta:50};f.status.records='1234';await f.context.loadDashboard();await f.context.loadStatus();assert.equal(f.nodes.widgetGrid.querySelector('.comparison'),null);assert.equal(card(f,'lead_trend').querySelector('i'),null);assert.ok(card(f,'campaign_attribution').textContent.includes(f.i.t('common.unknown')));assert.equal(f.nodes.crmConnection.textContent,f.i.t('crm.dashboard.fetched',{count:f.i.t('common.unknown')}));
});
test('CRM business titles, custom metric identifiers and activity text stay literal and inert while observed dates localize in UTC',async()=>{
 const f=fixture();add(f,'stalled_deals');add(f,'activity');add(f,'Literal_custom <img> metric');f.summary.analytics.stalled_deals=[{title:'Literal private <img> deal',next_action_at:'2026-09-24T23:45:00-03:00'}];f.summary.analytics.activity_feed=[{type:'literal_custom_type',summary:'Literal <script> activity',at:'2026-09-24T23:45:00-03:00'}];await f.context.loadDashboard();const before=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);const date=new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date('2026-09-24T23:45:00-03:00'));assert.equal(card(f,'stalled_deals').querySelector('td').textContent,'Literal private <img> deal');assert.equal(card(f,'stalled_deals').querySelector('td').children.length,0);assert.ok(card(f,'stalled_deals').textContent.includes(date));assert.ok(card(f,'activity').textContent.includes('literal_custom_type'));assert.ok(card(f,'activity').textContent.includes('Literal <script> activity'));assert.equal(card(f,'Literal_custom <img> metric').querySelector('h3').textContent,'Literal_custom <img> metric');assert.equal(f.calls.length,before);assert.equal(f.i.missingKeys().length,0);}
});
test('CRM localized pending and denied messages cannot revive cleared private observations',async()=>{
 const f=fixture();await f.context.loadDashboard();const release=f.hold('/api/crm/summary'),pending=f.context.refreshDashboardData();await release.started;const before=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.dashboardNotice.textContent,f.i.t('crm.dashboard.refreshing'));assert.equal(f.calls.length,before);}release();await pending;f.deny();await assert.rejects(f.context.loadDashboard());const after=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.dashboardNotice.textContent,f.i.t('common.access_denied'));assert.equal(f.nodes.dashboardFreshness.textContent,'');assert.equal(f.nodes.widgetGrid.textContent,'');assert.equal(f.nodes.crmConnection.textContent,f.i.t('common.access_denied'));assert.ok(!f.nodes.dashboardNotice.textContent.includes('RAW_PRIVATE_ERROR'));assert.equal(f.calls.length,after);assert.equal(f.i.missingKeys().length,0);}
});
test('CRM status denial clears dashboard observations and late status success cannot restore record counts',async()=>{
 const f=fixture();await f.context.loadDashboard();await f.context.loadStatus();let release=f.hold('/api/crm/status'),pending=f.context.loadStatus();await release.started;f.deny();await assert.rejects(f.context.loadDashboard());release();await pending;assert.equal(f.nodes.crmConnection.textContent,f.i.t('common.access_denied'));assert.equal(f.nodes.crmConnection.classList.contains('online'),false);f.allow();await f.context.loadDashboard();f.deny();await assert.rejects(f.context.loadStatus());assert.equal(f.nodes.widgetGrid.textContent,'');assert.equal(f.currentDashboard(),null);
});
test('CRM late dashboard saves cannot repopulate private data after denial and pending saves reject duplicate requests',async()=>{
 const f=fixture();await f.context.loadDashboard();const release=f.hold('/api/crm/dashboard'),pending=f.context.saveDashboard();await release.started;const before=f.calls.length;await f.context.saveDashboard();assert.equal(f.calls.length,before);f.deny();await assert.rejects(f.context.loadDashboard());release();await pending;assert.equal(f.currentDashboard(),null);assert.equal(f.nodes.widgetGrid.textContent,'');assert.equal(f.calls.filter(c=>c.options?.method==='PATCH').length,1);assert.ok(!f.nodes.toast.textContent.includes('saved'));
});
test('CRM dashboard editing preserves native layout writes while detached old controls cannot change newer or denied state',async()=>{
 const f=fixture();await f.context.loadDashboard();f.setEditing(true);const old=f.nodes.widgetGrid.children[0],up=old.querySelector('[data-size="up"]');old.onclick({target:up});assert.equal(f.currentDashboard().widgets[0].w,6);old.onclick({target:up});assert.equal(f.currentDashboard().widgets[0].w,6);await f.context.saveDashboard();const write=f.calls.find(c=>c.options?.method==='PATCH'),payload=JSON.parse(write.options.body);assert.equal(write.route,'/api/crm/dashboard');assert.equal(payload.name,'Literal dashboard');assert.equal(payload.id,'literal_dashboard');assert.equal(payload.widgets[0].w,6);assert.equal(payload.widgets[0].metric,'leads');assert.ok(write.options.headers['idempotency-key'].startsWith('dashboard-'));f.deny();await assert.rejects(f.context.loadDashboard());old.onclick({target:up});assert.equal(f.currentDashboard(),null);
});
test('CRM comparison units distinguish percentage points from percentage changes and retain signed elapsed-time units',async()=>{
 const f=fixture();add(f,'conversion','KPI');add(f,'response_time','KPI');f.summary.analytics.metrics.conversion={available:true,value:60,unit:'percent',source_count:2};f.summary.analytics.metrics.response_time={available:true,value:2,unit:'hours',source_count:2};f.summary.analytics.comparison.metrics.conversion={available:true,absolute_delta:10,percent_delta:20,unit:'percent'};f.summary.analytics.comparison.metrics.response_time={available:true,absolute_delta:-1.5,percent_delta:null,unit:'hours'};await f.context.loadDashboard();
 for(const locale of locales){f.i.setLocale(locale);const sign=new Intl.NumberFormat(locale,{maximumFractionDigits:2,signDisplay:'exceptZero'}).format(10),percent=new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:1,signDisplay:'exceptZero'}).format(.2),hours=new Intl.NumberFormat(locale,{style:'unit',unit:'hour',unitDisplay:'short',maximumFractionDigits:2,signDisplay:'exceptZero'}).format(-1.5);assert.equal(card(f,'conversion').querySelector('.comparison').textContent,f.i.t('crm.dashboard.comparison',{value:f.i.t('crm.dashboard.percentage_points',{value:sign})+' · '+percent}));assert.equal(card(f,'response_time').querySelector('.comparison').textContent,f.i.t('crm.dashboard.comparison',{value:hours}));assert.equal(f.i.missingKeys().length,0);}
});
