'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {locales}=require('../foundly-i18n'),{fixture:baseFixture,ViewElement,extract}=require('../zero-evaluation/zero-presentation-fixture');
const source=fs.readFileSync(require.resolve('../index-script.js'),'utf8'),panels=['panelInventory','panelLeads','panelCrm','panelTasks','panelRecords','panelProviders'];
function controller(name,end){const start=source.indexOf('async function '+name+'('),stop=source.indexOf(end,start);assert.ok(start>=0&&stop>start);return source.slice(start,stop);}
function fixture(locale='en-GB'){
  const f=baseFixture(locale),pulses=[];f.zero.preferences.timezone='Europe/Copenhagen';f.context.window=f.context;f.context.neuralRuntime.event=event=>pulses.push(event);
  for(const id of [...panels,'coreState','runtimeState','memoryState','connectorState','liveSourceList','summaryObservedAt','events'])f.nodes[id]=new ViewElement();
  const data={health:{total_connectors:100},connectors:{connected:1234,configured:1500,total:2000,connectors:[{id:'native_provider',name:'Literal provider'}]},zero:{core_available:true,worker:{status:'RUNNING'},memory:{durable:true,persisted:true}},summary:{observed_at:'2026-09-24T14:35:27Z',business:{inventory_records:1234,leads:0,crm_records:null},operations:{active_tasks:2345},data_layer:{total_records:3456},sources:{connected_providers:1,connected:[{id:'native_provider',name:'Status niet beschikbaar <literal provider>'}]}},events:{events:[{id:'older',at:'2026-09-24T14:30:00Z',message:'Activiteit niet beschikbaar <literal event>'}]}};
  const response=path=>{const key={'/api/health':'health','/api/connectors':'connectors','/api/zero/status':'zero','/api/dashboard/summary':'summary','/api/events':'events'}[path];assert.ok(key,path);return {ok:true,status:200,json:async()=>data[key]};};
  f.context.fetch=async(path,options)=>{f.requests.push({path,options});return response(path);};
  vm.runInContext(['dashboardCount','dashboardNumber','dashboardTime','setPanelValue'].map(extract).join('\n')+'\n'+controller('loadSystemStatus','loadSystemStatus();setInterval')+'\n'+controller('loadDashboardSummary','loadDashboardSummary();setInterval')+'\nlet lastVisualEventId=null;\n'+controller('refreshEvents','\nrefreshEvents();'),f.context);
  return {...f,data,response,pulses};
}
const time=(locale,value,seconds=false)=>new Intl.DateTimeFormat(locale,{timeZone:'Europe/Copenhagen',hour:'2-digit',minute:'2-digit',...(seconds?{second:'2-digit'}:{})}).format(new Date(value));
test('system status localizes observed native states and counts without mutating the snapshot or issuing locale-triggered requests',async()=>{
  const f=fixture(),before=JSON.stringify(f.data);await f.context.loadSystemStatus();const nodes=['coreState','runtimeState','memoryState','connectorState'].map(id=>f.nodes[id].firstChild);
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.coreState.textContent,f.i.t('dashboard.core_ok'));assert.equal(f.nodes.runtimeState.textContent,f.i.t('dashboard.worker.running'));assert.equal(f.nodes.memoryState.textContent,f.i.t('dashboard.memory_durable'));assert.equal(f.nodes.connectorState.textContent,f.i.t('dashboard.connected_count',{count:1234}));assert.deepEqual(['coreState','runtimeState','memoryState','connectorState'].map(id=>f.nodes[id].firstChild),nodes);assert.equal(f.requests.length,3);assert.equal(f.zero.preferences.language,'da-DK');assert.equal(JSON.stringify(f.data),before);assert.equal(f.i.missingKeys().length,0);}
  for(const state of ['IDLE','DEGRADED','ERROR','NOT_RUN']){f.data.zero.worker.status=state;await f.context.loadSystemStatus();for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.runtimeState.textContent,f.i.t('dashboard.worker.'+state.toLowerCase()));}}
  f.data.zero.memory={durable:false,persisted:true};f.data.connectors.connected=0;await f.context.loadSystemStatus();assert.equal(f.nodes.memoryState.textContent,f.i.t('dashboard.memory_cache'));assert.equal(f.nodes.connectorState.textContent,f.i.t('dashboard.connected_count',{count:0}));
  f.data.zero.memory={durable:false,persisted:false};await f.context.loadSystemStatus();assert.equal(f.nodes.memoryState.textContent,f.i.t('dashboard.memory_unproven'));
});
test('missing or contradictory status is unknown, with no invented zero/100 default or fallback provider configuration',async()=>{
  const f=fixture();f.data.connectors={connectors:[null,{id:'native_provider'}]};f.data.zero={worker:{status:'constructor'},memory:{durable:true,persisted:false}};await f.context.loadSystemStatus();
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.coreState.textContent,f.i.t('common.unknown'));assert.equal(f.nodes.runtimeState.textContent,'constructor');assert.equal(f.nodes.memoryState.textContent,f.i.t('common.unknown'));assert.equal(f.nodes.connectorState.textContent,f.i.t('common.unknown'));assert.equal(f.context.__foundlyConnectorStatus.connected,null);assert.equal(f.context.__foundlyConnectorStatus.total,null);assert.equal(f.context.__foundlyConnectorStatus.openai_search,null);assert.equal(f.context.__foundlyConnectorStatus.connectors.length,1);assert.equal(f.requests.length,3);}
  for(const value of [null,undefined,false,-1,1.5,Infinity,'0',Number.MAX_SAFE_INTEGER+1])assert.equal(f.context.dashboardCount(value),null);assert.equal(f.context.dashboardCount(0),0);
});
test('a newer denied system observation clears old connector data and cannot be overwritten by a late successful read',async()=>{
  const f=fixture();await f.context.loadSystemStatus();const pending=[];let calls=0;f.context.fetch=async path=>{f.requests.push({path});return ++calls<=3?new Promise(resolve=>pending.push(()=>resolve(f.response(path)))):{ok:false,status:403};};const old=f.context.loadSystemStatus();await f.context.loadSystemStatus();for(const release of pending)release();await old;
  for(const locale of locales){f.i.setLocale(locale);for(const id of ['coreState','runtimeState','memoryState','connectorState'])assert.equal(f.nodes[id].textContent,f.i.t('common.unknown'));assert.equal(f.context.__foundlyConnectorStatus.available,false);assert.equal(f.context.__foundlyConnectorStatus.connectors.length,0);assert.equal(f.context.__foundlyConnectorStatus.total,null);assert.equal(calls,6);}
});
test('dashboard counts and observed time change locale in place while real zero and literal provider names remain intact',async()=>{
  const f=fixture(),before=JSON.stringify(f.data.summary);await f.context.loadDashboardSummary();const row=f.nodes.liveSourceList.children[0],name=row.textContent,numberNode=f.nodes.panelInventory.firstChild;
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.panelInventory.textContent,new Intl.NumberFormat(locale).format(1234));assert.equal(f.nodes.panelInventory.firstChild,numberNode);assert.equal(f.nodes.panelLeads.textContent,'0');assert.equal(f.nodes.panelCrm.textContent,f.i.t('common.unknown'));assert.equal(f.nodes.panelTasks.textContent,new Intl.NumberFormat(locale).format(2345));assert.equal(f.nodes.panelRecords.textContent,new Intl.NumberFormat(locale).format(3456));assert.equal(f.nodes.panelProviders.textContent,'1');assert.equal(f.nodes.summaryObservedAt.textContent,time(locale,f.data.summary.observed_at,true));assert.equal(f.nodes.liveSourceList.children[0],row);assert.equal(row.textContent,name);assert.equal(f.requests.length,1);assert.equal(JSON.stringify(f.data.summary),before);assert.equal(f.pulses.length,0);assert.equal(f.i.missingKeys().length,0);}
  f.data.summary={sources:{connected:[]},observed_at:false};await f.context.loadDashboardSummary();f.i.setLocale('fr-FR');for(const id of panels)assert.equal(f.nodes[id].textContent,f.i.t('common.unknown'));assert.equal(f.nodes.summaryObservedAt.textContent,f.i.t('common.unknown'));assert.equal(f.nodes.liveSourceList.children[0].textContent,f.i.t('static.8f8188fa'));
  f.data.summary={};await f.context.loadDashboardSummary();f.i.setLocale('de-DE');assert.equal(f.nodes.liveSourceList.children[0].textContent,f.i.t('static.8ee1fa32'));assert.equal(f.nodes.summaryObservedAt.textContent,f.i.t('common.unknown'));
  f.zero.preferences.timezone='invalid-zone';f.data.summary.observed_at='2026-09-24T14:35:27Z';await f.context.loadDashboardSummary();f.i.setLocale('sv-SE');assert.equal(f.nodes.summaryObservedAt.textContent,f.i.t('common.unknown'));
});
test('failed summary reads clear private source labels and freshness; older or detached replies cannot restore them',async()=>{
  const f=fixture();await f.context.loadDashboardSummary();let release;f.context.fetch=async()=>new Promise(resolve=>release=resolve);const old=f.context.loadDashboardSummary();f.context.fetch=async()=>({ok:false,status:403,json:async()=>({error:'RAW_PRIVATE_ERROR'})});await f.context.loadDashboardSummary();release(f.response('/api/dashboard/summary'));await old;
  for(const locale of locales){f.i.setLocale(locale);for(const id of panels)assert.equal(f.nodes[id].textContent,f.i.t('common.unknown'));assert.equal(f.nodes.liveSourceList.textContent,f.i.t('static.8ee1fa32'));assert.equal(f.nodes.summaryObservedAt.textContent,f.i.t('common.unknown'));assert.ok(!f.nodes.liveSourceList.textContent.includes('literal provider'));}
  f.context.fetch=async()=>new Promise(resolve=>release=resolve);const detached=f.context.loadDashboardSummary();f.nodes.liveSourceList=new ViewElement();f.nodes.liveSourceList.textContent='Replacement content';f.nodes.summaryObservedAt=new ViewElement();f.nodes.summaryObservedAt.textContent='Replacement clock';release(f.response('/api/dashboard/summary'));await detached;assert.equal(f.nodes.liveSourceList.textContent,'Replacement content');assert.equal(f.nodes.summaryObservedAt.textContent,'Replacement clock');
});
test('event timestamps localize while source messages and native visual-event delivery stay unchanged',async()=>{
  const f=fixture();await f.context.refreshEvents();const initial=f.nodes.events.children[0];
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.events.children[0],initial);assert.equal(initial.className,'ev');assert.equal(initial.textContent,time(locale,f.data.events.events[0].at)+' · '+f.data.events.events[0].message);assert.equal(initial.children.length,0);assert.equal(f.requests.length,1);assert.equal(f.pulses.length,0);}
  const next={id:'newer',at:'2026-09-24T14:35:00Z',message:'New <literal customer event>'};f.data.events.events.unshift(next);await f.context.refreshEvents();assert.equal(f.pulses.length,1);assert.equal(f.pulses[0],next);for(const locale of locales){f.i.setLocale(locale);assert.equal(f.pulses.length,1);assert.equal(f.requests.length,2);assert.equal(f.nodes.events.children[0].textContent,time(locale,next.at)+' · '+next.message);}
  const normal=f.context.fetch;f.context.fetch=async()=>({ok:false,status:403,json:async()=>({error:'RAW_PRIVATE_ERROR'})});await f.context.refreshEvents();for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.events.children.length,1);assert.equal(f.nodes.events.textContent,f.i.t('dashboard.activity_unavailable'));assert.equal(f.pulses.length,1);assert.ok(!f.nodes.events.textContent.includes('literal customer'));}
  f.context.fetch=normal;await f.context.refreshEvents();assert.equal(f.pulses.length,1,'A restored read must not replay historical events as new activity');
});
test('late or invalid activity responses cannot restore cleared rows or paint another view',async()=>{
  const f=fixture();await f.context.refreshEvents();let release;f.context.fetch=async()=>new Promise(resolve=>release=resolve);const old=f.context.refreshEvents();f.context.fetch=async()=>({ok:false,status:401,json:async()=>({})});await f.context.refreshEvents();release(f.response('/api/events'));await old;assert.equal(f.nodes.events.textContent,f.i.t('dashboard.activity_unavailable'));
  f.context.fetch=async()=>({ok:true,json:async()=>({events:null})});await f.context.refreshEvents();assert.equal(f.nodes.events.textContent,f.i.t('dashboard.activity_unavailable'));
  f.context.fetch=async()=>new Promise(resolve=>release=resolve);const detached=f.context.refreshEvents();f.nodes.events=new ViewElement();f.nodes.events.textContent='Replacement activity';release(f.response('/api/events'));await detached;assert.equal(f.nodes.events.textContent,'Replacement activity');assert.equal(f.pulses.length,0);
});
