'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture,reserve,advance}=require('../zero-evaluation/demo-universe-fixture'),{SCOPE}=require('../demo-universe-engine');
test('an explicitly isolated empty tenant and current manager authority are required before seed reservation',()=>{const f=fixture();f.setIsolated(false);assert.throws(()=>reserve(f),{code:'demo_isolated_scope_required'});f.setIsolated(true);assert.throws(()=>f.engine.preview(f.ctx,{id:'viewer',roles:['VIEWER']},f.options),{code:'demo_manage_forbidden'});f.crm.create(f.ctx,f.actor,'companies',{name:'Existing customer-owned record'});assert.throws(()=>reserve(f),{code:'demo_empty_tenant_required'});assert.equal(f.adapter.bucket(f.ctx,SCOPE).length,0);});
test('normal native CRM, identity, domain and ZERO memory writes create a linked synthetic seed without activating mail or providers',()=>{const f=fixture();let row=reserve(f);row=advance(f,row);assert.equal(row.status,'SEEDED');assert.equal(row.applied_nodes,row.total_nodes);const stored=f.adapter.bucket(f.ctx,SCOPE)[0],lead=f.crm.get(f.ctx,f.actor,'leads',stored.bindings['lead-0'].id);assert.equal(lead.vehicle_id,stored.bindings['vehicle-0'].id);assert.equal(lead.person_id,stored.bindings['customer-0'].id);assert.equal(lead.provenance.classification,'SYNTHETIC_DEMO');const sale=f.domains.sales.get(f.ctx,f.actor,'opportunities',stored.bindings['sale-0'].id);assert.equal(sale.provenance.classification,'SYNTHETIC_DEMO');assert.equal(sale.industry_fields.vehicle_id,stored.bindings['vehicle-0'].id);assert.equal(f.identities.list(f.ctx,f.actor).items[0].status,'INVITED');assert.equal(f.memory.search(f.ctx,f.actor).total,1);assert.equal(row.external_effects,false);assert.equal(row.full_acceptance,false);assert.equal(f.adapter.bucket(f.ctx,'communication:submissions').length,0);});
test('current capability denial blocks further native writes and preserves already applied seed work',()=>{const f=fixture();let row=reserve(f);row=advance(f,row,1);f.resolver.configure(f.ctx,f.actor,{industry_id:'AUTOMOTIVE',entitlements:['crm','procurement','sales','marketing','communication','calendar'],capability_flags:{'crm:companies':false},expected_revision:1});assert.throws(()=>advance(f,row),{code:'capability_disabled'});assert.equal(f.adapter.bucket(f.ctx,SCOPE)[0].cursor,1);assert.equal(f.adapter.bucket(f.ctx,'crm:companies').length,1);});
test('lost seed receipt after a durable native effect recovers after restart using the same native idempotency key',()=>{const f=fixture();let row=reserve(f);f.failReceiptAt(1);assert.throws(()=>advance(f,row,1),/seed receipt persistence failure/);assert.equal(f.adapter.bucket(f.ctx,'crm:companies').length,1);assert.equal(f.adapter.bucket(f.ctx,SCOPE)[0].cursor,0);f.allowPersistence();Object.assign(f,f.restart());row=f.engine.get(f.ctx,f.actor,row.id);row=advance(f,row,1);assert.equal(row.applied_nodes,1);assert.equal(f.adapter.bucket(f.ctx,'crm:companies').length,1);});
test('changed native dependency revisions cannot silently seed downstream records using an earlier scenario observation',()=>{const f=fixture();let row=reserve(f);row=advance(f,row,1);const binding=f.adapter.bucket(f.ctx,SCOPE)[0].bindings.company;f.crm.update(f.ctx,f.actor,'companies',binding.id,{name:'Changed after reservation'},{expectedRevision:1});assert.throws(()=>advance(f,row),{code:'demo_dependency_changed'});assert.equal(f.adapter.bucket(f.ctx,SCOPE)[0].cursor,1);});
test('seed metadata and replay are scoped to the current owner, tenant and exact confirmed manifest',()=>{const f=fixture(),row=reserve(f);assert.throws(()=>f.engine.get(f.ctx,{...f.actor,id:'different-owner'},row.id),{code:'demo_universe_missing'});assert.throws(()=>f.engine.get({...f.ctx,tenant_id:'other'},f.actor,row.id),{code:'demo_composition_required'});const p=f.engine.preview(f.ctx,f.actor,f.options);assert.throws(()=>f.engine.start(f.ctx,f.actor,{...f.options,plan_fingerprint:'a'.repeat(64),expected_profile_revision:p.profile_revision,confirm:true,reason:'Same confirmation'},'demo-other-start'),{code:'demo_plan_changed'});assert.equal(reserve(f).id,row.id);});
test('the complete flagship dataset passes the actual native contracts for every seed node',()=>{const f=fixture({full:true,durable:false});let row=reserve(f);while(row.status!=='SEEDED')row=advance(f,row);assert.equal(f.adapter.bucket(f.ctx,'crm:vehicles').length,200);assert.equal(f.adapter.bucket(f.ctx,'crm:people').length,720);assert.equal(f.adapter.bucket(f.ctx,'crm:leads').length,1200);assert.equal(f.adapter.bucket(f.ctx,'crm:activities').length,2600);assert.equal(f.domains.calendar.list(f.ctx,f.actor,'events').total,200);assert.equal(f.domains.sales.list(f.ctx,f.actor,'opportunities').total,140);assert.equal(f.adapter.bucket(f.ctx,'finance:invoices').length,142);assert.equal(f.adapter.bucket(f.ctx,'finance:payments').length,84);assert.equal(f.adapter.bucket(f.ctx,'finance:journal_entries').length,199);assert.ok(f.adapter.bucket(f.ctx,'finance:journal_entries').every(j=>j.debit_cents===j.credit_cents));assert.equal(row.full_acceptance,false);});
test('an empty demo scope may contain real bootstrap metadata but no business records, ZERO memories, decisions or queued tasks',()=>{const {hasBusinessData}=require('../demo-universe-engine'),ctx={tenant_id:'demo-test',dealer_id:'default'},prefix='demo-test:default:',metadata=['identity:members','composition:profiles','platform:migrations','platform:audit','finance:migrations','finance:audit_events'],records=new Map(metadata.map(s=>[prefix+s,[{id:'bootstrap-metadata'}]]));assert.equal(hasBusinessData(ctx,{records,memory:new Map(),tasks:new Map(),decisions:new Map()}),false);for(const name of ['records','memory','tasks','decisions']){const stores={records:new Map(records),memory:new Map(),tasks:new Map(),decisions:new Map()};stores[name].set(prefix+'customer_data',[{id:'existing-private-record'}]);assert.equal(hasBusinessData(ctx,stores),true);stores[name].delete(prefix+'customer_data');stores[name].set('another-tenant:default:customer_data',[{id:'foreign'}]);assert.equal(hasBusinessData(ctx,stores),false);}});
test('losing the final receipt for a multi-node batch replays exact native effects and binds the original records without duplicate identities',()=>{const f=fixture();let row=reserve(f);f.failReceiptAt(5);assert.throws(()=>advance(f,row,5),/seed receipt persistence failure/);assert.equal(f.adapter.bucket(f.ctx,SCOPE)[0].cursor,0);const ids=f.identities.list(f.ctx,f.actor).items.map(r=>r.id);assert.equal(ids.length,1);f.allowPersistence();Object.assign(f,f.restart());row=f.engine.get(f.ctx,f.actor,row.id);row=advance(f,row,5);assert.equal(row.applied_nodes,5);assert.equal(f.adapter.bucket(f.ctx,'crm:companies').length,2);assert.deepEqual(f.identities.list(f.ctx,f.actor).items.map(r=>r.id),ids);});
test('a lost demo receipt remains recoverable after more than two thousand subsequent native CRM requests and a restart',()=>{
 const f=fixture();let row=reserve(f);f.failReceiptAt(1);assert.throws(()=>advance(f,row,1),/seed receipt persistence failure/);
 const original=f.adapter.bucket(f.ctx,'crm:companies')[0].id;f.allowPersistence();
 for(let i=0;i<2001;i++)f.crm.create(f.ctx,f.actor,'notes',{content:'Subsequent native activity '+i},{idempotencyKey:'native-retention-'+i});
 Object.assign(f,f.restart());row=f.engine.get(f.ctx,f.actor,row.id);row=advance(f,row,1);
 assert.equal(row.applied_nodes,1);assert.deepEqual(f.adapter.bucket(f.ctx,'crm:companies').map(r=>r.id),[original]);
 assert.equal(f.adapter.bucket(f.ctx,SCOPE)[0].bindings.company.id,original);
});
test('CRM receipt capacity refuses new effects while existing requests still replay under current authorization',()=>{
 const f=fixture({durable:false}),key='native-capacity-existing',input={name:'Existing receipt'};
 const first=f.crm.create(f.ctx,f.actor,'companies',input,{idempotencyKey:key}),receipts=f.adapter.bucket(f.ctx,'crm:idempotency');
 // Capacity setup only: these are old request tombstones, not business data.
 for(let i=receipts.length;i<100000;i++)receipts.push({digest:'capacity-'+i});
 assert.throws(()=>f.crm.create(f.ctx,f.actor,'companies',{name:'Must not be written'},{idempotencyKey:'native-capacity-new'}),{code:'crm_request_capacity'});
 assert.equal(f.adapter.bucket(f.ctx,'crm:companies').length,1);assert.equal(receipts.length,100000);
 assert.equal(f.crm.create(f.ctx,f.actor,'companies',input,{idempotencyKey:key}).id,first.id);
 assert.throws(()=>f.crm.create(f.ctx,{...f.actor,roles:['VIEWER']},'companies',input,{idempotencyKey:key}),{code:'crm_forbidden'});
});
test('a confirmed demo graph survives generator changes and restart without abandoning its applied records',()=>{
 const f=fixture();let row=reserve(f);row=advance(f,row,1);const fingerprint=row.plan_fingerprint;
 Object.assign(f,f.restart());f.engine.build=()=>{throw Error('New generator is incompatible with the original version');};
 row=f.engine.get(f.ctx,f.actor,row.id);row=advance(f,row);
 assert.equal(row.status,'SEEDED');assert.equal(row.plan_fingerprint,fingerprint);assert.equal(f.adapter.bucket(f.ctx,'crm:companies').length,2);
});
test('a modified retained graph is rejected before any native write',()=>{
 const f=fixture(),row=reserve(f),{MANIFESTS}=require('../demo-universe-engine');
 f.adapter.bucket(f.ctx,MANIFESTS)[0].nodes[0].input.name+=' altered';
 assert.throws(()=>advance(f,row,1),{code:'demo_manifest_fingerprint_invalid'});assert.equal(f.adapter.bucket(f.ctx,'crm:companies').length,0);
});
