'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/fixture');
test('native domain recovery retrieves only its current actor/entity result or permanently closes an absent request without a record change',async()=>{
 const f=await fixture();try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['sales','analysis'],expected_revision:0})).status,200);const key='domain-terminal-request-001',review={entity:'opportunities',target_id:null,expected_revision:0,confirm:true},route='/api/sales/record-requests/'+key+'/recover',input={title:'Literal terminal candidate'},headers={'idempotency-key':key};
  const schema=await f.request('/api/analysis/schema');assert.deepEqual(schema.body.request_context,{tenant_id:'zero-evaluation',dealer_id:'default',actor_id:'evaluation-bootstrap'});const report=await f.request('/api/analysis/reports','POST',{title:'Literal report recovery',content:'Source-bound retained report'},null,{'idempotency-key':'domain-analysis-recovery'});assert.equal(report.status,201);const recoveredReport=await f.request('/api/analysis/record-requests/domain-analysis-recovery/recover','POST',{...review,entity:'reports'});assert.equal(recoveredReport.status,200);assert.deepEqual(recoveredReport.body.record,report.body.record);
  const result=await f.request(route,'POST',review);assert.equal(result.status,200);assert.equal(result.body.state,'NOT_APPLIED');assert.equal(result.body.request_id,key);assert.equal(result.body.actor_id,'evaluation-bootstrap');assert.equal(result.body.entity,'opportunities');assert.equal((await f.request('/api/sales/opportunities','POST',input,null,headers)).body.code,'record_request_abandoned');assert.equal((await f.request('/api/sales/opportunities')).body.total,0);await f.stop();await f.start();assert.deepEqual((await f.request(route,'POST',review)).body,result.body);
  const created=await f.request('/api/sales/opportunities','POST',input,null,{'idempotency-key':'domain-applied-request-001'});assert.equal(created.status,201);const receipt='/api/sales/record-requests/domain-applied-request-001/recover';assert.deepEqual((await f.request(receipt,'POST',review)).body.record,created.body.record);assert.equal((await f.request(receipt,'POST',{...review,entity:'tasks'})).status,409);
  assert.equal((await f.request('/api/sales/opportunities/'+created.body.record.id,'PUT',{title:'Current newer record',expected_revision:1})).status,200);assert.equal((await f.request(receipt,'POST',review)).body.code,'record_request_superseded');
  const other=await f.enroll('domain.recovery.other',['SALES']);const isolated=await f.request(receipt,'POST',review,other.cookie);assert.equal(isolated.status,200);assert.equal(isolated.body.state,'NOT_APPLIED');assert.ok(!JSON.stringify(isolated.body).includes(created.body.record.id));
  const owner=await f.enroll('domain.recovery.owner',['SALES']),owned=await f.request('/api/sales/opportunities','POST',{title:'Private old ownership'},owner.cookie,{'idempotency-key':'domain-former-owner-request'});assert.equal(owned.status,201);assert.equal((await f.request('/api/sales/opportunities/'+owned.body.record.id,'PUT',{owner_id:other.member.id,expected_revision:1})).status,200);const inaccessible=await f.request('/api/sales/record-requests/domain-former-owner-request/recover','POST',review,owner.cookie);assert.equal(inaccessible.status,409);assert.equal(inaccessible.body.code,'record_request_unavailable');assert.ok(!JSON.stringify(inaccessible.body).includes('Private old ownership'));
 }finally{await f.close();}
});
test('domain terminal recovery closes a held HTTP body before it can commit and rolls back its terminal key when persistence fails',async()=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'domain-terminal-fault-')),marker=path.join(dir,'fail'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/identity-persistence-fault'),FOUNDLY_IDENTITY_FAIL_FILE:marker});let held;
 try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['sales'],expected_revision:0})).status,200);const key='domain-held-body-request',input={title:'Literal held domain body'},body=JSON.stringify(input),review={entity:'opportunities',target_id:null,expected_revision:0,confirm:true},route='/api/sales/record-requests/'+key+'/recover';
  fs.writeFileSync(marker,'fail');try{assert.equal((await f.request(route,'POST',review)).status,500);}finally{fs.rmSync(marker,{force:true});}
  const pending=new Promise((resolve,reject)=>{held=require('node:http').request(f.base+'/api/sales/opportunities',{method:'POST',headers:{authorization:'Bearer '+f.env.FOUNDLY_ADMIN_TOKEN,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(body),'idempotency-key':key}},res=>{let data='';res.on('data',part=>data+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(data)}));});held.on('error',reject);held.flushHeaders();held.write(body.slice(0,-1));});
  assert.equal((await f.request(route,'POST',review)).body.state,'NOT_APPLIED');held.end(body.slice(-1));const late=await pending;assert.equal(late.status,409);assert.equal(late.body.code,'record_request_abandoned');assert.equal((await f.request('/api/sales/opportunities')).body.total,0);
 }finally{held?.destroy();fs.rmSync(marker,{force:true});await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
