'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{BusinessDomain}=require('../business-domains'),{CapabilityResolver}=require('../capability-resolver');
function fixture(){const state=new Map(),ctx={tenant_id:'domain_guard_fixture',dealer_id:'default'},actor={id:'domain_guard_owner',roles:['SUPER_ADMIN']},adapter={bucket(c,scope){const key=JSON.stringify([c,scope]);if(!state.has(key))state.set(key,[]);return state.get(key);},persist(){},audit(){},publish(){}};const resolver=new CapabilityResolver(adapter);resolver.configure(ctx,actor,{entitlements:['sales'],expected_revision:0});return {ctx,actor,adapter,resolver,core:new BusinessDomain('sales',adapter,resolver)};}
test('legacy domain request evidence is retained but cannot falsely verify a result revision it never recorded',()=>{
 const f=fixture(),input={title:'Literal legacy record'},key='domain-legacy-request',first=f.core.save(f.ctx,f.actor,'opportunities',input,{idempotency_key:key}),rows=f.adapter.bucket(f.ctx,'sales:idempotency'),receipt=rows[0];delete receipt.receipt_version;delete receipt.result_revision;delete receipt.expected_revision;const before=JSON.stringify(rows);assert.throws(()=>f.core.save(f.ctx,f.actor,'opportunities',input,{idempotency_key:key}),{code:'record_request_unverifiable'});assert.equal(JSON.stringify(rows),before);assert.equal(f.core.get(f.ctx,f.actor,'opportunities',first.record.id).revision,1);assert.equal(f.adapter.bucket(f.ctx,'sales:outbox').length,1);
});
test('bounded generic request storage preserves existing retries and current owner and capability checks',()=>{
 const f=fixture(),input={title:'Literal bounded record'},key='domain-bounded-request',first=f.core.save(f.ctx,f.actor,'opportunities',input,{idempotency_key:key}),rows=f.adapter.bucket(f.ctx,'sales:idempotency');for(let n=1;n<100000;n++)rows.push({key:'other-'+n,actor_id:'other'});
 assert.equal(f.core.save(f.ctx,f.actor,'opportunities',input,{idempotency_key:key}).deduplicated,true);assert.throws(()=>f.core.save(f.ctx,f.actor,'opportunities',{title:'Capacity must not mutate'},{idempotency_key:'domain-over-capacity'}),{code:'record_request_capacity'});assert.equal(f.core.list(f.ctx,f.actor,'opportunities').total,1);assert.equal(f.adapter.bucket(f.ctx,'sales:outbox').length,1);assert.equal(rows.length,100000);
 assert.throws(()=>f.core.save(f.ctx,{id:'other',roles:['SALES']},'opportunities',{title:'Cannot edit another owner'},{id:first.record.id,expected_revision:1,idempotency_key:key}),{code:'record_not_found'});
 f.resolver.configure(f.ctx,f.actor,{entitlements:['sales'],enabled_modules:[],expected_revision:1});assert.throws(()=>f.core.save(f.ctx,f.actor,'opportunities',input,{idempotency_key:key}),{code:'module_disabled'});
});
