'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('../zero-evaluation/fixture'),{create}=require('../zero-evaluation/finance-action-page-http-fixture'),{act}=require('../zero-evaluation/finance-action-client-fixture');
async function fill(view,entity,kind,number){
 await view.set('legal_entity',entity.id);await view.set('invoice_kind',kind);
 for(const[key,value]of Object.entries({number,date:'2026-09-01',supply_date:'2026-09-01',due_date:'2026-09-30',supplier_name:'PRIVATE_CREATED_SUPPLIER',supplier_address:'Explicit supplier source',supplier_vat_id:'DEMO-NOT-REAL',supplier_kvk_number:'DEMO-NOT-REAL',customer_name:'PRIVATE_CREATED_CUSTOMER',customer_address:'Explicit customer source'}))await view.set(key,value);
 for(const[key,value]of Object.entries({description:'Explicit first line',quantity:'1.5',unit_price:'10,01',tax_rate:'21'}))await view.setLine(0,key,value);
 await view.button('add_line').fire('click');for(const[key,value]of Object.entries({description:'Explicit second line',quantity:'2',unit_price:'5.50',tax_rate:'9'}))await view.setLine(1,key,value);
}
async function submit(view){await view.button('preview').fire('click');await view.confirm();await view.button('submit').fire('click');}
for(const industry of ['AUTOMOTIVE','ECOMMERCE'])test(industry+' production Finance page creates native and ZERO drafts, refreshes current invoices and recovers a lost creation response after approval and posting', {timeout:60000},async()=>{
 const s=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/finance-http-faults')});
 try{
  assert.equal((await s.request('/api/composition','PUT',{industry_id:industry,entitlements:['finance'],expected_revision:0})).status,200);
  const admin=await s.enroll('creation.admin.'+industry.toLowerCase(),['FINANCE_ADMIN']),accountant=await s.enroll('creation.accountant.'+industry.toLowerCase(),['ACCOUNTANT']),approver=await s.enroll('creation.approver.'+industry.toLowerCase(),['APPROVER']);
  const call=(member,route,method='GET',body)=>s.request(route,method,body,member.cookie),native=(...args)=>call(admin,...args);
  const entity=(await native('/api/finance/legal-entities','POST',{name:'[SYNTHETIC DEMO] Creation UI',legal_form:'BV',address:'Explicit legal address',vat_id:'DEMO-NOT-REAL',kvk_number:'DEMO-NOT-REAL'})).body;
  assert.equal((await native('/api/finance/periods','POST',{legal_entity_id:entity.id,start_date:'2026-01-01',end_date:'2026-12-31'})).status,201);assert.equal((await native('/api/finance/legal-entities/'+entity.id+'/bootstrap-chart','POST',{})).status,201);
  const html=await call(accountant,'/finance');assert.equal(html.status,200);assert.ok(html.body.includes('id="financeCreate"'));assert.equal((await call(accountant,'/finance-invoice-actions-client.js')).status,200);
  let page=await create(s,accountant);assert.ok(page.creation);await fill(page.creation,entity,'SALES','UI-CREATE-SALE');await submit(page.creation);
  let invoices=(await native('/api/finance/records/invoices?limit=100')).body.items;assert.equal(invoices.length,1,page.creation.box.textContent);const sale=invoices[0];assert.equal(sale.status,'DRAFT');assert.equal(sale.gross_cents,3016);assert.ok(page.field('document').children.some(row=>row.value===sale.id),'Completed creation refreshes the current invoice picker');assert.equal((await native('/api/finance/records/journal_entries')).body.total,0);
  await act(page,'INVOICE_POST',sale.id);assert.equal((await native('/api/finance/records/journal_entries')).body.total,1);
  await page.transport('zero');await fill(page.creation,entity,'PURCHASE','UI-CREATE-PURCHASE');page.loseNext('/api/zero/turn');await submit(page.creation);assert.equal(page.creation.box.canLeave(),false);assert.ok(page.calls.some(c=>c.body?.client_context?.finance_action?.operation==='INVOICE_CREATE_EXECUTE'));
  invoices=(await native('/api/finance/records/invoices?limit=100')).body.items;assert.equal(invoices.length,2);const purchase=invoices.find(row=>row.kind==='PURCHASE');assert.equal(purchase.approval_status,'PENDING');assert.equal(purchase.gross_cents,3016);assert.equal((await native('/api/finance/records/journal_entries')).body.total,1);
  const retained=(await call(accountant,'/api/finance/invoice-actions/confirmations?operation=INVOICE_CREATE')).body;assert.equal(retained.total,1);const command=retained.items[0].command;assert.equal((await call(approver,'/api/finance/invoice-actions/recover','POST',command)).status,403);
  page.box.isConnected=page.creation.box.isConnected=false;await s.stop();await s.start();for(const member of [admin,accountant,approver])member.cookie=await s.login(member);
  assert.equal((await call(accountant,'/api/finance/invoices/'+purchase.id+'/post','POST',{})).status,409);const review=await create(s,approver);assert.equal(review.creation,undefined);await act(review,'INVOICE_APPROVE',purchase.id);assert.equal((await call(accountant,'/api/finance/invoices/'+purchase.id+'/post','POST',{})).status,200);
  const {operation,...input}=command,zero=await call(accountant,'/api/zero/turn','POST',{message:command.reason,conversation_id:crypto.randomUUID(),turn_id:crypto.randomUUID(),client_context:{finance_action:{operation:'INVOICE_CREATE_RECOVER',input}}});assert.equal(zero.status,200,JSON.stringify(zero.body));assert.equal(zero.body.finance_data.original_result.invoice.status,'DRAFT');assert.equal(zero.body.finance_data.current_invoice.status,'POSTED');assert.equal(zero.body.verification.financial_posting_performed,false);
  page=await create(s,accountant);assert.equal(page.creation.box.open,true);await page.creation.button('recover').fire('click');assert.equal(page.creation.box.canLeave(),true,page.creation.box.textContent);assert.equal(page.calls.filter(c=>c.route==='/api/finance/invoice-actions/execute').length,0);assert.equal((await native('/api/finance/records/invoices?limit=100')).body.total,2);assert.equal((await native('/api/finance/records/journal_entries')).body.total,2);assert.equal((await native('/api/finance/records/payments')).body.total,0);
  await fill(page.creation,entity,'SALES','UI-CREATE-SALE');await page.creation.button('preview').fire('click');assert.equal(page.creation.button('submit').disabled,true);assert.ok(page.creation.box.textContent.includes(page.context.FoundlyI18n.t('finance.actions.block_duplicate')));
  assert.equal((await s.request('/api/composition','PUT',{industry_id:industry,entitlements:['finance'],capability_flags:{'finance:invoices':false},expected_revision:1})).status,200);await page.context.load(true);assert.equal(page.nodes.financeCreate.textContent,'');assert.equal(page.nodes.financeActions.textContent,'');assert.equal((await call(accountant,'/api/finance/invoice-actions/recover','POST',command)).status,403);
  const raw=fs.readFileSync(path.join(s.dir,'foundly-core-state.json'),'utf8');assert.ok(!raw.includes('PRIVATE_CREATED_CUSTOMER'));assert.ok(!raw.includes('PRIVATE_CREATED_SUPPLIER'));
 }finally{await s.close();}
});
