'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {create}=require('../zero-evaluation/finance-action-client-fixture'),{locales}=require('../foundly-locales');
const root='/api/finance/invoice-actions/';
function creation(options={}){const f=create({...options,invoiceCreation:true});f.line=(index,key)=>f.box.all().filter(n=>n.getAttribute('data-finance-line')!==null)[index].all().find(n=>n.getAttribute('data-finance-line-field')===key);f.setLine=async(index,key,value)=>{const node=f.line(index,key);node.value=value;await node.fire('input');};return f;}
async function fill(f,kind='SALES',number='NEW-SOURCE-001'){
 await f.box.ready;await f.set('legal_entity',f.native.entity.id);await f.set('invoice_kind',kind);
 for(const [key,value]of Object.entries({number,date:'2026-09-01',supply_date:'2026-09-01',due_date:'2026-09-30',supplier_name:'Source supplier <img>',supplier_address:'Source supplier address',supplier_vat_id:'SOURCE-NOT-REAL',supplier_kvk_number:'SOURCE-NOT-REAL',customer_name:'Source customer',customer_address:'Source customer address'}))await f.set(key,value);
 for(const [key,value]of Object.entries({description:'First native line <img>',quantity:'1.5',unit_price:'10,01',tax_rate:'21'}))await f.setLine(0,key,value);
}
async function submit(f){await f.button('preview').fire('click');await f.confirm();await f.button('submit').fire('click');}
for(const kind of ['SALES','PURCHASE'])test(kind+' draft creation preserves exact multi-line amounts and separate approval/posting, with source review in eight locales',async()=>{
 const f=creation();await fill(f,kind);await f.button('add_line').fire('click');for(const[key,value]of Object.entries({description:'Second native line',quantity:'2',unit_price:'5.50',tax_rate:'9'}))await f.setLine(1,key,value);
 await f.button('preview').fire('click');assert.ok(f.box.textContent.includes('First native line <img>'));assert.ok(f.box.textContent.includes('Second native line'));assert.ok(!f.box.all().some(n=>n.tag==='img'));assert.equal(f.native.rows('invoices').length,0);await f.confirm();const calls=f.calls.length;
 for(const locale of locales){f.context.FoundlyI18n.setLocale(locale);assert.equal(f.calls.length,calls);assert.equal(f.field('confirm').checked,true);assert.equal(f.line(0,'unit_price').value,'10,01');assert.ok(f.box.textContent.includes(f.context.FoundlyI18n.currencyCents(3016,'EUR')));assert.equal(f.context.FoundlyI18n.missingKeys().length,0);}
 await f.button('submit').fire('click');assert.equal(f.native.rows('invoices').length,1,f.box.textContent);const invoice=f.native.rows('invoices')[0];assert.equal(invoice.gross_cents,3016);assert.equal(invoice.net_cents,2602);assert.equal(invoice.kind,kind);assert.equal(invoice.status,'DRAFT');assert.equal(invoice.approval_status,kind==='PURCHASE'?'PENDING':'NOT_REQUIRED');assert.equal(f.native.rows('invoice_lines').length,2);assert.equal(f.native.rows('journal_entries').length,0);assert.equal(f.native.rows('payments').length,0);assert.equal(f.box.canLeave(),true);
});
test('creation rejects missing parties, invalid quantity, tax and money before confirmation; line edits invalidate review',async()=>{
 const f=creation();await fill(f);for(const [key,value]of [['quantity','0'],['quantity','1e2'],['unit_price','1,234'],['tax_rate','101']]){const node=f.line(0,key),old=node.value;await f.setLine(0,key,value);await f.button('preview').fire('click');await f.confirm();await f.button('submit').fire('click');assert.equal(f.native.rows('invoices').length,0);await f.setLine(0,key,old);}
 const address=f.field('customer_address').value;await f.set('customer_address','');await f.button('preview').fire('click');assert.equal(f.native.rows('invoices').length,0);await f.set('customer_address',address);
 await f.button('preview').fire('click');await f.confirm();await f.setLine(0,'description','New reviewed source');assert.equal(f.field('confirm').checked,false);assert.equal(f.button('submit').disabled,true);await submit(f);assert.equal(f.native.rows('invoices').length,1);
});
test('native creation lost before acknowledgement reappears after reload and recovers original draft separately from a later posted invoice',async()=>{
 const f=creation();await fill(f);f.lose(root+'execute');await submit(f);assert.equal(f.box.canLeave(),false);assert.equal(f.native.rows('invoices').length,1);const invoice=f.native.rows('invoices')[0];f.detach();f.native.restart();f.native.core.postInvoice(f.native.ctx,f.native.actor,invoice.id);
 const next=creation({native:f.native});await next.box.ready;assert.equal(next.box.open,true);assert.equal(next.box.canLeave(),false);await next.button('recover').fire('click');assert.equal(next.box.canLeave(),true,next.box.textContent);assert.equal(next.native.rows('invoices').length,1);assert.equal(next.native.rows('journal_entries').length,1);assert.equal(next.calls.filter(c=>c.route.endsWith('/execute')).length,0);assert.ok(next.box.textContent.includes(next.context.FoundlyI18n.t('finance.actions.status_draft')));assert.ok(next.box.textContent.includes(next.context.FoundlyI18n.t('finance.actions.status_posted')));
});
test('current legal entity change rejects stale creation and explicit recovery retires it without creating a draft',async()=>{
 const f=creation();await fill(f);await f.button('preview').fire('click');await f.confirm();f.native.rows('legal_entities')[0].name+=' current change';await f.button('submit').fire('click');assert.equal(f.native.rows('invoices').length,0);assert.equal(f.box.canLeave(),false);await f.button('recover').fire('click');assert.equal(f.box.canLeave(),false);assert.equal(f.field('number').value,'NEW-SOURCE-001');assert.equal(f.line(0,'description').value,'First native line <img>');assert.equal(f.native.rows('invoices').length,0);await submit(f);assert.equal(f.native.rows('invoices').length,1);assert.equal(f.box.canLeave(),true);
});
test('business fill uses only actual entity data, line count remains bounded and dirty input prevents paging or reload loss',async()=>{
 const f=creation();await fill(f);await f.button('fill_business').fire('click');assert.equal(f.field('supplier_name').value,f.native.entity.name);assert.equal(f.field('supplier_address').value,'');assert.equal(f.field('supplier_vat_id').value,'');
 for(let i=1;i<50;i++)await f.button('add_line').fire('click');assert.equal(f.box.all().filter(n=>n.getAttribute('data-finance-line')!==null).length,50);assert.equal(f.button('add_line').disabled,true);await f.button('remove_line').fire('click');assert.equal(f.box.all().filter(n=>n.getAttribute('data-finance-line')!==null).length,49);assert.equal(f.box.canLeave(),false);assert.equal(await f.box.refresh(),false);await f.button('clear').fire('click');assert.equal(f.box.canLeave(),true);assert.equal(f.box.all().filter(n=>n.getAttribute('data-finance-line')!==null).length,1);
});
test('detaching a creation controller during durable confirmation retention prevents the late execution',{timeout:5000},async()=>{
 const f=creation();await fill(f);await f.button('preview').fire('click');await f.confirm();const release=f.hold(root+'confirmations'),running=f.button('submit').fire('click');await release.started;f.detach();release();await running;assert.equal(f.native.rows('invoices').length,0);const next=creation({native:f.native});await next.box.ready;await next.button('recover').fire('click');assert.equal(next.native.rows('invoices').length,0);assert.equal(next.field('number').value,'NEW-SOURCE-001');assert.equal(next.box.canLeave(),false);await next.button('clear').fire('click');assert.equal(next.box.canLeave(),true);
});
test('legal-entity paging preserves authored invoice lines and uses the explicitly selected native currency',async()=>{
 const f=creation();for(let i=0;i<51;i++)f.native.core.createLegalEntity(f.native.ctx,f.native.actor,{name:'Other entity '+i,legal_form:'BV',currency:'USD'});await fill(f);await f.button('next').fire('click');assert.equal(f.field('customer_name').value,'Source customer');assert.equal(f.line(0,'unit_price').value,'10,01');assert.equal(f.field('confirm').checked,false);
 const entity=f.native.rows('legal_entities').at(-1);await f.set('legal_entity',entity.id);await submit(f);const invoice=f.native.rows('invoices')[0];assert.equal(invoice.legal_entity_id,entity.id);assert.equal(invoice.currency,'USD');assert.equal(invoice.gross_cents,1817);
});
test('a failed invoice-list refresh after durable creation remains a known saved draft and never offers financial retry',async()=>{
 const f=creation({onComplete:async()=>{throw Error('Read-only list unavailable');}});await fill(f);await submit(f);assert.equal(f.native.rows('invoices').length,1);assert.equal(f.box.canLeave(),true);assert.equal(f.native.core.listInvoiceActionConfirmations(f.native.ctx,f.native.actor,{operation:'INVOICE_CREATE'}).total,0);assert.ok(f.box.textContent.includes(f.context.FoundlyI18n.t('finance.actions.saved_refresh_needed')));assert.equal(f.button('recover').disabled,true);assert.equal(f.calls.filter(c=>c.route.endsWith('/execute')).length,1);
});
test('a source-list read failure after acknowledgement cannot turn a saved draft into an uncertain financial attempt',async()=>{
 const f=creation();await fill(f);f.lose('/api/finance/records/legal_entities');await submit(f);assert.equal(f.native.rows('invoices').length,1);assert.equal(f.native.core.listInvoiceActionConfirmations(f.native.ctx,f.native.actor,{operation:'INVOICE_CREATE'}).total,0);assert.ok(f.box.textContent.includes(f.context.FoundlyI18n.t('finance.actions.saved_refresh_needed')));assert.equal(f.button('recover').disabled,true);await f.button('clear').fire('click');assert.equal(f.box.canLeave(),true);assert.equal(f.native.rows('invoices').length,1);
});
test('a reload that finds the retained creation but fails to read entity choices still enables explicit outcome recovery',async()=>{
 const f=creation();await fill(f);f.lose(root+'execute');await submit(f);f.detach();const next=creation({native:f.native});next.lose('/api/finance/records/legal_entities');await next.box.ready;assert.equal(next.button('recover').disabled,false);await next.button('recover').fire('click');assert.equal(next.native.rows('invoices').length,1);assert.equal(next.box.canLeave(),true);assert.equal(next.calls.filter(c=>c.route.endsWith('/execute')).length,0);
});
