'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('../zero-evaluation/finance-page-fixture');
const {locales}=require('../foundly-i18n');
test('denied Finance refresh clears private ledger observations and mounted editor source evidence',async()=>{
 const f=fixture();await f.context.load();assert.ok(f.nodes.financePnl.textContent.includes('Literal private'));f.deny();await f.context.load();assert.equal(f.nodes.financePnl.textContent,'');assert.equal(f.nodes.financeJournal.textContent,'');assert.equal(f.nodes.financePeriodClosing.textContent,'');
});
test('missing Finance aging buckets cannot prove that no balance is overdue',async()=>{
 const f=fixture();delete f.reports.ar_aging.buckets['1_30'];await f.context.load();assert.notEqual(f.nodes.financeAgingBadge.textContent,'GEEN ACHTERSTAND');assert.equal(f.nodes.financeAgingBadge.textContent,f.i.t('common.unknown'));
});
test('Finance amounts retain exact cents and never coerce malformed values into money',async()=>{
 const f=fixture();await f.context.load();for(const locale of locales){f.i.setLocale(locale);for(const amount of [-1,0,123450,Number.MAX_SAFE_INTEGER])assert.equal(f.context.money(amount),f.i.currencyCents(amount,'EUR'));for(const amount of [null,undefined,false,true,'1234',1.2,Infinity,NaN])assert.equal(f.context.money(amount),f.i.t('common.unknown'));}
});
test('late Finance ZERO replies and exports cannot restore or download prior data after access denial',async()=>{
 for(const route of ['/api/zero/turn','/api/finance/exports']){const f=fixture();await f.context.load();f.nodes.financeZeroInput.value='Literal question';const release=f.hold(route),pending=route.endsWith('/turn')?f.context.askZero({preventDefault(){}}):f.context.exportJournal();await release.started;f.deny();await f.context.load();release();await pending;assert.equal(f.nodes.financeZeroOutput.textContent,'');assert.equal(f.downloads.length,0);assert.equal(f.nodes.exportFinance.disabled,true);assert.equal(f.nodes.financeZeroInput.disabled,true);assert.ok(!f.nodes.financeNotice.textContent.includes('RAW_PRIVATE_ERROR'));}
});
test('scoped report denial invalidates late exports while independently authorized entity observations remain',async()=>{
 const f=fixture();await f.context.load();const release=f.hold('/api/finance/exports'),pending=f.context.exportJournal();await release.started;f.errors.set('/api/finance/reports?legal_entity_id=entity_literal',403);await f.context.load();release();await pending;assert.equal(f.downloads.length,0);assert.equal(f.nodes.financeJournal.textContent,'');assert.ok(f.nodes.financeEntity.textContent.includes('Literal private entity'));assert.equal(f.nodes.exportFinance.disabled,true);assert.ok(!f.nodes.financePnlEmpty.textContent.includes('RAW_PRIVATE_ERROR'));
});
test('a dirty Finance editor keeps its confirmation state when access is unchanged and is removed when current access is revoked',async()=>{
 const f=fixture();await f.context.load();const editor=f.editors.at(-1);editor.dirty=true;const before=f.calls.length;await f.context.load();assert.equal(f.editors.at(-1),editor);assert.equal(f.calls.length,before+1);assert.equal(f.calls.at(-1).route,'/api/composition');assert.equal(editor.options.isActive(),true);f.deny();await f.context.load();assert.equal(editor.options.isActive(),false);assert.equal(f.nodes.financePeriodClosing.textContent,'');assert.equal(f.nodes.financeJournal.textContent,'');
});
test('pending Finance requests reject duplicates and authorized native exports retain exact payload and CSV bytes',async()=>{
 const f=fixture();await f.context.load();f.nodes.financeFrom.value='2026-01-01';f.nodes.financeTo.value='2026-09-24';const release=f.hold('/api/finance/exports'),pending=f.context.exportJournal();await release.started;const before=f.calls.length;await f.context.exportJournal();assert.equal(f.calls.length,before);release();await pending;assert.deepEqual(JSON.parse(f.calls.at(-1).options.body),{scope:'journal_entries',format:'CSV',filters:{legal_entity_id:'entity_literal',from:'2026-01-01T00:00:00.000Z',to:'2026-09-24T23:59:59.999Z'}});assert.equal(f.downloads[0].parts[0],'Literal CSV bytes');assert.equal(f.nodes.exportFinance.disabled,false);
});
test('Finance durability and forecast availability require boolean evidence and missing aging does not retain a stale badge',async()=>{
 const f=fixture();f.status.persistence.durable='false';f.reports.cash_forecast={available:'true',opening_cash_cents:0};await f.context.load();assert.ok(f.nodes.financeNotice.textContent.includes(f.i.t('finance.page.durable_unknown')));assert.equal(f.key('opening'),undefined);delete f.reports.ar_aging;await f.context.load();assert.equal(f.nodes.financeAgingBadge.textContent,f.i.t('common.unknown'));
});
test('missing Finance journal and profit rows remain unknown while native empty arrays remain observed empty data',async()=>{
 const f=fixture();await f.context.load();delete f.reports.general_ledger.entries;delete f.reports.profit_and_loss.rows;await f.context.load();assert.equal(f.nodes.journalCount.textContent,f.i.t('common.unknown'));assert.equal(f.nodes.financeJournalEmpty.textContent,f.i.t('common.no_data'));assert.equal(f.nodes.financePnlEmpty.textContent,f.i.t('common.no_data'));f.reports.general_ledger.entries=[];f.reports.profit_and_loss.rows=[];await f.context.load();assert.equal(f.nodes.journalCount.textContent,f.i.t('finance.page.entries',{value:f.i.number(0)}));assert.equal(f.nodes.financePnlEmpty.textContent,f.i.t('finance.page.pnl_empty'));
});
test('Finance page source observations, exact cents and UTC dates update in eight locales without reads or replacing controls and source rows',async()=>{
 const f=fixture();f.reports.cash_forecast={available:true,forecast_id:'Literal forecast',currency:'USD',horizon_days:90,opening_cash_cents:-1,closing_cash_cents:123450,assumptions:[]};f.reports.budget_vs_actual={available:true,budget_cents:123450,actual_cents:0,variance_cents:-123450};f.reports.general_ledger.entries[0].entry_type='POSTED';await f.context.load();f.nodes.financeFrom.value='2026-01-01';f.nodes.financeTo.value='2026-09-24';f.nodes.financeZeroInput.value='Literal authored question';const n=f.calls.length,editorCount=f.editors.length,journal=f.nodes.financeJournal.children[0],pnl=f.nodes.financePnl.children[0],kpi=f.nodes.financeKpis.children[0],source=JSON.stringify(f.reports);
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,n);assert.equal(f.editors.length,editorCount);assert.equal(f.nodes.financeJournal.children[0],journal);assert.equal(f.nodes.financePnl.children[0],pnl);assert.equal(f.nodes.financeKpis.children[0],kpi);assert.equal(f.nodes.financeEntity.value,'entity_literal');assert.ok(f.nodes.financeEntity.textContent.includes('Literal private entity'));assert.equal(f.nodes.financeZeroInput.value,'Literal authored question');assert.equal(f.nodes.financeFrom.value,'2026-01-01');assert.equal(f.nodes.financeTo.value,'2026-09-24');assert.equal(kpi.children[0].textContent,f.i.t('finance.page.kpi.revenue'));assert.equal(kpi.children[1].textContent,f.i.currencyCents(123450,'EUR'));assert.equal(pnl.children[0].textContent,'4000 · Literal private <img> account');assert.equal(pnl.children[0].children.length,0);assert.equal(pnl.children[1].textContent,f.i.t('finance.page.enum.revenue'));assert.equal(pnl.children[4].textContent,f.i.currencyCents(-123450,'EUR'));assert.equal(journal.children[1].textContent,f.i.date('2026-01-01',{dateStyle:'medium'}));assert.equal(journal.children[2].textContent,f.i.t('finance.page.enum.posted'));assert.equal(journal.children[3].textContent,'Literal private journal');assert.equal(journal.children[5].textContent,'Literal source');assert.equal(f.nodes.financeAgingBadge.textContent,f.i.t('finance.page.overdue',{amount:f.i.currencyCents(100,'EUR')}));assert.equal(f.key('opening').parentNode.children[1].textContent,f.i.currencyCents(-1,'USD'));assert.equal(f.key('assumptions').parentNode.children[1].textContent,f.i.number(0));assert.equal(f.key('trial_balance').parentNode.children[1].textContent,f.i.t('finance.page.balanced'));assert.equal(f.nodes.financeNotice.textContent,f.i.t('finance.page.loaded',{storage:f.i.t('finance.page.durable_unknown'),observed:f.i.date(f.reports.observed_at,{dateStyle:'medium',timeStyle:'medium',timeZone:'UTC'}),entities:''}));assert.equal(JSON.stringify(f.reports),source);assert.equal(f.i.missingKeys().length,0);}
});
test('Finance missing metrics, empty lists and unavailable components retain localized evidence distinctions',async()=>{
 const f=fixture();f.dashboard.widgets=[{id:'cash',value_cents:null},{id:'revenue',available:'true',value_cents:123450}];f.reports.profit_and_loss.rows=[];f.reports.general_ledger.entries=[];f.reports.trial_balance.balanced='true';delete f.reports.ar_aging.buckets['31_60'];f.reports.cash_forecast={available:false};await f.context.load();const n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);for(const card of f.nodes.financeKpis.children)assert.equal(card.children[1].textContent,f.i.t('common.unknown'));assert.equal(f.nodes.financeAgingBadge.textContent,f.i.t('common.unknown'));assert.equal(f.key('trial_balance').parentNode.children[1].textContent,f.i.t('common.unknown'));assert.equal(f.nodes.financePnlEmpty.textContent,f.i.t('finance.page.pnl_empty'));assert.equal(f.nodes.financeJournalEmpty.textContent,f.i.t('finance.page.journal_empty'));assert.equal(f.key('budget').parentNode.children[1].textContent,f.i.t('finance.page.no_budget'));assert.equal(f.key('forecast').parentNode.children[1].textContent,f.i.t('finance.page.no_forecast'));assert.equal(f.calls.length,n);assert.equal(f.i.missingKeys().length,0);}
});
test('Finance loading and denied feedback change locale in place and cannot restore cleared source text',async()=>{
 const f=fixture();await f.context.load();const release=f.hold('/api/composition'),pending=f.context.load();await release.started;const n=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.financeNotice.textContent,f.i.t('finance.page.loading'));assert.equal(f.calls.length,n);}release();await pending;f.deny();await f.context.load();const after=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.financeNotice.textContent,f.i.t('finance.page.load_error',{reason:f.i.t('common.access_denied')}));assert.equal(f.nodes.financeJournal.textContent,'');assert.equal(f.nodes.financePeriodClosing.textContent,'');assert.equal(f.nodes.financeEntity.textContent,'');assert.equal(f.calls.length,after);assert.equal(f.i.missingKeys().length,0);}
});
test('Finance ZERO progress and export feedback localize while model answers, exact requests and CSV bytes stay literal',async()=>{
 const f=fixture();await f.context.load();f.nodes.financeZeroInput.value='Literal question';let release=f.hold('/api/zero/turn'),pending=f.context.askZero({preventDefault(){}});await release.started;const n=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.financeZeroOutput.textContent,f.i.t('finance.page.zero_loading'));assert.equal(f.calls.length,n);}release();await pending;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.financeZeroOutput.textContent,'Literal ZERO answer');}
 await f.context.exportJournal();const after=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.financeNotice.textContent,f.i.t('finance.page.exported',{value:f.i.number(1)}));assert.equal(f.downloads[0].parts[0],'Literal CSV bytes');assert.equal(f.calls.length,after);assert.equal(f.i.missingKeys().length,0);}assert.equal(JSON.parse(f.calls.find(c=>c.route==='/api/zero/turn').options.body).message,'Literal question');
});
