'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('../zero-evaluation/fixture'),{input}=require('../zero-evaluation/finance-mutation-fixture'),{create}=require('../zero-evaluation/finance-action-page-http-fixture'),{act}=require('../zero-evaluation/finance-action-client-fixture');
for(const industry of ['AUTOMOTIVE','ECOMMERCE'])test(industry+' approve-only Finance page and ZERO preserve explicit supplier approval across lost reply, restart, later posting and capability revocation',async()=>{
 const s=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/finance-http-faults')});
 try{
  assert.equal((await s.request('/api/composition','PUT',{industry_id:industry,entitlements:['finance'],expected_revision:0})).status,200);
  const admin=await s.enroll('purchase.admin.'+industry.toLowerCase(),['FINANCE_ADMIN']),approver=await s.enroll('purchase.approver.'+industry.toLowerCase(),['APPROVER']),accountant=await s.enroll('purchase.accountant.'+industry.toLowerCase(),['ACCOUNTANT']),viewer=await s.enroll('purchase.viewer.'+industry.toLowerCase(),['VIEWER']);
  const call=(member,route,method='GET',body,headers={})=>s.request(route,method,body,member.cookie,headers),native=(...args)=>call(admin,...args);
  const entity=(await native('/api/finance/legal-entities','POST',{name:'[SYNTHETIC DEMO] Purchase UI',legal_form:'BV'})).body;
  assert.equal((await native('/api/finance/periods','POST',{legal_entity_id:entity.id,start_date:'2026-01-01',end_date:'2026-12-31'})).status,201);assert.equal((await native('/api/finance/legal-entities/'+entity.id+'/bootstrap-chart','POST',{})).status,201);
  const ids=[];for(let i=0;i<3;i++){const r=await call(accountant,'/api/finance/invoices','POST',{...input({entity},'APPROVE-'+i),kind:'PURCHASE',supplier_name:'PRIVATE_APPROVAL_SUPPLIER'});assert.equal(r.status,201,JSON.stringify(r.body));ids.push(r.body.invoice.id);}
  let page=await create(s,approver);assert.deepEqual(page.field('operation').children.map(n=>n.value),['INVOICE_APPROVE']);assert.ok(page.field('document').textContent.includes('approval required'));
  await act(page,'INVOICE_APPROVE',ids[0]);assert.ok(page.calls.some(c=>c.route==='/api/finance/invoice-actions/execute'));assert.ok(page.box.textContent.includes('approved'));assert.equal((await native('/api/finance/records/journal_entries')).body.total,0);
  await page.transport('zero');page.loseNext('/api/zero/turn');await act(page,'INVOICE_APPROVE',ids[1]);assert.equal(page.box.canLeave(),false);assert.ok(page.calls.some(c=>c.body?.client_context?.finance_action?.operation==='INVOICE_APPROVE_EXECUTE'));
  const retained=await call(approver,'/api/finance/invoice-actions/confirmations?operation=INVOICE_APPROVE');assert.equal(retained.body.total,1,JSON.stringify(retained.body));const command=retained.body.items[0].command;
  assert.equal((await call(accountant,'/api/finance/invoice-actions/recover','POST',command)).status,403);assert.equal((await call(viewer,'/api/finance/invoice-actions/recover','POST',command)).status,403);
  assert.equal((await call(approver,'/api/finance/invoice-actions/execute','POST',{...command,operation:'INVOICE_POST'})).status,403);
  const turn=(phase,{operation:ignored,...value})=>({message:value.reason||'Inspect the explicit purchase invoice',conversation_id:crypto.randomUUID(),turn_id:crypto.randomUUID(),client_context:{finance_action:{operation:'INVOICE_APPROVE_'+phase,input:value}}});
  assert.equal((await call(accountant,'/api/zero/turn','POST',turn('EXECUTE',command))).status,403);
  page.box.isConnected=false;await s.stop();await s.start();for(const member of [admin,approver,accountant,viewer])member.cookie=await s.login(member);
  assert.equal((await call(accountant,'/api/finance/invoices/'+ids[1]+'/post','POST',{})).status,200);
  const zeroRecovery=await call(approver,'/api/zero/turn','POST',turn('RECOVER',command));assert.equal(zeroRecovery.status,200,JSON.stringify(zeroRecovery.body));assert.equal(zeroRecovery.body.finance_data.original_result.invoice.status,'DRAFT');assert.equal(zeroRecovery.body.finance_data.current_invoice.status,'POSTED');assert.equal(zeroRecovery.body.verification.financial_posting_performed,false);
  page=await create(s,approver);assert.equal(page.box.canLeave(),false);await page.transport('zero');await page.button('recover').fire('click');assert.equal(page.box.canLeave(),true,page.box.textContent);assert.ok(page.box.textContent.includes('Draft'));assert.ok(page.box.textContent.includes('Posted'));assert.equal(page.calls.filter(c=>c.body?.client_context?.finance_action?.operation==='INVOICE_APPROVE_EXECUTE').length,0);
  assert.equal((await native('/api/finance/records/journal_entries')).body.total,1);assert.equal((await native('/api/finance/records/payments')).body.total,0);assert.equal((await call(approver,'/api/finance/invoice-actions/confirmations?operation=INVOICE_APPROVE')).body.total,0);
  const p=await call(approver,'/api/finance/invoice-actions/preview','POST',{operation:'INVOICE_APPROVE',input:{invoice_id:ids[2]}});assert.equal(p.body.ready,true);const delayed={operation:'INVOICE_APPROVE',input:{invoice_id:ids[2]},request_id:crypto.randomUUID(),expected_source_hash:p.body.source_hash,confirm:true,reason:'Explicit current approval'},body=JSON.stringify(delayed),marker=path.join(s.dir,'finance-body-boundary');let req;
  try{
   const response=new Promise((resolve,reject)=>{req=http.request(s.base+'/api/finance/invoice-actions/execute',{method:'POST',headers:{cookie:approver.cookie,origin:'https://foundly.example.test','content-type':'application/json','content-length':Buffer.byteLength(body),'x-fixture-finance-barrier':'body'}},res=>{let data='';res.on('data',chunk=>data+=chunk);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(data)}));});req.on('error',reject);req.write(body.slice(0,5));});
   for(let i=0;i<100&&!fs.existsSync(marker);i++)await new Promise(resolve=>setTimeout(resolve,10));assert.ok(fs.existsSync(marker));
   assert.equal((await s.request('/api/composition','PUT',{industry_id:industry,entitlements:['finance'],capability_flags:{'finance:invoices':false},expected_revision:1})).status,200);req.end(body.slice(5));assert.equal((await response).status,403);
  }finally{req?.destroy();}
  assert.equal((await call(approver,'/api/finance/invoice-actions/recover','POST',command)).status,403);assert.ok(!(await call(approver,'/api/zero/status')).body.tools.some(t=>t.tool_id==='finance_invoice_approve_execute'));
  assert.equal((await s.request('/api/composition','PUT',{industry_id:industry,entitlements:['finance'],expected_revision:2})).status,200);const invoices=(await native('/api/finance/records/invoices?limit=100')).body.items;assert.equal(invoices.find(i=>i.id===ids[2]).approval_status,'PENDING');assert.equal(invoices.find(i=>i.id===ids[1]).approved_by,approver.member.id);assert.ok(!fs.readFileSync(path.join(s.dir,'foundly-core-state.json'),'utf8').includes('PRIVATE_APPROVAL_SUPPLIER'));
 }finally{await s.close();}
});
