'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {fixture,modules}=require('../zero-evaluation/module-overlay-fixture'),{ViewElement}=require('../zero-evaluation/zero-presentation-fixture'),{locales}=require('../foundly-i18n');
const source=fs.readFileSync(require.resolve('../index-script.js'),'utf8');
function setup(){const f=fixture(),opened=[];for(const id of ['visualQuality','renderMetrics','viewMotion','mainCount','subCount','linkCount','legend'])f.nodes[id]=new ViewElement();f.context.openModule=id=>opened.push(id);vm.runInContext('const ids=Object.keys(MODULES);\n'+source.slice(source.indexOf('function renderGraphicsQuality('),source.indexOf('\nfunction pulseRoute(')),f.context);return {...f,opened};}
test('fallback graphics labels and module legend change locale without rebuilding controls or mutating native rendering observations',()=>{
  const f=setup(),quality={name:'BALANCED',auto:true},metrics={fps:60,particles:2200,filaments:300,manual_active:false},original=JSON.stringify({quality,metrics});f.context.renderGraphicsQuality(quality);f.context.renderGraphicsMetrics(metrics);const legend=f.nodes.legend.children.slice(),number=f.nodes.renderMetrics.firstChild;
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.visualQuality.textContent,f.i.t('graphics.balanced')+f.i.t('graphics.auto_suffix'));assert.equal(f.nodes.renderMetrics.textContent,f.i.t('graphics.metrics',{fps:f.i.number(60),particles:f.i.number(2200),ribbons:f.i.number(300)}));assert.equal(f.nodes.renderMetrics.firstChild,number);assert.equal(f.nodes.viewMotion.textContent,f.i.t('graphics.motion'));assert.deepEqual(f.nodes.legend.children,legend);assert.equal(f.nodes.mainCount.textContent,f.i.number(Object.keys(modules).length));assert.equal(f.nodes.subCount.textContent,f.i.number(Object.values(modules).reduce((n,m)=>n+m.sub.length,0)));assert.equal(f.nodes.linkCount.textContent,f.i.number(420));assert.equal(JSON.stringify({quality,metrics}),original);assert.equal(f.requests.length,0);assert.equal(f.opened.length,0);
    for(const [index,id]of Object.keys(modules).entries()){const button=legend[index];assert.equal(button.textContent,String(f.context.moduleLabel(id)));assert.equal(button.getAttribute('data-open'),id);assert.equal(button.getAttribute('style'),'--module:'+modules[id].kleur);assert.equal(button.children[0].tag,'i');assert.equal(button.childNodes[1].nodeType,3);}
    assert.equal(f.i.missingKeys().length,0);
  }
  legend[0].onclick();assert.deepEqual(f.opened,['inkoop']);f.context.renderGraphicsMetrics({manual_active:true,fps:0,particles:0,filaments:0});assert.equal(f.nodes.viewMotion.textContent,f.i.t('graphics.manual'));assert.equal(f.nodes.renderMetrics.textContent,f.i.t('graphics.metrics',{fps:'0',particles:'0',ribbons:'0'}));
});
test('unavailable or invalid graphics observations remain unknown, and the approved spatial renderer bypasses fallback legend construction',()=>{
  const f=setup();f.context.renderGraphicsQuality({available:false});f.context.renderGraphicsMetrics({fps:'60',particles:-1,filaments:null});
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.visualQuality.textContent,f.i.t('graphics.unavailable'));assert.equal(f.nodes.renderMetrics.textContent,f.i.t('graphics.metrics',{fps:f.i.t('common.unknown'),particles:f.i.t('common.unknown'),ribbons:f.i.t('common.unknown')}));assert.equal(f.nodes.viewMotion.textContent,f.i.t('common.unknown'));}
  const legend=f.nodes.legend.children;f.context.FoundlyCustomerSpatialRuntime=class{};f.context.buildModuleControls();assert.equal(f.nodes.legend.children,legend);assert.equal(f.requests.length,0);assert.equal(f.opened.length,0);
});
