'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/marketing-audience-client-fixture'),{fixture:nativeFixture}=require('../zero-evaluation/marketing-audience-fixture'),{locales}=require('../foundly-i18n'),service=require('../marketing-audiences');
test('audience owned controls localize in all eight locales while preserving literal member input and unknown consent',async()=>{const f=fixture();await f.ready();assert.equal(f.field('permission').value,'UNKNOWN');await f.fill();const reason=f.field('reason'),calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.control('save').textContent,f.i.t('marketing.audience.save'));assert.equal(f.field('reason'),reason);assert.equal(reason.value,'Literal private UI reason');assert.equal(f.field('email').value,'literal@EXAMPLE.test');assert.equal(f.field('permission').value,'UNKNOWN');assert.equal(f.field('confirm').checked,true);assert.equal(f.calls.length,calls);assert.ok(!f.box.textContent.includes('marketing.audience.'));}assert.equal(f.box.canLeave(),false);});
test('uncertain audience writes reconcile only exact metadata and never resend a changed consent body',async()=>{const f=fixture();await f.ready();f.lose();await f.save();f.field('permission').value='GRANTED';await f.submit();assert.equal(f.writes().length,1);assert.equal(f.calls.filter(c=>c.recovery).length,1);assert.equal(service.latest(f.native.core,f.native.ctx,f.native.audience.id)[0].member.permission_status,'UNKNOWN');assert.equal(f.storage.size,0);assert.equal(f.notice().textContent,f.i.t('marketing.audience.recovered'));});
test('fresh audience clients recover after restart using no literal participant, email, reason or consent evidence in browser storage',async()=>{const f=fixture();await f.ready();f.lose();await f.save();assert.equal(f.storage.size,1);const saved=JSON.stringify([...f.storage]);for(const literal of ['private-person-reference','literal@','Literal private','permission_evidence'])assert.ok(!saved.includes(literal));f.native.restart();const fresh=fixture({native:f.native,storage:f.storage});await fresh.ready();fresh.field('email').value='new-unsent@example.test';await fresh.submit();assert.equal(fresh.writes().length,0);assert.equal(fresh.storage.size,0);assert.equal(fresh.field('email').value,'new-unsent@example.test');});
test('a member request that never dispatched is durably closed before another body can execute',async()=>{const f=fixture();await f.ready();f.loseBefore();await f.save();const original=f.writes()[0];await f.submit();assert.equal(f.notice().textContent,f.i.t('marketing.audience.not_applied'));assert.equal(service.list(f.native.core,f.native.ctx,f.actor,f.native.audience.id).total,0);assert.throws(()=>service.upsert(f.native.core,f.native.ctx,f.actor,f.native.audience.id,original.input,{idempotency_key:original.key}),{code:'audience_request_abandoned'});});
test('audience source and member lists reject missing results instead of displaying an empty successful editor',async()=>{const f=fixture();await f.ready();f.alter((d,r,m)=>{if(m==='GET'&&r.includes('/members'))delete d.items;return d;});await f.control('refresh').fire('click');assert.equal(f.notice().textContent,f.i.t('marketing.audience.invalid'));assert.equal(f.control('save').disabled,true);});
test('current audience denial removes retained member selection and source literals',async()=>{const n=nativeFixture();n.apply(n.member({permission_status:'GRANTED'}));const f=fixture({native:n});await f.ready();await f.control('selection').fire('click');assert.ok(f.box.textContent.includes('literal@example.test'));f.deny();await f.control('refresh').fire('click');assert.ok(!f.box.textContent.includes('literal@example.test'));assert.ok(!f.box.textContent.includes('PRIVATE current audience denial'));assert.equal(f.notice().textContent,f.i.t('common.access_denied'));});
test('audience pagination loads all thirty-one current members without duplicating a concurrent next page',async()=>{const n=nativeFixture();for(let k=0;k<31;k++)n.apply(n.member({subject_id:'member-'+String(k).padStart(2,'0'),email:'person'+k+'@example.test'}));const f=fixture({native:n});await f.ready();await Promise.all([f.control('next').fire('click'),f.control('next').fire('click')]);assert.equal(f.calls.filter(c=>c.route.includes('offset=25')).length,1);const rows=f.box.all().filter(n=>n.getAttribute?.('data-audience-member'));assert.equal(rows.length,31);assert.equal(new Set(rows.map(n=>n.getAttribute('data-audience-member'))).size,31);assert.equal(f.control('next').disabled,true);});
test('read-only audience access displays the source without enabling member writes',async()=>{const n=nativeFixture(),f=fixture({native:n,actor:{...n.actor,roles:['VIEWER']}});await f.ready();assert.equal(f.control('save').disabled,true);assert.equal(f.field('email').disabled,true);assert.ok(f.box.textContent.includes('Literal private audience'));});
test('unavailable browser recovery storage prevents an audience write from dispatching',async()=>{const f=fixture();await f.ready();f.failStorage();await f.save();assert.equal(f.writes().length,0);assert.equal(f.notice().textContent,f.i.t('marketing.audience.storage'));});
test('retired audience forms cannot submit after explicit input reset',async()=>{const f=fixture();await f.ready();await f.fill();const old=f.box.all().find(n=>n.tag==='form'),oldSave=f.control('save');await f.control('refresh').fire('click');const before=f.writes().length;if(old)await old.fire('submit');await oldSave.fire('click');assert.equal(f.writes().length,before);});

for(const zero of [false,true])test((zero?'ZERO':'native')+' audience filter controls reconcile the exact revision and preserve pending tab input through every locale',async()=>{const f=fixture({zero});await f.ready();await f.control('filters').fire('click');f.field('tags_all').value='literal-tag';f.field('reason').value='Literal filter rationale';await f.field('reason').fire('input');f.field('confirm').checked=true;f.lose();await f.submit();assert.equal(f.native.currentAudience().revision,2);const input=f.field('tags_all'),calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.field('tags_all'),input);assert.equal(input.value,'literal-tag');assert.equal(f.field('reason').value,'Literal filter rationale');assert.equal(f.calls.length,calls);}await f.submit();assert.equal(f.writes().length,1);assert.equal(f.calls.filter(c=>c.recovery).length,1);assert.equal(f.storage.size,0);assert.equal(f.notice().textContent,f.i.t('marketing.audience.recovered'));});
test('superseded consent recovery presents the newer opt-out while keeping newer unsent input',async()=>{const f=fixture();await f.ready();f.lose();await f.fill();f.field('permission').value='GRANTED';await f.submit();const original=f.writes()[0];f.native.apply(f.native.member({...original.input,expected_member_revision:1,permission_status:'REVOKED',reason:'Later explicit opt-out'}));f.field('reason').value='New unsent reason';await f.submit();assert.equal(f.writes().length,1);assert.equal(f.field('reason').value,'New unsent reason');assert.equal(f.notice().textContent,f.i.t('marketing.audience.superseded'));assert.ok(f.box.textContent.includes(f.i.t('marketing.audience.permission_revoked')));assert.equal(service.latest(f.native.core,f.native.ctx,f.native.audience.id)[0].member.permission_status,'REVOKED');});
test('audience acknowledgements reject a changed native reason despite a self-consistent result hash',async()=>{const f=fixture();await f.ready();f.alter((data,route,method)=>{if(method==='POST'&&route.endsWith('/members')){data.record.reason='Forged different reason';data.request_acknowledgement.result_snapshot_sha256=require('../zero-evaluation/marketing-audience-fixture').hash(data.record);}return data;});await f.save();assert.equal(f.storage.size,1);assert.equal(f.notice().textContent,f.i.t('marketing.audience.uncertain'));assert.equal(f.box.canLeave(),false);});
test('contradictory audience recovery cannot discard the original request metadata',async()=>{const f=fixture();await f.ready();f.lose();await f.save();f.alter((data,route)=>{if(route.includes('/audience-requests/'))data.result_revision+=1;return data;});await f.submit();assert.equal(f.storage.size,1);assert.equal(f.writes().length,1);assert.equal(f.box.canLeave(),false);});
test('current denial during audience reconciliation clears private fields but retains attribution',async()=>{const f=fixture();await f.ready();f.lose();await f.save();f.deny();await f.submit();assert.equal(f.storage.size,1);assert.equal(f.field('email').value,'');assert.equal(f.field('reason').value,'');assert.ok(!f.box.textContent.includes('Literal private audience'));assert.equal(f.writes().length,1);assert.equal(f.notice().textContent,f.i.t('common.access_denied'));});
test('confirmed audience metadata cleanup failure cannot dispatch a second mutation',async()=>{const f=fixture();await f.ready();f.failCleanup();await f.save();assert.equal(f.storage.size,1);assert.equal(f.notice().textContent,f.i.t('marketing.audience.confirmed_metadata'));await f.submit();assert.equal(f.writes().length,1);assert.equal(service.list(f.native.core,f.native.ctx,f.actor,f.native.audience.id).total,1);});
test('late audience write responses from a retired view retain metadata for a fresh explicit recovery',async()=>{const f=fixture();await f.ready();const release=f.hold('/members','POST'),saving=f.save();await release.started;f.retire();const text=f.notice().textContent;release();await saving;assert.equal(f.notice().textContent,text);assert.equal(f.storage.size,1);const fresh=fixture({native:f.native,storage:f.storage,global:true});await fresh.ready();await fresh.control('recover').fire('click');assert.equal(fresh.storage.size,0);assert.equal(fresh.writes().length,0);});
test('read-only audience selection reports unknown permission as exclusion without recording a grant',async()=>{const n=nativeFixture();n.apply(n.member());const f=fixture({native:n,actor:{...n.actor,roles:['VIEWER']}});await f.ready();await f.control('selection').fire('click');assert.equal(f.writes().length,0);assert.ok(f.box.textContent.includes(f.i.t('marketing.audience.excluded_no_recorded_permission')));assert.equal(f.control('save').disabled,true);});
test('audience selection cannot claim filters that differ from the displayed native audience revision',async()=>{const f=fixture();await f.ready();f.alter((data,route)=>{if(route.endsWith('/selection'))data.filters.tags_all=['forged-filter'];return data;});await f.control('selection').fire('click');assert.equal(f.notice().textContent,f.i.t('marketing.audience.invalid'));});
test('audience pagination rejects a repeated participant even when the later page has a different valid history record',async()=>{const n=nativeFixture();for(let k=0;k<26;k++)n.apply(n.member({subject_id:'person-'+String(k).padStart(2,'0'),email:'person'+k+'@example.test'}));const f=fixture({native:n});await f.ready();n.apply(n.member({subject_id:'person-00',expected_member_revision:1,permission_status:'REVOKED'}));const repeated=service.latest(n.core,n.ctx,n.audience.id).find(r=>r.subject_id==='person-00');f.alter((data,route)=>{if(route.includes('offset=25'))data.items=[repeated];return data;});await f.control('next').fire('click');assert.equal(f.notice().textContent,f.i.t('marketing.audience.invalid'));assert.equal(f.box.all().filter(n=>n.getAttribute?.('data-audience-member')).length,25);});

for(const zero of [false,true])test((zero?'ZERO':'native')+' exact audience member and filter acknowledgements complete without a recovery write',async()=>{const f=fixture({zero});await f.ready();await f.save();assert.equal(f.notice().textContent,f.i.t('marketing.audience.saved'));assert.equal(f.storage.size,0);await f.control('refresh').fire('click');await f.control('filters').fire('click');f.field('tags_none').value='excluded-tag';f.field('reason').value='Literal filter reason';await f.field('reason').fire('input');f.field('confirm').checked=true;await f.submit();assert.equal(f.notice().textContent,f.i.t('marketing.audience.saved'));assert.equal(f.storage.size,0);assert.equal(f.writes().length,2);assert.equal(f.calls.filter(c=>c.recovery).length,0);assert.deepEqual(f.native.currentAudience().filters,{tags_all:[],tags_none:['excluded-tag']});});
