'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture:serverFixture}=require('../zero-evaluation/fixture'),{fixture:page}=require('../zero-evaluation/marketing-metrics-client-fixture'),{locales}=require('../foundly-i18n');
test('actual native and ZERO Marketing controls paginate current member sources and retire evidence after HTTP capability denial',async()=>{const server=await serverFixture();try{
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['marketing'],expected_revision:0})).status,200);const owner=await server.enroll('metric.presentation.owner',['MARKETING']),other=await server.enroll('metric.presentation.other',['MARKETING']);
 for(let index=0;index<32;index++)assert.equal((await server.request('/api/platform/events/ingest','POST',{event_id:'http_metric_'+index,event_name:'marketing_spend',source:index===31?'PRIVATE_DENIED_SOURCE':'Literal HTTP source',campaign_id:'literal_http_campaign',occurred_at:'2026-08-15T00:00:00Z',permissions:{user_ids:[index===31?other.member.id:owner.member.id]},properties:{currency:'USD',metric_semantics:'DELTA',spend_cents:index===31?999999:123,impressions:0,clicks:0,private_unused:'PRIVATE_EXCLUDED_FIELD'},consent_context:{purpose:'isolated_metric_fixture',legal_basis:'contract'}})).status,202);
 const transport=async(route,options)=>{const response=await server.request(route,options.method||'GET',options.body?JSON.parse(options.body):undefined,owner.cookie);if(response.status>=400)throw Object.assign(Error('RAW_PRIVATE_SERVER_ERROR'),{code:response.body.code,status:response.status});return response.body;},views=[];
 for(const zero of [false,true]){const f=page({zero,transport});views.push(f);f.field('campaign_ids').value='literal_http_campaign';await f.calculate();assert.ok(f.control('sources'),f.notice().textContent);assert.ok(f.box.textContent.includes(f.i.currencyCents(31*123,'USD')),JSON.stringify({zero,text:f.box.textContent,calls:f.calls.map(c=>c.body)}));await f.drill();assert.equal(f.box.all().filter(n=>n.tag==='pre').length,25);const next=f.control('next');assert.ok(next);await next.fire('click');assert.equal(f.box.all().filter(n=>n.tag==='pre').length,6);assert.equal(f.control('next'),undefined);assert.ok(!f.box.textContent.includes('PRIVATE_'));const count=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.control('query').textContent,f.i.t('marketing.metrics.calculate'));assert.equal(f.field('campaign_ids').value,'literal_http_campaign');assert.ok(f.box.textContent.includes(f.i.t('marketing.metrics.page',{from:f.i.number(26),to:f.i.number(31),total:f.i.number(31)})));}assert.equal(f.calls.length,count);assert.equal(f.calls.length,3);}
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['marketing'],capability_flags:{'marketing:attribution':false},expected_revision:1})).status,200);
 for(const f of views){const old=f.control('sources');await old.fire('click');assert.equal(f.control('sources'),undefined);assert.equal(f.box.all().filter(n=>n.tag==='pre').length,0);assert.equal(f.notice().textContent,f.i.t('common.access_denied'));const count=f.calls.length;await old.fire('click');assert.equal(f.calls.length,count);assert.ok(!f.box.textContent.includes('Literal HTTP source'));}
 }finally{await server.close();}});
