'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture,hash,clone}=require('../zero-evaluation/marketing-journey-fixture');
test('journey definitions bind the exact confirmed reason and retain typed outcome proof through restart',()=>{const f=fixture(),r=f.define(),saved=f.apply(r);assert.deepEqual(saved.request_acknowledgement.request,r.meta);f.restart();const proof=f.recover(r);assert.deepEqual(proof.result_snapshot,saved.record);assert.equal(proof.result_snapshot_sha256,hash(saved.record));assert.equal(proof.result_is_current,true);assert.throws(()=>f.apply({...r,input:{...r.input,reason:'Changed reason'}}),{code:'journey_key_conflict'});});
test('a definition ID cannot acknowledge a different reason under a fresh request identity',()=>{const f=fixture(),r=f.definitionRequest,changed=f.reference('DEFINE',{...r.input,reason:'Changed reason'},r.sourceId);assert.throws(()=>f.apply(changed),{code:'journey_version_immutable'});});
test('recovering automatic enrollment returns exact current run identities without executing a step',()=>{const f=fixture(),r=f.activation({execution_mode:'AUTOMATIC_INTERNAL'}),saved=f.apply(r);f.restart();const proof=f.recover(r);assert.deepEqual(proof.result_snapshot,saved.record);assert.deepEqual(proof.runs.map(x=>x.id),saved.record.run_ids);assert.equal(proof.runs[0].revision,1);assert.equal(f.core.bucket(f.ctx,'tasks').length,0);assert.equal(proof.external_send,false);});
test('advance recovery distinguishes the originally created task from later completed native work and never creates a second task',()=>{const f=fixture(),id=f.enroll(),r=f.advance(id),saved=f.apply(r);const complete=f.complete(id);f.apply(complete);f.apply(f.advance(id));f.restart();const proof=f.recover(r);assert.deepEqual(proof.result_snapshot,saved.record);assert.equal(proof.record.status,'COMPLETED_INTERNAL');assert.equal(proof.result_is_current,false);assert.equal(proof.effects[0].result_snapshot.status,'OPEN');assert.equal(proof.effects[0].record.status,'COMPLETED');assert.equal(f.core.bucket(f.ctx,'tasks').length,1);assert.throws(()=>f.apply(r),{code:'journey_result_changed'});});
test('an old task completion replay cannot acknowledge a subsequently reopened task as its original completion',()=>{const f=fixture(),id=f.enroll();f.apply(f.advance(id));const r=f.complete(id);f.apply(r);const task=f.core.bucket(f.ctx,'tasks')[0];f.core.save(f.ctx,f.actor,'tasks',{status:'OPEN'},{id:task.id,expected_revision:task.revision});assert.throws(()=>f.apply(r),{code:'journey_result_changed'});const proof=f.recover(r);assert.equal(proof.result_is_current,false);assert.equal(proof.effects[0].result_snapshot.status,'COMPLETED');assert.equal(proof.effects[0].record.status,'OPEN');assert.equal(f.core.get(f.ctx,f.actor,'tasks',task.id).status,'OPEN');});
test('pause, resume and cancellation recover original revisions without restoring superseded journey state',()=>{const f=fixture(),id=f.enroll(),requests=[];for(const action of ['PAUSE','RESUME','CANCEL']){const r=f.control(id,action);f.apply(r);requests.push(r);}f.restart();for(const [index,r]of requests.entries()){const proof=f.recover(r);assert.equal(proof.result_snapshot.status,['PAUSED','ACTIVE','CANCELLED'][index]);assert.equal(proof.record.status,'CANCELLED');assert.equal(proof.result_is_current,index===2);}});
test('absent definition, enrollment, advance, task completion and control requests close durably before delayed original bodies arrive',()=>{for(const operation of ['DEFINE','ACTIVATE','ADVANCE','COMPLETE_TASK','PAUSE','RESUME','CANCEL']){const f=fixture();let r;if(operation==='DEFINE')r=f.define();else if(operation==='ACTIVATE')r=f.activation();else {const id=f.enroll();if(operation==='COMPLETE_TASK')f.apply(f.advance(id));if(operation==='RESUME')f.apply(f.control(id,'PAUSE'));r=operation==='ADVANCE'?f.advance(id):operation==='COMPLETE_TASK'?f.complete(id):f.control(id,operation);}const before=hash(f.core.bucket(f.ctx,'journey_runs'));assert.equal(f.recover(r).state,'NOT_APPLIED');f.restart();assert.throws(()=>f.apply(r),{code:'journey_request_abandoned'});assert.equal(hash(f.core.bucket(f.ctx,'journey_runs')),before);}});
test('journey recovery binds exact metadata and actor and rechecks current source ownership and capabilities',()=>{const f=fixture(),r=f.activation();f.apply(r);assert.throws(()=>f.recover(r,{...r.meta,request_fingerprint:'0'.repeat(64)}),{code:'journey_key_conflict'});assert.throws(()=>f.recover(r,r.meta,{id:'other',roles:['MARKETING']}),{code:'record_not_found'});f.core.bucket(f.ctx,'campaigns')[0].owner_id=f.admin.id;assert.throws(()=>f.recover(r,r.meta,f.admin),{code:'journey_recovery_unverifiable'});assert.throws(()=>f.recover(r),{code:'record_not_found'});});
test('journey proof and native mutations roll back together on persistence failure, including durable absence closure',()=>{const f=fixture(),r=f.activation();const before=f.snapshot();f.fail(true);assert.throws(()=>f.apply(r),{code:'EIO'});assert.equal(f.snapshot(),before);assert.throws(()=>f.recover(r),{code:'EIO'});assert.equal(f.snapshot(),before);f.fail(false);assert.equal(f.recover(r).state,'NOT_APPLIED');});
test('legacy and tampered journey receipts cannot acquire invented typed result or side-effect proof',()=>{const f=fixture(),id=f.enroll(),r=f.advance(id);f.apply(r);const entry=f.receipts().find(e=>e.key===r.key),saved=clone(entry);delete entry.request_kind;assert.throws(()=>f.recover(r),{code:'journey_recovery_unverifiable'});Object.assign(entry,saved);entry.result_snapshot.history[0].actor_id='forged';assert.throws(()=>f.recover(r),{code:'journey_recovery_unverifiable'});});
test('draft preparation recovery verifies exact native output and current communication authority without sending',()=>{const f=fixture({mail:true}),id=f.enroll(),r=f.advance(id);f.apply(r);const proof=f.recover(r);assert.equal(proof.effects[0].entity,'drafts');assert.equal(proof.effects[0].record.delivery_state,'NOT_SENT');assert.equal(f.communication.bucket(f.ctx,'messages').length,0);f.actor.permissions=[];assert.throws(()=>f.recover(r),{code:'composition_forbidden',statusCode:403});});

test('journey recovery rechecks module revocation even for confirmed outcomes',()=>{const f=fixture(),r=f.activation();f.apply(r);f.resolver.configure(f.ctx,f.admin,{entitlements:['marketing','communication'],enabled_modules:['communication'],expected_revision:2});assert.throws(()=>f.recover(r),{code:'module_disabled',statusCode:403});assert.throws(()=>f.apply(r),{code:'module_disabled',statusCode:403});});
test('bounded journey receipts reject new writes and closures without discarding existing outcome proof',()=>{const f=fixture(),existing=f.definitionRequest,r=f.activation(),rows=f.receipts();while(rows.length<100000)rows.push({key:'existing-'+rows.length,actor_id:'other'});assert.throws(()=>f.apply(r),{code:'journey_capacity',statusCode:507});assert.throws(()=>f.recover(r),{code:'journey_capacity',statusCode:507});assert.equal(f.recover(existing).state,'APPLIED');assert.equal(rows.length,100000);});
test('journey recovery rejects damaged native task evidence and original source ownership changes',()=>{const f=fixture(),id=f.enroll(),r=f.advance(id);f.apply(r);const receipt=f.receipts().find(e=>e.key===r.key);receipt.effects[0].result_snapshot.title='Corrupted original task';assert.throws(()=>f.recover(r),{code:'journey_recovery_unverifiable'});const activation=f.receipts().find(e=>e.operation==='ACTIVATE'),meta={request_id:activation.key,request_fingerprint:activation.fingerprint,operation:activation.operation,source_id:activation.source_id,expected_revision:null,expected_task_revision:null};f.core.bucket(f.ctx,'campaigns')[0].owner_id='new-owner';assert.throws(()=>f.recover({meta},meta,{...f.actor,roles:['SUPER_ADMIN']}),{code:'journey_recovery_owner_changed',statusCode:403});});
