'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{fixture:serverFixture}=require('../zero-evaluation/fixture'),{fixture:client}=require('../zero-evaluation/marketing-review-client-fixture');
for(const zero of [false,true])test('actual '+(zero?'ZERO':'native')+' review controls reconcile preparation and approval in fresh VMs after encrypted restart',async()=>{const server=await serverFixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/review-ack-drop')});try{
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['marketing'],expected_revision:0})).status,200);const owner=await server.enroll('review.client.owner',['MARKETING']),reviewer=await server.enroll('review.client.approver',['MANAGER']);const grant=await server.request('/api/identity/users/'+reviewer.member.id,'PUT',{roles:['MANAGER'],permissions:['marketing:approve'],expected_revision:reviewer.member.revision,confirm:true,reason:'Explicit isolated reviewer authority'});assert.equal(grant.status,200);reviewer.member=grant.body.member;reviewer.cookie=await server.login(reviewer);
 const created=await server.request('/api/marketing/creatives','POST',{title:'Actual UI review source',content:'Literal private HTTP content'},owner.cookie);assert.equal(created.status,201);const source=created.body.record;
 const transport=(account)=>{let drop=true;return async(route,options={})=>{const body=options.body?JSON.parse(options.body):undefined,write=options.method==='POST'&&(route.endsWith('/reviews')||route.includes('/creative_reviews/')&&route.endsWith('/approve')||route==='/api/zero/turn'&&['REVIEW_PREPARE','REVIEW_DECIDE'].includes(body.client_context.marketing_action.operation)),headers=write&&drop?{'x-zero-review-drop-reply':'isolated-review-fixture'}:{};if(write)drop=false;const response=await server.request(route,options.method||'GET',body,account.cookie,{...options.headers,...headers});if(response.status>=400)throw Object.assign(Error('PRIVATE HTTP review failure'),{code:response.body.code,status:response.status});return response.body;};};
 const realm=account=>({tenant_id:source.tenant_id,dealer_id:source.dealer_id,actor_id:account.member.id});let record=source;
 for(const [kind,account,action]of [['PREPARE',owner,'prepare'],['REVIEW',reviewer,'decide']]){const call=transport(account),first=client({zero,kind,record,actor:{id:account.member.id},realm:realm(account),transport:call});await first.ready();await first.fill();if(kind==='PREPARE')first.field('reviewers').value=reviewer.member.id;await first.control(action).fire('click');assert.equal(first.storage.size,1);assert.equal(first.notice().textContent,first.i.t('marketing.review.uncertain'));first.retire();await server.stop();await server.start();account.cookie=await server.login(account);const fresh=client({zero,kind,record,actor:{id:account.member.id},realm:realm(account),transport:call,storage:first.storage});await fresh.ready();fresh.field('reason').value='Newer unsent HTTP reason';await fresh.control(action).fire('click');assert.equal(fresh.storage.size,0);assert.equal(fresh.field('reason').value,'Newer unsent HTTP reason');assert.equal(fresh.writes().length,0);assert.equal(fresh.notice().textContent,fresh.i.t('marketing.review.recovered'));const list=await server.request('/api/marketing/creative_reviews');assert.equal(list.body.total,1);record=list.body.items[0];}
 assert.equal(record.status,'APPROVED_INTERNAL');assert.equal(record.reviews.length,1);const current=await server.request('/api/marketing/creatives/'+source.id);assert.equal(current.body.record.revision,2);assert.equal(current.body.record.delivery_state,'NOT_PUBLISHED');const asset=await server.request('/marketing-review-client.js');assert.equal(asset.status,200);assert.equal(asset.body,fs.readFileSync(require.resolve('../marketing-review-client.js'),'utf8'));
 }finally{await server.close();}});
