'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{page}=require('../zero-evaluation/procurement-intelligence-page-fixture');
const query=f=>({allocation_mode:'FULL',scenarios:[{id:'literal_scenario',label:'Literal PRIVATE reviewed costs',allocations:[{bid_id:f.bid.id,item_id:'literal_item',quantity:2}],costs:{shipping_cents:0,tax_cents:0,fees_cents:0,handling_cents:0}}]});
const report=(f,revision=0,cost=2500)=>({award_id:f.award.id,supplier_id:f.supplier.id,expected_award_revision:f.award.revision,expected_observation_revision:revision,lines:[{item_id:'literal_item',delivered_quantity:2,rejected_quantity:0}],delivery_due_at:'2026-09-18T00:00:00Z',delivered_at:'2026-09-18T00:00:00Z',observed_at:'2026-09-19T00:00:00Z',actual_cost_cents:cost,...(f.savedScenario?{economics_snapshot_id:f.savedScenario.id,scenario_id:'literal_scenario'}:{}),evidence_reference:'Literal PRIVATE outcome source',reason:'Literal explicit observation',confirm:true});
function remove(f,entity,index=0){f.core.bucket(f.ctx,entity)[index].deleted_at='2026-09-26T08:00:00.000Z';}
test('live saved economic scenarios and replays require non-deleted snapshots and current RFQ and bid sources',async()=>{for(const entity of ['economics_snapshots','rfqs','bids']){const f=await page({withSavedScenario:true}),input={query:query(f),expected_source_hash:f.savedScenario.source_hash,reason:'Literal reviewed costs',confirm:true};assert.equal(f.economics.snapshot(f.core,f.ctx,f.buyer,f.rfq.id,input,{idempotency_key:'fixture-scenario'}).deduplicated,true);remove(f,entity);assert.throws(()=>f.core.get(f.ctx,f.actor,'economics_snapshots',f.savedScenario.id),{code:'record_not_found'},entity);assert.equal(f.core.list(f.ctx,f.actor,'economics_snapshots').total,0);assert.throws(()=>f.economics.snapshot(f.core,f.ctx,f.buyer,f.rfq.id,input,{idempotency_key:'fixture-scenario'}),{code:'record_not_found'},entity+' replay');}});
test('new economic comparisons reject deleted RFQ, bid and supplier sources',async()=>{for(const entity of ['rfqs','bids','suppliers']){const f=await page();assert.equal(f.economics.compare(f.core,f.ctx,f.actor,f.rfq.id,query(f)).scenarios.length,1);remove(f,entity);assert.throws(()=>f.economics.compare(f.core,f.ctx,f.actor,f.rfq.id,query(f)),{code:'record_not_found'},entity);}});
test('current reported outcomes do not expose deleted observations or their award, supplier and linked economic sources',async()=>{for(const entity of ['outcome_observations','awards','suppliers','economics_snapshots','rfqs','bids']){const f=await page({entity:'suppliers',withSavedScenario:true,observedCost:2500}),id=f.core.bucket(f.ctx,'outcome_observations')[0].id;remove(f,entity);assert.throws(()=>f.core.get(f.ctx,f.actor,'outcome_observations',id),{code:'record_not_found'},entity);if(entity==='suppliers')assert.throws(()=>f.outcomes.supplier(f.core,f.ctx,f.actor,f.supplier.id),{code:'record_not_found'});else{const result=f.outcomes.supplier(f.core,f.ctx,f.actor,f.supplier.id);assert.equal(result.available,false);assert.equal(result.observations.length,0);assert.equal(result.late_report_count,null);}}});
test('deleting the latest reported outcome does not resurrect an earlier observation or permit a blind correction',async()=>{const f=await page({entity:'suppliers',observedCost:2500});f.outcomes.record(f.core,f.ctx,f.buyer,report(f,1,2600),{idempotency_key:'second-report'});remove(f,'outcome_observations',1);const result=f.outcomes.supplier(f.core,f.ctx,f.actor,f.supplier.id);assert.equal(result.observations.length,0);assert.equal(result.available,false);assert.equal(result.late_report_count,null);assert.throws(()=>f.outcomes.record(f.core,f.ctx,f.buyer,report(f,2,2700),{idempotency_key:'blind-third-report'}),{code:'procurement_outcome_access_changed'});assert.equal(f.core.bucket(f.ctx,'outcome_observations').length,2);});
test('new and replayed reported outcomes require a current non-deleted award and supplier',async()=>{for(const entity of ['awards','suppliers']){const f=await page({entity:'suppliers',observedCost:2500});assert.equal(f.outcomes.record(f.core,f.ctx,f.buyer,report(f),{idempotency_key:'fixture-observation'}).deduplicated,true);remove(f,entity);assert.throws(()=>f.outcomes.record(f.core,f.ctx,f.buyer,report(f),{idempotency_key:'fixture-observation'}),{code:'record_not_found'});assert.throws(()=>f.outcomes.record(f.core,f.ctx,f.buyer,report(f,1),{idempotency_key:'new-report'}),{code:'record_not_found'});assert.equal(f.core.bucket(f.ctx,'outcome_observations').length,1);}});
test('live bid comparison and allocation require current non-deleted RFQ, bid and supplier records',async()=>{const sourcing=require('../procurement-sourcing'),allocation=require('../procurement-allocations');for(const entity of ['rfqs','bids','suppliers']){const f=await page();assert.equal(sourcing.compareBids(f.core,f.ctx,f.actor,f.rfq.id).items.length,1);remove(f,entity);if(entity==='rfqs')assert.throws(()=>sourcing.compareBids(f.core,f.ctx,f.actor,f.rfq.id),{code:'record_not_found'});else{const comparison=sourcing.compareBids(f.core,f.ctx,f.actor,f.rfq.id);assert.equal(comparison.items.length,0);assert.equal(comparison.comparable_count,0);}assert.throws(()=>allocation.allocationProposal(f.core,f.ctx,f.actor,f.rfq.id,query(f).scenarios[0].allocations),{code:'record_not_found'});}});
test('current deletion guards preserve the existing authorized historical export without restoring live access',async()=>{const f=await page({entity:'suppliers',withSavedScenario:true,observedCost:2500});for(const entity of ['rfqs','bids','suppliers','awards','economics_snapshots','outcome_observations'])remove(f,entity);const exported=f.core.export(f.ctx,f.actor);assert.equal(exported.collections.economics_snapshots.length,1);assert.equal(exported.collections.outcome_observations.length,1);assert.equal(exported.collections.outcome_observations[0].observation.actual_cost_cents,2500);assert.throws(()=>f.core.get(f.ctx,f.actor,'economics_snapshots',f.savedScenario.id),{code:'record_not_found'});assert.throws(()=>f.core.get(f.ctx,f.actor,'outcome_observations',exported.collections.outcome_observations[0].id),{code:'record_not_found'});});
