'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture'),{page}=require('../zero-evaluation/procurement-clarifications-page-fixture'),{locales}=require('../foundly-locales');
// The actual workspace controller runs over real HTTP in a minimal DOM.
for(const mode of ['native','zero'])test('actual '+mode+' HTTP clarification controls recover destroyed question and contribution replies across encrypted restart and fresh pages',async()=>{const server=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/procurement-action-ack-drop')});try{
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['procurement'],expected_revision:0})).status,200);const owner=await server.enroll('clarification.page.owner',['MANAGER']),supplier=(await server.request('/api/procurement/suppliers','POST',{name:'PRIVATE actual supplier'},owner.cookie)).body.record,rfq=(await server.request('/api/procurement/rfqs','POST',{title:'PRIVATE actual RFQ',currency:'EUR',lines:[{item_id:'literal_item',description:'PRIVATE actual item',quantity:2}]},owner.cookie)).body.record;
 const calls=[];let loseQuestion=true,loseReply=true;const transport=async(route,opts={})=>{const input=opts.body?JSON.parse(opts.body):undefined,operation=route==='/api/zero/turn'?input.client_context.procurement_action.operation:route==='/api/procurement/clarifications'?'CLARIFY':/\/clarifications\/[^/]+\/entries$/.test(route)?'REPLY':route==='/api/procurement/clarification-requests/recover'?'RECOVER':'READ',drop=operation==='CLARIFY'&&loseQuestion||operation==='REPLY'&&loseReply;if(operation==='CLARIFY')loseQuestion=false;if(operation==='REPLY')loseReply=false;calls.push({route,operation,body:opts.body});const r=await server.request(route,opts.method||'GET',input,owner.cookie,{...opts.headers,...(drop?{'x-procurement-drop-reply':'isolated-action-fixture'}:{})});return {ok:r.status<400,status:r.status,json:async()=>r.body};};
 const f=await page({mode,transport,supplier,rfq});await f.render();await f.fill();await f.form().fire('submit');const saved=[...f.saved.entries()].filter(([key])=>key.startsWith('foundly.procurement.clarifications.v1:'));assert.equal(saved.length,1);assert.deepEqual(Object.keys(JSON.parse(saved[0][1])[0]).sort(),['operation','request_fingerprint','request_id','source_id']);assert.ok(!JSON.stringify(saved).includes('PRIVATE'));
 await server.stop();await server.start();owner.cookie=await server.login(owner);const list=await server.request('/api/procurement/rfqs/'+rfq.id+'/clarifications','GET',undefined,owner.cookie);assert.equal(list.body.total,1);const id=list.body.items[0].id;const r=await f.reload();await r.render();assert.equal(calls.filter(c=>c.operation==='RECOVER').length,0);const before=calls.length;for(const locale of locales)r.i.setLocale(locale);assert.equal(calls.length,before);await r.recoveryAction('recover').fire('click');assert.ok(r.recovery().textContent.includes('Literal PRIVATE supplier question'));assert.equal(calls.filter(c=>c.operation==='CLARIFY').length,1);assert.equal([...r.saved.keys()].filter(k=>k.startsWith('foundly.procurement.clarifications.v1:')).length,0);
 await r.box().all().find(n=>n.getAttribute?.('data-procurement-clarification-record')===id).fire('click');await r.box().ready;r.field('contribution_kind').value='USER_REPORTED_SUPPLIER_RESPONSE';await r.field('contribution_kind').fire('change');r.field('contribution').value='PRIVATE reported actual response';await r.field('contribution').fire('input');r.field('evidence').value='PRIVATE actual manual source';r.field('reason').value='PRIVATE actual contribution reason';r.field('confirm').checked=true;await r.form().fire('submit');assert.equal(calls.filter(c=>c.operation==='REPLY').length,1);
 await server.stop();await server.start();owner.cookie=await server.login(owner);const next=await r.reload();await next.render();await next.recoveryAction('recover').fire('click');for(const locale of locales){next.i.setLocale(locale);assert.ok(next.recovery().textContent.includes('PRIVATE reported actual response'));assert.ok(next.recovery().textContent.includes('PRIVATE actual manual source'));assert.ok(next.recovery().textContent.includes(next.i.t('procurement.clarifications.kind.USER_REPORTED_SUPPLIER_RESPONSE')));assert.ok(next.recovery().textContent.includes(next.i.t('procurement.recovery.clarification_internal_only')));}assert.equal(calls.filter(c=>c.operation==='REPLY').length,1);assert.equal(calls.filter(c=>c.operation==='CLARIFY').length,1);assert.equal(calls.filter(c=>c.operation==='RECOVER').length,2);assert.equal([...next.saved.keys()].filter(k=>k.startsWith('foundly.procurement.clarifications.v1:')).length,0);const result=await server.request('/api/procurement/clarifications/'+id,'GET',undefined,owner.cookie);assert.equal(result.body.record.revision,2);assert.equal(result.body.record.entries.length,2);assert.equal(result.body.record.entries[1].provider_verified,false);assert.equal(result.body.supplier_identity_verified,false);assert.equal((await server.request('/api/procurement/orders','GET',undefined,owner.cookie)).body.total,0);assert.ok(!fs.readFileSync(path.join(server.dir,'foundly-core-state.json'),'utf8').includes('PRIVATE'));
 const html=await server.request('/procurement','GET',undefined,owner.cookie);let previous=html.body.indexOf('src="/procurement-action-client-state.js"');for(const name of ['procurement-clarification-client-state.js','procurement-clarification-recovery-client.js','procurement-clarifications-client.js','foundly-workspace.js']){const at=html.body.indexOf('src="/'+name+'"');assert.ok(at>previous);previous=at;const asset=await server.request('/'+name,'GET',undefined,owner.cookie);assert.equal(asset.status,200);assert.equal(asset.body,fs.readFileSync(require.resolve('../'+name),'utf8'));}
 }finally{await server.close();}});
