'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture');
for(const operation of ['PREPARE','ORDER','ALLOCATION','INCREMENTAL','REVIEW','CANCEL'])test('actual HTTP '+operation+' observes withdrawn membership after its Procurement body wait',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'procurement-action-authority-')),barrier=path.join(dir,'body'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../test-identity-body-barrier'),FOUNDLY_IDENTITY_BODY_BARRIER:barrier});let request;try{
 assert.equal((await f.request('/api/composition','PUT',{entitlements:['procurement'],expected_revision:0})).status,200);const buyer=await f.enroll('procurement.authority.buyer',['MANAGER']),reviewer=await f.enroll('procurement.authority.reviewer',['ADMIN']);assert.equal((await f.request('/api/procurement/approval_policies','POST',{name:'PRIVATE approval policy',status:'OPEN',currency:'EUR',minimum_value_cents:0,approval_steps:[reviewer.member.id]})).status,201);const create=async(entity,input)=>{const r=await f.request('/api/procurement/'+entity,'POST',input,buyer.cookie);assert.equal(r.status,201);return r.body.record;},supplier=await create('suppliers',{name:'PRIVATE supplier'}),rfq=await create('rfqs',{title:'PRIVATE RFQ',currency:'EUR',lines:[{item_id:'item',description:'PRIVATE item',quantity:2}]}),bid=await create('bids',{title:'PRIVATE bid',currency:'EUR',rfq_id:rfq.id,rfq_revision:1,supplier_id:supplier.id,evidence_reference:'PRIVATE source',lines:[{item_id:'item',quantity:2,unit_price_cents:1000}]}),preview=await f.request('/api/procurement/rfqs/'+rfq.id+'/award-preview?bid_id='+bid.id,'GET',undefined,buyer.cookie);assert.equal(preview.status,200);const proposal={bid_id:bid.id,preview_fingerprint:preview.body.preview_fingerprint,reason:'PRIVATE delayed proposal',confirm:true};let actor=buyer,route='/api/procurement/rfqs/'+rfq.id+'/awards',input=proposal,award=null;
 if(operation==='ORDER'){const order=await create('orders',{title:'PRIVATE order',value_cents:2000,currency:'EUR',evidence_reference:'PRIVATE order source'}),basis=await f.request('/api/procurement/orders/'+order.id+'/approval-preview','GET',undefined,buyer.cookie);assert.equal(basis.status,200);route='/api/procurement/orders/'+order.id+'/approvals';input={preview_fingerprint:basis.body.preview_fingerprint,reason:'PRIVATE order reason',confirm:true};}
 if(['ALLOCATION','INCREMENTAL'].includes(operation)){route='/api/procurement/rfqs/'+rfq.id+'/'+(operation==='ALLOCATION'?'allocation-preview':'incremental-allocation-preview');input={allocations:[{bid_id:bid.id,item_id:'item',quantity:2}]};}
 if(['REVIEW','CANCEL'].includes(operation)){const created=await f.request(route,'POST',proposal,buyer.cookie,{'idempotency-key':'initial-proposal'});assert.equal(created.status,201);award=created.body.record;route='/api/procurement/awards/'+award.id+'/'+(operation==='REVIEW'?'approve':'cancel');actor=operation==='REVIEW'?reviewer:buyer;input={expected_revision:1,...(operation==='REVIEW'?{decision:'APPROVE',reason:'PRIVATE delayed decision'}:{}),confirm:true};}
 const data=JSON.stringify(input),pending=new Promise((resolve,reject)=>{request=http.request(f.base+route,{method:'POST',headers:{cookie:actor.cookie,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(data),'idempotency-key':'delayed-action','x-identity-fixture-barrier':'body'}},res=>{let raw='';res.on('data',x=>raw+=x);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(raw)}));});request.on('error',reject);request.write(data.slice(0,-1));});pending.catch(()=>{});for(let n=0;n<100&&!fs.existsSync(barrier);n++)await new Promise(r=>setTimeout(r,20));assert.ok(fs.existsSync(barrier));assert.equal((await f.request('/api/identity/users/'+actor.member.id,'PUT',{roles:['VIEWER'],expected_revision:actor.member.revision,confirm:true,reason:'Withdraw authority during action body wait'})).status,200);request.end(data.slice(-1));const denied=await pending;assert.equal(denied.status,401);assert.ok(!JSON.stringify(denied.body).includes('PRIVATE'));const rows=(await f.request('/api/procurement/awards')).body.items;assert.equal(rows.length,award?1:0);if(award){assert.equal(rows[0].revision,1);assert.equal(rows[0].reviews.length,0);assert.equal(rows[0].status,'APPROVAL_REQUIRED');}
 }finally{request?.destroy();await f.close();fs.rmSync(dir,{recursive:true,force:true});}});
