'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{fixture}=require('../zero-evaluation/fixture'),{page}=require('../zero-evaluation/procurement-award-page-fixture'),{locales}=require('../foundly-locales');
test('actual HTTP allocation and review controls retain exact confirmed bodies across locales, lost acknowledgements and encrypted server restarts',async()=>{const server=await fixture();try{
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['procurement'],expected_revision:0})).status,200);const buyer=await server.enroll('award.page.buyer',['MANAGER']),reviewer=await server.enroll('award.page.reviewer',['ADMIN']);assert.equal((await server.request('/api/procurement/approval_policies','POST',{name:'Literal reviewer policy',status:'OPEN',currency:'EUR',minimum_value_cents:0,approval_steps:[reviewer.member.id]})).status,201);
 const create=async(entity,input)=>{const r=await server.request('/api/procurement/'+entity,'POST',input,buyer.cookie);assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;},supplier=await create('suppliers',{name:'PRIVATE actual supplier'}),rfq=await create('rfqs',{title:'PRIVATE actual request',currency:'EUR',lines:[{item_id:'literal_item',description:'PRIVATE actual item',quantity:1}]}),bid=await create('bids',{title:'PRIVATE actual bid',currency:'EUR',rfq_id:rfq.id,rfq_revision:1,supplier_id:supplier.id,evidence_reference:'PRIVATE actual offer',lines:[{item_id:'literal_item',quantity:1,unit_price_cents:9007199254740990}]});
 const preparedWrites=[],reviewWrites=[];let dropPrepare=true,dropReview=true;
 const transport=member=>async(route,opts={})=>{const input=opts.body?JSON.parse(opts.body):undefined,prepare=route==='/api/zero/turn'&&input.client_context.procurement_action.operation==='PREPARE',review=/\/awards\/[^/]+\/approve$/.test(route);if(prepare)preparedWrites.push(opts.body);if(review)reviewWrites.push({body:opts.body,key:opts.headers['idempotency-key']});const r=await server.request(route,opts.method||'GET',input,member.cookie,opts.headers);if(prepare&&r.status===200&&dropPrepare){dropPrepare=false;throw Error('Isolated loss after committed HTTP proposal');}if(review&&r.status===200&&dropReview){dropReview=false;throw Error('Isolated loss after committed HTTP review');}return {ok:r.status<400,status:r.status,json:async()=>r.body};};
 const f=await page({transport:transport(buyer)});await f.compare();f.field('quantity').value='1';await f.field('quantity').fire('input');f.field('transport').value='zero';await f.field('transport').fire('change');await f.action('check_allocation').parentNode.fire('submit');const box=f.proposal(),form=box.querySelector('form');assert.ok(box.textContent.includes(f.i.currencyCents(9007199254740990,'EUR')));f.field('reason',box).value='Literal PRIVATE explicit HTTP allocation';await form.fire('submit');assert.equal(preparedWrites.length,1);for(const locale of locales){f.i.setLocale(locale);assert.equal(preparedWrites.length,1);assert.ok(box.textContent.includes(f.i.t('procurement.award.pending')));}await server.stop();await server.start();buyer.cookie=await server.login(buyer);await form.fire('submit');assert.equal(preparedWrites.length,2);assert.equal(preparedWrites[0],preparedWrites[1]);const proposals=await server.request('/api/procurement/awards','GET',undefined,buyer.cookie);assert.equal(proposals.status,200);assert.equal(proposals.body.total,1);const award=proposals.body.items[0];assert.equal(award.value_cents,9007199254740990);assert.equal(award.rfq_id,rfq.id);assert.equal(award.allocation_lines[0].bid_id,bid.id);
 reviewer.cookie=await server.login(reviewer);const r=await page({entity:'awards',transport:transport(reviewer)});await r.render();const detail=r.detail(),reviewForm=detail.querySelector('form');r.field('reason',detail).value='Literal PRIVATE actual review';await reviewForm.fire('submit');assert.equal(reviewWrites.length,1);for(const locale of locales){r.i.setLocale(locale);assert.equal(reviewWrites.length,1);assert.ok(detail.textContent.includes(r.i.t('procurement.award.pending')));}await server.stop();await server.start();reviewer.cookie=await server.login(reviewer);await reviewForm.fire('submit');assert.equal(reviewWrites.length,2);assert.deepEqual(reviewWrites[0],reviewWrites[1]);const approved=await server.request('/api/procurement/awards/'+award.id,'GET',undefined,reviewer.cookie);assert.equal(approved.status,200);assert.equal(approved.body.record.status,'APPROVED_INTERNAL');assert.equal(approved.body.record.revision,2);assert.equal(approved.body.record.reviews.length,1);assert.ok(detail.textContent.includes(r.i.t('procurement.award.review_saved',{status:r.i.t('procurement.award.status_approved_internal')})));assert.equal((await server.request('/api/procurement/orders','GET',undefined,reviewer.cookie)).body.total,0);
 const html=await server.request('/procurement','GET',undefined,reviewer.cookie);assert.equal(html.status,200);assert.ok(html.body.indexOf('src="/foundly-workspace.js"')>html.body.indexOf('src="/foundly-i18n.js"'));const asset=await server.request('/foundly-workspace.js','GET',undefined,reviewer.cookie);assert.equal(asset.status,200);assert.equal(asset.body,fs.readFileSync(require.resolve('../foundly-workspace.js'),'utf8'));
 }finally{await server.close();}});
