'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture'),{page}=require('../zero-evaluation/procurement-award-page-fixture'),{locales}=require('../foundly-locales');
// Actual shared DOM controller over real HTTP. This is not a browser/layout/AT fixture.
for(const mode of ['native','zero'])test('actual '+mode+' HTTP controls recover after destroyed replies, encrypted server restart and a fresh DOM page without resubmitting the proposal or review',async()=>{const server=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/procurement-action-ack-drop')});try{
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['procurement'],expected_revision:0})).status,200);const buyer=await server.enroll('recovery.page.buyer',['MANAGER']),reviewer=await server.enroll('recovery.page.reviewer',['ADMIN']);assert.equal((await server.request('/api/procurement/approval_policies','POST',{name:'PRIVATE policy',status:'OPEN',currency:'EUR',minimum_value_cents:0,approval_steps:[reviewer.member.id]})).status,201);
 const create=async(entity,input)=>{const r=await server.request('/api/procurement/'+entity,'POST',input,buyer.cookie);assert.equal(r.status,201);return r.body.record;},supplier=await create('suppliers',{name:'PRIVATE actual supplier'}),rfq=await create('rfqs',{title:'PRIVATE actual RFQ',currency:'EUR',lines:[{item_id:'literal_item',description:'PRIVATE actual item',quantity:1}]}),bid=await create('bids',{title:'PRIVATE actual bid',currency:'EUR',rfq_id:rfq.id,rfq_revision:1,supplier_id:supplier.id,evidence_reference:'PRIVATE actual source',lines:[{item_id:'literal_item',quantity:1,unit_price_cents:9007199254740990}]});
 const calls=[];let dropPrepare=true,dropReview=true;const transport=member=>async(route,opts={})=>{const input=opts.body?JSON.parse(opts.body):undefined,prepare=/\/rfqs\/[^/]+\/awards$/.test(route)||route==='/api/zero/turn'&&input.client_context?.procurement_action?.operation==='PREPARE',review=/\/awards\/[^/]+\/approve$/.test(route),drop=prepare&&dropPrepare||review&&dropReview;if(prepare)dropPrepare=false;if(review)dropReview=false;calls.push({route,method:opts.method||'GET',body:opts.body,prepare,review});const r=await server.request(route,opts.method||'GET',input,member.cookie,{...opts.headers,...(drop?{'x-procurement-drop-reply':'isolated-action-fixture'}:{})});return {ok:r.status<400,status:r.status,json:async()=>r.body};};
 const f=await page({transport:transport(buyer)});await f.prepare();const proposal=f.proposal(),form=proposal.querySelector('form');if(mode==='zero'){const select=proposal.procurementHost.querySelector('select');select.value='zero';await select.fire('change');}f.field('reason',proposal).value='PRIVATE original HTTP proposal';await form.fire('submit');const stored=[...f.saved.entries()].filter(([key])=>key.startsWith('foundly.procurement.actions.v1:'));assert.equal(stored.length,1);assert.deepEqual(Object.keys(JSON.parse(stored[0][1])[0]).sort(),['operation','request_fingerprint','request_id','source_id']);assert.ok(!JSON.stringify(stored).includes('PRIVATE'));assert.equal(calls.filter(c=>c.prepare).length,1);
 await server.stop();await server.start();buyer.cookie=await server.login(buyer);reviewer.cookie=await server.login(reviewer);const list=await server.request('/api/procurement/awards','GET',undefined,buyer.cookie);assert.equal(list.body.total,1);const award=list.body.items[0];assert.equal(award.rfq_id,rfq.id);assert.equal(award.bid_id,bid.id);
 const reviewPage=await page({entity:'awards',transport:transport(reviewer)});await reviewPage.render();const reviewForm=reviewPage.detail().querySelector('form');reviewPage.field('reason',reviewPage.detail()).value='PRIVATE later HTTP review';await reviewForm.fire('submit');assert.equal(calls.filter(c=>c.review).length,1);await server.stop();await server.start();buyer.cookie=await server.login(buyer);reviewer.cookie=await server.login(reviewer);
 for(const [old,expectedOriginal]of [[f,'procurement.award.status_approval_required'],[reviewPage,'procurement.award.status_approved_internal']]){const r=await old.reload();await r.render();const count=calls.length;assert.equal(calls.filter(c=>c.route==='/api/procurement/action-requests/recover').length,old===f?0:1);for(const locale of locales)r.i.setLocale(locale);assert.equal(calls.length,count);await r.recoveryAction('recover').fire('click');assert.ok(r.recovery().textContent.includes(r.i.t(expectedOriginal)));assert.ok(r.recovery().textContent.includes(r.i.t('procurement.award.status_approved_internal')));assert.ok(r.recovery().textContent.includes('PRIVATE later HTTP review'));assert.ok(r.recovery().textContent.includes(r.i.currencyCents(9007199254740990,'EUR')));assert.ok(r.recovery().textContent.includes(r.i.t('procurement.recovery.recovered')));assert.equal([...r.saved.keys()].filter(k=>k.startsWith('foundly.procurement.actions.v1:')).length,0);assert.equal(r.recovery().canLeave(),true);}
 assert.equal(calls.filter(c=>c.prepare).length,1);assert.equal(calls.filter(c=>c.review).length,1);const final=await server.request('/api/procurement/awards/'+award.id,'GET',undefined,buyer.cookie);assert.equal(final.body.record.revision,2);assert.equal(final.body.record.reviews.length,1);assert.equal((await server.request('/api/procurement/orders','GET',undefined,buyer.cookie)).body.total,0);assert.ok(!fs.readFileSync(path.join(server.dir,'foundly-core-state.json'),'utf8').includes('PRIVATE'));
 const html=await server.request('/procurement','GET',undefined,buyer.cookie);for(const name of ['procurement-action-client-state.js','procurement-action-client.js']){assert.ok(html.body.includes('src="/'+name+'"'));assert.ok(html.body.indexOf('src="/'+name+'"')<html.body.indexOf('src="/foundly-workspace.js"'));const asset=await server.request('/'+name,'GET',undefined,buyer.cookie);assert.equal(asset.status,200);assert.equal(asset.body,fs.readFileSync(require.resolve('../'+name),'utf8'));}
 }finally{await server.close();}});
