'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/sales-hierarchy-client-fixture');
const locales=['nl-NL','en-GB','de-DE','fr-FR','es-ES','da-DK','nb-NO','sv-SE'];
test('hierarchy pending save stays localized without requests or losing literal input and confirmation',async()=>{const f=fixture();await f.ready();await f.fill();f.lose();await f.submit();const calls=f.calls.length,title=f.field('title');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.field('title'),title);assert.equal(title.value,'Literal private hierarchy draft');assert.equal(f.field('confirm').checked,true);assert.equal(f.notice().textContent,f.i.t('sales.hierarchy.uncertain'));assert.equal(f.control('save').textContent,f.i.t('sales.hierarchy.recover'));assert.equal(f.calls.length,calls);assert.equal(f.box.canLeave(),false);}assert.ok(!f.box.textContent.includes('PRIVATE'));});
test('hierarchy absence preserves draft and requires fresh confirmation and a distinct request ID; retired PUT cannot execute',async()=>{const f=fixture();await f.ready();await f.fill();f.loseBefore();await f.submit();const original=f.writes()[0];await f.submit();assert.equal(f.notice().textContent,f.i.t('sales.hierarchy.not_applied'));assert.equal(f.field('title').value,'Literal private hierarchy draft');assert.equal(f.field('confirm').checked,false);await f.submit();assert.equal(f.writes().length,1);assert.throws(()=>f.native.apply({id:original.route.split('/').at(-1),input:original.input}),e=>e.code==='hierarchy_request_abandoned');f.field('confirm').checked=true;await f.submit();assert.equal(f.writes().length,2);assert.notEqual(f.writes()[1].route,original.route);assert.equal(f.native.records().length,1);});
test('hierarchy storage failure blocks mutation and refresh preserves the draft for explicit retry',async()=>{const f=fixture();await f.ready();await f.fill();f.failStorage();await f.submit();assert.equal(f.writes().length,0);const title=f.field('title');f.restoreStorage();await f.control('refresh').fire('click');assert.equal(f.field('title'),title);assert.equal(title.value,'Literal private hierarchy draft');await f.submit();assert.equal(f.writes().length,1);assert.equal(f.native.records().length,1);});
test('hierarchy cleanup failure retains proof and metadata until explicit recovery; no extra PUT',async()=>{const f=fixture();await f.ready();await f.fill();f.failCleanup();await f.submit();assert.equal(f.storage.size,1);assert.equal(f.notice().textContent,f.i.t('sales.hierarchy.cleanup'));assert.ok(f.box.textContent.includes('Literal private hierarchy draft'));f.restoreStorage();await f.control('refresh').fire('click');await f.control('recover').fire('click');assert.equal(f.storage.size,0);assert.equal(f.writes().length,1);assert.equal(f.native.records().length,1);});
test('recovery by a second widget cannot release the first widget into another PUT',async()=>{const first=fixture();await first.ready();await first.fill();first.lose();await first.submit();const fresh=fixture({native:first.native,storage:first.storage});await fresh.ready();await fresh.submit();assert.equal(first.storage.size,0);await first.submit();assert.equal(first.writes().length,1);assert.equal(first.recoveries().length,1);assert.equal(first.native.records().length,1);});
for(const [label,change]of [
 ['wrong record title',d=>{d.record.title='Forged title';}],
 ['wrong actor acknowledgement',d=>{d.request_acknowledgement.request_context.actor_id='other';}],
 ['false immutable claim',d=>{d.record.immutable=false;}],
 ['missing result hash',d=>{delete d.request_acknowledgement.result_snapshot_sha256;}],
 ['wrong result identity',d=>{d.record.id='another';}]
])test('hierarchy rejects '+label+' and retains metadata for native recovery',async()=>{const f=fixture({alter:(d,r,m)=>{if(m==='PUT')change(d);return d;}});await f.ready();await f.fill();await f.submit();assert.equal(f.storage.size,1);assert.equal(f.notice().textContent,f.i.t('sales.hierarchy.uncertain'));assert.ok(f.field('title'));f.alter(null);await f.submit();assert.equal(f.storage.size,0);assert.equal(f.writes().length,1);});
test('contradictory terminal recovery does not clear metadata or invent absence',async()=>{const f=fixture();await f.ready();await f.fill();f.lose();await f.submit();f.alter((d,r)=>{if(r.endsWith('/recover')){d.state='NOT_APPLIED';}return d;});await f.submit();assert.equal(f.storage.size,1);assert.ok(f.control('recover'));assert.equal(f.native.records().length,1);});
test('incomplete catalog is not writable empty success and has a working refresh',async()=>{const f=fixture({alter:(d,r)=>{if(r.endsWith('/hierarchies'))delete d.total;return d;}});await f.ready();assert.equal(f.control('create'),undefined);assert.equal(f.notice().textContent,f.i.t('sales.hierarchy.invalid'));f.alter(null);await f.control('refresh').fire('click');assert.equal(f.control('create').disabled,false);});
test('catalog scope changes erase private draft and do not transfer opaque requests to another actor',async()=>{const f=fixture();await f.ready();await f.fill();const title=f.field('title');f.alter((d,r)=>{if(r.endsWith('/hierarchies'))d.request_context.actor_id='other';return d;});await f.control('refresh').fire('click');assert.equal(title.value,'');assert.equal(f.field('title'),undefined);assert.equal(f.notice().textContent,f.i.t('common.access_denied'));assert.equal(f.box.canLeave(),true);});
test('current access denial clears all private content while preserving only opaque recovery identity',async()=>{const f=fixture();await f.ready();await f.fill();f.lose();await f.submit();const title=f.field('title');f.deny();await f.submit();assert.equal(title.value,'');assert.ok(!f.box.textContent.includes('Literal'));assert.equal(f.storage.size,1);assert.equal(f.box.canLeave(),true);assert.equal(f.writes().length,1);});
test('concurrent submissions are suppressed and detached replies cannot render or clear recovery metadata',async()=>{const f=fixture();await f.ready();await f.fill();const release=f.hold('/hierarchies/'),pending=f.submit();await release.started;await f.submit();assert.equal(f.writes().length,1);assert.equal(f.box.canLeave(),false);f.retire();release();await pending;assert.equal(f.storage.size,1);assert.equal(f.native.records().length,1);});
test('confirmation is reset by definition edits and invalid topology never reaches native mutation',async()=>{const f=fixture();await f.ready();await f.fill();f.field('node_parent').value='missing';await f.field('node_parent').fire('input');assert.equal(f.field('confirm').checked,false);f.field('confirm').checked=true;await f.submit();assert.equal(f.writes().length,0);assert.equal(f.notice().textContent,f.i.t('sales.hierarchy.definition_invalid'));});
test('recovering another panel request preserves an unrelated current draft',async()=>{const first=fixture();await first.ready();await first.fill();const other=fixture({native:first.native,storage:first.storage});await other.ready();await other.fill();other.lose();await other.submit();await first.submit();assert.equal(first.writes().length,0);await first.submit();assert.equal(first.field('title').value,'Literal private hierarchy draft');assert.equal(first.box.canLeave(),false);assert.equal(first.native.records().length,1);});
test('access denial during catalog refresh after a verified save is not replaced with a success message',async()=>{let committed=false;const f=fixture({alter:(d,r,m)=>{if(m==='PUT')committed=true;if(committed&&m==='GET')throw Object.assign(Error('PRIVATE after-save denial'),{status:403});return d;}});await f.ready();await f.fill();await f.submit();assert.equal(f.notice().textContent,f.i.t('common.access_denied'));assert.ok(!f.box.textContent.includes('Literal'));assert.equal(f.native.records().length,1);});
