'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture,hash,clone}=require('../zero-evaluation/sales-sequence-fixture');
test('sequence definitions retain exact typed acknowledgement and metadata recovery across restart',()=>{const f=fixture(),r=f.define(),saved=f.apply(r);assert.deepEqual(saved.request_acknowledgement.request,r.meta);f.restart();const p=f.recover(r);assert.deepEqual(p.result_snapshot,saved.record);assert.equal(p.result_snapshot_sha256,hash(saved.record));assert.equal(p.result_is_current,true);});
test('old sequence enrollment cannot acknowledge a later paused run as the original successful start',()=>{const f=fixture(),r=f.start(),saved=f.apply(r);f.apply(f.control(saved.record.id,'PAUSE'));assert.throws(()=>f.apply(r),{code:'sequence_result_changed'});});
test('sequence enrollment recovery rechecks source access without requiring the original opportunity revision to stay current',()=>{const f=fixture(),r=f.start(),saved=f.apply(r);f.core.save(f.ctx,f.actor,'opportunities',{title:'Later literal source'},{id:f.opportunity.id,expected_revision:1});f.restart();const p=f.recover(r);assert.deepEqual(p.result_snapshot,saved.record);assert.equal(p.result_is_current,true);assert.equal(f.core.bucket(f.ctx,'tasks').length,0);});
test('sequence task creation and completion retain separate original and current task evidence after reopening',()=>{const f=fixture(),id=f.enroll(),advance=f.advance(id);f.apply(advance);const complete=f.complete(id);f.apply(complete);const task=f.core.bucket(f.ctx,'tasks')[0];f.core.save(f.ctx,f.actor,'tasks',{status:'OPEN'},{id:task.id,expected_revision:task.revision});f.restart();const p=f.recover(complete);assert.equal(p.effects[0].result_snapshot.status,'COMPLETED');assert.equal(p.effects[0].record.status,'OPEN');assert.equal(p.result_is_current,false);assert.throws(()=>f.apply(complete),{code:'sequence_result_changed'});assert.equal(f.recover(advance).effects[0].result_snapshot.status,'OPEN');assert.equal(f.core.bucket(f.ctx,'tasks').length,1);});
test('sequence control recovery preserves superseding cancellation without changing current native state',()=>{const f=fixture(),id=f.enroll(),requests=[];for(const op of ['PAUSE','RESUME','CANCEL']){const r=f.control(id,op);f.apply(r);requests.push(r);}f.restart();for(const [i,r]of requests.entries()){const p=f.recover(r);assert.equal(p.result_snapshot.status,['PAUSED','ACTIVE','CANCELLED'][i]);assert.equal(p.record.status,'CANCELLED');assert.equal(p.result_is_current,i===2);}});
test('sequence outcome recovery preserves the original observation after the opportunity and feedback change without claiming causation',()=>{const f=fixture(),id=f.enroll(),r=f.outcome(id);f.apply(r);f.core.save(f.ctx,f.actor,'opportunities',{status:'WON'},{id:f.opportunity.id,expected_revision:1});f.apply(f.outcome(id));f.restart();const p=f.recover(r);assert.equal(p.result_snapshot.outcome_feedback[0].recorded_status,'DRAFT');assert.equal(p.record.outcome_feedback[1].recorded_status,'WON');assert.equal(p.result_is_current,false);assert.equal(p.result_snapshot.outcome_feedback[0].causal_attribution,'NOT_ESTABLISHED');assert.equal(p.source_records_modified,false);});
test('absent sequence requests for every mutation close durably before a delayed original body arrives',()=>{for(const op of ['DEFINE','START','ADVANCE','COMPLETE_TASK','PAUSE','RESUME','CANCEL','OUTCOME_FEEDBACK']){const f=fixture();let r;if(op==='DEFINE')r=f.define();else if(op==='START')r=f.start();else{const id=f.enroll();if(op==='COMPLETE_TASK')f.apply(f.advance(id));if(op==='RESUME')f.apply(f.control(id,'PAUSE'));r=op==='ADVANCE'?f.advance(id):op==='COMPLETE_TASK'?f.complete(id):op==='OUTCOME_FEEDBACK'?f.outcome(id):f.control(id,op);}const before=hash(f.core.bucket(f.ctx,'sequence_runs'));assert.equal(f.recover(r).state,'NOT_APPLIED');f.restart();assert.throws(()=>f.apply(r),{code:'sequence_request_abandoned'});assert.equal(hash(f.core.bucket(f.ctx,'sequence_runs')),before);}});
test('sequence recovery binds exact actor metadata and rejects original source ownership changes even for administrators',()=>{const f=fixture(),r=f.start();f.apply(r);assert.throws(()=>f.recover(r,{...r.meta,request_fingerprint:'0'.repeat(64)}),{code:'sequence_operation_conflict'});assert.throws(()=>f.recover(r,r.meta,f.admin),{code:'sequence_recovery_unverifiable'});f.core.bucket(f.ctx,'opportunities')[0].owner_id='later-owner';assert.throws(()=>f.recover(r,r.meta,{...f.actor,roles:['SUPER_ADMIN']}),{code:'sequence_recovery_owner_changed'});});
test('sequence result and closure receipts roll back atomically with native records on persistence failure',()=>{const f=fixture(),r=f.start(),before=f.snapshot();f.fail(true);assert.throws(()=>f.apply(r),{code:'EIO'});assert.equal(f.snapshot(),before);assert.throws(()=>f.recover(r),{code:'EIO'});assert.equal(f.snapshot(),before);f.fail(false);assert.equal(f.recover(r).state,'NOT_APPLIED');});
test('legacy and damaged sequence receipts cannot acquire fabricated original result proof',()=>{const f=fixture(),r=f.start();f.apply(r);const e=f.receipts().find(x=>x.key===r.key),saved=clone(e);delete e.request_kind;assert.throws(()=>f.recover(r),{code:'sequence_recovery_unverifiable'});Object.assign(e,saved);e.result_snapshot.history[0].reason='Damaged original reason';assert.throws(()=>f.recover(r),{code:'sequence_recovery_unverifiable'});});
test('sequence draft recovery verifies native draft output and current communication authority without sending',()=>{const f=fixture({mail:true}),id=f.enroll(),r=f.advance(id);f.apply(r);f.restart();const p=f.recover(r);assert.equal(p.effects[0].entity,'drafts');assert.equal(p.effects[0].record.delivery_state,'NOT_SENT');assert.equal(p.result_snapshot_sha256,hash(p.result_snapshot));assert.equal(f.communication.bucket(f.ctx,'messages').length,0);f.resolver.configure(f.ctx,f.admin,{entitlements:['sales','communication'],enabled_modules:['sales'],expected_revision:1});assert.throws(()=>f.recover(r),{code:'module_disabled',statusCode:403});});
test('resuming a sequence whose current opportunity is closed cannot reactivate internal execution',()=>{const f=fixture(),id=f.enroll();f.apply(f.control(id,'PAUSE'));f.core.save(f.ctx,f.actor,'opportunities',{status:'WON'},{id:f.opportunity.id,expected_revision:1});assert.throws(()=>f.apply(f.control(id,'RESUME')),{code:'sequence_source_closed'});assert.equal(f.view(id).record.status,'PAUSED');});

test('sequence definition confirmation reasons bind both the request identity and immutable version',()=>{const f=fixture(),r=f.define({reason:'Literal definition reason'});f.apply(r);assert.throws(()=>f.apply({...r,input:{...r.input,reason:'Different reason'}}),{code:'sequence_operation_conflict'});const fresh=f.reference('DEFINE',r.sourceId,{...r.input,reason:'Different reason'});assert.throws(()=>f.apply(fresh),{code:'sequence_version_immutable'});});
test('sequence recovery denies revoked Sales capability and malformed metadata while retaining native proof',()=>{const f=fixture(),r=f.start();f.apply(r);assert.throws(()=>f.recover(r,{...r.meta,expected_revision:0}),{code:'sequence_recovery_invalid'});assert.throws(()=>f.recover(r,{...r.meta,reason:'Not metadata'}),{code:'sequence_recovery_invalid'});f.resolver.configure(f.ctx,f.admin,{entitlements:['sales','communication'],enabled_modules:['communication'],expected_revision:1});assert.throws(()=>f.recover(r),{code:'module_disabled'});assert.equal(f.receipts().find(x=>x.key===r.key).state,'APPLIED');});
test('bounded sequence receipts reject new mutations and closures while preserving existing verification',()=>{const f=fixture(),r=f.start(),rows=f.receipts();while(rows.length<100000)rows.push({key:'prior-'+rows.length,actor_id:'other'});assert.throws(()=>f.apply(r),{code:'sequence_operation_capacity'});assert.throws(()=>f.recover(r),{code:'sequence_operation_capacity'});assert.equal(f.recover(f.definitionRequest).state,'APPLIED');});
test('sequence recovery rejects damaged effect snapshots and missing parent provenance',()=>{const f=fixture(),id=f.enroll(),r=f.advance(id);f.apply(r);const e=f.receipts().find(x=>x.key===r.key),saved=clone(e);e.effects[0].result_snapshot.title='Changed original task';assert.throws(()=>f.recover(r),{code:'sequence_recovery_unverifiable'});Object.assign(e,saved);e.parents=[];assert.throws(()=>f.recover(r),{code:'sequence_recovery_unverifiable'});});
