'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/sales-forecast-snapshot-client-fixture'),{locales}=require('../foundly-i18n'),{hash}=require('../zero-evaluation/sales-forecast-fixture');
test('forecast snapshot controls preserve literal input and form nodes in all eight locales without native requests',async()=>{const f=fixture();await f.ready();await f.fill();const field=f.field(),calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.field(),field);assert.equal(field.value,'Literal private forecast title');assert.equal(f.control('save').textContent,f.i.t('sales.forecast_snapshot.save'));assert.equal(f.calls.length,calls);assert.ok(!f.box.textContent.includes('sales.forecast_snapshot.'));}assert.equal(f.box.canLeave(),false);});
test('uncertain forecast snapshot replies recover exact metadata without replaying a changed private title',async()=>{const f=fixture();await f.ready();f.lose();await f.save();f.field().value='New unsent private title';await f.submit();assert.equal(f.writes().length,1);assert.equal(f.calls.filter(c=>c.recovery).length,1);assert.equal(f.field().value,'New unsent private title');assert.equal(f.native.core.bucket(f.native.ctx,'forecast_snapshots')[0].title,'Literal private forecast title');assert.equal(f.notice().textContent,f.i.t('sales.forecast_snapshot.recovered'));assert.equal(f.storage.size,0);});
test('fresh forecast recovery panels restore pending metadata after restart without storing input or performing a new calculation',async()=>{const f=fixture();await f.ready();f.lose();await f.save();const raw=[...f.storage.values()][0],entries=JSON.parse(raw);assert.equal(Object.keys(entries[0]).length,3);assert.ok(!raw.includes('Literal'));f.native.core.save(f.native.ctx,f.native.actor,'opportunities',{value_cents:50000},{id:f.native.opportunity.id,expected_revision:1});f.native.restart();const fresh=fixture({native:f.native,storage:f.storage,recoveryOnly:true});await fresh.ready();await fresh.submit();assert.equal(fresh.writes().length,0);assert.equal(fresh.storage.size,0);assert.equal(fresh.notice().textContent,fresh.i.t('sales.forecast_snapshot.recovered'));assert.equal(f.native.core.bucket(f.native.ctx,'forecast_snapshots')[0].forecast.groups[0].weighted_cents,5001);});
test('absent forecast saves close durably and no later body can be executed',async()=>{const f=fixture();await f.ready();f.loseBefore();await f.save();const old=f.writes()[0];await f.submit();assert.equal(f.notice().textContent,f.i.t('sales.forecast_snapshot.not_applied'));assert.throws(()=>require('../sales-forecast').snapshotForecast(f.native.core,f.native.ctx,f.native.actor,old.input,{idempotency_key:old.key}),{code:'forecast_request_abandoned'});assert.equal(f.native.core.bucket(f.native.ctx,'forecast_snapshots').length,0);});
test('contradictory forecast acknowledgements retain metadata even when their result digest is coherent',async()=>{const f=fixture();await f.ready();f.alter((d,r,m)=>{if(m==='POST'&&!r.includes('requests')){d.record.forecast.groups[0].weighted_cents=999;d.request_acknowledgement.result_snapshot_sha256=hash(d.record);}return d;});await f.save();assert.equal(f.storage.size,1);assert.equal(f.notice().textContent,f.i.t('sales.forecast_snapshot.uncertain'));f.alter(null);await f.submit();assert.equal(f.writes().length,1);assert.equal(f.storage.size,0);});
test('contradictory forecast terminal proofs cannot free an uncertain request or allow a duplicate save',async()=>{const f=fixture();await f.ready();f.lose();await f.save();f.alter((d,r)=>{if(r.includes('requests'))d.snapshot_created=true;return d;});await f.submit();assert.equal(f.storage.size,1);assert.equal(f.writes().length,1);assert.equal(f.box.canLeave(),false);});
test('forecast metadata storage failure blocks writes and failed cleanup does not erase a known saved result',async()=>{const f=fixture();await f.ready();f.failStorage();await f.save();assert.equal(f.writes().length,0);assert.equal(f.notice().textContent,f.i.t('sales.forecast_snapshot.storage'));const g=fixture();await g.ready();g.failCleanup();await g.save();assert.equal(g.notice().textContent,g.i.t('sales.forecast_snapshot.cleanup'));assert.equal(g.writes().length,1);await g.submit();assert.equal(g.writes().length,1);g.restoreStorage();await g.control('refresh').fire('click');await g.control('recover').fire('click');assert.equal(g.storage.size,0);});
test('late forecast replies preserve their recovery metadata after the view is retired',async()=>{const f=fixture();await f.ready();const release=f.hold('/snapshots'),pending=f.save();await release.started;f.retire();const old=f.notice().textContent;release();await pending;assert.equal(f.storage.size,1);assert.equal(f.notice().textContent,old);});
test('forecast recovery denial clears private title and retained result while preserving only opaque metadata',async()=>{const f=fixture();await f.ready();f.lose();await f.save();f.deny();await f.submit();assert.equal(f.storage.size,1);assert.equal(f.field()?.value??'','');assert.ok(!f.box.textContent.includes('Literal'));assert.equal(f.notice().textContent,f.i.t('common.access_denied'));assert.equal(f.box.canLeave(),true);});
test('forecast context failure leaves a working retry and malformed metadata cannot be discarded by it',async()=>{const f=fixture({alter:d=>{delete d.request_context;return d;}});await f.ready();assert.equal(f.notice().textContent,f.i.t('sales.forecast_snapshot.invalid'));f.alter(null);await f.control('refresh').fire('click');await f.save();assert.equal(f.writes().length,1);const g=fixture();await g.ready();const key='foundly.sales.forecast.snapshots.v1:'+JSON.stringify([g.native.ctx.tenant_id,g.native.ctx.dealer_id,g.native.actor.id]);g.storage.set(key,'not JSON');await g.save();assert.equal(g.writes().length,0);assert.equal(g.storage.get(key),'not JSON');});

test('forecast input survives a storage outage and refresh restores saving without losing the exact title',async()=>{const f=fixture();await f.ready();await f.fill();const field=f.field();f.failStorage();await f.submit();assert.equal(f.writes().length,0);f.restoreStorage();await f.control('refresh').fire('click');assert.equal(f.field(),field);assert.equal(field.value,'Literal private forecast title');await f.submit();assert.equal(f.writes().length,1);assert.equal(f.storage.size,0);});
test('multiple forecast panels cannot duplicate an action after another panel recovers its request',async()=>{const f=fixture();await f.ready();f.lose();await f.save();const other=fixture({native:f.native,storage:f.storage,recoveryOnly:true});await other.ready();await other.submit();assert.equal(f.storage.size,0);await f.control('refresh').fire('click');assert.equal(f.control('save').textContent,f.i.t('sales.forecast_snapshot.recover'));assert.equal(f.box.canLeave(),false);f.field().value='Another unsent title';await f.submit();assert.equal(f.writes().length,1);assert.equal(f.calls.filter(c=>c.recovery).length,1);assert.equal(f.native.core.bucket(f.native.ctx,'forecast_snapshots').length,1);assert.equal(f.box.canLeave(),true);});
test('a pending forecast write accepts neither duplicate submit nor cancellation while locale changes preserve its exact identity',async()=>{const f=fixture();await f.ready();await f.fill();const release=f.hold('/snapshots'),pending=f.submit();await release.started;const metadata=JSON.stringify([...f.storage]),title=f.field();for(const locale of locales){f.i.setLocale(locale);assert.equal(f.field(),title);assert.equal(JSON.stringify([...f.storage]),metadata);assert.equal(f.control('save').textContent,f.i.t('sales.forecast_snapshot.recover'));}await f.submit();await f.control('cancel').fire('click');assert.equal(f.writes().length,1);assert.equal(f.box.canLeave(),false);release();await pending;assert.equal(f.storage.size,0);assert.equal(f.box.canLeave(),true);});
test('read-only forecast context and contradictory terminal identities never enable a native save',async()=>{const f=fixture({alter:d=>({...d,can_save:false})});await f.ready();assert.equal(f.notice().textContent,f.i.t('sales.forecast_snapshot.read_only'));await f.submit();assert.equal(f.writes().length,0);for(const corrupt of [d=>{d.request_context.actor_id='other';},d=>{d.request_id='another';},d=>{d.record.revision=2;d.result_revision=2;d.result_snapshot_sha256=hash(d.record);},d=>{d.state='NOT_APPLIED';},d=>{d.external_send=true;}]){const g=fixture();await g.ready();g.lose();await g.save();g.alter((d,r)=>{if(r.includes('requests'))corrupt(d);return d;});await g.submit();assert.equal(g.storage.size,1);assert.equal(g.writes().length,1);assert.equal(g.box.canLeave(),false);}});
