'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/sales-forecast-fixture');
function setup(rows){const f=fixture(),bucket=f.core.bucket(f.ctx,'opportunities');bucket.splice(0);for(const [i,row]of rows.entries())bucket.push({id:'summary-'+i,owner_id:f.actor.id,title:'Literal private summary source',revision:1,status:'OPEN',...row});return {...f,summary:(actor=f.actor)=>f.core.summary(f.ctx,actor)};}
test('Sales summary retains the exact rounded cent at the safe integer boundary',()=>{const f=setup([{value_cents:Number.MAX_SAFE_INTEGER,currency:'EUR',probability:0.6}]);assert.equal(f.summary().currency_groups.EUR.weighted_cents,5404319552844595);});
test('Sales summary keeps unknown probability separate from explicit zero and marks partial coverage',()=>{const f=setup([{value_cents:100,currency:'EUR'},{value_cents:200,currency:'USD',probability:0}]);let r=f.summary();assert.equal(r.currency_groups.EUR.weighted_cents,null);assert.equal(r.currency_groups.USD.weighted_cents,0);assert.equal(r.currency_groups.EUR.probability_missing_count,1);f.core.bucket(f.ctx,'opportunities').push({id:'known',owner_id:f.actor.id,status:'OPEN',value_cents:200,currency:'EUR',probability:0.5});r=f.summary();assert.equal(r.currency_groups.EUR.weighted_cents,100);assert.equal(r.currency_groups.EUR.weighted_total_cents,null);assert.equal(r.currency_groups.EUR.weighted_scope,'PARTIAL_KNOWN_PROBABILITIES');assert.equal(r.currency_groups.EUR.probability_coverage,0.5);});
test('Sales summary never exposes unsafe aggregate cents and preserves other currency groups',()=>{const f=setup([{value_cents:Number.MAX_SAFE_INTEGER,currency:'EUR',probability:1},{value_cents:1,currency:'EUR',probability:1},{value_cents:10,currency:'USD',probability:1}]),r=f.summary();assert.equal(r.currency_groups.EUR.open_cents,null);assert.equal(r.currency_groups.EUR.weighted_cents,null);assert.ok(r.currency_groups.EUR.overflow_fields.includes('open_known_cents'));assert.equal(r.currency_groups.USD.open_cents,10);});
test('invalid amounts do not masquerade as complete open/won totals; known subtotals and exclusions stay explicit',()=>{const f=setup([{currency:'EUR',probability:0.5},{currency:'EUR',value_cents:100,probability:0.5},{currency:'EUR',status:'WON',value_cents:-1}]),r=f.summary(),g=r.currency_groups.EUR;assert.equal(g.open_cents,null);assert.equal(g.open_known_cents,100);assert.equal(g.won_cents,null);assert.equal(g.won_known_cents,0);assert.equal(g.weighted_cents,50);assert.equal(g.weighted_total_cents,null);assert.equal(g.source_coverage,'PARTIAL_SOURCE_RECORDS');assert.equal(r.sales_summary.excluded_source_count,2);assert.equal(r.sales_summary.state,'PARTIAL');});
test('unassigned currency cannot be silently dropped or assigned to a valid currency total',()=>{const f=setup([{currency:'__proto__',value_cents:500,probability:1},{value_cents:100,probability:1},{currency:'EUR',value_cents:100,probability:1}]),r=f.summary(),g=r.currency_groups.EUR;assert.deepEqual(Object.keys(r.currency_groups),['EUR']);assert.equal(g.open_cents,null);assert.equal(g.open_known_cents,100);assert.equal(g.weighted_total_cents,null);assert.equal(g.unassigned_currency_count,2);assert.equal(r.sales_summary.excluded_source_count,2);assert.equal(Object.prototype.open_cents,undefined);});
test('lost cancelled archived deleted and unauthorized sources do not create fabricated zero groups or leak exclusions',()=>{const f=setup([{currency:'EUR',value_cents:1,probability:0.5},{currency:'USD',value_cents:999,status:'LOST'},{currency:'GBP',status:'CANCELLED'},{currency:'SEK',status:'ARCHIVED'},{currency:'DKK',deleted_at:'2026-09-01'},{owner_id:'other',currency:'NOK',value_cents:100},{owner_id:'other',currency:'bad',value_cents:-1}]),before=JSON.stringify(f.core.bucket(f.ctx,'opportunities')),r=f.summary();assert.deepEqual(Object.keys(r.currency_groups),['EUR']);assert.equal(r.currency_groups.EUR.weighted_cents,1);assert.equal(r.sales_summary.excluded_source_count,0);assert.ok(!JSON.stringify(r).includes('other'));assert.equal(JSON.stringify(f.core.bucket(f.ctx,'opportunities')),before);assert.ok(f.summary(f.admin).sales_summary.excluded_source_count>0);});
test('all authorized rows contribute beyond list pagination and no active sources differ from unavailable sources',()=>{const f=setup(Array.from({length:105},()=>({currency:'EUR',value_cents:1,probability:0.5})));assert.equal(f.summary().currency_groups.EUR.weighted_cents,105);assert.equal(f.summary().by_entity.opportunities.items.length,100);const empty=setup([]).summary();assert.deepEqual(empty.currency_groups,{});assert.equal(empty.sales_summary.state,'NO_ACTIVE_SOURCES');assert.equal(empty.sales_summary.source_record_count,0);f.resolver.configure(f.ctx,f.admin,{entitlements:['sales'],capability_flags:{'sales:opportunities':false},expected_revision:1});const r=f.summary();assert.equal(r.sales_summary.state,'SOURCE_UNAVAILABLE');assert.equal(r.sales_summary.source_record_count,null);assert.equal(r.sales_summary.excluded_sources,null);assert.deepEqual(r.currency_groups,{});});
test('invalid probabilities remain missing and tiny scientific notation probabilities round exactly',()=>{const f=setup([{currency:'EUR',value_cents:100,probability:2},{currency:'EUR',value_cents:100,probability:'0.5'},{currency:'USD',value_cents:100000000,probability:5e-9}]),r=f.summary();assert.equal(r.currency_groups.EUR.weighted_cents,null);assert.equal(r.currency_groups.EUR.probability_missing_count,2);assert.equal(r.currency_groups.USD.weighted_cents,1);assert.equal(r.currency_groups.USD.weighted_total_cents,1);assert.equal(r.currency_groups.USD.accounting_revenue,false);});
test('ZERO native Sales evidence carries exact summary semantics and re-verifies changed sources',()=>{const f=setup([{currency:'EUR',value_cents:Number.MAX_SAFE_INTEGER,probability:0.6}]),tool=require('../zero/native-agents').nativeTools({composition:()=>f.resolver,domain:()=>f.core}).find(t=>t.id==='sales_pipeline'),data=tool.read(f.ctx,f.actor);assert.equal(data.currency_groups.EUR.weighted_cents,5404319552844595);assert.equal(data.sales_summary.accounting_revenue,false);assert.equal(tool.verify(f.ctx,f.actor,data),true);delete f.core.bucket(f.ctx,'opportunities')[0].probability;assert.equal(tool.verify(f.ctx,f.actor,data),false);assert.equal(tool.read(f.ctx,f.actor).currency_groups.EUR.weighted_cents,null);});
