'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture,clone,hash}=require('../zero-evaluation/sales-forecast-fixture'),state=require('../sales-forecast-client-state'),service=require('../sales-forecast'),scenarios=require('../sales-scenarios'),hierarchies=require('../sales-hierarchy');
const scenario=(f,adjustments=[{opportunity_id:f.opportunity.id,expected_revision:1,probability_bps:0}])=>scenarios.scenarioForecast(f.core,f.ctx,f.actor,f.filters,{title:'Literal scenario',reason:'Literal rationale',adjustments}),reject=r=>assert.throws(()=>state.validate(r),{code:'forecast_observation_invalid'});
test('decimal forecast rounding uses exact recorded probabilities including scientific notation and true zero',()=>{const examples=[[0.6,5404319552844595],[0.1,900719925474099],[0.29,2612087783874887],[1e-7,900719925],[1e-20,0],[0,0],[1,9007199254740991]];for(const [probability,expected]of examples)assert.equal(state.weightedCents(Number.MAX_SAFE_INTEGER,probability),expected);assert.equal(state.weightedCents(10001,0.5),5001);assert.equal(state.weightedCents(1,0.5),1);assert.throws(()=>state.weightedCents(Number.MAX_SAFE_INTEGER+1,0.5));});
test('forecast calculation version binds confirmations while retained legacy observations remain readable',()=>{const f=fixture(),r=f.query(),old=hash({filters:r.filters,quotas:r.quotas,records:r.items.map(row=>({id:row.id,revision:row.revision,value_cents:row.value_cents,probability:row.probability,date:row.date,status:row.status})),excluded:r.excluded});assert.notEqual(r.basis_fingerprint,old);assert.throws(()=>f.apply(f.request({basis_fingerprint:old})),{code:'forecast_basis_changed'});assert.equal(f.core.bucket(f.ctx,'forecast_snapshots').length,0);const legacy=clone(r);delete legacy.calculation_version;assert.doesNotThrow(()=>state.validate(legacy));});
test('typed forecasts preserve missing probabilities true zero valid empty periods and literal category names',()=>{const f=fixture();f.core.bucket(f.ctx,'opportunities')[0].probability=undefined;let r=f.query();assert.equal(state.validate(r).groups[0].weighted_cents,null);f.core.save(f.ctx,f.actor,'opportunities',{probability:0,forecast_category:'constructor'},{id:f.opportunity.id,expected_revision:1});r=f.query();assert.equal(state.validate(r).groups[0].weighted_cents,0);assert.equal(r.groups[0].categories.constructor.count,1);r=service.forecast(f.core,f.ctx,f.actor,{from:'2026-10-01',to:'2026-10-31'});assert.equal(state.validate(r).available,false);assert.equal(r.source_record_count,1);});
test('typed quota comparisons distinguish zero targets absent source and incomplete probability coverage',()=>{for(const variant of ['zero','missing_probability','no_source','complete']){const f=fixture();f.core.save(f.ctx,f.admin,'quotas',{name:'Literal quota',owner_id:f.actor.id,currency:'EUR',period_start:f.filters.from,period_end:f.filters.to,target_cents:variant==='zero'?0:20000,status:'OPEN'});if(variant==='missing_probability')delete f.core.bucket(f.ctx,'opportunities')[0].probability;if(variant==='no_source')f.core.save(f.ctx,f.actor,'opportunities',{expected_close_date:'2026-10-01'},{id:f.opportunity.id,expected_revision:1});const r=f.query(),q=state.validate(r).quotas.items[0];if(variant==='zero')assert.equal(q.unavailable_reason,'ZERO_TARGET');if(variant==='no_source')assert.equal(q.unavailable_reason,'NO_SOURCE_RECORDS');if(variant==='missing_probability')assert.equal(q.projected_attainment_percent,null);if(variant==='complete')assert.equal(q.projected_attainment_percent,25.005);}});
test('scenario observations retain outside-period amount and date assumptions while rejecting altered source and derived totals',()=>{const f=fixture(),outside=f.core.save(f.ctx,f.actor,'opportunities',{title:'Literal outside-period source',value_cents:10000,currency:'EUR',probability:0.5,expected_close_date:'2026-10-01'}).record,r=scenario(f,[{opportunity_id:outside.id,expected_revision:1,value_cents:0,expected_close_date:'2026-09-30'}]);assert.doesNotThrow(()=>state.validate(r));assert.equal(r.scenario.items.find(x=>x.id===outside.id).scenario_weighted_cents,0);for(const corrupt of [r=>{r.scenario.groups[0].scenario_projected_cents++;},r=>{r.scenario.items.find(x=>x.id===outside.id).scenario_close_date='2026-10-01';},r=>{r.scenario.source_records[0].owner_id='other';},r=>{r.scenario.groups[0].comparison_available=false;},r=>{r.scenario.source_records_modified=true;}]){const altered=clone(r);corrupt(altered);reject(altered);}});
test('scenario observations retain genuinely unavailable comparisons and explicit out-of-period zeros',()=>{const f=fixture();delete f.core.bucket(f.ctx,'opportunities')[0].probability;let r=scenario(f,[{opportunity_id:f.opportunity.id,expected_revision:1,value_cents:20000}]);assert.equal(state.validate(r).scenario.groups[0].scenario_projected_cents,null);r=scenario(f,[{opportunity_id:f.opportunity.id,expected_revision:1,expected_close_date:'2026-10-01'}]);assert.equal(state.validate(r).scenario.items[0].scenario_weighted_cents,0);assert.equal(r.scenario.groups[0].baseline_projected_cents,null);assert.equal(r.scenario.groups[0].scenario_projected_cents,0);});
test('hierarchy observations must match the requested node scope and cannot claim a verified organization total',()=>{const f=fixture(),record=hierarchies.save(f.core,f.ctx,f.admin,'forecast_hierarchy',{expected_revision:0,confirm:true,definition:{key:'team',title:'Literal hierarchy',version:1,reader_ids:[f.actor.id],nodes:[{id:'root',label:'Literal root',parent_id:null,owner_ids:[f.actor.id]}]}}).record,r=hierarchies.query(f.core,f.ctx,f.actor,record.id,{node_id:'root',filters:f.filters});assert.doesNotThrow(()=>state.validate(r,{filters:f.filters,hierarchy:{id:record.id,node_id:'root'}}));assert.throws(()=>state.validate(r,{hierarchy:{id:record.id,node_id:'other'}}),{code:'forecast_observation_invalid'});r.hierarchy.organization_total_verified=true;reject(r);});
test('malformed forecast identities source counts dates categories and candidate bounds cannot become valid empty success',()=>{const f=fixture(),r=f.query();for(const corrupt of [r=>{r.items[0].date='2026-02-30';},r=>{r.items.push(clone(r.items[0]));},r=>{r.source_record_count=0;},r=>{r.groups[0].categories.UNCATEGORIZED.value_cents++;},r=>{r.scenario_candidate_total++;},r=>{r.scenario_candidates[0].currency='EU';},r=>{r.provider_verified=true;},r=>{r.calculation_version=999;}]){const altered=clone(r);corrupt(altered);reject(altered);}});

test('current forecasts require the calculation version and authenticated context while retained legacy records stay distinguishable',()=>{const f=fixture(),r=f.query();for(const key of ['calculation_version','request_context','can_save']){const changed=clone(r);delete changed[key];assert.throws(()=>state.validate(changed,{filters:f.filters}),{code:'forecast_observation_invalid'});}});
