'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture'),{fixture:editorFixture}=require('../zero-evaluation/workflow-editor-fixture');
const hash=input=>crypto.createHash('sha256').update(JSON.stringify(input)).digest('hex'),input=(name,revision,key)=>({draft:{name,steps:[]},expected_revision:revision,request_id:key}),review=body=>({request_id:body.request_id,expected_revision:body.expected_revision,request_fingerprint:hash(body),confirm:true});
test('a fresh actual editor recovers a genuinely lost keyed update after encrypted server restart without replaying private input or leaking the receipt to Data',async()=>{
 const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-native-draft-ack-drop')});try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const realm=(await f.request('/api/automation/drafts')).body.request_context,spec=(await f.request('/api/automation/workflows')).body.editor_contract;let drop=true;
  const invalid=await f.request('/api/automation/drafts/rejected_editor','PUT',{draft:{name:'Rejected private condition',steps:[{type:'create_task',condition:{enabled:false,value:'x'.repeat(12001)}}]},expected_revision:0,request_id:'invalid_write_key'});assert.equal(invalid.status,422);assert.equal(invalid.body.code,'workflow_draft_invalid');
  const requestOverride=async(route,options)=>{const body=JSON.parse(options.body);let headers={};if(drop&&options.method==='PUT'&&body.expected_revision===1){drop=false;headers={'x-native-draft-drop-reply':'isolated-http-fixture'};}const result=await f.request(route,options.method,body,null,headers);if(result.status!==200)throw Object.assign(Error('Native request rejected'),{status:result.status,code:result.body.code});return result.body;};
  const first=editorFixture({requestContext:realm,editorSpec:spec,requestOverride});first.valid();await first.button('Concept nu bewaren').fire('click');first.field('Workflownaam').value='Private HTTP edit recovered after reload';await first.box.fire('input');await first.button('Concept nu bewaren').fire('click');assert.equal(first.storage.size,1);const original=JSON.parse(first.calls.at(-1).options.body),metadata=[...first.storage.values()].join('');assert.ok(!metadata.includes(original.draft.name));first.retire();await f.stop();await f.start();const fresh=editorFixture({requestContext:realm,editorSpec:spec,requestOverride,storage:first.storage});await fresh.recover().fire('click');assert.equal(fresh.calls.length,1);assert.equal(fresh.calls[0].operation,'RECOVER');assert.equal(fresh.recovered[0].revision,2);assert.equal(fresh.recovered[0].draft.name,original.draft.name);assert.equal(first.storage.size,0);assert.equal((await f.request('/api/automation/drafts')).body.items.length,1);assert.equal((await f.request('/api/automation/status')).body.workflow_count,0);assert.equal((await f.request('/api/automation/tasks')).body.total,0);const generic=await f.request('/api/module/data/data');assert.equal(generic.status,200);assert.ok(!JSON.stringify(generic.body).includes(original.request_id));const disk=fs.readFileSync(path.join(f.dir,'foundly-core-state.json'),'utf8');assert.ok(!disk.includes(original.request_id));assert.ok(!disk.includes(original.draft.name));
 }finally{await f.close();}
});
test('failed terminal persistence leaves the original update usable and a durable later closure blocks an actual incomplete PUT body through restart',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'editor-write-terminal-')),marker=path.join(dir,'fail'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/identity-persistence-fault'),FOUNDLY_IDENTITY_FAIL_FILE:marker});let held;try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const route='/api/automation/drafts/terminal_editor',recover=route+'/writes/recover';assert.equal((await f.request(route,'PUT',{draft:{name:'Initial private draft'},expected_revision:0})).status,200);const first=input('Update after rolled-back closure',1,'failed_close_key');fs.writeFileSync(marker,'fail');try{assert.equal((await f.request(recover,'POST',review(first))).status,500);}finally{fs.rmSync(marker,{force:true});}assert.equal((await f.request(route,'PUT',first)).body.record.revision,2);
  const second=input('Must not apply after closure',2,'closed_update_key'),payload=JSON.stringify(second),pending=new Promise((resolve,reject)=>{held=require('node:http').request(f.base+route,{method:'PUT',headers:{authorization:'Bearer '+f.env.FOUNDLY_ADMIN_TOKEN,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload)}},res=>{let text='';res.on('data',part=>text+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}));});held.on('error',reject);held.flushHeaders();held.write(payload.slice(0,-1));});
  const closed=await f.request(recover,'POST',review(second));assert.equal(closed.status,200,JSON.stringify(closed.body));assert.equal(closed.body.state,'NOT_APPLIED');held.end(payload.slice(-1));const late=await pending;assert.equal(late.status,409,JSON.stringify(late.body));assert.equal(late.body.code,'workflow_draft_write_abandoned');await f.stop();await f.start();assert.deepEqual((await f.request(recover,'POST',review(second))).body,closed.body);assert.equal((await f.request(route,'PUT',second)).status,409);const rows=(await f.request('/api/automation/drafts')).body.items;assert.equal(rows.length,1);assert.equal(rows[0].revision,2);assert.equal(rows[0].draft.name,first.draft.name);
 }finally{held?.destroy();fs.rmSync(marker,{force:true});await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('write recovery checks the current member after its authenticated body wait and rejects another owner without private content',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'editor-write-authority-')),marker=path.join(dir,'body'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../test-identity-body-barrier'),FOUNDLY_IDENTITY_BODY_BARRIER:marker});let held;try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('editor.write.owner',['ADMIN']),other=await f.enroll('editor.write.other',['ADMIN']),route='/api/automation/drafts/owned_editor',body=input('Private keyed member draft',0,'member_write_key');assert.equal((await f.request(route,'PUT',body,owner.cookie)).status,200);assert.equal((await f.request(route+'/writes/recover','POST',review(body),other.cookie)).status,404);const payload=JSON.stringify(review(body));
  const pending=new Promise((resolve,reject)=>{held=require('node:http').request(f.base+route+'/writes/recover',{method:'POST',headers:{cookie:owner.cookie,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload),'x-identity-fixture-barrier':'body'}},res=>{let text='';res.on('data',part=>text+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}));});held.on('error',reject);held.write(payload.slice(0,-1));});
  for(let n=0;n<100&&!fs.existsSync(marker);n++)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(marker));assert.equal((await f.request('/api/identity/users/'+owner.member.id,'PUT',{roles:['VIEWER'],expected_revision:owner.member.revision,confirm:true,reason:'Revoke access while keyed recovery awaits body'})).status,200);held.end(payload.slice(-1));const denied=await pending;assert.equal(denied.status,401);assert.ok(!JSON.stringify(denied.body).includes(body.draft.name));owner.cookie=await f.login(owner);assert.equal((await f.request(route+'/writes/recover','POST',review(body),owner.cookie)).status,403);
 }finally{held?.destroy();await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
