'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{fixture}=require('../zero-evaluation/workflow-editor-fixture'),{locales}=require('../foundly-i18n');
const nativeRequest=f=>async(route,options)=>{const body=JSON.parse(options.body);return route==='/api/automation/publications/recover'?f.core.recoverAutomationPublication(f.ctx,f.actor,body):route==='/api/automation/workflows'?f.core.defineAutomation(f.ctx,f.actor,body):f.drafts.save(f.ctx,f.actor,route.split('/').at(-1),body);};
const recover=f=>f.box.all().find(n=>n.getAttribute?.('data-workflow-publication-recovery')==='recover');
async function lost(applied=true){let f;f=fixture({requestOverride:applied?null:async(route,options)=>{if(route==='/api/automation/workflows')throw Error('Fixture loss before publication');return nativeRequest(f)(route,options);}});f.valid();if(applied)f.lose('PUBLISH');await f.box.fire('submit');assert.equal(f.saved.length,0);return f;}
test('fresh editor publication recovery uses scoped source-free metadata and no original definition replay or execution',async()=>{
 const f=await lost(),original=f.calls.at(-1),body=JSON.parse(original.options.body);assert.equal(typeof body.request_id,'string');assert.equal(f.storage.size,1);const metadata=[...f.storage.values()].join('');assert.ok(!metadata.includes(body.name));assert.ok(!metadata.includes(body.actions[0].title));assert.deepEqual(Object.keys(JSON.parse(metadata)[0]).sort(),['definition_fingerprint','request_fingerprint','request_id']);f.retire();const g=fixture({storage:f.storage,requestOverride:nativeRequest(f)}),before=f.counts();assert.ok(recover(g));await recover(g).fire('click');assert.equal(g.calls.length,1);assert.equal(g.calls[0].route,'/api/automation/publications/recover');assert.equal(g.saved.length,1);assert.equal(g.recovered.length,0);assert.equal(f.storage.size,0);assert.deepEqual(f.counts(),before);assert.equal(f.core.bucket(f.ctx,'automations').length,1);
});
test('fresh publication recovery closes an absent request and refuses its delayed body while preserving an independent explicit publication',async()=>{
 const f=await lost(false),body=JSON.parse(f.calls.at(-1).options.body),g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});assert.ok(recover(g));await recover(g).fire('click');assert.equal(g.saved.length,0);assert.equal(f.storage.size,0);assert.equal(f.core.bucket(f.ctx,'automations').length,0);assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,body),{code:'automation_publication_abandoned'});const calls=g.calls.length;for(const locale of locales){g.i.setLocale(locale);assert.ok(g.box.textContent.includes(g.i.t('workflow.editor.publication_not_applied')));assert.equal(g.i.missingKeys().length,0);}assert.equal(g.calls.length,calls);g.valid();await g.box.fire('submit');assert.equal(g.saved.length,1);assert.equal(f.core.bucket(f.ctx,'automations').length,1);assert.notEqual(JSON.parse(g.calls.at(-1).options.body).request_id,body.request_id);
});
test('malformed publication metadata and unavailable storage prevent new native effects without discarding current form values',async()=>{
 const f=await lost(),key=[...f.storage.keys()][0];assert.ok(key?.includes('publications'));f.storage.set(key,'[{"request_id":"broken"}]');const g=fixture({storage:f.storage});g.valid();await g.box.fire('submit');assert.equal(g.calls.length,0);assert.equal(g.notice().textContent,g.i.t('workflow.generator.storage_required'));assert.equal(g.field('Workflownaam').value,'Literal <img> editor');const h=fixture();h.valid();await h.button('Concept nu bewaren').fire('click');h.failStorage();await h.box.fire('submit');assert.equal(h.calls.filter(c=>c.operation==='PUBLISH').length,0);assert.equal(h.core.bucket(h.ctx,'automations').length,0);
});
test('forged publication recovery envelopes or immutable content preserve metadata and cannot confirm a workflow',async()=>{
 for(const change of [r=>r.request_id='other',r=>r.request_context.actor_id='other',r=>r.request_fingerprint='a'.repeat(64),r=>r.definition_fingerprint='a'.repeat(64),r=>r.record.signature='a'.repeat(64),r=>{r.record.actions[0].title='Other valid content';r.record.signature=crypto.createHash('sha256').update(JSON.stringify({name:r.record.name,version:r.record.version,trigger:r.record.trigger,actions:r.record.actions,enabled:r.record.enabled,approval_required:r.record.approval_required})).digest('hex');}]){const f=await lost(),g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});assert.ok(recover(g));g.alter((r,op)=>{if(op==='PUBLICATION_RECOVER')change(r);return r;});await recover(g).fire('click');assert.equal(g.saved.length,0);assert.equal(f.storage.size,1);assert.equal(recover(g).disabled,false);}
});
test('current denial, scoped actor separation and retired late publication recovery never release saved callbacks or erase evidence',async()=>{
 const f=await lost(),g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});assert.ok(recover(g));g.deny(403);await recover(g).fire('click');for(const locale of locales){g.i.setLocale(locale);assert.ok(g.box.textContent.includes(g.i.t('common.access_denied')));assert.ok(!g.box.textContent.includes('RAW_PRIVATE_DENIAL'));}assert.equal(f.storage.size,1);assert.equal(g.saved.length,0);const foreign=fixture({storage:f.storage,requestContext:{...f.ctx,actor_id:'other_actor'}});assert.equal(recover(foreign),undefined);const h=fixture({storage:f.storage,requestOverride:nativeRequest(f)}),release=h.hold('PUBLICATION_RECOVER'),pending=recover(h).fire('click');await release.started;h.retire();release();await pending;assert.equal(h.saved.length,0);assert.equal(f.storage.size,1);
});
test('known publication and absent-request recovery remain distinct when metadata cleanup fails',async()=>{
 for(const applied of [true,false]){const f=await lost(applied),g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});assert.ok(recover(g));const release=g.hold('PUBLICATION_RECOVER'),pending=recover(g).fire('click');await release.started;g.failStorage();release();await pending;assert.equal(g.saved.length,applied?1:0);assert.equal(f.storage.size,1);assert.equal(recover(g).disabled,true);for(const locale of locales){g.i.setLocale(locale);assert.equal(g.box.all().filter(n=>n.tag==='output').at(-1).textContent,g.i.t('workflow.editor.publication_recovery_metadata'));}}
});
test('publication acknowledgement binds the exact request key and request hash before clearing recovery metadata',async()=>{
 for(const change of [r=>r.request_id='wrong_request',r=>r.request_fingerprint='a'.repeat(64),r=>r.request_context.actor_id='other_actor']){const f=fixture();f.valid();f.alter((r,op)=>{if(op==='PUBLISH')change(r);return r;});await f.box.fire('submit');assert.equal(f.saved.length,0);assert.equal(f.storage.size,1);assert.equal(f.notice().textContent,f.i.t('workflow.editor.unconfirmed'));f.alter(null);await f.box.fire('submit');assert.equal(f.saved.length,1);assert.equal(f.storage.size,0);assert.equal(f.core.bucket(f.ctx,'automations').length,1);}
});
test('definitive version conflict clears only its pending publication so the corrected independent version can be saved',async()=>{
 const f=fixture();f.valid();await f.box.fire('submit');assert.equal(f.saved.length,1);f.field('Taaktitel').value='Changed action for a new version';await f.box.fire('input');await f.box.fire('submit');assert.equal(f.saved.length,1);assert.equal(f.storage.size,0);assert.equal(f.notice().textContent,f.i.t('workflow.editor.conflict'));f.field('Versie').value='2';await f.box.fire('input');await f.box.fire('submit');assert.equal(f.saved.length,2);assert.equal(f.storage.size,0);assert.equal(f.core.bucket(f.ctx,'automations').length,2);
});
test('recovering an earlier publication cannot refresh away unsaved input typed before or during recovery',async()=>{
 for(const during of [false,true]){const f=await lost(),g=fixture({storage:f.storage,requestOverride:nativeRequest(f)}),name=g.field('Workflownaam');let pending,release;if(during){release=g.hold('PUBLICATION_RECOVER');pending=recover(g).fire('click');await release.started;}name.value='New private input must remain';await g.box.fire('input');if(during){release();await pending;}else await recover(g).fire('click');assert.equal(g.saved.length,0);assert.equal(name.value,'New private input must remain');assert.equal(g.box.dataset.unsaved,'true');assert.equal(f.storage.size,0);assert.ok(g.box.textContent.includes(g.i.t('workflow.editor.publication_recovered')));assert.equal(recover(g).disabled,true);}
});
test('a missing previously confirmed publication remains unavailable and does not block independent new drafts',async()=>{
 const f=await lost();f.core.bucket(f.ctx,'automations').length=0;const g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});await recover(g).fire('click');assert.equal(g.saved.length,0);assert.equal(f.storage.size,0);assert.ok(g.box.textContent.includes(g.i.t('workflow.editor.publication_unavailable')));g.valid();await g.button('Concept nu bewaren').fire('click');assert.equal(g.records().length,0);assert.equal(f.records().length,2);assert.equal(f.core.bucket(f.ctx,'automations').length,0);
});
