'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{FoundlyPlatformCore}=require('../platform-core');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex'),definition=()=>({name:'Private literal workflow',version:1,trigger:{type:'custom_event',automatic:false},actions:[{type:'create_document',title:'Literal title',content:'Private first line\nPrivate second line'}],approval_required:false}),input=(key='publish_1')=>({...definition(),request_id:key}),signature=body=>hash({name:body.name,version:body.version,trigger:body.trigger,actions:body.actions,enabled:body.enabled!==false,approval_required:body.approval_required===true}),review=body=>({request_id:body.request_id,request_fingerprint:hash(body),definition_fingerprint:signature(body),confirm:true});
function fixture(){let rows=new Map(),fail=false,writes=0;const ctx={tenant_id:'publication-recovery-fixture',dealer_id:'default'},actor={id:'publication-owner',roles:['ADMIN','SUPER_ADMIN']},adapter={bucket(c,s){const key=JSON.stringify([c,s]);if(!rows.has(key))rows.set(key,[]);return rows.get(key);},persist(){if(fail)throw Object.assign(Error('Isolated publication persistence failure'),{code:'EIO'});writes++;}};let core=new FoundlyPlatformCore(adapter);return {ctx,actor,get core(){return core;},restart(){rows=new Map(JSON.parse(JSON.stringify([...rows])));core=new FoundlyPlatformCore(adapter);},fail:value=>fail=value,writes:()=>writes,receipts:()=>core.bucket(ctx,'automation_publication_requests')};}
test('keyed publication recovery binds the exact immutable version and scoped metadata through native reconstruction without replay or execution',()=>{
 const f=fixture(),body=input(),saved=f.core.defineAutomation(f.ctx,f.actor,body);assert.equal(saved.request_id,body.request_id);assert.equal(saved.request_fingerprint,hash(body));assert.deepEqual(saved.request_context,{...f.ctx,actor_id:f.actor.id});const before=f.writes();f.restart();const recovered=f.core.recoverAutomationPublication(f.ctx,f.actor,review(body));assert.equal(recovered.state,'APPLIED');assert.equal(recovered.record.id,saved.id);assert.equal(recovered.record.signature,signature(body));assert.deepEqual(recovered.request_context,saved.request_context);assert.equal(recovered.record.actions[0].content,body.actions[0].content);assert.equal(f.writes(),before);assert.equal(f.core.defineAutomation(f.ctx,f.actor,body).idempotent,true);assert.equal(f.writes(),before);assert.equal(f.core.bucket(f.ctx,'automation_runs').length,0);assert.equal(f.receipts().length,1);assert.ok(!JSON.stringify(f.receipts()).includes(body.name));assert.ok(!JSON.stringify(f.receipts()).includes(body.actions[0].content));
});
test('a durable absent publication closes only that request key and rejects its original delayed definition',()=>{
 const f=fixture(),body=input(),closed=f.core.recoverAutomationPublication(f.ctx,f.actor,review(body));assert.equal(closed.state,'NOT_APPLIED');assert.equal(closed.record,null);f.restart();assert.deepEqual(f.core.recoverAutomationPublication(f.ctx,f.actor,review(body)),closed);assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,body),{code:'automation_publication_abandoned'});assert.equal(f.core.bucket(f.ctx,'automations').length,0);const separate=f.core.defineAutomation(f.ctx,f.actor,input('publish_2'));assert.equal(separate.signature,signature(body));assert.equal(f.core.bucket(f.ctx,'automations').length,1);assert.equal(f.core.recoverAutomationPublication(f.ctx,f.actor,review(body)).state,'NOT_APPLIED');
});
test('definition, audit, queued owned event and publication receipt roll back together, including absent closure and existing-version confirmation',()=>{
 const f=fixture(),body=input();for(const scope of ['automations','audit','module_event_outbox','automation_publication_requests'])f.core.bucket(f.ctx,scope);f.fail(true);assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,body),{code:'EIO'});for(const scope of ['automations','audit','module_event_outbox','automation_publication_requests'])assert.equal(f.core.bucket(f.ctx,scope).length,0,scope);assert.throws(()=>f.core.recoverAutomationPublication(f.ctx,f.actor,review(body)),{code:'EIO'});assert.equal(f.receipts().length,0);f.fail(false);f.core.defineAutomation(f.ctx,f.actor,definition());const audit=f.core.bucket(f.ctx,'audit').length;f.fail(true);assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,body),{code:'EIO'});assert.equal(f.receipts().length,0);assert.equal(f.core.bucket(f.ctx,'audit').length,audit);f.fail(false);assert.equal(f.core.defineAutomation(f.ctx,f.actor,body).idempotent,true);assert.equal(f.core.recoverAutomationPublication(f.ctx,f.actor,review(body)).state,'APPLIED');
});
test('publication recovery checks current authority, actor and realm before releasing receipt evidence',()=>{
 const f=fixture(),body=input();f.core.defineAutomation(f.ctx,f.actor,body);assert.throws(()=>f.core.recoverAutomationPublication(f.ctx,{id:f.actor.id,roles:['VIEWER']},review(body)),{statusCode:403});const other=f.core.recoverAutomationPublication(f.ctx,{...f.actor,id:'other-owner'},review(body));assert.equal(other.state,'NOT_APPLIED');assert.equal(other.record,null);const foreign=f.core.recoverAutomationPublication({...f.ctx,tenant_id:'other-tenant'},f.actor,review(body));assert.equal(foreign.state,'NOT_APPLIED');assert.equal(foreign.record,null);assert.equal(f.core.recoverAutomationPublication(f.ctx,f.actor,review(body)).state,'APPLIED');
});
test('changed request identity and definition hashes cannot claim or close another publication',()=>{
 const f=fixture(),body=input();f.core.defineAutomation(f.ctx,f.actor,body);for(const altered of [{...review(body),request_fingerprint:'a'.repeat(64)},{...review(body),definition_fingerprint:'b'.repeat(64)}])assert.throws(()=>f.core.recoverAutomationPublication(f.ctx,f.actor,altered),{code:'automation_publication_conflict'});assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,{...body,version:2}),{code:'automation_publication_conflict'});assert.equal(f.core.bucket(f.ctx,'automations').length,1);for(const change of [r=>r.confirm='true',r=>r.request_id='',r=>r.definition_fingerprint='bad',r=>r.request_fingerprint='bad',r=>r.name='Private extra input']){const value=review(input('new_key'));change(value);assert.throws(()=>f.core.recoverAutomationPublication(f.ctx,f.actor,value),{code:'automation_publication_recovery_invalid'});}assert.equal(f.receipts().length,1);
});
test('missing or altered immutable result is not released or recreated by its retained publication key',()=>{
 const f=fixture(),body=input();f.core.defineAutomation(f.ctx,f.actor,body);const rows=f.core.bucket(f.ctx,'automations'),original=JSON.parse(JSON.stringify(rows[0]));rows[0].actions[0].title='Altered retained title';assert.throws(()=>f.core.recoverAutomationPublication(f.ctx,f.actor,review(body)),{code:'automation_publication_unverifiable'});assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,body),{code:'automation_publication_unverifiable'});rows[0]=original;rows.length=0;const before=f.writes();assert.throws(()=>f.core.recoverAutomationPublication(f.ctx,f.actor,review(body)),{code:'automation_publication_unavailable'});assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,body),{code:'automation_publication_unavailable'});assert.equal(f.writes(),before);
});
test('legacy immutable publication remains compatible without fabricating request attribution',()=>{
 const f=fixture(),bare=definition(),saved=f.core.defineAutomation(f.ctx,f.actor,bare);assert.equal(f.core.defineAutomation(f.ctx,f.actor,bare).idempotent,true);assert.equal(f.receipts().length,0);const unknown=input('legacy_unknown'),closed=f.core.recoverAutomationPublication(f.ctx,f.actor,review(unknown));assert.equal(closed.state,'NOT_APPLIED');assert.equal(closed.record,null);assert.equal(f.core.bucket(f.ctx,'automations')[0].id,saved.id);assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,unknown),{code:'automation_publication_abandoned'});assert.equal(f.core.defineAutomation(f.ctx,f.actor,input('new_confirmation')).idempotent,true);for(const key of ['',null,5,'x'.repeat(101),'bad/key'])assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,{...bare,request_id:key}),{code:'automation_publication_request_invalid'});
});
test('publication receipt capacity retains earlier evidence and blocks both new definitions and new confirmations',()=>{
 const f=fixture(),body=input();f.core.defineAutomation(f.ctx,f.actor,body);const receipts=f.receipts();for(let n=receipts.length;n<10000;n++)receipts.push({actor_id:'other',request_id:'other_'+n});const before=f.writes();assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,{...input('new_version'),version:2}),{code:'automation_publication_capacity'});assert.throws(()=>f.core.defineAutomation(f.ctx,f.actor,input('new_confirmation')),{code:'automation_publication_capacity'});assert.throws(()=>f.core.recoverAutomationPublication(f.ctx,f.actor,review(input('close_new'))),{code:'automation_publication_capacity'});assert.equal(f.core.defineAutomation(f.ctx,f.actor,body).idempotent,true);assert.equal(f.core.recoverAutomationPublication(f.ctx,f.actor,review(body)).state,'APPLIED');assert.equal(f.writes(),before);assert.equal(receipts.length,10000);
});
