'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),{fixture}=require('../zero-evaluation/fixture'),{fixture:editorFixture}=require('../zero-evaluation/workflow-editor-fixture');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex'),input=(version,key)=>({name:'Private HTTP publication',version,trigger:{type:'custom_event',automatic:false},actions:[{type:'create_document',title:'Private literal document',content:'Line one\nLine two'}],approval_required:false,request_id:key}),review=body=>({request_id:body.request_id,request_fingerprint:hash(body),definition_fingerprint:hash({name:body.name,version:body.version,trigger:body.trigger,actions:body.actions,enabled:true,approval_required:body.approval_required}),confirm:true}),recover=f=>f.box.all().find(n=>n.getAttribute?.('data-workflow-publication-recovery')==='recover'),route='/api/automation/publications/recover';
test('actual editor publication with a lost committed HTTP response is recovered in a fresh VM after encrypted restart without replay or private browser storage',async()=>{
 const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-publication-ack-drop')});try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const realm=(await f.request('/api/automation/drafts')).body.request_context,spec=(await f.request('/api/automation/workflows')).body.editor_contract;let drop=true;
  const requestOverride=async(url,options)=>{let headers={};if(drop&&url==='/api/automation/workflows'){drop=false;headers={'x-workflow-publish-drop-reply':'isolated-http-fixture'};}const result=await f.request(url,options.method,JSON.parse(options.body),null,headers);if(![200,201].includes(result.status))throw Object.assign(Error('Publication HTTP rejected'),{status:result.status,code:result.body.code});return result.body;};
  const first=editorFixture({requestContext:realm,editorSpec:spec,requestOverride,withZero:false});first.valid();await first.box.fire('submit');assert.equal(first.saved.length,0);assert.equal(first.storage.size,1);const original=JSON.parse(first.calls.at(-1).options.body);assert.ok(![...first.storage.values()].join('').includes(original.name));first.retire();await f.stop();await f.start();const fresh=editorFixture({requestContext:realm,editorSpec:spec,requestOverride,storage:first.storage,withZero:false});await recover(fresh).fire('click');assert.equal(fresh.saved.length,1);assert.equal(fresh.calls.length,1);assert.equal(fresh.calls[0].route,route);assert.equal(first.storage.size,0);assert.equal((await f.request('/api/automation/workflows')).body.workflow_count,1);assert.equal((await f.request('/api/automation/tasks')).body.total,0);assert.equal((await f.request('/api/automation/documents')).body.total,0);const data=await f.request('/api/module/data/data');assert.equal(data.status,200);assert.ok(!JSON.stringify(data.body).includes(original.request_id));const disk=fs.readFileSync(path.join(f.dir,'foundly-core-state.json'),'utf8');assert.ok(!disk.includes(original.name));assert.ok(!disk.includes(original.request_id));
 }finally{await f.close();}
});
test('publication terminal persistence rolls back on EIO and a durable closure rejects an actual delayed POST body through encrypted restart',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'publication-terminal-')),marker=path.join(dir,'fail'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/identity-persistence-fault'),FOUNDLY_IDENTITY_FAIL_FILE:marker});let held;try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const first=input(1,'publication_eio');fs.writeFileSync(marker,'fail');try{assert.equal((await f.request(route,'POST',review(first))).status,500);}finally{fs.rmSync(marker,{force:true});}assert.equal((await f.request('/api/automation/workflows','POST',first)).status,201);const second=input(2,'publication_held'),payload=JSON.stringify(second);
  const pending=new Promise((resolve,reject)=>{held=http.request(f.base+'/api/automation/workflows',{method:'POST',headers:{authorization:'Bearer '+f.env.FOUNDLY_ADMIN_TOKEN,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload)}},res=>{let body='';res.on('data',part=>body+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(body)}));});held.on('error',reject);held.flushHeaders();held.write(payload.slice(0,-1));});
  const closed=await f.request(route,'POST',review(second));assert.equal(closed.status,200,JSON.stringify(closed.body));assert.equal(closed.body.state,'NOT_APPLIED');held.end(payload.slice(-1));const late=await pending;assert.equal(late.status,409);assert.equal(late.body.code,'automation_publication_abandoned');await f.stop();await f.start();assert.deepEqual((await f.request(route,'POST',review(second))).body,closed.body);assert.equal((await f.request('/api/automation/workflows','POST',second)).status,409);const versions=(await f.request('/api/automation/workflows')).body;assert.equal(versions.workflow_count,1);assert.equal(versions.workflows[0].version,1);assert.equal((await f.request('/api/automation/documents')).body.total,0);const data=await f.request('/api/module/data/data');assert.equal(data.status,200);assert.ok(!JSON.stringify(data.body).includes(second.request_id));
 }finally{held?.destroy();fs.rmSync(marker,{force:true});await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('publication recovery requires current workflow capability and current member authority after a body wait, with actor-isolated receipts',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'publication-access-')),marker=path.join(dir,'body'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../test-identity-body-barrier'),FOUNDLY_IDENTITY_BODY_BARRIER:marker});let held;try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('publication.owner',['ADMIN']),other=await f.enroll('publication.other',['ADMIN']),body=input(1,'owned_publication');assert.equal((await f.request('/api/automation/workflows','POST',body,owner.cookie)).status,201);const foreign=await f.request(route,'POST',review(body),other.cookie);assert.equal(foreign.status,200);assert.equal(foreign.body.state,'NOT_APPLIED');assert.equal(foreign.body.record,null);assert.ok(!JSON.stringify(foreign.body).includes(body.name));
  async function delayed(change){fs.rmSync(marker,{force:true});const payload=JSON.stringify(review(body)),pending=new Promise((resolve,reject)=>{held=http.request(f.base+route,{method:'POST',headers:{cookie:owner.cookie,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload),'x-identity-fixture-barrier':'body'}},res=>{let data='';res.on('data',part=>data+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(data)}));});held.on('error',reject);held.write(payload.slice(0,-1));});for(let n=0;n<100&&!fs.existsSync(marker);n++)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(marker));await change();held.end(payload.slice(-1));return pending;}
  const disabled=await delayed(async()=>{assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],capability_flags:{'automation:workflows':false},expected_revision:1})).status,200);});assert.equal(disabled.status,403);assert.ok(!JSON.stringify(disabled.body).includes(body.name));assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],capability_flags:{'automation:workflows':true},expected_revision:2})).status,200);
  const revoked=await delayed(async()=>{assert.equal((await f.request('/api/identity/users/'+owner.member.id,'PUT',{roles:['VIEWER'],expected_revision:owner.member.revision,confirm:true,reason:'Revoke publication authority while recovery body waits'})).status,200);});assert.equal(revoked.status,401);assert.ok(!JSON.stringify(revoked.body).includes(body.name));owner.cookie=await f.login(owner);assert.equal((await f.request(route,'POST',review(body),owner.cookie)).status,403);assert.equal((await f.request('/api/automation/workflows')).body.workflow_count,1);
 }finally{held?.destroy();await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
