'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workspace-identity-fixture'),{locales}=require('../foundly-i18n');
test('identity owned labels follow all eight locales while literal names, canonical grants and draft controls stay intact',async()=>{
 const f=await fixture();f.fill();const form=f.form(),inputs=form.querySelectorAll('input'),values=inputs.map(n=>[n.value,n.checked]),requests=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.ok(f.form()===form);assert.deepEqual(inputs.map(n=>[n.value,n.checked]),values);assert.equal(form.querySelector('button').textContent,f.i.t('workspace.page.identity_invite'));assert.ok(form.textContent.includes(f.i.t('workspace.page.identity_role.viewer')));assert.equal(f.calls.length,requests);assert.equal(f.i.missingKeys().length,0);}
});
test('an identity session or list arriving after navigation cannot repaint a retired view',async()=>{
 for(const route of ['/api/identity/session','/api/identity/users']){const f=await fixture({start:false}),release=f.hold(route),read=f.render();await release.started;f.ui.state.activeSection='OTHER';f.content.textContent='Current different section';release();await read;assert.equal(f.content.textContent,'Current different section');}
 const f=await fixture({start:false}),release=f.hold('/api/identity/session'),old=f.render();await release.started;f.overrides.set('GET /api/identity/session',{...f.session(),principal:{...f.actor,id:'new_current_actor'}});await f.render();release();await old;assert.ok(f.content.textContent.includes('new_current_actor'));assert.ok(!f.content.textContent.includes('identity_fixture_admin'));
});
test('unknown invitation acknowledgement keeps a frozen key and body, suppresses duplicates and never creates a second user',async()=>{
 const f=await fixture();f.fill();const form=f.form(),release=f.hold('/api/identity/users','POST');f.lose();const write=form.fire('submit');await release.started;await form.fire('submit');assert.equal(f.writes().length,1);release();await write;assert.equal(f.identities.list(f.ctx,f.actor).items.length,1);assert.equal(form.querySelector('output').textContent,f.i.t('workspace.page.identity_unconfirmed'));
 const body=f.writes()[0].input,key=f.writes()[0].key;assert.match(key,/^[A-Za-z0-9_.:-]{8,160}$/);f.field('username').value='must.not.replace';for(const locale of locales)f.i.setLocale(locale);await form.fire('submit');assert.equal(f.writes().length,2);assert.equal(f.writes()[1].key,key);assert.deepEqual(f.writes()[1].input,body);assert.equal(f.identities.list(f.ctx,f.actor).items.length,1);assert.equal(f.content.querySelector('textarea').value,f.session().public_origin+'/login#invite='+f.identities.request(f.ctx,f.actor,key).invite_token);assert.equal(form.querySelector('button').disabled,true);
});
test('request receipt survives a new controller without storing names or invite secrets and recovery does not repeat a write',async()=>{
 const f=await fixture();f.fill();f.lose();await f.form().fire('submit');assert.equal(f.saved.size,1);const saved=[...f.saved.values()].join('');assert.ok(!saved.includes('literal.person'));assert.ok(!saved.includes('Literal private person'));assert.ok(!saved.includes('Reviewed identity access'));assert.ok(!saved.includes('invite_token'));
 const retained=new Map(f.saved),g=await fixture({shared:f,storage:f.saved});assert.ok(g.action('recover'));await g.action('recover').fire('click');assert.equal(g.writes().filter(row=>row.route==='/api/identity/users').length,0);assert.ok(g.content.querySelector('textarea'));assert.equal(g.saved.size,0);
 const h=await fixture({start:false,shared:f,storage:retained});h.actor.id='other_actor';await h.render();assert.equal(h.action('recover'),undefined);assert.equal(h.saved.size,1);
});
test('malformed mutation replies do not reset drafts or expose a false invitation',async()=>{
 for(const reply of [{ok:true},{ok:false,member:{}},{ok:true,operation:'INVITE',request_id:'wrong-request',invite_token:'a'.repeat(64),enrollment_url:'https://untrusted.test/login'}]){const f=await fixture();f.fill();f.overrides.set('POST /api/identity/users',reply);await f.form().fire('submit');assert.equal(f.field('username').value,'literal.person');assert.ok(f.content.querySelector('textarea')===null,'No invitation may be exposed');assert.equal(f.form().querySelector('output').textContent,f.i.t('workspace.page.identity_unconfirmed'));}
});
test('malformed identity observations fail closed and anonymous or denied sessions remove private workspace state',async()=>{
 for(const value of [{authenticated:'true'}, {...(await fixture({start:false})).session(),can_manage:'true'}]){const f=await fixture({start:false});f.overrides.set('GET /api/identity/session',value);await f.render();assert.ok(f.form()===null,'No editable form may be exposed');}
 for(const value of [{items:[]},{items:[],roles:[],permissions:[],tenant_id:'different_tenant'}]){const f=await fixture({start:false});f.overrides.set('GET /api/identity/users',value);await f.render();assert.ok(f.form()===null,'No editable form may be exposed');assert.equal(f.content.querySelectorAll('input').length,0);}
 for(const anonymous of [true,false]){const f=await fixture();f.ui.state.snapshot={private:'secret'};f.nodes.zeroOutput.textContent='Private answer';if(anonymous)f.overrides.set('GET /api/identity/session',{authenticated:false});else f.deny();await f.render();assert.equal(f.ui.state.snapshot,null);assert.ok(!f.nodes.zeroOutput.textContent.includes('Private answer'));assert.ok(f.form()===null,'No editable form may be exposed');}
});
test('a mutation acknowledged after navigation stays recoverable and cannot repaint another section',async()=>{
 const f=await fixture();f.fill();const release=f.hold('/api/identity/users','POST'),write=f.form().fire('submit');await release.started;f.ui.state.activeSection='OTHER';f.content.textContent='Another section';release();await write;assert.equal(f.content.textContent,'Another section');assert.equal(f.saved.size,1);f.ui.state.activeSection='USERS';await f.render();await f.action('recover').fire('click');assert.ok(f.content.querySelector('textarea'));assert.equal(f.writes().filter(row=>row.route==='/api/identity/users').length,1);
});
test('unavailable durable request metadata blocks mutation before sending it',async()=>{
 const f=await fixture();f.context.sessionStorage.setItem=()=>{throw Error('Storage denied');};f.fill();await f.form().fire('submit');assert.equal(f.writes().length,0);assert.equal(f.identities.list(f.ctx,f.actor).items.length,0);
});
test('current native reissue and access edits use one stable request each and require a fresh list before another change',async()=>{
 const f=await fixture();f.fill();await f.form().fire('submit');const first=f.identities.list(f.ctx,f.actor).items[0],firstToken=f.content.querySelector('textarea').value;await f.render();
 const form=f.content.querySelectorAll('form')[1];f.field('reason',form).value='Reviewed replacement';f.field('confirm',form).checked=true;f.lose();await f.action('reissue',form).fire('click');assert.equal(f.identities.list(f.ctx,f.actor).items[0].revision,2);await f.action('reissue',form).fire('click');assert.equal(f.identities.list(f.ctx,f.actor).items[0].revision,2);assert.notEqual(f.content.querySelector('textarea').value,firstToken);assert.equal(f.action('reissue',form).disabled,true);await form.fire('submit');assert.equal(f.writes().length,3);
 await f.render();const next=f.content.querySelectorAll('form')[1];f.field('reason',next).value='Reviewed suspension';f.field('confirm',next).checked=true;const checks=next.querySelectorAll('input');checks.find(n=>n.value==='VIEWER').checked=false;checks.find(n=>n.value==='ANALYST').checked=true;f.lose();await next.fire('submit');await next.fire('submit');const member=f.identities.list(f.ctx,f.actor).items[0];assert.equal(member.id,first.id);assert.equal(member.revision,3);assert.equal(member.status,'SUSPENDED');assert.deepEqual(member.roles,['ANALYST']);assert.equal(f.writes()[3].key,f.writes()[4].key);assert.deepEqual(f.writes()[3].input,f.writes()[4].input);assert.equal(next.querySelector('button').disabled,true);assert.ok(f.content.querySelector('textarea')===null);
 for(const locale of locales){f.i.setLocale(locale);assert.ok(f.content.textContent.includes('Literal private person'));assert.ok(f.content.textContent.includes(f.i.t('workspace.page.identity_status.suspended')));assert.equal(f.i.missingKeys().length,0);}
});
test('recovery rejects another scope or revision, distinguishes superseded invitations and closes absent requests without claiming a member change',async()=>{
 const f=await fixture();f.fill();f.lose();await f.form().fire('submit');const pending=JSON.parse([...f.saved.values()][0])[0],receipt={...f.identities.request(f.ctx,f.actor,pending.request_id)};receipt.enrollment_url=f.session().public_origin+'/login#invite='+receipt.invite_token;await f.render();
 for(const patch of [{tenant_id:'other'},{actor_id:'other'},{dealer_id:'other'},{member:{...receipt.member,revision:2}},{delivered:true},{enrollment_url:'https://untrusted.test/login'}]){f.overrides.set('POST /api/identity/requests/'+pending.request_id+'/recover',{...receipt,...patch});await f.action('recover').fire('click');assert.ok(f.content.querySelector('textarea')===null);assert.equal(f.saved.size,1);}
 f.overrides.delete('POST /api/identity/requests/'+pending.request_id+'/recover');f.identities.reissue(f.ctx,f.actor,receipt.member.id,{expected_revision:1,confirm:true,reason:'Newer authorised invitation'},'fixture-newer-invitation');await f.action('recover').fire('click');assert.equal(f.saved.size,0);assert.ok(f.content.textContent.includes(f.i.t('workspace.page.identity_superseded')));assert.ok(f.content.querySelector('textarea')===null);
 const g=await fixture();g.fill();g.overrides.set('POST /api/identity/users',{});await g.form().fire('submit');await g.render();await g.action('recover').fire('click');assert.equal(g.saved.size,0);assert.equal(g.writes().filter(row=>row.route==='/api/identity/users').length,1);assert.ok(g.content.textContent.includes(g.i.t('workspace.page.identity_not_applied')));assert.equal(g.form().querySelector('button').disabled,true);
});
test('logout requires a current typed acknowledgement, suppresses duplicates and clears private views on confirmed sign-out',async()=>{
 const f=await fixture({start:false});f.overrides.set('GET /api/identity/session',{...f.session(),authentication_method:'MEMBER_SESSION'});await f.render();f.overrides.set('POST /api/identity/logout',{});await f.action('logout').fire('click');assert.equal(f.context.location.redirect,undefined);assert.ok(f.ui.state.workspace);f.overrides.delete('POST /api/identity/logout');const button=f.action('logout'),release=f.hold('/api/identity/logout','POST'),write=button.fire('click');await release.started;await button.fire('click');assert.equal(f.writes().length,2);release();await write;assert.equal(f.context.location.redirect,'/login');assert.equal(f.ui.state.workspace,null);assert.equal(f.content.textContent,'');
});
