'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture'),{create}=require('../workflow-draft-session');
test('native draft session recovers a genuinely lost HTTP reply across encrypted server restart before saving newer input',async()=>{
 const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-native-draft-ack-drop')});try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const calls=[],realm=(await f.request('/api/automation/drafts')).body.request_context;let drop=true;
  const session=create({id:'http-draft-session',requestContext:realm,request:async(route,options)=>{calls.push({...options});const headers=drop?{'x-native-draft-drop-reply':'isolated-http-fixture'}:{};drop=false;const response=await f.request(route,options.method,JSON.parse(options.body),null,headers);if(response.status!==200)throw Object.assign(Error('Native draft refused'),{status:response.status,code:response.body.code});return response.body;}});
  await assert.rejects(session.save({name:'  Private <img> first edit  ',steps:[{type:'create_task',values:{title:''}}]}));assert.equal(session.revision,0);await f.stop();await f.start();const result=await session.save({name:'Private second edit',steps:[]});assert.deepEqual(calls[1],calls[0]);assert.equal(calls.length,3);assert.equal(result.revision,2);assert.equal(result.draft.name,'Private second edit');const listed=(await f.request('/api/automation/drafts')).body.items;assert.equal(listed.length,1);assert.deepEqual(listed[0],result);assert.equal((await f.request('/api/automation/status')).body.workflow_count,0);assert.equal((await f.request('/api/automation/tasks')).body.total,0);const disk=fs.readFileSync(path.join(f.dir,'foundly-core-state.json'),'utf8');assert.ok(!disk.includes(result.draft.name));
 }finally{await f.close();}
});
test('a native draft PUT rechecks current member access after the authenticated body wait and creates no private draft',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'draft-put-body-')),marker=path.join(dir,'body'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../test-identity-body-barrier'),FOUNDLY_IDENTITY_BODY_BARRIER:marker});let held;try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('draft.put.owner',['ADMIN']),payload=JSON.stringify({draft:{name:'Private revoked editor'},expected_revision:0});
  const pending=new Promise((resolve,reject)=>{held=require('node:http').request(f.base+'/api/automation/drafts/revoked-editor',{method:'PUT',headers:{cookie:owner.cookie,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload),'x-identity-fixture-barrier':'body'}},res=>{let text='';res.on('data',part=>text+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}));});held.on('error',reject);held.write(payload.slice(0,-1));});
  for(let n=0;n<100&&!fs.existsSync(marker);n++)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(marker));assert.equal((await f.request('/api/identity/users/'+owner.member.id,'PUT',{roles:['VIEWER'],expected_revision:owner.member.revision,confirm:true,reason:'Revoke while native draft body waits'})).status,200);held.end(payload.slice(-1));const denied=await pending;assert.equal(denied.status,401);assert.ok(!JSON.stringify(denied.body).includes('Private revoked editor'));assert.equal((await f.request('/api/automation/drafts')).body.items.length,0);assert.equal((await f.request('/api/automation/status')).body.workflow_count,0);
 }finally{held?.destroy();await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
