'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/fixture'),{fixture:editorFixture}=require('../zero-evaluation/workflow-editor-fixture');
test('actual editor publication retries a genuinely lost HTTP response after encrypted server restart and preserves multiline content into a separate native execution',async()=>{
 const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-publication-ack-drop')});try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const realm=(await f.request('/api/automation/drafts')).body.request_context,spec=(await f.request('/api/automation/workflows')).body.editor_contract;let drop=true;
  const e=editorFixture({requestContext:realm,editorSpec:spec,withZero:false,requestOverride:async(route,options)=>{let headers={};if(drop&&route==='/api/automation/workflows'){drop=false;headers={'x-workflow-publish-drop-reply':'isolated-http-fixture'};}const result=await f.request(route,options.method,JSON.parse(options.body),null,headers);if(![200,201].includes(result.status))throw Object.assign(Error('Native request denied'),{status:result.status,code:result.body.code});return result.body;}});e.valid();const type=e.field('Actie');type.value='create_document';await type.fire('change');e.field('Documenttitel').value='Literal HTTP document';const content=e.field('Inhoud').value='First <img> literal line\nSecond line\twith tab';await e.box.fire('submit');assert.equal(e.saved.length,0);assert.equal(e.notice().textContent,e.i.t('workflow.editor.unconfirmed'));assert.equal((await f.request('/api/automation/status')).body.workflow_count,1);assert.equal((await f.request('/api/automation/documents')).body.total,0);const original=e.calls.at(-1);
  await f.stop();await f.start();e.i.setLocale('sv-SE');await e.box.fire('submit');assert.equal(e.saved.length,1,e.notice().textContent);assert.deepEqual(e.calls.at(-1),original);assert.equal(e.calls.filter(c=>c.operation==='DRAFT').length,1);const published=(await f.request('/api/automation/workflows')).body.workflows;assert.equal(published.length,1);assert.equal(published[0].actions[0].content,content);const run=await f.request('/api/automation/workflows/'+published[0].id+'/runs','POST',{event:{event_id:'literal-document-http-run'},options:{inputs:{}}});assert.equal(run.status,202,JSON.stringify(run.body));assert.equal(run.body.status,'SUCCEEDED');const documents=(await f.request('/api/automation/documents')).body;assert.equal(documents.total,1);assert.equal(documents.items[0].content,content);await f.stop();await f.start();assert.equal((await f.request('/api/automation/documents')).body.items[0].content,content);
 }finally{await f.close();}
});
