'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workspace-composer-fixture'),{locales}=require('../foundly-i18n');
const pause=()=>new Promise(resolve=>setImmediate(resolve));
test('composer owned controls follow eight locales without replacing drafts, capability IDs or issuing requests',async()=>{
 const f=await fixture();assert.ok(f.form());const form=f.form(),industry=f.industry(),checks=form.querySelectorAll('input');industry.value='AUTOMOTIVE';checks[0].checked=!checks[0].checked;const values=checks.map(n=>n.checked),calls=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.ok(f.form()===form,'The original form must remain active');assert.ok(f.industry()===industry,'The industry control must retain identity');assert.equal(industry.value,'AUTOMOTIVE');assert.deepEqual(checks.map(n=>n.checked),values);assert.equal(f.preview().textContent,f.i.t('workspace.page.composer_preview'));assert.equal(f.apply().textContent,f.i.t('workspace.page.composer_apply'));for(const [index,module]of f.catalog.modules.entries()){const group=f.fieldsets()[index];assert.equal(group.querySelector('legend').textContent,f.i.t('module.'+module.module_id));assert.ok(group.textContent.includes(f.i.t('workspace.page.composer_entitlement')));for(const cap of module.provided_capabilities){const suffix=cap.split(':')[1],key='workspace.page.'+(Object.hasOwn(require('../foundly-locales').messages[locale],'workspace.page.composer_capability.'+suffix)?'composer_capability.':'section.')+suffix;assert.ok(group.textContent.includes(f.i.t(key)),locale+' '+cap);}}assert.equal(f.calls.length,calls);assert.equal(f.i.missingKeys().length,0);}
});
test('malformed configuration flags or contradictory identity and module observations cannot create an editable composition',async()=>{
 for(const mutate of [v=>v.profile.capability_flags['crm:contacts']='false',v=>v.profile.industry_id='AUTOMOTIVE',v=>v.profile.entitlements=[],v=>v.profile=null,v=>v.resolution.revision=-1]){
  const f=await fixture({start:false}),current={ok:true,resolution:f.resolver.resolve(f.ctx,f.actor),profile:JSON.parse(JSON.stringify(f.resolver.profile(f.ctx))),can_manage:true};mutate(current);f.overrides.set('GET /api/composition',current);await f.render();assert.ok(f.form()===null,'Malformed observations must not produce an editable form');assert.equal(f.content.textContent,f.i.t('workspace.page.composer_invalid'));assert.equal(f.writes().length,0);
 }
});
test('retry after a lost acknowledgement preserves a newer native composition instead of overwriting it',async()=>{
 const f=await fixture();f.industry().value='AUTOMOTIVE';await f.form().fire('submit');f.lose();await f.apply().fire('click');assert.equal(f.resolver.profile(f.ctx).revision,2);
 f.resolver.configure(f.ctx,f.actor,{industry_id:'GENERAL',entitlements:['finance'],expected_revision:2});await f.apply().fire('click');assert.equal(f.resolver.profile(f.ctx).revision,3);assert.deepEqual(f.resolver.profile(f.ctx).entitlements,['finance']);assert.equal(f.apply().hidden,true);assert.equal(f.nodes.toastRegion.textContent,'');
});
test('revocation after review blocks native apply and a late committed response cannot repaint a retired view',async()=>{
 const f=await fixture();await f.form().fire('submit');f.actor.roles=['VIEWER'];await f.apply().fire('click');assert.equal(f.resolver.profile(f.ctx).revision,1);assert.equal(f.ui.state.workspace,null);assert.equal(f.content.children.length,0);
 const g=await fixture();g.industry().value='AUTOMOTIVE';await g.form().fire('submit');const release=g.hold('/api/composition','PUT'),pending=g.apply().fire('click');await release.started;g.ui.state.activeSection='USERS';g.content.textContent='Literal later view';release();await pending;assert.equal(g.content.textContent,'Literal later view');assert.equal(g.nodes.toastRegion.textContent,'');assert.equal(g.calls.some(c=>c.route==='/api/workspaces'),false);assert.equal(g.resolver.profile(g.ctx).revision,2);
});
test('changed selections invalidate a pending preview and cannot apply an obsolete reviewed payload',async()=>{
 const f=await fixture(),release=f.hold('/api/composition/preview','POST'),pending=f.form().fire('submit');await release.started;f.industry().value='AUTOMOTIVE';await f.form().fire('change');release();await pending;assert.equal(f.apply().hidden,true);await f.apply().fire('click');assert.equal(f.writes().length,0);assert.equal(f.resolver.profile(f.ctx).industry_id,'GENERAL');
});
test('an older composition read or preview cannot replace a newer or retired settings view',async()=>{
 const f=await fixture({start:false}),release=f.hold('/api/composition'),old=f.render();await release.started;await f.render();const form=f.form();release();await old;assert.ok(f.form()===form,'The original form must remain active');
 const delayed=f.hold('/api/composition/preview','POST'),pending=f.form().fire('submit');await delayed.started;f.ui.state.activeSection='USERS';f.content.replaceChildren();delayed();await pending;assert.equal(form.querySelectorAll('button').find(n=>n.type==='button').hidden,true);assert.equal(f.content.children.length,0);
 const g=await fixture({start:false}),late=g.hold('/api/composition'),read=g.render();await late.started;g.deny();await assert.rejects(g.ui.request('/api/composition'));late();await read;assert.equal(g.content.children.length,0);
});
test('a preview requires explicit native evidence and malformed apply replies cannot claim a saved composition',async()=>{
 for(const value of [{ok:true,diff:{enabled:[],disabled:[]}},{ok:false,diff:{enabled:[],disabled:[]}}]){const f=await fixture();f.overrides.set('POST /api/composition/preview',value);await f.form().fire('submit');assert.equal(f.apply().hidden,true);await f.apply().fire('click');assert.equal(f.writes().length,0);}
 const f=await fixture();f.industry().value='AUTOMOTIVE';await f.form().fire('submit');f.overrides.set('PUT /api/composition',{ok:true});await f.apply().fire('click');assert.equal(f.resolver.profile(f.ctx).industry_id,'GENERAL');assert.ok(!f.nodes.toastRegion.textContent.includes('opgeslagen'));assert.equal(f.form().querySelector('output').textContent,f.i.t('workspace.page.composer_unconfirmed'));
});
test('duplicate submission is suppressed and a dropped committed response retries the frozen reviewed request',async()=>{
 const f=await fixture();f.industry().value='AUTOMOTIVE';await f.form().fire('submit');const apply=f.apply(),release=f.hold('/api/composition','PUT');f.lose();const write=apply.fire('click');await release.started;await apply.fire('click');assert.equal(f.writes().length,1);release();await write;assert.equal(f.resolver.profile(f.ctx).revision,2);f.industry().value='GENERAL';await f.form().fire('change');for(const locale of locales)f.i.setLocale(locale);await apply.fire('click');assert.equal(f.writes().length,2);assert.deepEqual(f.writes()[1].input,f.writes()[0].input);assert.equal(f.resolver.profile(f.ctx).revision,2);assert.equal(f.adapter.bucket(f.ctx,'platform:audit').length,2);
});
test('composition management requires explicit true and successful native apply retains chosen canonical values',async()=>{
 const f=await fixture({start:false}),current={ok:true,resolution:f.resolver.resolve(f.ctx,f.actor),profile:f.resolver.profile(f.ctx),can_manage:'true'};f.overrides.set('GET /api/composition',current);await f.render();assert.ok(f.form().querySelectorAll('input,select').every(n=>n.disabled));assert.equal(f.preview().disabled,true);assert.equal(f.apply().disabled,true);await f.form().fire('submit');assert.equal(f.calls.some(c=>c.method==='POST'),false);
 const g=await fixture();g.industry().value='AUTOMOTIVE';await g.form().fire('submit');assert.equal(g.apply().hidden,false);await g.apply().fire('click');await pause();assert.equal(g.resolver.profile(g.ctx).industry_id,'AUTOMOTIVE');assert.equal(g.resolver.profile(g.ctx).revision,2);
});
test('review exposes entitlement-only and capability-only changes in every locale and sends their canonical values',async()=>{
 const f=await fixture(),groups=f.fieldsets(),procurement=groups[0].querySelectorAll('input'),crm=groups[2].querySelectorAll('input');procurement[0].checked=true;procurement[1].checked=false;crm[2].checked=false;await f.form().fire('change');await f.form().fire('submit');const before=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);const text=f.form().querySelector('output').textContent;assert.ok(text.includes(f.i.t('module.procurement')));assert.ok(text.includes(f.i.t('module.crm')+' / '+f.i.t('workspace.page.composer_capability.contacts')));assert.equal(f.calls.length,before);assert.equal(f.i.missingKeys().length,0);}
 await f.apply().fire('click');const profile=f.resolver.profile(f.ctx);assert.equal(profile.entitlements.includes('procurement'),true);assert.equal(profile.enabled_modules.includes('procurement'),false);assert.equal(profile.capability_flags['crm:contacts'],false);
});
test('a confirmed write followed by failed navigation refresh is not retried as an unconfirmed mutation',async()=>{
 const f=await fixture();f.industry().value='AUTOMOTIVE';await f.form().fire('submit');f.overrides.set('GET /api/workspaces',{});const button=f.apply();await button.fire('click');assert.equal(f.writes().length,1);assert.equal(f.apply().hidden,true);assert.equal(f.form().querySelector('output').textContent,f.i.t('workspace.page.composer_saved_refresh_failed'));await button.fire('click');assert.equal(f.writes().length,1);
});
