'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{FoundlyPlatformCore}=require('../platform-core'),{CapabilityResolver}=require('../capability-resolver'),{WorkflowDrafts,SCOPE}=require('../workflow-drafts'),zero=require('../workflow-zero');
const REQUESTS='platform:automation_draft_requests';
function fixture(){const rows=new Map(),ctx={tenant_id:'draft_recovery_fixture',dealer_id:'default'},actor={id:'draft_owner',roles:['ADMIN','SUPER_ADMIN']};let fail=false,writes=0;const adapter={bucket(c,s){const key=JSON.stringify([c,s]);if(!rows.has(key))rows.set(key,[]);return rows.get(key);},persist(){if(fail)throw Object.assign(Error('Isolated persist failure'),{code:'EIO'});writes++;},audit(){}};const resolver=new CapabilityResolver(adapter);resolver.configure(ctx,actor,{entitlements:['automation'],expected_revision:0});const core=new FoundlyPlatformCore(adapter),drafts=new WorkflowDrafts(adapter,resolver),draft={name:'Literal private recovered draft',version:1,trigger_type:'custom_event',automatic:false,approval_required:true,steps:[{type:'create_task',values:{title:'Literal private task'}}]},meta={message:'Isolated reviewed private draft',conversation_id:'draft_recovery_conversation',turn_id:'draft_recovery_turn'};
 const preview=id=>zero.execute(drafts,core,ctx,actor,{operation:'PREVIEW',draft_id:id,input:{draft,expected_revision:0}},meta).automation_data;
 const save=(id,fingerprint)=>zero.execute(drafts,core,ctx,actor,{operation:'SAVE',draft_id:id,input:{draft,expected_revision:0,preview_fingerprint:fingerprint,confirm:true,reason:'Isolated native confirmation'}},meta).automation_data;
 return {rows,ctx,actor,adapter,resolver,core,drafts,draft,preview,save,fail:value=>{fail=value;},writes:()=>writes};}
const review=fingerprint=>({expected_revision:0,preview_fingerprint:fingerprint,confirm:true});
test('new private draft recovery is bound to the original native preview and current actor, realm and revision',()=>{
 const f=fixture(),id='recoverable-draft',p=f.preview(id),saved=f.save(id,p.preview_fingerprint),before=f.writes();const recovered=f.drafts.recoverNew(f.ctx,f.actor,id,review(p.preview_fingerprint));assert.equal(recovered.state,'APPLIED');assert.deepEqual(recovered.record,saved.record);assert.equal(recovered.preview_fingerprint,p.preview_fingerprint);assert.deepEqual(recovered.request_context,{...f.ctx,actor_id:f.actor.id});assert.equal(f.writes(),before);
 assert.throws(()=>f.drafts.recoverNew(f.ctx,f.actor,id,review('f'.repeat(64))),{code:'workflow_draft_request_conflict'});assert.throws(()=>f.drafts.recoverNew(f.ctx,{...f.actor,id:'another_owner'},id,review(p.preview_fingerprint)),{code:'workflow_draft_missing'});
 f.drafts.save(f.ctx,f.actor,id,{draft:{...f.draft,name:'Literal newer draft'},expected_revision:1});assert.throws(()=>f.drafts.recoverNew(f.ctx,f.actor,id,review(p.preview_fingerprint)),{code:'workflow_draft_request_superseded'});assert.throws(()=>f.save(id,p.preview_fingerprint),{code:'workflow_draft_conflict'});
});
test('terminal closure atomically prevents an absent new draft from being committed later while independent IDs remain usable',()=>{
 const f=fixture(),id='closed-draft',p=f.preview(id),input=review(p.preview_fingerprint);f.fail(true);assert.throws(()=>f.drafts.recoverNew(f.ctx,f.actor,id,input),{code:'EIO'});f.fail(false);assert.equal(f.adapter.bucket(f.ctx,REQUESTS).length,0);const closed=f.drafts.recoverNew(f.ctx,f.actor,id,input);assert.equal(closed.state,'NOT_APPLIED');assert.equal(closed.record,null);assert.deepEqual(f.drafts.recoverNew(f.ctx,f.actor,id,input),closed);assert.throws(()=>f.save(id,p.preview_fingerprint),{code:'workflow_draft_request_abandoned'});assert.equal(f.drafts.list(f.ctx,f.actor).items.length,0);const next=f.preview('independent-draft');assert.equal(f.save('independent-draft',next.preview_fingerprint).record.revision,1);
});
test('creation and recovery evidence roll back together; missing recorded drafts never reappear from an older retry',()=>{
 const f=fixture(),id='atomic-draft',p=f.preview(id);f.fail(true);assert.throws(()=>f.save(id,p.preview_fingerprint),{code:'EIO'});f.fail(false);assert.equal(f.adapter.bucket(f.ctx,REQUESTS).length,0);assert.equal(f.drafts.list(f.ctx,f.actor).items.length,0);f.save(id,p.preview_fingerprint);assert.equal(f.adapter.bucket(f.ctx,REQUESTS).length,1);f.adapter.bucket(f.ctx,SCOPE).length=0;const before=f.writes();assert.throws(()=>f.save(id,p.preview_fingerprint),{code:'workflow_draft_request_unavailable'});assert.throws(()=>f.drafts.recoverNew(f.ctx,f.actor,id,review(p.preview_fingerprint)),{code:'workflow_draft_request_unavailable'});assert.equal(f.writes(),before);assert.equal(f.drafts.list(f.ctx,f.actor).items.length,0);
});
test('legacy drafts remain readable and retryable without fabricating generated-preview attribution; current authority precedes recovery',()=>{
 const f=fixture(),id='legacy-draft',p=f.preview(id),saved=f.drafts.save(f.ctx,f.actor,id,{draft:f.draft,expected_revision:0});assert.deepEqual(f.drafts.save(f.ctx,f.actor,id,{draft:f.draft,expected_revision:0}).record,saved.record);assert.throws(()=>f.drafts.recoverNew(f.ctx,f.actor,id,review(p.preview_fingerprint)),{code:'workflow_draft_request_unverifiable'});assert.throws(()=>f.drafts.recoverNew(f.ctx,{...f.actor,roles:['VIEWER']},id,review(p.preview_fingerprint)),{statusCode:403});f.resolver.configure(f.ctx,f.actor,{entitlements:['automation'],capability_flags:{'automation:workflows':false},expected_revision:1});assert.throws(()=>f.drafts.recoverNew(f.ctx,f.actor,id,review(p.preview_fingerprint)),{statusCode:403});
});
test('receipt capacity preserves prior recovery and rejects new effects, and terminal confirmation remains typed',()=>{
 const f=fixture(),id='retained-receipt',p=f.preview(id);f.save(id,p.preview_fingerprint);const rows=f.adapter.bucket(f.ctx,REQUESTS);for(let n=rows.length;n<10000;n++)rows.push({draft_id:'other-'+n,actor_id:'other'});const before=f.writes(),next=f.preview('over-capacity');assert.throws(()=>f.save('over-capacity',next.preview_fingerprint),{code:'workflow_draft_request_capacity'});assert.equal(f.drafts.recoverNew(f.ctx,f.actor,id,review(p.preview_fingerprint)).state,'APPLIED');assert.equal(rows.length,10000);assert.equal(f.writes(),before);assert.throws(()=>f.drafts.recoverNew(f.ctx,f.actor,'typed-confirmation',{...review(next.preview_fingerprint),confirm:'true'}),{code:'workflow_draft_recovery_invalid'});
});
test('the original keyless native draft protocol still replays identical generated content without inventing its preview reference',()=>{
 const f=fixture(),id='native-compatible',p=f.preview(id),saved=f.save(id,p.preview_fingerprint);const replay=f.drafts.save(f.ctx,f.actor,id,{draft:f.draft,expected_revision:0});assert.equal(replay.deduplicated,true);assert.deepEqual(replay.record,saved.record);assert.equal(replay.preview_fingerprint,null);assert.equal(f.drafts.recoverNew(f.ctx,f.actor,id,review(p.preview_fingerprint)).state,'APPLIED');
});
