'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workspace-page-fixture'),{locales}=require('../foundly-i18n');
function client(){const f=fixture(),native=f.context.fetch,writes=[];let lose=false,malformed=false,deny=false,hold,started;f.context.fetch=async(route,options={})=>{
 if(options.method==='PUT'&&route.includes('/dashboard')){writes.push({route,options:JSON.parse(JSON.stringify(options))});if(hold){started();await hold;}if(deny)return {ok:false,status:403,json:async()=>({error:'RAW_PRIVATE_DENIAL'})};if(lose){lose=false;throw Error('Lost committed reply');}const draft=JSON.parse(options.body);return {ok:true,status:200,json:async()=>malformed?{ok:true}:{dashboard:{...draft,workspace_id:'data',revision:draft.revision+1,persisted:true},request_id:options.headers['idempotency-key']}};}
 return native(route,options);
 };return {...f,writes,lose(){lose=true;},malformed(value=true){malformed=value;},denyWrite(){deny=true;},holdWrite(){let release;hold=new Promise(resolve=>release=resolve);release.started=new Promise(resolve=>started=resolve);return release;}};}
test('workspace controller retains original dashboard request through response loss, locale changes and explicit access refresh',async()=>{
 const f=client();await f.ui.loadWorkspaceData();f.ui.toggleEditing(true);f.nodes.dateFrom.value='2026-09-01';f.lose();await f.ui.saveDashboard();assert.equal(f.nodes.dateFrom.disabled,true);assert.equal(f.nodes.saveDashboard.disabled,false);const first=f.writes[0],calls=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,calls);assert.ok(f.nodes.workspaceNotice.textContent.includes(f.i.t('workspace.page.write_unconfirmed')));assert.equal(f.nodes.dateFrom.value,'2026-09-01');}
 f.nodes.dateFrom.value='2020-01-01';await f.ui.loadWorkspaceData();await f.ui.saveDashboard();assert.equal(f.writes.length,2);assert.deepEqual(f.writes[1],first);assert.ok(first.options.headers['idempotency-key']);assert.equal(f.ui.state.dashboard.revision,2);assert.equal(f.ui.state.dashboard.filters.from,'2026-09-01');assert.equal(f.nodes.dateFrom.disabled,false);
});
test('workspace controller leaves missing save acknowledgement unconfirmed and retries the same original identity',async()=>{
 const f=client();await f.ui.loadWorkspaceData();f.ui.toggleEditing(true);f.malformed();await f.ui.saveDashboard();assert.equal(f.ui.state.dashboard.revision,1);assert.equal(f.nodes.dateFrom.disabled,true);f.malformed(false);await f.ui.saveDashboard();assert.deepEqual(f.writes[1],f.writes[0]);assert.equal(f.ui.state.dashboard.revision,2);
});
test('pending dashboard submission locks editing controls and duplicate submits do not create another write',async()=>{
 const f=client();await f.ui.loadWorkspaceData();f.ui.toggleEditing(true);const remove=f.nodes.dashboardGrid.children[0].all().find(n=>n.tag==='button'&&n.textContent==='×'),release=f.holdWrite(),pending=f.ui.saveDashboard();await release.started;await f.ui.saveDashboard();await remove.fire('click');assert.equal(f.writes.length,1);assert.equal(f.ui.state.dashboard.widgets.length,2);assert.equal(f.nodes.dateFrom.disabled,true);release();await pending;
});
test('pending dashboard refresh rechecks current access and a late save cannot re-enable a revoked private editor',async()=>{
 const f=client();await f.ui.loadWorkspaceData();f.ui.toggleEditing(true);const release=f.holdWrite(),pending=f.ui.saveDashboard();await release.started;f.deny();await assert.rejects(f.ui.loadWorkspaceData());release();await pending;assert.equal(f.ui.state.dashboard,null);assert.equal(f.nodes.dashboardGrid.textContent,'');assert.equal(f.nodes.saveDashboard.disabled,true);const writes=f.writes.length;await f.ui.saveDashboard();assert.equal(f.writes.length,writes);
});
test('a mismatched dashboard scope before any write stays editable and does not become an unconfirmed save',async()=>{
 const f=client();await f.ui.loadWorkspaceData();f.ui.toggleEditing(true);f.nodes.dashboardScope.value='TEAM';f.nodes.dashboardQualifier.value='literal_unloaded_team';await f.ui.saveDashboard();assert.equal(f.writes.length,0);assert.equal(f.nodes.dateFrom.disabled,false);assert.ok(!f.nodes.workspaceNotice.textContent.includes(f.i.t('workspace.page.write_unconfirmed')));f.nodes.dashboardScope.value='PERSONAL';f.nodes.dashboardQualifier.value='';await f.ui.saveDashboard();assert.equal(f.writes.length,1);assert.equal(f.ui.state.dashboard.revision,2);
});
test('a definitive rejected dashboard save releases inputs and gives a corrected request a new identity',async()=>{
 const f=client();await f.ui.loadWorkspaceData();f.ui.toggleEditing(true);const native=f.context.fetch;let reject=true,rejectedKey;f.context.fetch=async(route,options)=>{if(reject&&options?.method==='PUT'){rejectedKey=options.headers['idempotency-key'];return {ok:false,status:422,json:async()=>({code:'dashboard_invalid',error:'RAW_PRIVATE_VALIDATION'})};}return native(route,options);};await f.ui.saveDashboard();assert.equal(f.nodes.dateFrom.disabled,false);assert.ok(!f.nodes.workspaceNotice.textContent.includes('RAW_PRIVATE'));reject=false;f.nodes.dateFrom.value='2026-09-20';await f.ui.saveDashboard();assert.equal(f.ui.state.dashboard.filters.from,'2026-09-20');assert.notEqual(f.writes[0].options.headers['idempotency-key'],rejectedKey);
});
