'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workflow-generator-fixture'),{locales}=require('../foundly-i18n');
async function pending(f,committed=true){f.prompt().value='Private description never retained in browser storage';await f.prepare().fire('click');f.reason().value='Private reason never retained in browser storage';if(committed)f.lose();else f.failBeforeSave();await f.save().fire('click');return f.calls.at(-1);}
test('a fresh generator recovers a committed native draft using only realm-scoped metadata without reissuing its private SAVE',async()=>{
 const f=fixture();await pending(f);assert.equal(f.storage.size,1);const text=[...f.storage.values()].join('');for(const value of ['Private description','Private reason',f.draft.name,'Literal <script> title'])assert.ok(!text.includes(value));const metadata=JSON.parse(text)[0];assert.deepEqual(Object.keys(metadata).sort(),['draft_id','expected_revision','preview_fingerprint']);const g=fixture({native:f.native,storage:f.storage}),before=g.counts();assert.ok(g.recover());assert.equal(g.save().disabled,true);assert.equal(g.preview().textContent,'');for(const locale of locales){g.i.setLocale(locale);assert.equal(g.recover().textContent,g.i.t('workflow.generator.recover'));}await g.recover().fire('click');assert.equal(g.calls.length,1);assert.equal(g.calls[0].action.operation,'RECOVER');assert.equal(g.saved.length,1);assert.equal(g.saved[0].id,metadata.draft_id);assert.equal(g.storage.size,0);assert.ok(!g.box.textContent.includes(g.i.t('workflow.generator.pending')));assert.deepEqual(g.counts(),before);assert.equal(g.core.automationStatus(g.ctx,g.actor).workflow_count,0);
});
test('reload can close an uncommitted original request so that its delayed SAVE cannot create a draft later',async()=>{
 const f=fixture(),original=await pending(f,false),g=fixture({native:f.native,storage:f.storage});assert.ok(g.recover());await g.recover().fire('click');assert.equal(g.saved.length,0);assert.equal(g.records().length,0);assert.equal(g.storage.size,0);assert.throws(()=>f.deliver(original),{code:'workflow_draft_request_abandoned'});assert.ok(g.box.textContent.includes(g.i.t('workflow.generator.not_applied')));assert.equal(g.prepare().disabled,false);
});
test('unavailable storage prevents a new write while retaining the reviewed private proposal',async()=>{
 const f=fixture();f.prompt().value='Literal proposal';await f.prepare().fire('click');f.reason().value='Reviewed';f.failStorage();const calls=f.calls.length,before=f.counts();await f.save().fire('click');assert.equal(f.calls.length,calls);assert.deepEqual(f.counts(),before);assert.ok(f.preview().textContent.includes(f.draft.name));assert.equal(f.notice().textContent,f.i.t('workflow.generator.storage_required'));
});
test('mismatched recovery evidence and retired views cannot clear a scoped pending reference or claim a saved draft',async()=>{
 const f=fixture();await pending(f);const g=fixture({native:f.native,storage:f.storage});g.alter(r=>({...r,request_context:{...r.request_context,actor_id:'another_actor'}}));await g.recover().fire('click');assert.equal(g.saved.length,0);assert.equal(g.storage.size,1);g.alter(null);const release=g.hold('RECOVER'),read=g.recover().fire('click');await release.started;g.retire();release();await read;assert.equal(g.saved.length,0);assert.equal(g.storage.size,1);
});
test('failure to remove a closed request reference cannot turn a not-applied result into a saved-draft claim',async()=>{
 const f=fixture();await pending(f,false);const g=fixture({native:f.native,storage:f.storage}),release=g.hold('RECOVER');const read=g.recover().fire('click');await release.started;g.failStorage();release();await read;assert.equal(g.records().length,0);assert.equal(g.saved.length,0);assert.equal(g.storage.size,1);for(const locale of locales){g.i.setLocale(locale);assert.ok(g.box.textContent.includes(g.i.t('workflow.generator.recovery_metadata')));assert.ok(!g.box.textContent.includes(g.i.t('workflow.generator.saved_metadata')));}
});
test('another actor cannot load pending private references and malformed stored metadata blocks new draft writes',async()=>{
 const f=fixture();await pending(f);const g=fixture({native:{...f.native,actor:{...f.actor,id:'other_generator_actor'}},storage:f.storage});assert.equal(g.recover(),undefined);assert.equal(g.calls.length,0);assert.equal(g.saved.length,0);assert.ok(!g.box.textContent.includes(f.draft.name));const key=[...f.storage.keys()][0];f.storage.set(key,'{"invalid":"metadata"}');const h=fixture({native:f.native,storage:f.storage}),before=h.counts();h.prompt().value='A different proposal';await h.prepare().fire('click');h.reason().value='Explicit reason';const calls=h.calls.length;await h.save().fire('click');assert.equal(h.calls.length,calls);assert.deepEqual(h.counts(),before);assert.equal(h.save().disabled,true);
});
