'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workflow-editor-fixture'),{locales}=require('../foundly-i18n');
test('owned editor controls and branch/condition labels follow eight locales while literal input, nodes and native state remain unchanged',async()=>{
 const f=fixture();f.valid();const type=f.field('Actie');type.value='branch';await type.fire('change');const input=f.field('Workflownaam'),version=f.field('Versie'),before=f.counts(),calls=f.calls.length;version.value='1234';input.value='Literal <img> customer workflow';await f.box.fire('input');
 for(const locale of locales){f.i.setLocale(locale);assert.ok(f.button('Workflowversie opslaan'));assert.equal(f.button('Workflowversie opslaan').textContent,f.i.t('workflow.editor.publish'));assert.ok(f.box.textContent.includes(f.i.t('workflow.editor.then')));assert.ok(f.box.textContent.includes(f.i.t('workflow.editor.help')));assert.equal(f.field('Workflownaam'),input);assert.equal(f.field('Versie'),version);assert.equal(input.value,'Literal <img> customer workflow');assert.equal(version.value,'1234');assert.equal(type.value,'branch');assert.equal(f.notice().textContent,f.i.t('workflow.editor.dirty'));assert.equal(f.i.missingKeys().length,0);}assert.equal(f.calls.length,calls);assert.deepEqual(f.counts(),before);assert.equal(f.box.querySelector('img'),null);
});
test('ZERO editor review includes every literal action field, trigger and approval while owned readout follows locale without new requests',async()=>{
 const f=fixture();f.valid();const type=f.field('Actie');type.value='create_document';await type.fire('change');f.field('Documenttitel').value='Literal document';f.field('Inhoud').value='Literal <script> complete document\nRetained second line';await f.button('Concept met ZERO voorbereiden').fire('click');const calls=f.calls.length,before=f.counts();
 for(const locale of locales){f.i.setLocale(locale);const review=f.find('pre').textContent;assert.ok(review.includes('Literal <script> complete document\nRetained second line'));assert.ok(review.includes(f.i.t('workflow.generator.content')));assert.ok(review.includes(f.i.t('workflow.trigger.custom_event')));assert.ok(review.includes(f.i.t('workflow.generator.approval',{value:f.i.t('workflow.generator.not_required')})));assert.equal(f.notice().textContent,f.i.t('workflow.editor.review'));assert.equal(f.i.missingKeys().length,0);}assert.equal(f.calls.length,calls);assert.deepEqual(f.counts(),before);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);assert.equal(f.counts().effects,0);assert.equal(f.box.querySelector('script'),null);
});
test('current denial and compiler feedback are localized safely without provider or native diagnostic text',async()=>{
 const f=fixture();f.valid();f.deny(403);await f.button('Concept met ZERO voorbereiden').fire('click');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.notice().textContent,f.i.t('common.access_denied'));assert.ok(!f.box.textContent.includes('RAW_PRIVATE_DENIAL'));assert.equal(f.find('pre').textContent,'');}
 const g=fixture();g.valid();const conditional=g.field('Alleen uitvoeren wanneer de conditie waar is');conditional.checked=true;await conditional.fire('change');g.field('Conditieveld, bijvoorbeeld inputs.priority').value='inputs.priority';g.field('Vergelijking').value='in';await g.box.fire('submit');for(const locale of locales){g.i.setLocale(locale);assert.equal(g.notice().textContent,g.i.t('workflow.editor.condition_values'));}assert.equal(g.calls.length,0);
});
test('locale changes during an uncertain publication preserve the frozen request and explicit retry controls',async()=>{
 const f=fixture();f.valid();f.lose('PUBLISH');await f.box.fire('submit');const original=f.calls.at(-1),count=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.notice().textContent,f.i.t('workflow.editor.unconfirmed'));assert.equal(f.button('Workflowversie opslaan').textContent,f.i.t('workflow.editor.retry_publication'));assert.equal(f.field('Workflownaam').disabled,true);assert.equal(f.i.missingKeys().length,0);}assert.equal(f.calls.length,count);await f.box.fire('submit');assert.deepEqual(f.calls.at(-1),original);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,1);assert.equal(f.saved.length,1);
});
test('late ZERO review uses the current locale and cannot restore a changed or retired draft proposal',async()=>{
 const f=fixture();f.valid();const release=f.hold('PREVIEW'),pending=f.button('Concept met ZERO voorbereiden').fire('click');await release.started;f.i.setLocale('de-DE');release();await pending;assert.equal(f.notice().textContent,f.i.t('workflow.editor.review'));assert.ok(f.find('pre').textContent.includes(f.i.t('workflow.trigger.custom_event')));
 const g=fixture();g.valid();const finish=g.hold('PREVIEW'),stale=g.button('Concept met ZERO voorbereiden').fire('click');await finish.started;g.field('Workflownaam').value='Changed while preview waited';await g.box.fire('input');g.i.setLocale('fr-FR');finish();await stale;assert.equal(g.find('pre').textContent,'');assert.equal(g.button('Bevestig concept bewaren via ZERO').disabled,true);assert.equal(g.notice().textContent,g.i.t('workflow.editor.dirty'));
 const h=fixture();h.valid();const done=h.hold('PREVIEW'),retired=h.button('Concept met ZERO voorbereiden').fire('click');await done.started;h.retire();done();await retired;assert.equal(h.find('pre').textContent,'');assert.equal(h.button('Bevestig concept bewaren via ZERO').disabled,true);
});
