'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workflow-editor-fixture');
test('retired editor controls and an already scheduled autosave dispatch no native or ZERO requests',async()=>{
 const f=fixture();f.valid();await f.box.fire('input');const timers=[...f.timers.values()];f.retire();for(const timer of timers)await timer();await f.button('Concept nu bewaren').fire('click');await f.button('Bewaar invoer als nieuw concept').fire('click');await f.button('Concept met ZERO voorbereiden').fire('click');await f.box.fire('submit');await new Promise(resolve=>setImmediate(resolve));assert.equal(f.calls.length,0);assert.equal(f.saved.length,0);assert.equal(f.records().length,0);
});
test('a late native draft reply cannot publish or call saved after the owning editor retires',async()=>{
 const f=fixture();f.valid();const release=f.hold(),pending=f.box.fire('submit');await release.started;const notice=f.notice().textContent;f.retire();release();await pending;assert.equal(f.calls.filter(c=>c.operation==='PUBLISH').length,0);assert.equal(f.saved.length,0);assert.equal(f.notice().textContent,notice);assert.equal(f.records().length,1);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);
});
test('changed input during a publication prerequisite must be reviewed again before publication',async()=>{
 const f=fixture();f.valid();const release=f.hold(),pending=f.box.fire('submit');await release.started;f.field('Workflownaam').value='Changed while draft acknowledgement waited';await f.box.fire('input');release();await pending;assert.equal(f.calls.filter(c=>c.operation==='PUBLISH').length,0);assert.equal(f.saved.length,0);assert.equal(f.box.dataset.unsaved,'true');assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);
});
test('saving as a new draft cannot replace ownership of a pending native editor save',async()=>{
 const f=fixture();f.valid();await f.box.fire('input');const release=f.hold(),pending=f.button('Concept nu bewaren').fire('click');await release.started;const count=f.calls.length;await f.button('Bewaar invoer als nieuw concept').fire('click');assert.equal(f.calls.length,count);release();await pending;await new Promise(resolve=>setImmediate(resolve));assert.equal(f.records().length,1);assert.equal(f.box.dataset.unsaved,'false');
});
test('malformed native prerequisite acknowledgement never permits workflow publication and exact retry can recover it',async()=>{
 const f=fixture();f.valid();f.alter((result,operation)=>{if(operation==='DRAFT')result.record.draft.name='Unattributed replacement';return result;});await f.box.fire('submit');assert.equal(f.calls.filter(c=>c.operation==='PUBLISH').length,0);assert.equal(f.saved.length,0);const original=f.calls[0];f.alter(null);await f.box.fire('submit');assert.deepEqual(f.calls[1],original);assert.equal(f.saved.length,1);assert.equal(f.records().length,1);assert.equal(f.counts().effects,0);
});
test('a genuine native conflict preserves another editor and permits an explicitly separate new draft',async()=>{
 const f=fixture();f.valid();await f.button('Concept nu bewaren').fire('click');const row=f.records()[0];f.drafts.save(f.ctx,f.actor,row.id,{draft:{...row.draft,name:'Other editor retained revision'},expected_revision:row.revision});f.field('Workflownaam').value='My separate conflict copy';await f.box.fire('input');await f.button('Concept nu bewaren').fire('click');const count=f.calls.length;await f.button('Bewaar invoer als nieuw concept').fire('click');assert.equal(f.calls.length,count+1);assert.equal(f.records().length,2);assert.equal(f.records().find(r=>r.id===row.id).draft.name,'Other editor retained revision');assert.equal(f.records().find(r=>r.id!==row.id).draft.name,'My separate conflict copy');assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);
});
test('an uncertain private draft cannot be forked into a duplicate with the save-as-new control',async()=>{
 const f=fixture();f.valid();f.lose('DRAFT');await f.button('Concept nu bewaren').fire('click');const count=f.calls.length;await f.button('Bewaar invoer als nieuw concept').fire('click');assert.equal(f.calls.length,count);assert.equal(f.records().length,1);await f.button('Concept nu bewaren').fire('click');assert.deepEqual(f.calls[1],f.calls[0]);assert.equal(f.records()[0].revision,1);
});
async function prepared(f){f.valid();await f.button('Concept met ZERO voorbereiden').fire('click');assert.equal(f.button('Bevestig concept bewaren via ZERO').disabled,false,f.notice().textContent);f.field('Reden om dit concept via ZERO te bewaren').value='Reviewed exact private concept';}
test('uncertain ZERO editor saves keep the original action and turn through reason changes and block other write paths',async()=>{
 const f=fixture();await prepared(f);f.lose('SAVE');await f.button('Bevestig concept bewaren via ZERO').fire('click');const original=f.calls.at(-1),count=f.calls.length;f.field('Reden om dit concept via ZERO te bewaren').value='Changed after lost reply';await f.box.fire('input');await f.button('Concept met ZERO voorbereiden').fire('click');await f.button('Concept nu bewaren').fire('click');await f.button('Bewaar invoer als nieuw concept').fire('click');await f.box.fire('submit');assert.equal(f.calls.length,count);await f.button('Bevestig concept bewaren via ZERO').fire('click');assert.deepEqual(f.calls.at(-1),original);assert.equal(f.records()[0].revision,2);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);assert.equal(f.counts().effects,0);
});
test('ZERO editor preparation binds the exact compiled definition, private draft and revision before enabling confirmation',async()=>{
 for(const change of [r=>r.expected_revision=99,r=>r.publication_required=false,r=>r.preview_fingerprint='unverified',r=>r.definition.actions[0].title='Unreviewed action',r=>r.draft.name='Other private draft']){const f=fixture();f.valid();f.alter((r,op)=>{if(op==='PREVIEW')change(r);return r;});await f.button('Concept met ZERO voorbereiden').fire('click');assert.equal(f.button('Bevestig concept bewaren via ZERO').disabled,true);assert.equal(f.find('pre').textContent,'');assert.equal(f.calls.filter(c=>c.operation==='SAVE').length,0);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);}
});
test('ZERO editor acknowledgement must bind the exact reviewed private revision before adopting it',async()=>{
 for(const change of [r=>r.record.revision=99,r=>r.request_context.actor_id='foreign',r=>r.record.draft.name='Unreviewed saved draft',r=>r.record.executable=true,r=>r.request_fingerprint='a'.repeat(64)]){const f=fixture();await prepared(f);f.alter((r,op)=>{if(op==='SAVE')change(r);return r;});await f.button('Bevestig concept bewaren via ZERO').fire('click');assert.equal(f.button('Bevestig concept bewaren via ZERO').disabled,false);assert.equal(f.box.dataset.unsaved,'true');f.alter(null);const original=f.calls.at(-1);await f.button('Bevestig concept bewaren via ZERO').fire('click');assert.deepEqual(f.calls.at(-1),original);assert.equal(f.records()[0].revision,2);assert.equal(f.box.dataset.unsaved,'false');}
});
test('an uncertain publication freezes its definition and retries only that immutable version without another private save',async()=>{
 const f=fixture();f.valid();f.lose('PUBLISH');await f.box.fire('submit');const original=f.calls.at(-1),count=f.calls.length;assert.equal(original.operation,'PUBLISH');assert.equal(f.saved.length,0);f.field('Workflownaam').value='Changed after uncertain publication';f.field('Versie').value='2';await f.box.fire('input');await f.button('Concept nu bewaren').fire('click');await f.button('Bewaar invoer als nieuw concept').fire('click');await f.button('Concept met ZERO voorbereiden').fire('click');assert.equal(f.calls.length,count);await f.box.fire('submit');assert.equal(f.calls.length,count+1);assert.deepEqual(f.calls.at(-1),original);assert.equal(f.saved.length,1);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,1);assert.equal(f.records()[0].revision,1);assert.equal(f.counts().effects,0);
});
test('publication requires a typed matching native immutable definition before a saved callback',async()=>{
 for(const change of [()=>({ok:true}),r=>({...r,version:99}),r=>({...r,tenant_id:'foreign'}),r=>({...r,immutable_version:false}),r=>({...r,signature:'a'.repeat(64)}),r=>({...r,actions:[{type:'create_task',title:'Unreviewed replacement'}]})]){const f=fixture();f.valid();f.alter((r,op)=>op==='PUBLISH'?change(r):r);await f.box.fire('submit');assert.equal(f.saved.length,0);assert.equal(f.box.dataset.unsaved,'true');const original=f.calls.at(-1);f.alter(null);await f.box.fire('submit');assert.deepEqual(f.calls.at(-1),original);assert.equal(f.saved.length,1);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,1);}
});
test('typing the ZERO confirmation reason after review does not invalidate the reviewed draft or schedule an autosave',async()=>{
 const f=fixture();await prepared(f);const reason=f.field('Reden om dit concept via ZERO te bewaren'),before=f.calls.length;reason.value='Reason entered after review';await f.box.fire('input',{target:reason});await f.box.fire('change',{target:reason});assert.equal(f.button('Bevestig concept bewaren via ZERO').disabled,false);assert.equal(f.timers.size,0);assert.equal(f.calls.length,before);await f.button('Bevestig concept bewaren via ZERO').fire('click');assert.equal(f.calls.at(-1).action.input.reason,reason.value);assert.equal(f.records()[0].revision,2);
});
test('a subsequent ordinary private save invalidates the older ZERO revision review before confirmation',async()=>{
 const f=fixture();await prepared(f);await f.button('Concept nu bewaren').fire('click');const count=f.calls.length;assert.equal(f.button('Bevestig concept bewaren via ZERO').disabled,true);assert.equal(f.find('pre').textContent,'');await f.button('Bevestig concept bewaren via ZERO').fire('click');assert.equal(f.calls.length,count);assert.equal(f.records()[0].revision,2);
});
test('literal multiline document content survives the reviewed native publication without a false acknowledgement mismatch',async()=>{
 const f=fixture();f.valid();const type=f.field('Actie');type.value='create_document';await type.fire('change');f.field('Documenttitel').value='Literal document';f.field('Inhoud').value='First literal <img> line\nSecond line\twith tab';await f.box.fire('submit');assert.equal(f.saved.length,1,f.notice().textContent);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflows[0].actions[0].content,f.field('Inhoud').value);assert.equal(f.counts().effects,0);
});
test('native-only editor step controls retain dirty tracking without a ZERO reason field',async()=>{
 const f=fixture({withZero:false});await f.button('Stap toevoegen').fire('click');assert.equal(f.box.dataset.unsaved,'true');assert.equal(f.timers.size,1);assert.equal(f.calls.length,0);
});
test('a known publication remains confirmed when the consumer refresh fails and is not sent again',async()=>{
 const f=fixture({onSaved:()=>{throw Error('RAW_PRIVATE_REFRESH_FAILURE');}});f.valid();await f.box.fire('submit');assert.equal(f.saved.length,1);assert.equal(f.notice().textContent,f.i.t('workflow.editor.published_refresh'));assert.equal(f.box.dataset.unsaved,'false');const count=f.calls.length;await f.box.fire('submit');assert.equal(f.calls.length,count);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,1);assert.equal(f.counts().effects,0);
});
test('pending and retired publication controls cannot duplicate a write or release late saved callbacks',async()=>{
 const f=fixture();f.valid();const release=f.hold('PUBLISH'),pending=f.box.fire('submit');await release.started;const count=f.calls.length,notice=f.notice().textContent;await f.box.fire('submit');await f.button('Concept nu bewaren').fire('click');await f.button('Concept met ZERO voorbereiden').fire('click');assert.equal(f.calls.length,count);f.retire();release();await pending;assert.equal(f.saved.length,0);assert.equal(f.notice().textContent,notice);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,1);assert.equal(f.counts().effects,0);
});
test('a late ZERO save cannot adopt a revision or release confirmed feedback into a retired editor',async()=>{
 const f=fixture();await prepared(f);const release=f.hold('SAVE'),pending=f.button('Bevestig concept bewaren via ZERO').fire('click');await release.started;const count=f.calls.length,notice=f.notice().textContent;await f.button('Bevestig concept bewaren via ZERO').fire('click');assert.equal(f.calls.length,count);f.retire();release();await pending;assert.equal(f.notice().textContent,notice);assert.equal(f.box.dataset.unsaved,'true');assert.equal(f.records()[0].revision,2);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);
});
