'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workspace-domain-fixture'),{locales}=require('../foundly-i18n');
test('shared domain form labels and owned status choices follow eight locales without replacing drafts or canonical values',async()=>{
 const f=await fixture(),form=f.form();assert.ok(form);f.field('title').value='Literal private opportunity';f.field('status').value='OPEN';f.field('value_cents').value='123.45';const calls=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.ok(f.form()===form);assert.equal(f.field('title').value,'Literal private opportunity');assert.equal(f.field('status').value,'OPEN');assert.equal(f.field('value_cents').value,'123.45');assert.ok(form.textContent.includes(f.i.t('workspace.page.domain_field.title')));assert.equal(f.field('status').options.find(n=>n.value==='OPEN').textContent,f.i.t('workspace.page.domain_status.open'));assert.equal(f.calls.length,calls);assert.equal(f.i.missingKeys().length,0);}
});
test('old domain list and schema observations cannot overwrite a newer view of the same entity or another module',async()=>{
 const f=await fixture({start:false}),route='/api/sales/opportunities?limit=100',release=f.hold(route),old=f.render();await release.started;f.core.save(f.ctx,f.actor,'opportunities',{title:'New current record'});await f.render();release();await old;assert.ok(f.content.textContent.includes('New current record'));
 const g=await fixture({start:false}),held=g.hold('/api/sales/schema'),read=g.render();await held.started;g.ui.state.workspaceId='procurement';g.content.textContent='Current procurement screen';held();await read;assert.equal(g.content.textContent,'Current procurement screen');
});
test('malformed domain list or schema never becomes an empty state or editable success',async()=>{
 for(const [route,value]of [['/api/sales/opportunities?limit=100',{ok:true}],['/api/sales/opportunities?limit=100',{ok:false,items:[],total:0,next_offset:null}],['/api/sales/schema',{ok:true,module_id:'marketing',entities:['opportunities'],required_fields:{},industry_fields:{fields:[]}}]]){const f=await fixture({start:false});f.overrides.set('GET '+route,value);await f.render();assert.ok(f.form()===null);assert.ok(!f.content.textContent.includes(f.i.t('workspace.page.domain_empty')));}
});
test('a lost native create acknowledgement keeps its exact request key and body and suppresses duplicate submissions',async()=>{
 const f=await fixture(),form=f.form();f.field('title').value='Literal exactly once';const release=f.hold('/api/sales/opportunities','POST');f.lose();const write=form.fire('submit');await release.started;await form.fire('submit');assert.equal(f.writes().length,1);release();await write;assert.equal(f.core.list(f.ctx,f.actor,'opportunities').total,1);f.field('title').value='Do not substitute';for(const locale of locales)f.i.setLocale(locale);await form.fire('submit');assert.equal(f.writes().length,2);assert.equal(f.writes()[0].key,f.writes()[1].key);assert.deepEqual(f.writes()[0].input,f.writes()[1].input);assert.equal(f.core.list(f.ctx,f.actor,'opportunities').total,1);
});
test('a malformed domain write acknowledgement retains its draft and never shows saved success',async()=>{
 const f=await fixture(),form=f.form();f.field('title').value='Retained literal draft';f.overrides.set('POST /api/sales/opportunities',{ok:true});await form.fire('submit');assert.ok(f.form()===form);assert.equal(f.field('title').value,'Retained literal draft');assert.equal(f.nodes.toastRegion.textContent,'');
});
test('a retired domain editor cannot send a mutation into the newly selected module',async()=>{
 const f=await fixture(),form=f.form();f.field('title').value='Must remain unsent';f.ui.state.workspaceId='procurement';await form.fire('submit');assert.equal(f.writes().length,0);
});
test('a lost update retries the original revision through a new view and cannot claim a later separate update',async()=>{
 const f=await fixture();const initial=f.core.save(f.ctx,f.actor,'opportunities',{title:'Literal original record'}).record;await f.render();await f.edit().fire('click');f.field('title').value='Literal reviewed update';f.lose();await f.form().fire('submit');assert.equal(f.core.get(f.ctx,f.actor,'opportunities',initial.id).revision,2);await f.render();const form=f.form();assert.equal(f.field('title').value,'Literal reviewed update');await form.fire('submit');assert.equal(f.writes().length,2);assert.equal(f.writes()[0].key,f.writes()[1].key);assert.deepEqual(f.writes()[0].input,f.writes()[1].input);assert.equal(f.core.get(f.ctx,f.actor,'opportunities',initial.id).revision,2);assert.equal(f.adapter.bucket(f.ctx,'sales:outbox').length,2);assert.equal(form.querySelector('button').disabled,true);
 const g=await fixture();const record=g.core.save(g.ctx,g.actor,'opportunities',{title:'Initial separate record'}).record;await g.render();await g.edit().fire('click');g.field('title').value='Attempted retained update';g.lose();await g.form().fire('submit');g.core.save(g.ctx,g.actor,'opportunities',{title:'Newer separate change'},{id:record.id,expected_revision:2});await g.form().fire('submit');assert.equal(g.core.get(g.ctx,g.actor,'opportunities',record.id).title,'Newer separate change');assert.equal(g.nodes.toastRegion.textContent,'');assert.equal(g.form().querySelector('button').disabled,true);
});
test('calendar recurrence choices keep canonical values, duration, participants and explicit time offsets through locale changes',async()=>{
 const f=await fixture({workspaceId:'calendar',entity:'events'});assert.ok(f.form());f.field('title').value='Literal calendar appointment';f.field('start_at').value='2026-10-24T10:00:00+02:00';f.field('end_at').value='2026-10-24T11:00:00+02:00';f.field('timezone').value='Europe/Amsterdam';f.field('participants').value='alice,bob';f.field('recurrence_frequency').value='DAILY';await f.field('recurrence_frequency').fire('change');f.field('recurrence_count').value='3';
 const form=f.form(),calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.ok(f.form()===form);assert.equal(f.field('recurrence_frequency').value,'DAILY');assert.equal(f.field('start_at').value,'2026-10-24T10:00:00+02:00');assert.ok(form.textContent.includes(f.i.t('workspace.page.domain_recurrence')));assert.equal(f.i.missingKeys().length,0);}assert.equal(f.calls.length,calls);await form.fire('submit');const rows=f.core.list(f.ctx,f.actor,'events').items;assert.equal(rows.length,1);assert.deepEqual(rows[0].recurrence,{frequency:'DAILY',interval:1,count:3});assert.deepEqual(rows[0].participants,['alice','bob']);assert.equal(rows[0].start_at,'2026-10-24T10:00:00+02:00');const series=require('../business-domains').occurrences(rows[0]);assert.equal(series[0].start_at,'2026-10-24T08:00:00.000Z');assert.equal(series[1].start_at,'2026-10-25T09:00:00.000Z');assert.equal(Date.parse(series[1].end_at)-Date.parse(series[1].start_at),3600000);
});
test('procurement quotation lines and canonical supplier choices survive translation and local malformed input sends no write',async()=>{
 const f=await fixture({workspaceId:'procurement',entity:'rfqs'});f.field('title').value='Literal request';f.field('currency').value='EUR';f.field('lines').value='PART_A | Literal description | 3';for(const locale of locales){f.i.setLocale(locale);assert.ok(f.field('lines').getAttribute('placeholder').includes('|'));assert.equal(f.field('lines').value,'PART_A | Literal description | 3');assert.equal(f.i.missingKeys().length,0);}await f.form().fire('submit');const request=f.core.list(f.ctx,f.actor,'rfqs').items[0];assert.ok(request);assert.deepEqual(request.lines,[{item_id:'PART_A',description:'Literal description',quantity:3}]);
 const g=await fixture({workspaceId:'procurement',entity:'rfqs'});g.field('title').value='Must not be sent';g.field('currency').value='EUR';g.field('lines').value='malformed';await g.form().fire('submit');assert.equal(g.writes().length,0);for(const locale of locales){g.i.setLocale(locale);assert.ok(g.form().textContent.includes(g.i.t('workspace.page.domain_rfq_help')));}
 const h=await fixture({workspaceId:'procurement',entity:'bids',start:false}),rfq=h.core.save(h.ctx,h.actor,'rfqs',{title:'Literal request choice',currency:'EUR',lines:[{item_id:'P1',description:'Literal item',quantity:2}]}).record,supplier=h.core.save(h.ctx,h.actor,'suppliers',{name:'Literal supplier choice'}).record;await h.render();h.field('rfq_id').value=rfq.id;await h.field('rfq_id').fire('change');h.field('supplier_id').value=supplier.id;h.field('title').value='Literal bid';h.field('evidence_reference').value='Literal reviewed bid reference';h.field('lines').value='P1 | 2 | 19.99 | 3';for(const locale of locales){h.i.setLocale(locale);assert.equal(h.field('rfq_id').value,rfq.id);assert.equal(h.field('supplier_id').value,supplier.id);assert.equal(h.field('rfq_revision').value,'1');assert.ok(h.form().textContent.includes('Literal supplier choice'));assert.equal(h.i.missingKeys().length,0);}await h.form().fire('submit');assert.equal(h.core.list(h.ctx,h.actor,'bids').items[0].lines[0].unit_price_cents,1999);
});
test('industry draft fields are included when controls lock for submission and saved package values remain intact',async()=>{
 const f=await fixture({industry:'AUTOMOTIVE'}),industryInputs=f.form().querySelectorAll('input').filter(n=>n.name.startsWith('industry_'));assert.ok(industryInputs.length);f.field('title').value='Literal automotive opportunity';const target=industryInputs.find(n=>n.type==='text');assert.ok(target);target.value='Literal industry value';for(const locale of locales)f.i.setLocale(locale);await f.form().fire('submit');const saved=f.core.list(f.ctx,f.actor,'opportunities').items[0];assert.equal(saved.industry_fields[target.name.slice(9)],'Literal industry value');assert.equal(saved.industry_field_pack_id,'AUTOMOTIVE');
});
