'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),crypto=require('node:crypto');
const {fixture}=require('../zero-evaluation/fixture'),{fixture:client}=require('../zero-evaluation/workflow-activation-fixture');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function init(f){assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);}
async function setup(f,cookie=null){const w=await f.request('/api/automation/workflows','POST',{name:'Private HTTP activation',trigger:'custom_event',actions:[{type:'notify',message:'Private exact notification'}]},cookie);assert.equal(w.status,201);return w.body;}
function review(workflow){const body={active:true,confirm:true,expected_revision:0,reason:'Private exact HTTP activation reason',request_id:crypto.randomUUID()};return {body,meta:{request_id:body.request_id,request_fingerprint:hash(body),workflow_id:workflow.id,workflow_signature:workflow.signature,expected_revision:0,active:true,confirm:true}};}
test('actual activation controls recover a lost HTTP reply after encrypted restart without another activation revision',async()=>{
 const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-activation-ack-drop')});try{
  await init(f);const owner=await f.enroll('activation.http.owner',['ADMIN']),workflow=await setup(f,owner.cookie),realm=(await f.request('/api/automation/workflows','GET',undefined,owner.cookie)).body.request_context;let drop=true;
  const transport=async(route,options)=>{const headers=drop&&route.endsWith('/activation')&&options.method==='PUT'?{'x-workflow-activation-drop-reply':'isolated-http-fixture'}:{};if(headers['x-workflow-activation-drop-reply'])drop=false;const r=await f.request(route,options.method||'GET',options.body?JSON.parse(options.body):undefined,owner.cookie,headers);if(r.status!==200)throw Object.assign(Error('HTTP activation rejected'),{status:r.status,code:r.body.code});return r.body;};
  const first=client({workflow,ctx:{tenant_id:realm.tenant_id,dealer_id:realm.dealer_id},actor:{id:realm.actor_id,roles:['ADMIN']}});first.transport=transport;await first.render('WORKFLOWS');await first.choose('pause');assert.equal(first.storage.size,1);const retained=JSON.parse([...first.storage.values()][0])[0];let status=(await f.request('/api/automation/status')).body;assert.equal(status.workflows[0].activation_revision,1);assert.equal(status.workflows[0].effective_enabled,false);const events=(await f.request('/api/automation/export')).body.collections.automation_activations;assert.equal(events.length,1);first.retire();await f.stop();await f.start();owner.cookie=await f.login(owner);
  const fresh=client({workflow,ctx:{tenant_id:realm.tenant_id,dealer_id:realm.dealer_id},actor:{id:realm.actor_id,roles:['ADMIN']},storage:first.storage});fresh.transport=transport;await fresh.render('WORKFLOWS');await fresh.control('recover').fire('click');assert.equal(fresh.storage.size,0);assert.ok(fresh.content.textContent.includes(fresh.i.t('workflow.activation.pause_saved')));assert.deepEqual((await f.request('/api/automation/export')).body.collections.automation_activations,events);assert.equal((await f.request('/api/automation/status')).body.runs.length,0);assert.ok(!fs.readFileSync(path.join(f.dir,'foundly-core-state.json'),'utf8').includes('Private exact activation reason'));assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],capability_flags:{'automation:workflows':false},expected_revision:1})).status,200);assert.equal((await f.request('/api/automation/activation-requests/recover','POST',{...retained,confirm:true},owner.cookie)).status,403);
 }finally{await f.close();}
});
test('activation terminal retirement blocks a held original body through encrypted restart and keeps private metadata out of Data',async()=>{
 const f=await fixture();let held;try{
  await init(f);const workflow=await setup(f),r=review(workflow),route='/api/automation/workflows/'+workflow.id+'/activation',payload=JSON.stringify(r.body),pending=new Promise((resolve,reject)=>{held=http.request(f.base+route,{method:'PUT',headers:{authorization:'Bearer '+f.env.FOUNDLY_ADMIN_TOKEN,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload)}},res=>{let value='';res.on('data',part=>value+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(value)}));});held.on('error',reject);held.write(payload.slice(0,-1));});
  const closed=await f.request('/api/automation/activation-requests/recover','POST',r.meta);assert.equal(closed.status,200);assert.equal(closed.body.state,'NOT_APPLIED');held.end(payload.slice(-1));const late=await pending;assert.equal(late.status,409);assert.equal(late.body.code,'automation_activation_request_abandoned');await f.stop();await f.start();assert.deepEqual((await f.request('/api/automation/activation-requests/recover','POST',r.meta)).body,closed.body);assert.equal((await f.request(route,'PUT',r.body)).status,409);assert.equal((await f.request('/api/automation/status')).body.workflows[0].activation_revision,0);assert.ok(!JSON.stringify((await f.request('/api/module/data/data')).body).includes(r.meta.request_id));
 }finally{held?.destroy();await f.close();}
});
test('activation and receipt roll back on EIO and current authority is rechecked after a held authenticated body',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'activation-http-integrity-')),fault=path.join(dir,'fault'),barrier=path.join(dir,'body'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/identity-persistence-fault')+' --require '+require.resolve('../test-identity-body-barrier'),FOUNDLY_IDENTITY_FAIL_FILE:fault,FOUNDLY_IDENTITY_BODY_BARRIER:barrier});let held;try{
  await init(f);const owner=await f.enroll('activation.current.owner',['MANAGER']),workflow=await setup(f,owner.cookie),r=review(workflow),route='/api/automation/workflows/'+workflow.id+'/activation';fs.writeFileSync(fault,'fail');try{assert.equal((await f.request(route,'PUT',r.body,owner.cookie)).status,500);}finally{fs.rmSync(fault,{force:true});}assert.equal((await f.request('/api/automation/status')).body.workflows[0].activation_revision,0);assert.equal((await f.request('/api/automation/activation-requests/recover','POST',r.meta,owner.cookie)).body.state,'NOT_APPLIED');
  const next=review(workflow),payload=JSON.stringify(next.body),pending=new Promise((resolve,reject)=>{held=http.request(f.base+route,{method:'PUT',headers:{cookie:owner.cookie,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload),'x-identity-fixture-barrier':'body'}},res=>{let value='';res.on('data',part=>value+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(value)}));});held.on('error',reject);held.write(payload.slice(0,-1));});for(let n=0;n<100&&!fs.existsSync(barrier);n++)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(barrier));assert.equal((await f.request('/api/identity/users/'+owner.member.id,'PUT',{roles:['VIEWER'],expected_revision:owner.member.revision,confirm:true,reason:'Remove activation authority during held request'})).status,200);held.end(payload.slice(-1));assert.equal((await pending).status,401);owner.cookie=await f.login(owner);assert.equal((await f.request(route,'PUT',next.body,owner.cookie)).status,403);assert.equal((await f.request('/api/automation/activation-requests/recover','POST',next.meta,owner.cookie)).status,403);assert.equal((await f.request('/api/automation/status')).body.workflows[0].activation_revision,0);
 }finally{held?.destroy();fs.rmSync(fault,{force:true});await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
