'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{FoundlyPlatformCore}=require('../platform-core');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
function fixture(){let rows=new Map(),disk,broken=false;const ctx={tenant_id:'activation-request',dealer_id:'default'},actor={id:'owner',roles:['MANAGER']},adapter={bucket(c,s){const k=JSON.stringify([c,s]);if(!rows.has(k))rows.set(k,[]);return rows.get(k);},persist(){if(broken)throw Object.assign(Error('Fixture storage failure'),{code:'EIO'});disk=JSON.stringify([...rows]);}};let core=new FoundlyPlatformCore(adapter);const workflow=core.defineAutomation(ctx,actor,{name:'Private native activation',trigger:'custom_event',actions:[{type:'notify'}]}),input={active:true,expected_revision:0,confirm:true,reason:'Private reviewed activation',request_id:'activation-exact-reference'},meta={request_id:input.request_id,request_fingerprint:hash(input),workflow_id:workflow.id,workflow_signature:workflow.signature,expected_revision:0,active:true,confirm:true};return {get core(){return core;},ctx,actor,workflow,input,meta,send:(body=input,principal=actor)=>core.setAutomationActivation(ctx,principal,workflow.id,body),fail:value=>broken=value,restart(){rows=new Map(JSON.parse(disk));core=new FoundlyPlatformCore(adapter);},current:()=>core.automationStatus(ctx,actor).workflows.find(w=>w.id===workflow.id)};}
test('an activation request identity cannot be reused for an opposite choice or newer revision',()=>{const f=fixture();f.send();assert.throws(()=>f.send({...f.input,active:false,expected_revision:1}),{code:'automation_activation_request_conflict'});assert.equal(f.current().effective_enabled,true);assert.equal(f.current().activation_revision,1);});
test('activation recovery returns the original exact result after restart without creating another event',()=>{const f=fixture(),first=f.send();assert.ok(first.request_acknowledgement);f.restart();const events=JSON.stringify(f.core.bucket(f.ctx,'raw_events')),recovered=f.core.recoverAutomationActivationRequest(f.ctx,f.actor,f.meta);assert.equal(recovered.state,'APPLIED');assert.equal(recovered.activation_performed,false);assert.equal(recovered.activation.revision,1);assert.equal(recovered.activation.active_workflow_id,f.workflow.id);assert.equal(JSON.stringify(f.core.bucket(f.ctx,'raw_events')),events);});
test('superseded activation recovery cannot report the old version as currently active or overwrite a newer pause',()=>{const f=fixture();f.send();f.send({...f.input,request_id:'activation-new-pause',expected_revision:1,active:false});const recovered=f.core.recoverAutomationActivationRequest(f.ctx,f.actor,f.meta);assert.equal(recovered.state,'SUPERSEDED');assert.equal(recovered.activation,null);assert.equal(f.current().effective_enabled,false);assert.equal(f.current().activation_revision,2);assert.throws(()=>f.send(),{code:'automation_activation_request_superseded'});});
test('terminal retirement rejects delayed activation after restart while EIO closure leaves no partial request',()=>{const f=fixture();f.fail(true);assert.throws(()=>f.core.recoverAutomationActivationRequest(f.ctx,f.actor,f.meta),{code:'EIO'});f.fail(false);const closed=f.core.recoverAutomationActivationRequest(f.ctx,f.actor,f.meta);assert.equal(closed.state,'NOT_APPLIED');assert.equal(f.current().activation_revision,0);f.restart();assert.deepEqual(f.core.recoverAutomationActivationRequest(f.ctx,f.actor,f.meta),closed);assert.throws(()=>f.send(),{code:'automation_activation_request_abandoned'});assert.equal(f.current().activation_revision,0);});
test('activation and acknowledgement roll back together on storage failure and current owner is checked before replay',()=>{const f=fixture();f.fail(true);assert.throws(()=>f.send(),{code:'EIO'});f.fail(false);assert.equal(f.current().activation_revision,0);const first=f.send();assert.equal(first.revision,1);assert.throws(()=>f.send(f.input,{id:'other-owner',roles:['MANAGER']}),{code:'automation_activation_forbidden'});assert.throws(()=>f.core.recoverAutomationActivationRequest(f.ctx,{id:'other-owner',roles:['MANAGER']},f.meta),{code:'automation_activation_forbidden'});});
test('contradictory persisted activation cannot be presented as either current success or a newer choice',()=>{for(const mutate of [row=>row.request_signature='f'.repeat(64),row=>row.reason='Forged reason',row=>row.active_workflow_id='other-workflow',row=>row.revision=0]){const f=fixture();f.send();mutate(f.core.bucket(f.ctx,'automation_activations')[0]);assert.throws(()=>f.core.recoverAutomationActivationRequest(f.ctx,f.actor,f.meta),{code:'automation_activation_request_unverifiable'});}});
