'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workspace-domain-fixture');
const recover=f=>f.content.querySelectorAll('button').find(button=>button.getAttribute('data-domain-action')==='recover');
test('a fresh controller recovers a committed domain request without persisting its private draft or repeating the mutation',async()=>{
 const f=await fixture();f.field('title').value='Literal private lost title';f.field('description').value='Private description stays out of storage';f.lose();await f.form().fire('submit');assert.equal(f.saved.size,1);const metadata=[...f.saved.values()].join('');assert.ok(!metadata.includes('Literal'));assert.ok(!metadata.includes('Private'));const retained=new Map(f.saved),g=await fixture({shared:f,storage:f.saved});assert.ok(recover(g));assert.equal(g.form().querySelector('button').disabled,true);await recover(g).fire('click');assert.equal(g.writes().filter(row=>row.route==='/api/sales/opportunities').length,0);assert.equal(g.saved.size,0);assert.equal(g.core.list(g.ctx,g.actor,'opportunities').total,1);assert.ok(g.content.textContent.includes(g.i.t('workspace.page.domain_saved')));
 const h=await fixture({shared:f,storage:retained,start:false});h.actor.id='different_identity';await h.render();assert.equal(recover(h),undefined);assert.equal(h.saved.size,1);
});
test('an uncommitted request after reload is durably closed before a fresh record request can be made',async()=>{
 const f=await fixture();f.field('title').value='Literal absent request';f.overrides.set('POST /api/sales/opportunities',{});await f.form().fire('submit');const first=f.writes()[0];assert.equal(f.saved.size,1);const g=await fixture({shared:f,storage:f.saved});await recover(g).fire('click');assert.equal(g.saved.size,0);assert.equal(g.core.list(g.ctx,g.actor,'opportunities').total,0);assert.ok(g.content.textContent.includes(g.i.t('workspace.page.domain_not_applied')));assert.throws(()=>g.core.save(g.ctx,g.actor,'opportunities',first.input,{idempotency_key:first.key}),{code:'record_request_abandoned'});await g.render();g.field('title').value='Explicit fresh record';await g.form().fire('submit');assert.equal(g.core.list(g.ctx,g.actor,'opportunities').total,1);
});
test('unavailable or malformed session recovery metadata blocks new effects and remains preserved',async()=>{
 const f=await fixture();f.context.sessionStorage.setItem=()=>{throw Error('Storage unavailable');};f.field('title').value='Must not be sent';await f.form().fire('submit');assert.equal(f.writes().length,0);
 const g=await fixture();g.field('title').value='Recovery fixture';g.lose();await g.form().fire('submit');const key=[...g.saved.keys()][0];g.saved.set(key,'{"malformed":true}');const h=await fixture({shared:g,storage:g.saved});assert.equal(h.form().querySelector('button').disabled,true);await h.form().fire('submit');assert.equal(h.writes().length,0);assert.equal(h.saved.get(key),'{"malformed":true}');
});
test('recovery rejects a forged realm, retires late observations and permits unrelated new work after access to an applied result is lost',async()=>{
 const f=await fixture();f.field('title').value='Private former-owner record';f.lose();await f.form().fire('submit');const pending=JSON.parse([...f.saved.values()][0]),route='/api/sales/record-requests/'+pending.key+'/recover',g=await fixture({shared:f,storage:f.saved});g.overrides.set('POST '+route,{ok:true,request_id:pending.key,state:'NOT_APPLIED',entity:'opportunities',target_id:null,expected_revision:0,tenant_id:'forged',dealer_id:g.ctx.dealer_id,actor_id:g.actor.id});await recover(g).fire('click');assert.equal(g.saved.size,1);assert.equal(g.form().querySelector('button').disabled,true);g.overrides.delete('POST '+route);const release=g.hold(route,'POST'),request=recover(g).fire('click');await release.started;g.ui.state.activeSection='OTHER';g.content.textContent='Current unrelated section';release();await request;assert.equal(g.content.textContent,'Current unrelated section');assert.equal(g.saved.size,1);
 const record=f.core.list(f.ctx,f.actor,'opportunities').items[0];f.core.save(f.ctx,f.actor,'opportunities',{owner_id:'another_owner'},{id:record.id,expected_revision:1});const h=await fixture({shared:f,storage:f.saved,start:false});h.actor.roles=['SALES'];await h.render();await recover(h).fire('click');assert.equal(h.saved.size,0);assert.ok(!h.content.textContent.includes('Private former-owner record'));await h.render();h.field('title').value='New independently permitted record';await h.form().fire('submit');assert.equal(h.core.list(h.ctx,h.actor,'opportunities').total,1);
});
