'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{fixture}=require('../zero-evaluation/fixture');
const draft={name:'Literal private recoverable workflow',version:1,trigger_type:'custom_event',automatic:false,approval_required:true,steps:[{type:'create_task',values:{title:'Literal private reviewed task'}}]};
function body(id,operation,input){return {message:'Isolated explicit draft '+operation,conversation_id:'recover-draft-conversation',turn_id:crypto.randomUUID(),preferred_module:'automation',client_context:{automation_action:{operation,draft_id:id,input}}};}
async function preview(f,id,cookie=null){const result=await f.request('/api/zero/turn','POST',body(id,'PREVIEW',{draft,expected_revision:0}),cookie);assert.equal(result.status,200,JSON.stringify(result.body));return result.body.automation_data.preview_fingerprint;}
const review=fingerprint=>({expected_revision:0,preview_fingerprint:fingerprint,confirm:true});
const saveBody=(id,fingerprint)=>body(id,'SAVE',{draft,...review(fingerprint),reason:'Explicit isolated confirmation'});
test('an actually dropped ZERO save response recovers its native draft and preview reference after encrypted restart without publication or duplicate writes',async()=>{
 const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-draft-ack-drop')});try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const id='http-recovered-draft',fingerprint=await preview(f,id),input=saveBody(id,fingerprint);let lost=false;try{await f.request('/api/zero/turn','POST',input,null,{'x-zero-draft-drop-reply':'isolated-http-fixture'});}catch{lost=true;}assert.equal(lost,true);assert.equal((await f.request('/api/automation/drafts')).body.items.length,1);
  await f.stop();await f.start();const result=await f.request('/api/automation/drafts/'+id+'/recover','POST',review(fingerprint));assert.equal(result.status,200,JSON.stringify(result.body));assert.equal(result.body.state,'APPLIED');assert.equal(result.body.preview_fingerprint,fingerprint);assert.deepEqual(result.body.request_context,{tenant_id:'zero-evaluation',dealer_id:'default',actor_id:'evaluation-bootstrap'});assert.equal(result.body.record.id,id);assert.equal(result.body.record.revision,1);assert.equal((await f.request('/api/zero/turn','POST',input)).body.automation_data.record.revision,1);assert.equal((await f.request('/api/automation/drafts')).body.items.length,1);assert.equal((await f.request('/api/automation/status')).body.workflow_count,0);assert.equal((await f.request('/api/automation/tasks')).body.total,0);
  const generic=await f.request('/api/module/data/data');assert.equal(generic.status,200);assert.ok(!JSON.stringify(generic.body).includes(fingerprint));const disk=fs.readFileSync(path.join(f.dir,'foundly-core-state.json'),'utf8');assert.ok(!disk.includes(draft.name));assert.ok(!disk.includes(fingerprint));
  assert.equal((await f.request('/api/automation/drafts/'+id+'/recover','POST',review('f'.repeat(64)))).status,409);assert.equal((await f.request('/api/automation/drafts/'+id,'PUT',{draft:{...draft,name:'Newer retained private draft'},expected_revision:1})).status,200);assert.equal((await f.request('/api/automation/drafts/'+id+'/recover','POST',review(fingerprint))).body.code,'workflow_draft_request_superseded');
 }finally{await f.close();}
});
test('terminal draft recovery rolls back failed persistence and blocks a real original ZERO body arriving after closure, including restart',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'draft-terminal-fault-')),marker=path.join(dir,'fail'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/identity-persistence-fault'),FOUNDLY_IDENTITY_FAIL_FILE:marker});let held;try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const id='http-closed-draft',fingerprint=await preview(f,id),route='/api/automation/drafts/'+id+'/recover',payload=JSON.stringify(saveBody(id,fingerprint));fs.writeFileSync(marker,'fail');try{assert.equal((await f.request(route,'POST',review(fingerprint))).status,500);}finally{fs.rmSync(marker,{force:true});}
  const pending=new Promise((resolve,reject)=>{held=require('node:http').request(f.base+'/api/zero/turn',{method:'POST',headers:{authorization:'Bearer '+f.env.FOUNDLY_ADMIN_TOKEN,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload)}},res=>{let text='';res.on('data',part=>text+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}));});held.on('error',reject);held.flushHeaders();held.write(payload.slice(0,-1));});
  const closed=await f.request(route,'POST',review(fingerprint));assert.equal(closed.status,200,JSON.stringify(closed.body));assert.equal(closed.body.state,'NOT_APPLIED');held.end(payload.slice(-1));const late=await pending;assert.equal(late.status,409,JSON.stringify(late.body));assert.equal(late.body.code,'workflow_draft_request_abandoned');assert.equal((await f.request('/api/automation/drafts')).body.items.length,0);await f.stop();await f.start();assert.deepEqual((await f.request(route,'POST',review(fingerprint))).body,closed.body);assert.equal((await f.request('/api/automation/status')).body.workflow_count,0);
 }finally{held?.destroy();fs.rmSync(marker,{force:true});await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('current member authority is checked after the recovery body wait; another owner cannot retrieve a private draft receipt',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'draft-body-wait-')),marker=path.join(dir,'body'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../test-identity-body-barrier'),FOUNDLY_IDENTITY_BODY_BARRIER:marker});let held;try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('draft.recovery.owner',['ADMIN']),other=await f.enroll('draft.recovery.other',['ADMIN']),id='member-owned-draft',fingerprint=await preview(f,id,owner.cookie);assert.equal((await f.request('/api/zero/turn','POST',saveBody(id,fingerprint),owner.cookie)).status,200);const route='/api/automation/drafts/'+id+'/recover';assert.equal((await f.request(route,'POST',review(fingerprint),other.cookie)).status,404);
  const payload=JSON.stringify(review(fingerprint));const pending=new Promise((resolve,reject)=>{held=require('node:http').request(f.base+route,{method:'POST',headers:{cookie:owner.cookie,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload),'x-identity-fixture-barrier':'body'}},res=>{let text='';res.on('data',part=>text+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}));});held.on('error',reject);held.write(payload.slice(0,-1));});
  for(let n=0;n<100&&!fs.existsSync(marker);n++)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(marker));assert.equal((await f.request('/api/identity/users/'+owner.member.id,'PUT',{roles:['VIEWER'],expected_revision:owner.member.revision,confirm:true,reason:'Revoke member during authenticated recovery body'})).status,200);held.end(payload.slice(-1));const denied=await pending;assert.equal(denied.status,401);assert.ok(!JSON.stringify(denied.body).includes(draft.name));owner.cookie=await f.login(owner);assert.equal((await f.request(route,'POST',review(fingerprint),owner.cookie)).status,403);
 }finally{held?.destroy();await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
