'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/fixture'),{fixture:page}=require('../zero-evaluation/automation-page-fixture'),{WorkspaceView}=require('../zero-evaluation/workspace-page-fixture'),{locales}=require('../foundly-i18n');
test('the actual shared chooser reads native member drafts and templates, preserves locale state, and retires a held response after current capability denial',async()=>{const server=await fixture();try{
 assert.equal((await server.request('/api/composition','PUT',{entitlements:['automation'],industry_id:'AUTOMOTIVE',expected_revision:0})).status,200);const owner=await server.enroll('chooser.native.owner'),input={name:'  Literal native draft name  ',version:'1',trigger_type:'custom_event',automatic:false,approval_required:false,steps:[{type:'create_task',values:{title:'Literal private task title'}}]},saved=await server.request('/api/automation/drafts/native_choice','PUT',{draft:input,expected_revision:0,request_id:'initial_native_choice'},owner.cookie);assert.equal(saved.status,200);
 const f=page(),calls=[];f.nodes.contextContent=f.content;f.nodes.body=f.context.document.body=new WorkspaceView('body');let held=false,release,started;const gate=new Promise(resolve=>release=resolve),began=new Promise(resolve=>started=resolve);
 f.context.fetch=async(route,options={})=>{calls.push({route,options});const response=await server.request(route,options.method||'GET',options.body?JSON.parse(options.body):undefined,owner.cookie);if(held&&route.startsWith('/api/composition/industry-presets')){held=false;started();await gate;}return {ok:response.status>=200&&response.status<300,status:response.status,json:async()=>response.body};};
 const control=key=>f.content.all().find(n=>n.getAttribute?.('data-draft-choice')===key),editor=()=>f.content.all().find(n=>n.tag==='form'&&n.className.includes('workflow-editor'));
 await f.render('WORKFLOWS');const chooser=control('select');chooser.value='native_choice';await control('open').fire('click');const form=editor(),name=form.all().find(n=>n.tag==='input'),before=calls.length;assert.equal(name.value,saved.body.record.draft.name);for(const locale of locales){f.i.setLocale(locale);assert.equal(control('select'),chooser);assert.equal(chooser.value,'native_choice');assert.equal(editor(),form);assert.equal(name.value,saved.body.record.draft.name);}assert.equal(calls.length,before);
 await control('template').fire('click');let dialog=f.nodes.body.all().find(n=>n.tag==='dialog');assert.ok(dialog?.open,JSON.stringify({notices:f.content.all().filter(n=>n.tag==='output').map(n=>n.textContent),toast:f.nodes.toastRegion.textContent}));assert.ok(dialog.textContent.includes('Voertuigbeoordeling opvolgen'));await dialog.all().find(n=>n.tag==='button'&&n.type==='button').fire('click');assert.equal((await server.request('/api/automation/workflows')).body.workflow_count,0);assert.equal((await server.request('/api/automation/drafts','GET',undefined,owner.cookie)).body.items[0].revision,1);
 held=true;const pending=control('template').fire('click');await began;assert.equal((await server.request('/api/composition','PUT',{entitlements:['automation'],capability_flags:{'automation:workflows':false},expected_revision:1})).status,200);await f.render('WORKFLOWS');release();await pending;assert.equal(f.nodes.body.all().find(n=>n.tag==='dialog'),undefined);assert.ok(!f.content.textContent.includes('Literal private'));assert.ok(!calls.some(c=>['POST','PUT'].includes(c.options.method)));
 }finally{await server.close();}});
