'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{FoundlyPlatformCore}=require('../platform-core'),{signature}=require('../workflow-execution');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
function fixture(actions=[{type:'delay',seconds:1},{type:'create_document',title:'Private request outcome',content:'Private line one\nPrivate line two'}],approval=false){
 const rows=new Map(),ctx={tenant_id:'run-request-fixture',dealer_id:'default'},actor={id:'run-request-owner',roles:['ADMIN','SUPER_ADMIN']};let now=Date.parse('2026-01-01T00:00:00Z'),writes=0,effects=0,fail=false,retry=false;
 const adapter={bucket(c,s){const key=JSON.stringify([c,s]);if(!rows.has(key))rows.set(key,[]);return rows.get(key);},now:()=>new Date(now),persist(){if(fail){fail=false;throw Object.assign(Error('Isolated persistence fault'),{code:'EIO'});}writes++;},audit(){},automationActionContract:()=>({idempotent:true}),executeAutomationAction(){effects++;if(retry){retry=false;throw Object.assign(Error('Isolated action retry'),{code:'EIO'});}return {executed:true};}},core=new FoundlyPlatformCore(adapter),workflow=core.defineAutomation(ctx,actor,{name:'Private recovery workflow',trigger:{type:'custom_event',automatic:false},actions,approval_required:approval}),input={event:{event_id:'request-recovery-event',event_version:1},inputs:{literal:'Private request input'},reason:'Private reviewed reason'},meta={request_id:'request-1',request_fingerprint:hash(input),workflow_id:workflow.id,event_id:input.event.event_id,workflow_signature:workflow.signature,request_signature:signature({workflow:workflow.signature,trigger:input.event,inputs:input.inputs})};
 return {core,ctx,actor,workflow,input,meta,submit:(metadata=meta,who=actor,extra={})=>core.runAutomation(ctx,who,workflow.id,input.event,{inputs:input.inputs,request_id:metadata.request_id,request_fingerprint:metadata.request_fingerprint,...extra}),recover:(metadata=meta,who=actor)=>core.recoverAutomationRunRequest(ctx,who,{...metadata,confirm:true}),counts:()=>({writes,effects,runs:core.bucket(ctx,'automation_runs').length,requests:core.bucket(ctx,'automation_run_requests').length}),advance:()=>now+=2000,fail:()=>fail=true,retry:()=>retry=true};
}
test('a keyed retry observes a due waiting run without resuming a later native effect',()=>{
 const f=fixture(),first=f.submit();assert.equal(first.status,'WAITING_TIME');f.advance();const before=f.counts(),again=f.submit();assert.equal(again.run_id,first.run_id);assert.equal(again.status,'WAITING_TIME');assert.equal(again.replayed,true);assert.deepEqual(f.counts(),before);const recovered=f.recover();assert.equal(recovered.state,'APPLIED');assert.equal(recovered.run.run_id,first.run_id);assert.equal(recovered.execution_performed,false);assert.equal(recovered.outcome_reverified,false);assert.deepEqual(f.counts(),before);
});
test('request reconciliation reads current retry and separate approval states without retrying or granting approval',()=>{
 const f=fixture([{type:'create_document',title:'Retried document',content:'Literal',retry:{max_attempts:2,initial_delay_seconds:1}}]);f.retry();assert.equal(f.submit().status,'WAITING_RETRY');f.advance();const before=f.counts();assert.equal(f.recover().run.status,'WAITING_RETRY');assert.equal(f.submit().status,'WAITING_RETRY');assert.deepEqual(f.counts(),before);assert.equal(f.core.runAutomation(f.ctx,f.actor,f.workflow.id,f.input.event,{inputs:f.input.inputs}).status,'SUCCEEDED');assert.equal(f.recover().run.status,'SUCCEEDED');assert.equal(f.counts().effects,2);
 const a=fixture([{type:'create_task',title:'Separate approval'}],true),run=a.submit();assert.equal(run.status,'AWAITING_APPROVAL');assert.equal(a.recover().run.status,'AWAITING_APPROVAL');assert.equal(a.counts().effects,0);assert.throws(()=>a.submit(a.meta,a.actor,{approval:{run_id:run.run_id,request_signature:run.request_signature,reference:'approval',reason:'Explicit separate approval'}}),e=>e.code==='automation_run_request_approval_separate');assert.equal(a.counts().effects,0);
});
test('terminal absent request closure prevents a delayed original key but permits a separately confirmed new request',()=>{
 const f=fixture(),closed=f.recover();assert.equal(closed.state,'NOT_APPLIED');assert.equal(closed.run,null);const before=f.counts();assert.deepEqual(f.recover(),closed);assert.deepEqual(f.counts(),before);assert.throws(()=>f.submit(),e=>e.code==='automation_run_request_abandoned');assert.equal(f.counts().runs,0);assert.equal(f.submit({...f.meta,request_id:'request-2'}).status,'WAITING_TIME');assert.equal(f.counts().runs,1);
});
test('a failed initial run reservation or terminal closure rolls back run, reference and audit together before effects',()=>{
 for(const operation of ['submit','recover']){const f=fixture();const before=f.counts();f.fail();assert.throws(()=>f[operation](),e=>e.code==='EIO');assert.deepEqual(f.counts(),before);assert.equal(f.submit().status,'WAITING_TIME');assert.equal(f.recover().state,'APPLIED');}
});
test('current native authority and actor-isolated references precede private request outcome disclosure',()=>{
 const f=fixture(),run=f.submit(),other={id:'other-admin',roles:['ADMIN','SUPER_ADMIN']},denied={...f.actor,roles:['VIEWER']};assert.throws(()=>f.recover(f.meta,denied),e=>e.statusCode===403);const foreign=f.recover(f.meta,other);assert.equal(foreign.state,'NOT_APPLIED');assert.equal(foreign.run,null);assert.ok(!JSON.stringify(foreign).includes(f.workflow.name));assert.throws(()=>f.submit({...f.meta,request_id:'other-key'},other),e=>e.code==='automation_run_request_forbidden');assert.equal(f.recover().run.run_id,run.run_id);
});
test('metadata conflicts and changed or missing native results remain unverified and cannot create replacement runs',()=>{
 const f=fixture();f.submit();for(const key of ['request_fingerprint','workflow_signature','request_signature'])assert.throws(()=>f.recover({...f.meta,[key]:'a'.repeat(64)}),e=>e.code==='automation_run_request_conflict');const run=f.core.bucket(f.ctx,'automation_runs')[0];run.inputs.literal='Tampered source';assert.throws(()=>f.recover(),e=>e.code==='automation_run_request_unverifiable');f.core.bucket(f.ctx,'automation_runs').length=0;assert.throws(()=>f.recover(),e=>e.code==='automation_run_request_unavailable');assert.throws(()=>f.submit(),e=>e.code==='automation_run_request_unavailable');assert.equal(f.counts().runs,0);
});
test('request capacity and invalid identifiers reject before any native run or effect without evicting recovery references',()=>{
 const f=fixture();assert.throws(()=>f.submit({...f.meta,request_id:'../invalid'}),e=>e.code==='automation_run_request_invalid');const rows=f.core.bucket(f.ctx,'automation_run_requests');for(let n=0;n<10000;n++)rows.push({actor_id:'other',request_id:'retained-'+n});assert.throws(()=>f.submit(),e=>e.code==='automation_run_request_capacity');assert.throws(()=>f.recover(),e=>e.code==='automation_run_request_capacity');assert.equal(rows.length,10000);assert.equal(f.counts().runs,0);assert.equal(f.counts().effects,0);
});
test('attributing a previously keyless native run never resumes it and receipt failure preserves the older run',()=>{
 const f=fixture(),run=f.core.runAutomation(f.ctx,f.actor,f.workflow.id,f.input.event,{inputs:f.input.inputs});f.advance();const before=f.counts();f.fail();assert.throws(()=>f.submit(),e=>e.code==='EIO');assert.deepEqual(f.counts(),before);assert.equal(f.core.bucket(f.ctx,'automation_runs')[0].status,'WAITING_TIME');const attributed=f.submit();assert.equal(attributed.run_id,run.run_id);assert.equal(attributed.status,'WAITING_TIME');assert.equal(f.counts().effects,0);assert.equal(f.recover().run.run_id,run.run_id);
});
test('legacy ZERO callers without a browser request ID also observe the same turn without resuming a due run',()=>{
 const f=fixture(),{CapabilityResolver}=require('../capability-resolver'),{WorkflowDrafts}=require('../workflow-drafts'),zero=require('../workflow-zero'),resolver=new CapabilityResolver(f.core.adapter);resolver.configure(f.ctx,f.actor,{entitlements:['automation'],expected_revision:0});const drafts=new WorkflowDrafts(f.core.adapter,resolver),meta={message:'Explicit legacy ZERO run',conversation_id:'legacy-run-conversation',turn_id:'legacy-run-turn'},preview=zero.execute(drafts,f.core,f.ctx,f.actor,{operation:'RUN_PREVIEW',workflow_id:f.workflow.id,input:{event:f.input.event,inputs:f.input.inputs}},meta).automation_data,action={operation:'RUN_SUBMIT',workflow_id:f.workflow.id,input:{event:f.input.event,inputs:f.input.inputs,preview_fingerprint:preview.preview_fingerprint,confirm:true,reason:'Exact legacy confirmation'}};assert.equal(zero.execute(drafts,f.core,f.ctx,f.actor,action,meta).automation_data.run.status,'WAITING_TIME');f.advance();const before=f.counts();assert.equal(zero.execute(drafts,f.core,f.ctx,f.actor,action,meta).automation_data.run.status,'WAITING_TIME');assert.deepEqual(f.counts(),before);
});
