'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{fixture}=require('../zero-evaluation/fixture'),{fixture:client}=require('../zero-evaluation/workflow-run-client-fixture');
test('actual ZERO run client reconciles a lost committed HTTP request through server restart and verifies its native literal effects once',async()=>{
 const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-run-ack-drop')});try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('run.client.owner',['ADMIN']),workflow=(await f.request('/api/automation/workflows','POST',{name:'Private HTTP run review',trigger:{type:'custom_event',automatic:false},actions:[{type:'create_document',title:'Private HTTP literal title',content:'Exact first line\nExact second line'}],approval_required:false},owner.cookie)).body,realm=(await f.request('/api/automation/workflows','GET',undefined,owner.cookie)).body.request_context;let lose=true;const conversation=crypto.randomUUID(),bodies=[];
  const zeroRequestOverride=async(action,turn)=>{const body={message:'Explicit client run operation',conversation_id:conversation,turn_id:turn,client_context:{automation_action:action},preferred_module:'automation'},headers=lose&&action.operation==='RUN_SUBMIT'?{'x-workflow-run-drop-reply':'isolated-http-fixture'}:{};if(action.operation==='RUN_SUBMIT'){bodies.push(body);lose=false;}const result=await f.request('/api/zero/turn','POST',body,owner.cookie,headers);if(result.status!==200)throw Object.assign(Error('HTTP run request rejected'),{status:result.status,code:result.body.code});return result.body.automation_data;};
  const requestOverride=async(route,options)=>{const result=await f.request(route,options.method,JSON.parse(options.body),owner.cookie);if(result.status!==200)throw Object.assign(Error('HTTP recovery rejected'),{status:result.status,code:result.body.code});return result.body;};
  const c=client({workflow,requestContext:realm,zeroRequestOverride,requestOverride,payload:{event:{event_id:'run_client_http',event_version:1},options:{inputs:{literal:'Private exact request'}}}});await c.prepare().fire('click');assert.equal(c.confirm().disabled,false);assert.ok(c.review().textContent.includes(workflow.actions[0].content));assert.equal((await f.request('/api/automation/documents')).body.total,0);c.reason().value='Reviewed native literal effect';await c.confirm().fire('click');assert.equal(c.notice().textContent,c.i.t('workflow.run.unconfirmed'));assert.equal(c.prepare().disabled,true);assert.equal((await f.request('/api/automation/documents')).body.total,1);
  await f.stop();await f.start();owner.cookie=await f.login(owner);c.reason().value='Unreviewed change';c.payload.event.event_id='changed_input';await c.confirm().fire('click');assert.equal(bodies.length,1);assert.equal(c.requests.length,1);assert.equal(JSON.parse(c.requests[0].options.body).request_id,bodies[0].client_context.automation_action.input.request_id);assert.equal(c.prepare().disabled,false);const runs=(await f.request('/api/automation/status')).body;assert.equal(runs.run_count,1);assert.ok(c.notice().textContent.includes(runs.runs[0].run_id));const docs=(await f.request('/api/automation/documents')).body;assert.equal(docs.total,1);assert.equal(docs.items[0].content,workflow.actions[0].content);assert.ok(!JSON.stringify((await f.request('/api/zero/conversation/'+conversation,'GET',undefined,owner.cookie)).body).includes('Exact first line'));
 }finally{await f.close();}
});
