'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workflow-run-client-fixture'),{locales}=require('../foundly-i18n');
async function submit(f){await f.prepare().fire('click');f.reason().value='Private exact confirmation reason';await f.confirm().fire('click');}
const fresh=f=>fixture({core:f.core,drafts:f.drafts,workflow:f.workflow,storage:f.storage});
test('a fresh run control recovers only metadata and never resumes a due waiting run',async()=>{
 const f=fixture({actions:[{type:'delay',seconds:1},{type:'create_document',title:'Private after delay',content:'Private effect content'}]});f.lose('RUN_SUBMIT');await submit(f);assert.equal(f.storage.size,1);const text=[...f.storage.values()].join('');for(const literal of ['Private exact confirmation reason','Private effect content','Private after delay','Literal <img> parameter'])assert.ok(!text.includes(literal));f.retire();f.advance();const before=f.counts(),g=fresh(f);assert.ok(g.recover());assert.equal(g.prepare().disabled,true);g.payload.event.event_id='new unsaved input';await g.recover().fire('click');assert.equal(g.calls.length,0);assert.equal(g.requests.length,1);assert.equal(g.storage.size,0);assert.deepEqual(f.counts(),before);assert.equal(f.core.bucket(f.ctx,'automation_runs')[0].status,'WAITING_TIME');assert.equal(g.payload.event.event_id,'new unsaved input');assert.equal(g.prepare().disabled,false);
});
test('same-view uncertainty reconciles the original request reference without resubmitting changed private input',async()=>{
 const f=fixture({actions:[{type:'delay',seconds:1},{type:'create_task',title:'Do not resume'}]});f.lose('RUN_SUBMIT');await submit(f);const action=f.calls.at(-1).action;assert.ok(action.input.request_id);f.advance();f.payload.event.event_id='changed';f.reason().value='Changed reason';await f.confirm().fire('click');assert.equal(f.calls.filter(c=>c.action.operation==='RUN_SUBMIT').length,1);assert.equal(f.requests.length,1);assert.equal(JSON.parse(f.requests[0].options.body).request_id,action.input.request_id);assert.equal(f.counts().effects,0);assert.equal(f.storage.size,0);
});
test('an absent request is durably closed in a fresh view, including against the retained delayed original body',async()=>{
 const f=fixture();f.dropBefore();await submit(f);assert.equal(f.storage.size,1);const original=f.calls.at(-1);f.retire();const g=fresh(f);await g.recover().fire('click');assert.equal(g.notice().textContent,g.i.t('workflow.run.recovery_not_applied'));assert.equal(g.storage.size,0);const zero=require('../workflow-zero');assert.throws(()=>zero.execute(f.drafts,f.core,f.ctx,f.actor,original.action,{message:'Delayed original submission',conversation_id:'same-request',turn_id:original.turn}),e=>e.code==='automation_run_request_abandoned');assert.equal(f.counts().effects,0);assert.equal(f.core.bucket(f.ctx,'automation_runs').length,0);
});
test('unavailable or corrupt browser metadata prevents dispatch and a confirmed native outcome survives metadata cleanup failure',async()=>{
 const f=fixture();await f.prepare().fire('click');f.reason().value='Exact reason';f.failStorage();await f.confirm().fire('click');assert.equal(f.calls.filter(c=>c.action.operation==='RUN_SUBMIT').length,0);assert.equal(f.counts().effects,0);assert.equal(f.notice().textContent,f.i.t('workflow.run.storage_required'));
 const g=fixture();await g.prepare().fire('click');g.reason().value='Exact reason';g.alter((r,op)=>{if(op==='RUN_SUBMIT')g.failStorage();return r;});await g.confirm().fire('click');assert.ok(g.notice().textContent.includes(g.core.bucket(g.ctx,'automation_runs')[0].run_id));assert.ok(g.notice().textContent.includes(g.i.t('workflow.run.confirmed_metadata')));assert.equal(g.storage.size,1);assert.equal(g.counts().effects,2);
});
test('forged recovery identity, state, flags or private run binding cannot clear the original reference',async()=>{
 for(const change of [r=>r.request_id='other-request',r=>r.request_context.actor_id='other-actor',r=>r.state='NOT_APPLIED',r=>r.execution_performed=true,r=>r.outcome_reverified=true,r=>r.run.inputs.flag=false]){const f=fixture();f.lose('RUN_SUBMIT');await submit(f);f.retire();const g=fresh(f);g.alter((r,op)=>{if(op==='RUN_RECOVER')change(r);return r;});await g.recover().fire('click');assert.equal(g.storage.size,1);assert.equal(g.prepare().disabled,true);assert.ok(!g.notice().textContent.includes(f.core.bucket(f.ctx,'automation_runs')[0].run_id));}
});
test('recovery controls preserve locale, request identity and current-view ownership across denial and late replies',async()=>{
 const f=fixture();f.lose('RUN_SUBMIT');await submit(f);f.retire();const g=fresh(f),button=g.recover();for(const locale of locales){g.i.setLocale(locale);assert.equal(button.textContent,g.i.t('workflow.run.recover'));assert.equal(g.calls.length,0);assert.equal(g.requests.length,0);assert.equal(g.i.missingKeys().length,0);}g.deny(403);await button.fire('click');assert.equal(g.notice().textContent,g.i.t('common.access_denied'));assert.equal(g.storage.size,1);g.deny(0);const release=g.hold('RUN_RECOVER'),pending=button.fire('click');await release.started;const count=g.requests.length;await button.fire('click');assert.equal(g.requests.length,count);g.retire();const notice=g.notice().textContent;release();await pending;assert.equal(g.notice().textContent,notice);assert.equal(g.storage.size,1);assert.equal(g.calls.length,0);
});
test('corrupt scoped references fail closed while another actor scope neither displays nor erases them',async()=>{
 const f=fixture();f.lose('RUN_SUBMIT');await submit(f);f.retire();const other=fixture({core:f.core,drafts:f.drafts,workflow:f.workflow,storage:f.storage,requestContext:{...f.ctx,actor_id:'other-actor'}});assert.equal(other.recover(),undefined);assert.equal(other.prepare().disabled,false);assert.equal(f.storage.size,1);const key=[...f.storage.keys()][0];f.storage.set(key,'[{"request_id":"incomplete"}]');const g=fresh(f);assert.equal(g.prepare().disabled,true);assert.equal(g.notice().textContent,g.i.t('workflow.run.storage_required'));await g.prepare().fire('click');assert.equal(g.calls.length,0);assert.equal(g.requests.length,0);assert.equal(f.storage.size,1);
});
test('even a native 4xx after a partial effect retains attribution until separate reconciliation proves the current run',async()=>{
 const f=fixture();f.alter((r,op)=>{if(op==='RUN_SUBMIT')throw Object.assign(Error('Rejected after native effect'),{status:409});return r;});await submit(f);assert.equal(f.counts().effects,2);assert.equal(f.storage.size,1);assert.equal(f.prepare().disabled,true);f.alter(null);await f.confirm().fire('click');assert.equal(f.requests.length,1);assert.equal(f.calls.filter(c=>c.action.operation==='RUN_SUBMIT').length,1);assert.equal(f.counts().effects,2);assert.equal(f.storage.size,0);assert.equal(f.prepare().disabled,false);
});
test('a missing retained run remains explicitly unavailable and does not block separately reviewed future input',async()=>{
 const f=fixture();f.lose('RUN_SUBMIT');await submit(f);f.retire();f.core.bucket(f.ctx,'automation_runs').length=0;const g=fresh(f),before=f.counts();await g.recover().fire('click');assert.equal(g.notice().textContent,g.i.t('workflow.run.recovery_unavailable'));assert.equal(g.storage.size,0);assert.equal(g.prepare().disabled,false);assert.deepEqual(f.counts(),before);assert.equal(g.calls.length,0);
});
