'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workflow-manual-fixture'),{locales}=require('../foundly-i18n');
test('manual retry after a lost reply does not resume a due waiting run',async()=>{const f=fixture();f.lose();await f.submit();assert.equal(f.core.automationStatus(f.ctx,f.actor).runs[0].status,'WAITING_TIME');f.advance();await f.retry();assert.equal(f.core.automationStatus(f.ctx,f.actor).runs[0].status,'WAITING_TIME');assert.equal(f.effects(),0);});
test('uncertain manual input cannot be replaced by a new reference or edited reason',async()=>{const f=fixture({actions:[{type:'create_document',title:'Private exact title',content:'Private exact content'}]});f.lose();await f.submit();assert.equal(f.effects(),1);f.reference().value='different_private_reference';if(f.native())f.native().all().find(n=>n.tag==='input').value='Different reason';await f.retry();assert.equal(f.effects(),1);assert.equal(f.core.automationStatus(f.ctx,f.actor).run_count,1);});
test('fresh manual controls reconcile only scoped metadata and keep newer input unchanged',async()=>{const f=fixture();f.lose();await f.submit();assert.equal(f.storage.size,1);const stored=JSON.stringify([...f.storage]);for(const secret of ['Private manual title','Private line one','Explicit private reviewed reason'])assert.ok(!stored.includes(secret));f.retire();const fresh=fixture({core:f.core,workflow:f.workflow,storage:f.storage});fresh.reference().value='new_unsent_input';const recover=fresh.control('recover');assert.ok(recover);await recover.fire('click');assert.equal(fresh.calls.length,1);assert.equal(fresh.calls[0].route,'/api/automation/run-requests/recover');assert.equal(fresh.storage.size,0);assert.equal(fresh.reference().value,'new_unsent_input');assert.equal(fresh.form.inert,false);assert.equal(f.effects(),0);});
test('manual confirmation rejects contradictory native success and keeps the recovery reference',async()=>{const f=fixture();f.alter((result,route)=>{if(route.endsWith('/run-confirmation'))result.run.status='SUCCEEDED';return result;});await f.submit();assert.equal(f.storage.size,1);assert.ok(!f.native().textContent.includes('SUCCEEDED'));f.alter(null);await f.retry();assert.equal(f.storage.size,0);assert.equal(f.effects(),0);});
test('manual controls preserve input and literal review through all eight locale changes without requests',async()=>{const f=fixture();f.reference().value='literal_manual_event';await f.control('prepare').fire('click');const count=f.calls.length,reference=f.reference(),native=f.native(),review=native.all().find(n=>n.tag==='pre');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.reference(),reference);assert.equal(reference.value,'literal_manual_event');assert.ok(review.textContent.includes('Private line one\nPrivate line two'));assert.equal(f.i.missingKeys().length,0);}assert.equal(f.calls.length,count);});
test('manual controls fail before dispatch when recovery storage is unavailable',async()=>{const f=fixture();f.failStorage();await f.submit();assert.equal(f.effects(),0);assert.equal(f.core.automationStatus(f.ctx,f.actor).run_count,0);assert.ok(!f.calls.some(x=>x.route.endsWith('/run-confirmation')));});
test('retired manual confirmation and late preview cannot dispatch or restore controls',async()=>{const f=fixture();const release=f.hold(),pending=f.control('prepare').fire('click');await release.started;f.retire();const shown=f.native().textContent;release();await pending;assert.equal(f.native().textContent,shown);await f.control('confirm').fire('click');assert.equal(f.calls.length,1);assert.equal(f.effects(),0);});

test('an uncertain native run blocks a competing ZERO confirmation and a denied recovery never restores private success',async()=>{const f=fixture();f.lose();await f.submit();const zero=f.card.all().find(n=>n.getAttribute?.('data-workflow-run-mode')==='zero'),prepare=zero.all().find(n=>n.getAttribute?.('data-workflow-run-action')==='prepare'),before=f.calls.length;await prepare.fire('click');assert.equal(f.calls.length,before);f.deny();await f.retry();assert.equal(f.storage.size,1);assert.ok(!f.native().textContent.includes('Private native title'));assert.equal(f.effects(),0);});
