'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workspace-page-fixture'),{locales}=require('../foundly-i18n');
test('shared workspace metrics and drilldowns update all locales in place with exact money and literal source labels',async()=>{
 const f=fixture();await f.ui.loadWorkspaceData();const card=f.nodes.dashboardGrid.children[0],count=f.nodes.dashboardGrid.children[1],before=f.calls.length,serialized=JSON.stringify(f.snapshot);f.ui.openMetricDrilldown(f.dashboard.dashboard.widgets[0],f.snapshot.metrics.money);
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.calls.length,before);assert.equal(f.nodes.dashboardGrid.children[0],card);assert.ok(card.textContent.includes(f.i.currencyCents(-123,'USD')));assert.ok(count.textContent.includes(f.i.number(1234)));assert.equal(card.getAttribute('aria-label'),f.i.t('workspace.page.open_metric',{label:'Literal money label'}));assert.ok(f.nodes.metricDialogContent.textContent.includes(f.i.t('workspace.page.observed_utc')));assert.ok(f.nodes.metricDialogContent.textContent.includes(f.i.currencyCents(-123,'USD')));assert.ok(f.nodes.metricDialogContent.textContent.includes('Literal private source'));assert.equal(JSON.stringify(f.snapshot),serialized);assert.equal(f.i.missingKeys().length,0);}
});
test('workspace records retain source text and control identity while localizing exact cents, UTC dates and counts',async()=>{
 const f=fixture();f.snapshot.rows[0].name='Records <img> literal customer';await f.ui.loadWorkspaceData();f.nodes.recordSearch.value='Unsubmitted literal search';const row=f.nodes.recordRows.children[0],calls=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.recordRows.children[0],row);assert.ok(row.textContent.includes('Records <img> literal customer'));assert.equal(row.querySelector('img'),null);assert.ok(row.textContent.includes(f.i.currencyCents(-123,'USD')));assert.ok(row.textContent.includes(f.i.date(f.snapshot.rows[0].updated_at,{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'})));assert.equal(f.nodes.recordSearch.value,'Unsubmitted literal search');assert.equal(f.nodes.recordCount.textContent,f.i.t('workspace.page.records_count',{shown:'1',total:'1'}));assert.equal(f.calls.length,calls);}
});
test('source registry and workspace coverage keep unknowns distinct from zero and preserve filter selection across locales',async()=>{
 const f=fixture();f.snapshot.sources=[{source_id:'zero',display_name:'Literal zero',records_available:0,provenance_supported:false,categories:[]},{source_id:'absent',display_name:'Literal absent',categories:[]}];await f.ui.loadWorkspaceData();await f.ui.reloadRegistries();const card=f.nodes.sourceMatrix.children[0],unknown=f.nodes.sourceMatrix.children[1],registry=f.nodes.sourceRegistryGrid.children[0],calls=f.calls.length;f.nodes.sourceFilter.value='literal_source_selection';
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.sourceMatrix.children[0],card);assert.ok(card.textContent.includes(f.i.t('workspace.page.provenance_absent')));assert.ok(card.textContent.includes(f.i.t('workspace.page.source_summary',{categories:f.i.t('workspace.page.uncategorized'),count:'0',provenance:f.i.t('workspace.page.provenance_absent')})));assert.ok(unknown.textContent.includes(f.i.t('common.unknown')));assert.ok(!unknown.textContent.includes(f.i.t('workspace.page.provenance_present')));assert.ok(registry.textContent.includes(f.i.number(1234)));assert.equal(f.nodes.sourceFilter.value,'literal_source_selection');assert.equal(f.calls.length,calls);assert.equal(f.i.missingKeys().length,0);}
});
test('connector observations localize owned states and counts without mutating provider names or reloading sources',async()=>{
 const f=fixture();await f.ui.loadWorkspaceData();await f.ui.reloadRegistries();const card=f.nodes.connectorGrid.children[0],calls=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.connectorGrid.children[0],card);assert.ok(card.textContent.includes('Literal private connector'));assert.ok(card.textContent.includes('Literal provider'));assert.ok(card.textContent.includes(f.i.t('analysis.page.state.connected')));assert.ok(card.textContent.includes(f.i.number(1234)));assert.ok(card.textContent.includes(f.i.t('workspace.page.configuration')));assert.ok(card.textContent.includes(f.i.t('common.unknown')));assert.equal(f.calls.length,calls);assert.equal(f.i.missingKeys().length,0);}
});
test('editing and pending ZERO drafts survive locale changes without new requests or manufactured answers',async()=>{
 const f=fixture();await f.ui.loadWorkspaceData();f.ui.toggleEditing(true);const old=f.nodes.dashboardGrid.children[0],calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.dashboardGrid.children[0],old);assert.equal(f.nodes.editDashboard.textContent,f.i.t('workspace.page.editing_close'));assert.equal(f.calls.length,calls);}
 f.nodes.zeroInput.value='Original draft';const release=f.hold('/api/zero/turn'),pending=f.ui.askZero({preventDefault(){}});await release.started;const asked=f.calls.length;f.nodes.zeroInput.value='Later draft';for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.zeroInput.value,'Later draft');assert.equal(f.nodes.zeroOutput.textContent,f.i.t('workspace.page.zero_busy'));assert.equal(f.calls.length,asked);}release();await pending;assert.equal(f.nodes.zeroInput.value,'Later draft');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.zeroOutput.textContent,'Literal private ZERO answer');}
});
test('retired observation errors localize without retaining raw errors, private titles or successful runtime claims',async()=>{
 const f=fixture();await f.ui.loadWorkspaceData();await f.ui.reloadRegistries();f.deny();await assert.rejects(f.ui.loadWorkspaceData());const calls=f.calls.length;
 for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.workspaceNotice.textContent,f.i.t('common.access_denied'));assert.equal(f.nodes.workspaceRuntime.textContent,f.i.t('workspace.page.runtime_unavailable'));assert.equal(f.nodes.workspaceTitle.textContent,f.i.t('common.unknown'));assert.equal(f.context.document.title,'Foundly OS');assert.ok(!Object.values(f.nodes).some(n=>n.textContent.includes('RAW_PRIVATE')));assert.equal(f.calls.length,calls);}
});
test('missing row observations are unavailable and not represented as a successful empty collection',async()=>{
 const f=fixture();delete f.snapshot.rows;await f.ui.loadWorkspaceData();for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.recordCount.textContent,f.i.t('workspace.page.records_unavailable'));assert.equal(f.nodes.recordEmpty.textContent,f.i.t('workspace.page.records_unavailable'));}
});
test('fresh export uses current source rows and quotes formula-shaped source strings without converting amounts',async()=>{
 const f=fixture();await f.ui.loadWorkspaceData();f.snapshot.rows=[{name:'=PRIVATE_LITERAL_FORMULA()',amount_cents:-123,currency:'USD'}];await f.ui.exportRows();assert.equal(f.downloads.length,1);const csv=f.downloads[0].parts[0];assert.ok(csv.includes('"\'=PRIVATE_LITERAL_FORMULA()"'));assert.ok(csv.includes('"-123"'));assert.ok(!csv.includes('Literal private record'));
});
test('a late export observation cannot release records after another current read denies access',async()=>{
 const f=fixture();await f.ui.loadWorkspaceData();const release=f.hold('/api/workspaces/data/snapshot'),pending=f.ui.exportRows();await release.started;f.deny();await assert.rejects(f.ui.reloadRegistries());release();await pending;assert.equal(f.downloads.length,0);
});
