'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workflow-editor-fixture'),{locales}=require('../foundly-i18n');
const nativeRequest=f=>async(route,options)=>{const body=JSON.parse(options.body);return route.endsWith('/writes/recover')?f.drafts.recoverWrite(f.ctx,f.actor,route.split('/').at(-3),body):f.drafts.save(f.ctx,f.actor,route.split('/').at(-1),body);};
async function lost(){const f=fixture();f.valid();await f.button('Concept nu bewaren').fire('click');f.field('Workflownaam').value='Private edit after the initial draft';await f.box.fire('input');f.lose('DRAFT');await f.button('Concept nu bewaren').fire('click');assert.equal(f.records()[0].revision,2);return f;}
test('a fresh editor recovers an uncertain native update from scoped metadata without resending or storing private draft content',async()=>{
 const f=await lost(),metadata=[...f.storage.values()].join('');assert.ok(metadata.includes('request_id'));assert.ok(!metadata.includes('Private edit'));assert.ok(!metadata.includes('Literal <script>'));f.retire();const g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});assert.ok(g.recover());const count=f.counts();await g.recover().fire('click');assert.equal(g.calls.length,1);assert.equal(g.calls[0].operation,'RECOVER');assert.equal(g.recovered[0].draft.name,'Private edit after the initial draft');assert.equal(g.recovered[0].revision,2);assert.equal(f.storage.size,0);assert.deepEqual(f.counts(),count);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);
});
test('reload recovery closes an uncommitted initial draft request, rejects its delayed original body and never calls the saved-draft handler',async()=>{
 const f=fixture({requestOverride:async()=>{throw Error('RAW_FAILURE_BEFORE_NATIVE_WRITE');}});f.valid();await f.button('Concept nu bewaren').fire('click');assert.equal(f.storage.size,1);const original=f.calls[0];f.retire();const g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});await g.recover().fire('click');assert.equal(g.recovered.length,0);assert.equal(f.records().length,0);assert.equal(f.storage.size,0);assert.throws(()=>f.drafts.save(f.ctx,f.actor,original.route.split('/').at(-1),JSON.parse(original.options.body)),{code:'workflow_draft_write_abandoned'});for(const locale of locales){g.i.setLocale(locale);assert.ok(g.box.textContent.includes(g.i.t('workflow.editor.recovery_not_applied')));assert.equal(g.i.missingKeys().length,0);}
});
test('malformed or unavailable browser metadata blocks new native writes without discarding private form input',async()=>{
 const f=fixture();f.valid();f.failStorage();await f.button('Concept nu bewaren').fire('click');assert.equal(f.calls.length,0);assert.equal(f.records().length,0);assert.equal(f.field('Workflownaam').value,'Literal <img> editor');assert.equal(f.notice().textContent,f.i.t('workflow.generator.storage_required'));
 const known=await lost(),key=[...known.storage.keys()][0];known.storage.set(key,'[{"unexpected":"data"}]');const g=fixture({storage:known.storage});g.valid();await g.box.fire('submit');assert.equal(g.calls.length,0);assert.equal(g.notice().textContent,g.i.t('workflow.generator.storage_required'));
});
test('forged or retired recovery replies preserve the scoped pending reference and never release a private record',async()=>{
 for(const change of [r=>r.request_id='other',r=>r.request_context.actor_id='other',r=>r.request_fingerprint='a'.repeat(64),r=>r.record.revision=99,r=>r.record.draft.name='Unattributed private replacement']){const f=await lost(),g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});g.alter((r,op)=>{if(op==='RECOVER')change(r);return r;});await g.recover().fire('click');assert.equal(g.recovered.length,0);assert.equal(f.storage.size,1);assert.equal(g.recover().disabled,false);}
 const f=await lost(),g=fixture({storage:f.storage,requestOverride:nativeRequest(f)}),release=g.hold('RECOVER'),pending=g.recover().fire('click');await release.started;g.retire();release();await pending;assert.equal(g.recovered.length,0);assert.equal(f.storage.size,1);
});
test('current recovery denial is safely localized and another actor cannot see the first actor pending metadata',async()=>{
 const f=await lost(),g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});g.deny(403);await g.recover().fire('click');for(const locale of locales){g.i.setLocale(locale);assert.ok(g.box.textContent.includes(g.i.t('common.access_denied')));assert.ok(!g.box.textContent.includes('RAW_PRIVATE_DENIAL'));}assert.equal(f.storage.size,1);assert.equal(g.recovered.length,0);const other=fixture({storage:f.storage,requestContext:{...f.ctx,actor_id:'another_actor'}});assert.equal(other.recover(),undefined);assert.equal(other.calls.length,0);assert.equal(f.storage.size,1);
});
test('an uncertain ZERO editor update uses the same metadata-only native recovery after a fresh view',async()=>{
 const f=fixture();f.valid();await f.button('Concept met ZERO voorbereiden').fire('click');f.field('Reden om dit concept via ZERO te bewaren').value='Private confirmation reason';f.lose('SAVE');await f.button('Bevestig concept bewaren via ZERO').fire('click');assert.equal(f.storage.size,1);assert.ok(![...f.storage.values()].join('').includes('Private confirmation reason'));assert.equal(f.records()[0].revision,2);const count=f.counts(),g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});await g.recover().fire('click');assert.equal(g.recovered[0].revision,2);assert.equal(g.calls.length,1);assert.equal(g.calls[0].operation,'RECOVER');assert.deepEqual(f.counts(),count);assert.equal(f.storage.size,0);
});
test('definitive invalid draft input clears its recovery metadata and can be corrected without a trapped retry',async()=>{
 const f=fixture();f.valid();f.field('Vergelijkingswaarde').value='x'.repeat(12001);await f.button('Concept nu bewaren').fire('click');assert.equal(f.records().length,0);assert.equal(f.storage.size,0);assert.equal(f.notice().textContent,f.i.t('workflow.editor.validation'));f.field('Vergelijkingswaarde').value='Corrected partial condition';await f.button('Concept nu bewaren').fire('click');assert.equal(f.records().length,1);assert.equal(f.records()[0].revision,1);assert.equal(f.storage.size,0);
});
test('a newer native revision is not released as the old request outcome and does not block an independent draft',async()=>{
 const f=await lost(),row=f.records()[0];f.drafts.save(f.ctx,f.actor,row.id,{draft:{...row.draft,name:'Newer independently saved draft'},expected_revision:row.revision});const g=fixture({storage:f.storage,requestOverride:nativeRequest(f)});await g.recover().fire('click');assert.equal(g.recovered.length,0);assert.equal(f.storage.size,0);assert.ok(g.box.textContent.includes(g.i.t('workflow.editor.recovery_changed')));g.valid();await g.button('Concept nu bewaren').fire('click');assert.equal(f.records().length,2);assert.equal(f.records().find(r=>r.id===row.id).draft.name,'Newer independently saved draft');
});
test('failed local reference removal preserves the confirmed recovery outcome without confusing closed and saved requests',async()=>{
 for(const applied of [true,false]){const f=applied?await lost():fixture({requestOverride:async()=>{throw Error('Fixture before-write loss');}});if(!applied){f.valid();await f.button('Concept nu bewaren').fire('click');}const g=fixture({storage:f.storage,requestOverride:nativeRequest(f)}),release=g.hold('RECOVER'),pending=g.recover().fire('click');await release.started;g.failStorage();release();await pending;assert.equal(g.recovered.length,applied?1:0);assert.equal(f.storage.size,1);assert.equal(g.recover().disabled,true);for(const locale of locales){g.i.setLocale(locale);assert.equal(g.box.all().filter(n=>n.tag==='output').at(-1).textContent,g.i.t('workflow.editor.recovery_metadata'));}}
});
