'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{FoundlyPlatformCore}=require('../platform-core');
function fixture(){let rows=new Map(),disk,broken=false,effects=0,clock=Date.parse('2026-01-01T00:00:00Z');const ctx={tenant_id:'approval-request',dealer_id:'default'},actor={id:'owner',roles:['ADMIN']},adapter={now:()=>new Date(clock),bucket(c,s){const key=JSON.stringify([c,s]);if(!rows.has(key))rows.set(key,[]);return rows.get(key);},persist(){if(broken)throw Object.assign(Error('Isolated persistence failure'),{code:'EIO'});disk=JSON.stringify([...rows]);},executeAutomationAction(){effects++;return {executed:true};}};let core=new FoundlyPlatformCore(adapter);const workflow=core.defineAutomation(ctx,actor,{name:'Exact approval',trigger:'custom_event',approval_required:true,actions:[{type:'create_task',title:'First'},{type:'delay',seconds:1},{type:'create_task',title:'Second'}]}),event={event_id:'approval_event',event_version:1},run=core.runAutomation(ctx,actor,workflow.id,event,{inputs:{literal:'Private approval input'}}),input={run_id:run.run_id,request_signature:run.request_signature,reference:'approval_exact_reference',reason:'Private exact approval reason'};assert.equal(run.status,'AWAITING_APPROVAL');return {get core(){return core;},ctx,actor,workflow,event,run,input,send:(value=input,principal=actor)=>core.runAutomation(ctx,principal,workflow.id,event,{inputs:run.inputs,approval:value}),effects:()=>effects,advance:()=>clock+=2000,fail:value=>broken=value,restart(){rows=new Map(JSON.parse(disk));core=new FoundlyPlatformCore(adapter);},current:()=>core.automationStatus(ctx,actor).runs[0]};}
test('replaying an exact legacy approval never resumes its now-due waiting run',()=>{const f=fixture();assert.equal(f.send().status,'WAITING_TIME');assert.equal(f.effects(),1);f.advance();assert.equal(f.send().status,'WAITING_TIME');assert.equal(f.effects(),1);});
test('an approval identity cannot replace its original confirmation reason after uncertainty',()=>{const f=fixture();f.send();f.advance();assert.throws(()=>f.send({...f.input,reason:'Changed confirmation reason'}),{code:'automation_approval_request_conflict'});assert.equal(f.effects(),1);});
test('approval replay rechecks approval permission even when a prior run has completed',()=>{const f=fixture();f.send();f.advance();f.core.runAutomation(f.ctx,f.actor,f.workflow.id,f.event,{inputs:f.run.inputs});assert.equal(f.current().status,'SUCCEEDED');assert.throws(()=>f.send(f.input,{id:f.actor.id,roles:['MANAGER'],permissions:['automation:manage']}),{code:'automation_approval_forbidden'});});
test('approval receipt and grant roll back together before effects when persistence fails',()=>{const f=fixture();f.fail(true);assert.throws(()=>f.send(),{code:'EIO'});f.fail(false);assert.equal(f.current().status,'AWAITING_APPROVAL');assert.equal(f.current().approval,null);assert.equal(f.effects(),0);assert.equal(f.send().status,'WAITING_TIME');});
test('approval replay survives a durable restart without executing another step',()=>{const f=fixture(),first=f.send();assert.ok(first.approval_acknowledgement);f.restart();f.advance();const replay=f.send();assert.deepEqual(replay.approval_acknowledgement,first.approval_acknowledgement);assert.equal(replay.status,'WAITING_TIME');assert.equal(f.effects(),1);});

function metadata(f){return {request_id:f.input.reference,request_fingerprint:require('node:crypto').createHash('sha256').update(JSON.stringify(f.input)).digest('hex'),workflow_id:f.workflow.id,run_id:f.run.run_id,request_signature:f.run.request_signature,step_index:0,run_actor_id:f.run.actor_id,confirm:true};}
test('closing an absent approval reference durably rejects delayed legacy approval without changing the waiting step',()=>{const f=fixture(),meta=metadata(f),closed=f.core.recoverAutomationApprovalRequest(f.ctx,f.actor,meta);assert.equal(closed.state,'NOT_APPLIED');assert.equal(closed.run,null);assert.equal(f.current().status,'AWAITING_APPROVAL');assert.throws(()=>f.send(),{code:'automation_approval_request_abandoned'});f.restart();assert.deepEqual(f.core.recoverAutomationApprovalRequest(f.ctx,f.actor,meta),closed);assert.throws(()=>f.send(),{code:'automation_approval_request_abandoned'});assert.equal(f.effects(),0);});
test('failed approval retirement leaves the exact original request executable and successful recovery delivers no additional events',()=>{const f=fixture(),meta=metadata(f);f.fail(true);assert.throws(()=>f.core.recoverAutomationApprovalRequest(f.ctx,f.actor,meta),{code:'EIO'});f.fail(false);f.send();const events=JSON.stringify(f.core.bucket(f.ctx,'raw_events')),before=f.effects();f.advance();const recovered=f.core.recoverAutomationApprovalRequest(f.ctx,f.actor,meta);assert.equal(recovered.state,'APPLIED');assert.equal(recovered.approval_performed,false);assert.equal(recovered.execution_performed,false);assert.equal(recovered.run.status,'WAITING_TIME');assert.equal(f.effects(),before);assert.equal(JSON.stringify(f.core.bucket(f.ctx,'raw_events')),events);});
test('approval recovery rejects a forged step, wrong owner and corrupted durable grant',()=>{const f=fixture(),meta=metadata(f);f.send();for(const changed of [{...meta,step_index:1},{...meta,run_actor_id:'other-owner'},{...meta,request_signature:'a'.repeat(64)}])assert.throws(()=>f.core.recoverAutomationApprovalRequest(f.ctx,f.actor,changed),{code:'automation_approval_request_conflict'});const row=f.core.bucket(f.ctx,'automation_approval_requests')[0];row.approval_digest='0'.repeat(64);assert.throws(()=>f.core.recoverAutomationApprovalRequest(f.ctx,f.actor,meta),{code:'automation_approval_request_unverifiable'});assert.equal(f.effects(),1);});
