'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),crypto=require('node:crypto');
const {fixture}=require('../zero-evaluation/fixture'),{fixture:client}=require('../zero-evaluation/workflow-approval-fixture');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function setup(f,cookie=null,id='approval-http-event'){
  const w=await f.request('/api/automation/workflows','POST',{name:'Private HTTP approval',trigger:'custom_event',approval_required:true,actions:[{type:'create_document',title:'First approved title',content:'Private approved line one\nPrivate approved line two'},{type:'delay',seconds:1},{type:'create_document',title:'Second approved title',content:'Second private content'}]},cookie);assert.equal(w.status,201);
  const r=await f.request('/api/automation/workflows/'+w.body.id+'/runs','POST',{event:{event_id:id,event_version:1},options:{inputs:{private:'Private approval input'}}},cookie);assert.equal(r.status,202);assert.equal(r.body.status,'AWAITING_APPROVAL');return {workflow:w.body,run:r.body};
}
async function review(f,workflow,run,cookie=null){const p=await f.request('/api/automation/runs/'+run.run_id+'/approval-preview','GET',undefined,cookie);assert.equal(p.status,200);const approval={run_id:run.run_id,request_signature:run.request_signature,reference:crypto.randomUUID(),reason:'Explicit private HTTP approval',step_index:p.body.step.index,preview_fingerprint:p.body.preview_fingerprint};return {body:{event:run.trigger,options:{inputs:run.inputs,approval}},meta:{request_id:approval.reference,request_fingerprint:hash(approval),workflow_id:workflow.id,run_id:run.run_id,request_signature:run.request_signature,step_index:p.body.step.index,run_actor_id:run.actor_id,confirm:true}};}
test('actual shared approval controls recover a lost native HTTP reply after encrypted restart without advancing the due next step',async()=>{
  const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-approval-ack-drop')});try{
    assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('approval.http.owner',['ADMIN']),{workflow,run}=await setup(f,owner.cookie),realm=(await f.request('/api/automation/runs','GET',undefined,owner.cookie)).body.request_context;
    let drop=true;const transport=async(route,options)=>{const headers=drop&&route.endsWith('/runs')&&options.method==='POST'?{'x-workflow-approval-drop-reply':'isolated-http-fixture'}:{};if(headers['x-workflow-approval-drop-reply'])drop=false;const r=await f.request(route,options.method||'GET',options.body?JSON.parse(options.body):undefined,owner.cookie,headers);if(![200,202].includes(r.status))throw Object.assign(Error('HTTP approval rejected'),{status:r.status,code:r.body.code});return r.body;};
    const first=client({workflow,run,ctx:{tenant_id:realm.tenant_id,dealer_id:realm.dealer_id},actor:{id:realm.actor_id,roles:['ADMIN']}});first.transport=transport;await first.render('APPROVALS');await first.approve();assert.equal(first.storage.size,1);assert.equal((await f.request('/api/automation/documents')).body.total,1);const waiting=(await f.request('/api/automation/status')).body.runs[0];assert.equal(waiting.status,'WAITING_TIME');first.retire();await f.stop();await f.start();owner.cookie=await f.login(owner);const due=Date.parse(waiting.next_wakeup_at);assert.ok(Number.isFinite(due)&&due-Date.now()<=1000);while(Date.now()<due)await new Promise(resolve=>setTimeout(resolve,due-Date.now()));
    const fresh=client({workflow,run,ctx:{tenant_id:realm.tenant_id,dealer_id:realm.dealer_id},actor:{id:realm.actor_id,roles:['ADMIN']},storage:first.storage});fresh.transport=transport;await fresh.render('APPROVALS');assert.equal(fresh.control('prepare'),undefined);assert.ok(fresh.control('recover'));await fresh.control('recover').fire('click');assert.equal(fresh.storage.size,0);assert.equal((await f.request('/api/automation/status')).body.runs[0].status,'WAITING_TIME');assert.equal((await f.request('/api/automation/documents')).body.total,1);const resumed=await f.request('/api/automation/workflows/'+workflow.id+'/runs','POST',{event:run.trigger,options:{inputs:run.inputs}},owner.cookie);assert.equal(resumed.body.status,'SUCCEEDED');const documents=(await f.request('/api/automation/documents')).body;assert.equal(documents.total,2);assert.equal(documents.items.filter(row=>row.content==='Private approved line one\nPrivate approved line two').length,1);assert.ok(!fs.readFileSync(path.join(f.dir,'foundly-core-state.json'),'utf8').includes('Private approved line one'));
  }finally{await f.close();}
});
test('native approval terminal retirement blocks a held original body and remains closed after encrypted restart',async()=>{
  const f=await fixture();let held;try{
    assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const {workflow,run}=await setup(f),r=await review(f,workflow,run),route='/api/automation/workflows/'+workflow.id+'/runs',payload=JSON.stringify(r.body);
    const pending=new Promise((resolve,reject)=>{held=http.request(f.base+route,{method:'POST',headers:{authorization:'Bearer '+f.env.FOUNDLY_ADMIN_TOKEN,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload)}},res=>{let value='';res.on('data',part=>value+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(value)}));});held.on('error',reject);held.write(payload.slice(0,-1));});const closed=await f.request('/api/automation/approval-requests/recover','POST',r.meta);assert.equal(closed.status,200);assert.equal(closed.body.state,'NOT_APPLIED');held.end(payload.slice(-1));const late=await pending;assert.equal(late.status,409);assert.equal(late.body.code,'automation_approval_request_abandoned');await f.stop();await f.start();assert.deepEqual((await f.request('/api/automation/approval-requests/recover','POST',r.meta)).body,closed.body);assert.equal((await f.request(route,'POST',r.body)).status,409);assert.equal((await f.request('/api/automation/documents')).body.total,0);assert.equal((await f.request('/api/automation/status')).body.runs[0].status,'AWAITING_APPROVAL');assert.ok(!JSON.stringify((await f.request('/api/module/data/data')).body).includes(r.meta.request_id));
  }finally{held?.destroy();await f.close();}
});
test('native approval grant and receipt roll back on EIO and approval authority is revalidated after a held authenticated body',async()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'approval-http-integrity-')),fault=path.join(dir,'fault'),barrier=path.join(dir,'body'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/identity-persistence-fault')+' --require '+require.resolve('../test-identity-body-barrier'),FOUNDLY_IDENTITY_FAIL_FILE:fault,FOUNDLY_IDENTITY_BODY_BARRIER:barrier});let held;try{
    assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('approval.current.owner',['ADMIN']),{workflow,run}=await setup(f,owner.cookie),r=await review(f,workflow,run,owner.cookie),route='/api/automation/workflows/'+workflow.id+'/runs';fs.writeFileSync(fault,'fail');try{assert.equal((await f.request(route,'POST',r.body,owner.cookie)).status,500);}finally{fs.rmSync(fault,{force:true});}const current=(await f.request('/api/automation/status')).body.runs[0];assert.equal(current.status,'AWAITING_APPROVAL');assert.equal(current.approval,null);assert.equal((await f.request('/api/automation/documents')).body.total,0);assert.equal((await f.request('/api/automation/approval-requests/recover','POST',r.meta,owner.cookie)).body.state,'NOT_APPLIED');
    const next=await review(f,workflow,run,owner.cookie),payload=JSON.stringify(next.body),pending=new Promise((resolve,reject)=>{held=http.request(f.base+route,{method:'POST',headers:{cookie:owner.cookie,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload),'x-identity-fixture-barrier':'body'}},res=>{let text='';res.on('data',part=>text+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}));});held.on('error',reject);held.write(payload.slice(0,-1));});for(let n=0;n<100&&!fs.existsSync(barrier);n++)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(barrier));assert.equal((await f.request('/api/identity/users/'+owner.member.id,'PUT',{roles:['MANAGER'],expected_revision:owner.member.revision,confirm:true,reason:'Remove approval authority during held request'})).status,200);held.end(payload.slice(-1));assert.equal((await pending).status,401);owner.cookie=await f.login(owner);assert.equal((await f.request(route,'POST',next.body,owner.cookie)).status,403);assert.equal((await f.request('/api/automation/approval-requests/recover','POST',next.meta,owner.cookie)).status,403);assert.equal((await f.request('/api/automation/documents')).body.total,0);
  }finally{held?.destroy();fs.rmSync(fault,{force:true});await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
