'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),{fixture}=require('../zero-evaluation/fixture'),{fixture:client}=require('../zero-evaluation/workflow-run-client-fixture');
const route='/api/automation/run-requests/recover',hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex'),turn=action=>({message:'Explicit isolated run request',conversation_id:crypto.randomUUID(),turn_id:crypto.randomUUID(),preferred_module:'automation',client_context:{automation_action:action}});
async function setup(f,cookie=null){const definition={name:'Private HTTP request recovery',trigger:{type:'custom_event',automatic:false},actions:[{type:'delay',seconds:1},{type:'create_document',title:'Private delayed title',content:'Private first line\nPrivate second line'}],approval_required:false};const result=await f.request('/api/automation/workflows','POST',definition,cookie);assert.equal(result.status,201);const workflow=result.body,realm=(await f.request('/api/automation/workflows','GET',undefined,cookie)).body.request_context;return {workflow,realm};}
async function reviewed(f,workflow,event_id,cookie=null){const input={event:{event_id,event_version:1},inputs:{literal:'Private run input'}},preview=(await f.request('/api/zero/turn','POST',turn({operation:'RUN_PREVIEW',workflow_id:workflow.id,input}),cookie)).body.automation_data;assert.ok(preview);const action={operation:'RUN_SUBMIT',workflow_id:workflow.id,input:{...input,preview_fingerprint:preview.preview_fingerprint,confirm:true,reason:'Private exact reviewed reason',request_id:crypto.randomUUID()}},meta={request_id:action.input.request_id,request_fingerprint:hash(action.input),workflow_id:workflow.id,event_id,workflow_signature:workflow.signature,request_signature:preview.request_signature,confirm:true};return {action,meta,body:turn(action)};}
test('actual fresh ZERO control reconciles a lost waiting-run HTTP reply after encrypted restart without executing a due step',async()=>{
 const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-run-ack-drop')});try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('run.reload.owner',['ADMIN']),{workflow,realm}=await setup(f,owner.cookie);let drop=true;const zeroRequestOverride=async(action,turn_id)=>{const body={...turn(action),conversation_id:'run-reload-conversation',turn_id},headers=drop&&action.operation==='RUN_SUBMIT'?{'x-workflow-run-drop-reply':'isolated-http-fixture'}:{};if(action.operation==='RUN_SUBMIT')drop=false;const result=await f.request('/api/zero/turn','POST',body,owner.cookie,headers);if(result.status!==200)throw Object.assign(Error('HTTP request rejected'),{status:result.status,code:result.body.code});return result.body.automation_data;},requestOverride=async(url,options)=>{const result=await f.request(url,options.method,JSON.parse(options.body),owner.cookie);if(result.status!==200)throw Object.assign(Error('HTTP recovery rejected'),{status:result.status,code:result.body.code});return result.body;};
  const first=client({workflow,requestContext:realm,zeroRequestOverride,requestOverride});await first.prepare().fire('click');first.reason().value='Private exact reviewed reason';await first.confirm().fire('click');assert.equal(first.storage.size,1);const metadata=JSON.parse([...first.storage.values()][0])[0],waiting=(await f.request('/api/automation/status')).body.runs[0];assert.equal(waiting.status,'WAITING_TIME');assert.equal((await f.request('/api/automation/documents')).body.total,0);first.retire();await f.stop();await f.start();owner.cookie=await f.login(owner);
  // A fast encrypted restart may finish before the one-second delay is due.
  // Reach the persisted boundary explicitly; recovery must still not execute it.
  const dueAt=Date.parse(waiting.next_wakeup_at);
  assert.ok(Number.isFinite(dueAt));
  assert.ok(dueAt-Date.now()<=1000,'Fixture delay must remain bounded to one second');
  while(Date.now()<dueAt)await new Promise(resolve=>setTimeout(resolve,dueAt-Date.now()));
  assert.ok(Date.now()>=dueAt);const fresh=client({workflow,requestContext:realm,zeroRequestOverride,requestOverride,storage:first.storage});await fresh.recover().fire('click');assert.equal(fresh.calls.length,0);assert.equal(fresh.requests.length,1);assert.equal(fresh.storage.size,0);assert.ok(fresh.notice().textContent.includes(waiting.run_id));assert.equal((await f.request('/api/automation/status')).body.runs[0].status,'WAITING_TIME');assert.equal((await f.request('/api/automation/documents')).body.total,0);assert.ok(!JSON.stringify((await f.request('/api/module/data/data')).body).includes(metadata.request_id));assert.ok(!fs.readFileSync(path.join(f.dir,'foundly-core-state.json'),'utf8').includes(metadata.request_id));
  const resumed=await f.request('/api/automation/workflows/'+workflow.id+'/runs','POST',{event:waiting.trigger,options:{inputs:waiting.inputs}},owner.cookie);assert.equal(resumed.status,202);assert.equal(resumed.body.status,'SUCCEEDED');assert.equal((await f.request('/api/automation/documents')).body.total,1);
 }finally{await f.close();}
});
test('real HTTP terminal closure and initial reservation roll back on EIO and a held ZERO body cannot start after durable closure or restart',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'run-request-eio-')),marker=path.join(dir,'fail'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/identity-persistence-fault'),FOUNDLY_IDENTITY_FAIL_FILE:marker});let held;try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const {workflow}=await setup(f),first=await reviewed(f,workflow,'request-eio-reservation');fs.writeFileSync(marker,'fail');try{const rejected=await f.request('/api/automation/workflows/'+workflow.id+'/runs','POST',{event:first.action.input.event,options:{inputs:first.action.input.inputs,request_id:first.meta.request_id,request_fingerprint:first.meta.request_fingerprint}});assert.equal(rejected.status,500);}finally{fs.rmSync(marker,{force:true});}assert.equal((await f.request('/api/automation/status')).body.run_count,0);assert.equal((await f.request(route,'POST',first.meta)).body.state,'NOT_APPLIED');
  const second=await reviewed(f,workflow,'request-eio-closure');fs.writeFileSync(marker,'fail');try{assert.equal((await f.request(route,'POST',second.meta)).status,500);}finally{fs.rmSync(marker,{force:true});}assert.equal((await f.request('/api/zero/turn','POST',second.body)).body.automation_data.run.status,'WAITING_TIME');
  const third=await reviewed(f,workflow,'request-delayed-body'),payload=JSON.stringify(third.body),pending=new Promise((resolve,reject)=>{held=http.request(f.base+'/api/zero/turn',{method:'POST',headers:{authorization:'Bearer '+f.env.FOUNDLY_ADMIN_TOKEN,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload)}},res=>{let value='';res.on('data',part=>value+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(value)}));});held.on('error',reject);held.write(payload.slice(0,-1));});const closed=await f.request(route,'POST',third.meta);assert.equal(closed.status,200);assert.equal(closed.body.state,'NOT_APPLIED');held.end(payload.slice(-1));const late=await pending;assert.equal(late.status,409);assert.equal(late.body.code,'automation_run_request_abandoned');await f.stop();await f.start();assert.deepEqual((await f.request(route,'POST',third.meta)).body,closed.body);assert.equal((await f.request('/api/zero/turn','POST',third.body)).status,409);assert.equal((await f.request('/api/automation/status')).body.run_count,1);assert.equal((await f.request('/api/automation/documents')).body.total,0);
 }finally{held?.destroy();fs.rmSync(marker,{force:true});await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('run request recovery enforces current workflow/run capabilities and actor authority after authenticated body waits',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'run-request-access-')),marker=path.join(dir,'body'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../test-identity-body-barrier'),FOUNDLY_IDENTITY_BODY_BARRIER:marker});let held;try{
  assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('run.recovery.owner',['ADMIN']),other=await f.enroll('run.recovery.other',['ADMIN']),{workflow}=await setup(f,owner.cookie),review=await reviewed(f,workflow,'request-current-access',owner.cookie);assert.equal((await f.request('/api/zero/turn','POST',review.body,owner.cookie)).status,200);const foreign=await f.request(route,'POST',review.meta,other.cookie);assert.equal(foreign.body.state,'NOT_APPLIED');assert.equal(foreign.body.run,null);
  async function delayed(change){fs.rmSync(marker,{force:true});const payload=JSON.stringify(review.meta),pending=new Promise((resolve,reject)=>{held=http.request(f.base+route,{method:'POST',headers:{cookie:owner.cookie,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload),'x-identity-fixture-barrier':'body'}},res=>{let value='';res.on('data',part=>value+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(value)}));});held.on('error',reject);held.write(payload.slice(0,-1));});for(let n=0;n<100&&!fs.existsSync(marker);n++)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(marker));await change();held.end(payload.slice(-1));return pending;}
  const disabled=await delayed(async()=>{assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],capability_flags:{'automation:runs':false},expected_revision:1})).status,200);});assert.equal(disabled.status,403);assert.ok(!JSON.stringify(disabled.body).includes(workflow.name));assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],capability_flags:{'automation:runs':true},expected_revision:2})).status,200);const revoked=await delayed(async()=>{assert.equal((await f.request('/api/identity/users/'+owner.member.id,'PUT',{roles:['VIEWER'],expected_revision:owner.member.revision,confirm:true,reason:'Revoke run reconciliation authority during body wait'})).status,200);});assert.equal(revoked.status,401);owner.cookie=await f.login(owner);assert.equal((await f.request(route,'POST',review.meta,owner.cookie)).status,403);assert.equal((await f.request('/api/automation/documents')).body.total,0);
 }finally{held?.destroy();await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
