'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workflow-run-client-fixture'),{locales}=require('../foundly-i18n');
async function prepare(f){await f.prepare().fire('click');f.reason().value='Private reviewed execution reason';}
test('ZERO run review contains the complete literal definition and localized controls without changing the reviewed input or dispatching effects',async()=>{
 const f=fixture(),before=f.counts();await prepare(f);const reason=f.reason(),calls=f.calls.length;assert.ok(f.review().textContent.includes(f.workflow.actions[0].content));assert.ok(f.review().textContent.includes(f.workflow.actions[1].message));for(const locale of locales){f.i.setLocale(locale);assert.equal(f.prepare().textContent,f.i.t('workflow.run.prepare'));assert.equal(f.confirm().textContent,f.i.t('workflow.run.confirm'));assert.equal(f.reason(),reason);assert.equal(reason.value,'Private reviewed execution reason');assert.ok(f.review().textContent.includes('Literal <img> parameter'));assert.ok(f.review().textContent.includes(f.i.number(1234)));assert.equal(f.i.missingKeys().length,0);}assert.equal(f.calls.length,calls);assert.deepEqual(f.counts(),before);assert.equal(f.box.querySelector('script'),null);
});
test('a mismatched native workflow, request, definition or step projection cannot enable explicit run confirmation',async()=>{
 for(const change of [r=>r.workflow_signature='a'.repeat(64),r=>r.workflow_version=2,r=>r.request_signature='a'.repeat(64),r=>r.inputs.flag=false,r=>r.event.event_id='other_event',r=>r.steps[0].index=99,r=>r.steps[0].condition_matched='true']){const f=fixture();f.alter((r,op)=>{if(op==='RUN_PREVIEW')change(r);return r;});await prepare(f);assert.equal(f.confirm().disabled,true);assert.equal(f.counts().effects,0);assert.equal(f.review().textContent,'');}
});
test('an uncertain native run freezes one exact action and turn while blocking a new preparation or changed confirmation reason',async()=>{
 const f=fixture();await prepare(f);f.lose('RUN_SUBMIT');await f.confirm().fire('click');const original=f.calls.at(-1),effects=f.counts().effects,count=f.calls.length;assert.ok(effects>0);assert.equal(f.host.inert,true);assert.equal(f.reason().disabled,true);assert.equal(f.prepare().disabled,true);await f.prepare().fire('click');assert.equal(f.calls.length,count);f.reason().value='Changed unreviewed reason';f.payload.event.event_id='changed_unreviewed_event';await f.confirm().fire('click');assert.deepEqual(f.calls.at(-1),original);assert.equal(f.counts().effects,effects);assert.equal(f.core.bucket(f.ctx,'automation_runs').length,1);
});
test('native run acknowledgement must bind reviewed workflow, event, signature, actor and realm before confirmed feedback',async()=>{
 for(const change of [r=>r.run.automation_id='other_workflow',r=>r.run.event_id='other_event',r=>r.run.request_signature='a'.repeat(64),r=>r.run.actor_id='other_actor',r=>r.run.tenant_id='other_tenant',r=>r.run.status='INVENTED_SUCCESS']){const f=fixture();await prepare(f);f.alter((r,op)=>{if(op==='RUN_SUBMIT')change(r);return r;});await f.confirm().fire('click');assert.equal(f.notice().textContent,f.i.t('workflow.run.unconfirmed'));assert.equal(f.confirm().disabled,false);const effects=f.counts().effects;f.alter(null);await f.confirm().fire('click');assert.equal(f.counts().effects,effects);assert.equal(f.core.bucket(f.ctx,'automation_runs').length,1);}
});
test('run denial and transport diagnostics use owned current-locale feedback without private provider text',async()=>{
 for(const status of [403,0]){const f=fixture();if(status)f.deny(status);else f.lose('RUN_PREVIEW');await f.prepare().fire('click');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.notice().textContent,f.i.t(status?'common.access_denied':'workflow.run.failed'));assert.ok(!f.box.textContent.includes('RAW_PRIVATE_RUN'));}assert.equal(f.counts().effects,0);}
});
test('a substituted executed action, step identity or contradictory success cannot confirm the reviewed run',async()=>{
 for(const change of [r=>r.run.steps[0].input.content='Substituted action',r=>r.run.steps[0].idempotency_key='different-effect',r=>r.run.steps=[],r=>r.run.steps[0].status='FAILED',r=>r.run.steps[0].status='SKIPPED_CONDITION']){const f=fixture();await prepare(f);f.alter((r,op)=>{if(op==='RUN_SUBMIT')change(r);return r;});await f.confirm().fire('click');assert.equal(f.notice().textContent,f.i.t('workflow.run.unconfirmed'));assert.equal(f.prepare().disabled,true);assert.equal(f.core.bucket(f.ctx,'automation_runs').length,1);}
});
