'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{WorkflowDrafts,SCOPE}=require('../workflow-drafts'),{CapabilityResolver}=require('../capability-resolver');
const WRITES='platform:automation_draft_writes',hash=input=>crypto.createHash('sha256').update(JSON.stringify(input)).digest('hex'),input=(name,revision=1,key='write_1')=>({draft:{name,steps:[]},expected_revision:revision,request_id:key}),review=body=>({expected_revision:body.expected_revision,request_id:body.request_id,request_fingerprint:hash(body),confirm:true});
function fixture(){let rows=new Map(),fail=false,writes=0;const ctx={tenant_id:'draft-write-recovery-fixture',dealer_id:'default'},actor={id:'write-owner',roles:['ADMIN','SUPER_ADMIN']},adapter={bucket(c,s){const k=JSON.stringify([c,s]);if(!rows.has(k))rows.set(k,[]);return rows.get(k);},persist(){if(fail)throw Object.assign(Error('Isolated write failure'),{code:'EIO'});writes++;},audit(c,a,action,entity,id,meta){adapter.bucket(c,'platform:audit').push({actor_id:a.id,action,entity,id,meta});}},resolver=new CapabilityResolver(adapter);resolver.configure(ctx,actor,{entitlements:['automation'],expected_revision:0});let drafts=new WorkflowDrafts(adapter,resolver);drafts.save(ctx,actor,'existing_draft',{draft:{name:'Private initial draft',steps:[]},expected_revision:0});adapter.bucket(ctx,WRITES);return {ctx,actor,adapter,resolver,get drafts(){return drafts;},restart(){rows=new Map(JSON.parse(JSON.stringify([...rows])));drafts=new WorkflowDrafts(adapter,resolver);},fail:value=>fail=value,writes:()=>writes};}
test('a keyed partial-draft update retains exact metadata-only recovery across native reconstruction without replaying private input',()=>{
 const f=fixture(),body=input('Private edited draft'),saved=f.drafts.save(f.ctx,f.actor,'existing_draft',body);assert.equal(saved.request_id,body.request_id);assert.equal(saved.request_fingerprint,hash(body));const before=f.writes();f.restart();const recovered=f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(body));assert.equal(recovered.state,'APPLIED');assert.deepEqual(recovered.record,saved.record);assert.equal(recovered.request_id,body.request_id);assert.equal(recovered.request_fingerprint,hash(body));assert.deepEqual(recovered.request_context,{...f.ctx,actor_id:f.actor.id});assert.equal(f.writes(),before);assert.equal(f.drafts.save(f.ctx,f.actor,'existing_draft',body).deduplicated,true);assert.equal(f.writes(),before);const journal=f.adapter.bucket(f.ctx,WRITES);assert.equal(journal.length,1);assert.ok(!JSON.stringify(journal).includes(body.draft.name));
});
test('terminal update recovery prevents the delayed original write but permits a separately identified edit at the same current revision',()=>{
 const f=fixture(),body=input('Absent update'),closed=f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(body));assert.equal(closed.state,'NOT_APPLIED');assert.equal(closed.record,null);f.restart();assert.deepEqual(f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(body)),closed);assert.throws(()=>f.drafts.save(f.ctx,f.actor,'existing_draft',body),{code:'workflow_draft_write_abandoned'});const next=f.drafts.save(f.ctx,f.actor,'existing_draft',input('Separate new edit',1,'write_2'));assert.equal(next.record.revision,2);assert.equal(next.record.draft.name,'Separate new edit');
});
test('draft revision, audit and keyed evidence commit or roll back together, including terminal closure persistence',()=>{
 const f=fixture(),body=input('Atomic private edit'),audit=f.adapter.bucket(f.ctx,'platform:audit').length;f.fail(true);assert.throws(()=>f.drafts.save(f.ctx,f.actor,'existing_draft',body),{code:'EIO'});f.fail(false);assert.equal(f.drafts.list(f.ctx,f.actor).items[0].revision,1);assert.equal(f.adapter.bucket(f.ctx,WRITES).length,0);assert.equal(f.adapter.bucket(f.ctx,'platform:audit').length,audit);f.fail(true);assert.throws(()=>f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(body)),{code:'EIO'});f.fail(false);assert.equal(f.adapter.bucket(f.ctx,WRITES).length,0);assert.equal(f.drafts.save(f.ctx,f.actor,'existing_draft',body).record.revision,2);assert.equal(f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(body)).state,'APPLIED');
});
test('a superseded or missing draft is never claimed as the earlier request outcome or restored by its old key',()=>{
 const f=fixture(),body=input('Original request');f.drafts.save(f.ctx,f.actor,'existing_draft',body);f.drafts.save(f.ctx,f.actor,'existing_draft',input('Newer request',2,'write_2'));assert.throws(()=>f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(body)),{code:'workflow_draft_write_superseded'});assert.throws(()=>f.drafts.save(f.ctx,f.actor,'existing_draft',body),{code:'workflow_draft_write_superseded'});const current=input('Newer request',2,'write_2');f.adapter.bucket(f.ctx,SCOPE).length=0;const before=f.writes();assert.throws(()=>f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(current)),{code:'workflow_draft_write_unavailable'});assert.throws(()=>f.drafts.save(f.ctx,f.actor,'existing_draft',current),{code:'workflow_draft_write_unavailable'});assert.equal(f.writes(),before);
});
test('request identity, draft, fingerprint, current owner and current capability bind private recovery',()=>{
 const f=fixture(),body=input('Owned edit');f.drafts.save(f.ctx,f.actor,'existing_draft',body);assert.throws(()=>f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',{...review(body),request_fingerprint:'a'.repeat(64)}),{code:'workflow_draft_write_conflict'});assert.throws(()=>f.drafts.save(f.ctx,f.actor,'other_draft',{...body,expected_revision:0}),{code:'workflow_draft_write_conflict'});assert.throws(()=>f.drafts.recoverWrite(f.ctx,{...f.actor,id:'other_owner'},'existing_draft',review(body)),{code:'workflow_draft_missing'});assert.throws(()=>f.drafts.recoverWrite(f.ctx,{...f.actor,roles:['VIEWER']},'existing_draft',review(body)),{statusCode:403});f.resolver.configure(f.ctx,f.actor,{entitlements:['automation'],capability_flags:{'automation:workflows':false},expected_revision:1});assert.throws(()=>f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(body)),{statusCode:403});
});
test('legacy writes stay compatible without fabricating an earlier keyed receipt, and invalid recovery metadata cannot close a request',()=>{
 const f=fixture(),legacy={draft:{name:'Private initial draft',steps:[]},expected_revision:0};assert.equal(f.drafts.save(f.ctx,f.actor,'existing_draft',legacy).deduplicated,true);const unknown={...legacy,request_id:'legacy_unknown'};assert.throws(()=>f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(unknown)),{code:'workflow_draft_write_unverifiable'});const body=input('Typed request');for(const change of [r=>r.confirm='true',r=>r.expected_revision='1',r=>r.request_id='',r=>r.request_fingerprint='bad',r=>r.draft={name:'Unneeded private content'}]){const data=review(body);change(data);assert.throws(()=>f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',data),{code:'workflow_draft_recovery_invalid'});}assert.equal(f.adapter.bucket(f.ctx,WRITES).length,0);
});
test('bounded write receipts preserve existing evidence and refuse new keyed effects before changing the draft',()=>{
 const f=fixture(),body=input('Retained keyed edit');f.drafts.save(f.ctx,f.actor,'existing_draft',body);const rows=f.adapter.bucket(f.ctx,WRITES);for(let n=rows.length;n<10000;n++)rows.push({request_id:'other_'+n,actor_id:'other'});const before=f.writes();assert.throws(()=>f.drafts.save(f.ctx,f.actor,'existing_draft',input('Capacity rejected',2,'new_write')),{code:'workflow_draft_write_capacity'});assert.equal(f.drafts.recoverWrite(f.ctx,f.actor,'existing_draft',review(body)).state,'APPLIED');assert.equal(f.drafts.save(f.ctx,f.actor,'existing_draft',body).record.revision,2);assert.equal(f.writes(),before);assert.equal(rows.length,10000);
});
