'use strict';
const {resume}=require('../zero-evaluation/workflow-resume-http');
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const {fixture}=require('../zero-evaluation/fixture'),{fixture:client}=require('../zero-evaluation/workflow-manual-fixture');
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function setup(f,cookie=null){
  const response=await f.request('/api/automation/workflows','POST',{name:'Private native manual review',trigger:{type:'custom_event',automatic:false},actions:[{type:'delay',seconds:1},{type:'create_document',title:'Private native title',content:'Private first line\nPrivate second line'}],approval_required:false},cookie);
  assert.equal(response.status,201);return response.body;
}
async function review(f,workflow,eventId,cookie=null){
  const input={event:{event_id:eventId,event_version:1},inputs:{literal:'Private native input'}},p=await f.request('/api/automation/workflows/'+workflow.id+'/run-preview','POST',input,cookie);assert.equal(p.status,200);
  const body={...input,preview_fingerprint:p.body.preview_fingerprint,confirm:true,reason:'Explicit private native confirmation',request_id:crypto.randomUUID()};
  return {body,meta:{request_id:body.request_id,request_fingerprint:hash(body),workflow_id:workflow.id,event_id:eventId,workflow_signature:workflow.signature,request_signature:p.body.request_signature,confirm:true}};
}
test('actual native manual controls recover a lost HTTP response after encrypted restart without resuming a due run',async()=>{
  const f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/workflow-run-ack-drop')});try{
    assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);
    const owner=await f.enroll('manual.http.owner',['ADMIN']),workflow=await setup(f,owner.cookie),realm=(await f.request('/api/automation/workflows','GET',undefined,owner.cookie)).body.request_context;
    let drop=true;const requestOverride=async(route,options)=>{const headers=drop&&route.endsWith('/run-confirmation')?{'x-workflow-run-drop-reply':'isolated-http-fixture'}:{};if(route.endsWith('/run-confirmation'))drop=false;const response=await f.request(route,options.method,JSON.parse(options.body),owner.cookie,headers);if(response.status!==200)throw Object.assign(Error('Native HTTP rejected'),{status:response.status,code:response.body.code});return response.body;};
    const first=client({workflow,realm,ctx:{tenant_id:realm.tenant_id,dealer_id:realm.dealer_id},actor:{id:realm.actor_id,roles:['ADMIN']},requestOverride});await first.submit();assert.equal(first.storage.size,1);assert.equal(first.calls.filter(c=>c.route.endsWith('/run-confirmation')).length,1);
    const run=(await f.request('/api/automation/status')).body.runs[0];assert.equal(run.status,'WAITING_TIME');assert.equal((await f.request('/api/automation/documents')).body.total,0);first.retire();await f.stop();await f.start();owner.cookie=await f.login(owner);
    const due=Date.parse(run.next_wakeup_at);assert.ok(Number.isFinite(due)&&due-Date.now()<=1000);while(Date.now()<due)await new Promise(resolve=>setTimeout(resolve,due-Date.now()));
    const fresh=client({workflow,realm,ctx:{tenant_id:realm.tenant_id,dealer_id:realm.dealer_id},actor:{id:realm.actor_id,roles:['ADMIN']},requestOverride,storage:first.storage});fresh.reference().value='New unsent reference';await fresh.control('recover').fire('click');assert.equal(fresh.calls.length,1);assert.equal(fresh.calls[0].route,'/api/automation/run-requests/recover');assert.equal(fresh.storage.size,0);assert.equal(fresh.reference().value,'New unsent reference');assert.equal((await f.request('/api/automation/status')).body.runs[0].status,'WAITING_TIME');assert.equal((await f.request('/api/automation/documents')).body.total,0);
    const resumed=await resume((route,method,body)=>f.request(route,method,body,owner.cookie),run);assert.equal(resumed.status,202);assert.equal(resumed.body.status,'SUCCEEDED');const documents=(await f.request('/api/automation/documents')).body;assert.equal(documents.total,1);assert.equal(documents.items[0].content,'Private first line\nPrivate second line');assert.ok(!fs.readFileSync(path.join(f.dir,'foundly-core-state.json'),'utf8').includes('Private native title'));
  }finally{await f.close();}
});
test('native manual confirmations bind the reviewed input and terminal closure rejects a held original body across restart',async()=>{
  const f=await fixture();let held;try{
    assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const workflow=await setup(f),route='/api/automation/workflows/'+workflow.id+'/run-confirmation',r=await review(f,workflow,'manual-held');
    for(const changed of [{...r.body,inputs:{literal:'changed'}},{...r.body,confirm:'true'},{...r.body,approval:{approved:true}},{...r.body,request_id:''}])assert.ok([409,422].includes((await f.request(route,'POST',changed)).status));assert.equal((await f.request('/api/automation/status')).body.run_count,0);
    const payload=JSON.stringify(r.body),pending=new Promise((resolve,reject)=>{held=http.request(f.base+route,{method:'POST',headers:{authorization:'Bearer '+f.env.FOUNDLY_ADMIN_TOKEN,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload)}},res=>{let text='';res.on('data',part=>text+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}));});held.on('error',reject);held.write(payload.slice(0,-1));});
    assert.equal((await f.request('/api/automation/run-requests/recover','POST',r.meta)).body.state,'NOT_APPLIED');held.end(payload.slice(-1));assert.equal((await pending).body.code,'automation_run_request_abandoned');await f.stop();await f.start();assert.equal((await f.request(route,'POST',r.body)).body.code,'automation_run_request_abandoned');assert.equal((await f.request('/api/automation/status')).body.run_count,0);assert.equal((await f.request('/api/automation/documents')).body.total,0);
  }finally{held?.destroy();await f.close();}
});
test('native manual HTTP reservation rolls back on storage failure and current capability is checked after the body wait',async()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'manual-integrity-')),fault=path.join(dir,'fault'),barrier=path.join(dir,'body'),f=await fixture({NODE_OPTIONS:'--require '+require.resolve('../zero-evaluation/identity-persistence-fault')+' --require '+require.resolve('../test-identity-body-barrier'),FOUNDLY_IDENTITY_FAIL_FILE:fault,FOUNDLY_IDENTITY_BODY_BARRIER:barrier});let held;try{
    assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],expected_revision:0})).status,200);const owner=await f.enroll('manual.current.owner',['ADMIN']),workflow=await setup(f,owner.cookie),route='/api/automation/workflows/'+workflow.id+'/run-confirmation',r=await review(f,workflow,'manual-eio',owner.cookie);
    fs.writeFileSync(fault,'fail');try{assert.equal((await f.request(route,'POST',r.body,owner.cookie)).status,500);}finally{fs.rmSync(fault,{force:true});}assert.equal((await f.request('/api/automation/status')).body.run_count,0);assert.equal((await f.request('/api/automation/run-requests/recover','POST',r.meta,owner.cookie)).body.state,'NOT_APPLIED');
    const next=await review(f,workflow,'manual-revoked',owner.cookie),payload=JSON.stringify(next.body),pending=new Promise((resolve,reject)=>{held=http.request(f.base+route,{method:'POST',headers:{cookie:owner.cookie,origin:f.env.FOUNDLY_PUBLIC_BASE_URL,'content-type':'application/json','content-length':Buffer.byteLength(payload),'x-identity-fixture-barrier':'body'}},res=>{let text='';res.on('data',part=>text+=part);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}));});held.on('error',reject);held.write(payload.slice(0,-1));});for(let n=0;n<100&&!fs.existsSync(barrier);n++)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(barrier));assert.equal((await f.request('/api/composition','PUT',{entitlements:['automation'],capability_flags:{'automation:runs':false},expected_revision:1})).status,200);held.end(payload.slice(-1));assert.equal((await pending).status,403);assert.equal((await f.request('/api/automation/documents')).body.total,0);
  }finally{held?.destroy();fs.rmSync(fault,{force:true});await f.close();fs.rmSync(dir,{recursive:true,force:true});}
});
