'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('../zero-evaluation/workflow-generator-fixture'),{locales}=require('../foundly-i18n');
async function prepared(f){f.prompt().value='Literal requested workflow';await f.prepare().fire('click');assert.equal(f.save().disabled,false,f.notice().textContent);f.reason().value='Reviewed literal branches';}
test('generator owned review copy follows all locales without changing literal proposals, inputs, requests or native state',async()=>{
 const f=fixture(),before=f.counts();await prepared(f);const input=f.prompt(),reason=f.reason(),calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);assert.equal(f.prepare().textContent,f.i.t('workflow.generator.prepare'));assert.equal(f.save().textContent,f.i.t('workflow.generator.save'));assert.ok(f.preview().textContent.includes(f.i.t('workflow.inspector.not')));assert.ok(f.preview().textContent.includes(f.i.number(1234)));assert.ok(f.preview().textContent.includes('Literal <script> title'));assert.equal(f.prompt(),input);assert.equal(f.reason(),reason);assert.equal(input.value,'Literal requested workflow');assert.equal(reason.value,'Reviewed literal branches');assert.equal(f.save().disabled,false);assert.equal(f.i.missingKeys().length,0);}assert.equal(f.calls.length,calls);assert.deepEqual(f.counts(),before);assert.equal(f.records().length,0);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);assert.ok(f.box.querySelector('script')===null);
});
test('a lost committed save locks the reviewed request and retries exactly the same body and turn despite input events and locales',async()=>{
 const f=fixture();await prepared(f);f.lose();await f.save().fire('click');const first=f.calls.at(-1),writes=f.counts().writes;assert.equal(f.records().length,1);assert.equal(f.reason().disabled,true);assert.equal(f.prompt().disabled,true);f.reason().value='Changed after uncertain commit';f.prompt().value='Changed draft';await f.prompt().fire('input');f.i.setLocale('fr-FR');assert.equal(f.save().disabled,false);await f.save().fire('click');assert.deepEqual(f.calls.at(-1),first);assert.equal(f.counts().writes,writes);assert.equal(f.saved.length,1);assert.equal(f.records().length,1);assert.equal(f.counts().effects,0);
});
test('typed native acknowledgement must match the reviewed draft and revision before claiming a saved private concept',async()=>{
 for(const mutate of [r=>r.record.revision=0,r=>r.record.revision=2,r=>r.record.request_revision=10,r=>r.record.status='PUBLISHED',r=>r.record.executable=true,r=>r.executable=true,r=>r.record.draft.steps[0].then_steps[0].values.title='UNREVIEWED REPLACEMENT']){const f=fixture();await prepared(f);f.alter((r,a)=>{if(a.operation==='SAVE')mutate(r);return r;});await f.save().fire('click');assert.equal(f.saved.length,0);assert.equal(f.save().disabled,false);assert.ok(!f.notice().textContent.includes(f.i.t('workflow.generator.saved')));f.alter(null);await f.save().fire('click');assert.equal(f.saved.length,1);assert.equal(f.records().length,1);assert.equal(f.counts().effects,0);}
});
test('provider and access failures use localized safe copy, clear proposal state and cannot trigger save',async()=>{
 const f=fixture();await prepared(f);f.deny();await f.prepare().fire('click');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.notice().textContent,f.i.t('common.access_denied'));assert.ok(!f.box.textContent.includes('RAW_PRIVATE_PROVIDER_FAILURE'));}assert.equal(f.preview().textContent,'');assert.equal(f.save().disabled,true);const calls=f.calls.length;await f.save().fire('click');assert.equal(f.calls.length,calls);
});
test('retired generator controls neither invoke ZERO nor release late private proposals or saved callbacks',async()=>{
 const f=fixture();await prepared(f);f.retire();const calls=f.calls.length;await f.prepare().fire('click');await f.save().fire('click');assert.equal(f.calls.length,calls);
 const g=fixture(),release=g.hold();g.prompt().value='Pending literal workflow';const pending=g.prepare().fire('click');await release.started;g.retire();release();await pending;assert.equal(g.preview().textContent,'');assert.equal(g.save().disabled,true);
 const h=fixture();await prepared(h);const finish=h.hold('SAVE'),saving=h.save().fire('click');await finish.started;h.retire();finish();await saving;assert.equal(h.saved.length,0);assert.equal(h.counts().effects,0);
});
test('malformed or contradictory clarification responses cannot become questions or a savable proposal',async()=>{
 for(const value of [{questions:'RAW_PRIVATE_STRING',inference:true,executable:false},{questions:[],inference:true,executable:false},{questions:['Literal question'],inference:false,executable:false},{questions:['Literal question'],inference:true,executable:true}]){const f=fixture();f.prompt().value='Workflow';f.alter(()=>value);await f.prepare().fire('click');assert.equal(f.notice().textContent,f.i.t('workflow.generator.invalid'));assert.equal(f.save().disabled,true);assert.ok(!f.box.textContent.includes('RAW_PRIVATE_STRING'));}
});
test('late generation uses the current locale but cannot restore a proposal after its description changes',async()=>{
 const f=fixture(),release=f.hold();f.prompt().value='Original literal request';const pending=f.prepare().fire('click');await release.started;f.i.setLocale('es-ES');release();await pending;assert.ok(f.preview().textContent.includes(f.i.t('workflow.trigger.custom_event')));assert.equal(f.notice().textContent,f.i.t('workflow.generator.review'));
 const finish=f.hold(),second=f.prepare().fire('click');await finish.started;f.prompt().value='New literal request';await f.prompt().fire('input');finish();await second;assert.equal(f.preview().textContent,'');assert.equal(f.save().disabled,true);assert.equal(f.notice().textContent,f.i.t('workflow.generator.changed'));assert.equal(f.records().length,0);
});
test('a pending save blocks duplicate save and generation while locale changes preserve the one native draft write',async()=>{
 const f=fixture();await prepared(f);const before=f.counts(),release=f.hold('SAVE'),pending=f.save().fire('click');await release.started;const calls=f.calls.length;for(const locale of locales){f.i.setLocale(locale);await f.save().fire('click');await f.prepare().fire('click');assert.equal(f.notice().textContent,f.i.t('workflow.generator.saving'));}assert.equal(f.calls.length,calls);release();await pending;assert.equal(f.saved.length,1);assert.equal(f.records().length,1);assert.equal(f.counts().writes,before.writes+1);assert.equal(f.counts().effects,0);assert.equal(f.core.automationStatus(f.ctx,f.actor).workflow_count,0);
});
test('an uncertain older save cannot overwrite a newer native draft revision or claim it as its own confirmation',async()=>{
 const f=fixture();await prepared(f);f.lose();await f.save().fire('click');const row=f.records()[0],newer=JSON.parse(JSON.stringify(row.draft));newer.name='Literal newer draft';f.drafts.save(f.ctx,f.actor,row.id,{expected_revision:row.revision,draft:newer});const before=f.counts();await f.save().fire('click');assert.equal(f.saved.length,0);assert.equal(f.records()[0].revision,2);assert.equal(f.records()[0].draft.name,newer.name);assert.deepEqual(f.counts(),before);assert.equal(f.preview().textContent,'');assert.equal(f.save().disabled,true);assert.equal(f.prepare().disabled,false);for(const locale of locales){f.i.setLocale(locale);assert.equal(f.notice().textContent,f.i.t('workflow.generator.conflict'));}
});
test('valid clarification questions remain literal text through every locale and cannot publish or save a workflow',async()=>{
 const f=fixture(),before=f.counts();f.provider(JSON.stringify({questions:['Literal <img> question?']}));f.prompt().value='Need a workflow';await f.prepare().fire('click');for(const locale of locales){f.i.setLocale(locale);assert.equal(f.notice().textContent,f.i.t('workflow.generator.questions',{questions:'Literal <img> question?'}));assert.equal(f.save().disabled,true);}assert.deepEqual(f.counts(),before);assert.equal(f.preview().textContent,'');assert.ok(f.box.querySelector('img')===null);
});
test('generation rejects mismatched IDs, definition, fingerprint and typed publication flags before review',async()=>{
 for(const mutate of [r=>r.draft_id='another_draft',r=>r.expected_revision='0',r=>r.preview_fingerprint='unverified',r=>r.definition.actions[0].title='Other proposal',r=>r.publication_required='true',r=>r.draft.automatic='false']){const f=fixture(),before=f.counts();f.alter(r=>{mutate(r);return r;});f.prompt().value='Literal workflow';await f.prepare().fire('click');assert.equal(f.notice().textContent,f.i.t('workflow.generator.invalid'));assert.equal(f.preview().textContent,'');assert.equal(f.save().disabled,true);assert.deepEqual(f.counts(),before);}
});
