'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {locales}=require('../foundly-i18n'),{fixture,ViewElement}=require('../zero-evaluation/zero-presentation-fixture');
test('parameterised text fragments preserve links, literal replacements and repeated native layouts',()=>{
  const f=fixture(),node=f.nodes.rich=new ViewElement(),link=new ViewElement('a');link.href='https://example.test/literal';link.textContent='Aanmelden <customer label>';
  node.append(link,f.context.document.createTextNode(' · '),f.context.document.createTextNode('1,234 records'));
  const params={count:1234};f.i.bindText(node,2,'common.record_count',params);params.count=5;
  for(const locale of locales){f.i.setLocale(locale);assert.equal(node.childNodes[0],link);assert.equal(link.textContent,'Aanmelden <customer label>');assert.equal(node.childNodes[2].textContent,f.i.t('common.record_count',{count:1234}));}
  const customer={nodeType:3,textContent:node.childNodes[2].textContent};node.childNodes[2]=customer;const literal=customer.textContent;f.i.setLocale('en-GB');assert.equal(customer.textContent,literal);
  f.i.renderText(node,'');node.append(link,f.context.document.createTextNode(' · '),f.context.document.createTextNode('0 records'));f.i.bindText(node,2,'common.record_count',{count:0});f.i.setLocale('de-DE');assert.equal(node.childNodes[2].textContent,'0 Datensätze');assert.equal(node.childNodes[0],link);assert.throws(()=>f.i.bindText(node,0,'common.save'),/text_node_required/);
});
test('actual ZERO results change eight locales in place while preserving native data, source URLs and per-source verification',()=>{
  const f=fixture(),literal='BRONNEN <img src=x onerror=example> {key: common.save}',j={ok:true,answer:literal,spoken_text:'Dansk svar til samtalen',voice_mode:'CONVERSATION',actions:[{type:literal,status:'executed'},{type:'private_action',status:'blocked',reason:literal}],syncs:[{id:'native_sync',ok:true,ingested:1234},{id:'unknown_sync',ok:true},{id:'zero_sync',ok:true,ingested:0},{id:'unverified_sync',ok:'true',ingested:20}],sources:[{url:'https://example.test/a?q=literal#keep',title:literal,source_kind:'external_provider',provider_verified:true},{url:'javascript:alert(1)',title:literal,source_kind:'web_research',provider_verified:'true'},{source_id:'literal-id',source_kind:'constructor'},{method:'unknown'}],web:{sources:[{title:'Literal web title',url:'https://example.test/web',source_kind:'web_research',provider_verified:false}]}};
  const original=JSON.stringify(j);f.context.showZeroResult(j);const grid=f.nodes.layerBody.children[0],answer=grid.children[0].children[1],sources=grid.children[1],firstRow=sources.children[1],link=firstRow.children[0],textNodes=[...answer.childNodes];
  assert.deepEqual(grid.children.map(node=>node.className),['card','card']);assert.equal(answer.className,'answer');assert.equal(answer.style.whiteSpace,'pre-wrap');assert.equal(f.nodes.layer.classList.contains('hidden'),false);
  for(const locale of locales){
    f.i.setLocale(locale);assert.equal(f.nodes.layerBody.children[0],grid);assert.equal(sources.children[1],firstRow);assert.equal(firstRow.children[0],link);assert.deepEqual(answer.childNodes,textNodes);
    assert.equal(f.nodes.layerTitle.textContent,f.i.t('zero.result.title'));assert.equal(f.nodes.layerSmall.textContent,'ZERO · '+f.i.t('zero.mode.conversation'));assert.equal(answer.textContent,f.context.formatCommandResult(j));assert.ok(answer.textContent.startsWith(literal));assert.ok(answer.textContent.includes(f.i.t('zero.result.actions')));assert.ok(answer.textContent.includes(f.i.t('zero.result.synced',{id:'native_sync',count:1234})));assert.ok(answer.textContent.includes(f.i.t('zero.result.synced',{id:'zero_sync',count:0})));assert.ok(answer.textContent.includes(f.i.t('zero.result.synced_unknown',{id:'unknown_sync'})));assert.ok(!answer.textContent.includes('unverified_sync'));
    assert.equal(link.href,j.sources[0].url);assert.equal(link.rel,'noopener noreferrer');assert.equal(link.target,'_blank');assert.equal(link.textContent,literal);assert.ok(firstRow.textContent.endsWith(f.i.t('zero.source.verified')));assert.equal(sources.children[2].children.length,0);assert.ok(sources.children[2].textContent.endsWith(f.i.t('zero.source.unverified')));assert.ok(sources.children[3].textContent.includes('constructor'));assert.ok(sources.children[4].textContent.startsWith(f.i.t('zero.result.unknown_source')));
    assert.equal(JSON.stringify(j),original);assert.equal(f.zero.preferences.language,'da-DK');assert.equal(f.context.spokenText(j),'Dansk svar til samtalen');assert.equal(f.requests.length,0);assert.equal(f.events.length,0);assert.equal(f.speeches.length,0);assert.equal(f.i.missingKeys().length,0);assert.equal(grid.all().some(node=>['img','script'].includes(node.tag)),false);
  }
  f.context.showZeroResult({...j,answer:'New literal answer'});const current=f.nodes.layerBody.children[0].children[0].children[1];f.i.setLocale('fr-FR');assert.ok(current.textContent.startsWith('New literal answer'));assert.ok(current.textContent.includes(f.i.t('zero.result.actions')));
});
test('blocked-only and empty results have neutral framing; business-shaped objects never become translation bindings',()=>{
  const f=fixture(),out=f.nodes.answer=new ViewElement();f.nodes.layer.classList.remove('hidden');const j={actions:[{status:'blocked'}],syncs:[{id:'count_string',ok:true,ingested:'0'}]};f.context.showZeroResult(j);
  for(const locale of locales){f.i.setLocale(locale);assert.equal(out,f.nodes.answer);assert.ok(out.textContent.startsWith(f.i.t('zero.result.no_answer')));assert.ok(out.textContent.includes(f.i.t('zero.result.actions')));assert.ok(out.textContent.includes(f.i.t('zero.result.blocked',{type:f.i.t('common.unknown'),reason:f.i.t('common.unknown')})));assert.ok(out.textContent.includes(f.i.t('zero.result.synced_unknown',{id:'count_string'})));assert.equal(f.nodes.layerBody.children.length,0);}
  f.context.showZeroResult({answer:{key:'common.save',params:{}}});f.i.setLocale('en-GB');assert.equal(out.textContent,'[object Object]');
  f.context.showZeroResult({answer:'Aanmelden'});f.i.setLocale('sv-SE');assert.equal(out.textContent,'Aanmelden');assert.equal(f.i.missingKeys().length,0);
});
test('all ZERO state labels and owned details update without emitting telemetry or changing audio state, canonical codes or conversation language',()=>{
  const f=fixture(),states=['STANDBY','ACTIVATING','LISTENING','THINKING','SEARCHING','PLANNING','WAITING_TOOL','EXECUTING','WAITING_CONFIRMATION','VERIFYING','SPEAKING','SUCCESS','WARNING','ERROR','RECOVERING','MUTED'];
  for(const state of states){
    f.context.setZeroState(state,f.i.message('zero.status.fallback_listening',{mode:f.i.message('zero.status.on_device')}));const counts=[f.events.length,f.audio.length,f.visual.length];
    for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.voiceState.textContent,f.i.t('zero.state.'+state.toLowerCase()));assert.equal(f.nodes.listenText.textContent,f.i.t('zero.status.fallback_listening',{mode:f.i.t('zero.status.on_device')}));assert.equal(f.zero.state,state);assert.equal(f.nodes.voicebar.dataset.state,state);assert.equal(f.nodes.mic.getAttribute('aria-pressed'),'true');assert.deepEqual([f.events.length,f.audio.length,f.visual.length],counts);assert.equal(f.zero.preferences.language,'da-DK');}
  }
  f.context.setZeroState('LISTENING','Luisteren…',{speech_started:true});assert.equal(f.events.filter(x=>x[0]==='SPEECH_STARTED').length,1);f.i.setLocale('fr-FR');assert.equal(f.nodes.listenText.textContent,'Luisteren…');assert.equal(f.events.filter(x=>x[0]==='SPEECH_STARTED').length,1);assert.equal(f.events.filter(x=>x[0]==='WEBRTC_CONNECTED').length,1);
  for(const [alias,state]of [['WAKE','ACTIVATING'],['UNDERSTANDING','THINKING'],['DONE','SUCCESS']]){f.context.setZeroState(alias);assert.equal(f.zero.state,state);assert.equal(f.nodes.voiceState.textContent,f.i.t('zero.state.'+state.toLowerCase()));}
  f.context.setZeroState('constructor');f.i.setLocale('de-DE');assert.equal(f.zero.state,'constructor');assert.equal(f.nodes.voiceState.textContent,'constructor');assert.equal(f.i.missingKeys().length,0);
});
test('native ZERO execution survives a locale change during the request with one canonical payload and unchanged spoken response',async()=>{
  const f=fixture(),out=f.nodes.answer=new ViewElement(),j={ok:true,status:'ok',answer:'Literal source-grounded answer',spoken_text:'Dansk talt svar',voice_mode:'CONVERSATION',ui_commands:[],actions:[{type:'native_action',status:'blocked',reason:'literal native reason'}]};f.nodes.layer.classList.remove('hidden');let release;f.context.fetch=async(path,options)=>{f.requests.push({path,options});return new Promise(resolve=>release=()=>resolve({ok:true,json:async()=>j}));};
  const pending=f.context.askModule('crm','Letterlijke opdracht');assert.equal(f.requests.length,1);assert.equal(out.textContent,f.i.t('zero.result.processing'));
  for(const locale of locales){f.i.setLocale(locale);assert.equal(out.textContent,f.i.t('zero.result.processing'));assert.equal(f.nodes.listenText.textContent,f.i.t('static.aff8ec2b'));assert.equal(f.requests.length,1);}
  release();await pending;const call=f.requests[0];assert.equal(call.path,'/api/zero/turn');const payload=JSON.parse(call.options.body);assert.equal(payload.message,'Letterlijke opdracht');assert.equal(payload.preferred_module,'native-crm');assert.equal(payload.conversation_id,'canonical-conversation');assert.equal(payload.turn_id,'canonical-turn');assert.deepEqual(f.refreshes,['status','events']);assert.equal(f.speeches.length,1);assert.equal(f.speeches[0][0],j);assert.equal(f.context.spokenText(j),'Dansk talt svar');assert.equal(f.nodes.listenText.textContent,f.i.t('zero.result.completed'));
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.requests.length,1);assert.equal(f.speeches.length,1);assert.equal(out.textContent,f.context.formatCommandResult(j));assert.equal(f.nodes.listenText.textContent,f.i.t('zero.result.completed'));assert.equal(f.zero.preferences.language,'da-DK');}
});
test('wake-listener status changes locale without starting recognition again or changing its native mode',()=>{
  const f=fixture();let starts=0;Object.assign(f.zero,{realtimeConnected:false,wakeAvailable:true,wakeMode:'on_device',conversationActive:true,wakeRecognition:{start(){starts++;}}});Object.assign(f.zero.preferences,{microphone_enabled:true,wake_enabled:true,clap_enabled:true});
  f.context.startWakeListener();assert.equal(starts,1);
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.listenText.textContent,f.i.t('zero.status.fallback_listening',{mode:f.i.t('zero.status.on_device')}));assert.equal(starts,1);assert.equal(f.zero.wakeMode,'on_device');assert.equal(f.zero.state,'LISTENING');}
  f.zero.wakeRunning=false;f.zero.wakeAvailable=false;f.context.startWakeListener();
  for(const locale of locales){f.i.setLocale(locale);assert.equal(f.nodes.listenText.textContent,f.i.t('zero.status.clap_standby'));assert.equal(starts,1);assert.equal(f.zero.state,'STANDBY');}
});
test('lost module responses show a translatable uncertain result without raw errors, automatic retry or synthetic speech',async()=>{
  const f=fixture(),out=f.nodes.answer=new ViewElement();f.context.renderCommandResult(out,{answer:'Previous sensitive result',actions:[{type:'old_action',status:'executed'}]});let fail;f.context.executeZeroTurn=()=>{f.requests.push('turn');return new Promise((_,reject)=>fail=()=>reject(Error('RAW_PROVIDER_DETAILS')));};const lost=f.context.askModule('crm','Literal request');assert.equal(out.textContent,f.i.t('zero.result.processing'));fail();await lost;
  for(const locale of locales){f.i.setLocale(locale);assert.equal(out.textContent,f.i.t('zero.result.unavailable'));assert.equal(f.requests.length,1);assert.equal(f.speeches.length,0);assert.ok(!out.textContent.includes('RAW_PROVIDER_DETAILS'));}
  let release;f.context.executeZeroTurn=()=>new Promise(resolve=>release=resolve);const pending=f.context.askModule('crm','Second request'),replacement=f.nodes.answer=new ViewElement();replacement.textContent='New module content';release({answer:'Stale result'});await pending;assert.equal(replacement.textContent,'New module content');
});
test('owned result fragments preserve leading and trailing source whitespace through repeated locale changes',()=>{
  const f=fixture(),out=f.nodes.answer=new ViewElement(),j={answer:'Literal answer',actions:[{type:'  native_action',status:'blocked',reason:'  Literal reason\t '}]};
  f.context.renderCommandResult(out,j);
  for(const locale of [...locales,...locales]){f.i.setLocale(locale);assert.equal(out.textContent,f.context.formatCommandResult(j));}
  const node=f.nodes.fragment=new ViewElement();node.append(f.context.document.createTextNode('1,234 records'));f.i.bindText(node,0,'common.record_count',{count:1234});
  f.i.renderText(node,'Fresh layout');node.setAttribute('data-i18n-text','{"0":"common.record_count"}');assert.throws(()=>f.i.translate(node),/plural_count_required/,'A new layout cannot borrow a previous result count');
});
